### ISSUE TITLE
Heritages inside non-core Compendiums have no Traits according to the sytem.

### ISSUE THREAD

**Issue by Teraunce** [foundryvtt/pf2e#10045]
Reproduction Steps: 

1. Install PF2e Extended
2. Modify Chosen of Lamashtu feat to search for Bugbear: ```{
  "choices": {
    "filter": [
      "item:ancestry:bugbear"
    ],
    "itemType": "heritage"
  },
  "flag": "heritage",
  "key": "ChoiceSet",
  "prompt": "Choose a Heritage"
}```
3. Try and apply the modified feat to a character.
4. Watch the feat pull up no Heritages.
5. Import the PF2e Extended Heritages Compendium into the table.
6. Repeat step 3.
7. Watch it pull up Heritages from the Imported Material. 
-----------------------------------------------------------------------------------------------------------------------------------
Bonus Bug: If none of a Ancestries' Heritages have the Ancestry in the trait bar they are unfindable by trait searching. The second one of them has the Ancestry trait in the trait bar they will all be found.

**Comment by stwlam** [comment]
It doesn't appear you're searching by trait there.

**Comment by stwlam** [comment]
I'm also not able to find "PF2e Extended." Is it a listed module?

**Comment by stwlam** [comment]
I remembered there is a PF2e Expansion Pack and saw it has a bugbear ancestry. The reason why it only works if imported is because the module's heritages have old data, and importing the module's compendiums migrates its contents. There's nothing we can do there except ask the author to update their module.
