### ISSUE TITLE
FR Party sheet Multiple select and sell for half in stash

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#10121]
what would be cool is if you could click a button that opens up the inventory on the stash part of the party sheet and you could click tick boxes for multiple selections and then click a button to sell for half. so you can sell multiple items faster and get the correct return. the sell button could also include a percentage modifier.

**Comment by apoapostolov** [comment]
Also, chat post with revert button to fix mistakes or undo decisions
without having to manually undo the some item. Personally I would prefer if
the sold items are stored and remembered in a compendium cache to revert
mistake as the item may be unique insurance with custom code and text.

This already puts this beyond core feature and would make a great mod.

**Comment by stwlam** [comment]
This won't be happening, sorry.
