### ISSUE TITLE
removeAfterRoll happens even if bonus is disabled in roll dialog

### ISSUE THREAD

**Issue by git-kor-av** [foundryvtt/pf2e#10144]
As a test I imported the Aid effect into my world and added "removeAfterRoll": true to the flat modifier:
![image](https://github.com/foundryvtt/pf2e/assets/32276185/8fcbc140-49b6-4b7e-9c5c-812a6bc75ff8)

Then, I applied this effect to a player, and made a roll bringing up the roll dialog.  Chose to disable the bonus for this roll (as the player was using it on a subsequent roll):
![image](https://github.com/foundryvtt/pf2e/assets/32276185/53427758-c1df-4e8d-b223-11ecc5070904)

As soon as that roll is made, the effect is removed, regardless of whether or not it is actually applied to the roll.

**Comment by stwlam** [comment]
Use `"removeAfterRoll": "if-enabled"`

**Comment by stwlam** [comment]
I believe that particular effect _doesn't_ use `"removeAfterRoll" "if-enabled"` because it is intended to work according to the Aid reaction, which triggers just before the applicable roll.

**Comment by git-kor-av** [comment]
As of 5.5.2, Aid doesn't have this "removeAfterRoll" set at all.  Is the "if-enabled" included in 5.5.2?  When I set this option, it seems to read it as false.
