### ISSUE TITLE
"Resonance" Specific Familiar Ability

### ISSUE THREAD

**Issue by davidmetraux** [foundryvtt/pf2e#10153]
It's just like the current Effect: Resonance for Wisps, but it needs to also affect Alchemical items and not everything from an Elemental with that trait gains the boost. Also, doesn't affect accuracy,  just the damage boost

https://2e.aonprd.com/Familiars.aspx?ID=26&Specific=true

**Comment by TikaelSol** [comment]
Consolidating into #15858
