### ISSUE TITLE
Feature Request: Allow Familiar to use it's owner's Hero Point to reroll a save

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#10155]
Trying this out with no modules activated, I can use a hero point to reroll a PC's save, but not the Familiar assigned to them. RAW states that you should be able to spend a Hero Point on behalf of your familiar or animal companion, so it'd be nice if it were possible to do so here with the standard right click function rather than manually.

**Comment by stwlam** [comment]
I'm not sure there's a rules case for this. If there isn't, it'd have to be implemented in a module.

**Comment by GorgoPrimus** [comment]
If you mean rules case as in written in the rules, then: https://2e.aonprd.com/Rules.aspx?ID=427  
"You can spend your Hero Points in one of two ways. Neither of these is an action, and you can spend Hero Points even if you aren't able to act. **You can spend a Hero Point on behalf of your familiar or animal companion**."

If you meant something else, my apologies for not understanding you.

**Comment by stwlam** [comment]
No, that's it, thanks!
