### ISSUE TITLE
Issue with Advanced Witchcraft Archetype Feat

### ISSUE THREAD

**Issue by Keypaladin** [foundryvtt/pf2e#10164]
I was making a Wizard with a Witch Archetype.  When the Lv 6 Feats came up, I attempted to give Advanced Witchcraft, but it didn't open a separate menu for feat selection as Basic Witchcraft did at lv 4.  

![Witch stuff](https://github.com/foundryvtt/pf2e/assets/145303178/caef5c7f-a250-46bf-ab20-445eb57b5df6)

**Comment by tdhsmith** [comment]
These are not yet automated due to needing some additional data in the roll options to properly filter which feats are available for a given slot.

There is an open pull request to address it: #8914

**Comment by stwlam** [comment]
Closing in favor of #12807
