### ISSUE TITLE
Feature Request: Griveous Rune (Pick)

### ISSUE THREAD

**Issue by Bomberman1988** [foundryvtt/pf2e#10160]
It isn't working

**Comment by simonward** [comment]
It looks like the grievous rune adjustments aren't applying.
<img width="294" alt="Screen Shot 2023-10-13 at 3 55 10 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/1cb1c5f7-4f82-4c7d-9161-7559668143d0">

**Comment by simonward** [comment]
Closed in favor of new issue https://github.com/foundryvtt/pf2e/issues/10705
