### ISSUE TITLE
FR add the travel distance macro to exploration tab in the party sheet as a button.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#10181]
i thought it would be a good idea to have a button that calls on the travel distance macro within the exploration tab on the party sheet. so there is a quick reference for calculating distances. 

*if possible adding mounts for that calculation too*

**Comment by CarlosFdez** [comment]
Does this recently merged feature accomplish what you needed the travel distance macro for? https://github.com/foundryvtt/pf2e/pull/14428

**Comment by ThingsCouldGetDicey** [comment]
i guess the only thing remaining is calculating if the party has access to horses or not.

**Comment by CarlosFdez** [comment]
Which I believe might already be covered by https://github.com/foundryvtt/pf2e/issues/10730

**Comment by ThingsCouldGetDicey** [comment]
> Which I believe might already be covered by #10730

is there a way to select if the party are using horses or not then?

**Comment by CarlosFdez** [comment]
Nope. Which is what that other issue is about. The other parts regarding travel speeds I think are accounted for, or at least more than usable, so I'll close this PR as I don't think we're going to actually integrate the travel macro into the party sheet (maybe vice versa).
