### ISSUE TITLE
Eidolon AC not being affected by Potency Rune

### ISSUE THREAD

**Issue by kaizenmc** [foundryvtt/pf2e#10189]
I may have this wrong, but the item bonus for the eidolon array and the item bonus from any summoner's armor potency rune should stack, giving the eidolon whatever their bonus is plus the summoner's potency rune.

Page 53 of SoM says "Your eidolon _increases_ its item bonus to AC based on your armor’s armor potency rune or bracers of armor."

Currently, only the higher of the two (in my case the base +2 from the array) is applying for AC.  
-Angel Eidolon, Angelic Avenger array.

I have worked around this by giving it an untyped ac bonus equal to the potency rune, but wanted to let you know in case anyone does what I initially did, which was just give the eidolon explorer's clothing with the same potency rune as the summoner.

Love what you guys are doing and thanks for all the many hours of enjoyment using this system!!!

**Comment by stwlam** [comment]
Eidolons are not yet a system feature.
