### ISSUE TITLE
Feature Request: Add method for GM to create chat roll prompts for saves and skills

### ISSUE THREAD

**Issue by JulieWinchester** [foundryvtt/pf2e#10244]
GMs regularly need to ask players to make various checks. The inline roll prompt button support in journals and other sheets is fantastic but requires preparation that isn't always possible, and there will always be some need for players to roll arbitrary skill checks or saves at times. It would be great to have some method for GMs to bring up a dialog that allows for adding a message to chat that prompts players to do a skill check or save, ideally with the ability to specify title or label, difficulty class, and to flag certain types of rolls (recall knowledge, etc.) so that rules elements could act on these rolls. Being able to select multiple skills to produce multiple prompts would be a bonus. Possibly this could take the form of a macro that can be placed on the hotbar but could also be accessed through a button somewhere in the system UI, such as on the party sheet or as a button on the actor tab (similar to the compendium browser button).

**Comment by Qenthel94** [comment]
@JulieWinchester 
There is a macro in the workbench module that does something like this. You press it, choose skill and DC and it creates a prompt in the chat for players to click.
