### ISSUE TITLE
nature's pathway missing uncommon

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#10261]
in the remaster core preview, nature's pathway is uncommon, but it's missing this trait in foundry

**Comment by simonward** [comment]
It is correctly set as uncommon. This wasn't visible due to this issue: https://github.com/foundryvtt/pf2e/pull/10247

<img width="449" alt="Screen Shot 2023-09-21 at 12 51 01 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/3a27adbe-d6ba-4e0c-85d7-4e566743be1a">
