### ISSUE TITLE
Missing RE: Spell Effect: Inspire Heroics (Defense, +2/+3)

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#10305]
Unless I am mistaken, Inspire Heroics effects for Defense should also give the physical damage resistance that Inspire Defense gives.

![image](https://github.com/foundryvtt/pf2e/assets/81383360/0a967051-c0d7-4b35-9255-b52d6aed9405)

**Comment by Intervencion** [comment]
#10310
