### ISSUE TITLE
Token Image rule element intermittently causes a ghost image to spawn

### ISSUE THREAD

**Issue by Hertzila** [foundryvtt/pf2e#10313]
No modules active, fresh new world, on PF2e version 5.5.3 and Foundry build 309.

Applying an effect to an actor with the Token Image element causes the token to spawn a "ghost" token image of itself onto the canvas with the new image. This ghost will stick around in the canvas at the place it was spawned until either a scene is switched or the browser refreshed. It's not a selectable token, simply the image frozen in place. The actual token is still functional.  
However, this only happens intermittently, seemingly at random. Sometimes it triggers on the first time the effect is applied onto the token, other times the effect can be applied onto it multiple times without issue.

Steps to recreate:  
1. Create a fresh world and a scene for it.
2. Create an actor, give it a picture and a token in the scene.
3. Create an Effect with the Token Image rule element with some other image.
4. Drag the effect onto the token in the scene.
5. Sometimes, this will trigger the bug. It may require refreshes or removing the token and the applied effect then re-adding them for it to actually trigger.

The console log: 
[localhost-1695593105326.log](https://github.com/foundryvtt/pf2e/files/12709764/localhost-1695593105326.log)

Image of what it looks like, the very center "token" being the ghost while lower left is the actual token, with Alt being pressed to show token borders and names: 
![Ghost](https://github.com/foundryvtt/pf2e/assets/7857080/02e30d2a-bcfe-47e7-b032-59a8567c5676)

What my rule element looked like, "reittikartat" being a world: ``{"key":"TokenImage","value":"worlds/reittikartat/tokens/Bestiary/Criminal_Charlatan.png"}``

**Comment by stwlam** [comment]
Not able to reproduce. Feel free to post reproduction steps if you discover any.

**Comment by Hertzila** [comment]
Alright then, more detailed steps that, so far, always cause the bug for me. The steps from 10 (bolded) onwards should be done quickly to make sure it triggers. My guess is that it's a race condition because of that.

On Foundry 313. PF2e system version 5.7.1, zero modules active.

1. Create a fresh world.
2. Create a scene there, in my case the name was "test", with the Foundry setup screen as the background: ``ui/backgrounds/setup.webp`` .
3. Create an actor, player character, in my case the name was "guy". Don't add anything more.
4. Create an effect item, in my came the name was "eff", add a Token Image RE with that same Foundry setup screen as image. Don't add anything more.
5. Open the sheet for the actor and move it out of the way.
6. Drop the actor's token onto the scene from the sidebar. Do not select the token.
7. Drag the effect onto the token.
8. Remove the token from the scene.
9. Drag a new token from the sidebar.
10. **Select the token and remove the effect through the top-right status icon.**
11. Remove the token from the scene again.
12. Drag a new token again from the sidebar. Do not select the token.
13. Drag the effect onto the token.
14. The bug should now trigger.

But in case it didn't trigger for some reason, I'll add the steps on how I trigger it with refreshes after those steps are done. The steps from 5 (bolded) onwards should be done quickly to make sure it triggers.

1. Remove all the tokens from the scene.
2. Refresh.
3. Open the actor's sheet and move it out of the way. To make the next steps easier, you can open the items directory with the right click.
4. Drag the actor's token onto the scene from the sidebar.
5. **Select the token and remove the effect from the actor with the top-right status icon.**
6. Remove the token.
7. Drag the actor's token onto the scene from the sidebar again. Do not select the token.
8. Drag the effect onto the token.
9. The bug should now trigger.

Here's exactly what my Token Image Rule Element looks like:  
```
{
  "key": "TokenImage",
  "value": "ui/backgrounds/setup.webp",
  "tint": null
}
```

If this doesn't work, I don't know anymore. I have recorded video of what triggering the bug on a refresh looks like, but other than that, I'll be out of ideas.
