### ISSUE TITLE
Party Sheet Rest button - only restores hit points

### ISSUE THREAD

**Issue by gravagehulk** [foundryvtt/pf2e#10425]
This may just be an instance of me not understanding how something works. I assumed the rest button on the party sheet was for a long rest. When I click it, it restores hit points and tells them that they get focus points, etc back, but does not actually restore them. However, if they players click the long rest button themselves on their character sheets, it restores those resources. 

Is this intended behavior? A bug? A misunderstanding on my part about how it works?

By the way, thank you so much for adding this. Coming from Fantasy Grounds, it was the only thing I missed. Love it.

**Comment by stwlam** [comment]
Not able to reproduce: is this still occurring in your games?
