### ISSUE TITLE
Augury Flat Check Doesn't List DC

### ISSUE THREAD

**Issue by FrostLock63** [foundryvtt/pf2e#10435]
It's supposed to be a DC6 Flat Check, but the DC isn't visible to players.

**Comment by simonward** [comment]
The spell description says: “The GM rolls a secret DC 6 flat check.”
https://2e.aonprd.com/Spells.aspx?ID=15

**Comment by simonward** [comment]
Ah, I see what you mean.
<img width="449" alt="Screen Shot 2023-09-29 at 7 16 59 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/be4fe155-4bf7-4552-aad0-1ede51d4d4a1">
