### ISSUE TITLE
BaseSpeed rule element throws irrecoverable error if selector is undefined

### ISSUE THREAD

**Issue by navisayslisten** [foundryvtt/pf2e#10450]
Foundry Version: 11.308
PF2e Version: 5.6.2

I can make new Heritages but I can't add any rule elements. After attempting to do so, I can never open/edit the Heritage ever again after closing the window. The following is a screenshot of console errors in Google Chrome, performing the following actions after making a new Heritage:

1. Try to add base speed rule element.
2. Close the new heritage's details window
3. Try to reopen the heritage

![image](https://github.com/foundryvtt/pf2e/assets/27226232/cd92d86a-009a-4e9d-ae8e-7792a241529d)

The errors change in Firefox

![image](https://github.com/foundryvtt/pf2e/assets/27226232/3c94c0fd-baf0-417c-907c-da681f0d984b)

**Comment by navisayslisten** [comment]
@In3luki just for clarity, this is an issue for all rule elements on Heritage. Not just Base Speed

**Comment by In3luki** [comment]
I don't get any errors with other rule elements.
