### ISSUE TITLE
Inspire Defense Aura doesn't apply AC or resistance effects

### ISSUE THREAD

**Issue by matterramun** [foundryvtt/pf2e#10487]
Casting Inspire Defense will generate a new effect on the caster with an aura that applies an Inspire Defense spell effect, however the spell effect that is applied lacks rule elements for the AC bonus or physical damage resistance.

The Inspire Defense spell effect on the spell item has the correct rule element, but the effect imparted by the aura does not.

**Comment by stwlam** [comment]
The system does not have an inspire defense aura. I believe that comes from the workbench module.
