### ISSUE TITLE
Unable to add REs to an effect.

### ISSUE THREAD

**Issue by Teraunce** [foundryvtt/pf2e#10530]
Using latest Foundry and PF2e version.
![image](https://github.com/foundryvtt/pf2e/assets/7956641/4b66f825-0e75-436a-8666-e45e705db952)

**Comment by Teraunce** [comment]
More specifically Base Speed seems to be breaking it. The below also popped up on login: 
![image](https://github.com/foundryvtt/pf2e/assets/7956641/a190c2c7-82c8-432a-b4a6-84ef72f82468)

**Comment by Teraunce** [comment]
It's apparently already fixed in the Dev branch anyways.
TLDR: in 5.6.2 Don't try creating a BaseSpeed RE using the adder and never leave one without a selector. It corrupts the Item irreparably.

**Comment by TMunsie** [comment]
Diagnosed on discord. Looks like it was fixed by a PR yesterday. Can replicate on release, cannot replicate on master. Closing as fixed in next release.
