### ISSUE TITLE
{Suggestion/New Feature} Object token/document

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#10531]
New type of token document, "object". This actor is useful for when you need to have statistics for a wall or a crate etc you can drag an "object" actor on to the scene quickly configure it with drop downs using tables here https://2e.aonprd.com/Rules.aspx?ID=730 and rules here https://2e.aonprd.com/Rules.aspx?ID=195. You also have the option to edit the stats to whatever you would like if you wanted more precise stats. 

This could also possibly be used to track item hp when thats needed.

Good start would be building off the vehicle sheet.

The use of this overall will allow for targeting the "object" applying effects and damage to it and having it tracked like a normal actor.

**Comment by stwlam** [comment]
This is more of a Foundry feature request, and it has in fact appeared in past polls. The issue is being tracked here: https://github.com/foundryvtt/foundryvtt/issues/227

**Comment by CrackJackFlood** [comment]
@stwlam The main point of this isn't for dropping items on to a scene or to track items. It would be like a vehicle actor.

Its for helping simulate situations where you want to hit an object, like a wall, with this token you could set it on the scene and target it to simulate hitting or effecting an object.
