### ISSUE TITLE
Tengu Weapon Familiarity Missing Some Options

### ISSUE THREAD

**Issue by mhallet** [foundryvtt/pf2e#10596]
I was trying to create a tengu armor inventor that uses a nodachi as his main weapon.  Since inventors are trained in all martial weapons, common advanced weapons, like the nodachi, should be an option, but it wasn't.

https://2e.aonprd.com/Feats.aspx?ID=1314

**Common Martial Swords**
Bastard Sword
Exquisite Sword Cane
Falchion
Greatsword
Longsword
Machete
Panabas
Rapier
Scimitar
Shortsword
Sword Cane
Talwar

**Common Advanced Swords**
Falcata
Nodachi

**Comment by stwlam** [comment]
Foundry and system versions?

**Comment by mhallet** [comment]
Foundry 11.306
PF2e 5.3.0

**Comment by TMunsie** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/25963508/cc4c02d4-4b9d-4a71-8aa0-2f4bc62517f8)

Cannot replicate. Closing.
