### ISSUE TITLE
Vitality damage hurts living creatures

### ISSUE THREAD

**Issue by MatthewSmit** [foundryvtt/pf2e#10618]
# Steps to Reproduce

Deal vitality damage to a living creature, or void damage to an undead creature.

# Outcome

The creature is damaged.

# Expected Outcome

The creature is unaffected.

Previously, positive damage didn't affect living, and negative didn't affect undead. I couldn't find a reference to this changing in the rework.

**Comment by TikaelSol** [comment]
Check that immunities, weakness, resistance automation is enabled in the system settings, and try without any modules enabled. Verified that this is not a current issue in the release build.
