### ISSUE TITLE
Possibility to revert depositing

### ISSUE THREAD

**Issue by reyzor1991** [foundryvtt/pf2e#10629]
Add button to revert depositing when PC deposits item to incorrect place
Similar to revert damage to fast revert deposit operation

**Comment by stwlam** [comment]
This already exists by virtue of the deposit button becoming an extraction one upon depositing.

**Comment by reyzor1991** [comment]
@stwlam When I deposit to party stash I see no  extraction button. Or I look in incorrect place?
<img width="301" alt="Screenshot 2023-10-08 at 14 26 54" src="https://github.com/foundryvtt/pf2e/assets/6688366/981f6bda-de8d-4312-9f2d-66757fd20590">
