### ISSUE TITLE
As in Life, So in Death should allow for any ancestry

### ISSUE THREAD

**Issue by Yuven91** [foundryvtt/pf2e#10643]
![image](https://github.com/foundryvtt/pf2e/assets/22319152/d51d0221-c0b0-407e-befd-36964b24786c)
As in Life, So in Death should allow for any ancestry, but when selected in foundry, one only gets to select from the common list as standard adopted ancestry

**Comment by TikaelSol** [comment]
Adopted Ancestry was relaxed, so this issue is now moot
