### ISSUE TITLE
Add Implementation to the Scatter Trait

### ISSUE THREAD

**Issue by ChasarooniZ** [foundryvtt/pf2e#10640]
https://2e.aonprd.com/Traits.aspx?ID=413
Add the following trait as splash damage if item has it

**Comment by simonward** [comment]
This should already be in place for PCs.

**Comment by ChasarooniZ** [comment]
Ah, I was testing on NPC's i'll try it on PCs instead

**Comment by DocSchlock** [comment]
Scatter is already implemented for NPCs and PCs.
