### ISSUE TITLE
Aura's Do Not Correctly Account for Creature Size in Radius

### ISSUE THREAD

**Issue by Incantatio** [foundryvtt/pf2e#10655]
According to the aura rules they are an emanation type area effect: https://2e.aonprd.com/MonsterAbilities.aspx?ID=5

According to the emanation rules they start measuring the specified distance from the outer edge of the source creature's square(s): https://2e.aonprd.com/Rules.aspx?ID=357

The areas displayed in the creature compendiums have the distance correct based on what is in the creature's stat block, however the circle template drawn around their token starts measuring from the centre of the creature token rather than its outer edge.

Example: Hound of Tindalos is a medium creature with a 30' aura Ripping Gaze.  Placing the hound on a map the aura only extends out from the hound 5 squares (25') instead of the expected 6 squares (30').  The same can be seen with the Ravager of Tindalos (large version of the hound with the same aura) and it's aura only going 5 squares out from it instead of the expected 6.

For most small, medium, and large creatures this means that the aura is functionally 5' too small when being drawn on the map.  For huge and gargantuan creatures their auras are 10' too small as drawn on the map.  

I'm not sure if Tiny creatures should work like Small creatures in this case or if they should be left as is (based on how their reach works).

If the radius of the drawn circle is a separate data value from the displayed radius in the text this is hopefully a quick batch update to add 5' or 10' to the drawn circle radius value, if they are the same this may be a more challenging issue to fix depending on how stuff is setup on the back end.

**Comment by stwlam** [comment]
Looks fine to me:
![image](https://github.com/foundryvtt/pf2e/assets/106829671/5e8327d6-39aa-4102-b41b-6297799012fe)

**Comment by Incantatio** [comment]
![Hound of Tindalos](https://github.com/foundryvtt/pf2e/assets/112785017/25f77930-7512-437c-9970-8a707666f12d)
![Ravager of Tindalos](https://github.com/foundryvtt/pf2e/assets/112785017/069691c2-7b7c-4a65-a495-20d90f1138a6)
This is what I'm seeing for auras on them in my world on Foundry V11 Build 313 with PF2e 5.6.2 grabbing fresh copies of the creatures out of the Bestiary Browser

**Comment by stwlam** [comment]
You're starting the measurement five feet away from the creature in each case, so it will of course be five fewer feet than expected.

**Comment by Incantatio** [comment]
From what I understand emanations start measuring from outside of the creature so your screenshot is correct there should be 6 squares in the area not counting the token's space.  But in mine I only have 5 squares not counting the token's space.

**Comment by stwlam** [comment]
The background obscures it, but I also count six squares in your first screenshot. Compare with https://2e.aonprd.com/Images/Rules/Rules354.png for reference.
