### ISSUE TITLE
Overdrive not working from the macro bar for player

### ISSUE THREAD

**Issue by Mortavius** [foundryvtt/pf2e#10673]
Hey folks,

So my Inventor player dragged the Overdrive action from the Actions tab of their character sheet down to their macro bar, but when they click it on the bar, they get an orange bar at the top of the screen saying they don't have permission.

If they click it directly from the character sheet, it works fine, and puts the Overdrive action into the chat log.

If I (as GM) do the process, it works fine for me whether it's the character sheet or the macro bar.

In my User Permission settings, players already have "Use Script Macros" checked.

No error shows up in the console when the player does this; and I have tried with all my modules disabled, with no change.

It just seems that if the player wants to run that Overdrive action from their macro bar, they cannot.

**Comment by stwlam** [comment]
What does the body of the macro look like?

**Comment by Mortavius** [comment]
It's a script, and it has this in it:

game.pf2e.rollItemMacro("0TD8c8AuUO3us2yi");

**Comment by stwlam** [comment]
Do they in fact have an item with that ID? It sounds like they made a macro directly from the compendium.

**Comment by Mortavius** [comment]
My player said that he dragged id directly from his PC sheet to the macro bar.  I wasn't beside him, so I can't say that for an exact surety, but I confirmed with him multiple times that was what he was doing, and he said yes.

**Comment by Mortavius** [comment]
Just went over to my friend's house today.  Confirmed that all he is doing is dragging the action from the actions tab of his sheet to the bar at the bottom.  From there, it will not work.  If he clicks it on his sheet, it works fine.  But will not work from the bar.
