### ISSUE TITLE
Final Sacrifice missing 20ft emanation template

### ISSUE THREAD

**Issue by ottyn** [foundryvtt/pf2e#10684]
The spell "Final Sacrifice" is missing the 20ft Burst template on the spell card as described in the description.

https://2e.aonprd.com/Spells.aspx?ID=689

![image](https://github.com/foundryvtt/pf2e/assets/97130150/42ef43a0-153c-4cd1-8217-1a4216ff5944)

![image](https://github.com/foundryvtt/pf2e/assets/97130150/5059f50b-8719-4f85-abc2-f9a004e84d16)

**Comment by dellatorreadrian** [comment]
Working on it
