### ISSUE TITLE
Code to Help Automate Protector's Sphere, Hopefully

### ISSUE THREAD

**Issue by KamaKuzy** [foundryvtt/pf2e#10708]
I don't know how to add code to this repository without screwing it up somehow. If someone could take this macro code : 
```
const actors = const actors = Array.from(new Set(canvas.tokens.controlled.flatMap((token) => token.actor ?? [])));
if (actors.length === 0 && game.user.character) actors.push(game.user.character);
if (actors.length === 0) {
    return ui.notifications.error("PF2E.ErrorMessage.NoTokenSelected", { localize: true });
}

const ITEM_UUID = "Item.V0JW7PJnPzmYUFt3"; // Protector's Sphere: Resistance 4 to all damage
const item = await fromUuid(ITEM_UUID);
if (item?.type === "condition") {
    for (const actor of actors) {
        actor.toggleCondition(item.slug);
    }
} else if (item?.type === "effect") {
    const source = item.toObject();
    source.flags = mergeObject(source.flags ?? {}, { core: { sourceId: ITEM_UUID } });

    for (const actor of actors) {
        const existing = actor.itemTypes.effect.find((e) => e.flags.core?.sourceId === ITEM_UUID);
        if (existing) {
            await existing.delete();
        } else {
            await actor.createEmbeddedDocuments("Item", [source]);
        }
    }
} else {
    ui.notifications.error(game.i18n.format("PF2E.ErrorMessage.ItemNotFoundByUUID", { uuid: ITEM_UUID }));
}
```

And/or this effects code: 
`{"key":"Resistance","label":"PF2E.SpecificRule.CriticalDeck.Effect.Label","slug":"critical-effect-resistance-4","type":"all-damage","value":{"brackets":[{"end":4,"start":4,"value":3},{"end":5,"start":5,"value":4},{"end":6,"start":6,"value":5},{"end":7,"start":7,"value":6},{"end":8,"start":8,"value":7},{"end":9,"start":9,"value":8},{"end":10,"start":10,"value":9}],"field":"item|system.level.value"}}`

and add it to the Protector's Sphere natively, that would be super cool, thanks. 
Picture attached to show how it should perform.
![image](https://github.com/foundryvtt/pf2e/assets/16273856/da1f3f39-7eb2-47df-b305-5391bc0c3e6c)

**Comment by simonward** [comment]
This would be better implemented as an aura effect rather than a macro. However, changes to Core Rulebook items are frozen until remaster.
