### ISSUE TITLE
Cant access info when using renderCharacterSheet Hook

### ISSUE THREAD

**Issue by jacobwojoski** [foundryvtt/pf2e#10714]
- When using the `renderCharacterSheetPF2e`, `renderActorSheet`, `renderActorSheetPF2e` the user is unable to access all the data right away.
- Unable to access Summery Field of Any Actions when viewing the HTML
- Unable to access any Field other than Action Names when viewing character HTML through a hook

On the image 
- New Actor Sheet with No info added other than Custom Actions
- Left (Data found in Hook) 
- Right (Data found when inspecting element)

![Actions Not Appearing](https://github.com/foundryvtt/pf2e/assets/124112219/5c824373-d260-40bd-a3ab-207e3d39b982)

**Comment by jacobwojoski** [comment]
This was found when trying to add a hook to a button in the action summery

**Comment by stwlam** [comment]
This is not a system issue, sorry. You may have better luck seeking assistance in foundry development channels.
