### ISSUE TITLE
Stag Lord actor needs effect added

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/pf2e#10720]
The Stag Lord actor in the Kingmaker bestiary has a few issues/could use a few improvements:

- He is missing the Sickened 1 condition from his Perpetual Hangover passive
- His Sneak Attack is missing an inline roll for the damage
- His Hunt Prey ability is missing a description

**Comment by simonward** [comment]
1) "The values in this stat block have been adjusted to account for his sickened state."
2) The sneak attack damage is automated.
3) Will be addressed via https://github.com/foundryvtt/pf2e/pull/10723
