### ISSUE TITLE
Dragon's Rage Breath has DC 0 (inconsistent classDC usage?)

### ISSUE THREAD

**Issue by emk** [foundryvtt/pf2e#10741]
Thank you for an amazing PF 2e game system! It has made running PF 2e online a delight.

After upgrading to v11 of Foundry and 5.6.2 of the plugin, one of my players noticed this:

![image](https://github.com/foundryvtt/pf2e/assets/36963/4227236d-8e9a-4e3f-a1e0-5eadaf276315)

This is using the following, which does not seem to work:

```
@Check[type:reflex|dc:resolve(@actor.attributes.classDC.value)|basic:true]
```

Looking through `packs/feats` also finds some uses of this, which doesn't work either:

```
@Check[type:reflex|dc:resolve(@actor.system.attributes.classDC.value)|basic:true]
```

However, changing this to the following works fine:

```
@Check[type:reflex|dc:resolve(@actor.classDCs.barbarian.dc.value)|basic:true]
```

Searching for `classDC` through `packs/feats` shows examples of all three usages, plus a few others. I'm not sure what each of the different variations is intended to do, and which are currently supported.

I'd be happy to submit a PR, except I'm not quite sure which is correct. Please let me know if I can help!

**Comment by TikaelSol** [comment]
Feats from classes that use class DC should use that class DC, so the last one would be correct.

**Comment by emk** [comment]
Great, thanks! Here are all the feats that use `@actor.attributes.classDC.value` or `@actor.system.attributes.classDC.value`.

```
packs/feats/roiling-mudslide.json
packs/feats/turn-the-wheel-of-seasons.json
packs/feats/dazing-blow.json
packs/feats/tremor.json
packs/feats/black-powder-flash.json
packs/feats/calcifying-sand.json
packs/feats/thunder-clap.json
packs/feats/weight-of-stone.json
packs/feats/steam-knight.json
packs/feats/megavolt.json
packs/feats/dragons-rage-breath.json
packs/feats/giant-slayer.json
packs/feats/gigaton-strike.json
packs/feats/aerial-boomerang.json
packs/feats/hell-of-1-000-000-needles.json
packs/feats/desiccating-inhalation.json
packs/feats/the-shattered-mountain-weeps.json
packs/feats/deep-freeze.json
packs/feats/elemental-explosion.json
packs/feats/loose-cannon.json
```

Are there any situations in which feats should still use `classDC.value`? I'm not sure how many of these would need to fixed.

**Comment by stwlam** [comment]
Does the character have the barbarian class or just archetype?

**Comment by TikaelSol** [comment]
Things that are from an archetype use your highest class DC, so would need `@actor.system.attributes.classDC.value` or `@actor.system.attributes.classOrSpellDC.value` if the feat uses the higher of those two.

**Comment by jesuisfrog** [comment]
This seems to no longer be an issue and should be closed.

First image comes from a full barbarian and is using the correct DC, second image is from a Thaumaturge with barbarian dedication and is using the highest of the two class DCs so it's correct on both sides.
![image](https://github.com/user-attachments/assets/b794ef11-1052-455b-ba19-34c6b8d36ee5)
![image](https://github.com/user-attachments/assets/7ea36cdd-68ba-41fc-9262-5841d7c83b2f)
