### ISSUE TITLE
FR: Ability to alter an item's icon

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#10759]
Presumably by adding `img` to the list of things ItemAlteration can change. Similar to how people are advised to do the book of forms things for TokenImages, you could have a bunch of predicated ItemAlterations that would change the weapon icon depending on various buffs/debuffs.

**Comment by stwlam** [comment]
Same reason we're not doing actor images: managing it using foundry image selection facilities is too much of a pain.
