### ISSUE TITLE
Stamina is no longer an option as a Bar Attribute on token configuration

### ISSUE THREAD

**Issue by davidmetraux** [foundryvtt/pf2e#10763]
![image](https://github.com/foundryvtt/pf2e/assets/66972164/87e7bde8-cb2a-40dc-9671-1ea3da9eeff4)

It used to be a thing, but not anymore

**Comment by Peach774** [comment]
Not only is it not a bar attribute, but attacks don't work against it - it seems 5.7.1 fixed SOME of the stamina issues but not all of them.

**Comment by Peach774** [comment]
This is still a problem in 5.7.2 - resolve is there, but there is no stamina attribute

**Comment by laurieathey** [comment]
Just upgraded to 5.7.3 and discovered it, so it's still a thing.

It appears to be messing with the following mod as well cause I don't see any reason for it to stop working: https://github.com/mclemente/healthEstimate and it includes stamina in the health estimates.

Incase it helps, I'll post the error from the mod here, but I'm gonna go make a ticket for it on the mod of course:
```
TypeError: Error thrown in hooked function '' for hook 'setup'. Cannot read properties of undefined (reading 'warn')
    at HealthEstimate.updateSettings (logic.js:352:22)
    at HealthEstimate.setup (logic.js:34:8)
    at Object.fn (healthEstimate.js:10:47)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8654:11)
    at async Game._initializeGameView (foundry.js:9931:5)
```

I assume stamina has just moved to somewhere new
