### ISSUE TITLE
Failed data preparation for Actor.xxxPF2ExPARTYxxx.

### ISSUE THREAD

**Issue by Lame-One** [foundryvtt/pf2e#10778]
![image](https://github.com/foundryvtt/pf2e/assets/16337208/81e99fe7-5656-413b-881a-99e5daee7b96)

After updating to latest (5.7.2), I see the above error whenever I boot up my world. I rolled it back and attempted the migration again, I tried booting it up in safemode, and I tried doing both at once, but all result in the above issue.

**Comment by Lame-One** [comment]
This seems to be the result of having familiars and animal companions in the player party tab. Guess it's kinda resolved, though still an issue.

**Comment by CarlosFdez** [comment]
I'm testing with a familiar (animal companions are PC actors) and I'm not reproducing. That said, the error you're having seems to be because of the actors doesn't actually have a speed. Would you be able to isolate which one is causing the issue, and then export that actor?

**Comment by dcoffee** [comment]
I'm getting errors from PC with class levels, Eidolon, and Goblin Dog NPC straight out of the compendium.  (I can open the Goblin Dog sheet, but still get errors about unable to map undefined attributes).

My PC and Eidolon cannot have their sheets opened in 5.7.2 after migration.

Goblin dog:
```
TypeError: Failed data preparation for Scene.sDF52JZbW7w8KH6h.Token.mPYm0KNFKvhN2Kjy.Actor.7OHgTPrbXKaZEsLG. Cannot read properties of undefined (reading 'map')
    at getStrikeAttackDomains (helpers.ts:249:40)
    at strikeFromMeleeItem (helpers.ts:360:21)
    at _NPCPF2e.prepareDerivedData (document.ts:252:33)
    at _NPCPF2e.prepareData (foundry.js:14134:12)
    at _NPCPF2e.prepareData (base.ts:667:15)
    at _NPCPF2e.prepareData (document.ts:247:15)
    at _NPCPF2e._safePrepareData (foundry.js:14109:14)
    at _NPCPF2e._initialize (foundry.js:13937:19)
    at _NPCPF2e._initialize (base.ts:642:15)
    at _NPCPF2e._initialize (document.ts:243:15)
    ```
    
    PC:
    ```
    foundry.js:753 TypeError: An error occurred while rendering CharacterSheetPF2e 125. actor.feats is not iterable
    at _CharacterSheetPF2e.getData (sheet.ts:274:37)
    at async _CharacterSheetPF2e._render (foundry.js:5736:18)
    at async _CharacterSheetPF2e._render (foundry.js:6456:5)
    at async maintainFocusInRender (helpers.ts:84:5)
    at async _CharacterSheetPF2e._render (base.ts:1340:9)
    ```
    
    
[fvtt-Actor-delvin-8XKyV6Wj0cvzZblJ.json](https://github.com/foundryvtt/pf2e/files/12965754/fvtt-Actor-delvin-8XKyV6Wj0cvzZblJ.json)
[fvtt-Actor-goblin-dog-7OHgTPrbXKaZEsLG.json](https://github.com/foundryvtt/pf2e/files/12965755/fvtt-Actor-goblin-dog-7OHgTPrbXKaZEsLG.json)
[fvtt-Actor-eidolonis-6qDD3uFfkM1ElxLC.json](https://github.com/foundryvtt/pf2e/files/12965756/fvtt-Actor-eidolonis-6qDD3uFfkM1ElxLC.json)

**Comment by dcoffee** [comment]
I also encounter similar errors preventing me from adding a class to a brand-new PC created in the party folder.

**Comment by CarlosFdez** [comment]
The failed actors are actually opening up correctly for me. And creating a brand new PC in the party folder and adding a class (I tried barbarian) is also working. I can only recommend using the troubleshooting button as a GM to remigrate, and if that fails reinstall.

The error isn't with the party sheet, the party sheet errors are occurring because the party members are erroring.

**Comment by dcoffee** [comment]
Seems like something happened in that world's migration.  Creating a new world off the same install of pf2e worked fine.

**Comment by dcoffee** [comment]
FYI, this was reproduced again by me when migrating from 5.4.2 to 5.7.x (in this case, 5.7.4).

**Comment by CarlosFdez** [comment]
What's the error in the console this time?
