### ISSUE TITLE
Cosmos Oracle curse not scaling enfeebled condition

### ISSUE THREAD

**Issue by notacynth** [foundryvtt/pf2e#10787]
Cosmos mystery Oracle's Curse of the Sky's Call inflicts, among other things, enfeebled at increasing levels as the curse level goes up. The other scaling effects seemingly work fine but the enfeebled condition stays at 1 at all curse levels, instead of the 1 - 2 - 4 it should be.

**Comment by dsaraujo** [comment]
Maybe related to Rules Elements ordering? My oracle player also complained about this.
