### ISSUE TITLE
Skinstitch salve missing rule element and effect is expired on application

### ISSUE THREAD

**Issue by carpebiem** [foundryvtt/pf2e#10788]
The rule element for upgrading the success to a crit success is missing:

Provided by esheyw
{
    "key": "AdjustDegreeOfSuccess",
    "selector": "medicine",
    "adjustment": {
        "success": "one-degree-better"
    },
    "predicate": [
        {
            "or": [
                "action:treat-wounds",
                "action:battle-medicine"
            ]
        }
    ]
}

Also, the effect is currently set for null rounds so is expired when applied, so a duration should be given

**Comment by simonward** [comment]
Changes to APG items are frozen until remaster.

**Comment by dellatorreadrian** [comment]
Working on it (to get it ready when it can be merged)

**Comment by dellatorreadrian** [comment]
@TikaelSol

Just helping remember to close this issue due to this merged PR: https://github.com/foundryvtt/pf2e/pull/11324
