### ISSUE TITLE
Allow drag & dropping the recovery check to the macro bar

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1079]
In GitLab by @Mr-Monocyte on Feb 12, 2021, 01:41

It would be great to have the autocalculating Recovery check that's built in to the character sheet accessible from the hot bar.

This way, we wouldn't have to open up the whole character sheet to search for the tiny roll icon.

**Comment by TikaelSol** [comment]
Issue is quite stale and there seems to be no interest in pursuing it. Seems too niche to really be something worth spending time on so closing as wontfix.
