### ISSUE TITLE
Critical Damage that includes precision damage throws an error

### ISSUE THREAD

**Issue by Allalinor** [foundryvtt/pf2e#10790]
When trying to roll damage for a critical hit, while having the "Double the number of dice" rule for critical rolls active, on an attack that has precision damage it doesn't roll and throws the following error. 
Normal Hits work fine.
(Tested on 5.7.2, no modules, fresh world, with Precision Ranger, Rogue Sneak Attack and Swashbuckler Finisher)
![chrome_LFE9Kq5TPm](https://github.com/foundryvtt/pf2e/assets/7441153/142e9c72-f2db-4310-b7d0-d44a4fdb9e32)

**Comment by Metasynic** [comment]
This has been happening for me as well! 👍
