### ISSUE TITLE
Some actors in the Kingmaker bestiary lack publication data

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#10826]
![](https://i.imgur.com/DneDDkz.png)

- "Nok-Nok (Level 5)"
- "Jubilost (Level 8)"
- "Ekundayo (Level 1)"
- "Ekundayo (Level 6)"
- "Jubilost (Level 1)"
- "Amiri (Level 1, Kingmaker)"
- "Linzi (Level 1)"
- "Valerie (Level 9)"
- "Valerie (Level 1)"
- "Tristian (Level 1)"
- "Amiri (Level 11, Kingmaker)"
- "Nok-Nok (Level 1)"
- "Tristian (Level 10)"
- "Linzi (Level 7)"

**Comment by TikaelSol** [comment]
These are all the PC like built NPCs.
