### ISSUE TITLE
Compendium Browser doesn't show monsters

### ISSUE THREAD

**Issue by HibaniPaws** [foundryvtt/pf2e#10832]
![Screenshot 2023-10-20 084959](https://github.com/foundryvtt/pf2e/assets/69739925/e58973d7-4d12-46aa-81b8-ea92948e0abb)
Players and GMs who doesn't ignore filtering do not see any monsters from the compendium browser.

**Comment by stwlam** [comment]
Foundry and system version? Are there anything in the actual compendiums?

**Comment by HibaniPaws** [comment]
Current version of PF2e (5.7.2) and latest foundry version. Compendiums contain the usual. Have you tried unchecking the "GMs ignore filtering" settings in the compendium browser?

**Comment by TikaelSol** [comment]
You can try hitting the clear filters button if you hadn't already, uninstalling / reinstalling the PF2e system, try with no modules, and make sure that the compendiums are set to show on the settings tab.

Closing the issue as non-repro
