### ISSUE TITLE
Errors in Agents of Edgewatch Monsters

### ISSUE THREAD

**Issue by EmanuelNa** [foundryvtt/pf2e#10838]
Hello,

I noticed that 3 monsters in Agents of Edgewatch: Belly of the Black Whale (Book 5) have a elite template pre-applied to them.
This makes it so the listed attackbonuses, DCs, etc. no longer match up with the given values of the book.
Affected are:

- Clockwork Chopper Level 14 (elite clockwork assassins being Level 13)
- Mr. Snips (elite variant)
- Pulping Golem (elite variant)

I can understand your reasoning if the latter two were intended to be handled as they were, but since they deviate from the given values and levels of the PDF i assume they should not be elite, but only scaled to the given level.

Version: Foundry 11 Build 313, Pf2e 5.7.2

**Comment by dellatorreadrian** [comment]
Working on it
