### ISSUE TITLE
Infused Reagents adding partial boosts to daily prep

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#10855]
![image](https://github.com/foundryvtt/pf2e/assets/139762764/7c172b26-2689-4387-9afc-4209aa2bec40)

Its adding 0.5 to infused reagents. from the intelligence mod when its a partial boost.

**Comment by stwlam** [comment]
That wouldn't be from a partial boost. Does the character have rule elements adding fractional values to modifiers?

**Comment by GuitarGuyNick** [comment]
Does that include feats or general effects? if general effects there are none.

**Comment by GuitarGuyNick** [comment]
> That wouldn't be from a partial boost. Does the character have rule elements adding fractional values to modifiers?

When my player used the partial boost to test the reagents it went from 14.5 to 14 then added it again. it went to 14.5 

https://cdn.discordapp.com/attachments/828003871435391016/1165346429716406272/fvtt-Actor-arkhan-burnt-nose-kmXWi38XvM7CYF3u.json?ex=6546846f&is=65340f6f&hm=2bbfd3f0e7e911ca34d55d5ee979b44b7d46c08466721caddfe5671a790b457a&

here is a link to the json download to test.
