### ISSUE TITLE
Feature Request: Add the Size changer from npc sheets to PC Sheets for GMs only

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#10865]
There was a part of an ap in alkenstar where you had to switch your pcs size every round. and the only way to do that on the fly fast is to open up the icon config and change the size manually. as a gm it would be useful if a situation where you have to change the pc size could have the benefit on the pc sheet to change the size as like you do with the npc sheet 
![image](https://github.com/foundryvtt/pf2e/assets/139762764/da8d8099-e5dc-4e59-81c8-d2af937fc745)

**Comment by TMunsie** [comment]
This is what the TokenSize rule element is for. Making an effect to do this is rather trivial. There are already several that do this.
