### ISSUE TITLE
Soft-landing (And probably all accessory runes) missing invested trait

### ISSUE THREAD

**Issue by farabor** [foundryvtt/pf2e#10860]
The rules on accessory runes make it so they turn the item they are on into an invested item, so for foundry bookkeeping, they should probably just get the invested trait themselves?   I noticed there's no way for soft-landing, and I assume it's probably the same for others.

**Comment by stwlam** [comment]
Runes themselves aren't invested. This will be taken care of when accessory rune support is added.
