### ISSUE TITLE
Ancestries/feats apply languages to the actor's data even if they aren't part of the world anymore

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/pf2e#10911]
The system is applying an ancestry's languages to the actor's data without checking if said language is still in the world.

How to replicate:

1. Create a Language under the Homebrew Elements menu.
2. Create an Ancestry and add that language to its languages.
3. Remove the Homebrew Language from the settings.
4. Add that Ancestry to an actor.
5. Check that actor's data and its `system.traits.languages.value` will have that language even though it isn't shown.

Notes: Updating the actor's languages won't do anything because it seems the update adds the ancestry's language even if they aren't listed.

A probable fix would be to add a check before applying an ancestry's language to the actor.

EDIT: Also noticed ancestries don't apply custom languages at all.

**Comment by stwlam** [comment]
To some extent there's an expectation that homebrewers clean up after themselves, but it would be simple enough to include a check.

**Comment by mclemente** [comment]
The thing is that this affects modules and world scripts that remove the vanilla PF2e languages too.
For example, Polyglot allows users to remove languages AND assumes the actor's languages are "clean". It isn't feasible to clean the original ancestries and items with Rule Elements that add languages (e.g. Voice of the Elements feat, Stone Communion feat).

**Comment by stwlam** [comment]
The system doesn't support removing languages.
