### ISSUE TITLE
Create applyDamageToTokenFromMessage()

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#10927]
This is a request to create a function that works similarly to `applyDamageFromMessage` but allows you to provide your own tokens to damage, and of course exported for outside use.

https://github.com/foundryvtt/pf2e/blob/0f09409447bb5a2a6ae285f1f73977e4ed14753c/src/module/chat-message/helpers.ts#L73C30-L73C30

Its possible it would be easier to have the existing function updated to allow for providing tokens with the default values being the same as before, instead of maintaining two functions at once.

This request is purely for module-related reasons (Target Damage) as currently the only way to process a message's damage rolls and apply them to a token is to copy the entire function, which has to be maintained and updated every time the system changes.

**Comment by CarlosFdez** [comment]
Personally my thought has been that the current existing functionality should be on the actor instead. But I haven't dug into what would be needed to do that.
