### ISSUE TITLE
Battleform missing the Brawling weapon group

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#10925]
The strikes from battle forms are missing the "group":"brawling", following the precedent from Lizardfolk Claws that ommit the Brawling weapon group but it's added. 

https://2e.aonprd.com/Ancestries.aspx?ID=15
**Claws**
Your sharp claws offer an alternative to the fists other humanoids bring to a fight. You have a claw unarmed attack that deals 1d4 slashing damage and has the [agile](https://2e.aonprd.com/Traits.aspx?ID=170) and [finesse](https://2e.aonprd.com/Traits.aspx?ID=179) traits.

**Comment by stwlam** [comment]
Battle form attacks are without groups, and there is no precedent for globally adding them.
