### ISSUE TITLE
Feral Child Background without rule elements

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#10924]
Feral Child Background doesn't have the proper rule elements:

{"key":"Sense","selector":"lowLightVision"}

{"key":"Sense","predicate":["self:low-light-vision:from-ancestry"],"selector":"darkvision"}

{"acuity":"imprecise","key":"Sense","range":30,"selector":"scent"}

**Comment by dellatorreadrian** [comment]
Working on it
