### ISSUE TITLE
Powerful Fist Feat does not upgrade Unarmed Attack die

### ISSUE THREAD

**Issue by heyzoms** [foundryvtt/pf2e#10936]
I'm playing a Cleric with the archetype Martial Artist Dedication. After applying that to my sheet and checking my unarmed strike it remains the same. I also tried to apply "Powerful Fist Feat" to my character sheet and it also doesn't change my hit dices. I'm wondering if this is a bug, feature not added yet, ects... 

I've Checked the Rules inside both feats and they state below
{"fist":true,"key":"Strike"}
and 
{"key":"DamageDice","override":{"upgrade":true},"selector":["{item|id}-damage"]}
but they don't seem to actually do anything.

Any reply would be nice, thank you

**Comment by stwlam** [comment]
Powerful fist upgrades the fist attack rather than the basic unarmed attack.

**Comment by heyzoms** [comment]
> Powerful fist upgrades the fist attack rather than the basic unarmed attack.

Oh how do i add the fist attack?

**Comment by stwlam** [comment]
It is available if at least one hand is free.

**Comment by heyzoms** [comment]
Oh I found "Fist" in the equipment browser and added it. This allowed me to be able to change the damage dice manually so, all good here now!
