### ISSUE TITLE
Spirit Sense missing effect

### ISSUE THREAD

**Issue by StephenDeBoer** [foundryvtt/pf2e#10951]
The spell [Spirit Sense](https://2e.aonprd.com/Spells.aspx?ID=718) does not have an accompanying effect that can be applied to tokens.

**Comment by dellatorreadrian** [comment]
Working on it

**Comment by dellatorreadrian** [comment]
@TikaelSol 

Just helping remember to close this issue due to this merged PR: https://github.com/foundryvtt/pf2e/pull/11323
