### ISSUE TITLE
Increases and decreases to item repair should be automated

### ISSUE THREAD

**Issue by Unoblueboy** [foundryvtt/pf2e#10958]
When repairing an item with the Crafter's Eyepiece invested, the amount of HP restored via the "Repair: Crafting" action macro doesn't change. For example, when expert in crafting and successfully repairing an item, with and without the Crafter's Eyepiece 15 HP is restored, but I believe it should be the 15 HP is restored when the Crafter's Eyepiece isn't invested and 30 HP is restored when it is invested (a similar case is also true for critical success).

Also I believe the descriptions for the Crafter's Eyepiece and Crafter's Eyepiece (Greater) need to be updated as they don't match what is found on [Archives of Nethys](https://2e.aonprd.com/Equipment.aspx?ID=427), in particular on foundry it says:

> When you Repair an item, increase the Hit Points restored by 15 per proficiency rank instead of 10.

whereas on Archives of Nethys it says:
> When you Repair an item, increase the Hit Points restored to 10 + 10 per proficiency rank on a success or 15 + 15 per proficiency rank on a critical success.

**Comment by TMunsie** [comment]
Please do not use AoN as a reference. Please provide the text from printed source material.

**Comment by Unoblueboy** [comment]
Found the text in the CRB (pg. 609), I've attached the section. This looks to match what is on AoN
![image](https://github.com/foundryvtt/pf2e/assets/12022978/438608fa-2672-4866-b616-c1f02b8fd7dc)

**Comment by TMunsie** [comment]
The text in the system is from the third reprinting. This must have been missed when the last errata came out. We'll check it against the upcoming releases and change if necessary. Thanks for reporting.
