### ISSUE TITLE
Automatic resistance to all damage mishandles Precision damage

### ISSUE THREAD

**Issue by rumelis** [foundryvtt/pf2e#10961]
![image](https://github.com/foundryvtt/pf2e/assets/149266494/70c45183-4bff-4bb1-bc26-834985cf68bf)
![image](https://github.com/foundryvtt/pf2e/assets/149266494/b638884a-8cda-4942-afa2-b6a396a8a99b)
These images shows damage being dealt to an incorporeal creature with Resistance 10 to All Damage (with exceptions that are not relevant to this issue). Per RAW, [https://2e.aonprd.com/Rules.aspx?ID=340](url), precision damage is treated as the same damage type as the original attacks' damage type, but automated resistance to all damage treats it as a separate damage instance and resists the precision damage.

**Comment by stwlam** [comment]
This is from a player's view and doesn't show the breakdown of what was resisted.

**Comment by rumelis** [comment]
Posted in error; creature was immune to precision damage. Apologies.
