### ISSUE TITLE
Variable Core not changing Overdrive and Explode

### ISSUE THREAD

**Issue by gs1github** [foundryvtt/pf2e#10960]
Discovered with one of my players that Variable core does not have automation for the damage type to be selected and doe snot interface with any of the Inventor class features or feats to change the default Fire damage to Electricity damage. I was able to create some custom effects for overdrive with some quick swapping of electricity for fire and moving things around in the grant item rule section, then a quick editing of things like Explode is trivial. I added a quick Choice automation for Variable energy in my own game as well using Kinetic Gate as the base for it as well. Not great and kind of janky, but something I was able to throw together quick as a base for using later.

Variable Core feat RE Choice Set
{
  "choices": [
    {
      "label": "PF2E.TraitAcid",
      "value": "acid"
    },
    {
      "label": "PF2E.TraitCold",
      "value": "cold"
    },
    {
      "label": "PF2E.TraitElectricity",
      "value": "electricity"
    }
  ],
  "flag": "VariableCoreOne",
  "key": "ChoiceSet",
  "prompt": "Variable Core energy type",
  "rollOption": "core-energy"
}

**Comment by pedrogrullada** [comment]
Resolved by #13274
