### ISSUE TITLE
Fire Impulse Junction not applying to 1 action Elemental Blast

### ISSUE THREAD

**Issue by mereghost** [foundryvtt/pf2e#10972]
Hello folks, 

It seems that the fire impulse junction has a built-in requirement of 2 actions on the system that don't map to the actual rules.

```json
{"damageType":"fire","key":"DamageDice","override":{"upgrade":true},
"predicate":[{"gte":["action:cost",2]},"impulse","junction:fire:impulse"],
"selector":["impulse-damage","inline-damage"]}
```

As far as I could gather, it should affect 1 action impulses too. That should be a minor correction on the predicate of the Impulses class feature (`Compendium.pf2e.classfeatures.Item.xhCYkt3acfFd0hr2`). =)

**Comment by In3luki** [comment]
```
In addition, you gain an impulse junction, a benefit that
occurs when you use an impulse of the chosen element
that takes 2 actions or more.
```
