### ISSUE TITLE
Data Error/Bug: Living Sun-Spire's Construct Armor does not affect hardness

### ISSUE THREAD

**Issue by chrpow** [foundryvtt/pf2e#10983]
The Living Sun-Spire's Construct Armor's description does not match the description in the book or in AON. In addition, the automatic reduction in hardness is not automated as it is with other construct enemies.

IS:

> Construct Armor (Hardness 14): Like normal objects, the Living Sun-Spire has Hardness. This Hardness reduces any damage it takes by an amount equal to the Hardness.
> Once the statue is reduced to less than half its Hit Points, or immediately upon being damaged by a critical hit, its construct armor breaks and its Armor Class is reduced to 32.

SHOULD BE:

> Construct Armor: Like normal objects, the living sun-spire has Hardness. This Hardness reduces any damage the sun-spire takes by an amount equal to the Hardness. Once a sun-spire is reduced to fewer than half its Hit Points, or immediately upon being damaged by a critical hit, its construct armor breaks, **removing the Hardness** and reducing its Armor Class to 32.

(Emphasis mine)

IS: When the living sun-spire is reduced to half HP, or when the "Construct Armor Broken by a Critical Hit" box is checked, the living sun-spire's AC is automatically reduced to 32, but it's hardness stays at 14.

SHOULD BE: When the living sun-spire is reduced to half HP, or when the "Construct Armor Broken by a Critical Hit" box is checked, the living sun-spire's AC is automatically reduced to 32, **AND** the hardness should automatically reduce to 0. The Animated Armor NPC in the compendium already has this behavior automated correctly.
![image](https://github.com/foundryvtt/pf2e/assets/15185224/0f0974c1-8577-4d50-a386-7f9b84aa91ed)

![image](https://github.com/foundryvtt/pf2e/assets/15185224/37ffe939-69a3-4be0-8f2f-a770467cc2d0)

**Comment by simonward** [comment]
Unable to reproduce. Did you grab a fresh copy from the compendium?

**Comment by chrpow** [comment]
Agreed, pulling from the compendium fixed the issue.

> Unable to reproduce. Did you grab a fresh copy from the compendium?
