### ISSUE TITLE
Investigator's Devise a Stratagem expires too early (again)

### ISSUE THREAD

**Issue by LJSmith066** [foundryvtt/pf2e#11004]
Previous "fix" makes it expire at end of round (beginning of initiative), not at beginning of investigator's next turn

**Comment by stwlam** [comment]
Working as intended: it does not have a duration of "1 round," so the rule governing that variety of duration language doesn't apply. It is instead closer to abilities that last "until the end of this turn" (but instead until the end of the present round).
