### ISSUE TITLE
Swaggering Initiative not applying properly

### ISSUE THREAD

**Issue by Mackthulu** [foundryvtt/pf2e#11014]
The prompt is still working as intended when initiative is rolled, but it should just always apply to initiative as it is a status bonus. Someone on the pf2e discord said it has a predicate, but I'm unsure what that means exactly.
![a193275a0178cdbe46e0572a71fdd650](https://github.com/foundryvtt/pf2e/assets/149513787/b762bbec-d88e-47c9-8a30-3d8778607074)
![ce32e403c8a7897d7aaa1351ea1950ab](https://github.com/foundryvtt/pf2e/assets/149513787/487b8c47-2165-4d03-b96d-c0ac5c73bbaa)
![tKV12HL](https://github.com/foundryvtt/pf2e/assets/149513787/ee7f1173-877c-4aca-9e71-39e70fceb012)

**Comment by Mackthulu** [comment]
I realize in the screenshot that Cooperative nature is also superseding it AND applying twice. Will show that in another issue.

**Comment by stwlam** [comment]
Swaggering Initiative is a free action, so it does not apply unless the player uses the action.

**Comment by Mackthulu** [comment]
> Swaggering Initiative is a free action, so it does not apply unless the player uses the action.

I guess it is working as intended then. We will just have to toggle it on in initiative.

**Comment by johncarney** [comment]
> Swaggering Initiative is a free action, so it does not apply unless the player uses the action.

In which case a _Roll Option_ rule element should be added to the feat to allow players to toggle it on in their action tab instead of having to do it manually each and every time.

**Comment by avagdumortesin** [comment]
> > Swaggering Initiative is a free action, so it does not apply unless the player uses the action.
> 
> In which case a _Roll Option_ rule element should be added to the feat to allow players to toggle it on in their action tab instead of having to do it manually each and every time.

That is not how actions work; you choose whether or not to use the action at the time it would be called for. You are more than welcome to set a RollOption on your character(s) for it, but the system is not going to add that.

**Comment by stwlam** [comment]
I think we can add a toggle for it.

**Comment by johncarney** [comment]
That was quick. I was about to submit my own PR 🤣
