### ISSUE TITLE
Urdefhan Hunter - immune to fear effects not working

### ISSUE THREAD

**Issue by proxyles** [foundryvtt/pf2e#11041]

**Comment by TikaelSol** [comment]
What are you wanting here? It has the correct data, the system does not stop you from adding frightened, etc to a creature and generally doesn't put notes or anything on saves because the rules regarding immunities and saves is actually not so simple.

**Comment by stwlam** [comment]
Frightened in particular is not a fear effect, as conditions do not have traits.
