### ISSUE TITLE
Conditions with a value can no longer be increased

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#11096]
Pretty sure you guys are already aware of this, but decided to make an issue to be safe.
Cannot increase the value of any condition with a value, i.e. stupefied, stunned, enfeebled, etc.
PF2e version: 5.8.2
Core: 11.314

**Comment by stwlam** [comment]
Are you trying to increase the condition value via rule element?
![image](https://github.com/foundryvtt/pf2e/assets/106829671/667adfee-90f8-4c97-9806-f97fcc2ab708)

**Comment by Symon-S** [comment]
No, trying to increase it through the effect/conditions bar
See [here](https://discord.com/channels/170995199584108546/697845559435853865/1170507333542088755)
If you left click nothing happens
![image](https://github.com/foundryvtt/pf2e/assets/81383360/f2c74236-90c6-4e9b-a481-5e5d02ef3509)

**Comment by Symon-S** [comment]
It seems to work if you have increased it from the hud first though.
