### ISSUE TITLE
Unexpected Shift via Ancestral Paragon 

### ISSUE THREAD

**Issue by marcel-wiechmann** [foundryvtt/pf2e#11186]
Hello,

with 5.8.2 I've created a gnome druid and tried to select 'Unexpected Shift' via 'Ancestral Paragon' as a level 3 general feat. Sadly the system didn't offered me this as a possible option.

**Comment by stwlam** [comment]
Not able to reproduce. Does the character already have the feat?

**Comment by marcel-wiechmann** [comment]
I've deleted the character and recreated it again. This time it was working. Sorry for the trouble. It might be possible that it was added under bonus talent.
