### ISSUE TITLE
Unable to open `Configure Default Token Settings` when using the `Stamina` variant rule

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#11248]
When the `Stamina` variant rule is enabled in the system, there is no way to open the `Configure Default Token Settings` core menu anymore.

![image](https://github.com/foundryvtt/pf2e/assets/651462/0da3d96d-2733-4a8c-9891-699aec3039a4)

**Comment by stwlam** [comment]
Maybe we should kill the variant for remaster after all. 😈

**Comment by reonZ** [comment]
You can't call it quit now, you need to see it through !!
