### ISSUE TITLE
Problem when adding a predicate in an AdjustStrike RE

### ISSUE THREAD

**Issue by Suldrun45** [foundryvtt/pf2e#11263]
I intend to add some suboptions to the RollOption on the Slayer's Strike action and based on this, apply the effects from the feat to the strike.
But I'm still in the first phase of this - no suboptions added yet, just making tests and it doesn't work as I thought it would.

In this phase, I added an AdjustStrike RE to the Slayer's Strike action. If I'm not mistaken, this RE should normally apply a Ghost Touch rune effect to any strike made by a weapon if Slayer's Strike is active.

{"definition":["item:type:weapon"],"key":"AdjustStrike","mode":"add","property":"property-runes","value":"ghost-touch", "predicate":["slayers-strike"]}

To test it, I target a ghost and make a strike... and there is no Ghost Touch (either on the damage card or in the Inspect roll). Without the predicate, it works.
If I inspect the roll, there is a "slayers-strike" Roll option applied to it.

![image](https://github.com/foundryvtt/pf2e/assets/49712710/dd0ef957-bab8-40d0-b266-1bcfd33f4960)

Tested on a last-pf2e-version/no-module world

**Comment by Drental** [comment]
This is specifically for the Slayer's Blessing feat.
