### ISSUE TITLE
Automated flanking rules on hexagonal grids

### ISSUE THREAD

**Issue by OlafurSiemsen** [foundryvtt/pf2e#11295]
I prefer hexagonal grids over square grids, which is one of the features that makes FoundryVTT so attractive to me. Is it possible to apply flanking rules to hexagonal grids? Whether these be the standard rule of center-to-center line method or a variant of counting hexes between allies around the flankee method.

**Comment by TMunsie** [comment]
We only add official rules from the variant and try not to editorialize. This is something that would be more suitable for a module to implement.
