### ISSUE TITLE
Auras (active effects) only work with a square grid

### ISSUE THREAD

**Issue by elespike** [foundryvtt/pf2e#11303]
Hello,

I can't figure out why, but auras only apply effects/conditions when using a square grid. If you have a **cinder rat** on the canvas, for example, and place another token within its aura, the aura effects will automatically apply to the token. But if you change the grid from square to hex (or any other, including gridless), the aura seems to stop working.

I've looked into the defined creatures and item effects, and there doesn't seem to be anything that would prevent auras from working in other grids. Could this be a Foundry issue?

**Comment by TMunsie** [comment]
Paizo has only defined things in terms of squares in their ruleset. The system is reflective of that. The ruleset isn’t designed for gridless (a module could override this) and doesn’t have set rules for hex for combat (how does elevation and how does flanking work? Again - a module could implement something)

Until Paizo makes firm rules on how this works we likely won’t change the system implementation. If you want automated auras you’ll be, unfortunately, relegated to square maps.

**Comment by elespike** [comment]
@TMunsie I see, thanks!
