### ISSUE TITLE
[Feature Request] Off Guard toggle in Attack Roll Dialogue

### ISSUE THREAD

**Issue by FolkvangrForgent** [foundryvtt/pf2e#11350]
It would be convenient if players could toggle if the enemy they are attacking have should have the Off Guard Condition. This would be especially convenient when playing on non Square grid types, where there is no automation for flanking. The reasoning behind this would be to remove the work the GM has to do adding and removing the Off Guard Condition.

**Comment by TikaelSol** [comment]
The system doesn't generally add ways for players to modify their targets. You could make use of the RollOption and EphemeralEffect rule elements to implement this for your own game but we don't want a checkbox that just makes thing off guard as part of the system.
