### ISSUE TITLE
Acrobatic Performer feat is not applying to perform rolls

### ISSUE THREAD

**Issue by SoraHjort** [foundryvtt/pf2e#11353]
FVTT Version: 11.315
PF2E Version: 5.8.3

The[ Acrobatic Performer](https://2e.aonprd.com/Feats.aspx?ID=2106) feat:
> You can roll an [Acrobatics](https://2e.aonprd.com/Skills.aspx?ID=1) check instead of a [Performance](https://2e.aonprd.com/Skills.aspx?ID=12) check when using the [Perform](https://2e.aonprd.com/Actions.aspx?ID=59) action.

When using any Perform action, the system module does not take the feat into account, and is instead set to only ever use performance.

![image](https://github.com/foundryvtt/pf2e/assets/18604504/06d8391b-8bbb-4343-ad4b-364e9b73c664)

**Comment by stwlam** [comment]
You would need to adjust your copy of the macro to switch the skill used.

**Comment by SoraHjort** [comment]
Even having the ability to manually edit to switch the perform macros to use acrobatics would be better than what we got now, which is creating a new macro from scratch to handle it. Which doesn't look as nice or uniform with the built in macros.

**Comment by pedrogrullada** [comment]
Closed by #16489
