### ISSUE TITLE
Enduring Might unable to be used during one's own turn

### ISSUE THREAD

**Issue by AlphaStarguide** [foundryvtt/pf2e#11392]
```
        "duration": {
            "expiry": "turn-start",
            "sustained": false,
            "unit": "rounds",
            "value": 0
        },
```
As you can see the duration's value is 0.
So after you drag it to the token it would immediately become expired and the resistance would not work.
Is it works as intended?

**Comment by stwlam** [comment]
It's used as a reaction, which will _typically_ will be outside one's turn. If used that way, it doesn't immediately expire. That said, it's certainly possible to have an occasion to use it in the midst of a turn, so there's currently a system limitation making that impossible.

**Comment by AlphaStarguide** [comment]
@stwlam Thank you for your explanation.
I checked Champion's Retributive Strike' resistance effect.
It have the same machanism and it's duration value is 1
`    "_id": "DawVHfoPKbPJsz4k",
    "img": "systems/pf2e/icons/spells/dancing-shield.webp",
    "name": "Effect: Champion's Resistance",
    "system": {
        "description": {
            "value": "<p>The ally gains resistance to all damage against the triggering damage equal to 2 + your level.</p>"
        },
        "duration": {
            "expiry": "turn-start",
            "sustained": false,
            "unit": "rounds",
            "value": 1
        },`

Is there any reason for this ?
