### ISSUE TITLE
Some spells missing the Holy trait

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#11425]
So far I have only noted Holy Light and its counterpart Moonlight Ray, but there may be more.
Don't believe that Moonlight Ray is in the remaster, but I would suspect that since they are supposed to work the same that it would also have the holy trait.
![image](https://github.com/foundryvtt/pf2e/assets/81383360/d8be671a-9148-4324-8207-5743dd7e8d4c)
![image](https://github.com/foundryvtt/pf2e/assets/81383360/ebd5ecf6-2fb5-4dbf-ba8b-68b4ee2022ee)

**Comment by Mamutito** [comment]
the divine wrath spell, the sanctified one is correctly added to the preparation list but when you drag it from the character sheet to the spell list, only the sanctified one remains and the holy one is removed.

**Comment by stwlam** [comment]
> the divine wrath spell, the sanctified one is correctly added to the preparation list but when you drag it from the character sheet to the spell list, only the sanctified one remains and the holy one is removed.

This is a separate issue and should be reported separately.
