### ISSUE TITLE
Drag functionality for Party Folder

### ISSUE THREAD

**Issue by Raileth** [foundryvtt/pf2e#11421]
Feature Request:  - Standard functionality in Foundry is that if you drag a folder of actors onto the play area all actors in that folder are dropped onto the map, however the party sheet drops a single 'party' token instead. is it possible to add an option to drop either the party actor or all individual actors in the party. - thereby making it easier to add party members to a map

**Comment by stwlam** [comment]
Not sure this is going to happen, but the clown car controls are there to dump everyone out.
