### ISSUE TITLE
Alliance: Ownership Default (Party/Opposition) should not consider ownership by users with role `None`

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/pf2e#11433]
Problem
-
Ownership by a **disabled** (i.e. `role: None`) Foundry user is counted as ownership by a party member, turning the NPC Configuration `Alliance: Ownership Default` into Party/Friendly.

Expected behaviour
- 
Ownership by a **disabled** (i.e. `role: None`) Foundry user should not be counted as ownership by a party member, and not turn the NPC Configuration `Alliance: Ownership Default` into Party/Friendly.

Details
- 
- A Foundry user / player or secondary GM user exists, which has ownership of the Actor.
- That Foundry user / player gets disabled (leaves the game / was used for testing and not needed anymore / other) by setting the Role in Foundry to `None`  
![image](https://github.com/foundryvtt/pf2e/assets/34374883/d86ac22d-7f74-4108-9bdd-df429f59313d)

For any Actor that belongs to that now-disabled Foundry user, they'll be considered friendly.

![image](https://github.com/foundryvtt/pf2e/assets/34374883/57e391bb-9933-4a0c-98cd-8698747b2a7f)
![image](https://github.com/foundryvtt/pf2e/assets/34374883/45c25d41-c3cf-4570-96aa-9a2f068a949a)
![image](https://github.com/foundryvtt/pf2e/assets/34374883/b58bbea1-2da0-4526-9ed3-b66c3dc93ebd)
![image](https://github.com/foundryvtt/pf2e/assets/34374883/dc378a88-047a-4304-a919-6d4b32e695e4)

This is a problem because often a disabled user, like a disabled GM, will have ownership of monsters. This means that monsters might be considered aligned with party members because a user which used to have ownership of them has been disabled.

Current solution
-
The way to fix this is for the active GM to remove the ownership of the disabled user from all of the affected Actors, which is a bit manual. Alternatively, they can also manually override the NPC Configuration `Alliance` setting for each of the affected Actors. 

![image](https://github.com/foundryvtt/pf2e/assets/34374883/80344375-fdf6-4d70-9554-4aa1fe6eb104)
![image](https://github.com/foundryvtt/pf2e/assets/34374883/dc16cdd8-c090-4b9e-9827-c1a4087f2b5c)
![image](https://github.com/foundryvtt/pf2e/assets/34374883/03c456ab-4499-4e35-ac03-d13330942bb4)
![image](https://github.com/foundryvtt/pf2e/assets/34374883/fba3f9aa-3e43-4225-b3a4-591359d8f46f)

Proposed solution
-
Above solution is cumbersome and manual, and it may be better if ownership by a disabled (i.e. `role: None`) Foundry user was not taken into account for the purposes of NPC Configuration `Alliance: Ownership Default`.

**Comment by stwlam** [comment]
This would be more appropriate as an upstream issue: a user without at least the `PLAYER` role shouldn't be considered a player owner of anything.
