### ISSUE TITLE
[Remaster] Add Basic Spellcasting tree as class features and grant it with the dedications

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#11439]
<img width="234" alt="image" src="https://github.com/foundryvtt/pf2e/assets/244795/d911d365-f82b-497f-958f-af64d67fdda0">

Right now you can't know what Basic Spellcasting means

<img width="363" alt="image" src="https://github.com/foundryvtt/pf2e/assets/244795/ea6da389-3f28-42d5-9913-e94e740a75d8">

Suggestion:
<img width="359" alt="image" src="https://github.com/foundryvtt/pf2e/assets/244795/1092a5fc-cc6e-48f5-8494-cc7faa79f1f7">

**Comment by stwlam** [comment]
I don't think we need to grant it, but we can certainly link to journal entry pages.

**Comment by sambomb** [comment]
I suggested to grant it, because it's easier to read
