### ISSUE TITLE
[Remaster] Holy Light missing the Holy trait

### ISSUE THREAD

**Issue by mindbane** [foundryvtt/pf2e#11447]
![image](https://github.com/foundryvtt/pf2e/assets/354137/9a39cce9-704d-47e9-ad27-2e07b223209a)
vs the pdf
![image](https://github.com/foundryvtt/pf2e/assets/354137/5f26ecd8-a67c-42b0-8024-60175f536e10)

**Comment by Daeke** [comment]
Already reported here: https://github.com/foundryvtt/pf2e/issues/11425

**Comment by stwlam** [comment]
Duplicate of #11425
