### ISSUE TITLE
[Remaster] Champion Archetype not allowing previously selectable options for Pharasma

### ISSUE THREAD

**Issue by zoranac** [foundryvtt/pf2e#11456]
It appears the champion archetype (and likely the base class itself although I have not checked that) does not allow for the selection of a valid champion cause for the gods that don't allow sanctification, like Pharasma. They should allow the previously selectable options.

**Comment by stwlam** [comment]
You'll need to make a copy of the deity and change it to taste.

**Comment by zoranac** [comment]
I would like to request that the data for these gods be changed to "can choose holy or unholy" then, as currently the system presents and empty ui box which is clearly unintended. And you can be a champion for these gods so blocking them entirely is inaccurate.

**Comment by zoranac** [comment]
Read a couple sentences down from that.

From the Paizo FAQ:  
> As an exception, if you could follow a certain champion cause before the remaster, you can still choose that cause (along with the related tenets of course) for that specific deity

Pharasma allows champions still, you can have it not work properly, I don't mind manually working around it, but I am requesting you look into a way to allow it to function properly instead of dismissing it outright.

**Comment by zoranac** [comment]
Additionally, it appears Gozreh is listed as can choose holy or unholy. Which allows them to take any despite being the other "none" god. If nothing else, adding the following to the cause Choice Set in the Deity and Cause feature item (and removing the not filter removing none sanctification gods from the deity choice set) should be close enough to functioning as expected for these two gods:
` "and": [
              "deity:primary:sanctification:none",
              {
                "or": [
                  "item:slug:redeemer",
                  "item:slug:desecrator"
                ]
              }
            ]`

While it gives Pharasma the Desecrator options that isn't technically legal, it keeps everything else accurate and doesn't require you to add special tags and or anything ugly. Especially since this is probably going to change to some degree when player core 2 comes out.
