### ISSUE TITLE
Spells cast from wands have non-functional buttons in the chat window

### ISSUE THREAD

**Issue by maplealmond** [foundryvtt/pf2e#11453]
When using wands, the spell buttons are not functional.

Foundry Level: Build 315

PF2e System: 5.9 or 5.9.1

How to Reproduce:  

* Drop a spellcaster like Ezren on an empty map.  
* Open inventory, drop a spell (force barrage used) and create a level 1 wand.  
* Use the wand from inventory.
* Click the roll damage buttons in the sidebar.

Expected: damage should be rolled, same as casting from spell slots.

Actual: damage does not roll.

**Comment by avagdumortesin** [comment]
From console while running in dev mode, it appears that this is being caused by line 654 in `src/module/item/spell/document.ts`. Looks like the change was in https://github.com/foundryvtt/pf2e/commit/82182d27de7407e01e6434ac4d7cb2cdbb566503.
