### ISSUE TITLE
[Feature Request] Edict and Anathema fields

### ISSUE THREAD

**Issue by Ghostdesu** [foundryvtt/pf2e#11454]
Now that Player Core is out, every ancestry and a few classes have (suggested or required) edicts and anathema that can have a mechanical impact in the case of Champion, Cleric and Druid. Especially Champion, since the new errata refers to their Edicts in feats, not just the part that say they can lose their powers if XYZ. 
It would be very nice to have a dedicated place on the biography tab to put them for reference.

**Comment by azrazalea** [comment]
@stwlam I can take this if you want, should be relatively easy

**Comment by sambomb** [comment]
Bonus points if it inherited from your deity from cleric/champion, champion tenant, druidic order, barbarian instinct, etc...

So you can have all your edits and anathemas at the same place.

Maybe add them as a class feature and use the grant item RE and the edits/anathemas list shows all available.

That would make link those to the chat or journals more easily.

**Comment by azrazalea** [comment]
@sambomb i'm a new contributor so assuming someone else doesn't jump in it'll definitely just be some additional basic text boxes you can paste into for the first iteration. You could definitely put links in it though too. It sounds really cool to have it be more automatic though just out of my experience range for the moment.

**Comment by sambomb** [comment]
Yeah, take your time and do what you can.
I know that what I'm suggesting is way harder then just 2 text box, but it would be very nice, maybe you can expand in the idea later
