### ISSUE TITLE
'Drow' trait not working when filtering for feats in the compendium

### ISSUE THREAD

**Issue by dabinski** [foundryvtt/pf2e#11461]
The compendium isn't filtering for 'drow' feats. I added a bunch of 3rd-party Drow ancestry feats to the compendium, and I can search the feats individually by name and they're in there, with the 'Drow' tag applied. But if i filter for feats with the 'Drow' tag, nothing.
No other creature traits appear to be having this problem. It wasn't a problem before the update.

**Comment by stwlam** [comment]
"Drow" has only ever existed as a creature trait. A homebrew trait would need to be added to make it usable with feats.

**Comment by dabinski** [comment]
Ah i misspoke - I have already added 'Drow' as a feat trait; ostensibly that's what's being filtered for here

**Comment by stwlam** [comment]
Did you add the trait via homebrew settings or a module?

**Comment by dabinski** [comment]
via the core system homebrew elements manager
