### ISSUE TITLE
[Remaster][Data Error]Dragon Form spell has pre-remaster rules text

### ISSUE THREAD

**Issue by Raelysk** [foundryvtt/pf2e#11474]
Dragon Form got traits, traditions & flavor text changed, but mechanics are pre-remaster only.

Current Foundry version:
![image](https://github.com/foundryvtt/pf2e/assets/12633722/4529eb82-5576-4c0d-af93-682334521e1a)
![image](https://github.com/foundryvtt/pf2e/assets/12633722/f73f09f8-e962-4fbd-b997-609ecd5d2aae)
PDF:
![image](https://github.com/foundryvtt/pf2e/assets/12633722/315a3bd6-afcf-40e2-b11e-bd23c3370909)
![image](https://github.com/foundryvtt/pf2e/assets/12633722/95be7360-a8a2-408d-9ba3-eacd39925233)
![image](https://github.com/foundryvtt/pf2e/assets/12633722/a57b4371-db2b-4706-a803-76290fc68ba3)

It makes sense to keep old dragons in spell as is, but then new dragons have to be added too.

**Comment by avagdumortesin** [comment]
Please note that if you want to have the CRB options for this spell after the update which includes the Remaster changes for this, you will need the Legacy Content module.

**Comment by Raelysk** [comment]
"Tradition resistance" is still missing from updated version - both in text and in effect (new part of that spell which gives additional resistance if casting tradition corresponds to dragon tradition).
