### ISSUE TITLE
Rogue Resilience Rule Element Configured Incorrectly

### ISSUE THREAD

**Issue by ChaseDonnally** [foundryvtt/pf2e#11480]
The Rogue Resilience rule element currently upgrades reflex to expert rather than fortitude
![image](https://github.com/foundryvtt/pf2e/assets/47797620/c9f7ecad-0e87-4674-be2f-61d5da26da59)

**Comment by simonward** [comment]
Fixed by https://github.com/foundryvtt/pf2e/pull/11431

**Comment by ChaseDonnally** [comment]
Ah! sorry I forgot to include closed issues in my search before I opened this one.
