### ISSUE TITLE
[Remaster] Reinforcing runes not able to be applied to shields

### ISSUE THREAD

**Issue by Balfuset790** [foundryvtt/pf2e#11482]
When adding a new shield to a character there is no place under the details of the shield to add a Reinforcing rune to adjust the HP, Hardness, etc.

These changes can be made manually to the shield's stats but it would be nice to have this automated like applying property runes to weapons or armour.

**Comment by avagdumortesin** [comment]
This is fixed with https://github.com/foundryvtt/pf2e/pull/11665
