### ISSUE TITLE
[Remaster 5.9.2] Champion strikes not triggering holy weakness

### ISSUE THREAD

**Issue by Suldrun45** [foundryvtt/pf2e#11497]
The Tenets of Good do not seem grant the correct Holy trait to strikes.

Currently, it is 
{"key":"AdjustStrike","mode":"add","predicate":["class:champion"],"property":"traits","value":"holy"}
And this does not trigger the weakness to holy.

On the other hand, the following rule element seems to work - the difference being that it adds the item:trait:holy rolloption to the strikes whereas the current one doesn't: 
{"key":"AdjustStrike","mode":"add","predicate":["class:champion"],"property":"weapon-traits","value":"holy"}

**Comment by stwlam** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/106829671/28acc83b-7fd0-44ee-a9c8-8c0f053e2441)
