### ISSUE TITLE
Anything to do with Shields is not working in newest update

### ISSUE THREAD

**Issue by GreydiusWest** [foundryvtt/pf2e#11513]
Raise a Shield is not applying the AC bonus. I have tried rebuilding the character, testing with different shields, deactivating all of my modules, and no matter what happens the Raise a Shield action does not interact with the character sheet...  even with the effect applied, the system says that "[Character] does not have a shield raised" when you use the block button for damage.

**Comment by stwlam** [comment]
Duplicate of #11079
