### ISSUE TITLE
[Remaster] Lamasthu using outdated anathama/edict and incorrect 1st level Cleric Spell

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#11516]
Lamasthu's entry in Foundry:

Edicts: bring power to outcasts and the downtrodden, _indoctrinate children in Lamashtu's teachings_, make the beautiful monstrous, reveal the corruption and flaws in all things

Anathema: _attempt to treat a mental illness or deformity_, provide succor to Lamashtu's enemies

It also lists her Cleric spells as being _Runic Body_, Animal Form, and Nightmare.

In Player Core 1 (new) her entry has:

Edicts: bring power to outcasts and the downtrodden, _indoctrinate others in Lamashtu’s teachings_, make the beautiful monstrous, reveal the corruption and flaws in all things

Anathema: _attempt to change that which makes you different_, provide succor to Lamashtu’s enemies

And it lists her Cleric spells as _Spider Sting_, Animal Form, and Nightmare.

I've italicized the differences for ease of comparison. Not huge deals, but worth correcting when you find the time imo.

**Comment by kakesu** [comment]
The edicts/anathema for Lamashtu are different between Player Core and GM Core; the current Foundry entry matches what is in GM Core.

**Comment by GorgoPrimus** [comment]
The GM Core info is a copy and paste from the CRB and isn’t particularly usable if you did want to pick it over the brand new stuff they worked to write in PC1 since this reprint has no info on fonts, sanctification, cleric spells, favoured weapon, etc. The PC1 version has all that info with all the updates needed for use in Remaster. GMC’s looks like a clear case of an editor forgetting the remastered changes done to her and copying from the wrong source to me.

In any event, you already use the new lore blurb from her block in PC1 instead of the one reprinted in GMCore so if you want to be consistent in favouring it you should revert that as well. But given they went through the trouble to revise and write up a whole new block of lore and rules for her, I think that’d be silly. Anyways, I’ve done my part and reported it, so that’s it from me.
