### ISSUE TITLE
BUG: removal of prepared spells when dragging into spontaneous spell lists

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#11529]
So i found a weird bug with prepared spells on the latest system version. 

if you get a prepared spell caster like my cleric. you load up the spell book with spells.  if you have a spontaneous table when you drag spells from your spell book it removes the spell from the spell book perminantley.

![pf2 in come assurance](https://github.com/foundryvtt/pf2e/assets/139762764/b62ec07b-a2bf-43f9-baa7-ff729a9d59d9)
 i hope this gif explains the issue.
 
 tested with no mods.

**Comment by stwlam** [comment]
Not a bug: increase your slots.

**Comment by GuitarGuyNick** [comment]
> Not a bug: increase your slots.

i noticed that part wasnt a bug. but when you drag from prepared into spontaenous it deletes the spell list inside the prepared book.
