### ISSUE TITLE
Feature Request: Expose target:distance and origin:distance roll options to all checks

### ISSUE THREAD

**Issue by mysurvive** [foundryvtt/pf2e#11565]
As title states. Requesting to have target:distance and origin:distance roll options exposed for all checks.

For my specific use case: 
The lantern implement specifies "The lantern's magical light attempts to reveal the unseen. You and your allies in the lantern's area of bright light gain a +1 status bonus to visual Perception checks to notice anything that is also within the bright light, and a +1 status bonus to checks to [Recall Knowledge] against creatures within the bright light"
This (the bright light of the lantern) can be faked with rule elements and roll options since we know the radius of the bright light.

**Comment by stwlam** [comment]
We currently have no way of identifying targeted checks besides attack rolls.

**Comment by mysurvive** [comment]
Fair enough, I have a janky workaround for it which will suffice
