### ISSUE TITLE
Pet general feat updates

### ISSUE THREAD

**Issue by Joshmvii7** [foundryvtt/pf2e#11601]
Pet general feat needs RE to have it give the familiar sheet 2 familiar abilities {"key":"ActiveEffectLike","mode":"upgrade","path":"system.attributes.familiarAbilities.value","priority":9,"value":2}

Additionally, if it's a Pet and not a proper familiar the skill bonus to acrobatics, perception, and stealth are 3+master level, with master level+casting attribute being an opt-in choice that actual familiars offer.

**Comment by avagdumortesin** [comment]
This should be fixed with 11644; not sure how to remove the unintentional reference to a completely different PR.
