### ISSUE TITLE
Resistances to holy and unholy applying multiples times

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#11629]
If a creature with unholy/holy resistance takes damage from a strike that has holy/unholy trait, the resistance applies to every type of damage in that strike, instead of just once.
![image](https://github.com/foundryvtt/pf2e/assets/87117602/abbfb7de-58b8-40ad-96bd-7c550c5dcfb2)

**Comment by avagdumortesin** [comment]
This is working correctly. Per the Resistance section on page 408 of _Player Core_:
> If you have resistance to a type of damage, each time you take that type of damage, reduce the amount of damage you take by the listed number (to a minimum of 0 damage).
> ...
> It’s possible to have resistance to all damage. When an effect deals damage of multiple types and you have resistance to all damage, apply the resistance to each type of damage separately. If an attack would deal 7 slashing damage and 4 fire damage, resistance 5 to all damage would reduce the slashing damage to 2 and negate the fire damage entirely.

Each damage type will have the resistance applied.
