### ISSUE TITLE
Idyllkin not mentioned in Remaster Changes journal entry

### ISSUE THREAD

**Issue by khionu** [foundryvtt/pf2e#11621]
[`Idyllkin`](https://2e.aonprd.com/Feats.aspx?ID=2284) was merged with `Form of the Fiend` to be `Beastial Manifestation`. `Form of the Fiend` already has an entry

![](https://i.imgur.com/KcbG17i.png)

**Comment by stwlam** [comment]
This wasn't merged with another feat.

**Comment by khionu** [comment]
Idk what's being treated as the source of truth, but the feat is gone, and there's no mention in the changelog 
![image](https://github.com/foundryvtt/pf2e/assets/11195266/861ef40d-7012-4b74-8f9d-53ae0eb59567)
