### ISSUE TITLE
Ancestral Paragon does not allow Earned Glory for Aiuvarin with Elf Ativism

### ISSUE THREAD

**Issue by 13jtibbitts** [foundryvtt/pf2e#11675]
When adding the Ancestral Paragon feat to a PC that has the _Aiuvarin_ Heritage, **Earned Glory** is not shown as an allowed option.

**Comment by Intervencion** [comment]
Hi, I can't seem to be able to reproduce it
![image](https://github.com/foundryvtt/pf2e/assets/13396742/591f680c-9fa8-428e-bf68-227efcf8d6bb)
![image](https://github.com/foundryvtt/pf2e/assets/13396742/1a97a0aa-c627-488c-93af-77f8c6c5a961)

**Comment by 13jtibbitts** [comment]
That's weird, it just appeared for me (although I should clarify that I am not using the _Ancestry Paragon_ variant rule, but the _Ancestral Paragon_ General Feat.

**Comment by Intervencion** [comment]
Yeah I just edited whilst you were replying. I misread originally, my apologies.

**Comment by 13jtibbitts** [comment]
I was able to figure out the difference. When I have _Elf Ativism_ (I chose Arctic Elf) selected, Earned Glory doesn't appear.
_(Other helpful info might be that it is a Gnome Aiuvarin Enigma Bard with Occult Librarian, but none of those changed, only if I have Elf Ativism or not.)_
![image](https://github.com/foundryvtt/pf2e/assets/45647359/d8356160-6406-4310-bd46-5bd738d2a6d9)
![image](https://github.com/foundryvtt/pf2e/assets/45647359/fe395478-4a49-4a95-8ad3-e4377650ce57)

**Comment by azrazalea** [comment]
Confirming Elf Atavism removes this option from the list. Have a Aiuvarin Elf Atavism Seer Elf that can't see the option either. Investigating

**Comment by azrazalea** [comment]
Okay @13jtibbitts figured out it is because your heritage gets cleared when you choose an Ancestral Paragon heritage, so you lose the aiurvarin heritage trait but still keep elf and your other ancestry trait.
