### ISSUE TITLE
Archer Archetype has lost crossbow support

### ISSUE THREAD

**Issue by maplealmond** [foundryvtt/pf2e#11674]
The Archer Archetype has a series of feats that could use additional support.

RAW: The dedication offers training in all simple and martial weapons in the bow weapon group.  Since crossbows have been split off to their own group, the Archer has lost crossbow support.  I do not believe this is RAI (considering that the Archer specifically supports Crossbows in later feats)  Likewise the Advanced Bow Training feat no longer supports crossbows.

This may require some editorializing between RAW/RAI or feedback from Paizo if possible, but I do not believe the dedication as written was intended to lose crossbow support.

**Comment by AFigureOfBlue** [comment]
This will presumably be clarified in _Player Core 2_ since the archer archetype will presumably be reprinted there. It's definitely in a bit of an uncertain spot until then though.
