### ISSUE TITLE
Just letting you know that the Tongue strike from the Frog (Animal Barbie) doesn't have image

### ISSUE THREAD

**Issue by Bomberman1988** [foundryvtt/pf2e#11697]
![image](https://github.com/foundryvtt/pf2e/assets/103781301/9ee5ca56-3f06-4f2f-a6e0-c3613da837b9)

**Comment by simonward** [comment]
Unable to reproduce. Have you tested with a fresh character?
<img width="392" alt="Screen Shot 2023-11-22 at 10 57 51 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/ef980307-dc52-4d18-966e-916dcd8e72fc">

**Comment by Bomberman1988** [comment]
That's strange, I just made that one. But ok, thanks anyway man

**Comment by simonward** [comment]
Bad system install maybe? Check that the image exists at "systems/pf2e/icons/unarmed-attacks/Tongue.webp"

**Comment by simonward** [comment]
Ha. That's the bug. You're on a case sensitive file system I'll bet.

**Comment by Bomberman1988** [comment]
Hmm.. I dunno what that means :(
