### ISSUE TITLE
Aeon Stone (Pearlescent Pyramid) Automation

### ISSUE THREAD

**Issue by TehT** [foundryvtt/pf2e#11708]
Would it be possible to add automation to Pearlescent Pyramid Aeon Stone, it should add the function of the Ghost Touch to all weapon and unarmed attacks.

https://2e.aonprd.com/Equipment.aspx?ID=407

**Comment by simonward** [comment]
It should already work. Grab a fresh copy from the compendium.

**Comment by simonward** [comment]
However, I do note that the usage is incorrect and will fix.
