### ISSUE TITLE
Feature Request: Provide a way to view emanations from a token while the token is selected

### ISSUE THREAD

**Issue by ScottWSlaughter** [foundryvtt/pf2e#11785]
It can be a bit difficult to determine exactly what is being affected by which emanations on a scene just by looking. Could you provide a way to display a token's emanations, but only when the token is selected. This way the GM or a player could click a token and see the emanation clearly, but the scene won't become cluttered if there are a lot of emanations present.

**Comment by stwlam** [comment]
Emanations that aren't auras are measured templates in Foundry, and those are always visible.

**Comment by ScottWSlaughter** [comment]
I'm referring to emanations from spells. As an example, the Bless spell. It has an emanation, but I haven't found a way to display it at all in Foundry.

**Comment by ScottWSlaughter** [comment]
@stwlam I'm tagging you since I'm assuming you won't see the follow up comment since this was closed so quickly.

**Comment by stwlam** [comment]
It comes with an aura effect
![image](https://github.com/foundryvtt/pf2e/assets/106829671/a08a8e82-1791-4530-a394-f6d1331331a2)

**Comment by ScottWSlaughter** [comment]
Interesting. I do not see that in my scene. I have the aura effect on a token, and I can see it applying to nearby tokens, but it isn't visible on the scene at all. 
![Screenshot 2023-11-26 165741](https://github.com/foundryvtt/pf2e/assets/52973405/4db51785-dd3c-4b65-873e-12b5463adca5)

**Comment by stwlam** [comment]
Try testing isn't a scene that isn't a splash page.

**Comment by ScottWSlaughter** [comment]
OK. Now I can see it. I didn't expect there to be a difference by scene. What is actually determining the display here? I don't see anything wildly difference in the scene settings.
