### ISSUE TITLE
Nature Incarnate ( Kaiju ) wrong token size

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#11797]
<img width="608" alt="image" src="https://github.com/foundryvtt/pf2e/assets/244795/0d5eea36-3728-4dd0-a9ce-aade263afa4e">
The token size for the form is following the normal Gargantuan ( 20x20 size ) but the spell description indicate a 30x30 size.

**Comment by stwlam** [comment]
Duplicate of #6628
