### ISSUE TITLE
Animal Trainer Animal Companions not implemented.

### ISSUE THREAD

**Issue by jaredthaler** [foundryvtt/pf2e#11790]
It looks like Animal Trainer ACs (ATAC) are not currently implemented correctly in pf2e-animal-companions.

ATACs lose their species skill and replace it with training in performance.
ATACs have a unique Mature Companion feature that makes them expert in performance.

**Comment by stwlam** [comment]
The repository for that module is at https://github.com/TikaelSol/PF2e-Animal-Companions
