### ISSUE TITLE
Finesse thrown weapon automatically applying STR rather than DEX to damage with Thief racket

### ISSUE THREAD

**Issue by LJSmith066** [foundryvtt/pf2e#11819]
On a Thief racket Rogue (apply dex modifier to strikes with finesse weapons):
![image](https://github.com/foundryvtt/pf2e/assets/110754119/4b2db46c-4c32-4093-ac90-0d7a35f71e13)
STR and DEX both show up for damage modifiers, but by default STR is used despite being the lower value.

**Comment by stwlam** [comment]
Foundry and system versions?

**Comment by LJSmith066** [comment]
Foundry build 315, Pathfinder version 5.9.5

**Comment by stwlam** [comment]
You're throwing it, so it's a ranged weapon in that case.

**Comment by stwlam** [comment]
Thrown trait:
> You can throw this weapon as a ranged attack, and it is a ranged weapon when thrown.

**Comment by LJSmith066** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/110754119/f29777ff-00b0-4b49-9376-e6487bef066e)

**Comment by stwlam** [comment]
It does add your strength modifier, yes, just like a melee weapon.

**Comment by LJSmith066** [comment]
shit yeah sorry just saw where thief racket specifies it only changes ability mod to damage on melee strikes, not ranged - my bad, I should probably get some sleep lol

**Comment by stwlam** [comment]
No worries--it's a common thing missed and requires pulling together rules that are hundreds of pages apart
