### ISSUE TITLE
"Other weapons" proficiencies from Classes are hardcoded and can not be added/removed/renamed [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1182]
The original issue

	Id: 1182
	Title: "Other weapons" proficiencies from Classes are hardcoded and can not be added/removed/renamed

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/1182

**Comment by Shandyan** [comment]
Closing, as I don't see why you need to be able to remove or edit the names of class-specific weapons normally. For homebrew, you can edit the rules elements on the class.
