### ISSUE TITLE
Negative Healing ability name not changed, also possible damage resistance bug discovered

### ISSUE THREAD

**Issue by Jolias055** [foundryvtt/pf2e#11838]
The text for the ability was changed correctly to reflect the changes in the remaster, but the name of the ability itself was not changed, despite being clearly called "void healing" inside of the text. Searching for Negative Healing in the compendium finds the ability, but searching for "Void Healing" does not.
![image](https://github.com/foundryvtt/pf2e/assets/152304230/b2065a5b-b8db-4b57-80cd-c58ebbf1c8e2)

Out of curiosity I tested whether a creature with Negative Healing could take Void damage and it could. I was using the Lich creature to test this, as it has a Void damage attack. It took the damage. 
![image](https://github.com/foundryvtt/pf2e/assets/152304230/d37102e5-e4c6-42bb-996f-a51ce0b19973)

Out of further curiosity, I tested the Lich's Cold resistance by having it take damage from it's own Cone of Cold spell. It took the full damage despite having Resistance 10 to Cold. (I healed the creature to full before testing)
![image](https://github.com/foundryvtt/pf2e/assets/152304230/9066de2e-17a4-4ff6-8018-fa0f892ea16f)

I then searched for a creature with immunity to test out on and found the Ice Golem. I then had it take damage from the Cone of Cold. It took full damage despite being immune.
![image](https://github.com/foundryvtt/pf2e/assets/152304230/bb371c7f-893a-471c-a7ce-7a728758bfba)

Initially I wondered if the trait Negative Healing didn't negate Void damage because of the renaming of the damage, because I vaguely remember creatures with this ability not being able to take Negative damage. But after testing it with resistances (which I clearly remember working before) and immunities (which I did not try before the remaster) I believe there might be an issue with the way damage interacts with resistances/immunities.

**Comment by stwlam** [comment]
Hi there,

Try enabling immunities, resistances, and weaknesses in system settings.

**Comment by Jolias055** [comment]
I see, my bad, that did it. Thank you very much.
