### ISSUE TITLE
Lingering Composition does not increase size of Focus Pool

### ISSUE THREAD

**Issue by EidolonForgery** [foundryvtt/pf2e#11842]
Lingering Composition is supposed to add +1 point to your focus pool, but does not seem to actually do this.

**Comment by stwlam** [comment]
Feats no longer grant focus points. Your number of focus points is equal to the number of focus-point-costing focus spells you have.
![image](https://github.com/foundryvtt/pf2e/assets/106829671/b0a6e4c1-cd2d-4162-8d2f-f3bec742e2b7)
