### ISSUE TITLE
(Bug) Creature Size doesn't animate size change when token image changes

### ISSUE THREAD

**Issue by WBHarry** [foundryvtt/pf2e#11862]
I've done RE setups for resizing a player and changing their token art before, and it's used the smooth scaling animation to the new size. For some reason that's not happening anymore.
**Reproduction:**
1. The character has a feat that I added a Token image RE to:
```
{
  "key": "TokenImage",
  "value": "tokenizer/pc-images/lamb.Token.webp",
  "predicate": [
    "self:effect:change-shape"
  ]
}
```
2. In the snippet below I tossed on an effect with a Creature Size RE: `{"key":"CreatureSize","value":"medium"}`
3. The token image disappears and after the animation time for token resizing is over it appears as the new token image.

https://github.com/foundryvtt/pf2e/assets/89362246/3537c424-8335-4236-be8f-e67270fb07d5

When the Creature Size Rule Element is applied in isolation it shows the size change animation correctly.

**Comment by stwlam** [comment]
Unfortunately, this is a limitation in V11 the system can't do anything about.
