### ISSUE TITLE
Remaster: Administer First Aid (Stop Bleeding) does not indicate lowered DC for appropriate help

### ISSUE THREAD

**Issue by Pexpy** [foundryvtt/pf2e#11865]
In the Remaster, Administer First Aid to stop bleeding was clarified to refer to the assisted recovery rules for persistent damage. It also newly indicates that it is 'particularly appropriate help' which lets the target roll a DC 10 instead of DC 15 flat check to end the bleed damage. Foundry pf2e 5.9.5 differs from the version in Player Core, and most importantly, makes no references to this lowered DC effect.

Please compare the two excerpts (the rest of the action is identical; differences are indicated in italics)
Foundry version 
> **Stop Bleeding** Attempt a Medicine check on a creature that is taking persistent bleed damage, _giving them a chance to make another flat check to remove the persistent damage._ The DC is usually the DC of the effect that caused the bleed.
> Success If you're trying to stabilize, the creature loses the dying condition (but remains Unconscious). If you're trying to stop bleeding, _the creature attempts a flat check to end the bleeding._

Player Core (p241-242)
> **Stop Bleeding** Attempt a Medicine check on a creature that is taking persistent bleed damage (page 409). The DC is usually the DC of the effect that caused the bleed.
> **Success** If you’re trying to stabilize, the target loses the dying condition (but remains unconscious). If you’re trying to stop bleeding, _the target benefits from an assisted recovery (page 445) with the lowered DC for particularly appropriate help._

Additionally when the player uses the "Administer First Aid - Stop Bleeding - Medicine Check' action macro, this is listed:
> Success The creature attempts a flat check to end the bleeding.

The roll macro makes no mention of granting the lowered DC and should instead read:
> Success The target benefits from an assisted recovery with the lowered DC for particularly appropriate help

**Comment by tdhsmith** [comment]
This content looks to have been added by @avagdumortesin in #11782, just hasn't been in a release yet.

**Comment by avagdumortesin** [comment]
Yes, this should be in the next release. Closing.

**Comment by avagdumortesin** [comment]
Macro text update has been merged; closing this again... for realsies this time.
