### ISSUE TITLE
Flat Modifier Item Bonuses are not being applied and not appear in the roll dialog box

### ISSUE THREAD

**Issue by hamsterwheel1** [foundryvtt/pf2e#11864]
As the title says, item bonuses are not being applied when an effect is added. The easiest way to replicate this bug is to use a Quicksilver Mutagen and add the effect to a player. Use Acrobatics or make an attack roll, no item bonus is applied. When the Roll Dialog box appears, no item bonus is shown in the dialog box. 

I've done some additional testing as well. If you Import Quicksilver Mutagen, go to the Rules tab and scroll down to the first Flat Modifier, you can change the bonus type to Untyped or another type. Doing so makes the effect work after the change and the effect appears in the roll dialog box.

Another example is Boots of Bounding. It gives a 5-foot item bonus to movement which is not applied unless you adjust the item to use a different bonus type like Untyped.

**Comment by stwlam** [comment]
Try disabling Automatic Bonus Progression.

**Comment by hamsterwheel1** [comment]
Thank you for the fix to the issue. I'll just have to wait on using ABP for now. Thanks again.
