### ISSUE TITLE
"Negative Healing" vs. "Void Healing"

### ISSUE THREAD

**Issue by tagnullde** [foundryvtt/pf2e#11913]
Unsure if this is an issue.

The Wight (and probably other undead) have the "Negative Healing" - Passive Ability.
Shouldn't that be renamed to "Void Healing"? 

![image](https://github.com/foundryvtt/pf2e/assets/44159008/6d4b0d18-2cb5-47d1-aa24-70cdf98c2937)

**Comment by Drental** [comment]
it's not an issue because the Wight in the compendium has the Void Healing ability - actors in the world are not updated.

**Comment by tagnullde** [comment]
Weird. When using the Bestiary Browser the name still shows up as "Negative Healing".

![image](https://github.com/foundryvtt/pf2e/assets/44159008/b988de40-9c7d-49d6-b55b-2739a04354f8)

**Comment by Drental** [comment]
might be the next release then, the change is here: https://github.com/foundryvtt/pf2e/commit/c4dbb862109441f561e4326f64807b1300410e91
