### ISSUE TITLE
(System 5.10.2) Skill Edit is broken

### ISSUE THREAD

**Issue by WBHarry** [foundryvtt/pf2e#11956]
Noticed after updating that it's impossible to enter the Skill Edit dialog for an NPC. Screenshot is without modules.
![image](https://github.com/foundryvtt/pf2e/assets/89362246/d032cd17-ce66-4c3c-80b5-6ab4e0230ecc)

**Comment by TMunsie** [comment]
Cannot replicate. Try reinstalling the system as it looks like a system file is missing. If it still fails after re-install you can re-open this issue.

**Comment by WBHarry** [comment]
I've now tried and looked at a few things:

- I've tried reinstalling the system now with no luck.
- Reinstalling foundry didn't help.
- Looking in the system files I'm not actually missing the mentioned template partial `lore-sidebar.hbs`. 
![image](https://github.com/foundryvtt/pf2e/assets/89362246/9c7e993d-6c09-4066-970f-240b182b5735)
