### ISSUE TITLE
Indestructible Shield forced as cold iron

### ISSUE THREAD

**Issue by Albireookami** [foundryvtt/pf2e#11967]
Unable to set as high grade adamatine and stats are off

**Comment by stwlam** [comment]
Hi there, where can one find this item?

**Comment by j-bs** [comment]
Seems like it's the _Indestructible Shield_ and yeah its material type is locked to cold iron (no other options in `select`):

![image](https://github.com/foundryvtt/pf2e/assets/4469633/5505d8f0-3920-4ce0-93b7-67757a6551c9)

**Comment by stwlam** [comment]
Untick the "specific magic shield" checkbox to unlock materials. The stats will still be off but will be fixed in the next release.
