### ISSUE TITLE
Suggestion: Replace "+" signs on character tab with magnifying glass

### ISSUE THREAD

**Issue by pinkflumph** [foundryvtt/pf2e#11989]
The character sheet generally uses a magnifying glass to denote compendium search, except for the _character tab_, where the selection is denoted with a plus sign. This leads to confusion among new players: they are subconsciously prepared to click plus everywhere else, but the system expects them to click the magnifying glass. 

It's a minor issue, but replacing the pluses with magnifying glasses will make it slightly more intuitive and consistent

**Comment by stwlam** [comment]
Try updating your system install.

**Comment by pinkflumph** [comment]
Ah, I see in the changelog, it has actually been implemented. The question being closed as "not planned" misled me for a moment. Nevermind then, thanks!
