### ISSUE TITLE
Template no longer snap to grid

### ISSUE THREAD

**Issue by uniwars** [foundryvtt/pf2e#12022]
Hi, I tested the heal 3 actions emanation template (with no modules) and the template doesn't snap to grid. I don't know if it's supposed to do something special because of it being an emanation but the template can be badly placed (it will not correct itself if placed wrongly)

**Comment by stwlam** [comment]
Foundry and system versions?

**Comment by uniwars** [comment]
11.315 and 5.10.3

**Comment by uniwars** [comment]
Seems fixed for me
