### ISSUE TITLE
rousing splash scaling broken

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#12060]
when a PC casts rousing splash, it doesn't scale at all, the THP is always as if they cast it as lvl 1

**Comment by simonward** [comment]
Cannot reproduce. What issues are you having?

<img width="296" alt="Screen Shot 2023-12-06 at 10 54 49 AM" src="https://github.com/foundryvtt/pf2e/assets/1904698/bf398cf5-272d-4ea3-821f-5e6da4740e8b">
