### ISSUE TITLE
Treat Wounds macro not working with Natural Medicine

### ISSUE THREAD

**Issue by thejoester** [foundryvtt/pf2e#12075]
I have a player character who has the Natural Medicine feat, so they are not trained in medicine. When I try and use the Treat Wounds macro, select Nature Skill it gives the error 

`Token Meredith Hollyleaf does not have the medicine skill`

The character should not need to be trained in medicine with this feat, they do have a Healers Toolkit worn or held. 
[Video.webm](https://github.com/foundryvtt/pf2e/assets/7744795/412071ce-e16e-4ca3-ba23-cbfaa858eb00)

**Comment by simonward** [comment]
I am unable to reproduce.

Is the character trained in Nature? The warning message incorrectly says "medicine" if Nature is untrained.

**Comment by thejoester** [comment]
So I did some more testing and discovered that for some reason the background on the character sheet was missing - this is where the Natural Medicine came from. Putting that back seems to have resolved the issue, They had the feature on the feat tab though. Anyway that seems to have resolved it.
