### ISSUE TITLE
GM Screen Journal requires some remaster changes

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#12132]
I.E it is missing Reposition action, Death and Dying section (clarification from remaster errata), critical specializations for certain weapons, etc.
Pf2e v5.10.5

**Comment by stwlam** [comment]
The journal entry is not intended to be an exhaustive list of every single change made. Particularly rules will have far too many to reasonably list.

**Comment by stwlam** [comment]
If the GM screen is at some point published in a remaster edition, we'll certainly include it.
