### ISSUE TITLE
Encounter XP/threat calculation should be influenced by the individual participants' alliance in the combat tracker (including NPCs), not strictly by whoever's in the party folder

### ISSUE THREAD

**Issue by SonofOrion42** [foundryvtt/pf2e#12168]
As it stands, the system does not properly calculate a combat encounter's level and XP for the party whenever allied NPCs are involved. I often have to do the calculations with the proper adjustments myself because, for example, a party of four fighting a moderate threat encounter by Foundry will have the same difficulty and XP award as it would if, say, four to six guards were fighting on the PCs' side. This makes it harder to determine what actually constitutes a certain level of difficulty when NPC allies are included in a fight and it also throws the XP amounts way out of whack. The system should be able to account for allegiance and adjust the encounter budget properly when necessary.
![image](https://github.com/foundryvtt/pf2e/assets/31265059/a12619ef-aa90-4869-8312-098bb9720442)
![image](https://github.com/foundryvtt/pf2e/assets/31265059/c36af66e-db5a-4340-882b-945a7e2510dd)

**Comment by stwlam** [comment]
Upstream issue: there are no rules for factoring in allied NPCs.
