### ISSUE TITLE
Remaining issues with Kingmaker Warfare data entry (compilation)

### ISSUE THREAD

**Issue by silvative** [foundryvtt/pf2e#12161]
Kingmaker's Warfare subsystem is pretty complex and, while I've done my best to be thorough, I did in some places hit the limits of my capabilities with rule elements. I've tried to document here some known issues/gaps or possible places for improvement, both in case I can revisit them later or in case someone else wants to take a stab at them.

Note: This issue is current to my as-yet unmerged PRs https://github.com/foundryvtt/pf2e/pull/12163 and https://github.com/foundryvtt/pf2e/pull/12162

### Items

- **Cavalry Experts** does not suppress the penalty to Morale & Maneuver checks from Overrun
- **Keep Up The Pressure** doesn't have any automation currently (I'm not sure if we can edit an army's MAP)
- **Darkvision** & **Low-Light Vision** - I don't think that Army actors have "real" senses currently?
- **Merciless** is not automated (wasn't sure if this is possible yet)
- **Guard** 's success effect is not automated (can Mark be used for this?). The Success is a toggle property which unfortunately means all armies have a toggle no matter what.
- **All-out assault** does not boost damage (I'm not sure if this is possible)
- Apparently we can use something like @Check[type:maneuver|defense:maneuver|roller:self] , which I hadn't been doing in most places

### Creatures

Actors:

- Currently the extra appendix armies are not entered, only the armies that appear in the adventure (which is most of them)

Unique tactics:

- The troll's **regeneration** does nothing atm (I don't think the regeneration rule element works on armies)
- The first world army's **primal magic** ability isn't automated (could it be?)

**Comment by silvative** [comment]
Shark mentions cavalry experts should use an adjustmodifier
```
{
    "key": "AdjustModifier",
    "predicate": [
        "penalty:type:circumstance"
    ],
    "selector": "attack-roll",
    "suppress": true
}
```

**Comment by CarlosFdez** [comment]
I think we have everything here except Primal Magic and some extra `@Check` uses now. At most it can maybe use some inline rolls and buttons for the maneuver checks.

**Comment by BernhardPosselt** [comment]
Feint is also broken input wise, there are no rollable checks

**Comment by CarlosFdez** [comment]
I fixed feint's formatting, but the rollable check seems to be an attack roll. For now though I'll close the issue, since half of the stuff listed here has been already done, and I'd like new issues for new problems.

**Comment by BernhardPosselt** [comment]
Many thanks looking into that
