### ISSUE TITLE
Label issue for armor resilient runes

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#12232]
![Foundry_Virtual_Tabletop_pSdQdeFzhH](https://github.com/foundryvtt/pf2e/assets/651462/c3fd5d9a-5690-43a6-ba86-453e47158761)

In the `lang/en.json` is it actually `PF2E.ResiliencyRuneLabel` and not `PF2E.ResilientRuneLabel`

**Comment by Symon-S** [comment]
I also mention this here https://github.com/foundryvtt/pf2e/issues/12230
