### ISSUE TITLE
Unable to transfer items from one actor to another as GM

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#12231]
There are 2 bugs here:

1. we can't drag & drop an item from a sheet onto a token to transfer/copy the item, the `dropCanvasData` isn't even triggered
2. when transferring an item from one sheet to another, even though it seems like the transfer went through, closing and re-opening the sheets shows that it is not the case

Here is a short video showing the issues (all modules were disabled of course)

https://github.com/foundryvtt/pf2e/assets/651462/a1317aca-15e4-4c18-ae3b-2f3dc9b39dab

**Comment by Guolfo** [comment]
I got the same issue as soon as I updated to the latest version
