### ISSUE TITLE
Heading links in Journals in multipage view break when any page contains a broken item link

### ISSUE THREAD

**Issue by Drental** [foundryvtt/pf2e#12266]
To reproduce: 

1. import the GM Screen journal.
2. Open the Journal and turn on multipage view
3. edit any page of the journal and add a link to a pf2e item
4. replace a letter in the item ID to break the link
5. the links on the first page of the GM screen will now always scroll all the way up.

additionally the broken link causes a noticeable delay (~0.1 seconds) when clicking the link, the journal appears to "jitter"

**Comment by stwlam** [comment]
Closing as upstream issue
