### ISSUE TITLE
The Language Changes listed in the PF2e Remaster Journal don't list Druidic -> Wildsong.

### ISSUE THREAD

**Issue by Payden-Pringle** [foundryvtt/pf2e#12272]
![image](https://github.com/foundryvtt/pf2e/assets/4104557/886940a1-5b02-4077-a75b-07b03b2e6846)

Druidic is now Wildsong in the Remaster.

**Comment by simonward** [comment]
Currently listed under Class Features:
<img width="626" alt="Screen Shot 2023-12-15 at 1 32 11 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/8020a06e-5bd2-4c2e-906e-55ace0d9708f">
