### ISSUE TITLE
Spell Effect: Shifting Form

### ISSUE THREAD

**Issue by DoctorDankovsky** [foundryvtt/pf2e#12281]
They forgot to mention swim speed in the text.

**Comment by stwlam** [comment]
Who is they?

**Comment by simonward** [comment]
Cannot reproduce.
<img width="693" alt="Screen Shot 2023-12-15 at 6 21 32 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/cefe6202-7f49-424d-9eb0-0694cbe7d989">

<img width="222" alt="Screen Shot 2023-12-15 at 6 21 54 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/7d736f94-1855-4bb0-98b8-f3ae44276cc8">
