### ISSUE TITLE
(alchemy) crafting feature requests/improvements

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#12323]
just added >60 alchemical items to my lvl 7 PFS alchemist i'm importing from r20, and the method of preparing at the start of the day is not great in foundry (nor in r20 either), it could do with stuff like being able to collapse each lvl of stuff, maybe a text search field, scrolling up and down to the lvl 3+ stuff i'm preparing is tedious, i could delete the formulae of lvl 1-2, but i need those cause i've got perpeptual infusions at 7...which can only be used with those!
i've not even got anything from TV on this alch, cause they've not been really played since it came out! (i could have quite a few more items!)
there could also do with being a way to prepare 0 to just have it in the list
also for there to be a way to look at the items in the prep list, without having to find it in the compendium or scrolling down past 40+ items to find it in the formulae

**Comment by stwlam** [comment]
Crafting likely won't see improvements until PC2. Please see existing issues, as most of this is covered in a more specific way.
