### ISSUE TITLE
@actor.level on the Kingdom Sheet looks at the level of the party instead of the Kingdom

### ISSUE THREAD

**Issue by SoupcanAnthill** [foundryvtt/pf2e#12320]
I'm trying to set up Untrained Improvisation for the Kingdom sheet, and the Flat Modifier rule is being weird.
I've got it set up to add to kingdom checks right, but the modifier is wrong. 
I've got it pointed at @actor.level, but it seems like it's looking at the actual character's level in the party sheet, because it thinks the level is 4, which is what the party is, but the kingdom is only 2.
I've tried @kingdom.level which just breaks it.

**Comment by CarlosFdez** [comment]
`@actor.level` cannot work since that's the party, but `@kingdom.level` should. It'll be resolved by the next release.
