### ISSUE TITLE
Scroll and wand spells shouldn't be posted to chat on failed Trick Magic Item checks

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#12339]
pf2e v 5.11.4
As per Player Core:
![image](https://github.com/foundryvtt/pf2e/assets/81383360/4971ac0d-8748-4e39-845f-33b2c53ee28d)

Current behaviour:
[Peek 2023-12-17 01-33.webm](https://github.com/foundryvtt/pf2e/assets/81383360/88623459-8e62-41ca-b7ae-dc7cf3d5278e)

**Comment by stwlam** [comment]
Hi, can you say what specifically is "per Player Core"?

**Comment by Symon-S** [comment]
From the wording it would seem to infer that the items cannot be used at all without first succeeding on the check. Would be weird to consume a wand or scroll that you can't even activate.
It doesn't state that a skill needs to be trained in to be used, so I will change the title. 🤔

**Comment by nikolaj-a** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/6374503/4a0853ce-51a7-441f-8941-3df996ce1433)

**Comment by Symon-S** [comment]
@nikolaj-a That's just the prerequisite for taking the feat I believe. It doesn't say in the actual text that you need to be trained in a skill you use to trick the item though, but I may be wrong on that one 🤷‍♂️

**Comment by nikolaj-a** [comment]
I guess the distinction matters very little, given how hard it'll be to actually succeed at the untrained check with any sort of reliability beyond, like, level 2 or 3.

**Comment by Symon-S** [comment]
Only really matters when you have untrained improvisation, when needing to be actually trained in a skill to use trick magic item would be make a real difference.

**Comment by Symon-S** [comment]
Withdrawing this feature request
