### ISSUE TITLE
Summon trait should list standard level progression

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#12377]
it strikes me that this line is basically useless info in the system, cause the tooltip for the trait doesn't help
![image](https://github.com/foundryvtt/pf2e/assets/88220878/56c380e6-7766-4ff6-846c-4ea1e1a6f69c)
given the lvl of summons is standardised, would it be possible to automate what lvl it says in the text?
i.e. "You summon a creature that has the [trait depending on spell] trait and whose level is [something that pulls from a table or something and says the right lvl] or lower to fight for you."

**Comment by TikaelSol** [comment]
We can do an `@Localize` call to handle it.
