### ISSUE TITLE
Feat not updated - Sorcerer Bloodline Focus 12

### ISSUE THREAD

**Issue by Steven-Soult-Jr** [foundryvtt/pf2e#12387]
I haven't seen this mentioned anywhere, but the Sorcerer feat at level 12 Bloodline Focus is still the old non-remaster version. It reads:

If you have spent at least 2 Focus Points since the last time you Refocused, you recover 2 Focus Points when you Refocus instead of 1.

Like the other level 12/14 focus feats, it should instead read:

Whenever you Refocus, completely refill your focus pool.

**Comment by TikaelSol** [comment]
Less a data error and more that we are still waiting on Paizo to release player core 2, the removal of the level 18 wellspring feats for classes not yet remastered was probably premature on our part.
