### ISSUE TITLE
Feature Request: ABP (Fundamental Runes Only)

### ISSUE THREAD

**Issue by LJSmith066** [foundryvtt/pf2e#12391]
I will Paypal, Venmo, Send to Charity of Choice or Post By Letter a Sum of 5 Genuine Australian Dollars To Whomever Fulfills This Humble Request

(there are mods that integrate this feature, however it would be lovely to have it included in the base pf2e module)

**Comment by TMunsie** [comment]
As this is not an official variant it will not be added to the core system. At least not until Paizo publishes it as a core variant.
