### ISSUE TITLE
Duskwalker Heritage not adding Darkvision to Low-Light Vision Ancestries (tested with Elf)

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#12404]
With no modules at all, made a new character that's an Elf. Gave them Duskwalker Heritage and they didn't get Darkvision even though the heritage says "You also gain Low-Light Vision, or you gain Darkvision if your ancestry already has low-light vision.".

**Comment by stwlam** [comment]
Closed by #12362
