### ISSUE TITLE
precious material weapons adding the price of weapon incorrectly

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#12403]
the stated price of a precious material weapon is always just the price+1/10 of that price per bulk
rule reference: all the weapons on this page: https://2e.aonprd.com/Equipment.aspx?Category=37&Subcategory=38, the same is the case for armour btw, found on the corresponding page for armour: https://2e.aonprd.com/Equipment.aspx?Category=11&Subcategory=12 just in case that's also wrong in the system - nothing ever says to add the price of mundane version of the weapon/armour, so you don't!

**Comment by stwlam** [comment]
If you can say what exactly is wrong, we'd be happy to address it.

**Comment by dharkus5000** [comment]
there's an orichalcum sickle in some loot somewhere in an AP, and it's auto-calculated the price to be 2sp, 24750gp - the 2sp shouldn't be there

**Comment by dharkus5000** [comment]
i can only assume this isn't a 1-off case, but maybe it is?

**Comment by dharkus5000** [comment]
can confirm, not a 1-off, just created a greatsword in the same loot actor, tried with lots of precious mats and they all added 2gp to the price incorrectly

**Comment by CarlosFdez** [comment]
This is if you add precious materials to a weapon without any runes? I'm not sure what's actually supposed to happen in that case, but I don't know if precious materials have the "ignore the base price" clause.

I can see that taking a steel shield and making it adamantine yields the incorrect result though, 486gp instead of 440gp https://2e.aonprd.com/Equipment.aspx?ID=310

**Comment by dharkus5000** [comment]
the price is the stated price, nothing mentions adding the mundane price to it anywhere, the price of an orichalcum sickle is 24750gp, that's what it says in the rules
`Price 22,500 gp (+ 2,250 gp per Bulk)` which, for a sickle, which is counted as 1B as that's the minimum bulk for this calc, as stated elsewhere (https://2e.aonprd.com/Rules.aspx?ID=731 `The Price entry for each material gives the Price of a simple non-magical item made of that material, based on its Bulk (if the item is lighter than 1 Bulk, use the price for 1 Bulk), as well as Prices for different amounts of the material itself. `) so 22500+2250=24750gp, the price of the non-precious version is never mentioned anywhere
