### ISSUE TITLE
Dread Marshal Stance Flat Modifier value fails to resolve after rolling an inline damage roll

### ISSUE THREAD

**Issue by pedrogrullada** [foundryvtt/pf2e#12426]
I'm not sure if it's more general than this, but here is how I reproduce it.
- Create an actor that contains some inline `@Damage` rolls
- Add Marshal Dedication and Dread Marshal Stance 
- Apply the stance to the character
- Click an `@Damage` link, such as from a kineticist impulse feat
- The damage bonus should not be working at this point. If you open the stance on the character via the edit button, you'll see `@item.origin.flags.pf2e.highestWeaponDamageDice` is unable to resolve, which was not present before rolling from the `@Damage` link.

Here is the full console warning
```
pf2e.mjs:1646 PF2e System | Flat Modifier rules element on item Effect: Dread Marshal Stance (Actor.tMLZY6UhrNGUDvl9.Item.ysdzLZavUuxvUBYl) failed to validate: unable to resolve formula, "@item.origin.flags.pf2e.highestWeaponDamageDice"
```

and here is a video reproducing the issue, PF2e 5.11.5 without any modules. In it, I roll damage with a weapon first, just to show that the damage bonus is working correctly prior to rolling the inline damage button.

https://github.com/foundryvtt/pf2e/assets/103401186/e10ab482-3d23-4beb-bd62-e9370e80d576

**Comment by stwlam** [comment]
Does the order matter, or can I roll with a kineticist first?

**Comment by pedrogrullada** [comment]
> Does the order matter, or can I roll with a kineticist first?

It doesn't, it was simply to note that the RE works prior to rolling with the kineticist feat
