### ISSUE TITLE
Variant Spells result in "cannot read properties of undefined reading 0" error

### ISSUE THREAD

**Issue by XChipXx** [foundryvtt/pf2e#12454]
Trying to cast a spell with at least one variant listed (eg. Heal, Needle Darts,..) will result in an error and no entry posted in chat as usual.

Foundry, system etc is up to date and already reinstalled, modules are deactivated.
Deleting the variants makes the error go away.²

**Comment by stwlam** [comment]
This is typically a symptom of installing V11 on top of V10 (that is, without uninstalling V10 first). Might that be the case here?

See, e.g., https://github.com/foundryvtt/foundryvtt/issues/9330.

**Comment by XChipXx** [comment]
Yeah i thought so too, but i reinstalled foundry on my server and nothing changed...

**Comment by stwlam** [comment]
Unfortunately this isn't enough information to speculate on (besides the common issue). If you come to the system's foundry server (https://discord.gg/pf2e), we can help you troubleshoot.
