### ISSUE TITLE
Savant's Curse should be called Sage's Curse

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#12467]
Screenshot from AV hardcover PDF:

![image](https://github.com/foundryvtt/pf2e/assets/6516621/307f8ed8-cd37-4c23-883e-56e55be74a8c)

I think that spell's name was changed between the original release and the hardcover.

**Comment by TikaelSol** [comment]
Yeah, this is from Paizo removing all uses of the word savant, which started happening after the initial books.
