### ISSUE TITLE
Undead trait adds bleed immunity

### ISSUE THREAD

**Issue by HenriDeh** [foundryvtt/pf2e#12472]
PCs and monsters with the undead trait are immune to persistent bleed damage. This is a bug. 
This immunity is not provided by the undead trait (https://2e.aonprd.com/Traits.aspx?ID=160), and additionally, if it was the case, the immunity should appear in the PC/NPC statblock (it does not). 

I tested on the current version, no modules, on a PC with zombie dedication. Removing the dedication allows bleed damage, adding back only the undead trait disallows it again. So the issue comes from the trait.

**Comment by TikaelSol** [comment]
Player Core page 409

> Another special type of physical damage is bleed damage. This is persistent damage that represents loss of blood. As such, it has no effect on nonliving creatures or living creatures that don’t need blood to live.

**Comment by farling42** [comment]
Note that Monster Core explicitly lists bleed in the immunities sections of relevant creatures, whereas the old Bestiaries did not list this as a separate immunity.
