### ISSUE TITLE
Feature request: Allow to change base damage type of spells when casting

### ISSUE THREAD

**Issue by Suldrun45** [foundryvtt/pf2e#12487]
Some spells like Shadow Blast, Spiritual Armament, etc... require the caster to choose the damage type of the spell when casting.
In the spell details tab, the damage type is set to a default type (usualy "untyped")
There is currently no way to select the effective damage type (except with a Roll Option + Damage Dice RE or by defining spell variantes, which might not always be practical/possible to do) and it might be interresting for automating those spells in IWR

So, with the  implementation of the damage dialog, which allows to add extra damage dices/modifiers and to select their damage type, I was wondering if something like adding a damage type dropdown next to the base damage of the spell would be possible?

**Comment by bradfordtfm** [comment]
Also the feat 'chaotic spell' which changes the damage type of a spell. having the ability to change the damage type of a spell for a single use, without modifying, and then returning proper settings would be helpful.
