### ISSUE TITLE
Remove migration notification on migration completion

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#12497]
Tiny QoL improvement.

This change should be easy, but I'm not creating a PR for it because there's a chance you want to do the same for more notifications in the system that I'm not thinking of.

See code here - https://github.com/foundryvtt/pf2e/blob/master/src/module/migration/runner/index.ts#L325

```        ui.notifications.info(game.i18n.format("PF2E.Migrations.Starting", { version: systemVersion }));```

Just add `const notificationId = ui.notifications.info...` there, and then at the end of the function add `ui.notifications.remove(notificationId)`.

**Comment by stwlam** [comment]
They notification goes away on its own, and I'd rather not have it show up for an unreadably low amount of time for a migration that finishes quickly.
