### ISSUE TITLE
Ephemeral Effects doesn't work with effects that adjusts skill check

### ISSUE THREAD

**Issue by xXParryXx** [foundryvtt/pf2e#12521]
Ephemeral Effects doesn't appear to work with effects that adjusts skill checks

So I have a spell that applies an effect to a target that is intended to give anyone targeting them a bonus in strikes and certain skill checks(ex trip, demoralize, recall knowledge and feint, and more these are just some of the ones that aren't working via this way) don't apply their effects properly.

But if one applies the effect that the ephemeral effect is referring to the skill checks gets the appropriately set bonus

example code of the ephemeral effect and its referred flat modifier
`{
  "key": "EphemeralEffect",
  "uuid": "Compendium.the-avenger-pf2e-class.effects.Item.2VIxA29vmfIORXI6",
  "selectors": [
    "all"
  ],
  "affects": "origin"
}`

`{
  "key": "FlatModifier",
  "selector": [
    "attack",
    "intimidation-check"
  ],
  "value": 1,
  "type": "status"
}`

the attack modifier get properly applied via ephemeral but the skill check doesn't, but when the flat modifier effect is manually applied it works as i was intending it to work via the ephemeral effect

**Comment by stwlam** [comment]
Are you Demoralizing or just making a check? Skill checks by their lonesome aren't targeted.

**Comment by xXParryXx** [comment]
i am using specifically the action demoralize, and i can't get the status affect to apply automatically via ephemeral effect rules but it does work when i apply the flat modifier directly to the actor manually, otherwise it can only apply the status bonus to attack rolls.
Effect applied manually to actor(effect is called judgement
![image](https://github.com/foundryvtt/pf2e/assets/54803660/fad91ff8-b210-40cc-ad86-03288d11c74b)
![image](https://github.com/foundryvtt/pf2e/assets/54803660/e4e8b9cf-1c89-45f6-adeb-5f22839c157f)
status bonus should be applied via ephemeral effect
![image](https://github.com/foundryvtt/pf2e/assets/54803660/1219dc3e-d0aa-4a19-8c17-59dc7b929290)
![image](https://github.com/foundryvtt/pf2e/assets/54803660/c956a790-c361-43c4-986f-072a25d1d1e8)

**Comment by xXParryXx** [comment]
Bug has been found and discussed on the PF2E foundry discord aswell before in #development-help https://discord.com/channels/880968862240239708/880969304365994034/1188955834290536519
![image](https://github.com/foundryvtt/pf2e/assets/54803660/7d04aa76-840b-4bfb-9240-64726c93b6c4)

**Comment by Cerapter** [comment]
Unfortunately managed to confirm that this bug still exists in 6.7.2.

Additionally, I and Tikael noticed the following:
- Even if the effect granted by the EphemeralEffect doesn't seem to visibly affect the check, it still appears in the roll inspector.
- The skill checks mentioned in the description no longer function correctly: now, only Strikes receive the EphemeralEffect's effect in time for it to actually affect the check.
- This seems to only be an issue with REs that are supposed to affect the check itself -- if you have an effect granted with an EphemeralEffect like this, and it has a FlatMod and a Note RE, the FlatMod doesn't get applied, but the Note will appear.
