### ISSUE TITLE
Spell Purifying Icicle has attack roll not Fort save

### ISSUE THREAD

**Issue by armydillo2025** [foundryvtt/pf2e#12536]
Spell Purifying Icicle has the attack trait and an attack roll instead of a Fort Save.
https://2e.aonprd.com/Spells.aspx?ID=1122

**Comment by DocSchlock** [comment]
"You evoke life essence into the form of water and freeze it, then launch the icicle at a foe. Make a spell attack roll. On a success, the icicle deals 2d6 piercing damage and 1d6 cold damage, and if the target is undead, the icicle deals an additional 1d4 positive damage. On a critical success, the target takes double damage and takes a –10-foot circumstance penalty to its Speeds for 1 round as the icicle lodges inside them before melting away."

The fortitude save appears to be a misprint given the description of the spell itself is a Spell Attack.

**Comment by TikaelSol** [comment]
We'll go with the spell description, since a fort save makes no sense given that it's not basic and there's no set outcomes.
