### ISSUE TITLE
Configure Art Menu

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#12530]
I propose adding a menu to PF2e system settings to configure the priority of art modules.

This would allow for people to create their own custom token packs without having to worry about being overwritten by other modules, as currently the only way to determine "priority" is, as far as I am aware, the alphabetical order of module IDs.

The 5e system already includes this sort of menu, though it could certainly be improved upon.
![image](https://github.com/foundryvtt/pf2e/assets/32039708/528073bf-134e-4154-995b-6c11f372ee44)

It would be great to have this implemented, as often people want to create copies of existing tokens with a different token border or image, like adventure path NPCs for example, only to find out they have to import and manually change the images around, and most importantly are unable to share the custom tokens in module form.

**Comment by stwlam** [comment]
It's planned. Someone just needs to get around to it.

**Comment by stwlam** [comment]
planned ... by upstairs!

**Comment by MrVauxs** [comment]
This one I see? https://github.com/foundryvtt/foundryvtt/issues/11125 👀
