### ISSUE TITLE
Add Strike Degree of Success to Roll Options for Strikes

### ISSUE THREAD

**Issue by avagdumortesin** [foundryvtt/pf2e#12598]
If DoS is added to Roll Options on Strikes, it can be predicated on for features such as Confident Finisher and Precise Strike from the Swashbuckler, enhancing the automation on these features.

In the case above, allowing the weapon Strike damage to be turned off on the damage card would also be helpful.

**Comment by nikolaj-a** [comment]
Roll options are defined and used _before_ doing the roll. Outcome is determined _after_ the roll is done and compared to a DC.
