### ISSUE TITLE
Scroll Thaumaturgy Feat should add Items Only Spellcasting Entry

### ISSUE THREAD

**Issue by apuma32** [foundryvtt/pf2e#12594]
When the Scroll Thaumaturgy Feat is added to a character sheet, 
The Items Only Spellcasting option should be added.
![image](https://github.com/foundryvtt/pf2e/assets/154711470/192cf5fb-2b70-4cfe-a373-9d6f768adf3f)
So that players do not receive the "$Player lacks the proficiency to use $scroll.name and does not have the trick magic item feat." message. and does not have to manually add the spellcasting entry.
-or- 
the toast message should include instruction that a player with this feet must manually add the spellcasting entry

**Comment by stwlam** [comment]
Spellcasting entries in general aren't added automatically.

**Comment by apuma32** [comment]
@stwlam is it possible to modify the scroll rules to allow casting when this feat is active? (as i assume it does when you have trick magic item)

**Comment by stwlam** [comment]
Spellcasting entries aren't currently possible to grant.
