### ISSUE TITLE
The "Sustain An Effect" Exploration Activity seems to be missing

### ISSUE THREAD

**Issue by SAOFan4Ever** [foundryvtt/pf2e#12652]
While putting together a list of actions that I should put on a new player's character sheet I noticed that the exploration activity Sustain an Effect was not in the system yet. Below is the text so that someone can add it in.

SUSTAIN AN EFFECT

Tags: CONSENTRATE  EXPLORATION

You  Sustain  one  effect  with  a  sustained  duration  while 
moving at half speed. Most such effects can be sustained for 
10 minutes, though some specify they can be sustained for a 
different duration. Sustaining an effect that requires making 
complex decisions, such as  spectral weapon, can make you 
fatigued, as determined by the GM.

Source: Player Core pg. 439

**Comment by TikaelSol** [comment]
The Sustain an Effect action was removed in the remaster, merging with Sustain a Spell into a generic Sustain action.
![image](https://github.com/foundryvtt/pf2e/assets/80183198/7f2f64e7-622e-44c7-8f18-a53872c50901)

**Comment by TikaelSol** [comment]
Ah, the exploration activity is still called that.
