### ISSUE TITLE
add 2 related effects for KM

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#12673]
Some creatures in Kingmaker Ch 10 pt 3 have a shame ability, and this ability is related to the Forgive Foe action
i've created 2 effects for these 2 things, guess the shame one could be just inserted into the shame ability, and the forgive foe effect could be added to the text for the success 

**For the Shame action**
`{
  "key": "FlatModifier",
  "value": -2,
  "type": "status",
  "label": "Shame",
  "selector": [
    "inline-dc",
    "spell-dc",
    "attack-roll"
  ],
  "predicate": [
    "shamed-by-foe"
  ]
}`
and also 
`{"key":"RollOption","domain":"all","option":"shamed-by-foe","toggleable":true,"label":"Shamed by Foe"}`

**For the Forgive Foe action's sucess entry**
`{
  "key": "FlatModifier",
  "value": -2,
  "type": "status",
  "label": "Forgive Foe",
  "selector": [
    "attack",
    "inline-dc",
    "spell-dc"
  ]
}`

the AP says penalty to att rolls for shame, and penalty to att for the forgive foe action, it's possible they meant these 2 to be the same thing...but the above have them as different, guess you could editorialise and make em the same...

**Comment by dharkus5000** [comment]
i can find and list the effected creatures that have the shame ability if that'd help?

**Comment by stwlam** [comment]
Thanks, but this isn't the correct area for pull requests. You'll want to add them here: https://github.com/foundryvtt/pf2e/pulls

**Comment by dharkus5000** [comment]
i've no idea what a pull request is compared to an issue, and how to create one

**Comment by dharkus5000** [comment]
tried creating a PR, don't have permissions to do so

**Comment by InfamousSky** [comment]
https://github.com/foundryvtt/pf2e/wiki/Helping-with-Data-Entry
