### ISSUE TITLE
Flanking lines should show in out-of-focus scenes

### ISSUE THREAD

**Issue by Gurrgel** [foundryvtt/pf2e#12697]
Holding Alt to Check for Flanking seems to break whenever a player is logged in for the game. Without a player in my game, with a setup like the image below, it seems to work as intended, showing that the YOU token is flanking the Enemy Token.
![image](https://github.com/foundryvtt/pf2e/assets/99760890/dd737803-ae02-4028-950b-df66798622ce)

With a player logged in, the same situation looks like this.
![image](https://github.com/foundryvtt/pf2e/assets/99760890/100c6df8-cba1-4d3b-9e4e-e7b579239bae)

This happens whether the player owns the flanking token or not, and whether they're on the same scene or not. This also means that a player can never check for flanking themselves, not even if the GM is offline and the player is alone on the server. I'm getting this even with no modules active.

Foundry Version: 11.315
Pathfinder Version: 5.8.2, although from a discord discussion, a user with version 5.11.5 was able to reproduce this issue on their version as well.

**Comment by websterguy** [comment]
Seems to only happen on a scene that is not active. Active scene works fine.

**Comment by stwlam** [comment]
There's an intentional requirement that the scene be in focus (either the GM is logged in alone or players are logged in and the scene is active), but that's probably not necessary.
