### ISSUE TITLE
Blade Ally Disruption/Vitalizing 

### ISSUE THREAD

**Issue by SOM1better** [foundryvtt/pf2e#12722]
The text for the Champion's Blade Ally class feature lists Disrupting, Ghost Touch, Returning, Shifting & Fearsome as options for the effect. 

<img width="327" alt="ally" src="https://github.com/foundryvtt/pf2e/assets/65267919/c3dbf2b5-706c-4abe-97b6-2179c58341fb">

The effect lists the same options: 

<img width="326" alt="effect" src="https://github.com/foundryvtt/pf2e/assets/65267919/b4e421a2-d4bd-437e-812d-56383d449a6a">

When the effect is applied however Disrupting is not an option and it has been replaced with Vitalizing. 

<img width="150" alt="apply" src="https://github.com/foundryvtt/pf2e/assets/65267919/6c95f946-0bda-4efd-af69-eed211c034c0">

I'm not sure if this is intended or not. The Vitalizing effect is stronger as it deals persistent damage and I can't find any errata for the Blade Ally effect or anything that says Disrupting was renamed to Vitalizing. However. Disrupting was excluded from the Remaster books and other that the persistent damage the runes have nearly identical wording and are the exact same level and price. 

Regardless of what one ends up being the intended effect the text of Blade Ally description and applications should match.

**Comment by stwlam** [comment]
Vitalizing replaced Disrupting as a rune in GM Core. Paizo may reconfigure the entire feature/feat line with a different schedule of runes, but we won't know until later this year. We'll get the class feature description updated.
