### ISSUE TITLE
Please reopen Issue #9394 to fix my mistake.

### ISSUE THREAD

**Issue by SAOFan4Ever** [foundryvtt/pf2e#12771]
In issue #9394 I suggested a change to sacks since you can get 5 for 1 cp, so the quantity was changed to 5. In #9707 stwlam explained that you couldn't just do that because there is no place in the data to do this. I assumed that this suggestion was disregaurded, but today I found out in made it in. As I understand it foundry assgins a different UUID for each sack, so that means despite the quantity looking correct you actually have only have one. Sorry for the bad suggestion I'll try to be more careful in the  future.

**Comment by stwlam** [comment]
That issue is still open.

**Comment by SAOFan4Ever** [comment]
Okay I saw that  was marked as closed on Aug 30th 2023. But doesn't the system giving out 5 sacks with the same UUID cause a problem still?

![Sack issue](https://github.com/foundryvtt/pf2e/assets/142608632/4e6e3931-0624-49d6-8ea9-163f6c462366)

**Comment by TMunsie** [comment]
Just change the quantity to 1 and make five of them. Containers that stack are a weird idea. Sacks are used so infrequently it is really not worth the time to code it, similar to a bullseye lantern - the only thing in the entire system where the direction your token is facing matters.

**Comment by SAOFan4Ever** [comment]
I guess that's a fair point. I just figured that it might be a bit annoying for GM's to change to quantity everytime they want to use one. Especally now that I uderstand why the quantity was orginally 1.
