### ISSUE TITLE
Feature request: Light cantrip to have a draggable actor for the secondary use of the remastered light cantrip.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#12778]
![image](https://github.com/foundryvtt/pf2e/assets/139762764/b25d5170-107c-449b-ad93-e8ba254bd4ad)
![image](https://github.com/foundryvtt/pf2e/assets/139762764/fd863229-8c00-4a66-a396-582fc2abd1fe)
What would be useful to have would be a draggable actor with the light spell on it. 

because templates dont have a light source. 
but a dummy actor that could be assigned to a pc could fix this issue. just something in the compendium to be able to enable this would be useful.

**Comment by stwlam** [comment]
You can drag the effect to any actor.
