### ISSUE TITLE
Expanding the search features in the compendium - Feats [feature suggestion]

### ISSUE THREAD

**Issue by LeChatLunatique** [foundryvtt/pf2e#12799]
Some of my new players are scratching their heads when they need to select feats.
Someone asked if it was possible to sort more accurately, like having negative search words etc. I find his idea very interesting.
There is no solution atm for sorting them like that.
Most of them have Expert or more requirements, needs some earlier feats or are tied to a dedication and there is a TON of them.
Is this something the system devs might add one day ? It will make this step less overwhelming for new players if they can have less clutter in front of them.

What I can suggest is some kind of negative search word to filter the prerequisite.
Something like "-dedication, -expert" and it will sort every feats and remove the feats with a dedication and an expert level requirement.

Having new players have to go to a thirdparty website/tool to search more accurately, if its even possible is always troublesome.
Mine are always completely lost on Nethys for exemple !

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated issue #6588
