### ISSUE TITLE
Feature Request: expand the refresh to one click for the whole character sheet to be refreshed

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#12808]
i love the refresh function on each inventory item. if it could be improved to have a refresh on the top of the character sheet to refresh all at once. would be super useful.

**Comment by stwlam** [comment]
Sorry, but you'll have to settle for a macro to do this. It's not a very intelligent process and can reverse customizations on a character with no recourse except to restore from a backup.
