### ISSUE TITLE
Unable to create Kingmaker Journal entries

### ISSUE THREAD

**Issue by mkniller** [foundryvtt/pf2e#12826]
After the latest update I am now unable to change the type of journal.  The button is missing on any new journal entry I create, however all previously existing journal entries still have the button.

New Journal Entry
![image](https://github.com/foundryvtt/pf2e/assets/8039354/a3affe32-61d6-4d1c-b0da-ac3a4e4abdf4)

Existing Journal Entry
![image](https://github.com/foundryvtt/pf2e/assets/8039354/6827601e-9022-46b2-bb9b-afca4c0aea37)

Existing Journal Entry with config menu
![image](https://github.com/foundryvtt/pf2e/assets/8039354/3a8e4ce4-9f53-47a6-909c-d0c6d1b336e7)

**Comment by stwlam** [comment]
This is the module hiding the option.

**Comment by TMunsie** [comment]
This has nothing to do with the system. Please report it to the module if you have an issue. We can’t influence downstream module settings.

**Comment by mkniller** [comment]
Understood.
