### ISSUE TITLE
CreatureSize RE for Corgi Mount issue

### ISSUE THREAD

**Issue by Suldrun45** [foundryvtt/pf2e#12822]
I'm trying to make a Corgi Mount familiar.
For that, I have added a custom Ability on the familiar's sheet and placed the following RE in it:
{"key":"CreatureSize","value":"small"}

Up to there, no problem, the "Small" trait is displayed correctly on the sheet and the token gets a small size, but when I reload the VTT, the token size gets back to tiny, although the "Small" trait remains displayed on the familiar's sheet.

**Comment by GorgoPrimus** [comment]
Does it not update if you move that token around a bit? That’s what fixes mine, for what it’s worth.
