### ISSUE TITLE
Burn It!'s persistent fire and non-alchemical weapons

### ISSUE THREAD

**Issue by axerwan** [foundryvtt/pf2e#12823]
The persistent damage bonus from the Burn It! goblin feat only applies to alchemical items and spells, even though it should apply to all instances of persistent fire damage dealt by the actor, such as a critical hit with a flaming weapon.
![image](https://github.com/foundryvtt/pf2e/assets/119694829/6b2248c8-84f0-4889-9b32-c8983de5c29e)

Now that we have the damage dialog box showing up before rolling it can be turned on manually, but it'll be doubled on the crit, which shouldn't happen with a flaming weapon since its persistent damage is not doubled on a critical hit.
![image](https://github.com/foundryvtt/pf2e/assets/119694829/6bc9a451-ae2d-4cdd-8c61-b7b6286d8f29)

If that helps, I also added the alchemical trait to a flaming battle axe for testing purposes, and Burn It's persistent damage was added, even though the battle axe deals no persistent damage on a normal hit.
![image](https://github.com/foundryvtt/pf2e/assets/119694829/41c01fed-ce2c-426d-8e0b-b61af255f4c7)

I also tried out a Dwarven Daisy (a bomb that deals fire damage but no persistent) and Burn It works as intended here: extra fire damage, but no extra persistent

**Comment by stwlam** [comment]
Changed in Player Core:
![image](https://github.com/foundryvtt/pf2e/assets/106829671/9f427dd8-a6cd-4743-9c5e-0169f26f8f7a)

**Comment by stwlam** [comment]
Sorry, I misread you as saying the opposite!
