### ISSUE TITLE
Low-light vision gets replaced by Darkvision

### ISSUE THREAD

**Issue by Bhalandros** [foundryvtt/pf2e#12867]
Low-light vision is erroneously replaced instead of coexisting when applying a Heritage that grants Darkvision if the race already has Low-Light Vision (or just grants Darkvision in general)
![one](https://github.com/foundryvtt/pf2e/assets/27706374/970bbb63-aff1-40f5-b563-6635aa07086f)
![two](https://github.com/foundryvtt/pf2e/assets/27706374/03499df6-f5d1-4656-a0e2-713cb7f3d31e)
![three](https://github.com/foundryvtt/pf2e/assets/27706374/9e7dc6d5-88e1-4a05-9267-de1a446e6ea8)

**Comment by stwlam** [comment]
Darkvision mechanically supplants low-light vision, with the latter doing nothing if the former is also present.

**Comment by CarlosFdez** [comment]
There are also ways to get darkvision without low light vision, and its functionally equivalent (the darkvision spell, or fetchlings).

**Comment by Bhalandros** [comment]
I believe the specific difference is that Darkvision is black and white, while Low-light vision is full color but only works in Dim Light, and not Darkness. I was under the impression that having both Low-Light vision and Darkvision meant that one could see in Darkness in black and white and in Dim Light in full color. Is this not correct?

**Comment by Drental** [comment]
creatures without low-light-vision can see in dim light with no mention of losing the ability to perceive colors, the only thing that low-light-vision changes is that it removes the concealed condition flat chack due to dim light.

Darkvision should always see at least as much color as a no-special vision character.

**Comment by Bhalandros** [comment]
> A creature with darkvision or greater darkvision can see perfectly well in areas of darkness and dim light, though such vision is in black and white only.

I was going off of this, but I might be wrong after all. Alright.

**Comment by Drental** [comment]
> Areas in shadow or lit by weak light sources are in dim light. Creatures and objects in dim light have the concealed condition, unless the seeker has darkvision or low-light vision (see Special Senses on page 465), or a precise sense other than vision.

compare to

> A creature or object within darkness is hidden or undetected unless the seeker has darkvision or a precise sense other than vision (Special Senses are on page 465). A creature without darkvision or another means of perceiving in darkness has the blinded condition while in darkness, though it might be able to see illuminated areas beyond the darkness. If a creature can see into an illuminated area, it can observe creatures within that illuminated area normally. After being in darkness, sudden exposure to bright light might make you dazzled for a short time, as determined by the GM.

and note that there is no mention of color here or anywhere in relation to dim light alone, only ignoring a condition if it is caused by a specific circumstance.

> The monster can see in dim light as though it were bright light, so it ignores the [concealed](https://2e.aonprd.com/Conditions.aspx?ID=4) condition due to dim light.

also compare to 

> Your family have been alchemists, engineers, and scientists for generations, on projects bringing smoke and fire to the field of battle. You gain [fire](https://2e.aonprd.com/Traits.aspx?ID=72) resistance equal to half your level (minimum 1). You automatically succeed at the DC 5 flat check to target a [concealed](https://2e.aonprd.com/Conditions.aspx?ID=4) creature if that creature is concealed only by smoke.

and I don't think you'd lose colored vision on a target that is concealed, but not hiddem by smoke (or fog for other feats)

**Comment by stwlam** [comment]
This language changed over the course of over the four printings of the CRB, but it's now (usually) careful to separate when the black-and-white vision applies. Looking at any ancestry, for example:

> You can see in darkness and dim light just as well as you can see in bright light, though your vision in darkness is in black and white.
