### ISSUE TITLE
Feature request: change "Blind GM Roll" to "Secret Roll" or similar

### ISSUE THREAD

**Issue by bogga** [foundryvtt/pf2e#12874]
Maybe make this optional? It would be handy to use pf2e terminology for the Blind GM Roll option, reduces the gap between the rulebook and foundry by a bit more

**Comment by stwlam** [comment]
These are terms set by the foundry software rather than the system. There's an open issue with a similar request here: https://github.com/foundryvtt/foundryvtt/issues/9864
