### ISSUE TITLE
Restored HP from Rest seem not to be published via Socket to other clients

### ISSUE THREAD

**Issue by STBaf** [foundryvtt/pf2e#12870]
Foundry V11.315
System: PF2 5.12.2

When a player push the Rest button on the character sheet the char rest and HP get restored. This change on the HP value by rest seem not to be published by websocket to other clients (aka no update is made) and is only send around when character sheet is closed.

We habe noticed that in a session today and were able to reproduce the following behavior:

1. Actor has reduced hit points (for example: 24 of 36)
2. Two people (the player and the GM) have the char sheet of that Actor open
3. Player press Rest button. HP are restored (in our example: 4). HP go up on player sheet (from 24 to 28 in our example) but not on the sheet that is open by GM (sheet keep showing 24, not the 28 which will be the right value)
4. Since the player session now show 28, but GM session still show 24 it depends wo close sheet now last because closing sheet seem to invoke a update. If player close sheet, HP on GM sheet keep being 24. Then, when GM close sheet last, HP are reduced back to the old value of 24 that was never updated in the GM sheet and the closing GM sheet with wrong value seem to push a update.

If only the player has the sheet open no problem, then HP is saved correctly (or better: not put back when GM close sheet) and when GM open sheet after the change the value is right at 28.
Same when manually changing HP value - if player set manually a HP value this is correctly send around to all clients and change on other clients looking at the sheet the same time. Seem only to happen when HP value is changed by a Rest.

**Comment by stwlam** [comment]
It's an update like any other, so this could be nothing more than server latency.
