### ISSUE TITLE
Shield material type overrides manual stats

### ISSUE THREAD

**Issue by tevwoods** [foundryvtt/pf2e#12897]
https://github.com/foundryvtt/pf2e/blob/274df0e694162065298f930be954f464e2376cbb/src/module/item/shield/document.ts#L101-L115

Because this logic runs in `prepareBaseData`, it always overrides the shield's statistics, even if they are entered manually. I believe this is undesirable because a user may want to reflect that their shield has a specific material type, but also want to tweak the numbers of that shield for a variety of reasons.

Instead of being re-calculated each time `prepareBaseData` is called, is there a way we could have this called just one time when the specific material is first selected or changed? That way the user gets the benefit of automation, but isn't then precluded from customization.

Additionally, modules that want to interact with both the material of a shield and its Hit Points/Hardness have no way around the current system (as far as I can tell), since any values that are given will be overridden by the system itself every time `prepareBaseData` is called.

I've noticed that flagging the shield as a "Specific Magic Shield" will stop this auto calculation, but it also disables the precious material dropdown. As an alternative to the above recommendation (if that's not feasible), maybe we could just no longer disable the precious material dropdown when specific magic shield is checked?

I'm currently in the process of updating the module for Everything Shields and so far I haven't been able to find a way to work around this issue. Thank you for considering this!

**Comment by stwlam** [comment]
This follows the basic rules for material statistics. As you've discovered, you can set an item to be a specific magic item to override anything. You'll of course want to set the material first.

**Comment by tevwoods** [comment]
Yep

My concern is that the current system hinders user customization.

Having to change the precious material before toggling Specific Magic Shield is an obtuse user experience that could use some improvement.

Not being able to change the precious material after Specific Magic Shield is checked is an unnecessary safeguard against nothing.

Thanks for reading
