### ISSUE TITLE
Heightened Enlarge does not inflict clumsy

### ISSUE THREAD

**Issue by Dharengo** [foundryvtt/pf2e#12911]
It does reduce values as if the target were clumsy, but it doesn't actually inflict clumsy.

![image](https://github.com/foundryvtt/pf2e/assets/7268565/0f8cd267-92cb-426b-a5ba-53476af74128)
![image](https://github.com/foundryvtt/pf2e/assets/7268565/129fff24-effb-4141-a5ca-d27c83867170)
![image](https://github.com/foundryvtt/pf2e/assets/7268565/f78dff42-7698-4bf8-9c0f-2128dac23665)

**Comment by simonward** [comment]
This has already been condensed into one effect via https://github.com/foundryvtt/pf2e/pull/10258.

**Comment by TikaelSol** [comment]
The 4th level version of the effect is slated to be removed along with many other condensed effect once a migration is written to replace those links with proper ones.
