### ISSUE TITLE
FR - Add Defense column to Spell-list

### ISSUE THREAD

**Issue by Intervencion** [foundryvtt/pf2e#12910]
Playing a psychic and trying to find my Will spells is a bit annoying, I keep having to open each spell individually
Something like this but better done (?)

![image](https://github.com/foundryvtt/pf2e/assets/13396742/faaada84-0e05-437e-8b16-ef515aa11786)

**Comment by CarlosFdez** [comment]
I can see Defense being a valid column on the sheet
