### ISSUE TITLE
Spell overlays loosing their _id property

### ISSUE THREAD

**Issue by Suldrun45** [foundryvtt/pf2e#12926]
I have been having a few problems since 5.12 with macros that were working previously (in particular the spellstrike macro):
When using this macro with some spells that have overlays, it fails as it cannot find the _id property of the overlay. 

I made a few tests, creating a new spell with overlays and had the same issue. But it doesn't affect every overlay spell. At the moment, I found essentialy that it affects Gouging Claw (Piercing), but there might be others.

From my tests, it would appear that the _id is correctly added to the overlay when it is first created but as soon as you update it (opening and closing the overlay sheet is enough to do this), the _id property gets lost in the process: This seems to be due to the fact that in the "updateOverride" method, the "difference2" object does not have that property.

**Comment by Cuingamehtar** [comment]
While the loss of `_id` field might be unintended, wouldn't it be better to update Spellstrike macro to iterate over `spell.overlays.keys()` and not just over values?

**Comment by Suldrun45** [comment]
I'm not in charge of the macro itself, it's just a macro that I use that comes from Workbench, so there is nothing I can do about this^^

**Comment by stwlam** [comment]
We'll alert the contributors.
