### ISSUE TITLE
Feature Request: Notes field for immunities

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1294]
In GitLab by @SpartanCPA on Apr 7, 2021, 21:22

I've come across a few monsters now that have a note on their immunity, which can't be presented adequately without use of the custom field.

As setting a custom immunity instead of the system version is likely to conflict with the upcoming RWI implementation, we should add a notes field to immunities, similar to the exceptions field of the weakness picker.

Two examples of what I mean:

http://2e.aonprd.com/Monsters.aspx?ID=879

http://2e.aonprd.com/Monsters.aspx?ID=770

**Comment by stwlam** [comment]
Custom immunities are possible.
