### ISSUE TITLE
Witch Cauldron feat missing RE for maxItemLevel

### ISSUE THREAD

**Issue by ottyn** [foundryvtt/pf2e#12957]
PF2e v5.12.4
Foundry v11.315

Found an issue with the latest update to the Cauldron feat REs.  While they do create the crafting entry and adjust for spell DC for quantity, there was no RE entry to handle the feats level restriction on the item level of potions that could be created.  The base Crafting Entry is missing the "maxItemLevel" field and the AE-like RE to change it.

Here is an adjusted version, that takes into account the Item Levels that are able to be created started at 4th level and goes up every 2 levels after that.

![image](https://github.com/foundryvtt/pf2e/assets/97130150/10ea00e4-20cc-4fa9-bbd7-ff94a5345b64)

**Comment by ottyn** [comment]
Crafting Entry RE add "maxItemLevel":1 next to maxSlots.

New AE-like from above RE.
```
{"key":"ActiveEffectLike","mode":"upgrade","path":"system.crafting.entries.cauldron.maxItemLevel","phase":"beforeDerived","predicate":["crafting:entry:cauldron"],"value":{"brackets":[{"end":5,"start":4,"value":4},{"end":7,"start":6,"value":6},{"end":9,"start":8,"value":8},{"end":11,"start":10,"value":10},{"end":13,"start":12,"value":12},{"end":15,"start":14,"value":14},{"end":17,"start":16,"value":16},{"end":19,"start":18,"value":18},{"end":20,"start":20,"value":20}]}}
```

**Comment by pedrogrullada** [comment]
Cauldron does not restrict the level of the created potion or oil as far as I can tell, which is why I didn't include it. Other features do limit the level by virtue of using the Craft language, which Cauldron does not. Happy to PR a change if convinced otherwise.

**Comment by ottyn** [comment]
While the feat doesn't specifically limit it like the Alchemist Dedication does, there is the text in the feat that says you gain a new formula starting at 4th level and every 2 levels after of that level or below of your choice.  Which kind of implies that you can only create potions/oils of your level or lower.  With the REs on the feat currently, at 4th level if you put a 4th level potion in the Daily crafting it will give you a warning that it's too high level.

I guess you could just put in the Crafting Entry RE to have maxItemLevel:@actor.level instead to limit it to your level or lower and not use the second AE-like.

![image](https://github.com/foundryvtt/pf2e/assets/97130150/48faf8dc-c302-444c-bb44-f9e2d5b9ee41)
