### ISSUE TITLE
Button to empty party stash

### ISSUE THREAD

**Issue by yorkshirelandscape** [foundryvtt/pf2e#12954]
Could you please add a button to empty the party stash? Resetting between sessions is a little bit more of a pain than it should be without one. A confirmation popup would probably make sense.

**Comment by TMunsie** [comment]
What is the use case here? Most parties wouldn’t be doing this. If it is for PFS this is better handled by the PFS module and its reset macro.

**Comment by Drental** [comment]
This sounds PFS specific and a bad idea for AP play.

You can delete the party actor and make a new one between sessions

Or you can use a macro like `game.actors.party.deleteEmbeddedDocuments("Item", [], { deleteAll: true });`

**Comment by yorkshirelandscape** [comment]
Are society style campaigns so rare that it's not worth throwing them a bone every so often? I mean, if so, that's fine. Perhaps my perspective is off. 
@Drental I didn't realize there were separate party actors, either, so that makes a little more sense. And thanks for the macro. I may use that.
@TMunsie When you say PFS module? You mean the official ones? Or is there a general PFS module I'm unaware of? If you're using one world for multiple saved adventures, it seems like it would make sense.

**Comment by TMunsie** [comment]
Yes I mean the official module. I can add it to suggestions for Dana working on more PFS support but I think this is not a great idea. And I’m saying that as a 5-glyph GM.

**Comment by yorkshirelandscape** [comment]
Yeah, no worries. I defer to your judgement.

**Comment by stwlam** [comment]
@yorkshirelandscape fwiw, you can't skip the confirmation prompts by CTRL-clicking the delete buttons.
