### ISSUE TITLE
Feature Request: Pathfinder Society Faction Mentorship

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1295]
In GitLab by @sambomb on Apr 7, 2021, 22:43

Add options to modify the level bump to include mentorship
- https://www.organizedplayfoundation.org/Lorespire/pfs2guide._.Factions-and-Reputation#Mentor_Skillful 
- https://www.organizedplayfoundation.org/Lorespire/pfs2guide._.Factions-and-Reputation#Mentor_Magical
- https://www.organizedplayfoundation.org/Lorespire/pfs2guide._.Factions-and-Reputation#Mentor_Rugged
- https://www.organizedplayfoundation.org/Lorespire/pfs2guide._.Factions-and-Reputation#Mentor_Protective
- https://www.organizedplayfoundation.org/Lorespire/pfs2guide._.Factions-and-Reputation#Mentor_Worldly
- https://www.organizedplayfoundation.org/Lorespire/pfs2guide._.Factions-and-Reputation#Mentor_Combat

**Comment by TMunsie** [comment]
Mentorship available via effects. Closing.
