### ISSUE TITLE
Elemental Blast can only have 6 or 8 die faces

### ISSUE THREAD

**Issue by AmondinPC** [foundryvtt/pf2e#12962]
I can't complete the homebrew I'm making in which fire's elemental blast would have 30 feet of range and be a d10, upgrading to a d12 as normal when single gate. Various workarounds aren't effective so far, and this would help a lot!

**Comment by TMunsie** [comment]
The DamageDice rule element can already do this. Please consult the wiki and if you still have issues feel free to ask on the discord.
