### ISSUE TITLE
Items like Arcane Fists create a Fist Strike that overrides Fists from similar items

### ISSUE THREAD

**Issue by axerwan** [foundryvtt/pf2e#12986]
Heya!
The Arcane Fists, Hand of the Lich, Mummy Dedication and Ferrousoul feats, as well as the Stone Fist Elixir effect all use a Strike RE to give a new fist unarmed attack with specific traits, instead of using the new fist shorthand (like in the Powerful Fist class feature or Martial Artist Dedication).
 
Perhaps slightly unrelated, but this led me to discover that: 
- the Spark Fist feat has no effect/automation at the moment.
- the Ghost Wrangler feat _has_ an effect, but it's not linked to/integrated in the feat's text
- Arcane Fists doesn't seem to grant brawling critical specialization as described in the text

Thank you as always!

**Comment by simonward** [comment]
> * the Ghost Wrangler feat _has_ an effect, but it's not linked to/integrated in the feat's text

Ghost Wrangler is a self effect.
