### ISSUE TITLE
Crafting Entry on feats breaks token configuration & rendering

### ISSUE THREAD

**Issue by mapleybacons** [foundryvtt/pf2e#12996]
Specifically, the selector line of the crafting entry isn't parsing correctly causing the token renderer to interrupt, eventually locking the token if on a map. 

We verified the error both with the console and noted the error disappeared if the crafting entry section was deleted from the feat.

![image](https://github.com/foundryvtt/pf2e/assets/152515878/07ec2618-57d8-4d35-bfee-9ea6aa06e24f)

![token_error_cannot_open_token_attributes_window](https://github.com/foundryvtt/pf2e/assets/152515878/1f39519a-360d-46ad-a9de-d5e8073f1423)

**Comment by roi007leaf** [comment]
Can confirm, happens with Munitions Crafter as well
