### ISSUE TITLE
Improvise counteract modifiers for NPCs

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#13007]
Steps to reproduce:
1. Have an NPC with a spell that has the "Counteract" option ticked
2. Cast the spell as that NPC
3. Click on the Counteract button in the chat card

Expected Result:
The NPC rolls with their counteract modifier (pretty much their spell attack value)

Actual Result:
NPC rolls a flat d20 check without any modifier
![image](https://github.com/foundryvtt/pf2e/assets/87117602/4f14226b-c377-4e6f-97cd-bb3404873a03)

**Comment by stwlam** [comment]
This is a little awkward rules-wise since NPCs have no explicit attribute modifier or proficiency bonus, and those two are the sole stable components of a spellcasting counteract check.

**Comment by Qenthel94** [comment]
> This is a little awkward rules-wise since NPCs have no explicit attribute modifier or proficiency bonus, and those two are the sole stable components of a spellcasting counteract check.

They do have a spell attack value tho. And the description from player core of spell attack formula is: "**Spell attack roll result = d20 roll + ability modifier used for spellcasting + proficiency bonus + other bonuses + penalties**" Which is the same formula as counteracting for spells: "**For spells, the counteract check modifier is your spellcasting ability modifier plus your spellcasting proficiency bonus, plus any bonuses and penalties that specifically apply to counteract checks**."

So I should be pretty safe to use their spell attack?

**Comment by TMunsie** [comment]
NPCs do not have an ability modifier for spellcasting (they have modifiers but it isn’t assigned) nor are the assigned spellcasting proficiencies. Given the exact rule that you've quoted then the (obviously wrong) rhing to do is a d20 roll plus zero plus zero plus anything affecting a counteract check.

If you can find a rule as written that says what it should be, or that those zeroes always equal the spell attack modifier then we can add it to the system. NPCs at the same level can have a spell attack within a value of 8. And for soell attack modifiers the system makes an assumption of DC - 8 when applicable and it isn’t supplied by Paizo bit is necessary for the system to function.

I’ll put it on the list of questions for the design team though. Until they say “do that” officially we won’t. We implement the system, not author it.
