### ISSUE TITLE
Identify Alchemy notes [5.12.6]

### ISSUE THREAD

**Issue by MichalGolaszewski** [foundryvtt/pf2e#13014]
The identify alchemy macro in the latest release has "notes" section copied from identify magic. Needs adjusting.

![image](https://github.com/foundryvtt/pf2e/assets/46850235/2e472829-d6be-4358-b566-33c9fdc37fdc)

**Comment by nikolaj-a** [comment]
Oh no, will fix.

**Comment by TMunsie** [comment]
> Oh no, will fix.

You had one job…
