### ISSUE TITLE
Combination Finisher affects MAP even without Panache

### ISSUE THREAD

**Issue by ChaseDonnally** [foundryvtt/pf2e#13049]
If Finisher was checked on when Panache was removed, MAP is still affected as though the character is using a finisher with the Combination Finisher feat. Because the Finisher checkbox is inaccessible when Panache is not on, the Panache effect needs to be re-added before it can be unchecked.

**Comment by simonward** [comment]
Fixed by https://github.com/foundryvtt/pf2e/pull/13058
