### ISSUE TITLE
Battle Forms are being affected by Armor penalties

### ISSUE THREAD

**Issue by Monation** [foundryvtt/pf2e#13064]
**What currently happens**
A druid using Untamed Form to apply a battle form, while using full plate, is currently having their speed reduced, and their skills affected by check penalty.

**What should happen**
Battle form should ignore speed reductions and check penalty

**Justification**
All battle form spells have the following line after their AC: "Ignore your armor’s check penalty and Speed reduction."

**Comment by j-bs** [comment]
Looks like the `BattleForm`s just need the following properties added to the existing (or a new) top level `"armorClass"` property:
```json
"armorClass": {
  "ignoreCheckPenalty": true,
  "ignoreSpeedReduction": true
}
```

There's quite a few to update though! If no one gets to it in a couple days then I'll smash it out.

**Comment by stwlam** [comment]
Those should default to true

**Comment by stwlam** [comment]
Oh, they do. So it's definitely a bug.
