### ISSUE TITLE
5.12.7 - Munitions Crafter cannot queue up Ammunition for Daily Crafting.

### ISSUE THREAD

**Issue by Reikou** [foundryvtt/pf2e#13099]
When clicking on the button for "Add this formula to one or more crafting entries" to the Munition's Crafter's advanced alchemy/infused reagents we get the below error message instead and it prevents us from adding it.

![image](https://github.com/foundryvtt/pf2e/assets/16329843/7533f687-7d39-454c-9766-7cbf83bed99e)

Alchemical bombs are still allowed to be added.  However neither basic rounds for a gun, nor alchemical rounds can be added.

![image](https://github.com/foundryvtt/pf2e/assets/16329843/54a9f8d0-628b-48f9-9ead-e5292398417d)

**Comment by stwlam** [comment]
Try replacing the feat with a new copy
