### ISSUE TITLE
My container disappeared?

### ISSUE THREAD

**Issue by FrostLock63** [foundryvtt/pf2e#13138]
I don't know what happened, just for whatever reason I clicked and dragged on a backpack in my character sheet, and it plus all the items in it disappeared entirely.  I was able to recreate it with another container, and it seemed like it had something to do with dragging the backpack onto the Container bar? I can't recreate it consistently though, but we checked every character sheet and those bags didn't go anywhere.

**Comment by stwlam** [comment]
Try updating your system install. There was an issue (#12638) a month ago concerning this.
