### ISSUE TITLE
Feature request: change style of empty tabs

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1316]
In GitLab by @Ustin on Apr 11, 2021, 06:56

Request to print names of empty tabs differently: grayed out or in italic. 

Tabs in new NPC sheet allows for cleaner interface, but in my opinion have one drawback. 
It's impossible to tell if creature have spells or inventory by looking at main screen; GM need to click on another tab to verify this and click on main tab to go back. 

Two-three extra clicks per creature is not a big deal, of course. But it adds up over time. 

Also would work amazingly with rules and active effects tabs: actors have a lot of items in them, and seeing if items have something attached to it without clicking on every tab would be amazing. 

Example, you could tell creature doesn't have inventory or spells available: 
![example](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/b3f2120b272d2f8fa1d2f50d47e8733f/example.png)

Another example, you can tell shield block does not have any rules or active effects attached to it. 
![example2](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/9a9377891a4e9786e7db37801b9fcb9c/example2.png)

**Comment by TikaelSol** [comment]
This has been implemented, closing.
