### ISSUE TITLE
Bulk/Encumbrance Not accounting for Size

### ISSUE THREAD

**Issue by steev42** [foundryvtt/pf2e#13168]
Have a tiny PC.  Bulk Limit isn't being halved (per Player Core p270), nor are negligible bulk items being treated as Light.

**Comment by stwlam** [comment]
You are seeing the sizes from the perspective of the creature carrying the item.

**Comment by steev42** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/6807026/6f9e746c-e9d2-4b9f-8c76-c9d14ad523fe)

Yes, the items are listed as Tiny, and that affects the bulk.  But that said, page 270 of Player Core reads "A Tiny creature doesn't treat any items as having negligible bulk."  I would read that as there shouldn't be anything on this chart with a "-" weight, but if that's not the official ruling, that's fine.

What also needs to be handled, however, is the max bulk. The shown Tiny character has a strength of +0, so (were they small or medium) an encumbrance limit of 5; as a Tiny creature, this should be halved to 2.

**Comment by stwlam** [comment]
Again, it is from the perspective of the creature. A tiny creature has as max bulk of 10 of tiny items.

**Comment by steev42** [comment]
Ok (and I swear I'm not trying to be argumentative here; at this point I'm just trying to understand the implementation because it doesn't make sense to me)...that makes sense for some of this.  A piece of chalk that's negligible becomes Light for a tiny character, but make it tiny, and it goes back to negligible. That's fine. A medium-sized healing potion goes from Light to bulk 1.  A medium sized toolkit goes from bulk 1 to bulk 2.  That's all consistent.  

But surely, the same would apply to the rapier and armor?  A bulk 1 rapier made for a medium character would be bulk 2 when held by a tiny; a rapier made for a tiny character would be Light when held by a medium character, but bulk 1 when held by a tiny character.  Same would go for the Leather armor.  The tiny dagger would remain bulk L (or negligible if held by a medium character), so that makes sense to me.

So what am I missing in the implementation and/or the rules that makes the rapier and armor feel inconsistent with how the rest of it works?

**Comment by steev42** [comment]
And here's where I apologize; learned last night that my player had manually altered the bulks for those two items.   That explains everything I was seeing and why the discrepancy was there.  All good now.
