### ISSUE TITLE
Treat Wounds DC Not Adjusting and Risky Surgury Not Changing DOS

### ISSUE THREAD

**Issue by john-gelinas** [foundryvtt/pf2e#13171]
When the Treat Wounds action is used with higher DCs (Expert, Master, Legendary), the DC of the check rolled is not increased. Also, although Risky Surgery is applied in the sense that it does the damage, it does not increase the degree of success from success to critical success.

The first issue persists when medicine is used for the skill check (rather than crafting with chirurgeon alchemist, as in the screenshots) whereas the risky surgery issue seems to work correctly when using medicine as the skill.

<img width="406" alt="image" src="https://github.com/foundryvtt/pf2e/assets/88011857/362b082d-fd8e-42a9-81f8-0c9c7eb7a52e">
<img width="286" alt="image" src="https://github.com/foundryvtt/pf2e/assets/88011857/78996038-12eb-470a-a30c-96c5d873db46">

**Comment by john-gelinas** [comment]
[fvtt-Actor-renard-(rei)-elm-Fg2fSulwYIXzJNBX.json](https://github.com/foundryvtt/pf2e/files/14002669/fvtt-Actor-renard-.rei.-elm-Fg2fSulwYIXzJNBX.json)

**Comment by stwlam** [comment]
The character you posted is only trained.
