### ISSUE TITLE
Background with more than one skill grant none

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#13207]
The `Feral Child` background is supposed to grant both `Nature` and `Survival` but provides neither.

![image](https://github.com/foundryvtt/pf2e/assets/651462/4ec9225c-7514-4d88-ad60-a2beecd766b1)

If i remove one of them, then the other is granted to the character properly.

Is the array considered a `or` maybe and therefore expect a manual choice from the user ?

**Comment by simonward** [comment]
src/module/item/background/document.ts:49 is checking for exactly 1 skill:
`if (trainedSkills.value.length === 1) {`

**Comment by stwlam** [comment]
Working as intended
