### ISSUE TITLE
Precision damage immunity does not completely negate the damage if it comes from a critical hit

### ISSUE THREAD

**Issue by pedrogrullada** [foundryvtt/pf2e#13217]
If you roll critical damage with an attack that deals precision damage and deal that damage to a creature immunity to it, it looks like the precision damage is only subtracted once. It seems this was fixed in the past #5431 but has resurfaced?

Following screenshot is of Merisiel vs. a Ghost Commoner
![image](https://github.com/foundryvtt/pf2e/assets/103401186/6904e794-4a14-48cd-a86f-e0f4496e227c)

**Comment by GrahamCorcoran** [comment]
I have created this [PR](https://github.com/foundryvtt/pf2e/pull/13539) to resolve this bug.
