### ISSUE TITLE
Was the Advanced Rule Element UI setting removed?

### ISSUE THREAD

**Issue by demotech89** [foundryvtt/pf2e#13238]
Was the Advanced Rule Element UI settings removed from the system?

**Comment by stwlam** [comment]
Rule elements are always visible to GMs now. For player access, turn on "Player Rule Elements Access".

**Comment by demotech89** [comment]
Yes but without the option of the advanced UI element, the module PF2 rule element module breaks and the tab no longer works and the edit rule element button no longer works. Per their module, "To get started, go the an item's Rules tab (you must have Advanced Rule Element UI enabled in System Settings to see the tab), and click the Wand "New Rule Element" or an existing Rule Element's wand icon." 

I have reported it to them as your removal of this option as broken their module.
