### ISSUE TITLE
Innate spellcasting shows incorrect proficiency modifier

### ISSUE THREAD

**Issue by digitalpacman** [foundryvtt/pf2e#13233]
I created an elf monk with stats 4str, 2dex, 0con, 1int, 2wis, 0cha.

Took the spellcasting ancestry feat otherworldly magic to get a cantrip.  

Under the proficiency tab on the character sheet, under spells, spell attack modifiers & DCs are marked as trained at +1.  It should say +3.

When I changed the spellcasting ability on the spellcasting tab, to strength, the number on the proficiency tab did not change to +7.

**Comment by stwlam** [comment]
As spellcasting abilities can use different attribute modifiers, the proficiencies tab just shows your proficiency bonus.

**Comment by digitalpacman** [comment]
That's fair. But it also doesn't even show that. The bonus is+3 not+1

**Comment by stwlam** [comment]
Innate spells are normally cast with trained proficiency, but that does not give one a general spellcasting proficiency. If anything, nothing should be shown in the proficiencies tab.

**Comment by stwlam** [comment]
Would you mind posting the character? There's not enough information to go off of here.
