### ISSUE TITLE
Versatile trait from AdjustStrike doesn't apply to the basic unarmed attack

### ISSUE THREAD

**Issue by axerwan** [foundryvtt/pf2e#13315]
Hello!
As it says in the title, something simple like `{"key":"AdjustStrike","mode":"add","property":"weapon-traits","value":"versatile-s","definition":["item:trait:unarmed"]}` doesn't apply to the basic unarmed attack. 
It does apply to stance unarmed strikes, ancestry unarmed attacks, as well as the fist strike from monk. Just not to the basic unarmed attack everyone has by default.

As far as I'm aware this is a problem with versatile specifically. Other traits like forceful, or even traits with spaces or hyphens like fatal aim d12 or two-hand apply without issue.

**Comment by stwlam** [comment]
No plans to support this, sorry. You'll want to instead make a special strike to be adjusted.
