### ISSUE TITLE
Players can perform rolls or checks as Dead Lootable NPC

### ISSUE THREAD

**Issue by nythz** [foundryvtt/pf2e#13316]
Players are able to perform dice rolls or roll on checks posted to chat as dead lootable npcs once they are selected.

By "Lootable NPC", I refer to the pf2e automation setting of that name being activated.

As the dead lootable npc gives some ownership to players to allow them to be looted, the player can select the token and then if they perform a dice roll ( ex: /r 1d20) or click to roll a check posted in chat ( ex: @Check[type:athletics|dc:20] ), 
It will then be rolled as the Dead Lootable NPC using its stats rather than the player's assigned or owned character.

Example in picture, Player TESTPC rolling as the dead Mudlicker maggot rather than its assigned character 
(source of roll shown by Dorako UX chat features but issue can be reproduced without any modules activated)
![image](https://github.com/foundryvtt/pf2e/assets/152181871/00214f66-e876-4747-a43b-02505c581655)

**Comment by stwlam** [comment]
Fixed by #13254
