### ISSUE TITLE
Daily crafting does not properly implement Alchemist's Field Discovery

### ISSUE THREAD

**Issue by Thisigia** [foundryvtt/pf2e#13404]
Field Discovery allows Alchemist to prepare _any_ 3 of their field items, and not three of the same item. Previously, this was properly tracked, but [this](https://github.com/foundryvtt/pf2e/commit/a03bf1ea752524365deda3786791837514c7e0a3) commit appears to have changed that. Currently, incrementing the quantity of a prepared formula always increments it by the batch size, even when field discovery should allow for more granular control over field items. Attempting to manually enter a quantity does not properly update the reagent cost, and at times switching tabs on the character sheet will cause this value to snap back to a multiple of 3.

**Comment by ottdmk** [comment]
To illustrate, I've attached a screenshot. My 8th level Bomber is creating 12 Bombs, which should cost 4 Reagents. Instead it costs 6.
![BombsWrong](https://github.com/foundryvtt/pf2e/assets/158676541/0ad85094-41b9-49fe-b2f7-e92d214fd3de)

**Comment by CarlosFdez** [comment]
> When using advanced alchemy to make bombs during your daily preparations, you can use a batch of reagents to create any three bombs instead of just two of the same bomb.

On double checking field discovery, it appears you are correct.

**Comment by ottdmk** [comment]
Thanks! As a reminder, Toxicologists and Mutagenists also have the same "mix & match" capability from their Field Discovery features. (Chirurgeons, oddly, do not.)
