### ISSUE TITLE
Show non-held scrolls in Spellcasting Activations tab

### ISSUE THREAD

**Issue by pedrogrullada** [foundryvtt/pf2e#13436]
Currently you must be holding a scroll for it to show there, which makes sense RAW, but makes it difficult to assess your options if you have multiple scrolls, as you have to switch back and forth between tabs. Perhaps non-held scrolls could show but with their cast button greyed out and a quick button to change its carry type, akin to the one in the inventory.

**Comment by stwlam** [comment]
It's planned; just kicked out MVP first
