### ISSUE TITLE
[Idea] Use attachment system to attach some Item Activations

### ISSUE THREAD

**Issue by ChasarooniZ** [foundryvtt/pf2e#13457]
First want to say unsure if this should be a module or if this is something that should be in the system.

But the general idea would be maybe to use the attached item system that  is used to attach shield boss to shields, and expand it to allow attaching actions to items so then you could add say **Jangling Dash** to **Bracelet of Dashing**. Unsure if this is the best way to go about it, but I'd be interested in putting in the work to try and get some way of tracking item's activations up and running.

**Comment by stwlam** [comment]
Not what attachments are, sorry
