### ISSUE TITLE
Activations Tab: Casting from Wand/Scroll doesn't send anything to chat.

### ISSUE THREAD

**Issue by dellatorreadrian** [foundryvtt/pf2e#13455]
![image](https://github.com/foundryvtt/pf2e/assets/72579484/df1074a6-8d5a-49b7-b6ea-1349300cfb0a)

When clicking in "CAST" from the new Activations tab, I believe it would improve user/player experience to send to chat the Spell Description, just like casting from Spells Tab and, in the case of Scrolls, send a message to chat that the "consumable" was spent, just like other consumables.

Maybe these next points should be another issue, but something to consider: 

  - It would be nice to have a button to "recharge" manually a Wand after casting it, in cases of misuse or some other incovenient, instead of being locked to "Resting for the Night".

  - It would be nice to implement a "Overcharge" action for Wands, automating the risks of overcharging it.

**Comment by stwlam** [comment]
Sorry, not able to reproduce.

**Comment by dellatorreadrian** [comment]
Hmmm... Strange...

The steps I used to reproduce the main issue here are: 

1 - Activations Tab
2 - Inside the desired Scroll, click "Cast"
![image](https://github.com/foundryvtt/pf2e/assets/72579484/8f8b0ebd-2572-4be3-9225-5a6bdde82532)
3 - Scroll Amount is decreased.
4 - Nothing is sent to chat:
![image](https://github.com/foundryvtt/pf2e/assets/72579484/9dd8226e-613e-422d-a8cf-85d8ca91bc0f)

I'm logged in as a GM.

With those steps, is the description of the Spell from the Scroll shown in chat?

**Comment by stwlam** [comment]
Foundry/system versions? Tried disabling modules?

**Comment by dellatorreadrian** [comment]
Yeah, tried now woth my bare bones Foundry and it worked. Sorry for the inconvenience.

I'll try to discover which module is conflicting with it.

The other 2 suggestions, should I make other issues, or you don't think it's worth of?

**Comment by stwlam** [comment]
Wands are recharged from resting, and there isn't room in the spells table for recharging as well. Overcharge support is planned, but feel free to make a feature request.
