### ISSUE TITLE
Broadleaf Shield

### ISSUE THREAD

**Issue by argiolucra** [foundryvtt/pf2e#13473]
The Broadleaf Shield item does not apply resistance correctly and seems to be stuck on void resistance.

**Comment by simonward** [comment]
Cannot reproduce. Have you used the popup in the actions tab?
<img width="511" alt="Screen Shot 2024-02-01 at 5 24 24 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/44d570b4-8322-4f66-8bc3-91da745ddf0e">

**Comment by argiolucra** [comment]
Thank you, didn't realize there was an associated action.

Thanks!
Nier New (She/They)
