### ISSUE TITLE
Hymn of Healing effect doesn't seem to work correctly

### ISSUE THREAD

**Issue by gravagehulk** [foundryvtt/pf2e#13486]
Per the spell description:

"Your divine singing mends wounds and provides a temporary respite from harm. The target gains fast healing 2.

When you Cast the Spell and the first time each round you Sustain the Spell, the target gains 2 temporary Hit Points, which last for 1 round."

Instead, the effect seems to be applying a formula for healing, which always results in 6 hit points. It also isn't setting temporary hit points on the target. I modified the effect to only apply 2 hit points of healing and 2 temp, but I can't get the temp hit points to refresh automatically (assuming it is maintained). This is what the effect looks like based on my interpretation of the rule:

![image](https://github.com/foundryvtt/pf2e/assets/69117052/609271d3-9068-47cf-89dc-f0376dc9e9af)

**Comment by TikaelSol** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/80183198/9a6dcce1-8667-4776-a5ad-ff755afef105)

Is your character by any chance level 5 or 6?

**Comment by gravagehulk** [comment]
It's actually the player's character. I'm the GM. But, yes. He is 5th level. I didn't see anything in the spell description that changed the parameters of that spell based on level. What am I missjng?

**Comment by TikaelSol** [comment]
The spell's heightening entry. It's a focus spell so it is always heightened to a rank of half the caster's level (rounded up). That means it's a rank 3 spell and gives fast healing 6.

**Comment by gravagehulk** [comment]
> The spell's heightening entry. It's a focus spell so it is always heightened to a rank of half the caster's level (rounded up). That means it's a rank 3 spell and gives fast healing 6.

Jesus. I'm an idiot. Thanks for the Pathfinder lesson!
