### ISSUE TITLE
Resistances for NPC Actors Not Working

### ISSUE THREAD

**Issue by sciencephile** [foundryvtt/pf2e#13489]
I have tried this with different creatures and with different resistances (fire, physical) and the resistances are not working when applying the damage to a NPC actor. I even started a new campaign with zero modules in it to verify that the problem wasn't being caused by an errant module.

An easy NPC actor to replicate the problem is the Grick (the uncommon one). It has resistance to physical damage 5 but that doesn't apply and the NPC takes full damage each time. I have not tried testing the resistances towards PCs, only NPCs.

**Comment by simonward** [comment]
Did you turn on IWR in settings?

**Comment by sciencephile** [comment]
Apologies, I didn't realize that this was an optional setting. I'll close it. Thanks.
