### ISSUE TITLE
Activations Tab: scrolls not showing up for a Kineticist with Kinetic Activation Gate

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#13484]
Steps to reproduce:
Create a level 2 Kineticist with air element and  "Kinetic Activation" feat
Add a scroll of tailwind to the inventory (it has matching air trait)
Navigate to the Activations tab

Expected Result:
Tailwind scroll shows up in the activations tab

Actual Result:
Tailwind does not show up in the activations tab
![Screenshot 2024-02-02 101000](https://github.com/foundryvtt/pf2e/assets/87117602/457a4a78-2ac4-4831-adee-42c24e1d8e44)
![Screenshot 2024-02-02 100945](https://github.com/foundryvtt/pf2e/assets/87117602/db00145e-9a36-4143-b68e-1fd7a2577a0a)
![Screenshot 2024-02-02 100954](https://github.com/foundryvtt/pf2e/assets/87117602/8f375099-5460-4190-9190-8a6b52f9c02d)

**Comment by stwlam** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/106829671/593bf289-9b63-4c5c-b44e-59f4198297fd)

Try refreshing the feat.
