### ISSUE TITLE
Shohbad Longrifle has no associated round type in the compendium

### ISSUE THREAD

**Issue by nsurette** [foundryvtt/pf2e#13496]
The Shobhad Longrifle is in the Compendium but it doesn't have a corresponding basic ammo type to load it with.

![image](https://github.com/foundryvtt/pf2e/assets/7799011/0fdec574-84a9-4b2a-842f-1ccd1e7852cc)

Edit: Even if I spell the name right it still doesn't show up.

**Comment by stwlam** [comment]
None was printed with it. I think it was intended more as an AP prop.

**Comment by stwlam** [comment]
Looking at relative dates, the AP book that had the gun would have been finished well before G&G was, so it's just not a thing.
