### ISSUE TITLE
Expose kingdom building attribute boost number.

### ISSUE THREAD

**Issue by Matthew-Dupler** [foundryvtt/pf2e#13490]
A common houserule for the Kingmaker kingdom subsystem is to increase the amount of attribute boosts a kingdom gets at level 1,5, etc from 2 to 3. The current amount appears to be hard-coded to 2.

It would be nice if this could be customized via settings or rule elements.

**Comment by MDupler-WATRUST** [comment]
A workaround is possible through manually editing the attribute values.
