### ISSUE TITLE
Divine Bloodline Sorcerer's "Angelic Halo" Focus Spell does not apply Effects

### ISSUE THREAD

**Issue by VoltasPistol** [foundryvtt/pf2e#13520]
Hi!

I'm new to GM the system so sorry if I don't communicate this very well, but when Angelic Halo is cast, nothing really happens?  Like, the card comes up in the chat, but it doesn't seem to be applying the bonus to hit points, and I think there's supposed to be some kind of indicator showing how many more rounds it's active but when my player casts the spell it sends info to chat but doesn't change anything else.

Thank you for all your hard work!  <3

**Comment by simonward** [comment]
Try refreshing the copy of the spell. Does the issue persist with all modules disabled?

**Comment by nikolaj-a** [comment]
You need to drag the aura effect from the chat card to the caster's token:
![image](https://github.com/foundryvtt/pf2e/assets/6374503/fcb1adeb-e577-4f84-adb9-0eb86687872d)

Also, you will usually have better luck getting answers to questions such as this in our Discord (https://discord.gg/pf2e), as this Github repository is not really a support channel 🙂

**Comment by VoltasPistol** [comment]
> You need to drag the aura effect from the chat card to the caster's token: ![image](https://private-user-images.githubusercontent.com/6374503/302078630-fcb1adeb-e577-4f84-adb9-0eb86687872d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzAzNzQsIm5iZiI6MTcwNzA3MDA3NCwicGF0aCI6Ii82Mzc0NTAzLzMwMjA3ODYzMC1mY2IxYWRlYi1lNTc3LTRmODQtYWRiOS0wZWI4NjY4Nzg3MmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMTgwNzU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNkOGNlMmQ5YWIwYWQyNDdiM2Q2NmViOWQ4MDdkYjBhNDEyM2M3ZTNhMWZhMjc1YTJiZTU0YjVhYTA2M2M1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DxoQIKIZmV6ddkgbp9zSOEtwRwfUbpu-GbrRr0QG5zM)
> 
> Also, you will usually have better luck getting answers to questions such as this in our Discord (https://discord.gg/pf2e), as this Github repository is not really a support channel 🙂

Because there's no indication that it's supposed to be used by dragging, none of us had the slightest clue that it wasn't just broken.  There's been absolutely nothing else we've encountered on this VTT that's worked like that.  We've been using foundry for over a year and PF2E on Foundry for almost three months, with us switching DMing, so it's not like we aren't familiar with the program.

If it's supposed to be dragged to make it work, unlike everything else in the game, just have it say so on the chat card.

And if you want people to go to discord, don't ask people to report problems Github.  That's on you guys.
