### ISSUE TITLE
Missing Critical Specialization for the Ruffian Rogue

### ISSUE THREAD

**Issue by jesuisfrog** [foundryvtt/pf2e#13568]
The Ruffian is missing the crit spec for martial and advanced weapons.

**Comment by MrVauxs** [comment]
The crit spec exists and works. Make sure your Ruffian subclass is up to date, and that you are attacking a flat-footed target with a martial or advanced weapon with a damage die smaller than a d8. 

You can update the subclass by pressing the Refresh button at the top of its sheet.

You can also manually add the following Rule Element.
```json
{"key":"CriticalSpecialization","predicate":["target:condition:off-guard","item:category:martial",{"lte":["item:damage:die:faces",6]}]}
```
