### ISSUE TITLE
Gozreh missing from drop down when selecting a deity on a champion

### ISSUE THREAD

**Issue by sevrick** [foundryvtt/pf2e#13572]
When creating a new character Gozreh missing from drop down when selecting a deity on a champion. I am not sure why.
Foundry Version: 11.315
PF2E Version: 5.13.2
![image](https://github.com/foundryvtt/pf2e/assets/2902311/306db024-904c-452e-a274-47248a7ad645)

**Comment by stwlam** [comment]
Gozreh has decided they don't care about causes anymore and would prefer to just go around wrecking coastlines.

![image](https://github.com/foundryvtt/pf2e/assets/106829671/f4232e85-611e-4404-a531-416d6f075e69)

To create a champion of them, you (or your GM, if applicable) can make a custom variant of Gozreh. It will then appear as an available champion deity.
