### ISSUE TITLE
Critical Hit Weakness in NPC UI

### ISSUE THREAD

**Issue by Pattern-Weld** [foundryvtt/pf2e#13608]
Tried using critical hit weakness from the NPC sheet UI, it didn't seem to apply the extra damage. No official monsters actually have a weakness to critical hits, it was going to be for a homebrew monster I was using, but if it can't be used you might want to remove it from the drop down menu. Thank you for the great work you do!

**Comment by JestePalom** [comment]
Weakness to critical hits is actually an official ability that a monster CAN have. It's there on the [Unkillable](**url**) ability for Zombies from Bestiary 1.

**Comment by stwlam** [comment]
This was implemented a few months ago.
