### ISSUE TITLE
Weird GM roll formatting in Chat

### ISSUE THREAD

**Issue by robinsving** [foundryvtt/pf2e#13611]
Our GM rolled a damage roll vs an Animal Companion, and this was shown to the chat (ignore the red dot, that is Windows)

![image](https://github.com/foundryvtt/pf2e/assets/3072502/3d97a730-e6ca-47ca-bc07-b75c9639f508)

**Comment by stwlam** [comment]
We're going to need to see what the GM saw to get any useful insight there.

**Comment by robinsving** [comment]
Player view
![image](https://github.com/foundryvtt/pf2e/assets/3072502/a3c04af6-5116-4caf-a7a8-f4cec1cec326)
vs GM view
![image](https://github.com/foundryvtt/pf2e/assets/3072502/3e325514-9e0e-43fe-b28e-86a9a6958880)

No modules activated
Foundry version 11, 315
PF2e version 5.13.5

**Comment by robinsving** [comment]
It was the same Actor doing the damage both times, if that changes anything

**Comment by MrVauxs** [comment]
What is weird about the hidden rolls made by the GM being hidden? (Besides perhaps the empty parenthesis)

**Comment by robinsving** [comment]
It's the empty parenthesis referred to
