### ISSUE TITLE
Feats for Kineticist like Rising Hurricane or Extract Elements getting a place in attacks

### ISSUE THREAD

**Issue by LordExtro** [foundryvtt/pf2e#13621]
As Rising Hurricane and Extract Elements (and such abilities for Kineticist) do give you more options of attacking opponents (and also scale with level) it would be nice for them to be automatically added to attacks when a player chooses the feat.

**Comment by TikaelSol** [comment]
These are not attacks, they are actions that require a save. There is an inline save button on each of these actions.
