### ISSUE TITLE
Sticky Bomb and Expanded Splash

### ISSUE THREAD

**Issue by ottdmk** [foundryvtt/pf2e#13646]
The change to Sticky Bomb to automatically add in the Persistent Damage is fantastic. I would like to propose one small change to the Flat Modifier rule element:
```
{
  "damageCategory": "persistent",
  "key": "FlatModifier",
  "predicate": [
    "item:trait:splash",
    "sticky-bomb"
  ],
  "selector": "alchemical-bomb-damage",
  "slug": "sticky-bomb",
  "value": "@weapon.system.splashDamage.value"
}
```
Adding "sticky-bomb" to the predicate gets the HUD toggle working properly; without it the Flat Modifier is always applied.

In addition, Expanded Splash isn't accounted for. I changed the Adjust Modifier rule element on Sticky Bomb to this, to stop the upgrade from applying when Expanded Splash is present: 
```
{
  "key": "AdjustModifier",
  "mode": "upgrade",
  "predicate": [
    "feat:calculated-splash",
    {
      "not": "feat:expanded-splash"
    }
  ],
  "selector": "alchemical-bomb-damage",
  "slug": "sticky-bomb",
  "value": "@actor.abilities.int.mod"
}
```
I then added a second Adjust Modifier that is predicated on Expanded Splash _being_ present.
```
{
  "key": "AdjustModifier",
  "mode": "add",
  "predicate": [
    "feat:expanded-splash"
  ],
  "selector": "alchemical-bomb-damage",
  "slug": "sticky-bomb",
  "value": "@actor.abilities.int.mod"
}
```
The second _adds_ the Int Mod instead of upgrading it.

**Comment by ottdmk** [comment]
Hi! I was just looking over the change; and I think there's one small problem.

'''
            {
                "damageCategory": "persistent",
                "key": "FlatModifier",
                "predicate": [
                    "item:trait:splash",
                    "sticky-bomb"
                ],
                "selector": "alchemical-bomb-base-type-damage",
                "slug": "sticky-bomb",
                "value": "@weapon.system.splashDamage.value"
            },
            {
                "key": "AdjustModifier",
                "mode": "upgrade",
                "predicate": [
                    "feat:calculated-splash"
                ],
                "selector": "alchemical-bomb-base-type-damage",
                "slug": "sticky-bomb",
                "value": "@actor.abilities.int.mod"
            },
            {
                "key": "AdjustModifier",
                "mode": "add",
                "predicate": [
                    "feat:expanded-splash"
                ],
                "selector": "alchemical-bomb-base-type-damage",
                "slug": "sticky-bomb",
                "value": "@actor.abilities.int.mod"
            }
'''
If I'm reading this correctly, the first Adjust Modifier will **upgrade** the Flat modifier to the Actor's Int Mod if the Actor has the Calculated Splash feat. 

Then, the 2nd Adjust Modifier will **add** the Actor's Int Mod to the Flat modifier if the Actor has the Expanded Splash Feat.

So, in that case, the Flat modifier will become 2*@actor.abilities.int.mod ; which is not the correct value. The correct value is @actor.abilities.int.mod + @weapon.system.splashDamage.value

If we change the first Adjust Modifier's predicate to:
'''
            "predicate": [
                    "feat:calculated-splash",
                    { "not": "feat:expanded-splash"}
                ],
```
we can get the desired behaviour . The **upgrade** will not apply if the Actor has Expanded Splash; instead only the **add** will apply.

**Comment by stwlam** [comment]
The upgrade runs second, at which point the persistent damage from sticky bombs is already higher.
