### ISSUE TITLE
Re-rolling checks via context menu broken except for hero points

### ISSUE THREAD

**Issue by BernhardPosselt** [foundryvtt/pf2e#13660]
**Affected version**: latest system release (5.13.5)

Steps to reproduce:

* Create a new world
* Create a new actor and assign it to a player
* Log in as the player and roll an unarmed attack
* Right click on the roll result and choose either Reroll and keep the new result/lower result/higher result
* Getting an error: **No actor is associated to the roll**
```
No actor is associated to the roll
fetch @ foundry.js:68326
notify @ foundry.js:68223
error @ foundry.js:68260
rerollFromMessage @ pf2e.mjs:1357
callback @ pf2e.mjs:1658
#onClickItem @ foundry.js:64986
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

Looks like if you don't use a heropoint, this one just jumps straight into the warning block? https://github.com/foundryvtt/pf2e/blob/master/src/module/system/check/check.ts#L405

**Comment by TMunsie** [comment]
Can confirm. I had two players affected by this on x.4 last night. As GM I could roll but the players got this error.
