### ISSUE TITLE
Partial Boost is erroneously counting as a Full Boost

### ISSUE THREAD

**Issue by DoritoBob** [foundryvtt/pf2e#13676]
5th or 6th level character that had a partial boost is reflecting as a full boost giving him a +5 instead of +4
<img width="1548" alt="Screenshot 2024-02-10 at 9 22 50 PM" src="https://github.com/foundryvtt/pf2e/assets/140255307/a56f36c3-782a-4234-b55d-dff0bcdd57d3">

**Comment by stwlam** [comment]
Not able to reproduce: try disabling modules. Was this made using an importer?

**Comment by DoritoBob** [comment]
Made from scratch, not imported using an importer.  All modules disabled, the error still occurs.  Player has used this actor sheet as is across 22 sessions, the error start this week after the PF2E system updates.  Right now, the work around has been we just do not assign the boost.  I will be rebuilding the character from scratch to see if that fixes it.

<img width="1430" alt="Screenshot 2024-02-10 at 9 37 29 PM" src="https://github.com/foundryvtt/pf2e/assets/140255307/ed56dc16-da65-4b99-85f4-88e9d4078924">
