### ISSUE TITLE
Two versions of Touch of Corruption spell in the system

### ISSUE THREAD

**Issue by Cuingamehtar** [foundryvtt/pf2e#13682]
There are two versions of the spell: one from APG, another from SoM.
They have the same description, but the APG one has both the healing and the damage variants, while SoM one has only the healing.

**Comment by TMunsie** [comment]
We consider this to be errata and will only maintain the one copy in the system. You’re welcome to add it locally yourself, but you’ll see several instances of things introduced in books and APs later overwritten by core books. 

In the system documentation we explain which books are considered more “canon” and within those books we go from most recent publishing date backwards. Using this, SoM is considered errata over previous core books and we only retain other versions on suggestion of Paizo.

**Comment by Cuingamehtar** [comment]
This is understandable.
But now that I look at it, Touch of Corruption doesn't seem to be mentioned in SoM at all.
I can find references to it in APG and GMG, which is consistent with AON.
Could it be that one of them was set as SoM by mistake?

**Comment by TMunsie** [comment]
Possibly. In any case the correction would be to the reference. A second version still wouldn’t be added.

**Comment by Cuingamehtar** [comment]
But there are two of them, when I think there don't have to be. That's my point.
https://github.com/foundryvtt/pf2e/blob/bfa39a4168ceebb71f69c22d50fd0be391fcad25/packs/spells/touch-of-corruption.json
https://github.com/foundryvtt/pf2e/blob/bfa39a4168ceebb71f69c22d50fd0be391fcad25/packs/spells/touch-of-corruption-healing.json

**Comment by TMunsie** [comment]
In that case I’ll bounce this over to the data entry leads: @TikaelSol ans @SpartanCPA

**Comment by TikaelSol** [comment]
The healing one is an old spell item from before we had variants on spells. Lay on hands has a similar duplicate. While we should migrate them it's old enough that I think we're fine just killing the healing variants.
