### ISSUE TITLE
Champion Shield Ally Shield HP/Hardness Issue

### ISSUE THREAD

**Issue by dtarr00** [foundryvtt/pf2e#13709]
On 5.13.6, equipping a shield (have tested with Reforging Shield, Sturdy Shield (Moderate), and Steel Shield) and having the Champion shield ally feat causes the hardness and the Max HP of a shield to increase to incorrect, massive amounts. For example, steel shield hardness increases to 19 and max HP increases to 337 and Reforging Shield hardness goes to 29 and max HP goes to 2047. Issue does not appear when shield is first equipped in character sheet, but appears after character sheet being closed and reopened.

**Comment by stwlam** [comment]
Try disabling modules.

**Comment by websterguy** [comment]
Try specifically with Token Action Hud disabled and report back
