### ISSUE TITLE
Jaathoom's Scarf missing all traits.

### ISSUE THREAD

**Issue by FrostLock63** [foundryvtt/pf2e#13727]
Should have the Air, Invested, and Magical traits.

It should also have a DC of 28 instead of 18, as errata'd by Pathfinder Society.

**Comment by simonward** [comment]
> It should also have a DC of 28 instead of 18, as errata'd by Pathfinder Society.

Do you have a reference for this?

**Comment by FrostLock63** [comment]
> > It should also have a DC of 28 instead of 18, as errata'd by Pathfinder Society.
> 
> Do you have a reference for this?

https://paizo.com/pathfindersociety/characteroptions

![image](https://github.com/foundryvtt/pf2e/assets/114524406/d4d347b3-ef16-44c0-a40c-1cba95793e69)
