### ISSUE TITLE
Compendium Browser - Retool "Kit" selector to "Tool". 

### ISSUE THREAD

**Issue by ammalagonc** [foundryvtt/pf2e#13741]
With Kits going the way of the Dodo (per the Remaster), would it be possible to change the "Kit" filter selector to something that makes more sense, like Tool/Tools?

Currently, the Kit filter brings up two items:
-  Adventurer's Pack
- Cartographer's Kit.

![Screenshot 2024-02-14 131440](https://github.com/foundryvtt/pf2e/assets/45524683/6da2ff6e-52b9-4c8c-adfc-fb698d12e724)

Might also want to recategorize these two items to equipment (or something else).

**Comment by stwlam** [comment]
Toolkits (alchemist's toolkit, etc.) are a different thing, and GMs can still create their own kits.
