### ISSUE TITLE
Adding Special Senses to NPCs doesn't properly save values

### ISSUE THREAD

**Issue by Intervencion** [foundryvtt/pf2e#13775]
When you add all the senses to a NPC sheet
![image](https://github.com/foundryvtt/pf2e/assets/13396742/4a4f0758-7868-44b0-848a-40f7c6485a08)

And click save...
![image](https://github.com/foundryvtt/pf2e/assets/13396742/de62ab83-e8a2-456e-a03e-e0d717b8983f)

Images courtesy of wwb2 @ Discord

**Comment by stwlam** [comment]
Give them ranges
