### ISSUE TITLE
Quai Dau To - Actor Data

### ISSUE THREAD

**Issue by ammalagonc** [foundryvtt/pf2e#13785]
Recreated the Quai Dau To from the Paizo Encounter: The Sound of Love [blogspot](https://paizo.com/community/blog/v5748dyo6sii5?Pathfinder-Encounter-The-Sound-of-Love) entry. 

Please review, and if acceptable, use in the next data entry. 

[fvtt-Actor-quai-dau-to-xgn7OZVUgZsOEkTZ.json](https://github.com/foundryvtt/pf2e/files/14317776/fvtt-Actor-quai-dau-to-xgn7OZVUgZsOEkTZ.json)

Hope this helps.

**Comment by TikaelSol** [comment]
Unfortunately we are still waiting for Paizo to confirm what license blog items can be published under (OGL, ORC, or something else entirely) so until they give an answer we have to hold off merging in anything from the blog.

**Comment by ammalagonc** [comment]
All good!

Hopefully, this gets resolved sooner rather than later.

Thanks again for everything you do!

**Comment by TikaelSol** [comment]
Monster was added as part of monster core
