### ISSUE TITLE
Ashen rune effect text not added with handwraps of mighty blows

### ISSUE THREAD

**Issue by Qwiddle13** [foundryvtt/pf2e#13804]
When using the ashen rune with handwraps of might blows you get the added damage but not the extra text that is correctly added when the rune is on a normal weapon.

**Comment by stwlam** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/106829671/3f2aba4c-69a2-44a4-a075-0012eb7b6046)

**Comment by stwlam** [comment]
I _do_ notice that the note doesn't show when posting critical damage for handwraps or any weapon.
