### ISSUE TITLE
Material weakness stacks with trait weakness

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#13846]
From player core: "If more than one weakness would apply to the same instance of damage, use only the highest applicable weakness value. This usually only happens when a creature is weak to both a type of damage and a material or trait, such as a cold iron axe cutting a monster that has weakness to cold iron and slashing."

Steps to reproduce:
Have a PC with cold iron weapon with a holy rune edged.
Have an NPC, such as Hezrou that has both weakness to holy and cold iron
Strike the NPC with the PCs weapon
Apply the damage

Expected result:
Weakness from the holy trait and the material does not stack and the creature takes an extra 10 damage

Actual result:
Weakness from holy trait and the material stack and the creatures takes an extra 20 damage
![Screenshot 2024-02-19 224050](https://github.com/foundryvtt/pf2e/assets/87117602/da2fceaa-7eed-4b6f-84e6-9ba56d80cb6d)

**Comment by stwlam** [comment]
> If you have a weakness to something that doesn't normally deal damage, such as water, you take damage equal to the weakness value when touched or affected by it.

The "holy" trait is something that doesn't normally deal damage, and it isn't applied to any particular instance.

**Comment by Qenthel94** [comment]
> > If you have a weakness to something that doesn't normally deal damage, such as water, you take damage equal to the weakness value when touched or affected by it.
> 
> The "holy" trait is something that doesn't normally deals damage, and--unlike the material--it isn't associated with a particular instance of damage.

Are you certain? The sentence you quoted is immediately followed by "If more than one weakness would apply to the same instance of damage, use only the highest applicable weakness value. This usually only happens when a creature is weak to both a type of damage and a material or trait" And with both cold iron and holy not being their own damage types, they would be treated as the same instance of damage, right?

**Comment by TikaelSol** [comment]
I think this is clearly covered under the quoted section as only using the highest weakness if multiple apply.
