### ISSUE TITLE
Opening and closing an item sheet while it being affected by a `AdjustStrike` RE will make the changes permanent (and more)

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#13909]
For instance, having a `AdjustStrike` RE with a `property-runes` property will permanently add the rune to the item.

Another notable point is that adding such RE will not modify the weapon/strike name, so there is no telling that the rune effect is actually active when rolling the attack or damage anywhere.

Lastly, it doesn't seem to be working with handwraps.

**Comment by stwlam** [comment]
Duplicate of #11366

**Comment by reonZ** [comment]
I am the original, not the clone !!
