### ISSUE TITLE
Marvelous Medicine not granting +2 bonus to Medicine Checks 

### ISSUE THREAD

**Issue by Unikatze** [foundryvtt/pf2e#13907]
As title. 

Marvelous Medicines should provide a +2 Item bonus to Medicine checks by just wearing them and it's not happening.

**Comment by TikaelSol** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/80183198/12f215fa-483b-424e-a8c7-60d9ddcd270b)

They have a usage of held in two hands.
