### ISSUE TITLE
Built in refresh tool for remaster changes removes the "At Will" notation from spells for creatures

### ISSUE THREAD

**Issue by soch0601** [foundryvtt/pf2e#13926]
I was using a mod to do it en masse for previously placed creatures.  However, the mod creator said they use the built in refresh from this system and to report it here.  That report is located:

https://github.com/robinsving/pf2e-item-revitalizer/issues/21

But will add details here as well:

Placing a creature, then updating to a remaster version, then updating the creature's spells to be the most recent copy removes the "At Will" designation.  Example is poltergeist:

Before refresh (Telekinetic Maneuver):
![image](https://github.com/foundryvtt/pf2e/assets/58669889/d3b11bbc-60ff-4705-8036-82daf0cd9f47)

After refresh (Telekinetic Maneuver):
![image](https://github.com/foundryvtt/pf2e/assets/58669889/b92ec432-0edd-42d3-8e74-de71553b890b)

I am not sure how to do the aforementioned refresh without that module's UI, but if you want steps to reproduce involving that, I can try to figure it out!

Thanks!

**Comment by stwlam** [comment]
Working as intended: the module is opting to reset the names of spells, so they are getting reset.

**Comment by soch0601** [comment]
Yup, I understand that would be needed.

Is there a way that it can detect the '(At Will)' string and add it again at the end (so a feature rather than a bug)?

**Comment by stwlam** [comment]
The module could and toggle on name preservation.

**Comment by soch0601** [comment]
Sounds good, I will add that as a feature request on the module.  Thank you for your time!
