### ISSUE TITLE
The new(?) Performance System Action Doesn't Look at Target for Checks

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#13958]
When playing as a Swashbuckler Battledancer, if you target someone and use any Perform System macro while targeting someone it compares the result to their Will DC to see if you got Panache. This is how it used to work when using the System actions last I played as onen too. But if you use any of the Perform System actions now, it doesn't look at the target and just shows the roll result which makes playing as this sort of character a bit of a pain at times.

**Comment by stwlam** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/106829671/fa5e5cd7-ef3f-4a3a-b9b1-f79f7705522b)

**Comment by GorgoPrimus** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/126842722/c7445139-a37f-4637-9a5a-fbe165fcf54b)

**Comment by stwlam** [comment]
The "use" series isn't being maintained. Is there a reason you're reaching around in the console instead of using the provided macros?

**Comment by GorgoPrimus** [comment]
This is what ITT and BAM are using and Idle said it was a system issue because they're using the latest version of the action. If it's not a System issue I apologize; I've been bounced back and forth between it being a System issue or a module issue.

I will say, when I use the Perform system action, without any modules, using the action Browser, it uses this(?) version and doesn't look at the target either.

**Comment by stwlam** [comment]
Alright, we'll see if we can get that one functional, at least.

**Comment by stwlam** [comment]
It looks like you need to specify a statistic to target since the Perform action doesn't have one on its own.

```json
game.pf2e.actions.get("perform").use({ variant: "oratory", difficultyClass: "will" })
```

**Comment by GorgoPrimus** [comment]
So should I ask for a FR for making the SB have a way to do this instead?
