### ISSUE TITLE
Fighter dedication seems to be missing on Multitalented dedication selection drop-down list.

### ISSUE THREAD

**Issue by pirosopus** [foundryvtt/pf2e#13961]
![2024-02-25 14_08_50-Window](https://github.com/foundryvtt/pf2e/assets/161248764/b9a22bc3-4f0d-43dc-89cf-b40f83572ed7)

**Comment by TikaelSol** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/80183198/1e91cd02-fb05-4cd4-b050-817e0ece4403)

Do you already have the feat?

**Comment by pirosopus** [comment]
Oh, sorry.
I didn't know it excluded already-taken feats.
