### ISSUE TITLE
Witch: Malicious shadow hex missing Attacks

### ISSUE THREAD

**Issue by martbab** [foundryvtt/pf2e#13975]
I am playing a Spinner of Fate Witch at 6th level. I have selected a Greater lesson feat with a lesson of shadow. However, when casting Malicious Shadow, I do not have access to spell attack selection, which I would expect to work similarly to other spells with Attack trait such as Telekinetic Projectile (see screenshots for comparison). There are only 'Roll Damage', 'Counteract', and 'Select Other Variant' buttons, no Spell Attack button.

This is a major usability issue, as I have to pull out different spell with attack trait so that I can target and roll attack as usual with automatic hit/miss calculation against target AC.

pf2e version: 5.9.5

Steps to reproduce:

1. Create a 6th level Witch with any Patron
2. select Greater Lesson 6th level feat and select Lesson of Shadow.
3. cast Malicious Shadow hex against some target and select any damage variant

Expected Outcome:

The spell has a Spell Attack Roll button (also with MAP values) so you can make Attacks directly from the chat window.

Actual Outcome:

There are no Spell Attack Roll Buttons so you have to resort to awkward workarounds.

Screenshots:

The Malicious shadow casting dialog from the chat, note the missing Attack buttons: 
![pf2e-malicious-shadow](https://github.com/foundryvtt/pf2e/assets/1563843/fe334bc9-08bc-43ba-91ea-d595b911771c)

It could look similarly to Telekinetic Projectile dialog: 
![pf2e-telekinetic-projectile](https://github.com/foundryvtt/pf2e/assets/1563843/af76e55c-1d60-4df3-ab8a-548ede98f16a)

**Comment by pedrogrullada** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/103401186/16908209-1980-4827-a916-bbcd88f62ff3)

**Comment by martbab** [comment]
Can confirm on pf2e version 5.13.6, thank you for clarification.
