### ISSUE TITLE
Bug: `Key Attribute Options` Subfeature disappears with two or more traits

### ISSUE THREAD

**Issue by Nhaaro** [foundryvtt/pf2e#14012]
I found this out when making a feat for Summoners

one trait
![image](https://github.com/foundryvtt/pf2e/assets/41486028/2b89c094-0c23-4e46-8b7f-3df4820d7507)

two traits
![image](https://github.com/foundryvtt/pf2e/assets/41486028/02173b56-e2f2-49f7-9f88-452a214028d2)

other repro
![image](https://github.com/foundryvtt/pf2e/assets/41486028/75fdc5e8-2828-485d-bf6d-8d53c4afc08a)
![image](https://github.com/foundryvtt/pf2e/assets/41486028/c4169534-1942-41a7-b9ce-e6c46b867a5a)
![image](https://github.com/foundryvtt/pf2e/assets/41486028/3df5d823-dc17-46a5-ae3e-e6c154a12d3a)

**Comment by stwlam** [comment]
With the exception of rarity, class features technically don't have traits. In foundry we add a trait associated with a class as a data-entry convenience.
