### ISSUE TITLE
Clown Car Duplicates NPCs

### ISSUE THREAD

**Issue by Meatbricks** [foundryvtt/pf2e#14035]
The clown car function of the party sheet/token does not 'pull in' companion NPC tokens.
The party token will spawn these token if they are not already adjacent to the party token.

The companion NPCs are part of the party sheet.
The party token will not pull the companion tokens in.
If you move the party token away and 'expell' the party, it will create new, duplicate, tokens for the NPC companions.
![PXL_20240302_045523823](https://github.com/foundryvtt/pf2e/assets/161915093/5e4e3bfd-1b30-421a-a844-002822254d7c)
![PXL_20240302_045534750](https://github.com/foundryvtt/pf2e/assets/161915093/4cce4c4e-f308-46b5-9dac-ebcd74ae6425)

**Comment by stwlam** [comment]
This does not have to do with NPCs but unlinked tokens. You'll want to link actor data if making an NPC a member of a party.
