### ISSUE TITLE
Critical specialization effect for the crossbow and pick are missing in the en.json

### ISSUE THREAD

**Issue by rectulo** [foundryvtt/pf2e#14037]
![image](https://github.com/foundryvtt/pf2e/assets/98176148/429f1880-c851-4c5d-9677-cf72379e985a)

From remaster pg.283
![image](https://github.com/foundryvtt/pf2e/assets/98176148/cb2f6d9f-26d4-4311-8bd0-275acc47a3a5)

**Comment by rectulo** [comment]
Picks too

![image](https://github.com/foundryvtt/pf2e/assets/98176148/a09f3888-e460-4f66-9c4f-95dd0c87568d)

**Comment by stwlam** [comment]
There is no note created for those.
