### ISSUE TITLE
NPC selfEffect abilities on master no longer show Use button

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#14058]
For an example, look at Reginald Vancaskerkin's Overdrive Engine.
Release:
<img width="477" alt="Screenshot 2024-03-03 at 9 49 54 AM" src="https://github.com/foundryvtt/pf2e/assets/1904698/99752b71-f02b-47ee-9309-2ab06053867d">
<img width="469" alt="Screenshot 2024-03-03 at 9 50 07 AM" src="https://github.com/foundryvtt/pf2e/assets/1904698/1ef1afdf-f436-4312-94a0-b00d6d8013e7">

Master:
<img width="476" alt="Screen Shot 2024-03-03 at 12 35 58 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/c0467116-6e4d-45bf-872d-085f8e6f1abe">
<img width="477" alt="Screen Shot 2024-03-03 at 12 36 06 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/5bdbe26e-3c98-4548-8062-302d7c44ee5b">

**Comment by stwlam** [comment]
Refactor work is in progress
