### ISSUE TITLE
Compendium browser support dual language search

### ISSUE THREAD

**Issue by bb46003** [foundryvtt/pf2e#14068]
Please consider add option to combpendium browser to allow serch in local language and oryginal. 
It can be easly achive by adding  for each tab in compendium-browser/tab file  three changes 

```
searchFields=["name","oryginalname"];
storeFields=["type","name","img","uuid","level","category","group","price","priceInCopper","traits","rarity","source", "oryginalname"]
```

this in searchfiels and storeFields on end I add variable "oryginalneme" and third place were all those data are asigne we need this
```

inventoryItems.push({
type:itemData.type,
name:itemData.name,
img:itemData.img,
uuid:`Compendium.${pack.collection}.${itemData._id}`,
level:itemData.system.level?.value 0,
category:itemData.system.category??"",
group:itemData.system.group??"",
price:priceCoins,
priceInCopper:coinValue,
traits:uniq(itemData.system.traits.value),
rarity:itemData.system.traits.rarity,
source:sourceSlug, 
oryginalname:itemData.originalName}) 
```

This will support all local language and have no effect for users wich out translation module

**Comment by stwlam** [comment]
What prevents this now?

**Comment by bb46003** [comment]
Macro compendium browser use in search only item name, if it is localize then it is impossible to search by English, of course Foundry compendium search works, but all places like buttons magnifying glas on character sheet not allow to search using English. Combine localize and english name by language modules brake other things like adding rune name to weapon

**Comment by Lioheart** [comment]
For example:

![obraz](https://github.com/foundryvtt/pf2e/assets/39154364/a3dd7ac9-c358-4295-87f1-d875371d5d1a)

![obraz](https://github.com/foundryvtt/pf2e/assets/39154364/923201bc-5034-4b4f-9d03-31d0a9139668)

**Comment by bb46003** [comment]
> For example:
> 
> ![obraz](https://private-user-images.githubusercontent.com/39154364/311328356-a3dd7ac9-c358-4295-87f1-d875371d5d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjI3MzcsIm5iZiI6MTcwOTkyMjQzNywicGF0aCI6Ii8zOTE1NDM2NC8zMTEzMjgzNTYtYTNkZDdhYzktYzM1OC00Mjk1LTg3ZjEtZDg3NTM3MWQ1ZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE4MjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NGFjZTcwNzk2NTc1NmQxZDkzODQ1Nzg5NGZkYjRiNTVmNjQwMGQ1ZTkwMTBhMzdkNzY2OTc2YWIyZGQyZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MhbYCCEwEGXLopQ_5Fq0N99EQeyx7DZ_a13dLkuYKrg)
> 
> ![obraz](https://private-user-images.githubusercontent.com/39154364/311328380-923201bc-5034-4b4f-9d03-31d0a9139668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MjI3MzcsIm5iZiI6MTcwOTkyMjQzNywicGF0aCI6Ii8zOTE1NDM2NC8zMTEzMjgzODAtOTIzMjAxYmMtNTAzNC00YjRmLTlkMDMtMzFkMGE5MTM5NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE4MjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMTMxM2NmYTA4ZTJhYTJjNTliZDM4NzJkZWZiNTMxMDZlNzY0YzIxZmZhNTNmYzVlNzlhMWMyMjhiNTk5ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8xWDHTyM8LnVkeXQnYAWFWb0dXVqdDSouVb5M4Tt8Hw)

But those are results WITH proposal changes, with out them first example fill not show anything
