### ISSUE TITLE
Create Combat on inactive party creates combate with active party instead

### ISSUE THREAD

**Issue by Intervencion** [foundryvtt/pf2e#14072]
![Foundry_Virtual_Tabletop_(13h-16m-25s)  06-03-2024](https://github.com/foundryvtt/pf2e/assets/13396742/f9b3a624-35dc-4ae9-9174-4ba619be0faf)

Unsure if bug or working as expected

**Comment by Allalinor** [comment]
Shouldn't that go to the module author that added that feature?
https://github.com/reyzor1991/pf2e-party-sheet-helper

**Comment by Intervencion** [comment]
Oh. NGL I 100% thought it was a system feature. Sorry 'bout that.
