### ISSUE TITLE
Description of Effects on the Effects tab ignores localization for displaying tags

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/pf2e#14086]
Add an effect with a trait to a character and it's description will show the tag in English rather than the localized text.

Tested with no modules.

![image](https://github.com/foundryvtt/pf2e/assets/5288872/f8d4881c-ea60-4188-9d76-19de20292401)

**Comment by stwlam** [comment]
The description would be the babele extension module not having a localization of that effect, but the traits not being localized is a bug.
