### ISSUE TITLE
@Damage Missing Bracket Crash

### ISSUE THREAD

**Issue by Crowguard** [foundryvtt/pf2e#14123]
Using an `@damage` without a closing bracket and saving the item crashes Foundry; any subsequent attempts to edit the item also result in crashes (found on accident, didn't notice I was missing the bracket when I saved).

`@Damage[(floor((@actor.level)/2)+2){2 + half your level}`

https://github.com/foundryvtt/pf2e/assets/99844555/8eada9e0-c501-46b3-9724-4793b28cbcc1

Foundry 11.315
PF2e 5.13.6
Electron app & Forge

**Comment by mclemente** [comment]
You can soft-brick a world if you post it to chat too. The only fix I found was deleting the messages DB file on the world's folder.
I had reported this privately to a dev the other day because I wasn't sure making it public wasn't dangerous.
