### ISSUE TITLE
pf2e 5.14.0 not adding Damage Modifiers to Damage Rolls

### ISSUE THREAD

**Issue by Aeristoka** [foundryvtt/pf2e#14146]
https://www.reddit.com/r/FoundryVTT/comments/1bb1e36/pf2e_strength_not_added_to_weapon_damage/

Worked fine on previous version.

**Comment by avagdumortesin** [comment]
Fixed in 5.14.1 with https://github.com/foundryvtt/pf2e/pull/14142.

**Comment by stwlam** [comment]
Addressed by #14142

**Comment by Aeristoka** [comment]
> Fixed in 5.14.1 with #14142.

2 Fast 2 Awesome
