### ISSUE TITLE
Can't open PC or NPC sheets after update today

### ISSUE THREAD

**Issue by Khybersghost** [foundryvtt/pf2e#14154]
![image](https://github.com/foundryvtt/pf2e/assets/65833146/3ce995fa-a003-441c-8ce8-107e7beacace)
Forge Hosted
PF2 v5.14.1
Foundry 11.315

**Comment by LebombJames** [comment]
Uninstall and reinstall the PF2e system

**Comment by Khybersghost** [comment]
Fixed, ty
