### ISSUE TITLE
Add Advancement Speed to Variant Rule settings

### ISSUE THREAD

**Issue by jsrose09** [foundryvtt/pf2e#14164]
New Feature Request - Add a toggle setting in Variant Rules that sets the Level-Up value for XP to 800, 1000, or 1200 for Fast, Medium, and Slow progression from Page 507 of the Core Rulebook (https://2e.aonprd.com/Rules.aspx?ID=574)

**Comment by LebombJames** [comment]
The maximum XP field is a text field, you can enter whatever number you want
