### ISSUE TITLE
Check.DC.Label opposer section not closed

### ISSUE THREAD

**Issue by MichalGolaszewski** [foundryvtt/pf2e#14161]
Missing opposer section closure in `Check.DC.Label.WithTarget` and `Check.DC.Label.WithOrigin` 
![image](https://github.com/foundryvtt/pf2e/assets/46850235/a2a6bf8e-b74a-464d-b7be-d33fb3476b08)

**Comment by stwlam** [comment]
Hi Michal,

If you are able to, would you mind making a PR?
