### ISSUE TITLE
Can only select Perception for NPC initiative

### ISSUE THREAD

**Issue by racehd** [foundryvtt/pf2e#14175]
**System version:** 15.14.1

**Steps to reproduce:** Open any world, open any NPC, and find drop-down for initiative.

**Expected result:** Clicking initiative drop down will reveal a list of skills

**Actual result:** Perception is only available skill. 

![image](https://github.com/foundryvtt/pf2e/assets/22131782/3f43b2ab-1061-47a8-9ec4-718a389ecb5a)

**Comment by stwlam** [comment]
Fixed but #14173
