### ISSUE TITLE
No vision tokens don't work properly for the GM

### ISSUE THREAD

**Issue by gammagandalph** [foundryvtt/pf2e#14186]
![Screenshot 2024-03-12 145740](https://github.com/foundryvtt/pf2e/assets/25881741/d7f39e0c-14b2-4bed-8d29-58522e9c7fd1)
![Screenshot 2024-03-12 145826](https://github.com/foundryvtt/pf2e/assets/25881741/1987a86c-d27f-408d-9885-8cf66d469af9)
Selecting a token that has vision disabled as a GM leads to wrong behaviour, see images

**Comment by BernhardPosselt** [comment]
Reverting 08ed14c1a8846c98e3c852cf9061cfb0076a3563 fixed it for me

**Comment by RecursionAversion** [comment]
This was an issue for my GM and I too.
