### ISSUE TITLE
Feature Request: Add "Send to Chat" button to item sheets.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1418]
In GitLab by @SpartanCPA on May 12, 2021, 22:59

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/610eb636fd7a1e5c5c1640af7dae2009/image.png)

If possible, add a "Send Description to Chat" button in an open area of an item card. I've underlined 2 areas that might work in the header.

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/40122e3a5e698ec67c589a1932d010ec/image.png)

At the moment, the only way to send an item's description is to put the item on a sheet and then click the image to send to chat. That makes it difficult to send one-off items or features that I a player may not always want on their actions tab, as they are infrequently applicable (like Grab an Edge, or Fly)

**Comment by TikaelSol** [comment]
There is a module that handles this now.
