### ISSUE TITLE
Rerolling a DC check with a Hero Point reveals the (previously secret) DC

### ISSUE THREAD

**Issue by Daeke** [foundryvtt/pf2e#14208]
When a player rolls a skill check with a hidden DC, and then uses right-click to reroll using a Hero Point, the follow-up roll 'reveals' the DC and is not using hidden GM text. See:
![image](https://github.com/foundryvtt/pf2e/assets/8185349/fa6311ef-7fd2-49ad-a4b6-939e5859e2e5)

**Comment by DocSchlock** [comment]
This was fixed in release 5.15.0.
