### ISSUE TITLE
Escape Action lacks roll options.

### ISSUE THREAD

**Issue by Mijati** [foundryvtt/pf2e#14224]
When making an Escape Action you get very few roll options when inspecting the roll, this applies to all types of escape actions (acrobatics, athletics and attacks).

This makes it very difficult to make rule elements for the Escape Action beyond the most basic as the roll is missing almost all context.

The same applies on a new world with no modules active. Running 5.14.3 and latest Foundry version.

![image](https://github.com/foundryvtt/pf2e/assets/8881984/4527b24b-e7e6-44fd-a8ef-11bb31d5046f)

**Comment by TMunsie** [comment]
What necessary context is missing?

It’s an escape action using acrobatics in context. Can you give a reference for an example of something published that has a different need for a different context.

**Comment by Mijati** [comment]
@TMunsie This is from a Squeeze Action.

![image](https://github.com/foundryvtt/pf2e/assets/8881984/269c7e87-9711-4965-80c5-8645e424eb8e)

All other actions have a similar complete list of roll options, it's just Escape that is missing everything for whatever reason.

You have no information on the equipment or traits the user or target have, it's missing a bunch of traits (dex-based, dex-skill-check etc.) and presumably a bunch more information.

In my use case I was trying to predicate on a roll option I'd created, however, as you can see this doesn't show up on Escape Actions but does on everything else ("ooze-bonus", as seen in the image for Squeeze).

**Comment by TMunsie** [comment]
@nikolaj-a

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated issue #15855
