### ISSUE TITLE
[Feature Request] Allow "Relic" Trait to be added to more items

### ISSUE THREAD

**Issue by TheErikkuBlade** [foundryvtt/pf2e#14254]
As it stands, the Relic trait can't be given to armor or shields, as far as I've read there is no actual limit that exists that would prevent relics to be armor or shields. I understand relics aren't a high priority at the moment, but it would be nice to have this functionality.

**Comment by CarlosFdez** [comment]
I took a look, and it seems that nothing says that relics gain the relic trait, and instead is something we inferred from paizo creating relic seeds with the relic trait. I think that's a good enough reason to include it, but someone else might disagree.
https://2e.aonprd.com/Traits.aspx?ID=494
