### ISSUE TITLE
Range and Range Increment traits on NPC attacks are not interchangeable.

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#14250]
Simple way to duplicate this.
Take a creature with a strike with the `range` trait (range 60ft/range 100ft), like say a Japalisura or a Wild Hunt Archer, and attempt to strike something in their second range increment. As opposed to an Archer Sentry or Grippli Archer.

![image](https://github.com/foundryvtt/pf2e/assets/81383360/34e4d89f-0eba-4e99-a7c7-b3ef9aa032b6)

**Comment by Symon-S** [comment]
Not sure if that just means they can't shoot beyond that, since they are all using a type of bow in the NPCs above. Might be another whyzo moment.

**Comment by stwlam** [comment]
True
