### ISSUE TITLE
Shield block should not block spirit damage (and others?)

### ISSUE THREAD

**Issue by fraserstanton** [foundryvtt/pf2e#14264]
Remaster shield block says it only blocks physical damage ...

Trigger While you have your shield raised, you would take physical damage (bludgeoning, piercing, or slashing) from an attack.
You snap your shield in place to ward off a blow. Your shield prevents you from taking an amount of damage up to the shield’s Hardness. You and the shield each take any remaining damage, possibly breaking or destroying the shield.

Discussions here about what should happen with shields and spirit damage (if it matters) - https://www.reddit.com/r/Pathfinder2e/comments/1aw9uo2/shield_block_spirit_damage/

**Comment by CarlosFdez** [comment]
That discussion is quite wrong. Read shield block more carefully. Only the trigger refers to physical damage. The actual body text does not care what type of damage it is once the trigger has been met:
> You snap your shield in place to ward off a blow. Your shield prevents you from taking an amount of damage up to the shield’s Hardness. You and the shield each take any remaining damage, possibly breaking or destroying the shield.

The only argument in favor of the shield not taking spirit damage is immunities, and has nothing to do with the shield's trigger.

**Comment by CarlosFdez** [comment]
Given we haven't taken to ignoring vitality/void damage despite object resistances, I assume spirit wont' be any different. Without official clarification of how to treat leftover damage, I'm going to assume we'll keep doing what we've been doing.
