### ISSUE TITLE
v11 Actor module-sub-types are not compatible with pf2e 5.14.4

### ISSUE THREAD

**Issue by MarkPearce** [foundryvtt/pf2e#14282]
v11 introduced a way for modules to create their own document sub types. https://foundryvtt.com/article/module-sub-types/

https://discord.com/channels/880968862240239708/880969304365994034/1220904695854399488
(drentalBot)
"The pf2e system doesn't use one actor class, but one class per actor type and has a Proxy setup to actually get those classes for NP,ActorPf2e, FamilairActorPf2e, etc. So when you add a new type of actor you also have to supply a new actor class and register it in 
CONFIG.PF2E.Actor.documentClasses[type]"

but that proves to be problematic.

I've only tried it with Actors, but if there are other documentTypes that behave the same could be more prevalent.

**Comment by Drental** [comment]
Hey, no pointing at me!

Can you sow what you tried and how it failed?

**Comment by MarkPearce** [comment]
Haha that’s what you get for helping newbs. Yea I’ll upload some failures.
(And code that works in other systems)

**Comment by MarkPearce** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/6976378/b4506ec6-f925-43db-b963-f3e082bb365d)
Screen shot of the current state in not-pathfinder2e.  Scum and Villainy in this case.

Here is the repo if anyone wants to take a look. https://github.com/MarkPearce/ore-companies
I have a some conditional logic there to check for pathfinder and try workarounds.

A few folks on the discord channel been suggesting ways to fix it.

I've tried:

1.  extending the actor class, but get "you may only push instances of actor to the actorsPF2e collection"
2. extending the ActorPF2e class, by getting the prototype of existing actors but the data models don't match 
3. Tried overriding the preparedata methods, but that just kills the actors data, and removes them all from sidebar.

**Comment by MarkPearce** [comment]
error with extending ActorPF2e (currently in code)

foundry.js:753 TypeError: Failed data preparation for Actor.TxTCzNXRxDgK7KNO. Cannot set properties of undefined (setting 'flanking')
    at CompanyActor.prepareBaseData (pf2e.mjs:1649:53368)
    at CompanyActor.prepareData (foundry.js:14209:12)
    at CompanyActor.prepareData (pf2e.mjs:1649:52446)
    at CompanyActor._safePrepareData (foundry.js:14187:14)
    at Game.initializeDocuments (foundry.js:8796:18)
    at Game.setupGame (foundry.js:8706:10)
    at async Game._initializeGameView (foundry.js:9990:5)

**Comment by MarkPearce** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/6976378/1921603e-0b7b-4c3a-b12d-775e675c6359)

error when trying to extend Actor

**Comment by MarkPearce** [comment]
disabling prepdata methods.  
foundry.js:753 TypeError: Failed to render Sidebar tab actors. Cannot read properties of undefined (reading 'level')
![image](https://github.com/foundryvtt/pf2e/assets/6976378/592e46cc-e304-4ab4-87d1-8c81ca7cf1c4)

**Comment by MarkPearce** [comment]
Anyone more clever than I have suggested workaround?

**Comment by CarlosFdez** [comment]
Personally I kinda want to wait till v12 before taking a look at this, given its such a minor underlying. Its very likely we'll have to do something to support it.

**Comment by CarlosFdez** [comment]
If anything breaks, please feel free to report so that this behavior can be finetuned.
