### ISSUE TITLE
Actor clones create duplicates of PartyPF2e in member.parties

### ISSUE THREAD

**Issue by RobertBeilich** [foundryvtt/pf2e#14308]
# Problem
Moving items from a player character to its party adds that party to the `parties` Set on each party member, despite already being present.
May get triggered through other methods as well.

## Environment
tested in 5.14.4, 5.15.0 and current master (currently identical with 5.15.0)

## Reproduction Steps
* Create new world
* Create two new player characters in the party -> actor.parties is a Set with one entry (for both party members)
* Add an item to one of the player characters
* Transfer the item to the party -> actor.parties now has two entries (for both party members)
* Transfer item back to actor -> still two entries
* Transfer to party -> now its three party entries

## Reason
In `prepareBaseData` the party is added to its members via `this`.
https://github.com/foundryvtt/pf2e/blob/eb01f79441cbd98284d3500b7953dc998035abce/src/module/actor/party/document.ts#L108-L110
In the process of moving the item to the party the function is called multiple times. The time after the item is "created" in the party actor, `this` points to a new object reference and therefore gets added to the Set.

## Possible Remedy
Manually check if the party is already in the Set. This kind of defeats the purpose of the Set in the first place, but is necessary in this case, because of the way Set checks for equality.

**Comment by CarlosFdez** [comment]
An actor being re-initialized shouldn't create a new document of it, last I checked, so this is weird.

**Comment by CarlosFdez** [comment]
I found the cause, its due to actor clones. Specifically handleHPChange() triggered by the _preUpdate(). We either need to convert the set to uuids, or skip such processing in clones. Haven't decided which yet.
