### ISSUE TITLE
Quest 17  ESCORTING A MIRAGE NPC + Monsters missing from compendium

### ISSUE THREAD

**Issue by BelorMcKraken** [foundryvtt/pf2e#14325]
Greetings! 

When you lovely humans have time. the NPC/Monsters for Quest 17 are not in foundry. 
 
 Let me know how I can buy ya a coffee. Thank you all in advance.
 
 Sorry for caps. Direct copy/paste from PDF
 
  ELITE SHARKTOPUS EIDOLON
 ELITE VULKARIKI EIDOLON
 DIV WORSHIPPERS
 FOOLHARDY MERCENARY 
MERCENARY SQUAD 
 SHARKTOPUS EIDOLON 
 TWO-HEADED GOAT EIDOLON
SHADOW OF SEZRUTH 
WEAK DIV WORSHIPPER 
ANGRY FOOLHARDY MERCENARIES (4) 
ELITE ANGRY FOOLHARDY MERCENARY (0) CREATURE 3
 TRAINED SHARKTOPUS EIDOLONS (2) 
ELITE TRAINED VULKARIKI EIDOLON
 ELITE TRAINED SHARKTOPUS EIDOLON
“ENLIGHTENED” DIV WORSHIPPERS (2) 
 TRAINED VULKARIKI EIDOLON
ANGRY FOOLHARDY MERCENARY 
ANGRY MERCENARY SQUAD
 THREE-HEADED GOAT EIDOLON 
TRAINED SHARKTOPUS EIDOLON 
EMPOWERED SHADOW OF SEZRUTH CREATURE 4
WEAK “ENLIGHTENED” DIV WORSHIPPER (0)

**Comment by DocSchlock** [comment]
Content added in a PR.

**Comment by deidril** [comment]
Thanks for reporting :)
