### ISSUE TITLE
Data Entry: Shadows Wisps in 1-01 do acid damage instead of void

### ISSUE THREAD

**Issue by yorkshirelandscape** [foundryvtt/pf2e#14353]
The Shadows Wisps in 1-01 do acid damage instead of void damage with their strikes.

**Comment by simonward** [comment]
Cannot reproduce.
<img width="297" alt="Screen Shot 2024-03-30 at 12 07 13 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/384b4b35-6650-45cb-92ed-8ee73ea4a2cd">

**Comment by yorkshirelandscape** [comment]
Yeah, I just double-checked it myself. Sorry for the trouble. Must have been looking at the wrong instance.
