### ISSUE TITLE
No way to add heightened area from the spell sheet

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#14369]
While working if the data is entered by code, there is no way to change it in the Item sheet, there are 2 `select` fields for the `Area` row of a fixed heightening and both are empty (also, i think it should be 1 `text` and 1 `select`)

![image](https://github.com/foundryvtt/pf2e/assets/651462/945deece-5f1d-4cfb-b590-bb1e73301eb5)

**Comment by CarlosFdez** [comment]
This was fixed in master by https://github.com/foundryvtt/pf2e/pull/14348.
