### ISSUE TITLE
Iron Command action has an unnecessary RollOption RE

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/pf2e#14366]
Iron Command action (Tyrant Champion's reaction) adds a toggleable RollOption which is meant for the Antipaladin's Destructive Vengeance action.

**Comment by simonward** [comment]
Iron Command says:
"In addition, your Strikes against the triggering creature deal 1 extra damage until the end of your next turn. You choose whether the damage type is evil or negative each time you use this reaction. This extra damage increases to 2 at 9th level and 3 at 16th level."

**Comment by mclemente** [comment]
Nevermind, then. I'm sorry.
