### ISSUE TITLE
Osprey Scion background does not provide Hobnobber free feat

### ISSUE THREAD

**Issue by rkukuchka** [foundryvtt/pf2e#14379]
Osprey Scion background has all the correct details in it's Description: 

> Choose two ability boosts. One must be to Constitution or Charisma, and one is a free ability boost.
> 
> You're trained in the Diplomacy skill and the Xin-Edasseril Lore skill. You gain the Hobnobber skill feat.

However the Details of the Background fail to provide the Hobnobber skill feat.

**Comment by TikaelSol** [comment]
Fixed in a PR I'll be submitting later tonight to also add in some blog content.
