### ISSUE TITLE
Torch light is too high in saturation and intensity

### ISSUE THREAD

**Issue by Shteb** [foundryvtt/pf2e#14372]
Currently, the light provided when toggling 'Torch is lit' is extremely high saturation and intensity to the point of obscuring the token holding it among other things. This especially becomes an issue if two tokens in close proximity hold lit torches. 
![image](https://github.com/foundryvtt/pf2e/assets/62250672/d69e373a-3621-4284-ad30-840b4885aa8b)

As such, I'd like to suggest to drop the colour intensity and saturation of the torch. Below is the results I obtained after fiddling, along with the settings to achieve it.
![image](https://github.com/foundryvtt/pf2e/assets/62250672/97c112cd-c4d5-42e5-aa0b-1a5ae86e0c66)
![image](https://github.com/foundryvtt/pf2e/assets/62250672/cca29694-3097-4174-9c18-c521db957488)
![image](https://github.com/foundryvtt/pf2e/assets/62250672/69aebd20-914a-4990-91d8-a66732996ec1)

**Comment by stwlam** [comment]
It appears you have two lights overlapping. Foundry will compound the intensity, so it's unfortunately out of our hands.

**Comment by Shteb** [comment]
> It appears you have two lights overlapping. Foundry will compound the intensity, so it's unfortunately out of our hands.

I'm very aware that foundry compounds colour which is not an issue that can be fixed for the PF2E module, but that being the case reducing the colour intensity for the baseline PF2E torch item fixes the issue of how saturated it appears no? As from what I can tell, Foundry compounds colour intensity but *not light intensity*, so reducing the colour in the light should result in it looking a little more normal, as per the screenshots.

Genuinely trying to gauge that this might make a party holding torches not look like star come to earth ^^'
