### ISSUE TITLE
Nephilim feats

### ISSUE THREAD

**Issue by Creativeburst** [foundryvtt/pf2e#14386]
In Pathfinder Society additional info character pages it says that Tiefling and Aasimar are interchangeable with Nephilim so is possible to put the feat that weren't reprinted back in the system as they not updating pre-remastered books? https://paizo.com/pathfindersociety/characteroptions under Player Core
<img width="881" alt="Screenshot 2024-04-05 011001" src="https://github.com/foundryvtt/pf2e/assets/166101380/e531f54e-dae2-4e9f-aa49-a88e45745e40">

**Comment by stwlam** [comment]
They are found in the legacy content module.
