### ISSUE TITLE
Item roll options no longer work when recomputing target AC

### ISSUE THREAD

**Issue by HydrallUrakan** [foundryvtt/pf2e#14380]
I was attempting to create an effect to replicate the [Wind Barrier](https://2e.aonprd.com/Relics.aspx?ID=126) relic gift, and found that the `item:ranged` predicate does not appear to be functioning properly; when I tried to use the Cover: Prone effect to test it, I found the same result happening, as well as disabling all modules, so it appears to be something in the system.

**Comment by simonward** [comment]
Confirmed that it doesn't seem to be working any longer. Tested with "Hit the Dirt!".

**Comment by pedrogrullada** [comment]
From my own testing, it looks like it's the same for any `item:` roll option
