### ISSUE TITLE
Dragon form only shows remaster options

### ISSUE THREAD

**Issue by QuagScoped** [foundryvtt/pf2e#14390]
Dragon form only shows options for monster core dragons, even though old (bestiary) dragons should still be viable picks. The text for dragon form simply references common dragons, see "choose one type of common dragon".

This is further reinforced by the player core's reprinting of the reactive transformation spell, which lists:

**Trigger** You take acid, cold, electricity, fire, or poison damage; Effect Choose a shape from dragon form that resists the triggering damage.

If monster core dragons were the only viable options, then only 2 out of these 5 listed damage types would have a valid option to shape into with this reaction.

The legacy module has the old options for dragon form, but requiring a module for options which should be available to anyone isn't ideal, especially since a feat (reactive transformation) references options that wouldn't exist without these old dragons. On top of that, the legacy module has the old dragon forms with varying damage dice for the breath weapons and attacks, while they should all be uniform since the remaster (10d6 base and 14d6 heightened for the breath weapon for example), as per the dragon form spell in the player core.

**Comment by ammalagonc** [comment]
Hi there,

The current version of the `Dragon Form` spell is predicated on dragons associated with magic traditions. Legacy dragons unfortunately do not have any associated magic traditions. Paizo will need to provide clarification on their end on how Legacy dragons fall in line with the traditions of magic. 

We will leave the issue open for the time being.

**Comment by TikaelSol** [comment]
The spell effects for the older dragons can be found in the legacy content module.

We'll revisit this and any other legacy content if Paizo issues guidance on converting them.
