### ISSUE TITLE
Kineticist skill junction

### ISSUE THREAD

**Issue by eynar39** [foundryvtt/pf2e#14424]
When I'm using a kineticist, there is a problem with the skill junctions you get at higher levels. When I pick skill junction (at 5th, 9th, 13th etc), the drop down menu does not feature skill feats (although there should only be one associated with each element) but regular impulse feats instead. Also, it seems to not be adding the skill feat functionality, but the sheet seems to think it does.

After this, every time I close the character sheet, there is a popup that tells me "PC already has X feat, it has not been added again." even though there is no evidence of the feat in the sheet.

I've tried leveling the character down, I've tried to create new sheets and rebuild them, but doesn't seem to work. 

Thanks in advance!

**Comment by pedrogrullada** [comment]
Did you by chance add the Intimidating Glare manually to this character at some point? That would cause the popup about already having the feat that you're experiencing. Concerning the granting of the skill feat, it is working right now. It's granted by the Elemental Gate item (Air Gate, Fire Gate, etc), but only after an actor update (such as changing their current hp, or any detail of their sheet).

**Comment by CarlosFdez** [comment]
There was a bug at some point where grant items defaulted to no-duplicates in the form, but the RE actually defaults to yes-duplicates. I haven't checked, but this skill junction grant could be a victim of that.
