### ISSUE TITLE
The Striking RE does not increase striking damage dice for features like Gravity Weapon

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#14431]
The title, gravity weapons effect does account the damage dice increase from runic weapon. 
![image](https://github.com/foundryvtt/pf2e/assets/49882452/48563115-8315-4ed1-8c2f-baa192bed393)

This is related to issue #14409

**Comment by CarlosFdez** [comment]
This is not related to that issue at all. Runic Weapon is supposed to count as if it was a striking weapon, because its the striking re. Increasing it via other ways is not a planned feature.
