### ISSUE TITLE
Damage rolls are supposed to override the default roll mode to be public rolls, but they don't.

### ISSUE THREAD

**Issue by Cthoodles** [foundryvtt/pf2e#14439]
When rolling in Private GM Roll mode, pf2e is supposed to override this mode for damage rolls, always making damage rolls public. It does set the roll mode to Public Roll in the damage roll menu, but then the roll itself isn't actually made public, and my players can't see it or click the damage. Notably, if I instead manually select Public Roll in the damage roll menu, then it does properly override my default roll mode. But when it's automatically set to public in the menu, it fails to override unless I manually unselect and then reselect Public Roll in the dropdown.
![image](https://github.com/foundryvtt/pf2e/assets/167039560/bdc4e690-4663-4285-9ed5-66a0c89a307c)
![image](https://github.com/foundryvtt/pf2e/assets/167039560/8e914aaa-8cea-42f6-a5e7-f59765b41bda)
What my players see:
![image](https://github.com/foundryvtt/pf2e/assets/167039560/540eedda-e3e2-4116-88ed-f7d5fa3a74bd)

**Comment by Kosyne** [comment]
is this the reason it keeps setting the damage roll to public and I have to set it to private every time I roll damage as GM?

**Comment by CarlosFdez** [comment]
Whatever issue you're having seems to be unrelated. This is about a desync between the dialog's display and the result, an issue that has been fixed for a few months now.

I suspect you're trying to override the roll mode in the dialog and expecting it to keep. For it to apply to all rolls, you have to change it in the chat sidebar at the bottom.
