### ISSUE TITLE
Tetsubo hands is 2, not 1

### ISSUE THREAD

**Issue by evasivacoches** [foundryvtt/pf2e#14441]
In pathfinder nexus the Tetsubo indicates the use of 2 hands instead of 1 as it appears in foundry, for this reason and given the 3 bulk and the fact that the weapon usually measures between 4 and 6 feet, in addition to the fact that its historical zone has always been 2 hands takes me to see the error in the entry

**Comment by TMunsie** [comment]
Pathfinder Nexus is not considered a primary source. Please confirm with the printed book prior to making a report in future. Book and page numbers are appreciated in data entry error reports :)

we’ll try to track down a primary source and update if incorrect.
