### ISSUE TITLE
Support RollOption rule elements in Hazards

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#14444]
As the title describes. Here is the following rule element I was using with the ability that has it unfolded in the screenshot. Moving the ability to an NPC sheet added the toggle.
`{"key":"RollOption","label":"1 Gem Broken","option":"one-gem","toggleable":true}`

![chrome_y1PnPm4chl](https://github.com/foundryvtt/pf2e/assets/32039708/7ce380d7-312f-4401-a492-0d24ae6042f2)

**Comment by CarlosFdez** [comment]
I have a thing ready, but it won't go in until after after V12 is functional.
