### ISSUE TITLE
Support resolvables in Actor Traits Rule Element form

### ISSUE THREAD

**Issue by ToonVanEysendeyk** [foundryvtt/pf2e#14455]
Currently the "Actor Traits" Rule Element only supports taking existing or homebrew traits directly. It is impossible to add more complex specifications, such as referring to a Choice Set Rule Element.

**Comment by CarlosFdez** [comment]
Actor traits seem to execute resolveInjectedProperties, so `{item|flags.pf2e.rulesSelections.blah}` should work I think?

**Comment by ToonVanEysendeyk** [comment]
Attempts to enter text ends in it being cleared after insertion!

**Comment by ToonVanEysendeyk** [comment]
Verified that it works, but not via the UI- my bad!
