### ISSUE TITLE
[Enhancement] Support inline link callbacks created from enrichHTML without having to invoke InlineRollLinks

### ISSUE THREAD

**Issue by typhonrt** [foundryvtt/pf2e#14468]
Greets,

An [enhancement issue](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/39) was filed for Forien's Quest Log in relation to `pf2e` regarding inline links support from the game system. There are several editor sections of FQL that can benefit from being able to augment the editor content in a similar manner that the game system [handles journals](https://github.com/foundryvtt/pf2e/blob/master/src/scripts/hooks/render-journal-text-page-sheet.ts). At minimum I'd need global access to [InlineRollLinks](https://github.com/foundryvtt/pf2e/blob/master/src/scripts/ui/inline-roll-links.ts) and I can take it from there. 

No worries if this is undesirable to make globally accessible or located in a system related exposed area, however this may be useful for external integration to provide editor augmentation features that `pf2e` provides in any 3rd party modules. Another option is perhaps exposing a custom `pf2e` hook that can take HTML content and optional document and perform the augmentation; I actually like the latter approach best. 

Normally FQL stays game system neutral, but this is a compelling enhancement since `pf2e` is a well used / maintained system.

**Comment by CarlosFdez** [comment]
Sorry for the late reply. What I'm considering doing is moving inline roll link handling to TextEditor.activateListeners(), and putting the handler in the body instead of each individual link. I wanted to do that because its cleaner, but a nice side effect is that integrations like Forien's Quest Log will work without you needing to do anything special.

I don't plan to do this until we have V12 support though, in order to make sure that our V11 final releases are as stable as can be.

Thanks for looking into this though. Hopefully you'll be able to keep that system neutral.

**Comment by typhonrt** [comment]
Thanks for taking a look... This week I'm actually working on the v12 FQL update. Is there a way I can test this with a recent build of PF2E? I gather there may not be a system release with this code yet. Let me know if one will be available this week or general suggestion such as cloning PF2E and building locally to verify. I usually only do one release / update for FQL per Foundry core version, so I'd be glad to confirm that this change is working as intended later this week.

**Comment by CarlosFdez** [comment]
No problem! I would recommend cloning and building though. The build process is the usual, make sure nodejs is installed, then `npm ci` followed by `npm run watch`. You can optionally run `npm run link` if you want to automatically create a symlink from the dist folder to the foundry systems folder.

**Comment by typhonrt** [comment]
Hi @CarlosFdez. I'd like to find out if this was released in `6.0.4`. From my cursory investigation I don't believe this feature made that release. I'm just wrapping up the FQL update and making a video about new features and would like to highlight this enhancement if possible.

**Comment by CarlosFdez** [comment]
It was not release. 6.0.4 cherry picked the major bugs. This change was a lot more fundamental and it needed more time before we released (and a few bugs have been caught since then as well). It will be part of the next minor release (6.1.0).
