### ISSUE TITLE
Familiar effects not expiring at master's turn

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#14504]
https://github.com/foundryvtt/pf2e/blob/master/src/module/item/abstract-effect/helpers.ts#L35

I believe that this part should be 
```js
const atTurnStart = () => startInitiative === currentInitiative && combatant.actor === fightyActor;
```
because `effect.origin` will always return the familiar and therefor never use its master as the fighty actor

**Comment by CarlosFdez** [comment]
That logic looks like it'd cause incorrect expiration for effects that players grant to other players.

What familiar effect are you having trouble with?

**Comment by reonZ** [comment]
You are right, i confused myself while looking at all the parts that involve combat turn simulation for familiars.
What i was testing was persistent damage on the familiar, and they would not trigger during master's turn, but that is handled by another part of the code.
