### ISSUE TITLE
Search in English and translated in minisearch

### ISSUE THREAD

**Issue by Lioheart** [foundryvtt/pf2e#14507]
Currently, if a system language other than English is set, minisearch in the compendium only searches for the translated name.

Preview:
![image](https://github.com/foundryvtt/pf2e/assets/39154364/f30577f9-6808-4417-9e94-8f4feae62220)

**Comment by stwlam** [comment]
This would be due to your babele module renaming things, right?

**Comment by In3luki** [comment]
This was already fixed by #14637
