### ISSUE TITLE
Alchemist + Poisoner Dedication

### ISSUE THREAD

**Issue by RasberryKai** [foundryvtt/pf2e#14541]
I experienced a bug with the pathfinder 2e Character sheet.

## Steps to Reproduce
1. Take the Alchemist Class Feat
2. Take an optional archetype feat at level 2 and choose the poisoner dedication (or any other dedication giving you the feat alchemical crafting)

## Effect
- The Infused Reagents from the archetype are not added to the ones from alchemist, although there are two different crafting windows.
- This makes daily preparation very annoying since temporary items disappear after performing daily crafting again, making it really annoying to play this build.

Thanks for help in advance :)

![Screenshot 2024-04-27 at 19 16 38](https://github.com/foundryvtt/pf2e/assets/71934742/c82c4d3c-5776-4087-af8d-864f0d853f95)
![Screenshot 2024-04-27 at 19 17 04](https://github.com/foundryvtt/pf2e/assets/71934742/704847a1-847d-42a3-b8bd-91df1f4ef651)
![Screenshot 2024-04-27 at 19 17 09](https://github.com/foundryvtt/pf2e/assets/71934742/6e717ee3-0734-4847-a14c-e5505bad8c0a)
![Screenshot 2024-04-27 at 19 17 17](https://github.com/foundryvtt/pf2e/assets/71934742/9ac26fda-fcbb-4a94-a5b0-33a2a7a4fed4)

**Comment by DmitriiSorokinEmp** [comment]
https://2e.aonprd.com/Rules.aspx?ID=1435
Infused reagents shouldn't be added by RAW
"If you gain infused reagents from more than one source, you use the highest number of reagents to determine your pool rather than adding them together"

**Comment by pedrogrullada** [comment]
As it was pointed out, this is working as intended. Both of your preparations draw from the same pool of reagents: the one with the biggest number of them, in this case, the one from the Alchemist class.
