### ISSUE TITLE
[Feature Request] [Rule Elements] Allow rule elements to add conditions

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1455]
In GitLab by @yoshisman8 on May 31, 2021, 08:09

It would be neat if you could have rule elements also toggle conditions while they're on. So when making some homebrew effect that, for example, made you flat-footed. You can just drag it in and it makes you flat-footed. Likely using the same lock icon that's used when you gain a condition that incurs other conditions (Such as the Grabbed condition imparting Flat-Footed and Immobilized)

**Comment by stwlam** [comment]
This was done at some point!
