### ISSUE TITLE
Inline damage rolls in a hazard's routine reveal the hazard's name

### ISSUE THREAD

**Issue by Qenthel94** [foundryvtt/pf2e#14562]
Steps to reproduce:
Set metagame information setting "token's determine NPC name visbility" to true. It says that if a nameplate isnt visbile to players then the name will be hiden in chat messages.
![image](https://github.com/foundryvtt/pf2e/assets/87117602/0c5e9a77-4ec6-4fb7-a1d7-de24c0a67e04)
Have a hazard with nameplate not visible to players, make a dmg roll from its sheet. 

Expected result:
the name of the hazard is not revealed in the chat

Actual result:
the name of the hazard is revealed.
![image](https://github.com/foundryvtt/pf2e/assets/87117602/e7a34509-5886-4e37-92ce-f88172d6081a)

This does seem to work fine for inline rolls made from non-hazard npcs.

**Comment by CarlosFdez** [comment]
After investigating, the issue is specifically the routine. Because there is no item, it is displaying the actor's name instead. It should either display Routine or nothing at all.
