### ISSUE TITLE
Ephemeral Effects are not triggered when predicated on a Token Mark target

### ISSUE THREAD

**Issue by pedrogrullada** [foundryvtt/pf2e#14575]
To reproduce, make an effect with two rule elements, a Token Mark and an Ephemeral Effect (for example, to have the target be off-guard against a particular character). The Ephemeral Effect must be predicated on the target being marked (`"target:mark:slug"`).

Once the effect is applied and the target marked, the following Strikes do not have the expected ephemeral effect applied to them.

**Comment by CarlosFdez** [comment]
Is there anything in specific you were trying to implement with this? Do you have some sample roll options I could possibly play with?

**Comment by pedrogrullada** [comment]
Yes, I use this for a personal implementation of the Investigator's Shared Stratagem. I use these rule elements:
```json
{
  "key": "TokenMark",
  "slug": "shared-stratagem"
}
```
```json
{
  "key": "EphemeralEffect",
  "selectors": [
    "strike-attack-roll"
  ],
  "uuid": "Compendium.pf2e.conditionitems.Item.AJh5ex99aV6VTggg",
  "predicate": [
    "target:mark:shared-stratagem"
  ]
}
```
