### ISSUE TITLE
Fury barbarian damage resistance is inverted

### ISSUE THREAD

**Issue by Cuingamehtar** [foundryvtt/pf2e#14588]
When damaged by player characters, Fury barbarian's level 9 physical damage resistance doesn't trigger on weapon attacks, but triggers on fist attacks.

To reproduce:
1) Create a Fury barbarian character with level 9+ and apply Effect: Rage to them
2) Create another Character actor with a weapon (I used iconic Ezren with a staff)
3) Damage the barbarian with the character's weapon -> no resistance
4) Damage the barbarian with the character's fist -> resistance

I should mention, however, that I don't believe there is a simple distinction between NPC weapon and non-weapon attacks (like Barbazu's beard and claw, or dragons' melee attacks are not considered unarmed).

**Comment by pedrogrullada** [comment]
This was fixed in #14480

**Comment by Cuingamehtar** [comment]
Actually, I don't believe that it was fixed.
Here are the results I get in 5.15.3 (Ezren damages catfolk Fury Barbarian)
![image](https://github.com/foundryvtt/pf2e/assets/34245546/f32a0325-e576-47e8-8c4f-ce75160d933d)
First with a staff (weapon), then with an unarmed Strike (non-weapon)

**Comment by pedrogrullada** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/103401186/2d722290-5af9-44d0-bc27-7572b6e88186)
This is what I get with the same experiment, both on master and release. Maybe you haven't done the level 0 and back dance with your barb?

**Comment by Cuingamehtar** [comment]
You are correct. I've reset the level and it worked as intended.
Must have been some unfortunate timing as I usually try to confirm bugs on the master branch, but this time the version I used was just a bit out of date.

My second statement about NPC Strikes is still valid, but it's way beyond this issue and would probably require some major data overhaul.
