### ISSUE TITLE
Duplicate of a token no longer off-guards the target when flanking with origin token

### ISSUE THREAD

**Issue by Intervencion** [foundryvtt/pf2e#14587]
See mirror thaum flanking with themselves. It used to provide flanking bonuses but now it doesn't

(Thanks to arkeoo on Discord for reporting this issue)

**Comment by CarlosFdez** [comment]
I distinctly remember conversation about this needing to be supported for mirror thaum, and I do recall it working at some point, so I think I can reasonably assume its a bug and not working as intended.

**Comment by CarlosFdez** [comment]
Seems this behavior changed a long time ago: https://github.com/CarlosFdez/pf2e/commit/58379d2f59ad216d29d11734047ad02b9ab3f951 the foundry system used to allow you to be your own ally.

I need to add a different check to flanking code to handle this scenario.
