### ISSUE TITLE
"Injection" Trait wording issue. 

### ISSUE THREAD

**Issue by GigidyLupa** [foundryvtt/pf2e#14628]
The Archives of Nethys link states the following:
**This weapon can be filled with a liquid, usually an injury poison**. Immediately after a successful attack with the weapon, you can inject the target with the loaded contents with a single Interact action. (If the target is willing, the injection takes only 1 Interact action total.) Refilling the weapon with a new substance requires 3 Interact actions and uses two hands.
https://2e.aonprd.com/Traits.aspx?ID=407#:~:text=This%20weapon%20can%20be%20filled,only%201%20Interact%20action%20total.

However, on Foundry it reads as following.

![image](https://github.com/foundryvtt/pf2e/assets/169002272/a69a684a-779d-4bdb-9d48-742161dda64d)

This is a significant nerf to the injection trait, and after checking in with the foundry VTT discord and the Pathfinder 2E one, it's come to my attention that this isn't a product of the remaster, but an issue.

**Comment by TMunsie** [comment]
AoN is correct. Likely this trait was edited between when we got the material and the printing. 

In future, please confirm against the printed source, not AoN, as it is equally likely that they are wrong. In general, I close any issue that cites anything other than PDF or printed copy verification.

**Comment by pedrogrullada** [comment]
For what it's worth, I checked Treasure Vault, and it looks like both versions are correct. One is in pg. 41, while the other is in the glossary.
