### ISSUE TITLE
Channeling block effect is incorrect.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#14640]
when you apply the effect of channeling block https://2e.aonprd.com/Feats.aspx?ID=4686

its looking at the feat level which is 14. 

so its doing 14d8 of hardness. which is incorrect. 

it should be d8s based on the spell rank of the pcs usage of harm/heal.

if their could be an intelligent automation for this based on what harm/heal slot they use that adds the effect then that would be great. 

if not then i expect the effect will be removed.

**Comment by pedrogrullada** [comment]
The Channeling Block effect has to be dragged from a Heal/Harm spell chat card, once you've enabled its spellcasting toggle.

**Comment by ThingsCouldGetDicey** [comment]
> The Channeling Block effect has to be dragged from a Heal/Harm spell chat card, once you've enabled its spellcasting toggle. Are you getting 14d8s even if you apply it that way?

no its working alright. my player didnt know he had to do that. thanks for that will close.

**Comment by pedrogrullada** [comment]
I will look into moving the toggle to the spellcasting tab to make it a bit easier to use.

**Comment by ThingsCouldGetDicey** [comment]
> I will look into moving the toggle to the spellcasting tab to make it a bit easier to use.

that sounds better

**Comment by jrmiller82** [comment]
I know this is closed, but I'm having trouble getting this to work. I can drag the effect onto the token, it rolls the correct amount of dice for heightened heal/harm spells, but then it doesn't increase the target's shield hardness at all. If you look at the effect's code in the rules tab, it's showing an error "Value must be at most 20", but we're high level and a high level heal/harm spell can definitely go over a value of 20. 

![Screenshot 2024-11-16 233335](https://github.com/user-attachments/assets/1d796d40-276d-49f1-a362-e6d15659dc92)
