### ISSUE TITLE
Elemental Blast breaks if the action is added manually

### ISSUE THREAD

**Issue by oWave** [foundryvtt/pf2e#14651]
When manually adding the elemental blast action to a Kineticist (tested both class and dedication), the One/Two Actions rolloption toggle breaks: The toggle will now change the second action item's RE, while the strike I think still looks at the first

Replication:
- Level 1 Kineticist, switch Elemental Blast roll option to Two Actions. Con is added correctly to the blast damage
- Add a second elemental blast action
- Toggling the roll option no longer changes the damage, it's just stuck on whatever was set before the second action was added

Issue is made worse by the actions being hidden, so fixing this requires deleting the second action via console.
In case anybody run into it and needs the fix: `_token.actor.deleteEmbeddedDocuments("Item", _token.actor.itemTypes.action.filter(e => e.slug == "elemental-blast" && !e.grantedBy).map(e => e.id))`

**Comment by stwlam** [comment]
Quite a lot of things would break if added in a way not setup by the system (e.g., manually adding psychic class features to a barbarian). What makes this a special case?

**Comment by CarlosFdez** [comment]
It seems to be, assuming I understood correctly, that a kineticist who adds elemental blast to their own sheet corrupts their character, without any means of deleting the duplicate item. So its more equivalent to a barbarian adding rage to their sheet and getting a double rage, but without any delete icon showing.
