### ISSUE TITLE
Hag bloodline blood magic note has broken damage roll

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#14660]
![grafik](https://github.com/foundryvtt/pf2e/assets/134313750/8ebaac44-b829-46ea-ad48-4ca39f29973d)

as you can see there is an @ to much in the textbox for the hag bloodline.

**Comment by TikaelSol** [comment]
The issue is a missing opening bracket. I'll fix it tonight unless someone else gets to it.
