### ISSUE TITLE
[BETA] Reach weapons being considered ranged weapons

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#14698]
version:
![image](https://github.com/foundryvtt/pf2e/assets/244795/115eb82a-d61c-40e4-89fa-5f3791445b17)

Bring the weapon from the compendium it works fine
![image](https://github.com/foundryvtt/pf2e/assets/244795/c19d2307-e2e2-4ee9-a567-1c57749214a3)

Click in edit the "range 10ft appear"
![image](https://github.com/foundryvtt/pf2e/assets/244795/9e6cc72b-9716-4364-832b-62b5b5d19688)

After close it without change anything:
![image](https://github.com/foundryvtt/pf2e/assets/244795/e5365dd4-39e3-4c38-9d8f-3a03af249744)

**Comment by TMunsie** [comment]
Why are you giving a staff a range increment?

**Comment by sambomb** [comment]
I'm not, it's a bug. 
It happens automatically

**Comment by TMunsie** [comment]
> I'm not, it's a bug. It happens automatically

Can you confirm that your bug is that open up the weapon and it sets a range and doesn’t leave it blank?

**Comment by sambomb** [comment]
Just click edit and the bug occur
