### ISSUE TITLE
(V12) Feature Suggestion: Add the new V12 prototype token settings (Subject artwork, ring scale, etc) as possible fields for the json files provided by modules to use with compendium image mapping functionality

### ISSUE THREAD

**Issue by silvative** [foundryvtt/pf2e#14696]
V12 adds quite a few new fields to the prototype tokens (some of which actually aren't exposed in the UI yet) which it'd be nice to be able to fill in at the same time as setting the other artwork!

![image](https://github.com/foundryvtt/pf2e/assets/66365038/bce73cab-c0f3-4836-8d63-59f521eb738b)

**Comment by CarlosFdez** [comment]
So this is what simple worldbuilding exposes. What are we not exposing? 5e adds new fields because that's where the feature originated I imagine.

![image](https://github.com/foundryvtt/pf2e/assets/1286721/d2977c7b-ed6a-4d8f-8ad8-d087d65e1e2d)

I think it makes sense to support this, but if I recall, you mentioned dynamic token rings are global correct (it doesn't look like it is, but you have mentioned they are)? How would we handle a module conflict? Would we make the user select which one they want then turn it off for the other?

**Comment by silvative** [comment]
I just checked in a test world, and I think the "ring scale" setting I was told about did indeed make its way onto the prototype token data, albeit in a slightly different form. There's actually a subject scale instead, at `actor.prototypeToken.ring.subject.scale` :

![image](https://github.com/foundryvtt/pf2e/assets/66365038/45ac9ac8-3cbe-4f41-9715-d65b9299251a)

What's more, modifying it, it does seem to work perfectly! Unlike the regular scale setting (which still exists), it doesn't scale the ring along with it, which allows us to do "popout" tokens where the subject artwork is larger than a token's space.

Being able to modify this setting would be necessary in order to allow token packs to make use of it, so it's unfortunate that even if the system was to allow it to be set by the mapping files, there wouldn't be a way for users to modify it themselves, which would make it difficult for them to overwrite our artwork with their own. As a result, I'd definitely understand if you'd rather not support automatically modifying the value until users can change it back themselves.
How would you feel about the system exposing the setting? It seems like that sort of change is something that should happen in the core software rather than a system update, but we do already make some changes to the prototype token config, so it could be something we do temporarily in the interim.

**Comment by silvative** [comment]
I think this issue can be closed in anticipation core issue [#11125](https://github.com/foundryvtt/foundryvtt/issues/11125) - although it is not yet implemented, it means that further development of the compendium image replacement functionality is probably not worth the time
