### ISSUE TITLE
Incapacitation not triggering for inline rolls on effects.

### ISSUE THREAD

**Issue by CronaxTheUnsane** [foundryvtt/pf2e#14699]
Foundry Version 11 Build 315
Pathfinder Second Edition 5.15.3

Steps to reproduce:
Make an Effect.
Set its level to 1.
Put @Check[type:reflex|dc:10|traits:incapacitation] in its description.
Have a level 2 actor roll the check.

**Comment by sambomb** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/244795/1cf5072b-7788-4c52-b400-fd0d56bf4d9d)

@Check is case sensitive so I changed it to 
`@Check[type:reflex|dc:10|traits:incapacitation]`

a level 2 actor roled the test
