### ISSUE TITLE
Persistent Boost feat needs automation

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#14704]
Based on the damage type from the offensive boost, to apply the same damage as persistent damage I used this RE:

`{"damageType":"{actor|flags.pf2e.inventor.offensiveBoost}","diceNumber":1,"dieSize":"d6","key":"DamageDice","label":"Persistent Boost","predicate":[{"or":[{"and":["feature:weapon-innovation","item:id:{actor|flags.pf2e.innovationId}"]},{"and":["feature:armor-innovation","unarmed"]}]}],"selector":"strike-damage","category":"persistent"}`

**Comment by simonward** [comment]
It seems that the selectors have changed from `*-weapon-group-attack` to `*-group-attack-roll`. There are several other places where we use this, so I suspect it's a bug.

Current non-working:
```
"selector": [
	"bow-weapon-group-attack",
	"crossbow-weapon-group-attack"
]
```

This works:
```
"selector": [
	"bow-group-attack-roll",
	"crossbow-group-attack-roll"
]
```
