### ISSUE TITLE
Archer Dedication Archer's Aim doesn't work properly

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#14703]
Changing the Flat Modifier RE to:

`{
  "key": "FlatModifier",
  "predicate": [
    "archers-aim",
    "ranged",
    "item:group:bow"
  ],
  "selector": "attack",
  "type": "circumstance",
  "value": 2
}`

And adding the roll option RE solve the problem

`{"domain":"attack-roll","key":"RollOption","option":"archers-aim","toggleable":true,"value":false}`

I based the solution into the Hunter's Aim RE

**Comment by simonward** [comment]
It seems that the selectors have changed from `*-weapon-group-attack` to `*-group-attack-roll`. There are several other places where we use this, so I suspect it's a bug.

Current non-working:
```
"selector": [
	"bow-weapon-group-attack",
	"crossbow-weapon-group-attack"
]
```

This works:
```
"selector": [
	"bow-group-attack-roll",
	"crossbow-group-attack-roll"
]
```
