### ISSUE TITLE
Automating Phase Bolt Spell

### ISSUE THREAD

**Issue by ChasarooniZ** [foundryvtt/pf2e#14734]
Hi, saw code in recent thread (thanks to @Rigo) just needs and effect added and a RE brushup by someone with the PF2e dev repo set up on their local Machine

**New Spell Effect to reduce Circumstance AC** (has this rule element)
```json
{
  "key": "AdjustModifier",
  "selector": "ac",
  "mode": "subtract",
  "value": 2,
  "predicate": [
    "bonus:type:circumstance"
  ]
}
```

new rule element for **Phase Bolt**
```json
{
  "key": "EphemeralEffect",
  "predicate": [
    "item:slug:phase-bolt"
  ],
  "selectors": [
    "spell-attack-roll"
  ],
  "uuid": "<NEW SPELL EFFECT UUID>"
}
```

**Comment by pedrogrullada** [comment]
This needs an additional check to make sure the circumstance bonus doesn't become negative, such as a second AdjustModifier. 

The EphemeralEffect approach works as a personal implementation, but adding rule elements to spells is not something typically done by the system, as far as I can tell. We could make it as a spell effect to drag onto the target though.
