### ISSUE TITLE
Broken Armor on construct is applying Weak template extra times if you edit the AC

### ISSUE THREAD

**Issue by Intervencion** [foundryvtt/pf2e#14763]
![Foundry_Virtual_Tabletop_(16h-14m-47s)  19-05-2024](https://github.com/foundryvtt/pf2e/assets/13396742/b9d0a5d2-72fc-4912-9884-49bb99aed9f6)

**Comment by DocSchlock** [comment]
This is working as intended by the system.

The Broken toggle isn't setting the AC to 13, it's applying a -4 to the base AC. When you start changing the base AC, the math follows correctly: 13 base - 2 Weak - 4 Broken = 7, 15 base - 2 Weak - 4 Broken = 9.
