### ISSUE TITLE
[Beta] Rule elements - Token Image - Changing Value to array

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#14767]
After you edit the rule element, the UI add another value, changing the value from text to array and therefore breaking the functionality.
Before
![image](https://github.com/foundryvtt/pf2e/assets/244795/8ab56b8a-19c2-49b7-99df-2174123fccf5)

After adding a predicate
![image](https://github.com/foundryvtt/pf2e/assets/244795/eaff7109-3e5f-41af-b391-65a95750a63b)

Json after
`{
  "key": "TokenImage",
  "value": [
    "Pin.jpg",
    "Pin.jpg"
  ],
  "predicate": [
    "mudar-forma"
  ]
}`

**Comment by CarlosFdez** [comment]
I thought this was handled, but it seems it was a different token related RE
