### ISSUE TITLE
(V12 Testing): Journal check buttons don't appear to be enriched correctly

### ISSUE THREAD

**Issue by silvative** [foundryvtt/pf2e#14765]
Example journal page from Kingmaker (with all modules disabled, hence no CSS): 

![image](https://github.com/foundryvtt/pf2e/assets/66365038/a43199a4-8902-456d-9eec-54f4e0396437)

Versions:

![image](https://github.com/foundryvtt/pf2e/assets/66365038/643308be-caa8-433c-ac13-68502033d597)

**Comment by In3luki** [comment]
Might be a bad system install?

![image](https://github.com/foundryvtt/pf2e/assets/41452412/70e985ef-29c1-4ed9-994e-38df64f36f94)

**Comment by silvative** [comment]
I think you're right because rebuilding it has made this go away >.>
thank you, that makes a lot more sense x)
