### ISSUE TITLE
Flat check for unstable in the descriptions not updated according to errata

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#14785]
Using version 5.15.4

![image](https://github.com/foundryvtt/pf2e/assets/244795/fe53f03a-c363-423b-b872-41e2bd36afe9)

When using actions that roll something it's working fine: 
![image](https://github.com/foundryvtt/pf2e/assets/244795/4701ef7b-6056-4873-a671-eb230053e661)

**Comment by pedrogrullada** [comment]
Already fixed by #14771
