### ISSUE TITLE
Feature Request: Add a highlight option similar to flanking but for reach.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#14797]
i think it would be relaly neat after v12 and everything that has died down to add a similar behaviour for flanking but for reach. with the rule that affects ignoring the first diagonal. 

it would be cool to have a hotkey to open the squares available to a tokens reach so gms can quickly see the reach of their monsters.

**Comment by stwlam** [comment]
Reach isn't assessed, which is a prerequisite for highlighting reach assessment.

**Comment by ThingsCouldGetDicey** [comment]
would it be a waste of resources to do so for this feature?

**Comment by CarlosFdez** [comment]
Seems you want us to implement something like what tactical grid does, which does have the unfortunate side effect of swallowing our aura animations.
