### ISSUE TITLE
Battle Form attack modifier ignored in generated strikes

### ISSUE THREAD

**Issue by NikitaBrik-moonactive** [foundryvtt/pf2e#14835]
Whenever Battle Form effect is attached, strikes modifiers are not applied to strikes

Here's an example of Zon-Kuthon's Avatar spell effect. But I've also reproduced it with other Battle Forms (like Spell Effect: Nature Incarnate (Green Man))

```
{
  "key": "BattleForm",
  "overrides": {
    "armorClass": {
      "modifier": "25 + @actor.level"
    },
    "senses": {
      "darkvision": {}
    },
    "size": "huge",
    "tempHP": 30,
    "speeds": {
      "fly": 70,
      "land": 70
    },
    "skills": {
      "ath": {
        "modifier": 35
      }
    },
    "strikes": {
      "midnightpain": {
        "category": "unarmed",
        "label": "Midnight Pain",
        "mod": 33,
        "ability": "dex",
        "damage": {
          "damageType": "mental",
          "dice": 6,
          "die": "d6",
          "modifier": 3
        },
        "traits": [
          "mental",
          "nonlethal",
          "range-120"
        ]
      },
      "spikedchain": {
        "ability": "str",
        "category": "unarmed",
        "damage": {
          "damageType": "slashing",
          "dice": 6,
          "die": "d8",
          "modifier": 6
        },
        "modifier": 33,
        "label": "Spiked Chain",
        "traits": [
          "disarm",
          "trip",
          "reach-15"
        ]
      }
    }
  }
}
```

<img width="914" alt="image" src="https://github.com/foundryvtt/pf2e/assets/116557580/33442e69-0b45-4bbd-8132-1a030696a9de">
<img width="1133" alt="image" src="https://github.com/foundryvtt/pf2e/assets/116557580/964ab4d9-0afe-4761-be71-97404186deae">
<img width="273" alt="image" src="https://github.com/foundryvtt/pf2e/assets/116557580/8368ecfa-ea7d-4b02-bf32-d00d0a8e3310">

**Comment by DocSchlock** [comment]
I cannot reproduce this. Battleform effects, including the ones mentioned, work without issue.

Can you confirm you have no modules enabled while you're testing this?
