### ISSUE TITLE
Arcane cascade not functioning

### ISSUE THREAD

**Issue by blazedw** [foundryvtt/pf2e#14868]
Nothing happens when attempting to apply the arcane cascade stance to my character. The console spits out this error when attempting to apply the effect:
![2024-05-28_20-05-1716898120](https://github.com/foundryvtt/pf2e/assets/87355488/fee9c067-3829-4d6d-a1f9-a06481e1589d)
Other stances don't seem to be affected by this problem.

**Comment by DocSchlock** [comment]
What is your Foundry and PF2E system version, and are you encountering this error without any modules enabled?

**Comment by TikaelSol** [comment]
This is a an error with the 6.0 beta and I believe is fixed on master.
