### ISSUE TITLE
Add filter to Reincarnated and Fey Influence Ancestry Feats

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#14869]
When searching by an Ancestry feat, the Reincarnated Feats should be disabled by default or at least being added to the Traits list and the Fey Influence feats should have a "pseudo trait" so we can disable then in the filter.

Adding the "Fey Influence" trait to the Fey influence feat tree would help the players to filter it out more easily.

Desired filter

![image](https://github.com/foundryvtt/pf2e/assets/244795/53c2ee31-b29b-48b3-92be-a895ca18098b)

**Comment by TikaelSol** [comment]
We will not be adding fake traits to the system under any circumstance.

**Comment by stwlam** [comment]
Isn't Reincarnated already a trait?

**Comment by sambomb** [comment]
Yes it is, but the problem is that using "all the above" still brings the feats even if they don't have the trait.

**Comment by sambomb** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/244795/e9828934-2c3c-4dcd-8a5b-2dbc184af0f7)

Using just an ancestry trait should not list reincarnated feats or Fey Influence because they don't have the ancestry trait.

If you add a second trait, for example reincarnated ( negated ) there is 2 results based on the "All of above" or "Any of above"

All of above, show Fey Influence
![image](https://github.com/foundryvtt/pf2e/assets/244795/a2e351b8-93e2-4294-a41d-08eaecfcdf0a)

Any of above, **don't** show Fey Influence
![image](https://github.com/foundryvtt/pf2e/assets/244795/aad6621a-26f4-4f1b-8684-74f1261e4094)

Even without an ancestry trait on the filter, the search bring the feats as a false positive.
![image](https://github.com/foundryvtt/pf2e/assets/244795/339e3292-2cdf-45d2-8201-c59784b6043f)

I understand the reason why it has been done this way, to show all available feats for the ancestry, but without a simple way to remove it from the list, it becomes a burden.

#10044 Implemented the filter but no way to filter out this extra options.

Instead of the "Fey influence" trait, an "Any ancestry" trait would solve the problem too, and just bring it at the initial search like the ancestry and versatile heritages so if anyone wants to remove it, they can just click the 🚫 button

**Comment by TikaelSol** [comment]
Consolidating into #6588
