### ISSUE TITLE
Clawdancer Archetype Lacks Automation

### ISSUE THREAD

**Issue by Rovoska** [foundryvtt/pf2e#14870]
### What happened?

When adding the clawdancer archetype, Foundry does not add the given stances, nor the given attacks by said stances. Both the stance actions and attacks do not appear to exist at all.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Opening foundry in Firefox, making or remake a character to add the clawdancer archetype, and observe that the system does not add the expected content to the character sheet

### What core version are you reporting this for?

Version 11 355

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Roghain** [comment]
I am having the same issue. I am running Foundry V12 stable Build 327 and PF2E 6.0.4
I have disabled all modules and the issue persists. The advice given above in refreshing doed not change the issue.
