### ISSUE TITLE
Add automation to Animal Fleetness feat (Werecreature dedication)

### ISSUE THREAD

**Issue by Mikkidez** [foundryvtt/pf2e#14894]
Good day! Thanks for your incredible work! 

In the latest update, some automation was added for the Werecreature archetype; I would like to ask, if possible, to add automation to Animal Fleetness feat. 

![Снимок экрана от 2024-05-30 09-24-15](https://github.com/foundryvtt/pf2e/assets/158248937/ca3d7125-5696-484b-a3e2-5a62e1790116)

I tried to make a temporary RE myself until it was done in the system, but for some reason it only worked for me at land speed... But I’m not a programmer, so most likely I made a mistake! =)

`{
   "key": "FlatModifier",
  "predicate": [
    "change-shape:animal"
  ],
  "selector": "all-speeds",
  "value": +10
}`

Thank you very much in advance!

**Comment by Cuingamehtar** [comment]
Change shape doesn’t remove other speeds that an Actor might have (such as a strix with permanent fight Speed of 25 retains this speed when turned into a boar).
A simple RE that just requires "change-shape:animal" would also affect Speed not granted by the Change Shape.
Some additional options like "polymorph-speed:land" granted by Change Shape ability might be required here. Or a way for the Change Shape to remove other Speeds.
