### ISSUE TITLE
Needle Thousand-Pains Fulu has wrong usage

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#14916]
the Thousand-Pains Fulu (Needle) item should have the Usage: _affixed to a creature,_ yet it has _held in 1 hand_ - it's from Treasure vault 79

**Comment by Intervencion** [comment]
They're all using "held in 1 hand" instead, not just needle. Wonder if it's on purpose? "affixed-to-a-creature": "PF2E.TraitAffixedToCreature" exists though but IDK if it's ever used anywhere?
