### ISSUE TITLE
Better Formating: Commune

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#14926]
![grafik](https://github.com/foundryvtt/pf2e/assets/134313750/2f22c675-532e-4f05-8ca1-6ab047e52846)

This is a really tiny request, but in the religion part ist should only tell which beings are effected and then the second part should be separated cause it is true for all the rolls.
![grafik](https://github.com/foundryvtt/pf2e/assets/134313750/23470cb2-1c75-4a8c-af5e-2043815abdcc)

**Comment by stwlam** [comment]
We more-or-less follow the formatting in the book. Has it deviated from that?

**Comment by Vendergast** [comment]
Yes it has

![grafik](https://github.com/foundryvtt/pf2e/assets/134313750/1432acb1-eb20-4e11-b34a-4f7fcc06968c)

Sry should have had that in the first pitch of the issue

**Comment by TMunsie** [comment]
Ah, it isn’t the formatting that’s a problem. It’s that Tikael’s tool doesn’t know when to end an unordered list and typically the first thing after that gets sucked into the tag.
