### ISSUE TITLE
Both versions of the Gylou incorrectly gives the Reflexive Grab reaction the move trait

### ISSUE THREAD

**Issue by TheErikkuBlade** [foundryvtt/pf2e#14952]
When checking on Archives of Nethys, both versions of the Gylou's reaction does not have the move trait, but it is present on Foundry. As the title suggests, seems to be a data error but I don't have any books to confirm.

Foundry Version:
![image](https://github.com/foundryvtt/pf2e/assets/63211464/02bfa551-973e-4357-b4e7-3b1c46265dd8)

AoN Version:
![image](https://github.com/foundryvtt/pf2e/assets/63211464/0d7cb6aa-35f3-4788-a054-03501e669049)

**Comment by simonward** [comment]
Verified in the PDFs that it should not have the move trait.
