### ISSUE TITLE
Reinforced Stock does not apply Two-Hand d8 when attached weapon is wielded in two hands

### ISSUE THREAD

**Issue by LJSmith066** [foundryvtt/pf2e#14971]
While the reinforced stock acts as expected when unattached (single handed = d4 damage, two-handed = d8 damage), it seems that when attached to a weapon it doesn't pass on the two-handedness of the attached weapon- so when wielding a sukgung in 2 hands, it still only does d4 damage.

Edit - just realised I'm still on 5.16.1 rather than the 6.0 beta, but given the lack of pull requests regarding this I wouldn't be surprised if this was still an issue.

**Comment by CarlosFdez** [comment]
I can confirm its still a bug.
