### ISSUE TITLE
Proposal to automate advanced feats

### ISSUE THREAD

**Issue by Lioheart** [foundryvtt/pf2e#14974]
I looked for a way to manually create this feat, but it is impossible without the appropriate changes to the system.

You need to create a self:halflevel variable (along the lines of self:level). This will make it possible to use it in the feat.
![obraz](https://github.com/foundryvtt/pf2e/assets/39154364/e7bfe211-367b-45f9-98a7-2c299e87fbf7)

For example, in the Advanced Trickery feat when I inserted the following condition, I could select level feat up to the character's level (example for a 14th level character):
```
     "lte": [
                "item:level",
                "self:level"
              ]
```
![obraz](https://github.com/foundryvtt/pf2e/assets/39154364/0b567ce3-7a6f-406b-9f62-f54b59e7d7c8)

I would ask you to consider such a possibility.

P.S.
It works, when I created manually
![obraz](https://github.com/foundryvtt/pf2e/assets/39154364/01b2546d-b7bc-4a93-815b-e14960714b52)

P.P.S.
I know that there have already been several attempts to solve this problem, but this option seems to be the least destructive. I searched for all occurrences of self:level in the pf2e.mjs file and manually added the following code after those occurrences:

> this.rollOptions.all[`self:halflevel:${this.level/2}`]=!0

This gives us a variable that we can use in a condition, as I gave in the example above, in place of "self:level".

**Comment by CarlosFdez** [comment]
I actually have a working implementation here https://github.com/foundryvtt/pf2e/pull/14636 but it broke when the v12 branch was rebased and merged into master. I just need to recreate it, but I have an alternative idea that should be more performant and simpler to work with that I want to present as an alternative.

**Comment by Lioheart** [comment]
My way would allow you to use this safely in Rule Element. Therefore, I found that this is the least destructive way to solve this problem.

**Comment by CarlosFdez** [comment]
What you have here doesn't seem to handle a level 10 actor adding an advanced archetype feat to a level 6 slot. halflevel is relative to the actor, not the slot. The active effect to inject a temporary variable idea is also employed by kineticist.

I'll close this for now, but thanks for writing the issue at least. So far the major ideas are the approach I took, and some other ones that have been juggled around behind the scenes regarding the UI of it. The issue right now isn't a technical one, its that people seem to have a habit of missing the dropzone which will alter the options.

**Comment by Lioheart** [comment]
I understand. I forgot about kineticist. I'm hoping that this will be resolved in the near future and everyone will be able to use advanced feats. Good luck.
