### ISSUE TITLE
Players can gift themselves items from merchant if the stock is higher than 1

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#15052]
Basically, when the stock of a merchant item is higher than 1, the new `Purchase` popup will show up and a player will be able to use the `gift` button (and the message notifying the sell is still generated).

Also, i was wondering if this input is there for something planned, because it doesn't exist in the template.

https://github.com/foundryvtt/pf2e/blob/30c91f6516d6b0982e208b07c8b218b80b0713bd/src/module/actor/sheet/popups/item-transfer-dialog.ts#L83

**Comment by CarlosFdez** [comment]
likely something that slipped in from it being in limbo for some long. I'll look into it, the gift button is not supposed to show to players and probably slipped in from some late adjustments.

**Comment by CarlosFdez** [comment]
Originally instead of a dedicated give button, it was another checkbox. I forgot to remove that code when I converted it to a give button.
