### ISSUE TITLE
Secret checks and v12's manual rolls

### ISSUE THREAD

**Issue by Mystler** [foundryvtt/pf2e#15063]
This is not a major issue at all but a feature request to smoothen things out now that Foundry Core has support for manual dice rolls.

So far, whether that was with modules for manual rolls or the core setting in v12, manual rolls will prompt the triggering user for their input. This works as expected but it gets tricky when we enter the PF2E-specific area of secret checks. I have run into my fair share of situations where players with manual rolls called wanting to do something like Sneak, Recall Knowledge, Identify, etc that would be a secret check and just hitting an action macro for it and then getting prompted for their manual roll. Once they did that I had to essentially tell them that I will ignore the result and properly reroll the check for them on my end.
To get to the point, if this is possible, it would be amazing Quality of Life if the system can check for the Secret tag and override the manual roll behavior so that these users are not prompted, a blind digital roll triggers instead, and the GM gets to see their secret check directly.

On top of that, it would be nice to have a manual roll indicator in the chat cards for completed rolls. Afaik, the latest core release added something for that, but this is not translated into the system, as I believe the changelog said that systems need to add support for it as well.

**Comment by stwlam** [comment]
Better addressable upstream (issue created)

**Comment by Mystler** [comment]
I am running on the lastest Foundry v12.329 and PF2E 6.1.0 now and it appears that manual rolls done with manual fulfillment via the Core Configure Dice setting still always prompt for manual input, even on blind rolls.

I saw the system had one commit regarding this but it does not seem to have done the trick yet.
Tested on a clean world without modules.
