### ISSUE TITLE
Magic exceptions to immunities aren't handled

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#15065]
Foundry 12.327
PF 6.0.1

Enemy:
![image](https://github.com/foundryvtt/pf2e/assets/244795/9a4b0a8e-4094-4a5d-ad53-0a9a8e93fc51)

Spell and roll inspector 
![image](https://github.com/foundryvtt/pf2e/assets/244795/5d4270ff-390a-4561-8856-528e42594767)

Inspector shows Magical instead of Magic 
Trying to add a rule element 
![image](https://github.com/foundryvtt/pf2e/assets/244795/17149162-03c6-4390-8603-9eacb07119f6)

Trying to add Magical at the list
![image](https://github.com/foundryvtt/pf2e/assets/244795/14c57922-7e1e-4a06-bcd9-c2251f15b657)

PS.: Weakness and Resistance are working fine but the text is "magical" instead of "magic"

**Comment by CarlosFdez** [comment]
I did some research and this is an unfortunate byproduct of golems. If we simply replace magic for magical, then golems will become immune to strikes. It appears to be that we'll need "magic" in the types, and "magical" in the exceptions to solve this issue. This also looks like an old bug.
