### ISSUE TITLE
Incendiary Aura Effect incorrectly has an Unlimited Duration

### ISSUE THREAD

**Issue by TheErikkuBlade** [foundryvtt/pf2e#15072]
Incendiary Aura only lasts for 1 minute, yet its effect has an unlimited duration.
![image](https://github.com/foundryvtt/pf2e/assets/63211464/7917bf1f-ddf4-43f2-b3e7-484f5f0ef8bb)
![image](https://github.com/foundryvtt/pf2e/assets/63211464/23b1f7eb-eb35-452f-b2af-cb5b32a3774d)

**Comment by stwlam** [comment]
This isn't a data error but a current limitation of auras: they're all forced to be unlimited.

**Comment by TheErikkuBlade** [comment]
> This isn't a data error but a current limitation of auras: they're all forced to be unlimited.

I was able to change it myself and it seems to work fine. All I did was change the spell effect's duration. Confirmed it even works with the initiative tracker and expires after 10 rounds or 1 minute.
![image](https://github.com/foundryvtt/pf2e/assets/63211464/f1b410db-85ba-4e1c-af93-86b5802ff6d9)
![image](https://github.com/foundryvtt/pf2e/assets/63211464/fab42e0f-7520-45e5-9079-6555aaaa1906)
![image](https://github.com/foundryvtt/pf2e/assets/63211464/96a960b9-003c-4ecc-9d59-fdb19908192f)
