### ISSUE TITLE
The Spell "Strange Geometry" has no area included in its description.

### ISSUE THREAD

**Issue by fishrobe** [foundryvtt/pf2e#15103]
As the title, Strange Geometry has a range of 60 ft which is included, but the area is 4 10 ft cubes, which is not anywhere in the spell description in Foundry (I needed to look it up on AoN). 

Obviously a very small issue, but thought I should let you guys know.

**Comment by pedrogrullada** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/103401186/89d5c376-7b36-4299-ba57-cbd8206fc0e0)

You may be running an old version of the system

**Comment by fishrobe** [comment]
![SG](https://github.com/foundryvtt/pf2e/assets/50474856/b386fd71-cafa-4de9-92e4-3dcb9c57f1a6)
Weird. Up to date but not showing up in the monster's stat block. Well, no big deal.

**Comment by simonward** [comment]
You just need to refresh the copy.
