### ISSUE TITLE
Wrong RE: Ironhoof centaur

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#15119]
The current RE is giving finesse instead of agile:
![image](https://github.com/foundryvtt/pf2e/assets/244795/861c0ca4-b128-4371-ac28-81a8c2766545)

`{"category":"unarmed","damage":{"base":{"damageType":"bludgeoning","dice":1,"die":"d6"}},"group":"brawling","img":"icons/sundries/misc/horseshoe-iron.webp","key":"Strike","label":"PF2E.BattleForm.Attack.Hoof","slug":"hoof","traits":["agile","unarmed"]}`

Just change from finesse to agile

**Comment by GorgoPrimus** [comment]
https://paizo.com/pathfinder/faq

That’s because that book/pdf has been officially errataed to make it so.

**Comment by sambomb** [comment]
Missed the errata, my bad 😅
