### ISSUE TITLE
Unarmed athletics skill actions don't benefit from the Agile trait

### ISSUE THREAD

**Issue by xyzzy42** [foundryvtt/pf2e#15120]
The MAP value for the Athletics actions with the attack trait follows the 0, -5, -10 progression.   E.g.,
`game.p2fe.actions.get('trip').use({multipleAttackPenalty: 1})` will be at -5.

In the remaster it's been explicitly stated that free hand athletics actions use the unarmed attack, which is Agile, and should use that MAP progression.

Maybe the code in `SingleCheckActionVariant.use()` that calculates MAP could be made aware of the agile trait, which could be passed in `options` when using a free hand.

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated issue #15855
