### ISSUE TITLE
Shield bash Strike from magical shield does not have magical trait on the Strike

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#15188]
<img width="297" alt="Screen Shot 2024-06-21 at 11 08 09 AM" src="https://github.com/foundryvtt/pf2e/assets/1904698/e0044fac-dbaf-48a9-a3d2-6187d0aabcbe">

**Comment by sambomb** [comment]
I don't think it should, only if it has fundamental weapon runes etched
