### ISSUE TITLE
Inline Spell/Class DCs incorrectly being affected twice by modifiers

### ISSUE THREAD

**Issue by TheErikkuBlade** [foundryvtt/pf2e#15198]
I've been running into this issue where Inline DCs that use Class, Spell, or the better of the two (this includes kineticist abilities) are being affected twice by modifiers of any sort (the example below uses Sickened) in both positive and negative directions. The DC used for Flying Flame (which is core to the system) `@Check[type:reflex|dc:resolve(@actor.system.proficiencies.classDCs.kineticist.dc)|basic:true]` and the DC for a custom ability I made `@Check[type:will|dc:resolve(@actor.system.proficiencies.classDCs.inheritor.dc)|basic:true]` (the example below uses the Kineticist one). For instance, if an actor is Sickened 1, the DC will be adjusted by -2 instead of -1 on the inline check, but the DC shown in the actor proficiencies tab will show the correct amount (but not in the inline).

https://github.com/foundryvtt/pf2e/assets/63211464/57309e50-c280-41e6-8e41-ffae920ee6d4

I believe this to be a particularly crucial issue, as it appears to be present on both v11 and v12 versions of foundry, meaning it's been around for a while and went largely unnoticed (I also didn't see any issue reports). I've tested it in both with and without modules.

My thoughts on why this occurs, being someone with limited experience in this field: 

The inline checks are incorrectly reading the adjusted DCs and are then adjusting them a second time (but they think it's being adjusted the first time). It doesn't seem to matter if the bonuses or negatives are typed bonuses of any sort, which supports this theory.

This issue persists beyond the actor sheet and into chat cards as well, indicating a true error in calculations, and is not just a visual bug.

**Comment by TheErikkuBlade** [comment]
I realize I didn't do a great job at explaining how to reproduce the issue, so here we go, here's the easiest way to do it:
- Build a Kineticist of any level, to stay true to the example, a fire kineticist
- Pick Flying Flame, or any Impulse with a DC related ability
- Once finished, add some type of modifier to the kineticist DC, ideally through Frightened or Sickened
- Compare the DC results of Flying Flame (or other ability) to the class DC shown in the proficiencies tab of the actor sheet

**Comment by TikaelSol** [comment]
Anything with resolve() or anything with a type of flat should be immutable by default, and definitely used to behave that way. So it's definitely a bug if we're letting them double dip now.

**Comment by CarlosFdez** [comment]
Seems to be an issue with "all" modifiers. Drained does not double apply. I'll look towards addressing it.
