### ISSUE TITLE
Target roll options aren't added to recall knowledge action macro

### ISSUE THREAD

**Issue by xyzzy42** [foundryvtt/pf2e#15214]
E.g., `game.pf2e.actions.get('recall-knowledge').use({statistic: 'society'});`

Obviously while targeting a token.

The problem is that RK creates a "synthetic" DC rather than an existing DC on the actor.  It might look like `{ value: 15, visible: false }`.

Then inside `StatisticCheck.roll()` we have this check:
```ts
        const selfIsTargeting =
            !!targetToken &&
            ((this.domains.includes("spell-attack-roll") && item?.isOfType("spell")) ||
                (!["flat-check", "saving-throw"].includes(this.type) &&
                    !!(args.dc?.slug || "statistic" in (args.dc ?? {})) &&
                    (!item || item.isOfType("action", "campaignFeature", "feat", "weapon"))));
```

This check result is false and prevents target roll options from being used.  The issue is the next to last line, `args.dc?.slug || "statistic" in (args.dc ?? {})`.  The dc object created by RK, which is what `#resolveCheckDC()` will return, has neither a slug nor a statistic.

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated issue #15855
