### ISSUE TITLE
Compatibility with DF Manual Roll

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1523]
In GitLab by @f.pomerleau0 on Jun 20, 2021, 12:56

As discussed a few days ago in the discord, The DicePF2e class in PF2 that the PC Actor references does not currently use the new Async Roll system and i'ts by-passing Async roll for Manual rolls in PF2e.

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/d67229f05c2388d5b38821f4bd2461b0/image.png)

**Comment by this-gavagai** [comment]
For what it's worth, I'm still having problems with Damage Rolls. On all rolls from character sheets, DF Manual Rolls invokes correctly, but rolls from the "cards" in chat seem to bypass. If there is anything I can do to help diagnose, please let me know.

v4.6.8

**Comment by stwlam** [comment]
We're not able to guarantee any module's compatibility with the system. Sorry.

**Comment by this-gavagai** [comment]
Not asking you to guarantee anything, of course. I'm just correcting what appears to be incorrect information here in case it's helpful to anyone. Thanks for everything you do!

**Comment by this-gavagai** [comment]
I've been able to make DF Manual Roll trigger for damage rolls by changing `async: false` to `async: true` in following line:

https://github.com/foundryvtt/pf2e/blob/29affd8a14b3d012ad3b33a5beed278e96091f65/src/scripts/dice.ts#L86

It is very possible that this has larger consequences than I realize, and if I notice anything I'll post it here.

**Comment by stwlam** [comment]
> I've been able to make DF Manual Roll trigger for damage rolls by changing `async: false` to `async: true` in following line:
> 
> https://github.com/foundryvtt/pf2e/blob/29affd8a14b3d012ad3b33a5beed278e96091f65/src/scripts/dice.ts#L86
> 
> It is very possible that this has larger consequences than I realize, and if I notice anything I'll post it here.

You certainly haven't, since that's not a damage roll (it's a legacy d20 roll function).

**Comment by this-gavagai** [comment]
I don't know what to tell you. It seems to be working for me. If there's something else causing the apparent effect other than the code I changed, I have no idea what it is.

**Comment by this-gavagai** [comment]
My understanding here was wrong, and it seemed to be working for me only because of coincidental factors related to testing.

The issue seems to be related to how DF Manual Rolls recognizes roll terms:
https://github.com/flamewave000/dragonflagon-fvtt/issues/443
