### ISSUE TITLE
BUG: Kineticists not gaining the benefit of CON mod to damage for 2 action elemental blast

### ISSUE THREAD

**Issue by meditatingCybermind** [foundryvtt/pf2e#15266]
Level 2 kineticist with 2 STR, 4 CON
![image](https://github.com/foundryvtt/pf2e/assets/7494538/fb5226ba-b8a4-4f55-9c74-a53649211379)

When the attack is set to 2 action, I'm not seeing the bonus damage from CON applied.

I glanced through the rule element and didn't see anything obvious that would be the issue unfortunately. :(

First noticed on version 6.0.4

**Comment by stwlam** [comment]
Not able to reproduce, but it looks like the attack roll in chat is a single-action blast.

**Comment by meditatingCybermind** [comment]
Weird. I set the toggle to 2 action :/ not sure whats going on there

**Comment by oWave** [comment]
Check if the elemental blast action exists more than once on the sheet: #14651

**Comment by meditatingCybermind** [comment]
Ah! That was it, thank you!
