### ISSUE TITLE
[Feature Enhancment] Blind Rolls Support for Manual Rolling

### ISSUE THREAD

**Issue by 117ksk** [foundryvtt/pf2e#15269]
After Foundry v12.328, support for manual rolls to revert back to digital and respect "Blind Rolls" was added. However, in the PF2e system, secret rolls or self rolls do not register as "Blind" for the purposes of this functionality. 

My feature request would be to integrate the blind roll distinction from FVTT into the PF2e system to allow for manual rolling to respect secret rolls made within the system.

**Comment by TMunsie** [comment]
Can you please articulate a PF2e rules case for the system to modify Foundry secret rolls? Otherwise this is somewhat out of scope for the system to implement. Not saying it won’t be done but without a rules reason it is a very low priority unless a specific dev wants it and the impact on the code base and usability is negligible.

**Comment by stwlam** [comment]
Blind rolls in pf2e are blind the same way they are in any system. There are other types of whispered rolls that aren't covered by the new V12 feature.

**Comment by 117ksk** [comment]
Rules use case example of this feature would be rolling a perception check (whilst holding CTRL) and not knowing the result as by rules you as the player should not know. Or recall knowledge rolls etc. With manual rolls enabled, based on latest FVTT update, any of these secret or hidden rolls should by design not print the user for an input. Based on my testing as of today with latest FVTT stable release, this dose not function like this and a prompt is still presented to player to input a roll regardless of if it’s rolled secretly or not.

**Comment by 117ksk** [comment]
The reason I believed this to be a system feature request is based on the response I received from the Foundry discord server here:
https://discord.com/channels/170995199584108546/1184176344276406292/1256019218554421259

**Comment by TMunsie** [comment]
In Foundry your example is a blind roll. Not a secret or self roll.

A secret roll shows the GM and the player who rolled. There isn’t a PF2e use case for this.

Self roles only show the player. There isn’t a PF2e use case for this.

> Rules use case example of this feature would be rolling a perception check (whilst holding CTRL) and not knowing the result as by rules you as the player should not know. Or recall knowledge rolls etc. With manual rolls enabled, based on latest FVTT update, any of these secret or hidden rolls should by design not prompt the user for an input. Based on my testing as of today with latest FVTT stable release, this does not function like this and a prompt is still presented to player to input a roll regardless of if it’s rolled secretly or not.
