### ISSUE TITLE
Inventor Unstable Action flat check has the wrong DC.

### ISSUE THREAD

**Issue by TactiCool-HUN** [foundryvtt/pf2e#15286]
According to AoN the flat check DC for the Inventor's unstable actions is 15 (https://2e.aonprd.com/Traits.aspx?ID=416)

In the module the DC is set to 17:

![image](https://github.com/foundryvtt/pf2e/assets/108133191/6f82f507-19c1-4034-bf59-300d926ec37e)

**Comment by pedrogrullada** [comment]
What action are you attempting there?

**Comment by TMunsie** [comment]
I'm assuming you mean the PF2e system and not a module. If you believe this is generated by a module please talk to the module author. 

Please confirm your system is up to date. That box is generated by a rule element and until the errata 17 was correct. You may have to set your character to level zero and back to get the updated rule element, but I have confirmed that re-en.json is correct and says 15 for the DC.

**Comment by pedrogrullada** [comment]
Do still comment which specific action you're using, just in case it's somehow using an unlocalized Note somehow. I happened to find a spot we missed during the errata update while double-checking (Distracting Explosion).

**Comment by TMunsie** [comment]
> Do still comment which specific action you're using, just in case it's using an unlocalized Note somehow. I happened to find a spot we missed during the errata update while double-checking (Distracting Explosion).

Those roll notes are generated by the trait, not by rule elements on the individual feats. We may have missed some text in some of the feats, but that's an entirely different issue. Worth searching for, but not related to this. If we do have feats doing this manually then we have made a big mistake, and there would be two roll notes coming up (Distracting Explosion shouldn't have any rule elements on it...).
