### ISSUE TITLE
Apply templates automatically based on label of actor link in journal

### ISSUE THREAD

**Issue by yorkshirelandscape** [foundryvtt/pf2e#15280]
This is a super niche request and if you want to give it a pass, I'd completely understand. But it can't hurt to ask:

You know how you can drag Stupefied into a journal and change the label to "Stupefied 2" and when you then drag it on to a token, it will apply as Stupefied 2? I'd love to see something similar for actors and templates. This would mostly be useful to content module creators, but would be very helpful for us and eventually benefit players, as well. 

The idea, to be precise, is: say I drag a Hound of Tindalos into my journal source. This creates a link to the actor that I or others can later drag onto a scene, creating a token. It would be great if, were I to change the link label to, say, "Elite Hound of Tindalos", dragging the link onto the canvas would create a Hound of Tindalos token with the Elite template applied. Same goes for Weak. Obviously, this should only work for unlinked tokens. 

This would permit content devs to set up encounter variations in a journal without having to save separate copies of the actors with templates pre-applied. 

Thanks for considering it.

**Comment by stwlam** [comment]
What makes conditions easy to do is that their numeric values are formatted the same across across languages. "Elite" and "weak" are English words, and it's not even guaranteed that they'll precede the creature name.

**Comment by yorkshirelandscape** [comment]
Ah fair point. Oh well. Thanks for thinking about it.
