### ISSUE TITLE
Arcane, Divine, Occult, and Primal traits do not propagate the Magical trait

### ISSUE THREAD

**Issue by iBoMbY** [foundryvtt/pf2e#15302]
At least not always, in the current version 6.0.4. For example the Ghast Paralysis has the Occult trait, and when the save is posted to the chat it retains that, but it doesn't set the Magical trait, which could cause some Rule Elements not to trigger correctly, since most seem only to test for that trait.

![image](https://github.com/foundryvtt/pf2e/assets/51856268/1f4409d0-01eb-4cd2-8d86-50905da1d31b)

The same seems to be true for all magic traditions, Arcane, Divine, Occult, and Primal. I think for consistency these traits should always automatically propagate the Magical trait, wherever they occur.

**Comment by stwlam** [comment]
Working as intended, though do report any rule elements incorrectly predicating on the presence of the "magical" trait.
