### ISSUE TITLE
Force Barrage Spell

### ISSUE THREAD

**Issue by ESVincent** [foundryvtt/pf2e#15309]
The Force Barrage spell spell does not give the option to scale the spell up to 2 or 3 actions.  It does not scale up for the heightened option either.

**Comment by ammalagonc** [comment]
For the current version of the spell in the system, you have to roll for each instance of damage/shard separately.  Adding the spell variants/ability to toggle between action variants does not change that functionality.

It's the same deal with Heightening - you still have to roll each instance of damage/shard separately.

**Comment by simonward** [comment]
If you're looking to automate this functionality, PF2e Workbench has a macro.
