### ISSUE TITLE
Worm's Repast

### ISSUE THREAD

**Issue by ESVincent** [foundryvtt/pf2e#15310]
Worm's Repast does not automatically calculate the persistent piercing damage for either of the damage options and does not calculate for the heightened version of the spell.

**Comment by ammalagonc** [comment]
Can you provide a screenshot?

I checked on my end and the spell is properly heightening the persistent damage when cast at higher spell slots. 

![image](https://github.com/foundryvtt/pf2e/assets/45524683/012b1c22-1d28-423c-8c92-b1eaee6ee64c)
![image](https://github.com/foundryvtt/pf2e/assets/45524683/298e17af-5443-46d2-9530-ba526da17507)

**Comment by simonward** [comment]
> On my end, the spell shows heightening the base damage to 6d6 but it does not include the persistent damage or the off guard or slowed conditions on failures and critical failures, respectively. Thanks for looking at this. Regards, Ed
> […](#)

Have you tried refreshing the copy of the spell?

**Comment by ESVincent** [comment]
How do you refresh the copy of the spell?  I usually do the updates as soon
as they come in.

**Comment by simonward** [comment]
> How do you refresh the copy of the spell? I usually do the updates as soon as they come in.
> […](#)

You can either remove the spell and re-add it from the compendium, or open the copy of the spell and click the Refresh button.
<img width="695" alt="Screen Shot 2024-07-01 at 1 03 42 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/a6ec2d73-18aa-46dc-b2ed-af3fc837e0fb">

**Comment by Aeristoka** [comment]
@simonward even with a fresh version it doesn't work:
![image](https://github.com/foundryvtt/pf2e/assets/7988297/810ae385-25f7-49bf-92c6-e9e1128d1dda)

That's the specific error, something with the scaling formula is very upset:

[[/r floor(@item.level/2)d6[persistent,piercing]]]

**Comment by simonward** [comment]
Consider refreshing Volluk's copy
