### ISSUE TITLE
Choker-Arm Mutagen issue

### ISSUE THREAD

**Issue by Bomberman1988** [foundryvtt/pf2e#15316]
The effects of this Mutagen improves the Reach of the character **BY** the listed amount, but on Foundry it's only giving normal Reach, the effects should have _"phase":"afterDerived"_ as well, or something alike.

**Comment by pedrogrullada** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/103401186/e2ea3890-ba26-4e5e-853f-6b794a84b54b)
Reach looks to be added correctly. Here's a longsword fighter with the major effect, adjudicating flanking correctly. Same with a reach weapon, like a glaive. Keep in mind this doesn't affect the reach trait of a weapon in any way.

**Comment by jesuisfrog** [comment]
Just double checked all of the Choker-Arm mutagens and the reach is calculated correctly as [pedrogrullada](https://github.com/pedrogrullada) mentioned. 

This issue should be closed.

**Comment by Bomberman1988** [comment]
The Reach isn't working correctly, I just checked it again. The problem I mentioned isn't it giving Reach, that part I know, but this is NOT what the Mutagen does, it doesn't give you Reach, it improves your Reach BY the the listed amount, which means that the Mutagen will stack with any Reach you already have, which the effect isn't doing atm.

**Comment by jesuisfrog** [comment]
I'm not sure how you are testing it for it to fail, I just tested all of them and it works with a reach weapon. 
It sets your base reach to a value and then the reach weapon interacts with that by adding an extra 5 as per the reach trait for creatures with reach.
![image](https://github.com/user-attachments/assets/5ac275d6-3ac1-4800-b7a3-725a4d7b6743)
![image](https://github.com/user-attachments/assets/10cf48fe-9e35-4b87-846b-b3ce5d519cb7)
![image](https://github.com/user-attachments/assets/90cd1a0c-d41e-472a-9f05-eb8386d5fa3f)

**Comment by Bomberman1988** [comment]
I just checked it nd you are right, I'm having this problem tho because this mutagen isn't stacking with the Fury Cocktail Mutagen (Titanic) and with the spell _enlarge_ (I know Mutagens don't work with this spell cuz of the trait Polymorph, I just used it for this test). 
What am I missing?

**Comment by jesuisfrog** [comment]
The Fury Cocktail(titanic) and Enlarge spell do the same thing, they don't increase your reach, they make your large (or huge for higher rank enlarge) which results in an increased reach (as per the creature size rules). 

The text mentioning the reach increase is just a reminder that larger creatures have a larger reach.

With that extra context, I'll fix the Choker-Arm mutagens to work in combination.
