### ISSUE TITLE
GM Vision does not stick between scenes

### ISSUE THREAD

**Issue by justinrpurdy** [foundryvtt/pf2e#15332]
After enabling the GM Vision feature on a scene, if I go to another scene GM vision stops working and must be disabled/re-enabled. Nothing shows up in the console when this happens.

**Comment by stwlam** [comment]
Not able to reproduce. Is it possible there's a module conflict?
[video](https://github.com/user-attachments/assets/01a99e81-b2cf-4785-89ad-972c259df346)

**Comment by justinrpurdy** [comment]
Looks like it's a conflict with SmallTime, actually.
