### ISSUE TITLE
Issues with AdjustStrike and adding Property Runes, Conducting and Merciful primarily

### ISSUE THREAD

**Issue by TheErikkuBlade** [foundryvtt/pf2e#15372]
While making some homebrew items and effects, I've frequently been running into some pains with AdjustStrike. Specifically for adding property runes. It seems that, not every property rune functions properly when being granted via AdjustStrike. From my observations:

- Merciful rune tends to break when granted via AdjustStrike
- Conducting rune doesn't function at all when added via AdjustStrike. When using Roll Inspector, I can see it in the Roll Options, but for some reason it doesn't *count* the item as having the rune, and thus the Conduct Energy effect does nothing. It doesn't even add the rune in the details bar.
- Anytime any property runes are given via AdjustStrike, if you mess with the item even a little bit (for example, opening and closing the "Edit Item" or changing the item to a "Specific Item" and back) makes the runes granted permanent, which can make things a bit messy.
- Using toggleable roll options for adding property runes tends to break things, often by making the runes permanent on the item even when turning off the roll option (like above).

I might add to this further if I discover any other issues with AdjustStrike and property runes. The ones that seem to have the most issues are ones that aren't the Ghost Touch rune or ones that aren't just damaging enhancers.

**Comment by stwlam** [comment]
Closed by #15336
