### ISSUE TITLE
Cannot update, see below error

### ISSUE THREAD

**Issue by Jfrankfl** [foundryvtt/pf2e#15399]
![image](https://github.com/foundryvtt/pf2e/assets/159719270/13f192e7-28ce-4642-9884-8ab6836eb313)

Currently on Foundry VTT V11.315

My PF2E Version is 5.15.3 and cannot update it despite there being new versions available on V11

**Comment by TMunsie** [comment]
That error is generated by Foundry, not the system. The system update points to the latest release. If you wish to remain on V11 and update you will have to install the system via manifest as they were changed during the transition and reverted once V12 became stable.

**Comment by Jfrankfl** [comment]
@TMunsie The manifest URL for version 5.16.1 displays as:
https://github.com/foundryvtt/pf2e/releases/latest/download/system.json
Which I know wont work as it is not the newest version but I attempted
https://github.com/foundryvtt/pf2e/releases/5.16.1/download/system.json
It did not work... is there a different manifest URL for this version?

**Comment by TMunsie** [comment]
Per the package page with the link: https://github.com/foundryvtt/pf2e/releases/download/5.16.1/system.json

![image](https://github.com/foundryvtt/pf2e/assets/25963508/40d344c5-e85a-4a45-8f08-dff47fd92436)
