### ISSUE TITLE
Default Size Dynamic Tokens Look Small

### ISSUE THREAD

**Issue by TangledLion** [foundryvtt/pf2e#15390]
What it says on the tin. Because of how Dynamic Tokens work, when I create a medium Creature and give them a Dynamic Token it looks like the Token is at 0.8 scale. For a Large one, it appears to be at 1.8 scale, ETC. Scaling them up manually is simple enough but maybe for simplicity's sake the system could somehow adjust the scaling on the Fly maybe?

**Comment by stwlam** [comment]
This is a core feature, and while I'm not sure of the details that go into it, the behavior you describe in pf2e is present in all systems.

**Comment by stwlam** [comment]
I reconfirmed that this is core behavior, but reopening in case there is some way to carefully thread in the system's mechanical autoscaling without interfering with commercial products.
