### ISSUE TITLE
Previous versions

### ISSUE THREAD

**Issue by Afgar** [foundryvtt/pf2e#15425]
I don't see any way to view/download pervious versions of PF2E. I have other addons that are not version 12 compatible but I don't see a way to download version 5.16.1 which is what foundry says is the last version of PF2E for Foundry version 11. Could someone help me out with getting the 5.16.1 files?

**Comment by TikaelSol** [comment]
You can see all of our releases [here](https://github.com/foundryvtt/pf2e/releases). Just download the pf2e.zip file for the release you want.

However, if you are running v11 then 5.16.1 will be the version of the system that installs when you install PF2e.
