### ISSUE TITLE
Glutton's Jaw temp hp not rollable

### ISSUE THREAD

**Issue by DoggieBert** [foundryvtt/pf2e#15422]
When making a strike with Glutton's Jaw the roll for temporary hp in the strike note is not rollable.

To reproduce:
Add the Spell Effect: Glutton's Jaw to a pc
Roll damage
The damage card has a roll note about the Glutton's Jaw effect, but the Xd6 is not rollable.

Foundry 12.328
Pf2e 6.0.4

**Comment by simonward** [comment]
This is on hold until PC2.
