### ISSUE TITLE
Strikes with the same slug don't merge or replace each other

### ISSUE THREAD

**Issue by DoggieBert** [foundryvtt/pf2e#15421]
When an ancestry with a native jaw strike has the Glutton's Jaw effect applied it doesn't change the jaw strike. I would expect it to either 1) replace the native jaw strike or 2) add an additional jaw strike.

To reproduce:
Create a pc actor with an ancestry with a native jaw strike (say gnoll)
Add the Spell Effect: Glutton's Jaw

Foundry 12.328
Pf2e 6.0.4

**Comment by TikaelSol** [comment]
The issue is colliding slugs, for gluttons jaws that is going to be irrelevant in a week since that spell is changing in Player core 2.
