### ISSUE TITLE
Feature Request: Make it so Creatures with Confused can't get Flanking from 'ex-allies'.

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#15441]
I don't know if you can add something to the flank check to take into account the effect/condition or if you'd need to add an RE to the condition itself, but it'd be nice if system had a way to automate the whole "you don't treat anyone as your ally (though they might still treat you as theirs)" clause for the purposes of Flanking automation.

**Comment by websterguy** [comment]
The confused condition already sets the data on the actor for "can flank" to false.
