### ISSUE TITLE
Expand `check:total:natural` to more Rule Elements

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#15457]
A suggestion to expand the pre-existing `check:total:natural` roll options that are only available on `AdjustDegreeOfSuccess` elements to also apply to other REs, **primarily `Note`s and `FlatModifier`s.**

This would be great automation for abilities that trigger off of rolling a "natural" number, such as a nat 1 (`check:total:natural:1`).

There is an example of Paizo abilities using natural dice results as well, [`Ageless Patience`](https://2e.aonprd.com/Feats.aspx?ID=4412&Redirected=1), currently handled manually and appearing on all rolls regardless of result.

**Comment by n1xx1** [comment]
Maybe I'm wrong, but it feels like this should be doable with AdjustDegreeOfSuccess already without the Note.

```json
{
    "key": "AdjustDegreeOfSuccess",
    "selector": "skill-check",
    "predicate": [
        "ageless-patience",
        "check:total:natural:1",
        { "not": { "lte": ["check:total:delta", -10] } }
    ],
    "adjustment": { "criticalFailure": "to-failure" }
}
```
