### ISSUE TITLE
Current implementation of bulk limits causes unintended issues with tiny characters

### ISSUE THREAD

**Issue by tcordeki** [foundryvtt/pf2e#15458]
In the current implementation of encumberance, instead of adjusting the max encumberance of a PC, items bulk is adjusted so items are the "normal" bulk for the creature's size. 

For example, in the current system a Large PC with +1 Str still has an encumberance limit of 6, and becomes over encumbered at 11. A Large Lonsword, with a bulk of 2, has its bulk adjusted back down to 1. Medium items have their bulk halved, so a Medium Maul goes down to 1 bulk, a medium longsword to L bulk, and a medium dagger to negligible bulk. In the end, Large PCs are still able to carry the same amount of gear as the rules intend.

This is also applied to Tiny PCs, but in the opposite direction. Instead of halving their encumberance limits, all medium item bulks are multiplied by 2, while tiny items are their normal bulks. While this may seem fine in theory, this actually causes three major issues with Tiny PC encumberance.

1. By not dividing bulk in half, the bulk limit is not accurate. A tiny PC with +0 str should be encumbered at 2 bulk, as you should divide 5 by 2 and round down. By not dividing, and multiplying everything instead, this gives them an effective 2.5 bulk limit.
2. When you multiply an item that is normally L bulk, the system increases the bulk to 1. While this is intended for increasing Medium objects to Large ones, it should not be applied to a tiny creature holding a medium object. This is essentially a 10x weight increase to L bulk items, applied only to Tiny creatures. In current RAW, a +1 str Human can hold 60 medium daggers, and a +1 str Sprite can hold 30. With the current implementation, that is reduced to 3, which is not intended nor supported by RAW. It is just as rediculous of a 5'9" human to be carrying 60 daggers as it is for a 2' tall sprite to carry 30 of them. 
3. Similar to point 2, when reducing an item to Tiny size, it should become L bulk. By "normalizing" item bulk for tiny creatures, items that should be L bulk are increased back to 1 bulk. This makes items far more cumbersome than RAW. For example, a tiny longsword should be L bulk, even to a tiny creature, however the system increases it back to 1 bulk which makes it essentially 10x heavier, meanwhile tiny creature's bulk limits not being halved is only giving them 2x more bulk. 
4. Tiny creatures have no checks to make tiny neglible items into L bulk. For example, a tiny flint and steel is still counted as neglible by the system, when it should be L bulk, since tiny creatures treat nothing as negligible bulk.

Here are the changes I propose:
1. Instead of multiplying and dividing item bulk based on the size of the carrier, simply multiply or divide bulk limits of the character. This will make Tiny PCs have appropriate bulk limits, and remove the incorrect bulk modification for medium L bulk items being held by tiny PCs, while Large PCs will be unaffected. 
2. Add a check to Tiny PCs only for negligible bulk items. If an item of negligible bulk is found, regardless of its size, increase it to L bulk.

**Comment by stwlam** [comment]
To be clear, there are no intended consequences for tiny PC: bulk rules were written before they came into existence. A tiny creature's bulk limit of "half" already won't amount to that since negligible bulk items become light, etc.

**Comment by tcordeki** [comment]
Both Sprites and Poppets reference the bulk rules on page 295 of the Core Rulebook, which did not change in Player Core. Players will look to these rules when trying to figure out how much bulk they can carry, then when building the PC in Foundry will find a completely different set of rules being used. The system should follow RAW whenever possible.

**Comment by CarlosFdez** [comment]
Regarding the 1L becoming 1 bulk, while nothing says that should occur, there is a passage in the opposite direction, which can imply it goes both ways:

> One made for a Tiny creature still costs 1 gp (due to its intricacy) and has 1/2 Bulk (rounding down to light Bulk).

We need an FAQ entry about bulk, because you're not the first to complain about it. PF2e's system is broken at its core, and the most amenable I'd be is discussing with a module dev on what to expose to make a "better homebrew bulk" module.

**Comment by TMunsie** [comment]
I've asked Paizo for explicit clarification on what the rules should be and how things should be accounted for.

If we can't solve it the closest RAW thing we can do will be to disable bulk calculations for tiny creatures.

**Comment by tcordeki** [comment]
I added additional information about how the system doesn't decrease the bulk of tiny 1 bulk items to L bulk for tiny creatures, which causes a vast increase in the amount of bulk a tiny creature would be carrying.

**Comment by stwlam** [comment]
Working as intended on all counts, sorry
