### ISSUE TITLE
Astral and Greater Astral property runes do not exist as an option for weapons

### ISSUE THREAD

**Issue by Erokusan** [foundryvtt/pf2e#15479]
Going through the property runes on weapons, Astral (And by proxy, Greater Astral) does not exist as an option to choose on weapons.

**Comment by simonward** [comment]
Cannot reproduce. What version are you running?
<img width="695" alt="Screen Shot 2024-07-18 at 4 57 04 PM" src="https://github.com/user-attachments/assets/ec680903-4b7b-4085-bd7e-3152b1251e59">

**Comment by Erokusan** [comment]
Ah, it's on an old version, apologies, I will see if I can convince the gm currently running to update.
