### ISSUE TITLE
(Feature Request) itemAlteration to change number of damage dice.

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#15505]
Title, please add a way to change the base damage dice of an item with itemAlteration you can currently change the dice face and edit persistent damage.
![image](https://github.com/user-attachments/assets/a3b16040-cd90-4f75-b8be-d79675f97fbc)

Would also be groovy if you could edit all the fields here with the RE especially the custom damage fields.

**Comment by stwlam** [comment]
Custom damage fields will sooner go away than get any attention, but can't you use a `DamageDice` RE?

**Comment by CrackJackFlood** [comment]
> Custom damage fields will sooner go away than get any attention, but can't you use a `DamageDice` RE?

damageDice RE add to the strike damage doesn't alter the base weapon damage dice meaning stuff that interacts I with base weapon, damageDice don't account for the added weapon damage.

I have been wanting this for around 10 months and asked about it quite a few times I have been waiting to see the new weapon/equipment attachment system because I thought since runes and stuff will be getting redone there would of been changes and updates to itemAlteration. I realised I should just explicitly make the feature request.

**Comment by CarlosFdez** [comment]
The Striking RE is the only way to add base damage dice currently. It did not before due to a bug, but it should work properly now. What case are you doing where that doesn't work?

**Comment by CrackJackFlood** [comment]
> The Striking RE is the only way to add base damage dice currently. It did not before due to a bug, but it should work properly now. What case are you doing where that doesn't work?

Striking RE doesn't just add base damage dice it also adds additional traits such as magical. I would like a way to manipulate the base damage dice of an item without additional things.

**Comment by CarlosFdez** [comment]
I would be more amenable to making the striking RE add non-magical. But I don't know what the use case is beyond HQ weapons which were not reprinted in remaster. If you find a good use case in paizo content or high profile 3pp like battlezoo, that might improve your case.

**Comment by CrackJackFlood** [comment]
#15650 pretty sure the PR closes this issue.
