### ISSUE TITLE
System actions localization issue when using a lore skill

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#15518]
When using either a `BaseAction` or the old actions found in `game.pf2e.actions` and providing a lore `statistic` in place of the default one, the header in the flavor text of the chat message tries to localize the `statistic` name as an `ActionCheck`.

![Foundry_Virtual_Tabletop_tUQ61noWif](https://github.com/user-attachments/assets/5a5966a8-2f91-4491-928e-6ee82fb0bd6b)

P.S.: We also have to manually add the `-lore` to the `statistic` to match the changes made in `6.1.0`

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated issue #15855
