### ISSUE TITLE
REdistrubute Potential (psychics) Amped not functioning properly.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#15524]
redistriubute potential when amped is selected isnt heigthening the spell damage properly. 

https://2e.aonprd.com/Spells.aspx?ID=1138

**Comment by pedrogrullada** [comment]
The spell heightens properly on release. I suspect you were trying to heighten the spell at a spell rank lower than what it's possible. It's minimum rank is 5. Its formula fails if one tries to do that, so we're adding a safeguard against that. See comment in #15648

**Comment by ThingsCouldGetDicey** [comment]
> The spell heightens properly on release. I suspect you were trying to heighten the spell at a spell rank lower than what it's possible. Its minimum rank is 5. Its formula fails if one tries to do that, so we're adding a safeguard against that. See comment in #15648

was this tried with amping?

**Comment by ammalagonc** [comment]
Yes, please see the following screenshots for reference:

![image](https://github.com/user-attachments/assets/f9366a09-082e-4fc8-8267-f6b4fd545ac2)
![image](https://github.com/user-attachments/assets/c729d360-0cdd-4389-988f-8c3a33183c8f)
