### ISSUE TITLE
Alchemical Error

### ISSUE THREAD

**Issue by Jenesequa** [foundryvtt/pf2e#15541]
I noticed recently that, at least at level four, Alchemist gets access to the level five ability "Field Discovery" wherein you can produce three elixirs that have a corresponding trait to your field. Besides Field discovery there are no other feats that increase the amount of elixirs you can produce with advanced alchemy for your daily prep

**Comment by ammalagonc** [comment]
Pending remaster changes

**Comment by Jenesequa** [comment]
As I am not the owner of the server I am unable to disable the mods, but here is the list.
![image](https://github.com/user-attachments/assets/58b27e79-9239-43a4-9589-850ba1559c32)
![image](https://github.com/user-attachments/assets/c5488449-3ab8-4e0b-8807-fdebc904d28a)
and a copy of my character so you can try to recreate it.
https://pathbuilder2e.com/launch.html?build=820550

And the error that I was talking about;
![image](https://github.com/user-attachments/assets/b5945a8a-6344-4112-8e19-71aca282ed45)

**Comment by ammalagonc** [comment]
If I understand correctly, it's supposed to craft 3 elixirs at the cost of one reagent. Is that correct?

Please note - due to the upcoming Remaster changes, this feature will function differently.

**Comment by Jenesequa** [comment]
The issue is that it's crafting MORE than it should at this level. Field discovery doesn't hit until level five, so it's creating more elixirs than it should.
![image](https://github.com/user-attachments/assets/4e603e63-dbb9-47d3-b600-7780b0ddb7b1)

**Comment by ammalagonc** [comment]
OK, I rebuilt your character using my instance of Foundry and can confirm that it is only creating 2 items as expected. 

Either one of the modules installed in the world is messing up with your character or you might need to re-create the character from scratch (sometimes the Pathbuilder imports can get messed up).

**Comment by stwlam** [comment]
We strongly recommend not using importers: they will produce broken characters without exception, even it is not immediately obvious.

**Comment by Jenesequa** [comment]
Alright, as long as the issue isn't the pf2e vtt itself I can deal with it. I just wanted to make y'all aware.
ty for the help
