### ISSUE TITLE
Campaign tab of the compendium browser is empty after changing browser source settings

### ISSUE THREAD

**Issue by oWave** [foundryvtt/pf2e#15555]
1. Turn on campaign specific features in the system homebrew elements settings
2. Open the compendium browser. Shows campaign feats and the source filter as normal
3. Turn off a source in the settings tab
4. Campaign tab no longer shows any feats and the source filters are blank

![image](https://github.com/user-attachments/assets/e01a0a3e-c3a5-457a-8dd9-0cec7ed7f7ad)

Re-enabling whatever source got turned off or resetting the source settings doesn't fix the issue.

v12 Build 329
pf2e v6.1.1

**Comment by PrinceEarwig** [comment]
Just a note to say this is still happening in 6.3.1
