### ISSUE TITLE
{Feature Request} More feat slots.

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#15554]
It would be nice to be able to have other ways generating feat slots on a character sheet. It would also be nice to have more options and softer barriers when it comes how feats are distrobuted. Examples of this instead of check box have variable box so you could have x number feats given at level. No level limit so you could have progression past 20. Maybe have a way to freely designate what sort of feats you get progression for based on the traits of the feat.
![image](https://github.com/user-attachments/assets/f78cb8a7-9579-4648-8dbd-d5424606e218)

**Comment by stwlam** [comment]
You'll need to turn on campaign feats for that.
