### ISSUE TITLE
Missing Prerequisite: Sharpened Senses

### ISSUE THREAD

**Issue by RodiakWolfshain** [foundryvtt/pf2e#15551]
Sharpened Senses is missing the prerequisite "Natural Senses"

**Comment by ammalagonc** [comment]
Hey there,

Looking at HotW the feat itself does not list a prerequisite:

![image](https://github.com/user-attachments/assets/5cc0cd9c-babb-4557-b517-c956302dbaf0)

I checked the Howl of the Wild errata and unfortunately, it was not covered there either:

![image](https://github.com/user-attachments/assets/4ddcc587-3099-472d-b8a7-a27df55d1973)

I agree that the feat text states that it uses `Natural Senses` as its base. Will try and see if we can get some clarification.

Thanks for pointing this out.

**Comment by ammalagonc** [comment]
OK, had someone check else check this and the way the feat reads off is that allows you to use Seek using one of the senses granted by Natural Senses.

Natural Senses is not required.
