### ISSUE TITLE
Weapon Infusion toggles are in wrong domain

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#15563]
![image](https://github.com/user-attachments/assets/432a0696-86a7-4aed-aed4-9f1f653fb863)

It would be nice to have the weapon infusion roll options present in the elemental blast macro popup just as the action number one.

I thought it was the case before, but i may be misremembering.

**Comment by stwlam** [comment]
?

**Comment by CarlosFdez** [comment]
I think reon is talking about toggleables, but I Never used this dialog so I wouldn't know if it did or didn't. I can investigate.

**Comment by reonZ** [comment]
The system exceptionally adds the action cost roll option to the element blast popup, i thought it would be nice if it also did it for the weapon infusion options.

![Foundry_Virtual_Tabletop_XXYYLYnPLi](https://github.com/user-attachments/assets/883283b5-c2ae-4a7b-8555-c679f77ad84e)

**Comment by stwlam** [comment]
It functions without as far as I'm aware. Is this a big report staying out doesn't?

**Comment by CarlosFdez** [comment]
reonZ effectively wants to select agile vs ranged in the popup.

**Comment by reonZ** [comment]
![image](https://github.com/user-attachments/assets/6753ce72-30c9-4b7f-9da3-778718f67fe5)

Even after `6.1.2`, the options are not showing up in the elemental blast attack popup.
