### ISSUE TITLE
Game Mastery Guide compendium entries have no text

### ISSUE THREAD

**Issue by farling42** [foundryvtt/pf2e#15573]
Foundry 12.330
PF2 version 6.1.2

The Game Mastery Guide journal compendium (gmg-srd) has lots of entries, but no pages in any of the entries.

**Comment by farling42** [comment]
This is because even in Foundry V11, the journal entries hadn't been converted from the V9 format.

Support for the old V9 format of journal documents was removed in V12.

**Comment by TikaelSol** [comment]
Ok, chased down the last time anyone had actually intentionally edited that compendium and not simply swept it up in a larger PR that touched all compendiums: December 2020.

So, we're going to go ahead and remove the compendium.
