### ISSUE TITLE
Damage redirections can ignore resistances if redirecting from immunities

### ISSUE THREAD

**Issue by reyzor1991** [foundryvtt/pf2e#15577]
<img width="964" alt="Screenshot 2024-07-26 at 01 41 37" src="https://github.com/user-attachments/assets/6d9396ee-6926-4c85-a03b-8708ae0a1457">
<img width="685" alt="Screenshot 2024-07-26 at 01 42 13" src="https://github.com/user-attachments/assets/0ef50197-a5fa-4707-86e0-494bc79cdf3b">
<img width="343" alt="image" src="https://github.com/user-attachments/assets/89334ab9-ca14-4725-b046-cdc528121047">

but works if add bludgeoning resistance

<img width="957" alt="image" src="https://github.com/user-attachments/assets/dafed87f-6a0e-4888-a668-0e4f7f994b71">

**Comment by stwlam** [comment]
looks like it worked?

**Comment by reyzor1991** [comment]
On first screen, creature has bludgeoning immunity and piercing resistance - 5

Damage roll - 6 bludgeoning

Damage should be 1 but was 6




When I add bludgeoning resistance to creature, it worked correctly
