### ISSUE TITLE
SpecialStatistic rules not supported for familiars

### ISSUE THREAD

**Issue by iconmaster5326** [foundryvtt/pf2e#15584]
When you attempt to make a SpecialStatistic rule on an effect granted to a familiar, you get the following message, and it fails to function:

![image](https://github.com/user-attachments/assets/975a3516-1532-49f2-9a33-7a75e50428c2)

It would be nice if familiars could have derived statistics too. The ones I specifically created don't have any user interface elements (such as `togglable`), so even basic support for these would be nice.

**Comment by TikaelSol** [comment]
Consolidating into #15858
