### ISSUE TITLE
Deadly Simplicity rule doesn't work on weapons

### ISSUE THREAD

**Issue by farling42** [foundryvtt/pf2e#15594]
The Deadly Simplicity rules only seem to work to increase simple weapons and unarmed to d6.

Create a cleric with Warpriest doctrine, Deity Lamashtu, and add a Falchion weapon.

The damage remains at d10, when it should be increased to d12.

Simplifying the predicate in the rule to only have `"item:deity-favored"` makes it work properly (but obviously breaks the functioning of the second paragraph of the feat's description).

**Comment by farling42** [comment]
It was also raised by #203 in 2020.

**Comment by Allalinor** [comment]
That is correct handling of the feat in the system.
As you can see from the prerequisite it only works for simple weapons and unarmed attacks.
Not martial or advanced weapons.

**Comment by stwlam** [comment]
The "Simplicity" bit in the feature's name turns out to be crucial:
> **Prerequisites** deity with a simple or unarmed attack favored weapon, trained with your deity's favored weapon

**Comment by nikolaj-a** [comment]
Even the First Doctrine explicitly predicates it:
> If your deity’s favored weapon is a simple weapon or an unarmed attack, you gain the Deadly Simplicity cleric feat (page 113).
