### ISSUE TITLE
[Data entry] Age of Ashes Bestiary: Scarlet Triad Mage has wrong wand

### ISSUE THREAD

**Issue by manfred7168** [foundryvtt/pf2e#15593]
In the inventory of the Scarlet Triad Mage is still the old 'Wand of crushing despair' which needs to be replaced by a 'Wand of wave of despair', because the spell was renamed in Core Rules.

**Comment by ammalagonc** [comment]
The Wand itself is linked to the correct spell, so it should work when trying to cast the new/renamed spell.

**Comment by TikaelSol** [comment]
We are not changing legacy actors more than we have to.
