### ISSUE TITLE
Untamed Shift not giving Untamed Claws to Lizardfolk

### ISSUE THREAD

**Issue by Xelveki** [foundryvtt/pf2e#15607]
I have a Lizardfolk druid in a game of mine and I can't get Untamed Shift to give him Untamed Claws. 

He's got the standard unarmed attack and a claw attack from being a Lizardfolk. Nothing new pops up when I give him Untamed Shift. It also does not convert his existing claw attack to the Untamed attack or give his existing claw attack the magical trait. The buff pops up on his character, I can see it in the effects tab.

If I make another druid that's not a lizardfolk, it works fine.

Foundry: v12.330
PF2E: v6.1.2

In the image, the top is our Lizardfolk and the bottom is what I would expect, taken from a Halfling. 
![Claws](https://github.com/user-attachments/assets/5623affa-6f32-40c0-8cad-5957dcb0167b)

**Comment by simonward** [comment]
Same issue as https://github.com/foundryvtt/pf2e/issues/15421?

**Comment by Xelveki** [comment]
Seems reasonable to think it is.

**Comment by TikaelSol** [comment]
Closing as a duplicate issue
