### ISSUE TITLE
Cannot edit Deity Items

### ISSUE THREAD

**Issue by lago508** [foundryvtt/pf2e#15634]
Edits to the fields in custom Deity items aren't sticking: they don't update when you press Enter. Weapon items seem to be working fine. A few people have reproduced the error.

Version 12 build 330 of foundry, reproducible with no modules running.

![image](https://github.com/user-attachments/assets/a4c0f4ce-1c9b-4782-903c-598027aa7999)
![image](https://github.com/user-attachments/assets/757ebbc4-c762-4747-bd9d-601dc853e4f1)
![image-1](https://github.com/user-attachments/assets/cfca158d-7d3f-456a-81e9-b9cbfe736a14)
![image](https://github.com/user-attachments/assets/1b8a2e9a-6c23-4377-b28c-49d55de89f9f)
![image](https://github.com/user-attachments/assets/9b10cf68-7d38-42bc-bfc3-4dad39254f62)

**Comment by stwlam** [comment]
Unable to reproduce. Would you mind providing some steps?

**Comment by stwlam** [comment]
Thanks. I was able to reproduce it with a new deity item.
