### ISSUE TITLE
Weapons action tags (sheathe, retrieve, etc)

### ISSUE THREAD

**Issue by tpegasus79** [foundryvtt/pf2e#15644]
I just noticed on my PCs character sheets the tags for action on weapons show the entire path instead of just retrieve, change grip, drop, draw, etc. This is what is showing.  Might have been a small issue form the last update 6.1.3.

![Action weapon tags](https://github.com/user-attachments/assets/5310690b-45ff-4691-b613-2dac82ff883b)

**Comment by stwlam** [comment]
This won't be an issue with the release itself: try a hard refresh or uninstalling and reinstalling the system.
