### ISSUE TITLE
Vector Screen heightened version shape is ambiguous

### ISSUE THREAD

**Issue by FolkvangrForgent** [foundryvtt/pf2e#15661]
The [Vector Screen](https://2e.aonprd.com/Spells.aspx?ID=1131) is as written a rectangle and it's heightened version is a 10x10 rectangle (as stated by _10 feet wide_) which would be a 5 foot burst however it is coded as a 10 foot burst. I have checked my book and the errata for relevant changes and text validity.

**Comment by FolkvangrForgent** [comment]
Rereading the spell with a fresh mind. I think the ambiguity of the spell requires a Errata from Paizo... It only says _10 feet wide_ which is modification to its original area of single square. I assumed this was an odd case of square shaped area but it just isn't clear enough what the heightened version is meant to be. It could be interpreted as a 10ft burst, 2 adjacent squares, or a 5ft burst.

**Comment by TikaelSol** [comment]
Closing as a whyzo, need them to clarify what they mean here.
