### ISSUE TITLE
PC2: Breath of the Dragon feat from Dragonblood versatile heritage is missing its action

### ISSUE THREAD

**Issue by intrand** [foundryvtt/pf2e#15689]
Player Core 2, page 45, right column, `Breath of the Dragon` 1st level feat should grant a 2-action activity similar to other Dragon Breath things in the system already.

I couldn't find any correct action in the system compendium packs, and obviously no GrantItem rule element on the feat since no action exists to grant.

Thank you very much for your hard work on this! The new content looks great so far!

**Comment by pedrogrullada** [comment]
The feat itself is an action, but it was entered as a passive. That'll be fixed, but keep in mind that it's not automated yet. Probably will be in the next few days.

**Comment by intrand** [comment]
Sweet! I wasn't sure how you wanted to handle it in the system as far as items go and such. Thanks very much!
