### ISSUE TITLE
Player Core 2 Herbalist Dedication bugged

### ISSUE THREAD

**Issue by Icarus-the-phoenix** [foundryvtt/pf2e#15685]
Player Core 2 herbalist dedication is missing the following paragraph and functionality.
"You become an expert in Nature and can use Nature instead of Crafting to Craft alchemical consumables with the healing trait. You don’t need to be trained in Crafting to do so, and you can use healer’s tools instead of alchemist’s tools"

 It does not grant expert in the Nature skill or the ability to craft with Nature instead of Crafting.

![image_2024-08-01_151255756](https://github.com/user-attachments/assets/65b01045-966d-4cce-bd90-2468b7dafd04)
![image](https://github.com/user-attachments/assets/f8f86c76-19f5-42f4-9c35-442aa95f63e6)

**Comment by ammalagonc** [comment]
I submitted a PR to get the text and proficiency scaling added. 
Please note that with the changes introduced in PC2, the crafting aspect of the dedication (along with the Alchemist and any other Alchemical dedications) must be reworked from the ground up.
