### ISSUE TITLE
Potency and resilient runes can be set to `null` from armor sheet

### ISSUE THREAD

**Issue by yannou38** [foundryvtt/pf2e#15691]
![image](https://github.com/user-attachments/assets/a5fb1b0c-d152-4c68-99bc-0bfdb56d7519)

If removing the armor potency rune of an armor that had one, the value get undefined, breaking REs (especially armor specialization). it should be set to 0 instead.

May be valuable to check other fundamental runes behaviour

~~A bit of quick testing on a custom armor (armor in earth) seem to show that no potency rune doesn't define the value, which make it a bit harder to create a RE that allow to set the armor specialization, while it could be valued at 0
I was able to go around it by defining a second RE without the variable, but it could be interesting taking a look at this, i don't think this was the behavior before.
Edit: a quick test with a test fighter wearing a full plate seem to show the same issue, by setting then removing a potency rune~~

**Comment by stwlam** [comment]
This has to do with not wearing armor rather than not having any runes. You can predicate on "armor:equipped" as a guard.

**Comment by yannou38** [comment]
the armor IS equipped 
![image](https://github.com/user-attachments/assets/b344ae86-72a0-435a-a277-5eec30d03687)
and work properly with a potency rune set
![image](https://github.com/user-attachments/assets/60b88378-85c0-45a1-8cd5-dae703799035)


Another example using a fighter:
start with nothing
![image](https://github.com/user-attachments/assets/5f67329e-c037-4828-9042-058ce0fb7a0a)
add full plate and equip it
![image](https://github.com/user-attachments/assets/c920a507-c55d-44a4-822f-39103f5c85aa)
add rune, resistance get updated
![image](https://github.com/user-attachments/assets/8358f06c-ab8b-4936-a006-c7613383352c)
then remove rune and resistance just disappear and break 
![image](https://github.com/user-attachments/assets/5d1423fa-b5f6-4930-af03-009f703d6464)

**Comment by stwlam** [comment]
thanks for the additional; we'll look more closely
