### ISSUE TITLE
Premaster Specific Draconic Exemplars don't have their Blood Magic effect shown on draconic bloodline spells

### ISSUE THREAD

**Issue by mela-lomaniac** [foundryvtt/pf2e#15697]
When using a premaster dragon as a Draconic Exemplar for Draconic Bloodline Sorcerers, their Blood Magic Effect doesn't appear on the Sorcerous Gift spells that are shared by all draconic sorcerers.

Additionally, (and tangentially related,) premaster draconic exemplars are set as arcane with the damage types from before the remaster, but under PC2's rules for specific draconic exemplars, they should use the tradition of the spellcaster variant of those dragons alongside the damage type associated with that tradition. (I'm not confident this is a serious enough issue that it should be posted separately, but I would hope for it to be addressed)

**Comment by pedrogrullada** [comment]
It was a deliberate decision to keep legacy options as they were before remaster. Maintaining their previous damage types, their tradition (all draconic sorcerers were arcane pre-remaster) and their spell list.

**Comment by TikaelSol** [comment]
Legacy options are, unless reprinted or mechanically unworkable, staying as is.
