### ISSUE TITLE
Animal Forms erroniously let you keep your other (unspecified) speeds

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#15698]
If you use Animal Form (for example) to turn into a Shark or Orca you gain their swim speeds as you should, but you also erroneously keep your land, fly, burrow, and climb speeds as well. This same pattern is seemingly true for all the animal forms - they let you keep whatever speeds they don't specify they give you (fly, burrow, etc).

**Comment by stwlam** [comment]
CRB never had anything to the effect that you lose them. Did PC1/2 change it?

**Comment by GorgoPrimus** [comment]
Oh, I assumed polymorphing into said animal and stating you can't change statistics meant you didn't keep your legs or wings if you turned into a shark et al.

**Comment by ammalagonc** [comment]
![image](https://github.com/user-attachments/assets/0120ef12-58a9-4c05-b375-ffb728dde691)
 
 PC1 Polymorph trait - Doesn't seem to be a indicate that you loose any of your previous speeds.

**Comment by stwlam** [comment]
Individual statistics can't change with a few exceptions, so you wouldn't benefit from an item bonus to your land speed. But it doesn't mention removing speeds outright like it does types of attacks you can make.

**Comment by GorgoPrimus** [comment]
Well that seems like a very bizarre way to handle battle forms where someone turns into an animal and creates very silly situations that I'd be surprised were RAI, but if that's RAW it's RAW. Thanks for looking into it.

**Comment by GorgoPrimus** [comment]
You know, after thinking on this some more and talking to others, this line of argument makes less and less sense to me. Yes, the stat blocks don’t say “land 0” (because not including a land speed is functionally the same) and it doesn’t explicitly say you lose your existing speeds when you transform, but it also doesn’t explicitly say you replace your land speed of 35 as a nimble elf with 25 when you become an Ape. Would you also claim that RAW that listing any form with a listed land speed of 20 and under is a pointless waste of ink because you’d always choose to use your kept Ancestry speed that typically runs from 25 to 30?

I’d like to ask you guys to reconsider this ruling that makes speeds on Forms fairly pointless unless it’s a kind of speed you didn’t already have and allows for Sharks to run like the wind on nonexistent legs. It’s clearly not the intent and what we do have written RAW is heavily implied to work this way or else a lot of it wouldn’t make sense both thematically and mechanically in the text.

**Comment by GorgoPrimus** [comment]
The 2026 Spring Errata has now explicitly made you lose other speeds while in Battle Forms. Should this be reopened, or should I make a new identical issue, or is this being worked on and just isn’t in yet?

“Page 301: The polymorph trait has been updated to clarify how Speeds work. In the second paragraph, before the final sentence, add: “You lose your Speeds and gain those of the battle form.””
