### ISSUE TITLE
Blade Ally only applies Returning or Shifting for Good champions

### ISSUE THREAD

**Issue by bookgrub** [foundryvtt/pf2e#15728]
With v6+, the Blade Ally only offers the Returning and Shifting options, not Ghost Touch or Disrupting. This applies to all weapons I have tried so far.

Not tested on v5.x

Short video of the behaviour attached.

https://github.com/user-attachments/assets/4b3330aa-9a7c-4b50-b1aa-86f5e57a1905

Still present in v6.2.0

**Comment by ammalagonc** [comment]
![image](https://github.com/user-attachments/assets/e8962bf0-4db4-475a-ab8b-e68490dcfcc4)

Are you using version 6.2? If so, the ability has been renamed to Blessed Armament.

**Comment by ammalagonc** [comment]
You'll need to level your character down to 0 and bring them back to their original level. That should reset the features.

**Comment by bookgrub** [comment]
I will give that a shot and update. We have just moved to v6.2 but had not tried to re-level the character.

**Comment by ammalagonc** [comment]
Before you go down that path, read up on the changes to Champion. A lot has changed for them with Player Core 2.

**Comment by ammalagonc** [comment]
Going to close this issue. If the challenge persists, please reply here and we will take a look.

Thanks.
