### ISSUE TITLE
PC2: Versatile Dragonblood Heritage feats Scaly Hide and Draconic Resistance lack automation

### ISSUE THREAD

**Issue by FarronLS** [foundryvtt/pf2e#15726]
Scaly Hide is supposed to provide an item bonus to unarmored AC that stacks with runes on explorer's clothing, Mystic Armor, or Bands of Force. Currently, the feat doesn't even provide the item bonus and has no Rule Elements interacting with AC.

Draconic Resistance also lacks automation. The feat provides resistance of half your level rounded up based on your draconic exemplar. There is also no option when picking Dragonblood or when selecting the feat to select a draconic exemplar which is required to determine resistances.

**Comment by TikaelSol** [comment]
Consolidating into PC2 issues #15804
