### ISSUE TITLE
PC2: Champions Expand aura effect  for duration tracking.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#15760]
![image](https://github.com/user-attachments/assets/8ca4bedd-8c0f-4160-aee1-16c0a0cab78b)
it would be great if this could have an effect to track the duration of the expanded aura if possible. 

many thanks if this can be done.

**Comment by TikaelSol** [comment]
Consolidating into PC2 issues #15804
