### ISSUE TITLE
PC2: Mighty Rage needs toggle

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#15777]
![ZcFMcRE](https://github.com/user-attachments/assets/421c239c-d32d-4b63-a19e-654e5de636f7)

mighty rage needs a toggle for the first strike.

**Comment by ammalagonc** [comment]
Hey there,

 Please note that this feature has not been automated yet. 
 
 Thanks again,

**Comment by TikaelSol** [comment]
Consolidating into PC2 issues #15804
