### ISSUE TITLE
[Bug} Token image rule element doesn't Work properly with Dynamic Token Rings

### ISSUE THREAD

**Issue by ChasarooniZ** [foundryvtt/pf2e#15789]
From my tests the `Token Image` rule element does the following for dynamic token ring tokens

**Respects these settings** 
- Image path

**Ignores these settubgs**
- Scale
- Opacity
- Tint Color

**Comment by stwlam** [comment]
Not a bug

**Comment by ChasarooniZ** [comment]
Is this rule not intended to also affect Dynamic Token RIngs?
