### ISSUE TITLE
Investigator's strategic strike dice not applying

### ISSUE THREAD

**Issue by supersonicstork** [foundryvtt/pf2e#15787]
When rolling for damage on a strike with devise a stratagem, with all the correct prerequisites, there is no added dice from strategic strike (see attached).

![image](https://github.com/user-attachments/assets/878893b3-d852-4ac1-bd89-841acfdcf398)

I have made sure that:
1) I am on attack stratagem
2) Modules are not the cause (all disabled, on a clean world)
3) Foundry is not the cause (happening across two different installs on two peoples' servers)

**Comment by pedrogrullada** [comment]
Closed by #15711
