### ISSUE TITLE
Discordant Voice shows up as an option to apply to damage. At level 1+.

### ISSUE THREAD

**Issue by Erokusan** [foundryvtt/pf2e#15794]
Whenever a bardic character's Courageous Anthem is active on a character, the option to turn on or off Discordant Voice on damage rolls seems to show up, even at level one. I have not yet tested if this shows up on NPC damage rolls as well, but player damage rolls always have the option regardless of what level the bard is.
To note, the bard does not have Discordant Voice on their feat list.

**Comment by ammalagonc** [comment]
Can't reproduce on my end. 

Please try reproducing the issue without modules enabled. 

Which version of the system are you in atm?

**Comment by Erokusan** [comment]
Foundry version is 12.327, Pathfinder 2e version 6.2.0, I'll start up a world without any modules and see if I can reproduce it

**Comment by Erokusan** [comment]
Alright so on the most recent version of pathfinder, and foundry, which is 330, it comes up with this.
![image](https://github.com/user-attachments/assets/01b5ce2e-d37a-4eeb-bd67-b584db38f725)
Notably the greatsword, when rolling damage, has the option to apply Discordant Voice onto it, but the player characters are level 1.
No modules are on at the current moment.

**Comment by ammalagonc** [comment]
Ah,

I see where the issue is stemming from.

One moment please while we work this one out.

**Comment by ammalagonc** [comment]
Alright, submitted a PR to get this fixed. 

Thanks again for reporting this issue :)
