### ISSUE TITLE
Pathfinder 2 Edition Remastered Player Core 2 Craft Formula List Drag and Sort Bug

### ISSUE THREAD

**Issue by MrSmithClone** [foundryvtt/pf2e#15808]
As the title says the drag and sort for the craft tab known formulas drag and sort function is bugged. It has been bugged since Remastered Player Core 1 update. I don't have any modules installed.

https://github.com/user-attachments/assets/8ac6c2d7-d69e-48b8-be84-d0d72579d258

**Comment by ammalagonc** [comment]
Hello,

Thank you for bringing this to our attention. This issue has been already reported (#15753).

We are closing this one as we will use the first one to track progress.

Thanks again.
