### ISSUE TITLE
Furious Footfalls has unintended interaction with Fleet

### ISSUE THREAD

**Issue by WallMeat** [foundryvtt/pf2e#15801]
Furious Footfalls, when rage is activated, increases the bonus speed gained from the Fleet feat as well as the bonus granted from itself.

The calculation should go, with a basic human barbarian, 25 base speed + 5 (untyped) from fleet + 5 (status) from Furious Footfalls, with an additional +5 (for +10 in total) making the barbarian's land speed 40. However, The rage bonus is interacting with other sources of speed increase, such as fleet and nimble elf, effectively adding a +5 to them as well. Right now, in the system, a 3rd-level nimble elf barbarian with the fleet feat can go 60 feet with one action when raging.

**Comment by ammalagonc** [comment]
Previously reported in https://github.com/foundryvtt/pf2e/issues/15692
Will get fixed in the next release.
