### ISSUE TITLE
herbalist bug

### ISSUE THREAD

**Issue by generallee2121** [foundryvtt/pf2e#15803]
Found a likely bug, when dropping the advanced herbalism feat from the herbalist archetype onto a player sheet with free archetype enabled the feat is placed as a class feat instead of an archetype feat.

Additionally the Herbalist dedication itself seems to be giving the wrong amount of advanced alchemy reagents that are scaling with level.

**Comment by ammalagonc** [comment]
Hello,

Someone beat you to this - https://github.com/foundryvtt/pf2e/issues/15793
Should be fixed in the next release - https://github.com/foundryvtt/pf2e/pull/15795

Thanks,
