### ISSUE TITLE
Kingmaker: Lickweed Passive

### ISSUE THREAD

**Issue by Crowguard** [foundryvtt/pf2e#15809]
The compendium actor for Lickweed includes the passive ability `+1 Status vs. Posion` (typo included). The stat block for this does not include this passive on either Archives of Nethys or Demiplane (I don't have the PDF or book to check there unfortunately).

PF2 6.2.0

**Comment by ammalagonc** [comment]
Hello,

I checked the Kingmaker's Companion Guide and Demiplane,  indeed this actor does have a +1 status bonus vs poison.

![image](https://github.com/user-attachments/assets/8255efd0-f04d-4d70-817e-899e35d7bb19)
![image](https://github.com/user-attachments/assets/b1542f80-bb43-4926-907e-c8ce31cbf7f3)

It appears AoN is the outlier here. 

I'll be closing this issue. If you can report this to AoN, that would be great.

Thank you!

**Comment by Crowguard** [comment]
Will do. Not sure how I missed that on Demiplane. Thank you.

**Comment by ammalagonc** [comment]
No need - I'm reopening the request and pushed a PR to fix the typo,
