### ISSUE TITLE
[Feature Request] Add RulerPF2e to CONFIG.PF2E

### ISSUE THREAD

**Issue by 7H3LaughingMan** [foundryvtt/pf2e#15838]
Would it be possible to add the `RulerPF2e` class to `CONFIG.PF2E`. Right now the only way to access the class itself is via `CONFIG.Canvas.rulerClass` but that is only if there are no module conflicts. You could add it under `CONFIG.PF2E.Canvas.rulerClass` which is similiar to how it's done for `CONFIG.PF2E.JournalEntry.sheetClass`.

**Comment by stwlam** [comment]
It's available at load. Grab it!

**Comment by 7H3LaughingMan** [comment]
> It's available at load. Grab it!

What is available at load? `RulerPF2e` isn't available in the global scope.

**Comment by CarlosFdez** [comment]
What are you trying to solve specifically? It looks like you're trying to get around something in particular. Some other module misbehaving?
