### ISSUE TITLE
Specific Companion Barding do not have Barding Stats

### ISSUE THREAD

**Issue by Steven-Soult-Jr** [foundryvtt/pf2e#15846]
This isn't too important and can be homebrewed by just copying the description/name to a light barding item, but I wanted to mention it in case someone has the time to update them.

Barding of the Zephyr (Compendium.pf2e.equipment-srd.Item.5yL2D3GPAggadZQN) and Waverider Barding (Compendium.pf2e.equipment-srd.Item.me7GsgRKnqA7vaB5) should have the details/stats of Light Barding (Compendium.pf2e.equipment-srd.Item.5yL2D3GPAggadZQN), since they are light barding with a special effect.

Barding Saddle (Compendium.pf2e.equipment-srd.Item.oqqHMA3eHBwJ2BlB) could have a toggle or effect for Heavy Barding (Compendium.pf2e.equipment-srd.Item.MUtAHJXf22SiVBeH) but that's more intricate.

**Comment by ammalagonc** [comment]
Breaking this down into two parts -

- [ ] Update Barding of the Zephyr and Waverider Barding to armor (#15848)
- [ ] Add effect to Barding Saddle (no PR yet)

**Comment by TikaelSol** [comment]
Go ahead and make Barding Saddle barding too, no need for a toggle for it. People can just unequip it when not using it
