### ISSUE TITLE
Godless healing replaced by Robust health

### ISSUE THREAD

**Issue by uniwars** [foundryvtt/pf2e#15873]
Hi, I would like to know if it's an error or something coming from Paizo but Godless Healing has been replaced by Robust health.

They have different names, one is a medic skill feat and the other a general feat and they don't do the same things so if I'm following what Paizo said Godless Healing should still be legal.

**Comment by ammalagonc** [comment]
I have to double check but I believe it's a name change.

**Comment by TikaelSol** [comment]
The name changed but the mechanics are near identical. People can grab godless healing from the legacy module if they still want it.
