### ISSUE TITLE
ItemAlteration RE - Unable To Override Strength Requirement —

### ISSUE THREAD

**Issue by 7H3LaughingMan** [foundryvtt/pf2e#15871]
If an item's strength requirement is set to null like Explorer's Clothing you are unable to override the strength requirement using the ItemAlteration Rule Element. I can understand not being able to add/subtract to a null value, but you should at least be able to override it.

https://github.com/foundryvtt/pf2e/blob/8a404f752ea493e4313b0595860b2c3f6ffbce5e/src/module/rules/rule-element/item-alteration/alteration.ts#L360

```
{
    "itemType": "armor",
    "key": "ItemAlteration",
    "mode": "override",
    "predicate": [
        "item:equipped"
    ],
    "property": "strength",
    "value": "3"
}
```

**Comment by stwlam** [comment]
Published use case?

**Comment by stwlam** [comment]
AE-likes are blind shotgun fire. The very purpose of item alterations is to bring some sanity to the process (otherwise I would have just made AE-likes usable with item data).
