### ISSUE TITLE
Bucklers don't have an option that lets them appear in the Shield section of the Character Sheet (and engage with automation accordingly) without being Gripped.

### ISSUE THREAD

**Issue by Payden-Pringle** [foundryvtt/pf2e#15903]
Rules text: https://2e.aonprd.com/Shields.aspx?ID=1
> You can Raise a Shield with your buckler as long as you have that hand free or are holding a light object that’s not a weapon in that hand.

This means you can always Raise a Buckler even when you aren't Gripping it, unless your hand is occupied by something else as defined above. And so long as it's strapped to your arm.

However, the way the foundry game system is configured, you _must_ grip the Buckler to have it be acknowledged in the Shield section. This is incorrect for how the game system works, because the Buckler doesn't occupy your hand while you can Raise it, unless you are also actively gripping it (for example, to Shield Bash, since that requires 1 hand to use as an attack).

What I recommend is having a separate setting for Buckler to be acknowledged in the Shield section of the character sheet. Something like "Strapped" that doesn't occupy your hand and doesn't give you the Shield Bash Attack for it, but does have it show correctly in the Shield section.

Without this, you can't use the Buckler without setting it to Gripped, when in truth, that may not be what's actually happening.
I guess you could just Grip 3 things and not worry about it, but this seems unnecessarily confusing to have to work around.

**Comment by stwlam** [comment]
One must still wield a buckler to raise it.

**Comment by Payden-Pringle** [comment]
The Buckler should not use a hand to be accessible for Raising & Shield Blocking.

As here: #15788, the system treats the hand as occupied, when it is not necessarily occupied.

If this won't be fixed, then I'll just work around it, but this interaction has degraded any interest I had in helping this system improve.

**Comment by Payden-Pringle** [comment]
I appreciate that.

For what it's worth, and in hopes it helps, the text is here:
https://app.demiplane.com/nexus/pathfinder2e/items/buckler-rm

> You can Raise a Shield with your buckler as long as you have that hand free or are holding a light object that’s not a weapon in that hand.

If a Buckler uses a hand to be accessible for Raising & Shield Blocking, then this sentence does nothing and is superfluous.
