### ISSUE TITLE
Token Image Rule Element: Update for subject texture option in V12 Tokens

### ISSUE THREAD

**Issue by Zatorg** [foundryvtt/pf2e#15904]
The token image selected by Token Image Rule Element token gets replaced by the Subject Texture. A option to replace this instead would be great.

**Comment by TangledLion** [comment]
Seconded. The token image rule element is fantastic and essential. The possibility of not being able to use it on Dynamic Tokens saddens me

**Comment by Khunkurisu** [comment]
To be clear a workaround for this is to leave Subject Texture blank and use the Token Image field instead even with dynamic rings, as the dynamic ring will use the Token Image as the Subject Texture when Subject Texture is blank. Thus allowing you to still use Rule Elements to set the Token Image of dynamic rings.
