### ISSUE TITLE
Allow purchasing items directly into party stash

### ISSUE THREAD

**Issue by basedpatches** [foundryvtt/pf2e#15917]
We're currently unable to use the 'Buy Item' button when adding items to the stash in a party sheet. It doesn't recognize the selected party token as valid and prompts the error, "Select at least one token." The 'Take Item' button does work, however, but does not deduct currency.

In the first image, I successfully take Chain Mail from the compendium. In the second, I fail to buy Chain Mail. I'm the Gamemaster in this world.

![partystash_take](https://github.com/user-attachments/assets/9cf38911-e9ec-4a50-a40e-46bd0aa067b6)

![partystash_buy](https://github.com/user-attachments/assets/a9bf39b5-0a35-4686-827a-9af8aabe845c)

**Comment by stwlam** [comment]
See #15984
