### ISSUE TITLE
Kineticist Single Gate 2 Action Elemental Blast not getting con mod or impulse junction at level 1

### ISSUE THREAD

**Issue by mgoldstein322** [foundryvtt/pf2e#15998]
Hello, one of players is playing as a single gate fire kineticist, and we noticed today that switching to two actions on elemental blast does not change the damage to d8s and does not add the CON modifier. I have disabled all modules and completely rebuilt the character, and the issue persists. Just to make sure, I've reread the class entry and the 2-action version of EB does qualify for this impulse junction. The status bonus is unrelated to that junction, but I imagine there's just something wrong with a rule element somewhere.

Other information about the character is Awakened Animal Ancestry, Running Animal Heritage, Magical Experiment Background (thoughtsense).

Foundry 12.330 and PF2e 6.2.1

**Comment by stwlam** [comment]
Pathmuncher?

**Comment by TikaelSol** [comment]
Working fine for me
![image](https://github.com/user-attachments/assets/dc080dfe-395a-4646-8531-45183cdefec4)

If this actor was initially imported with Pathmuncher you will want to make a new actor entirely and build from scratch without Pathmuncher. Also, double check that your player actually has two actions set for the blast

![image](https://github.com/user-attachments/assets/dc0981ae-cb11-4b3b-b762-f8a4b92e25f8)

**Comment by mgoldstein322** [comment]
Yeah I think she did use Pathmuncher initially. When I remade the character from scratch on a new actor instead of a duplicate, it worked fine. Thanks for telling me this and giving me another reason to tell them I'm uninstalling Pathmuncher lol.
