### ISSUE TITLE
Homebrew Languages Issue

### ISSUE THREAD

**Issue by Jolias055** [foundryvtt/pf2e#15992]
Hello, I was testing some language options with a friend who was GMing and it worked for me, whereas it did not work for him.
Here is a screenshot for when it worked for me.
![image](https://github.com/user-attachments/assets/658fe418-addc-498a-94b2-7dafcca6a2c8)

Then I realised our foundry versions differed, with him having updated to the latest version (6.2.1). After updating I was unable to get homebrew languages to work either. Which means this is something that happened with the newest version. I do not recall what version mine was, but it was only a few behind, 6.1.X.

Here is what I found: It is impossible to add new homebrew languages. The "bubbles" of homebrew languages that were visible at the top of the menu, where you could remove the language disappeared (meaning I cannot remove old homebrewed languages,).
Screenshot of latest version, missing the bubbles at the top.
![image](https://github.com/user-attachments/assets/a9d38c65-84d1-476e-8fe8-0a4a0e1405d0)

If I try to add a new language, it doesn't stay in the top bar as it did previously, and it directly appears in the "Common Languages" tab. The previously added languages disappear from the tab also. When I try typing in an additional language, it replaces the previous one I put in.
Screenshots of this in action. (obviously missing the new languages from before, Vistani and Xinese)
![image](https://github.com/user-attachments/assets/1bda2476-5cd4-4475-ba42-08367f80bd19)
![image](https://github.com/user-attachments/assets/6c5eca1d-9ed2-4449-9ee1-cccc227f745f)

Additionally, after I press save changes, the new language doesn't actually get added, and the languages revert to their previous state.
Screenshot after "Saving Changes" (with neither of the new languages).
![image](https://github.com/user-attachments/assets/b93190b9-d62d-4508-96b1-e25420d870e8)

Pls fix.
Thank you very much.

**Comment by TMunsie** [comment]
Closed by #19563
