### ISSUE TITLE
Add automatic note to strikes targeting allies under effect of Shields of the Spirit, as a reminder to roll the spirit damage.

### ISSUE THREAD

**Issue by MoritzGr** [foundryvtt/pf2e#16007]
Hello,

Shields of the spirits says the following:

> While one of your allies is in your champion's aura, the shields grant them a +1 status bonus to AC, and each time an enemy makes an attack against the ally, the enemy takes 1d4 spirit damage (even if it misses).

I suggest adding a reminder for this spirit damage to attacks that target allies under the effect of Shields of the Spirit.
This can be achieved by adding the following ephemeral effect rule element to the shields of the spirit spell effect:

```
{
  "key": "EphemeralEffect",
  "affects": "origin",
  "selectors": [
    "attack-roll",
    "skill-check"
  ],
  "uuid": ">UUID OF NOTE EFFECT GOES HERE<",
  "alterations": [
    {
      "mode": "override",
      "property": "badge-value",
      "value": "@item.origin.level"
    }
  ],
  "predicate": [
    {
      "not": "self:signature:{item|origin.signature}"
    }
  ]
}
```

where the uuid field contains the uuid of an effect with an enabled badge and the following not rule element:
```

{
  "key": "Note",
  "title": "Spirit Shield Damage Reminder",
  "text": "While one of your allies is in your champion's aura, the shields grant them a +1 status bonus to AC, and each time an enemy makes an attack against the ally, the enemy takes @Damage[(ceil({item|badge.value}/4))d4[spirit]] (even if it misses).",
  "selector": [
    "attack-roll",
    "skill-check"
  ],
  "predicate": [
    "attack"
  ]
}
```

this results in a nice clickable and scaling damage roll that saves everyone involved a lot of navigation through the spell tab.

![image](https://github.com/user-attachments/assets/25ce1187-2c68-4a47-9d33-e0bf88e2819d)

**Comment by MoritzGr** [comment]
Very fair points, I'll still keep using this Jacky version in my personal game because the amount of times it'll come in handy will be way more than the amount where IWR isn't correct. 

I guess just a note without the damage roll could work for the main branch, because honestly just remembering it is half the battle

**Comment by ammalagonc** [comment]
Close to consolidate
