### ISSUE TITLE
Sticky Bomb Feat requires additional predicate

### ISSUE THREAD

**Issue by maplealmond** [foundryvtt/pf2e#16019]
A Sticky Bomb's persistent damage is upgraded if the bomber has the feat calculated splash.  This part is correct.

A Sticky Bomb's persistent damage is not upgraded if a Remaster Bomber gets the calculated splash effect via their field discovery.  I believe this is because the predicate for sticky bomb is specifically "feat:calculated-splash" when it should now also include a reference to "field-discovery-bomber".  The RE below does not contain the reference.

```
{"key":"AdjustModifier","mode":"upgrade","predicate":["feat:calculated-splash"],"selector":"alchemical-bomb-base-type-damage","slug":"sticky-bomb","value":"@actor.abilities.int.mod"}
```

(Until fix - This can be worked around by granting the Alchemist Calculated Splash as bonus feat)

**Comment by ammalagonc** [comment]
Thanks again for reporting this. 

I will move this over to the PC Issues tracking. I'll close this issue and monitor progress on that end.
