### ISSUE TITLE
Kineticist Taking Gate's Threshold (Expand the Portal) not displaying options 

### ISSUE THREAD

**Issue by Everspace** [foundryvtt/pf2e#16020]
- Go from Level 4 to 5
- Select Expand the Portal
- Choose Water
- Choose Skill
- Get a display that I have "No Valid options for Gate's Threshold"

I have 
- Lv1 Earth gate with Armor in Earth
- Lv1 Water Gate with Deflecting Wave
- Lv1 Weapon Infusion
- Lv2 Winter's Clutch
- Lv4 Safe Elements

I wanted or expected to see Winter's Clutch as an option to select on gaining level 5

[Actor.json](https://github.com/user-attachments/files/16602346/fvtt-Actor-heshpar-Rb7HMwizcdGSX1oD.json)

**Comment by ammalagonc** [comment]
Hello!

Quick question- did you import your character using Pathbuilder?

**Comment by Everspace** [comment]
No I did not

**Comment by TikaelSol** [comment]
Something in the actor isn't set right. Go to level 0 then back up and it should fix it.

**Comment by Everspace** [comment]
@TikaelSol thanks, that did fix it.
