### ISSUE TITLE
Changing the grid fit setting in Stable 7 does not prompt a session reload

### ISSUE THREAD

**Issue by silvative** [foundryvtt/pf2e#16036]
I know this version literally isn't out yet, let alone supported, but I figured I'd write an issue up for it just to get it on the radar, since it's a little obscure.

Tested in Foundry VTT stable version 7 (public release to come later this week), with the system version 6.2.1
(Issue confirmed as not present in d&d 5e version 3.3.1)

**Replication steps:** 

- Change the ring fit mode
- Save changes

![image](https://github.com/user-attachments/assets/b5bdf8b9-0c48-4126-bbc1-d3678e49549f)

**Expected behaviour:** 

Foundry VTT will prompt for a reload after saving the change

**Reported behaviour:**

Instead the window stays open without any apparent effect, and the app has to be manually refreshed (eg F5) to apply the change properly

There is also a fairly cryptic console error:

![image](https://github.com/user-attachments/assets/16878afa-bdbd-4644-a1c8-a18facc5b3aa)

**Comment by Zullock** [comment]
Just tried it and for me it works as intended, prompting a reload.
