### ISSUE TITLE
Sentinel does not grant heavy armor proficiency

### ISSUE THREAD

**Issue by Arachnofiend** [foundryvtt/pf2e#16038]
Simple as the title; if you already have proficiency in medium armor Sentinel is intended to give proficiency in heavy armor, but as it stands it does not. It works the other way around (taking Sentinel first and then the Armor Proficiency general feat for heavy armor) but obviously the scaling for that is based on the general feat.

**Comment by ammalagonc** [comment]
Hello!

This was already reported and should be fixed in the next release.

Thank you!
