### ISSUE TITLE
Barbarian Armor Mastery feat at 19 gives mastery in heavy armor

### ISSUE THREAD

**Issue by LJSmith066** [foundryvtt/pf2e#16053]
Armor Mastery description reads "Your proficiency ranks for light, medium, and heavy armor..." and gives mastery in heavy armor, rather than only unarmored, light and medium

**Comment by jesuisfrog** [comment]
Yeah I think PC2 has the wrong feature name, it should be Medium Armor Mastery, Armor Mastery is the feature that give light/medium/heavy and barbarian has been added to that one. I'll fix it real quick.
