### ISSUE TITLE
Magus Arcane Cascade Variable Not Working

### ISSUE THREAD

**Issue by lago508** [foundryvtt/pf2e#16068]
The Arcane Cascade Stance has an ActiveEffect-Like to allow other effects to reference the damage type the Arcane Cascade effect is set to. It stores the damage type in flags.pf2e.arcaneCascade.damageType.

However, Compendium.pf2e.classfeatures.Item.09iL38CZZEa0q0Mt (the Arcane Cascade class feature) has its own ActiveEffect-Like that sets flags.pf2e.arcaneCascade.damageType to "", which the system inteprets as 0. This blocks the Arcane Cascade Stance effect from writing the player's chosen damage type to it.

![image](https://github.com/user-attachments/assets/ec1005ff-1e2f-4220-8d44-6fec6c7c0b5e)

Changing "" to "none" resolves the problem. Deleting the ActiveEffect-Like in the Arcane Cascade class feature entirely also seemed to work.

Steps to reproduce: Create a Magus player character, put them in Arcane Cascade stance, open the Arcane Cascade Stance effect to edit it, go into Rules and scroll down, the ActiveEffect-Like will be showing an error message and flags.pf2e.arcaneCascade.damageType will have a value of 0 when it should be a damage type.

Then apply the Arcane Cascade Stance effect to any non-magus actor, and it won't have the same "cannot override 0" error.

**Comment by ammalagonc** [comment]
Hello, 

I tested the out the feature and it's working as intended.

![image](https://github.com/user-attachments/assets/45095904-96a9-4f04-86a8-a17a1c5e6e52)

Other than the RE firing that warning message, can you provide more details as to how the feature/itself is not working?

**Comment by xyzzy42** [comment]
The problem is with the *actor* flag the AELike RE on the stance Effect creates.  The *item* flag is fine.  The Effect uses the item flag in the flat modifier RE for the extra damage.  So that part works fine as we see in your screenshot.  But as soon as something else tries to get the damage type from the actor flag, it fails.

Here's the status of the flag on the actor, which as the stance effect that should be setting this to `cold`:
![image](https://github.com/user-attachments/assets/759c5fe1-ac68-46ba-8cef-911b4107774a)

Notice how the value has changed from the string `""` to the number 0.  That prevents the AELike being able to override it to the correct damage type.

If the default from the class feature is changed to something not coercible to a number, then it works as expected:
![image](https://github.com/user-attachments/assets/dee3a949-c88c-4f7f-a3c5-b3b7aef5ecaa)

The bug here is either that the AELike is coercing the empty string into a numeric 0, or if that is the desired behavior, that the class feature AELike provides a default value that can be coerced.

**Comment by lago508** [comment]
Example time:

So I've made a magic weapon that adds 1d6 damage of the same type of the user's Arcane Cascade.
It uses this rules element.

*Rules Element for Custom Magic Weapon*
```
{
  "damageType": "{actor|flags.pf2e.arcaneCascade.damageType}",
  "diceNumber": 1,
  "dieSize": "d6",
  "key": "DamageDice",
  "predicate": [
    "self:effect:arcane-cascade"
  ],
  "selector": "strike-damage"
}
```

This works by referencing an ActiveEffect-Like in Effect: Arcane Cascade Stance. This ActiveEffect-Like has no actual bearing on Arcane Cascade Stance itself's function, it seems to just be there for other effects (such as this magic weapon) to be able to refer to its assigned damage type. I can't actually think of any in the core game, so whoever set it up this way was very considerate! (whoever you are, thank you!)

*from Effect: Arcane Cascade Stance*
```
{
  "key": "ActiveEffectLike",
  "mode": "override",
  "path": "flags.pf2e.arcaneCascade.damageType",
  "value": "{item|flags.pf2e.rulesSelections.stanceArcaneCascade}"
}
```

And it works! Stick this one a weapon, stick Effect: Arcane Cascade Stance on an actor, and it'll correctly inherit the damage type from whatever you set Arcane Cascade to!

![image](https://github.com/user-attachments/assets/264896b0-0182-4138-a3ae-707b3a45e043)

_Unleeess__ the actor in question is an actual Magus. Then it breaks.

 The problem is the Arcane Cascade class feature. 
 
![image](https://github.com/user-attachments/assets/00bcdd71-27e1-4b22-af39-cb06c8747281)
*from Arcane Cascade Stance class feature*
```
 {
  "key": "ActiveEffectLike",
  "mode": "override",
  "path": "flags.pf2e.arcaneCascade.damageType",
  "priority": -100,
  "value": ""
}
```

This has its own ActiveEffectLike that sets flags.pf2e.arcaneCascade.damageType to "". The problem is the system is interpreting this as 0, making the variable an incompatible data type and thus blocking Effect: Arcane Cascade Stance from assigning the damage type to it.

![image](https://github.com/user-attachments/assets/4d3f7dc8-4c73-4915-b753-390e8ae13482)

And because it can't save the damage type in the stance, the magic weapon then can't reference it and stops working.

![image](https://github.com/user-attachments/assets/feaf5cad-3834-47c2-b686-8e67e35eeb6b)
![image](https://github.com/user-attachments/assets/41bfebfc-ab20-42a7-80df-0148784de4f6)

The fix we found was to change the assignment in Arcane Cascade class feature from "" to "none", which stores the variable as the right data type and allows Effect: Arcane Cascade Stance to save damage types correctly. Removing the ActiveEffect-Like from the Arcane Cascade Stance class feature _entirely_ also works, I discovered the problem in the first place because actors without that class feature were working properly.

*Fixed Arcane Cascade Stance class feature!*
```
{
  "key": "ActiveEffectLike",
  "mode": "override",
  "path": "flags.pf2e.arcaneCascade.damageType",
  "priority": -100,
  "value": "none"
}
```

Let me know if you need more clarification!
