### ISSUE TITLE
Wrong Armor Category for Chain Shirt Base Group 

### ISSUE THREAD

**Issue by AlexBlankComposer** [foundryvtt/pf2e#16076]
A chain shirt belongs to the light armor category. https://2e.aonprd.com/Armor.aspx?ID=43 
However, as of v6.2.1, the item is classified as medium armor.

To Reproduce: have a character with light armor training and without Medium Armor training equip a Chain Shirt

Expected Behavior: No penalty is applied.

Actual Behavior: Untrained armor penalty is applied

**Comment by stwlam** [comment]
What does it say on the item sheet?

**Comment by TikaelSol** [comment]
What do you mean untrained armor penalty?
![image](https://github.com/user-attachments/assets/d2dba2a5-2c8c-4c80-b499-ecad2caf8ba0)

If you mean the check penalty that isn't related to trained or untrained, it's about whether you meet the armor strength requirement

**Comment by AlexBlankComposer** [comment]
I apologize--I'd failed to notice that my player had added an armored skirt without reading/understanding that it increases the category of light armor to medium. Apologies again!
