### ISSUE TITLE
Occular Warning Initiative effect does not correctly reference origin

### ISSUE THREAD

**Issue by websterguy** [foundryvtt/pf2e#16072]
Occular Warning effect for oracle links an effect that grants temp hp according to origin's level. This same effect grants a secondary effect that has a flat mod to initiative based on the origin's cursebound condition value. The issue is that when the temp hp effect grants the initiative effect, the origin for the initiative effect becomes the actor that has the effects (because granted by the temp hp effect) rather than the original Oracle.

I'm thinking either:
 - the temp hp effect could set an actor flag storing the oracle's cursebound value or
 - the initiative effect could be given a badge and granted with an alteration to set the badge value equal to the cursebound value

**Comment by pedrogrullada** [comment]
This is already fixed by #15993
