### ISSUE TITLE
PF2e Treat Wounds Macro always rolls risky surgery damage, even if not selected

### ISSUE THREAD

**Issue by maplealmond** [foundryvtt/pf2e#16086]
The PF2e Treat Wounds Macro ```game.pf2e.actions.treatWounds({ event, actors: [token?.actor ?? actor ?? game.user.character].filter((actor) => actor) })```

If used by an actor who has the risky surgery feat, this macro will always roll 1d8 damage, even if the actor has not checked the risky surgery option.

**Comment by ammalagonc** [comment]
Hello, will be tracking this issue via https://github.com/foundryvtt/pf2e/issues/15855. Please use it to track any progress towards this.

I'll close this issue now. Thanks!

**Comment by stwlam** [comment]
Keeping this as an independent issue
