### ISSUE TITLE
Obsidian Edge item on the compedium is wrongly imputed

### ISSUE THREAD

**Issue by Paolot-Git** [foundryvtt/pf2e#16082]
It shouldn't have the kickback trait, the range of the ranged should be 30ft and be a d10 for damage.

**Comment by ammalagonc** [comment]
Hello,

Per the item description, the `kickback` comes from the base Gun Sword, which means it inherits it even if it's not in the item.

https://2e.aonprd.com/Weapons.aspx?ID=218

I submitted a correction for the other items though.

**Comment by Paolot-Git** [comment]
Oh yeah, I saw it now. My mistake.
