### ISSUE TITLE
Kineticist Thermal Numbus gives enemies elemental resistance 

### ISSUE THREAD

**Issue by hostlund** [foundryvtt/pf2e#16098]
I was checking if Termal Numbus was automated with damage each turn on enemies but discovered that they enemy got the same resistance I and my allies got. 

Running 6.2.2
Tested with fire at level 4. Everybody in the area got fire resistance 4.

![bild](https://github.com/user-attachments/assets/1cc1d1e9-b821-4405-808f-b186c17e6ee7)

**Comment by ammalagonc** [comment]
Greetings,

Please note that Aura AE-likes work by using the party disposition. If you add the Kineticist to the Party Folder, the effect should only apply to allies as demonstrated below:

![image](https://github.com/user-attachments/assets/c4f20528-6c55-45c9-a0bc-d41623b1cd0f)

Let us know if this works.

Thanks!

**Comment by hostlund** [comment]
Yea it works if I put the Kineticist in the party sheet. I will closing this issue. My only complaint would be that how the party disposition works with feats/auras is not that obvious. 

![bild](https://github.com/user-attachments/assets/d3b4eb03-c647-46db-bb22-f3643507c7da)
