### ISSUE TITLE
Add option to auto-convert images (especially scene maps) to webp

### ISSUE THREAD

**Issue by ThiefMaster** [foundryvtt/pf2e#16104]
Some DMs create huge maps for their scenes which is of course great for details and zooming in, but not so great for those who are not lucky enough to have a gigabit internet connection at home.

The WEBP format is excellent at compression images without a visible loss in quality (even without lossless mode). For example, I was able to 11176x8128 PNG file (which is an actual map someone uses in their campaign) from 122 MB down to 9.3 MB (or 70 MB lossless). 

The only drawback is that converting huge images takes its time - on a few-year-old NUC with a i5-8259U CPU it took 35s for lossy and 1 min for lossless encoding of that image mentioned above. So it would almost certainly require a progress/activity indicator, or possibly client-side encoding (according to a quick search people already compiled cwebp to WASM, I have not looked into its performance though) to avoid putting high load on servers (especially shared ones hosting multiple Foundry instances)

**Comment by ammalagonc** [comment]
Hello,

This would be a core Foundry request. 

Please submit this request here - https://github.com/foundryvtt/foundryvtt/issues.

Thanks!

**Comment by ThiefMaster** [comment]
oops, that's where I intended to open this issue. not sure how I ended up in the pf2e repo... can you transfer it to that repo (if you have the necessary privileges)? otherwise I'll just reopen it over there

**Comment by ammalagonc** [comment]
I don't have those privileges :|

Probably for the best :P

**Comment by ThiefMaster** [comment]
Added it as a comment to this issue which is related: https://github.com/foundryvtt/foundryvtt/issues/4216#issuecomment-2295323792
