### ISSUE TITLE
Feature Request: Add Similar Rules for Armor Groups as for Martial Proficiency

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16128]
Introduce an RE similar to the existing Martial Proficiency (or modify that RE) that allows characters to gain training in specific armor groups. For instance, a character could become an expert with armors in the Plate group.

Currently, Pathfinder 2e does not have mechanics specifically designed to handle proficiency in armor groups. Implementing this feature would be valuable for homebrew content, enabling the creation of feats or abilities that grant proficiency in an entire group of armors. Additionally, it could provide bonuses for repairing or crafting armors within that group.

A feat that grants proficiency in a specific armor group (e.g., Plate) and bonuses to repairing or crafting armors in that group.
Homebrew content where characters can specialize in certain types of armor, mirroring the existing system for weapon groups.

While it's possible to simulate this effect through existing rules, it would be beneficial to have a dedicated mechanism similar to what exists for weapon groups.

**Comment by stwlam** [comment]
Use the MartialProficiency RE

**Comment by CrackJackFlood** [comment]
> Use the MartialProficiency RE

You can use the Martialproficiency RE for armor groups?
