### ISSUE TITLE
Properly Implement Bulk Calculations for Different Sized Characters and Items

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16124]
Up until "Howl of the Wild," keeping Bulk calculations the same as Medium size worked in most cases. However, with the introduction of permanent Large player characters, it's necessary to implement more accurate rules for Bulk based on character size.

Todo:
Implement Small Item Options:

Items should have a small-sized option for when they are carried by small creatures or for simulating a small item or creature being carried by a larger creature.
Reference: [bulk of creatures](https://2e.aonprd.com/Rules.aspx?ID=2158).
Update Bulk Calculations for Different Sized Characters:

The system currently only partially implements the "Items of Different Sizes" table. This needs to be updated so that Bulk is properly calculated for player characters of all sizes.
Proposed Bulk calculations:
Large Characters: 10 Bulk + (Strength Modifier * 2)
Tiny Characters: 2 Bulk + floor(Strength Modifier / 2)
Huge Characters: 20 Bulk + (Strength Modifier * 4)
Reference: [Items of Different Sizes Rule](https://2e.aonprd.com/Rules.aspx?ID=2163).
Enhance Automation for Item Size Adjustments:

Currently, items only change their size and value when added to a different-sized creature. This automation should be enhanced to correctly adjust the item's Bulk according to the character's size.

**Comment by stwlam** [comment]
Already done

**Comment by CrackJackFlood** [comment]
> Already done

What does this mean exactly, I am on 6.2.3 currently and none of this has been done. Done as in its coming the next update?
