### ISSUE TITLE
Creating token via macro that has compendium art mapping results in incorrectly sized token

### ISSUE THREAD

**Issue by 7H3LaughingMan** [foundryvtt/pf2e#16132]
If you use the below macro to import an actor from the Monster Core compendium pack it results in a token that is incorrectly sized compared to importing the actor from the Bestiary Browser.

```
const actor = await fromUuid("Compendium.pf2e.pathfinder-monster-core.Actor.Xo4IGzw28hivgMmM");
const imported = await Actor.create(actor);
const token = await imported.getTokenDocument();
canvas.scene.createEmbeddedDocuments("Token", [token]);
```

The one on the left was created with the above macro, while the one on the right was created from the Bestiary Browser.

![image](https://github.com/user-attachments/assets/29dd7f86-4328-45c8-9094-b104354fc8c6)

**Comment by stwlam** [comment]
Have you tried not passing documents to create methods?

**Comment by 7H3LaughingMan** [comment]
> Have you tried not passing documents to create methods?

I am not sure what you mean, it's retrieving the Zombie Shambler from the compendium pack and creating an actor using that document. If I don't do that then it's not going to have the compendium art mapping.

**Comment by 7H3LaughingMan** [comment]
I figured out what the issues was, it's using `Actor` instead of `ActorPF2e` to create the actor. Switching over to `Actor.implementation.create` fixed the issue.

```
const actor = await fromUuid("Compendium.pf2e.pathfinder-monster-core.Actor.Xo4IGzw28hivgMmM");
const imported = await Actor.implementation.create(actor);
const token = await imported.getTokenDocument();
canvas.scene.createEmbeddedDocuments("Token", [token]);
```
