### ISSUE TITLE
Effects seem to not be working properly.

### ISSUE THREAD

**Issue by AgentMajestic** [foundryvtt/pf2e#16136]
Was playing in a game recently and found out the Bestial Mutagen effect link is not working properly. I have the attack bonus and such including the negatives to the saves, but my attacks for the claws and jaws seem to no longer exist

**Comment by ammalagonc** [comment]
Hello,

Thanks for letting us know. This issue has been reported (#16090). A fix should be deployed in the next release.

Thank you!
