### ISSUE TITLE
Missing Texture Mappings for Monster Core

### ISSUE THREAD

**Issue by Arnatious** [foundryvtt/pf2e#16157]
# Info
Foundry Virtual Tabletop: Version 12 Stable, 12.331
Game System: pf2e, 6.2.2
Token Packs: Bestiary Tokens 1.20

Textures are missing/blank for (some? all?) Monster Core monsters without the Monster Core token set, causing errors in the compendium browser.

![image](https://github.com/user-attachments/assets/1529def8-3d4b-4e1c-866a-056b61a0508e)

And on opening the npc sheet
![image](https://github.com/user-attachments/assets/5cae567d-7a1d-441c-bf1b-bf874efa8a33)

Per websterguy on discord - it looks like the mappings were left blank in the module:

![image](https://github.com/user-attachments/assets/77e71152-d3e2-489d-b826-d4797d39874c)

**Comment by TikaelSol** [comment]
This is not related to the PF2e system
