### ISSUE TITLE
Dancing Lady showing wrong level 

### ISSUE THREAD

**Issue by liquidgabs** [foundryvtt/pf2e#16158]
The creature Dancing Lady from Kingmaker is showing as level 6, while on nethys and demiplane its listed as level 8.
![image](https://github.com/user-attachments/assets/db5e0b2d-27ae-4286-9907-6b514ab9b332)

![image](https://github.com/user-attachments/assets/9a9ee083-64ad-491f-89c2-cd1232d8f448)

**Comment by TikaelSol** [comment]
As a note, we never use AoN or demiplane as a reference for the system. The PDF is the source we turn to. But, in this case she is 8 in the PDF.

**Comment by liquidgabs** [comment]
Got it, I'm just a player, so can't check the pdf, but will keep in mind if something like that happens again.
