### ISSUE TITLE
Actor Sheet causing tokens to break.

### ISSUE THREAD

**Issue by ACartaya96** [foundryvtt/pf2e#16170]
Bug
Foundry Version: 12.331
Pathfinder Version: 6.2.3
All Mods disabled

For the past week I've been debugging trying to find the cause of this issue :
- Token ctrl + drag stops working
- Targeting on a token with the 'T' Key stops working
- Deleting a token is not possible when this bug occurs

You can recreate the bug by putting a token in the scene opening up their actor sheet and rolling any check from the sheet this will cause one, if not all three problems to occur.

I don't know if it's just a personal issue, but I wanted to report it in case it wasn't.

**Comment by stwlam** [comment]
Not able to reproduce, sorry. Are there errors in the console with all modules disabled?

**Comment by cwebster2** [comment]
What browser do you use?  Just tried that with Firefox 129.0.1/Linux with the same versions of Foundry and the pf2e system and could not reproduce.

**Comment by ACartaya96** [comment]
Hi go ahead and close this for now I went back to do more testing, and now this is no longer reproducing and the bug isn't showing up anymore so most likely this was a me thing.
