### ISSUE TITLE
Feature Request: Additional exceptions for IWR

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16184]
Could ranged and melee exceptions be added, they do not exist in rules but their are execeptions; for area, persisent and spell damage, weapons and unarmed/nonlethal attacks. 

Splash could be another not sure if that comes under area.

Weapons is too broad.

**Comment by stwlam** [comment]
Use custom entries

**Comment by CrackJackFlood** [comment]
> Use custom entries

What does that mean exactly?

**Comment by pedrogrullada** [comment]
> > Use custom entries
> 
> What does that mean exactly?

https://github.com/foundryvtt/pf2e/wiki/Quickstart-guide-for-rule-elements#immunity-weakness-resistance
