### ISSUE TITLE
9.6.3 - Versatile Vials missing item bonus(es) to attack

### ISSUE THREAD

**Issue by aremedis** [foundryvtt/pf2e#16201]
At levels 4,12, 18 in addition to damage die number increasing there should also be a +1, +2, +3 item bonus to attack rolls.

 Probably a better way to do this, but this is what I've come up with:
 
 `{
        "key": "FlatModifier",
        "value": {
          "brackets": [
            {
              "end": 3,
              "value": 0
            },
            {
              "start": 4,
              "end": 11,
              "value": 1
            },
            {
              "start": 12,
              "end": 17,
              "value": 2
            },
            {
              "start": 18,
              "value": 3
            }
          ],
          "field": "actor|level"
        },
        "selector": "attack",
        "type": "item"
      },`

**Comment by pedrogrullada** [comment]
The bonuses exist and are in the Versatile Vials class feature for now. The rule elements can't be in the item itself because there is no way for the vials to reference back to who crafted them, and thus giving an accurate bonus (for example, if differently leveled allies are using them).

Once the system has come out with its implementation of Crafting, these features will be looked at again.

**Comment by nikolaj-a** [comment]
Aren't the stats based on the level of the versatile vial? They follow the normal lesser, moderate, greater, and major tiers.

**Comment by pedrogrullada** [comment]
> Aren't the stats based on the level of the versatile vial? They follow the normal lesser, moderate, greater, and major tiers.
I was told to implement them as a single item. Presumably there is a plan to handle it once we have proper system implementation.

**Comment by ammalagonc** [comment]
I'll reference this to the PC2 Alchemist changes tracking and consolidate.
#15647

**Comment by ammalagonc** [comment]
Closing this issue - tracking via #15647
