### ISSUE TITLE
Dawnsilver is currently not bypassing Devil's Physical resistance. 

### ISSUE THREAD

**Issue by Unikatze** [foundryvtt/pf2e#16206]
The description for Dawnsilver in GM Core page 253 states: Dawnsilver is renowned for its lightness, durability, and effectiveness against a range of creatures **including devils** and werecreatures. It has the same sheen as silver but a slightly lighter hue. Dawnsilver weapons and armor are treated as if they were silver for the purpose of damaging creatures with weakness to silver.

While this doesn't specify it also works as silver to bypass Physical resistance, the fact it's mentioning devils in the description, and that no devils have weakness to Silver, I believe it is RAI that Dawnsilver should bypass this resistance just as silver does. 

Thank you.

**Comment by stwlam** [comment]
Gonna have to write a letter to Dr. Paizo, sorry.
