### ISSUE TITLE
Critical Immunity not working (Pyronite Ooze)

### ISSUE THREAD

**Issue by Albireookami** [foundryvtt/pf2e#16229]
Players were fighting Pyronite Ooze and it was not automating the critical immunity.     The other immunities were applied properly.

**Comment by Albireookami** [comment]
![image](https://github.com/user-attachments/assets/5af22e11-f358-462e-a20a-5d7a1bcdc7dd)
![image](https://github.com/user-attachments/assets/2a947cf1-a90d-4e6a-85dc-b5471477302e)

**Comment by racehd** [comment]
I recreated this on V12.331 and pf2e 6.2.3 with no mods enabled. With slime moold and gray ooze
