### ISSUE TITLE
Dread Marshal Dedication and Stance not updated with Player Core 2

### ISSUE THREAD

**Issue by Minethulhu** [foundryvtt/pf2e#16248]
The feats for Dread Marshal Dedication and Dread Marshal Stance are still using the entries from the Advanced Player's Guide.  The newer entries from the Player Core 2 appears to be a larger default size aura for the dedication, but no additional effect on a critical success for the stance.

FoundryVTT 12.331
PF2E 6.2.3

**Comment by websterguy** [comment]
The system has the larger size aura already. If your Marshal Dedication aura is still 10 feet, you need to get the new version from the compendium. Dread Marshal is similarly updated already.

![image](https://github.com/user-attachments/assets/764e21c6-2e38-454e-9bb0-28732514e542)
