### ISSUE TITLE
Not all spellcasting messages get `context.type = 'spell-cast'`

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#16261]
Not sure if that is intentional, but not every spell cast message has the `"flags.pf2e.context.type": "spell-cast"` flag. 
Instead, it is only spells that have some sort of `Defense`, whether AC or Saving Throw. Anything else has the `context` completely omitted, even if it has Damage Rolls or other properties.

**Comment by stwlam** [comment]
That is a check context.
