### ISSUE TITLE
Integrate saving throws into targeted abilities similar to spells

### ISSUE THREAD

**Issue by Raileth** [foundryvtt/pf2e#16274]
At present when an area effect spell is cast targeted entries have a save button in the chat allowing saves to be easily made and applied to each target: 
![image](https://github.com/user-attachments/assets/390cd4f7-1d24-406e-a76b-3c3130ca8dec)

However for abilities and items such as the kineticist Hail of splinters the damage and saves are not linked. as a result the saves have to be rolled seperately and then scrolled back to apply damage:

![image](https://github.com/user-attachments/assets/d1fe4362-5198-4b04-a583-316181018582)

The same is true for items / abilities where both damage and saves are described in the description. Isi it possible to link the saves to the targets?

**Comment by CarlosFdez** [comment]
The feature you are describing is a module feature, and is not provided by the core system. You'll have to ask the module dev to find some way to link them, but there isn't actually a way for them to do it.

When we implement linking in any capacity, this will be solved at a similar time.
