### ISSUE TITLE
FR: Pythagarus measurement options for flying and 3d movement/ 3d templates

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#16273]
what would be really useful would be to have the ruler to measure pyhtagrus measurements when flying at 45 degrees upwards. or a way to calculate the distance of going up or down in squares when using 3d measurements.

**Comment by stwlam** [comment]
The system doesn't use Pythagorean calculations anywhere, and there are no plans to do so.
