### ISSUE TITLE
Treat Wounds Macro - Medic, and Robust Health circumstance bonuses are stacking

### ISSUE THREAD

**Issue by git-kor-av** [foundryvtt/pf2e#16287]
The Medic Archetype provides the following circumstance bonus to healing received by the target(s) of it's treat wounds:

> When you succeed with Battle Medicine or Treat Wounds, the target gains a circumstance bonus to the number of Hit Points they regain equal to 5 HP at DC 20, 10 HP at DC 30, or 15 HP at DC 40.

The Robust Health General feat provides a similar bonus:

> Your physiology responds well to first aid. You gain a circumstance bonus to the number of Hit Points you regain equal to your level from a successful attempt to Treat your Wounds or use Battle Medicine on you.

The problem is when you roll the systems treat wounds macro, it applies an untyped bonus for healing directly on the roll, therefore when the healing is applied to a target with Robust Health there is an incorrect stacking of the circumstance bonus:
![robust-health-medic-bonuses-stacking](https://github.com/user-attachments/assets/36b3e06d-cbb7-4922-93d5-d5544968287a)

**Comment by TikaelSol** [comment]
Covered by #15855 already. The entire macro needs redone
