### ISSUE TITLE
Image in chat shown when tokens are hidden

### ISSUE THREAD

**Issue by farling42** [foundryvtt/pf2e#16297]
Starting a combat, all tokens are hidden.
Add tokens to initiative.
Roll initiative for all NPC tokens.
Images are shown for each of the dice rolls - even though the players shouldn't know what is present yet.

For any "blind GM roll", the image is giving metagaming clues to the players.

![image](https://github.com/user-attachments/assets/4f188beb-5f3d-4fdb-80a9-8a80e8a95b30)

**Comment by CarlosFdez** [comment]
Closed by https://github.com/foundryvtt/pf2e/pull/16317
