### ISSUE TITLE
Dedications missing link to Archetype Journal Entries

### ISSUE THREAD

**Issue by nythz** [foundryvtt/pf2e#16301]
The following archetypes dedications do not have a link to their archetype entry in the Archetype Journal :

- [x] Scion of Domora
- [x] Verudan Shadow
- [x] Red Mantis Assassin
- [x] Ghost
- [x] Stalwart Defender

- [x] Archer
- [x] Martial Artist
- [x] Medic

- [x] Cultivator
- [x] Fan Dancer
- [x] Spirit Warrior
- [x] Starlit Sentinel
- [x] Wandering Chef
- [x] Familiar Sage
- [x] Five-Breath Vanguard

The Following Archetypes do not have entries in the Archetypes Journal :

- [x] Stone Brawler
- [x] Stonebound

- [x] Shieldmarshal

- [x] Clawdancer
- [ ] Ostilli Host
- [ ] Swarmkeeper
- [ ] Thlipit Contestant
- [ ] Werecreature
- [ ] Wild mimic
- [ ] Winged Warrior

**Comment by simonward** [comment]
Added links to existing journal entries via https://github.com/foundryvtt/pf2e/pull/16305
