### ISSUE TITLE
Red Mantis Assassin journal entry typo

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#16304]
![image](https://github.com/user-attachments/assets/29bc8790-6388-4609-9ae8-c56302f807ae)

"He Who" should be "[He Who Walks In Blood](https://2e.aonprd.com/Deities.aspx?ID=29)"

**Comment by simonward** [comment]
It looks like this is Paizo's error in Prey for Death.
<img width="341" alt="Screen Shot 2024-08-29 at 10 01 30 AM" src="https://github.com/user-attachments/assets/01a88d51-ef88-40ac-b9ea-7c78bdbf2fd3">
