### ISSUE TITLE
Celestial Strikes missing damage according to the Errata issued.

### ISSUE THREAD

**Issue by Raizeki** [foundryvtt/pf2e#16309]
The remaster compatibility for using old aasimar feats with the Nephelin states: 

> As with any legacy material, players may need to work with their GM to determine appropriate rulings, such as swapping references to good or evil damage **with spirit damage with holy or unholy sanctification.**

![image-152](https://github.com/user-attachments/assets/939f9e60-ef46-4743-aefc-f08a25344faa)

So, following this statment, the old celestial strikes would give you 1 extra spirit damage and holy sanctification to your strikes, but the feat in foundry currently only gives the sanctification. 

I think it would be good to add the 1 extra damage back. Its a small bonus but is one that was specifically writen in the errata how it would work, and removing in in a arbitrary manner feels... Odd. 

This is specially true when you compare to the new reprinted quietus strikes from the duskwalker that still gives +1 extra damage.

**Comment by TikaelSol** [comment]
The guidance we got directly from Paizo is that instances of 1 alignment damage was there only to trigger weaknesses, and that is how we implemented this. If people want to add 1 spirit damage to the feat they can easily do so with a rule element (FlatModifier with a selector of `strike-damage`).
