### ISSUE TITLE
[Bug] Incorrect Class feat (Alertness) for Magus at level 3

### ISSUE THREAD

**Issue by Kronos25** [foundryvtt/pf2e#16321]
Steps to reproduce:
1 - Create a new character
2 - Choose Magus class
3 - Level up to lvl 3

You'll get Alertness as a class feature - this class feature is a level 9 magus feature, not a level 3.
![image](https://github.com/user-attachments/assets/962301ff-07c6-48e2-80a2-46bd5e8009d2)

![image](https://github.com/user-attachments/assets/63f0ab61-0eb5-4d43-8ada-a71b2d64f422)

**Comment by TikaelSol** [comment]
Class feature grants are fixed as of 6.3.1
