### ISSUE TITLE
Missing link in Module description to documentation on using Rule Elements etc

### ISSUE THREAD

**Issue by Terrox** [foundryvtt/pf2e#16333]
Would be good if there was links to documentation on how to get started customising things from the module description on foundry website and the repo main description - it's where I go first, then discord, then find there's a wiki link hidden in the VTT general tab but it took a while to work that out. 

Wiki link should be in the Module description.

Would recommend embedding the wiki nav menu into the first [wiki home](https://github.com/foundryvtt/pf2e/wiki) page too - it took me a while to realise the "[Quickstart guide for rule elements](https://github.com/foundryvtt/pf2e/wiki/Quickstart-guide-for-rule-elements)" page existed because the wiki home only lists a few links.

**Comment by TikaelSol** [comment]
We link to the wiki itself, and aren't going to reproduce the entire pages sidebar in the main document. The two links we did have already were likely leftover from a much earlier effort to organize the wiki.
