### ISSUE TITLE
ChoiceSet allowedDrops does not seem to be functioning

### ISSUE THREAD

**Issue by websterguy** [foundryvtt/pf2e#16339]
When testing allowedDrops, when I drop something into the Homebrew slot and click it, I get the error/warning "No selection was made: <effectname> is inactive." The GrantItem rule is then set to ignored on the added item.

**Comment by CarlosFdez** [comment]
For the purposes of testing, what were you testing with allowedDrops that failed?

**Comment by websterguy** [comment]
Well, I tested quite a few things.
I test Pitborn, which wouldn't even let me drop anything. It has the following predicate on its allowed drops:
```json
[
  "item:feat-type:skill",
  "item:level:1",
  "item:rarity:common"
]
```
But anything I dropped there I was given the error `<Feat Name> cannot be dropped here (must be 1st level Athletics skill feat)` even when trying to drop things like Quick Jump and Underwater Marauder.

So then I import Pitborn and remove the predicate from the `allowedDrops`. No matter what I drop there and select, `No selection was made: Pitborn is inactive.` This is what I get with any ChoiceSet I make.

**Comment by CarlosFdez** [comment]
This is a data error. item:feat-type:skill isn't a valid roll option.

**Comment by websterguy** [comment]
Supe, it won't apply a choice made even when the feat dropped is allowed. I have allowed drops with no restrictions. The feat goes in the box and I click the feat. I get the message that it was ignored.

**Comment by CarlosFdez** [comment]
This was actually the reason I asked for a test case, as I have to be able to reproduce it (I didn't not write this dialog, nor the recent updates involving allowed drops). The test case illustrated showed a completely different error than the one you wanted me to actually investigate, and thus led me to the wrong conclusion.

**Comment by websterguy** [comment]
Yes, sorry. I did specify that I made other tests without that predicate.
