### ISSUE TITLE
Default Display Name setting not honored when placing token from Actor List

### ISSUE THREAD

**Issue by xiitone** [foundryvtt/pf2e#16342]
When I drop a token on a map directly from the Bestiary Browser, the Display Name value I set up in core settings works just fine. If I instead drop an NPC from the Bestiary Browser into the actor list, and then drag from there onto a map, it sets the Display Name to "Never Displayed"
Furthermore, for actor that gets auto-created when I drop an NPC on a map-any future copies of that one that I drop on the map from the actor list have the correct Display Name
This is the behavoir when browsing the compedium directly or through the Compendia Browser.
Summary:
Bestiary->Map = follows default Display Name from setting
Actor List entry from above->Map = follows default Display Name from setting
Bestiary->Actor List->Map = sets Display Name to "Never Displayed"

**Comment by stwlam** [comment]
This would be a core issue.
