### ISSUE TITLE
Concussive trait seems to no longer be working

### ISSUE THREAD

**Issue by Olrar** [foundryvtt/pf2e#16351]
Guns with the concussive trait should bypass piercing resistance if bludgeoning is lower.  This is currently not happening.

**Foundry Version**: 12.331 (v12 Stable 7)
**Pf2e Version**: 6.3.1
**Steps taken**:
- Running on Foundry with no other modules active
- Blank PC with Jezail targetting Skeletal Hulk
- Deal damage with Jezail
- Skeletal Hulk takes reduced damage due to Piercing Resistance

**Expected outcome**: Skeletal Hulk has no resistance to bludgeoning so should be taking full damage

![image](https://github.com/user-attachments/assets/f4c6eec2-63ef-44f5-a918-657dd32d3e37)

**Comment by CrackJackFlood** [comment]
![image](https://github.com/user-attachments/assets/c91882be-0c87-4c64-a44f-46cc465eea12)

Its working for me

**Comment by Olrar** [comment]
@CrackJackFlood From the image that you've shared, the Jezail says it's dealing 1d8 piercing (+1d8 from your homebrew), but the symbol shows that it's dealing bludgeoning damage.
Do you have a module that automatically switches the damage type for concussive?  As far as I'm aware, the damage should still be piercing but just count as bludgeoning for IWR.

**Comment by CrackJackFlood** [comment]
> @CrackJackFlood From the image that you've shared, the Jezail says it's dealing 1d8 piercing (+1d8 from your homebrew), but the symbol shows that it's dealing bludgeoning damage. Do you have a module that automatically switches the damage type for concussive? As far as I'm aware, the damage should still be piercing but just count as bludgeoning for IWR (if less than piercing)

Appologies yeah I have module that switches the damage thought that was part IWR automation. I was able to recreate your behaviour with that module turned off - 
![image](https://github.com/user-attachments/assets/d64244ce-e75a-4d29-890a-2eee8337e3be)
