### ISSUE TITLE
Kineticist Perception Expertise Wrong Level

### ISSUE THREAD

**Issue by Karumac** [foundryvtt/pf2e#16355]
The system is granting Perception Expertise to Kineticist at 3 instead of 9.

**Comment by pedrogrullada** [comment]
Are you up to date? There was a bug in the previous release causing this.

**Comment by ammalagonc** [comment]
Tested on my end - can't replicate
![image](https://github.com/user-attachments/assets/a097c087-152d-4fcb-9fac-5d7a7ba9657a)

As @pedrogrullada mentioned, this bug was squashed in version 6.3.1. 

Please validate when you get a moment.
