### ISSUE TITLE
Missing Feat in the Marshal Archetype Journal

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#16363]
The Jorunal is missing the Devrin´s Cunning Stance Feat from the Firebrands Book

![grafik](https://github.com/user-attachments/assets/732615d3-e373-41c2-b3ca-8878f8d6d018)

**Comment by Vendergast** [comment]
This one was closed but the feat is still missing in the new update? I dont know if it wasnt included in this update or it isnt fixed yet!

**Comment by ammalagonc** [comment]
I see it on my end
![image](https://github.com/user-attachments/assets/0358e814-e9a5-4010-a70e-fa1612b21e9d)

Check your PF2e system version in your game instance/world. The change should've trickled in with this last update.

**Comment by Vendergast** [comment]
Yeah i was just stupid, sry for the trouble!
