### ISSUE TITLE
Athletic Strategist RE is incorrect, bad predicates

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#16405]
Reported on Discord [2 years ago](https://discord.com/channels/880968862240239708/880969253765935174/1042090402913730560) and [1 hour ago](https://discord.com/channels/880968862240239708/880969253765935174/1281241906273325190).

Looks like the predicate needs to only apply for specific athletics actions taken while using a relevant weapon.

**Comment by pedrogrullada** [comment]
I believe there are two things going on here: first, the predicate for Athletic Strategist is trying to use weapon roll options, which are not available when using the Trip action macro, or the athletics skill in general for that matter, so the predicate is never met.

And second, and this part may be a rather recent bug, it looks like the Flat Modifier is suppressing Strength if Intelligence is higher even when the predicate is false.
