### ISSUE TITLE
Multiattack rule element doesn't interact with Target: predicate

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1641]
In GitLab by @lostsanityreturned on Aug 13, 2021, 04:12

When using: 
> PF2E.RuleElement.MultipleAttackPenalty

It does not respect the target element of predicate. e.g. the following does not work
> "predicate": {"all": ["target:flatFooted"]}

**Context:**

It is useful to have target: working here as it makes automating flurry rangers simple via an effect that places a trait on the target. 

There are also homebrew implications with item, spell and feature uses. Where if it worked it allows granting allies lower multi attack penalties with a specific agile weapon vs undead or demonic targets only.

**Comment by TikaelSol** [comment]
Related to #2588, closing this one as the other issue is more detailed.
