### ISSUE TITLE
[Feature Request] Add the ability to disable the new chat portraits feature

### ISSUE THREAD

**Issue by LunarEcklipse** [foundryvtt/pf2e#16423]
There are modules that have wider-ranging chat image support that this new feature conflicts with, and I would like to be able to disable this new feature to continue using these modules.

**Comment by stwlam** [comment]
No plans to accommodate modules with this, sorry.

**Comment by scooper4711** [comment]
@LunarEcklipse  - you can turn off the PF2e chat portrait with this CSS that you can install using the Custom CSS module:

https://github.com/p4535992/foundryvtt-chat-portrait/issues/53#issuecomment-3070376349
