### ISSUE TITLE
Swashbuckler giving additional skill feat

### ISSUE THREAD

**Issue by SoilentBrad** [foundryvtt/pf2e#16442]
![image](https://github.com/user-attachments/assets/83613da6-8da7-40fd-a91a-f2fd8e6bb06a)
Per the class, the swashbuckler gains skill feats at level 2 and every 2 levels thereafter. However, the character sheet has them at 2, 3, 4, 6.

**Comment by pedrogrullada** [comment]
This is due to the Stylish Tricks class feature
![image](https://github.com/user-attachments/assets/9fcf028b-88a5-4d33-9228-a14dffcf5450)
