### ISSUE TITLE
Hymn of Healing

### ISSUE THREAD

**Issue by Neurochimp** [foundryvtt/pf2e#16466]
Hello,

I have a player using this and we've found that when cast it only conveys the effect to the caster. 

We've targeted the intended recipient and the effect still ends up on the caster. I've tried just having the recipient selected as well then casting from the other player off their sheet & it does not convey to the right person. I used Find the Culprit to remove all modules and the targeting behavior was the same.

Thanks!

**Comment by pedrogrullada** [comment]
What do you mean exactly when you say the effect "ends up on the caster"? The system effects are applied via drag and drop from chat cards onto tokens or character sheets. Anything applying the effect in a different way, with very few exceptions which don't include spells, must be a module.

**Comment by Neurochimp** [comment]
Thanks I'll look into the modules then.
