### ISSUE TITLE
The Fall of Plaguestone - Vilree - Old Pre-Remaster Item

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#16474]
The "Monster" Vilree has the old Tanglefoot Item in her Inventory. This schould be replaced with the GlueBomb.

![grafik](https://github.com/user-attachments/assets/6af06135-36d7-4993-8c72-c2f88bd57960)

This includes her Alchemy Ability

![grafik](https://github.com/user-attachments/assets/ae921ad3-8a3e-4da9-a7eb-9c0ca759209e)

**Comment by TMunsie** [comment]
Per direction from Paizo, these characters are OGL content and won’t necessarily be updated. If Paizo chooses to remaster Fall of Plaguestone it will be updated.
