### ISSUE TITLE
Rule element issue with Psychic Frostbite amped

### ISSUE THREAD

**Issue by uniwars** [foundryvtt/pf2e#16476]
Hi, the "The Oscillating Wave" feature has rule elements to amp the Frostbite cantrip but I think the behavior is not intended :

Amp You drain thermal energy at a distance, using what you plunder to replenish yourself. The orb deals 3d4 cold damage. You gain temporary Hit Points equal to half the damage the target takes (after applying resistances and the like). You lose any remaining temporary Hit Points after 1 minute.

The temporary hit points are added for everything that deals damage to the target, even other allies and I think it should only work from damage coming from the orb.

**Comment by TikaelSol** [comment]
We don't have any way to handle half damage temp HP application, so I am not sure what you mean.

**Comment by TikaelSol** [comment]
Gonna say this is a module issue
