### ISSUE TITLE
Vatumledor stat block: incorrect traits and damage on Mental Blast

### ISSUE THREAD

**Issue by silversiren1101** [foundryvtt/pf2e#16480]
Vatumledor (Prey for Death) is an ancient conspirator dragon, but his Mental Blast attack is incorrect compared to the generic ancient conspirator dragon statblock.

It should have the "mental" trait added, and the damage type should be mental, not bludgeoning.

**Correct Statblock**
![image](https://github.com/user-attachments/assets/13972bc8-b883-4166-8fb7-85b3f6624238)

**Vatumledor's Current Statblock**
![image](https://github.com/user-attachments/assets/87a5d9ed-fdf3-4bc3-9fd5-909a2f591569)

**Comment by ammalagonc** [comment]
I checked the actor -
When in humanoid form, the Conspirator Dragon's attacks all switch to bludgeoning, including the Mental Blast.
