### ISSUE TITLE
Spore Shephard's staff major wrong level & price

### ISSUE THREAD

**Issue by rectulo** [foundryvtt/pf2e#16595]
The level and price of the major version of the spoare equal to the staff of the normal version. 
The staff is in Sky King's Tomb Mantle of gold.

Nethys give me the answer. 

![image](https://github.com/user-attachments/assets/ca972d1a-9e5f-4466-9b33-c337af30b996)

I'm suggesting :
- either to add a note in the description too
- or to fix the level & Price of the item (12  ~1900 gp)

**Comment by TMunsie** [comment]
We will contact Paizo for errata but, at present, this is what is printed in the primary source so it is *technically* correct though obviously an error.

**Comment by TikaelSol** [comment]
Closing as a purely Paizo issue
