### ISSUE TITLE
Bug: Dragging a condition onto an actor stacks it rather than replacing it

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#16612]
To reproduce:  drag Frightened 1 onto a creature, and then drag Frightened 2 onto the creature.  You will see the creature end at Frightened 3.

The PF2E rules say that whenever an actor gains a new condition with a different number, only the hihgest number should remain -- rather than combining them.  So, we should expect the creature to be Frightened 2, here.

**Comment by stwlam** [comment]
Not a bug. This isn't a question of rules but of UI. The _rules_ say nothing about what happens when you drag a condition item onto an actor in Foundry.

**Comment by shemetz** [comment]
Sure, then call it a feature request.  But wouldn't it be an improvement if this was changed?

If a user actually wants to increase the existing condition, they can always click the condition icon in the top right while having the actor selected (or change it in its Effects tab).  I find it quite unlikely that they'd want to add two numbers together (due to the rules usually preventing a need for this).

Common scenario:
1. Player 1 successfully demoralizes an enemy, GM drags Frightened 1 onto the enemy, enemy becomes Frightened 1.
2. Player 2 then gets a crit-success on the demoralize, so the GM drags Frightened 2 onto the enemy.
3. The enemy suddenly becomes Frightened 3 -- and if no one notices the brief scrolling text that appears at that point, this can affect outcomes of rolls, the mistake may linger for a while.
