### ISSUE TITLE
Data entry feature request:  add embedded damage to Wildfire

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#16613]
![image](https://github.com/user-attachments/assets/a7aeff1a-7a81-4002-b6a8-b77057f9bfc9)

Wildfire is a spell that frequently deals damage and long after the first cast, since it applies whenever somebody walks over the hazardous terrain.  But right now there is no embedded button to take the 1 fire damage (per square);  only an embedded button for the persistent damage.  There *is* the spell damage itself, but that's a bit less easy to reach, in my opinion.

I suggest replacing the "1 fire damage" text with a `@Damage` embed that calculates 1 fire damage plus 1 per [heighten+2].

**Comment by pedrogrullada** [comment]
Is there a reason I'm missing why the damage on the spell itself won't work?
![image](https://github.com/user-attachments/assets/cabb907d-7652-46e7-8e7b-da2b5469b749)
