### ISSUE TITLE
Request : Adding option to select default character actor permission for all player

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1663]
In GitLab by @Uniwars68 on Aug 26, 2021, 08:30

Hi !
The system recently changed the default permission for all players on character actor to "Limited" instead of "None"
Having the option in the system setting to selectec between "None", "Limited" or even "Owner" would be really nice, changing back to none is jsut some clicks, but mutiplied by a huge number of new character actors it starts to count more. We have a living campaign with multiple GM and more then 50 active PC actors (without counting animal companionn, etc) and some of the GM use character actor to create their boss, if they forgot to change the permission all players will see the boss name and portrait, wich can spoil the quest.

I have no idea if adding the option to select the default permission would take time to dev it, just letting you know that it would be appreciated by some users.

Thanks for your work on the system :)

**Comment by stwlam** [comment]
This is more appropriate as an upstream feature request.
