### ISSUE TITLE
Bug: Goblin's Burn It! feat applies persistent damage to impulses

### ISSUE THREAD

**Issue by Jakub-L** [foundryvtt/pf2e#16669]
## Summary
The Goblins' ancestry Burn It! feat adds a "_+1 status bonus to any persistent fire damage you deal_". However, this bonus persistent damage is added to a fire gate kineticist's fire blast, where it shouldn't. Since the blast doesn't deal persistent damage, it shouldn't get a bonus.

## Replication
1. Create a new actor, give it the Goblin ancestry
2. Select the Kineticist class and choose single fire gate (feat selection doesn't matter)
3. Add the Goblin ancestry Burn It! feat
4. The damage for the Elemental Blast is now 1d6 fire + 1 persistent fire, where it should be 1d6 fire.

## Notes
I have checked whether this bonus also applies to:
- A fighter's longsword attack (it doesn't)
- A water-gate kineticist's blast (it doesn't)
- A fire/metal dual-gate kineticist's metal blast (it does)

I expect this is some weird interaction with the fire gate?

**Comment by pedrogrullada** [comment]
From my testing, it looks like this is a more general issue where typed bonuses to persistent damage are being added to disabled instances of persistent damage (such as the Fire Gate's Critical Blast)
