### ISSUE TITLE
Monk Powerful Fist being suppressed when both hands are occupied, or with a buckler

### ISSUE THREAD

**Issue by doctor-duus** [foundryvtt/pf2e#16688]
When a Monk has a weapon in one hand, and is wearing a buckler on the other, the Powerful Fist attack is suppressed. I don't think this is correct. Two reasons:

1. I believe (?) that Powerful Fist is not literally just the Fist, it is any unarmed attack, so should apply to, for example, kicks, and
2. The Buckler should not occupy the hand that is making a Fist regardless.

Same with the use of a Free-hand weapon in the second hand. It seems it should still allow Powerful Fist. It does not.

**Comment by stwlam** [comment]
See the [CounterFAQ entry](https://github.com/foundryvtt/pf2e/wiki/The-CounterFAQ#why-do-some-pc-sheets-show-separate-fist-and-unarmed-attack-entries-are-these-not-the-same)

**Comment by doctor-duus** [comment]
Hello. What about a buckler not taking up the fist? That seems like a separate issue.

**Comment by stwlam** [comment]
Baseline non-magical equipment doesn't show usage, but from specific magic bucklers we know they are in fact held in one hand despite strapping-to-forearm language:
https://2e.aonprd.com/Equipment.aspx?ID=734
https://2e.aonprd.com/Equipment.aspx?ID=1239
https://2e.aonprd.com/Equipment.aspx?ID=2825

**Comment by stwlam** [comment]
See also the rules from Player Core:
> All shields, unless specifically noted or described otherwise, must be strapped to your arm and held in one hand, so you can’t hold anything with that hand and Raise a Shield, and you lose the shield’s benefits if that hand is no longer free. A buckler, however, doesn’t take up your hand, so you can Raise a Shield with a buckler if the hand is free (or, at the GM’s discretion, if it’s holding a simple, lightweight object that’s not a weapon).

**Comment by doctor-duus** [comment]
The magic item description agrees with you, but I feel like this does not:

>  A buckler, however, doesn’t take up your hand, so you can Raise a Shield with a buckler if the hand is free (or, at the GM’s discretion, if it’s holding a simple, lightweight object that’s not a weapon).

If the hand is free, I can use it to make a fist attack. Right?

Anyway, it definitely seems more muddied than I thought it was. Thanks.

**Comment by stwlam** [comment]
The rules here are certainly not as clean as they could be (some might even say they are borderline nonsense in places: using Raise a Shield if the hand is free is equally applicable to both bucklers and non-buckler shields). From "though a fist or other grasping appendage generally works like a free-hand weapon," we treat a fist in that way.
