### ISSUE TITLE
@Check inlines not using predicated DC modifiers

### ISSUE THREAD

**Issue by artisauce** [foundryvtt/pf2e#16697]
When I use Bon Mot against a creature that has, say, the Greater Effect of Serene Mutagen, it works correctly, as it seems to use its own macro. However, for @Check, it does not seem to modify the DC if the effect that would give, say, a bonus to the DC based on the traits.

A test case would be Scare To Death's inline Check against Effect: Mental Balm. Mental Balm should increase the DC by 2, but it does not apply.

**Comment by TikaelSol** [comment]
The issue lies with serene mutagen's effects, which are set up wrong and using legacy rules anyways.

**Comment by artisauce** [comment]
It applies to more than just Serene Mutagen. When using the macro in Demoralize, it seems to account for applicable traits if they are listed not as "item:trait:fear" or "item:trait:emotion", but as "emotion" and "fear" in the predicate effect. If the target has Mental Balm, it applies to neither:
![image](https://github.com/user-attachments/assets/c80f301e-07d5-4673-8e6d-91ecd32f0077)
However, when I set the predicate of Mental Balm to "emotion", it seems to only affect Demoralize, which should keep in mind the DC change, but it doesn't affect the inline check of Scare to Death:
![image](https://github.com/user-attachments/assets/29718ac9-1c87-4104-9100-046b9ac6f841)
