### ISSUE TITLE
DamageAlteration RE not working as expected {bug?}

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16714]
@weapon.system.damage.dice oes not resolve additional damage dice added by the RE. Deadly trait works though.

**Comment by stwlam** [comment]
The rule element doesn't have access to this information.

**Comment by CrackJackFlood** [comment]
> The rule element doesn't have access to this information

If DamageAlteration is a way of modifying base damage dice so making a 1d8 into 2d8 etc How is it expected to work for RE's that rely on @weapon.system.damage.dice.

Logically @weapon.system.damage.dice should resolve an items damage dice *correctly* when its effected by DamageAlteration.



Can you possibly suggest workarounds for this if its not going to be fixed as its frustrating as its only half working as expected (deadly trait works for example) like for example gravity weapon and thaumaturges implements both go off bonus damage equal to the number of weapon dice
