### ISSUE TITLE
ItemAlteration removing other traits.

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16730]
When you remove a trait with ItemAlteration it removes another trait like unarmed.

**Comment by jesuisfrog** [comment]
I have just tested an ItemAlteration and could not reproduce this problem. Can you share what you did exactly? 

For example, I've tested removing a specific trait on an equipped weapon and it worked as intended, it did not remove other traits and the trait was added back when unequipping the weapon.

`{
  "key": "ItemAlteration",
  "itemType": "weapon",
  "mode": "remove",
  "predicate": [
    "item:equipped"
  ],
  "property": "traits",
  "value": "acid"
}`

**Comment by CrackJackFlood** [comment]
@jesuisfrog try `{"key":"ItemAlteration","property":"traits","mode":"remove","itemType":"weapon","value":"magical","predicate":["item:equipped"]}`

**Comment by CrackJackFlood** [comment]
> I have just tested an ItemAlteration and could not reproduce this problem. Can you share what you did exactly?
> 
> For example, I've tested removing a specific trait on an equipped weapon and it worked as intended, it did not remove other traits and the trait was added back when unequipping the weapon.
> 
> `{ "key": "ItemAlteration", "itemType": "weapon", "mode": "remove", "predicate": [ "item:equipped" ], "property": "traits", "value": "acid" }`

I tried with your RE same result its removing Unarmed from items
![image](https://github.com/user-attachments/assets/c457ea92-52b2-400e-b688-c5089a630537)

**Comment by jesuisfrog** [comment]
This bug is peculiar, after testing some more it seems that all the items meeting the prerequisite will get a singular trait removed, whether or not they have a trait that matches the RE. 

If a trait matches the RE, then that trait is removed as intended, if not, another trait (seemingly random but nothing is) is removed instead. 

I had not caught it because I was testing on one specific item and removing a trait that existed on the item.

This will need to be tagged as a bug.

**Comment by CarlosFdez** [comment]
A fix is up, though magical is not removed if it exists. I assume something adds it back in afterwards. This issue isn't about that, but I figured I"d give a heads up.

**Comment by CrackJackFlood** [comment]
> A fix is up, though magical is not removed if it exists (I tested using the example REs). I assume something adds it back in afterwards. This issue isn't about that, but I figured I"d give a heads up.

I think its the potency rune? In my testing at least or something else is adding magical after its removed.
