### ISSUE TITLE
Spell Effect: Enlarge (Heightened 4th) doesn't grant clumsy to the actor

### ISSUE THREAD

**Issue by digitalshadowhawk** [foundryvtt/pf2e#16737]
Despite saying in the description text that this effect makes the target clumsy 1, it does not actually grant the status effect like the regular Spell Effect Enlarge, instead opting to grant a -1 status bonus to Dex. While this accomplishes the same thing, I'm just not sure about the inconsistency.

**Comment by pedrogrullada** [comment]
Use the regular Enlarge effect. As long as it's dragged from a 4th rank or higher enlarge, it will behave correctly. That old effect you're referring to should be redirected to the new one and deleted.
