### ISSUE TITLE
IWR not respecting traits.

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16731]
Traits like fire or void are not triggering IWR.

**Comment by CrackJackFlood** [comment]
![image](https://github.com/user-attachments/assets/476d9714-3b79-4be6-99e9-26e1627c7d0b)

**Comment by stwlam** [comment]
> However, some complex effects might have parts that affect you even if you're immune to one of the effect's traits; for instance, a spell that deals both fire and acid damage can still deal acid damage to you even if you're immune to fire.
