### ISSUE TITLE
ItemAlteration property "defence-passive" will not override null - {Functionality Request}

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16745]
Title, so if item has "passive": null, ItemAlteration will not override it. I guess thats because its looking for "passive": {"statistic": "something"}.

Logically it should change the null to a proper value but I guess technically thats not override that would be add I guess.

**Comment by stwlam** [comment]
A spell lacking a passive defense isn't already an attack spell. That particular item alteration isn't intended to make that a change of that magnitude.
