### ISSUE TITLE
[Feature Request] Choiceset Random option.

### ISSUE THREAD

**Issue by CrackJackFlood** [foundryvtt/pf2e#16848]
Title, running season of ghosts I modified the disguises effect to be a choiceset so I could switch to other NPC images, would be cool if choiceset RE could just pick a random option. Wildcard options would also be pretty cool on various token manipulation RE's like name and image,

**Comment by pedrogrullada** [comment]
You could accomplish this by adding a formula to your effect and predicating each TokenImage rule element on a badge value.
