### ISSUE TITLE
Issue with Prepared Spellcasting in a Compendium

### ISSUE THREAD

**Issue by NasirTheWitcher** [foundryvtt/pf2e#16897]
Attempting to prepare a spell in a slot from the spell perparation menu for an NPC sheet in a compendium returns the following error:

Uncaught (in promise) Error: fromUuidSync was invoked on UUID 'Compendium.world.<name-of-world>.Actor.Z6LC36oE1G4y5ogX.Item.SIMLcPlfdx3uaXi5' which references an Embedded Document and cannot be retrieved synchronously.

Error does not occur when the Actor is in the game world, and this issue is not encountered for spontaneous spellcasters.

**Comment by ammalagonc** [comment]
Can you provide screenshots?
Can't reproduce the error on my end, unfortunately.

**Comment by NasirTheWitcher** [comment]
This was taken by another member of the discord server.
![image](https://github.com/user-attachments/assets/2313379f-f32b-4633-9a0c-fb63ef44b475)

This is the screenshot of my system.
![image](https://github.com/user-attachments/assets/0dd397c2-eff7-4ec2-a848-3e2e34be6905)

Apparently Prepared Spells for Actors in the Compendium can't be updated this way, the way the code is now. The actor has to be moved into the world and then the spells can be added.

**Comment by NasirTheWitcher** [comment]
This was taken by another member of the discord server.
![image](https://github.com/user-attachments/assets/2313379f-f32b-4633-9a0c-fb63ef44b475)

This is the screenshot of my system.
![image](https://github.com/user-attachments/assets/1fdc3dd8-dfbd-4e4c-a69c-5b33838e40eb)


Apparently Prepared Spells for Actors in the Compendium can't be updated this way, the way the code is now. The actor has to be moved into the world and then the spells can be added.

**Comment by ammalagonc** [comment]
OK, I was able to reproduce on my end.
