### ISSUE TITLE
Striker aimed should work on Agile Melee but does not

### ISSUE THREAD

**Issue by TheGnome1** [foundryvtt/pf2e#16904]
A striker operative should get the bonus damage (and ignoring one on cover) when using AIM action for AGILE MELEE weapons this does not appear to be the case (at least for the shooting starknife have not tested other weapons yet)

**Comment by ammalagonc** [comment]
This is for the SF2e Operative, right?
If so
You might want to submit the issue here - https://github.com/TikaelSol/starfinder-field-test/issues

**Comment by TheGnome1** [comment]
dagnabit... CLOSING
