### ISSUE TITLE
Leshy's Solar Rejuvenation healing and description errors

### ISSUE THREAD

**Issue by Intervencion** [foundryvtt/pf2e#16916]
a) The current healing formulae returns 0 as actor.con.mod seems to be an invalid "shortcut" (#16917)

b) The Rule Element isn't properly overwriting the description based on the ancestry.

**Comment by simonward** [comment]
I cannot reproduce the 2nd issue.
<img width="496" alt="Screen Shot 2024-10-17 at 11 22 14 AM" src="https://github.com/user-attachments/assets/78affba8-4a88-4366-aa9a-ef15da003401">
<img width="498" alt="Screen Shot 2024-10-17 at 11 22 28 AM" src="https://github.com/user-attachments/assets/61c4795f-2a42-4ddd-9b64-a2c4be9f9206">

**Comment by Intervencion** [comment]
Ah- I see the issue
I was looking at the feat with the "edit item" 
![image](https://github.com/user-attachments/assets/1a07853f-a910-4975-b814-0054f86dcae8)

I guess this is working as intended then? Cheers
