### ISSUE TITLE
Issue with Gourd Leshy - receiving bonus to perception/initiative? 

### ISSUE THREAD

**Issue by phroureo** [foundryvtt/pf2e#16969]
![image](https://github.com/user-attachments/assets/b57e5766-808a-4172-b214-3456ddcad6aa)

There's something weird going on with Gourd Leshy. We can't figure out why the level 2 character is being granted a +4. As far as I can find, there's nothing on AoN called "Gourd Head" at all, let alone anything that would give a Gourd Leshy a +4 to initiative rolls.

**Comment by ammalagonc** [comment]
Which compendium did you import the actor from?

**Comment by phroureo** [comment]
Sorry - found the issue. There's a toggle on the character sheet that is just "+4 to perception DC" without any further details. Not necessarily an issue, per se, but could perhaps do with a bit of clarification on what, exactly, the bonus applies to. 

The "Gourd Head" comes from the Gourd Leshy heritage, in particular, but I think that it could be worded a bit more clearly within foundry.
