### ISSUE TITLE
Adjust Damage: Allow for dice inputs.

### ISSUE THREAD

**Issue by Payden-Pringle** [foundryvtt/pf2e#16967]
It'd be cool if, when using Adjust Damage (Hold Shift & Click Damage), we could type in dice like 1d6 to have it roll that and adjust by the value provided. Same for Healing.

**Comment by stwlam** [comment]
that is a core feature that can be enabled: https://foundryvtt.com/article/dice-advanced/#fulilled

**Comment by Payden-Pringle** [comment]
Hi @stwlam , I don't understand.

You've linked Fulfilled, which is talking about determining how dice are rolled in terms of RNG Methodology.
What does that have to do with this?

![image](https://github.com/user-attachments/assets/cdc9e586-66f1-45a6-9d02-70e68f6970e7)

**Comment by stwlam** [comment]
I see. The intent of that dialog is simply to make corrections when automation doesn't handle it. For adding dice, you'll want to use rule elements: https://github.com/foundryvtt/pf2e/wiki/Quickstart-guide-for-rule-elements#damage-dice

**Comment by Payden-Pringle** [comment]
My understanding is that the purpose, or point, of the Adjust <thing> Modal is to correct a value that is incorrect.
Which it will usually be incorrect due to a mistake or other error.

What you've recommended instead is a feature (Rules Elements) that can only be used with forethought, which usually would've avoided the mistake to begin with.

Which is just saying "Don't make a mistake.", which isn't helpful.

My point is that it doesn't solve the problem I was trying to solve via this request.
That being, having to roll the adjustment separately, then typing it in manually in the modal.

Given that the concept of Adjust <thing> is to make it quicker/easier to correct for these issues in-play, I thought this feature request was appropriate to ask for. I guess, that too, was an error.

**Comment by stwlam** [comment]
I understand the request, and there's nothing wrong with the desire for such a feature. In this case, it's not something we're going to be investing time in. A module like [Workbench](https://github.com/xdy/xdy-pf2e-workbench) or [Toolbelt](https://github.com/reonZ/pf2e-toolbelt) might be interested in taking it up. Sorry for the disappointing answer.
