### ISSUE TITLE
Spell: Grim Tendrils missing persistent damage

### ISSUE THREAD

**Issue by TroelsL** [foundryvtt/pf2e#16976]
In `packs/spells/grim-tendrils.json`:

system.description.value should be changed from

`<p>Tendrils of darkness curl out from your fingertips and race through the air. You deal 2d4 void damage and @Damage[(@item.level)[bleed]] damage to living creatures in the line. Each living creature in the line must attempt a Fortitude save.</p>\n<hr />\n<p><strong>Critical Success</strong> The creature is unaffected.</p>\n<p><strong>Success</strong> The creature takes half the void damage and no persistent bleed damage.</p>\n<p><strong>Failure</strong> The creature takes full damage.</p>\n<p><strong>Critical Failure</strong> The creature takes double void damage and double persistent bleed damage.</p>\n<hr />\n<p><strong>Heightened (+1)</strong> The void damage increases by 2d4, and the persistent bleed damage increases by 1.</p>`

to

`<p>Tendrils of darkness curl out from your fingertips and race through the air. You deal 2d4 void damage and @Damage[(@item.level)[persistent,bleed]] damage to living creatures in the line. Each living creature in the line must attempt a Fortitude save.</p>\n<hr />\n<p><strong>Critical Success</strong> The creature is unaffected.</p>\n<p><strong>Success</strong> The creature takes half the void damage and no persistent bleed damage.</p>\n<p><strong>Failure</strong> The creature takes full damage.</p>\n<p><strong>Critical Failure</strong> The creature takes double void damage and double persistent bleed damage.</p>\n<hr />\n<p><strong>Heightened (+1)</strong> The void damage increases by 2d4, and the persistent bleed damage increases by 1.</p>`

In Player Core p. 334, Grid Tendrils deals 1 persistent bleed damage.

Apologies, I haven't done a MR for this repo before. Let me know if that would be helpful for such a minor change.

**Comment by pedrogrullada** [comment]
Bleed damage is persistent by definition, so it's not necessary to add it to the inline damage roll. Give it a try and roll it, it will be persistent already.
