### ISSUE TITLE
The `frequency-delete` and `delete-effect` buttons in the ability details tab aren't working

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#16987]
![image](https://github.com/user-attachments/assets/45915afb-d353-4f5d-92b6-4fa68259eae1)

It is currently impossible to remove a frequency or a self-effect from an ability as the buttons do nothing.

**Comment by CarlosFdez** [comment]
It appears to be working in feats, but not in abilities. Likely a consequence of abilities turning to data models.

**Comment by reonZ** [comment]
I should have tested for feats, i typed it by reflex.
