### ISSUE TITLE
Trait Toggling doesn't work on overriden strikes in the same item

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#16982]
When you have a choice between two `Strike`s, say, one using Charisma and one using Intelligence, and you later down the line want to use `AdjustStrike` to enhance it, `AdjustStrike` will only modify the first `Strike` element, EVEN if it is not turned on by the predicates not matching.

Here is an export of the feature this happens with:
[fvtt-Item-mystic-training-KfLxW2YtgvBic9k2.json](https://github.com/user-attachments/files/17494863/fvtt-Item-mystic-training-KfLxW2YtgvBic9k2.json)

And a video:
[chrome_7YXhqid8wQ.webm](https://github.com/user-attachments/assets/2890e237-f4c1-4bf9-bf56-4f211d479919)

**Comment by CarlosFdez** [comment]
Can you make the simplest set of REs to repro this with, and can you test on the latest dev version to make sure the fix I just did has no effect? I know you made an actor, but it will be helpful to reduce how much im testing.

**Comment by MrVauxs** [comment]
The export is the bare minimum. Just drag the class feature to any character.

**Comment by CarlosFdez** [comment]
Can this not be reproduced without the choicesets though? Just two Strike RE's and an AdjustStrike?

**Comment by MrVauxs** [comment]
It cannot be reproduced without ChoiceSets because the two Strikes override one another.

**Comment by MrVauxs** [comment]
[fvtt-Item-mystic-training-KG4STe2rMICAAsiC.json](https://github.com/user-attachments/files/17528336/fvtt-Item-mystic-training-KG4STe2rMICAAsiC.json)



https://github.com/user-attachments/assets/7e87f084-cb9f-4470-9b86-55116cd3f625

**Comment by CarlosFdez** [comment]
I would have preferred including the RE code as code blocks in comments, but I got it work.

I found the root cause but I don't know how to fix it in the current juncture. Basically trait-toggles.ts when running update(), finds a non-ignored strike rule element with a matching slug. The problem is that when strike B overrides strike A, strike A does not become ignored, so the lookup is always pulling up strike A.

**Comment by CarlosFdez** [comment]
Simpler test case

```json
{
  "label": "Magical Blast",
  "img": "icons/magic/fire/beam-jet-stream-embers.webp",
  "damage": {
    "base": {
      "damageType": "fire",
      "dice": 1,
      "die": "d6"
    }
  },
  "key": "Strike",
  "slug": "test-override-override"
}
```

```json
{
  "label": "Magical Blast",
  "img": "icons/magic/lightning/bolt-beam-strike-blue.webp",
  "damage": {
    "base": {
      "damageType": "cold",
      "dice": 1,
      "die": "d6"
    }
  },
  "key": "Strike",
  "slug": "test-override-override"
}
```

```json
{
  "definition": [
    "item:slug:test-override-override"
  ],
  "key": "AdjustStrike",
  "mode": "add",
  "property": "weapon-traits",
  "value": "versatile-b",
  "priority": 40
}
```
