### ISSUE TITLE
Incomplete description for inhaled, contact, ingested, and injury traits

### ISSUE THREAD

**Issue by Lioheart** [foundryvtt/pf2e#16986]
Inhaled's trait description includes only the first sentence. According to Archives of Nethus, it should read like this:

> An inhaled poison is activated by unleashing it from its container. Once unleashed, the poison creates a cloud filling a 10-foot cube lasting for 1 minute or until a strong wind dissipates the cloud. Every creature entering this cloud is exposed to the poison and must attempt a saving throw against it; a creature aware of the poison before entering the cloud can use a single action to hold its breath and gain a +2 circumstance bonus to the saving throw for 1 round.

https://2e.aonprd.com/Traits.aspx?ID=634&Redirected=1

**Comment by TMunsie** [comment]
When reporting an issue we do not accept Archive of Nethys as a definitive source. Please supply the book and page number that you have checked, and preferably what that page says.

**Comment by Lioheart** [comment]
In GM Core on page 248.
The description is the same, so I won't repeat it.

**Comment by Lioheart** [comment]
The situation is similar for the description of **Contact**, **Ingested**, and **Injury**. All in page 248 on GM Core.
