### ISSUE TITLE
Please add "Fortissimo Composition Spell Effect" to the Spell "Fortissimo Composition"

### ISSUE THREAD

**Issue by Psybernetik** [foundryvtt/pf2e#16994]
Please add "Fortissimo Composition Spell Effect" to the Spell "Fortissimo Composition"

The spell effect is listed in the Feat and is pasted below:

@UUID[Compendium.pf2e.spell-effects.Item.rAW5o8MjjuIhYhLg]{Spell Effect: Fortissimo Composition}

Thank you and appreciate everything you guys do.

**Comment by simonward** [comment]
It looks like it's there to me. Have you refreshed your copy of the spell?
<img width="672" alt="Screen Shot 2024-10-25 at 3 37 06 PM" src="https://github.com/user-attachments/assets/ca0cb1c7-90dc-46d7-b103-26562e091d91">

**Comment by Psybernetik** [comment]
My PF2E and all modules are up to date.  How does one update spells
specifically? TIA

**Comment by Psybernetik** [comment]
I figured it out.  I had to delete the spell from his list and redrag and
drop the spell.  Thx!

**Comment by Psybernetik** [comment]
Thx for quick response!

**Comment by simonward** [comment]
> I figured it out. I had to delete the spell from his list and redrag and drop the spell. Thx!

You can also open the spell and use the refresh button in the title bar.

**Comment by Psybernetik** [comment]
Did not know that button was there.  Thanks again for your help!
