### ISSUE TITLE
Bad formatting in "Shake it Off" ability of Gray Worm and other Worms

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#17013]
![grafik](https://github.com/user-attachments/assets/fee58a5e-7d2a-47dc-845f-40fe91882352)

Like the Glacial Worm before the Formatting of the Shake it off ability ist not correct

See Pull Request #17002 

Furthermore i propose to unify the description in all Worms that have this Ability, like the larvae in the Picture below
![grafik](https://github.com/user-attachments/assets/ca0ac824-ffce-443c-bb8b-f1c567978c04)

As far as my research goes the following Worms have this Ability:
Glacial Worm (Description should be adjusted), Gray Worm (Description should be adjusted), Juvenile Cave Worm (Description seems fine), Larval Cave Worm Brood  (Description seems fine)

Sry for the second issue, should have wrote it this way the first time.

**Comment by Vendergast** [comment]
@ammalagonc At the moment your PR just fixes the Glacial Worm but not the Gray Worm. Is this intentional?

**Comment by ammalagonc** [comment]
I didn't read the rest of them. 

Hang tight

**Comment by Vendergast** [comment]
OK im glad this was done but just wanted to be srue if i had to open another issue :) Thanks alot
