### ISSUE TITLE
Using @Embed in archetype descriptions

### ISSUE THREAD

**Issue by Lioheart** [foundryvtt/pf2e#17018]
It would be a good idea to use @Embed in archetype descriptions in journals, due to the fact that they mainly consist of feat descriptions.
This will make future updating of the feat descriptions easier, as well as the work of the translators.

**Comment by pedrogrullada** [comment]
That is the plan, someone just has to do it, and data entry on archetype and class journals is frozen at the moment for War of Immortals entry.

**Comment by Lioheart** [comment]
Good to know. All that is left is to wait.

**Comment by ammalagonc** [comment]
Closing to consolidate - will track this issue via #17070
