### ISSUE TITLE
Spirit Rage / Spirit Barbarian and agile weapons - wrong damage bonus

### ISSUE THREAD

**Issue by thevortex42** [foundryvtt/pf2e#17022]
Sprit Barbarian using Spirit Rage inflicts 3 points of bonus spirit damage. That should be halved (1) for agile weapons. Currently, the Bonus shows up as 0 instead of 1.

When I deactivate the Spirit Rage and use base rage instead, it should be +2 and +1 for agile. But even there it shows up as 2 and 0.

**Comment by ammalagonc** [comment]
Hey there,

I checked and could not reproduce the error:

![image](https://github.com/user-attachments/assets/2630a866-b54c-409f-8901-d2ab0d17c320)

I'm on version 6.5.1

**Comment by TikaelSol** [comment]
Most likely you somehow wound up with two copies of your instinct and it is halving twice.

**Comment by thevortex42** [comment]
I checked on a different server and didn't have the problem there, either. So it must be something local. Sorry for not checking that before posting the issue
