### ISSUE TITLE
Archetype and Class Journal rework - Please reply to this post with any Journal issues here. 

### ISSUE THREAD

**Issue by ammalagonc** [foundryvtt/pf2e#17070]
- [x] Update to use `@Embed` (where applicable)  
-- #17144
-- #17168

- [x] Use Remaster color table formats (where applicable)
- [x] Add missing details (such as additional feats).
- [x] Organize the Archetypes Journal (#17105)
- [x] Organize Class Journal

**Comment by Cuingamehtar** [comment]
In Archetypes journal, some entries are not in alphabetical order:
Assassin, Wandering Chef
