### ISSUE TITLE
Exemplar Epithet Cooldown Effect

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/pf2e#17077]
Most of the Exemplar Epithets make a target temporarily immune for a certain time, similar to guidance.
They should include an effect stating such an immunity for that duration.
![image](https://github.com/user-attachments/assets/e64fb301-5410-4631-8dea-81fec324b64c)

**Comment by pedrogrullada** [comment]
We don't make immunity tracking effects anymore
