### ISSUE TITLE
Exemplar: Energized Spark and Gleaming Blade Not Cooperating

### ISSUE THREAD

**Issue by Karumac** [foundryvtt/pf2e#17106]
Exemplar Feat Energized Spark converts Spirit Damage from Exemplar abilities into one of several damage types.

Exemplar Ikon Gleaming Blade Transcendence Action Flowing Spirit Strike converts the base weapon damage of the Strike into Spirit.

Expected Outcome: Using Flowing Spirit Strike with Energized Spark toggled on should convert the Weapon damage to the value set for Energized Spark.

Current Outcome: Weapon Damage stays Spirit Damage, the rest of the damage is properly converted.

Image 1: Both Toggled Off. Bludgeoning Weapon Damage with Spirit Damage from Astral Rune and from Gleaming Blade Immanence
![image](https://github.com/user-attachments/assets/ef49e213-bd64-4eac-be0e-7ac86d2025b2)

Image 2: Energized Spark Toggled On. Bludgeoning Weapon Damage with Spirit Damage from Astral Rune, but the rest has been converted to Piercing.
![image](https://github.com/user-attachments/assets/298e15a4-3fb7-4540-86ed-8239415ec1cf)

Image 3: Both Toggled On. Spirit Weapon Damage with Astral Rune while the rest of the damage has been converted to Piercing Damage.
![image](https://github.com/user-attachments/assets/0a887e10-c724-462b-911c-89216ed1e546)

**Comment by pedrogrullada** [comment]
Known issue, this relies on the new damage tags feature which doesn't support the DamageAlteration rule element yet. In other words, waiting on system improvement.
