### ISSUE TITLE
Victor's wreath Immanence effect is always active

### ISSUE THREAD

**Issue by Skafe** [foundryvtt/pf2e#17129]
Victor's wreath Immanence effect is always active, regardless of the value of the Divine Spark. 

Removing the effect: Victor's Wreath on the exemplar only works until the exemplar moves, which reapplies the effect automatically.

**Comment by pedrogrullada** [comment]
This was fixed on the latest release. Make sure you update and rebuild your exemplar. Closing as duplicate of #17080
