### ISSUE TITLE
Talisman Esoterica AE-Like RE is generating an error

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#17122]
![Foundry_Virtual_Tabletop_oxNMOkQIkM](https://github.com/user-attachments/assets/9013e7e8-206c-446a-b52d-6a6bef9e1c94)

It is trying to `upgrade` a `null` value. Changing it to `override` fixes it.

![Foundry_Virtual_Tabletop_zWzgS1sFnr](https://github.com/user-attachments/assets/61d1aade-c5b4-4a23-b8e3-c7961d2e7fa9)

**Comment by stwlam** [comment]
https://github.com/foundryvtt/pf2e/issues/16039#issuecomment-2289508089

**Comment by CarlosFdez** [comment]
I can't think of a good way to change this on the crafting system side. We could pre-fill the maxItemLevel, however the default maxItemLevel is actually actor level, so upgrade isn't correct. The feat has to change.

maxItemLevel supports resolvables, so the AELike is completely unnecessary.

**Comment by reonZ** [comment]
> https://github.com/foundryvtt/pf2e/issues/16039#issuecomment-2289508089

because it worked so well last time, after multiple revision, you ended up rejecting it :3

**Comment by reonZ** [comment]
> https://github.com/foundryvtt/pf2e/issues/16039#issuecomment-2289508089

quite funny you would use that when you ended up rejecting the pr you asked me to make there :3

**Comment by stwlam** [comment]
> quite funny you would use that when you ended up rejecting the pr you asked me to make there :3

I believe in you! <3
