### ISSUE TITLE
The Enlarge Companion spell should link directly to the Enlarge spell effect

### ISSUE THREAD

**Issue by fishrobe** [foundryvtt/pf2e#17136]
As the title, when cast at 4th or higher level, the focus spell Enlarge Companion still only seems to make companions large (or does nothing if the companion is already large), but it is supposed to make them Huge. Noticible since there doesn't seem to be a way to manually change their size the way you can with monsters.

**Comment by stwlam** [comment]
There doesn't appear to be an effect linked to it.

**Comment by fishrobe** [comment]
What I mean is, when you drag the effect of Enlarge over from the spell
linked in the Focus spell, it always is only at 2nd level and makes
the animal Large, but at 4th level, it is supposed to make it huge. So
basically, There is no way to upcast (without going into the token,
unlocking its size, and manually making it 3X3).
