### ISSUE TITLE
`tbody` tags never closed in the item identification dialog

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#17134]
https://github.com/foundryvtt/pf2e/blob/9a4e83b64df2e59f109041dcb5236bf9c03b6f98/static/templates/actors/identify-item.hbs

While browsers are smart enough to fix it and close the tabs, i imagine you guys would prefer it being done in your template: all 3 opened `tbody` tags are never closed there.

**Comment by reonZ** [comment]
Before i get scolded, i made the PR !

**Comment by TMunsie** [comment]
> Before i get scolded, i made the PR !

Yay! Thanks!
