### ISSUE TITLE
Fighter Archetype 'Advanced Maneuver' missing rule elements

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/pf2e#17165]
Basic maneuver has a choice set to choose the feat and grant item to grant it, but advanced maneuver has neither.
![image](https://github.com/user-attachments/assets/eeec790b-42b5-40de-98d6-1992f8b6eb20)
![image](https://github.com/user-attachments/assets/5575d878-ccc5-4af1-a34c-ddcdccb705cc)

**Comment by pedrogrullada** [comment]
Duplicate of #12807
