### ISSUE TITLE
Bestiary Redirects

### ISSUE THREAD

**Issue by pinkflumph** [foundryvtt/pf2e#17176]
**Issue:** As of version 6.5.0, Bestiary creatures that have equivalents in Monster Core are being redirected to the Monster Core version in both the compendium navigator and the compendium search. What's worse, some creatures appear to have been completely removed from the Bestiary compendia (e.g., Guard Dog, Animated Broom, Shadow, Greater Shadow, all of the Zombies, etc). 

This makes Legacy play extremely uncomfortable at best, for creatures that have to be sourced directly from the compendium rather than through search or the compendium navigator, or impossible at worst, for creatures that have been removed from the compendia altogether. Note that this also reduces the value of the Legacy module, since it does not affect the redirects, nor does it contain the original (full) versions of the Bestiary compendia themselves

It also restricts the flexibility of the Bestiary and Monster Core token packs, since some creatures that have different art across the two packages have now been removed from the compendia, making one of the art options completely redundant

**Solutions:** A radical solution would be to undo the redirect altogether, since as far as I can tell it seems to only be removing data and choice without adding any value. A more compromising and likely preferable alternative would be to add a toggle to switch between allowing redirects and blocking them.  

Edit: The changes appear to have been started before 6.5.0, but the issue remains the same - what is the need in purging the Bestiary compendia?

**Comment by TikaelSol** [comment]
We are not keeping duplicate actors or undoing the redirects. I am working on an update to the legacy module to add the bestiary 1-3 actors to it, but have not had time to finish it yet.

**Comment by pinkflumph** [comment]
@TikaelSol Thanks, it's good to know that the data won't be gone completely!
