### ISSUE TITLE
Added Speed value not calculated properly [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1720]
The original issue

	Id: 1720
	Title: Added Speed value not calculated properly

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/1720

**Comment by Shandyan** [comment]
This is because the boots give a bonus to `speed` while the class feature gives a boost to `land-speed`. I'm not sure which of these is correct, and what should happen with the ring of climbing

**Comment by ParadoxSong** [comment]
Still a problem. Speed penalties are also not applied.
