### ISSUE TITLE
Hryngar Veteran has Elite Template Applied in Compendium

### ISSUE THREAD

**Issue by Muhsigbokz** [foundryvtt/pf2e#17224]
![image](https://github.com/user-attachments/assets/df2c344b-eaa2-4c8d-b586-1d9f25cd9f4d)

Hello.

Not sure how this Sheet is presented in the source, but I guess default Elite/Weak toggles are errors.

**Comment by simonward** [comment]
<img width="334" alt="Screen Shot 2024-11-07 at 8 54 26 AM" src="https://github.com/user-attachments/assets/8aee6259-2c76-4c9a-881e-11129dbb9150">
