### ISSUE TITLE
Magic Immunity Doesn't Work

### ISSUE THREAD

**Issue by 7H3LaughingMan** [foundryvtt/pf2e#17240]
It looks like IWR is looking for `magical` when calculating IWR; however, it's impossible to setup magical immunity because the option for immunities is `magic`. However, for weaknesses and resistances it's `magical`. I could fix the underlying problem; however, I think this would require a migration which I don't know how to do because creatures are setup with magic immunities so they would need to be changed to magical.

https://github.com/foundryvtt/pf2e/blob/498dd946ccf924f9bc4c4830289bdcf4bf312f76/src/module/actor/data/iwr.ts#L106

https://github.com/foundryvtt/pf2e/blob/498dd946ccf924f9bc4c4830289bdcf4bf312f76/src/scripts/config/iwr.ts#L67

**Comment by DamianLyszczarczyk** [comment]
I believe I had a case today that one of my player casted [Caustic Blast](https://2e.aonprd.com/Spells.aspx?ID=1461&Redirected=1) at a wisp with magic immunity and the damage was applied to it normally.

**Comment by CarlosFdez** [comment]
magical immunity is not the same as magic immunity.

Magical immunity would give weaknesses to strikes from weapons with runes.
Magic immunity is probably paizo's way of saying "spell-like". This is GM arbitrated, foundry cannot control this.
