### ISSUE TITLE
Repeating Error Causes Lag

### ISSUE THREAD

**Issue by Armandeus66** [foundryvtt/pf2e#17269]
The errors start when Foundry boots up, and continue if the game is unpaused, causing input lag. 
I have tried with no mods, and still get the error. Here is a screenshot (I used Find the Culprit).
Browser: Chrome 130.0.6723.117 (Official Build) (64-bit), Foundry 12.331, PF2E 6.6.1
![Screenshot 2024-11-09 201035](https://github.com/user-attachments/assets/5a2b3940-e6a1-4c80-847a-f8c5cfd298bb)

**Comment by stwlam** [comment]
This is due to very old, unmigrated data. Please feel free to seek support on Discord.

**Comment by Armandeus66** [comment]
Actually, I did post this to the PF2E system Discord...
