### ISSUE TITLE
Spellcasting Tab class specific autopopulation

### ISSUE THREAD

**Issue by dg1m** [foundryvtt/pf2e#17278]
The spellcasting tab appears to no longer be autopopulating spellcasting entries based on class (e.g. sorcerer, cleric). I am manually creating the spellcasting entries, which also means that things like Divine Font is no longer autoupdating to the highest rank when a character levels up. If this is intended then you may close this issue. If the spellcasting tab should be autopopulating, then let me know and I'll review mods to see if something is interfering.

**Comment by pedrogrullada** [comment]
There is no such feature in the system, definitely a module.
