### ISSUE TITLE
[BUG] Console spammed with console.warns of failed to validate: Failed to resolve injected property for Dragonblood Surki

### ISSUE THREAD

**Issue by GeorgeWL** [foundryvtt/pf2e#17280]
**Describe the bug**
I'm seeing console.warns spammed for any scene in which my Surki player is loaded into, sometimes so often it causes lag for all my players

It seems to be an interaction with Simple Calendar module, which is causing it to retrigger every time the calendar ticks 1 second, and when I pause the time progressing in Simple Calendar it no longer sends these console.warns into the console

**To Reproduce**
1. Pause time
1. Create a Sukri with Ancestral Paragon & Dragonblood Ancestry
2. Add Surki Player to a Scene
3. Unpause Time
4. See console.warn trigger, once every second

**Expected behavior**
No console.warn spam

**Foundry Information**
 - Foundry Version: 12 (build 331)
 - Game System: Pathfinder Second Edition (system version 6.6.2)
 - [Simple Calendar](https://github.com/vigoren/foundryvtt-simple-calendar) Version: 2.4.18
 - Simple Calendar Configuration: None
 - [Simple Weather](https://github.com/dovrosenberg/foundry-simple-weather) Version: 1.17.0

**Browser (please complete the following information):**
 - Firefox Developer Edition v133.0b6 (64-bit)

**Additional context**

<details>
<summary>Error Log</summary>

> PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.shape}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.save}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Item Alteration rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "{actor|flags.pf2e.dragonblood.tradition}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.shape}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.save}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Item Alteration rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "{actor|flags.pf2e.dragonblood.tradition}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.shape}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.save}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Item Alteration rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "{actor|flags.pf2e.dragonblood.tradition}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.shape}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Roll Option rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "breath-of-the-dragon:{actor|flags.pf2e.dragonblood.save}" [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
PF2e System | Item Alteration rules element on item Breath of the Dragon (Dragonblood) (Actor.ZKvt0lB0cXOmt9ga.Item.YGOclf03x1urMG7F) failed to validate: Failed to resolve injected property "{actor|flags.pf2e.dragonblood.tradition}"
</details>

**Comment by ammalagonc** [comment]
Can you provide the actor json data?

Please and thank you.

**Comment by GeorgeWL** [comment]
> Can you provide the actor json data?
> 
> Please and thank you.

sure, I'll send that for you in a few hours once I finish work 👍 (in 5 hours)

**Comment by ammalagonc** [comment]
I created an actor with the same specifications provided and I did not get the error  :|

Looking at the console messages, it seems like the ancestry option for which Dragon was not selected properly and the rule elements are constantly generating error messages. This is conjecture on my part, would still need to see the actor data to validate.

**Comment by GeorgeWL** [comment]
[xol.json](https://github.com/user-attachments/files/17787983/xol.json)
here's their character data, grabbed it from `let actor = game.actors.get(actorId);` in console

**Comment by ammalagonc** [comment]
You have an older version of the Dragonblood Versatile Heritage - Delete the heritage and grab it again from the compendium. It should prompt you for the type of Dragon. Once that's done, it should resolve the errors.

**Comment by GeorgeWL** [comment]
guess it's maybe technically a bug in that it doesn't give an error message about it?
