### ISSUE TITLE
Cataphract Fleshwarp does not correctly apply alternate effect

### ISSUE THREAD

**Issue by Bhalandros** [foundryvtt/pf2e#17285]
The description of the Cataphract Fleshwarp Heritage reads as follows:

> Your battle-hardened skeleton is laced with additional cartilage and muscle to help bear armor across vast areas of operation, and your skin is bedecked with tiny spurs of pliable, resilient keratin to optimize the grip and weight distribution of your armor. You gain the Armor Proficiency feat.
>
> If your class makes you trained in all types of armor, you instead become trained in Athletics (or a skill of your choice if you're already trained in Athletics) and gain the Armor Assist skill feat.

Currently, adding this heritage to a character trained in all types of armor, produces this effect instead.
![image](https://github.com/user-attachments/assets/e03a92a0-ab54-4ba2-89b0-d0823c9ca9a3)

**Comment by pedrogrullada** [comment]
Looks like an issue with the Armor Proficiency feat. I'll look into it.
