### ISSUE TITLE
[Feature Request] Add option for Survival over Stealth when building Hazards.

### ISSUE THREAD

**Issue by EffiePops** [foundryvtt/pf2e#17290]
Linked below are the rules for alternative weather hazards. Instead of having a stealth DC they predominantly use Survival in its place. It would be nice to be able to choose between different skills as the primary check.

Rules: https://2e.aonprd.com/Rules.aspx?ID=1903
Examples: https://2e.aonprd.com/WeatherHazards.aspx

**Comment by CarlosFdez** [comment]
Late reply, but if possible please try to find non-kingmaker examples of this. Kingmaker was notorious for poor editing.

**Comment by CarlosFdez** [comment]
Without a suite of examples (especially non-kingmaker) I can't really work on this. Please feel free to reopen if you've collected some.
