### ISSUE TITLE
Staff of the Dreamlands

### ISSUE THREAD

**Issue by Crowguard** [foundryvtt/pf2e#17303]
The Major & Greater versions include spell names that don't link to their actual spells.

![image](https://github.com/user-attachments/assets/c7aa6755-92a0-4e7f-8360-e72c9add8207)

Foundry 12.331
PF2 6.6.2

**Comment by ammalagonc** [comment]
The non-linked spells are heightened versions of already linked spells in the item description. They're probably not linked as it would be redundant to include the links twice.

**Comment by Crowguard** [comment]
Fair; I wasn't sure how that was handled.
