### ISSUE TITLE
Spear Dancer feat listed as a passive

### ISSUE THREAD

**Issue by Crowguard** [foundryvtt/pf2e#17312]
This feat is set as a Passive in the system; according to Pathbuilder, Demiplane, and Tikael, it is 1 action.

![image](https://github.com/user-attachments/assets/16f5e460-5c88-4411-abcf-ab033665d7eb)

https://app.demiplane.com/nexus/pathfinder2e/feats/spear-dancer-rm

**Comment by TMunsie** [comment]
I don’t trust either pathbuilder or Demiplane as primary sources, but I will accept @TikaelSol
