### ISSUE TITLE
consecrate missing re

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#17337]
![image](https://github.com/user-attachments/assets/e5681060-1e3f-4348-bbe5-89868f17fcaf)
i would love to have a draggable effect for the positive side effects and an additional effect for the negatives. so it can be dragged regardless of deity. 

theres a section in prey for death that relies on this spell working on a large map. this would be super useful.

**Comment by stwlam** [comment]
Not automatable today, sorry
