### ISSUE TITLE
Flat Checks don't follow automatic success and failure rules for DCs of <=1 or >=21

### ISSUE THREAD

**Issue by websterguy** [foundryvtt/pf2e#17348]
Player Core page 405 states "In the rare circumstance that a flat check has a DC of 1 or lower, skip rolling; you automatically succeed. Conversely, if one ever has a DC of 21 or higher, you automatically fail."

Currently a natural 20 succeeds on a flat check with a DC of 21 and a natural 1 fails a DC 1.

**Comment by stwlam** [comment]
Hesitant to act on this since it would lock out critical success or failure results merely by the DC being out of that range.

**Comment by websterguy** [comment]
Sounds like that's the intent for flat checks specifically to me.

**Comment by stwlam** [comment]
I feel it's more likely that they saw an opportunity to invite the reader to skip a roll and didn't stop to think it through.

**Comment by CarlosFdez** [comment]
It could be that they didn't think the 4 degrees of success mattered for flat checks, then forgot about that when it came time to do inventor.

I agree with the hesitancy.

**Comment by stwlam** [comment]
Or, hell, _dying_

**Comment by stwlam** [comment]
We are more interested in what is affected than we are in what isn't.
