### ISSUE TITLE
Psychic cantrip Forbidden Thought needs an immunity timer

### ISSUE THREAD

**Issue by LonePaladin** [foundryvtt/pf2e#17345]
Many abilities that state the target is temporarily immune include a timed effect to track that immunity. The Psychic cantrip [Forbidden Thought](https://2e.aonprd.com/Spells.aspx?ID=1139) lacks this, even though the description states that targets are immune for 1 minute.

**Comment by pedrogrullada** [comment]
We don't make these purely tracking effects anymore, sorry.
