### ISSUE TITLE
Feature request: Assassin's Bracers should automatically add a 2 action "Focus on the Doomed" action to the action tab in the char sheet with frequency 1x day.

### ISSUE THREAD

**Issue by jrmiller82** [foundryvtt/pf2e#17358]
Feature request: Assassin's Bracers should automatically add a 2 action "Focus on the Doomed" action to the action tab in the char sheet with frequency 1x day.

**Comment by pedrogrullada** [comment]
The standard for now is for equipment activations to be in the equipment itself. Furthermore, physical items cannot use the Grant Item rule element anyway, so this could not be implemented.

**Comment by jrmiller82** [comment]
@pedrogrullada It's not in the equipment itself either. There's only descriptive text.
