### ISSUE TITLE
Concussive not working properly

### ISSUE THREAD

**Issue by deathspyder** [foundryvtt/pf2e#17360]
I have a player who is a gunslinger using an arquebus. However when he attacks something that has a resistance to all damage except magical bludgeoning, it still applies the resistance. I had this tested with pf2etoolbelt and without. 
<img width="215" alt="Screenshot 2024-11-17 145418" src="https://github.com/user-attachments/assets/8149d568-7e2d-438c-a785-8eec425372dc">
![Screenshot 2024-11-17 144700](https://github.com/user-attachments/assets/44d643a1-0c3d-455a-9cee-1bd714ecc61d)
![Screenshot 2024-11-17 144250](https://github.com/user-attachments/assets/85dcf830-a622-4cac-9d16-e059e09a806b)

**Comment by stwlam** [comment]
> When determining a creature's resistance or immunity to damage from this weapon, use the weaker of the target's resistance or immunity to piercing or to bludgeoning. For instance, if the creature were immune to piercing and had no resistance or immunity to bludgeoning damage, it would take full damage from a concussive weapon. **_<u>Resistance or immunity to all physical damage, or all damage, applies as normal._**

**Comment by deathspyder** [comment]
Correct... However, the creatures resistance to all physical damage has a major exception and that "except for magical bludgeoning", so concussive should then be applying the bludgeoning damage to said target. Where as this is not applying the bludgeoning damage as it should. I tested it with a copy of the arquebus and changed the damage to bludgeon, when doing so, the damage was not reduced. So I am saying that in this instance and it has happened once before, concussive is not applying the damage correctly. " f the creature were immune to piercing and had no resistance or immunity to bludgeoning damage, it would take full damage from a concussive weapon." - this sentence right here then reads that the creature should take full damage from bludgeoning.
