### ISSUE TITLE
Stonemaker: Petrifying Gaze Wrong Die

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#17370]
![grafik](https://github.com/user-attachments/assets/bc548525-b897-45a6-a687-1b5bf7d39690)

As you can See the Dice for Pertifying Gaze for Stonemaker is 1d3 an not 1d4 as it should be

**Comment by pedrogrullada** [comment]
The system itself is not a primary source. That creature is based off of a pre-remaster Basilisk, who did use a d3.

**Comment by Vendergast** [comment]
But its just a basilisk variant, which gets the d4?
So any monster which released pre-remaster but gets a updated one doesnt get updates? 
If so good to know :)

**Comment by pedrogrullada** [comment]
Adventure NPCs are, for the most part, left alone.
