### ISSUE TITLE
Advanced Alchemy - Rule elements

### ISSUE THREAD

**Issue by Lioheart** [foundryvtt/pf2e#17415]
According to the description, the number of alchemical items that can be produced is 4 + your Intelligence modifier.
Meanwhile, in the rules it is:
`{"key":"ActiveEffectLike","mode":"upgrade","path":"system.resources.crafting.infusedReagents.max","predicate":["class:alchemist"],"value":"@actor.level + @actor.abilities.int.mod"}`

It should be:
`{"key":"ActiveEffectLike","mode":"upgrade","path":"system.resources.crafting.infusedReagents.max","predicate":["class:alchemist"],"value":"4 + @actor.abilities.int.mod"}`

**Comment by CarlosFdez** [comment]
Duplicate of https://github.com/foundryvtt/pf2e/issues/15647
