### ISSUE TITLE
Oath of the Defender Applies to Everything At All Times

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#17452]
The moment our Champion took Oath of the Defender it gave everyone around them an effect to give resistance +X to everything under a label that says it applies to 'chosen creature type'. There was no option to choose anything and no way to turn it off outside of deleting the feat.

**Comment by pedrogrullada** [comment]
![image](https://github.com/user-attachments/assets/a52c176b-0b10-4c64-836c-a090f6bd9629)
You can choose the type of creature in the actions tab dropdown

**Comment by GorgoPrimus** [comment]
Ah, ok. They didn't see that. Thanks!
