### ISSUE TITLE
Create Kindgom button not showing on party in actors sidebar for new parties

### ISSUE THREAD

**Issue by websterguy** [foundryvtt/pf2e#17474]
As title, created a new world. Turn on kingmaker module or turn on kingmaker campaign homebrew setting. The create kingdom button doesn't show up on the party actor in the sidebar.

Seems there may be some issues with the KingdomBuilder showing choices as they are made, too, but that could be because of the workaround of putting an empty object in the `system.campaign` property to make the create button show up.

**Comment by Araxis2** [comment]
I have the same issue, after having updated from 6.4.1 to 6.7 the create kingdom button from the kingmaker module has disappeared
