### ISSUE TITLE
herbalist dedication + alchemical crafting has an interesting title.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#17500]
![image](https://github.com/user-attachments/assets/f7382eed-96a7-4d16-be85-bde8412aefda)
![image](https://github.com/user-attachments/assets/5ebd2945-535e-4fd4-8dc9-650e9aa17a2c)

if this hasnt been reported just wanted to report it here. we did a level 0 dance.

**Comment by CarlosFdez** [comment]
Dammit, I caught it last minute in advanced alchemy but forgot herbalist. Whoops.

**Comment by ammalagonc** [comment]
No need for the back to 0 dance
