### ISSUE TITLE
[UX] Formulas in Crafting should have an "Add to Advanced Alchemy" button

### ISSUE THREAD

**Issue by tpendragon** [foundryvtt/pf2e#17546]
## Reasoning

When you're an alchemist, the known formulas section is very big. It's difficult to click a formula from known formulas, drag it, and scroll to the correct section. It would be much easier to handle if there were a button for each formula if you have the advanced alchemy feature that would add it to the list. I suspect it would be next to the "Craft" button, maybe an up arrow or a little potion bottle?

Screenshot of the UI I'm talking about:

<img width="498" alt="Screenshot 2024-11-29 at 3 49 42 PM" src="https://github.com/user-attachments/assets/f0e1e6f7-f250-4f3a-816e-7af609b1047e">

**Comment by CarlosFdez** [comment]
There was a similar button, but it added to the first valid entry rather than a selected entry and thus was useless for this purpose.

This will likely become a popout in the future during the inevitable redesign.

**Comment by tpendragon** [comment]
So if I worked this feature to add that button back, it wouldn't be welcome?

**Comment by CarlosFdez** [comment]
It would not. That button was removed because it was awkward to update during all of the internal refactors, and it does not work with multiple crafting abilities very well at all.

If you want to try anything to make this easier, you can try the new sorting paradigm in the quick alchemy branch, where we sort in reverse level order, so that higher level formulas are at the top and closer to the crafting entries.

**Comment by tpendragon** [comment]
You're saying if I PRed a reverse level sort in formulas you'd be open to that? Do you want a button to switch asc/desc?

Also if I can help with the other crafting stuff I'd be happy to do that.

**Comment by tpendragon** [comment]
Another option is allowing items to be dropped into the advanced alchemy section from the compendium, is that also unreasonable?

**Comment by CarlosFdez** [comment]
No toggle, descending all the time. `R.sortBy(something, (f) => -f.item.level)` will do it. You might have to do a conversion from a record to a list of level/formulas objects. Remember that all of this needs redesigns anyways.

No on dropping from compendium. Any sort of drop from compendium has the risk of hitting the wrong dropzone and adding the item to the inventory or something. We don't want to risk that.

**Comment by tpendragon** [comment]
If I get some time tonight I'll take a look. Feel free to close this as wontfix.

**Comment by tpendragon** [comment]
Okay reverse formula sort doesn't really get me there either, it's totally impossible to prepare crafts on a touchpad. How would you feel about a favorite button as an intermediary? Something to push a few up to the top.

**Comment by tpendragon** [comment]
@CarlosFdez Okay reverse formula sort doesn't really get me there either, it's totally impossible to prepare crafts on a touchpad. How would you feel about a favorite button as an intermediary? Something to push a few up to the top.

**Comment by CarlosFdez** [comment]
Does this same issue exist for preparing spells? 

I would prefer not introducing a new feature as an intermediary, especially when the final version would end up removing it. People get too attached to such things.

**Comment by tpendragon** [comment]
It doesn't for preparing spells because they have favorites and searching.

**Comment by stwlam** [comment]
Closing this since it won't be done.
