### ISSUE TITLE
Frightful Presence ability of the Xotanispawn does not Refresh properly

### ISSUE THREAD

**Issue by robinsving** [foundryvtt/pf2e#17573]
### Description
The **Aura RE** for the **Frightful Presence** ability for the **Xotanispawn** is not set properly when Refreshing the ability from the Compendium.
It is set to 0, which is also the Radius of the Compendium Item (Compendium.pf2e.bestiary-ability-glossary-srd.Item.etMnv73EIdEZrYYu)

### Additional data
PF2e version: 6.7.2 (currently latest)
Foundry version: 12 build 331

###  Before Refresh
![image](https://github.com/user-attachments/assets/fd6bca3a-3eb3-446a-b402-0e6db6ad810a)

### After Refresh
![image](https://github.com/user-attachments/assets/0b3837c9-2956-4bd5-b839-739e833ee8c7)

**Comment by robinsving** [comment]
Oh, was just told by my GM that this is not limited to this monster, but to most, if not all, of them!

**Comment by simonward** [comment]
Frightful Presence per MC p. 359 does not have a default size, and different NPCs do have different sizes.

**Comment by simonward** [comment]
Is there a reason you’re refreshing this ability?

**Comment by robinsving** [comment]
No. I just I didn't know that it was not allowed to Refresh on certain NPCs. The Item in question is not of the right publication, so it is obviously not up-to-date, but there is no way of, AFAIK, determining if there are things that are outdated.

_Is_ there a way to determine if an Item needs to be/doesn't need to be updated, then that would be very useful
Closest comment to that was #11706, where (when) such a feature did not exist

**Comment by simonward** [comment]
Refreshing from the Compendium will replace the ability entirely, so there are many abilities where it’s ill-advised to refresh blindly.
