### ISSUE TITLE
Treat wounds and battle medicine macro not working

### ISSUE THREAD

**Issue by Moofal** [foundryvtt/pf2e#17584]
When clicking on the macro nothing pops up and i get this error in the console:
Uncaught (in promise) Error: undefined. "pf2e.RAI.TreatWoundsAltSkills" is not a registered game setting
[No packages detected]

![image](https://github.com/user-attachments/assets/8aee035f-8602-4afc-aa12-61253de9769c)

**Comment by stwlam** [comment]
If you're using macro from the system, that's about three years old now. Otherwise update modules.
