### ISSUE TITLE
Clawdancer Dedication Wrong Formatting

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/pf2e#17602]
The damage rolls on both stances seem to be incorrect on the journal entry.
![image](https://github.com/user-attachments/assets/43fe87fc-6e8f-4d3e-ab82-190be0c73c36)

Aditionally, also on the journal entry, the link to Claw Snag leads to the dedication instead.

**Comment by ammalagonc** [comment]
FYI - if you see any additional errors, please reply to them in #17070. 

Thanks!
