### ISSUE TITLE
Incorrect Prices: Greatpick, Pilgrim's Token

### ISSUE THREAD

**Issue by anaseskyrider** [foundryvtt/pf2e#17619]
According to Nethys, the [Greatpick](https://2e.aonprd.com/Weapons.aspx?ID=378) is worth 1 gp, and the [Pilgrim's Token](https://2e.aonprd.com/Feats.aspx?ID=6496) is a actually a [wooden religious symbol](https://2e.aonprd.com/Equipment.aspx?ID=2745) and so is worth 1 sp.

In Foundry, these prices are erroneously listed as 2 gp and 2 sp respectively.

**Comment by CarlosFdez** [comment]
It helps to link to the books. Sometimes nethys is the one that's wrong.

I verified that the values in nethys are the correct ones at least:
![image](https://github.com/user-attachments/assets/ca7a5bd7-9e7b-43b7-ae5e-f6b74dd319b0)

![image](https://github.com/user-attachments/assets/a1985b4b-6d3c-4e6c-ade3-1a4904fdb4d8)

**Comment by anaseskyrider** [comment]
I was shown how to make pull requests to correct these errors myself and have submitted them.
