### ISSUE TITLE
Shadow Blast Spell missing Saving Throw info when spell is cast

### ISSUE THREAD

**Issue by hugomarques** [foundryvtt/pf2e#17645]
Shadow Blast spell has the following description:

Remastered: 
> Range varies; Area varies; Targets basic Reflex or Will (target's choice)

Legacy: 
> Saving Throw [basic](https://2e.aonprd.com/Rules.aspx?ID=329) Reflex or Will (target's choice)

However, the spell is missing the Saving Throw info in Foundry. See attached.

UUID: Compendium.pf2e.spells-srd.Item.IqJ9URobmJ9L9UBG

Update: I noticed the info is available under the Spell Variants, but it's not shown when the spell is cast.

![Screenshot 2024-12-07 161424](https://github.com/user-attachments/assets/93046456-edbb-42f5-8e5b-7cbf46a027ea)
![Screenshot 2024-12-07 161544](https://github.com/user-attachments/assets/6a8d9c59-0fb9-4d93-93d2-ac51018bbc7e)
![Screenshot 2024-12-07 161552](https://github.com/user-attachments/assets/d0f99b52-76c3-4f61-b5bf-da3ad998e810)

**Comment by ammalagonc** [comment]
I am seeing the two variants, along with the corresponding save rolls.

![image](https://github.com/user-attachments/assets/75d65a2a-67b4-4016-b4e2-db10e65b7de7)
![image](https://github.com/user-attachments/assets/ed656315-e834-43c2-8394-5e7971247695)
![image](https://github.com/user-attachments/assets/bdce68f2-3cbc-4a5c-b240-72899df070d0)

The spell/item might be out of date. Try refreshing it when you get a moment.

**Comment by hugomarques** [comment]
Interesting, how do I refresh it?

**Comment by ammalagonc** [comment]
On the character sheet,, you'll see a Refresh button on the right-hand corner for the spell.
![image](https://github.com/user-attachments/assets/b177d3d9-9f5d-499b-87bd-11b02f0ddd9c)

Other way - just drop the spell and add it again from the compendium.

**Comment by hugomarques** [comment]
Oh, that screenshot was the spell from the compendium.

Initially, I thought it was on my NPC or the PC that the spell was outdated. But then, I searched for the spell in the compendium and that is the screenshot I shared here.  

![Screenshot 2024-12-07 204906](https://github.com/user-attachments/assets/9c6cbfdb-179c-484b-8cec-6b39c741b200)

You can even see there's no refresh button.

**Comment by ammalagonc** [comment]
Perfect - I will go ahead and close this issue then.

Happy Pathfinding!
