### ISSUE TITLE
`damage-received` Notes don't work with custom Roll Options

### ISSUE THREAD

**Issue by ammalagonc** [foundryvtt/pf2e#17651]
I was attempting to automate one of the Mantle of the Frozen Heart effects using the following syntax:

```json
{
  "key": "Note",
  "selector": "damage-received",
  "text": "PF2E.SpecificRule.SpellEffectMantle.FrozenHeart.HeartOfIce.DamageNote",
  "title": "PF2E.SpecificRule.SpellEffectMantle.FrozenHeart.HeartOfIce.Title",
  "predicate": [
    {
      "or": [
        "frozen-heart-first:heart-of-ice",
        "frozen-heart-second:heart-of-ice"
      ]
    }
  ]
}
```

The spell effect allows you two ongoing effects simultaneously, which can be swapped using an action. The two roll options worked for everything but the damage note.

**Comment by CarlosFdez** [comment]
if I put in predicates that show up in the roll inspector, it seems to work. You'll need to pop open the roll inspector and show me that those predicates you're referring to do exist for me to dig further.

**Comment by ammalagonc** [comment]
![image](https://github.com/user-attachments/assets/4b022d40-7baa-431f-830c-1d223b3b0f8c)

**Comment by CarlosFdez** [comment]
The issue you're having is that the roll options aren't available when damage is taken. Only your own options that start with self: show up in ephemeral effects from the perspective of the actor taking damage.

**Comment by ammalagonc** [comment]
Fun times - Guess I'll have to add that one as a separate effect for it to work.

**Comment by ammalagonc** [comment]
Welp, it was worth asking - thanks @CarlosFdez
