### ISSUE TITLE
Status and circumstance bonuses to damage do not work unless there's an untyped bonus of the same type

### ISSUE THREAD

**Issue by JestePalom** [foundryvtt/pf2e#17683]
Issue as in title. The screenshot is taken on a game with no modules activated.
![obraz](https://github.com/user-attachments/assets/cf3f334d-75aa-4dc3-8781-957c04da29c3)
![obraz](https://github.com/user-attachments/assets/e1d7fe83-f643-4695-90db-ea26b83939bf)
![obraz](https://github.com/user-attachments/assets/60aa6c76-ecb5-492e-b437-7bc94d360f06)
![obraz](https://github.com/user-attachments/assets/19f663ce-7263-4d69-acc9-96f07b952ea5)

**Comment by stwlam** [comment]
Working as intended: you'll want to change the base damage type to match in a case like this.
