### ISSUE TITLE
Ranged weapons need their range increment to be displayed [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1769]
The original issue

	Id: 1769
	Title: Ranged weapons need their range increment to be displayed

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/1769

**Comment by stwlam** [comment]
Resolved at some point!
