### ISSUE TITLE
Adv Weapon Training feat

### ISSUE THREAD

**Issue by GM-Swan** [foundryvtt/pf2e#17757]
Foundry v12.331
PF2e v6.7.2

The Advanced Weapon Training feat is not working correctly in the following instance:
A 6th level fighter with feats - Fighter Weapon Mastery (sword) and Advanced Weapon Training (sword) is using a Katana (martial) and spiral rapier (advanced).
The simple and martial sword proficiency is calculated correctly at +12
But the advanced weapon training sword proficiency is + 10. This should also be +12 (same as the martial weapon of that group)

**Comment by stwlam** [comment]
Duplicate of #16906
