### ISSUE TITLE
Raging Barbarians increase their Furious Footfalls *and* Fleet bonuses

### ISSUE THREAD

**Issue by TheL0rd0fSpace** [foundryvtt/pf2e#17760]
When a Barbarian is Raging, their bonus from Furious Footfalls is supposed to increase from +5ft to +10ft.

However, the same thing happens to their Fleet bonus, which isn't supposed to happen.
I don't know enough about the underlying software to know why.

**Comment by pedrogrullada** [comment]
This was an issue that was fixed very soon after PC2's release. Make sure your copy of Furious Footfalls is up to date. Duplicate of #15692
