### ISSUE TITLE
[Data Error]: Scales of the Dragon listing in the Dragon Disciple Archetype says Status instead of Item.

### ISSUE THREAD

**Issue by Payden-Pringle** [foundryvtt/pf2e#17770]
![image](https://github.com/user-attachments/assets/d6e5a179-2b79-4b34-aaeb-b57cc54f2534)
In the Dragon Disciple summary of Feats page in the Journal, it states the bonus is a Status Bonus to AC. This is incorrect.
In the actual Scales of the Dragon Feat, it correctly shows the bonus is an Item Bonus to AC.

**Comment by simonward** [comment]
Fixed by Journal changes 53acbbd45c9a.
