### ISSUE TITLE
Alchemist daily crafting not taking efficient alchemy feat into consideration

### ISSUE THREAD

**Issue by thejoester** [foundryvtt/pf2e#17778]
Have a level 5 alchemist with +4 INT, will not let him prep 10 items as it should (6+INT).

>  Thanks to the time you've spent studying and experimenting, you know how to scale your formulas into larger batches that don't require any additional attention. Increase the number of items you can create each day with Advanced Alchemy to 6 + your Intelligence modifier.
> In addition, when you Craft alchemical consumables during downtime, you can produce twice as many alchemical items in a single batch without spending additional preparatory time. For instance, if you are creating Elixirs of Life, you can craft up to eight elixirs in a single batch using downtime, rather than four. This doesn't change the amount of alchemical reagents or other ingredients required to craft each item, nor does it change your rate of progress for days past the base downtime spent.

**Comment by CarlosFdez** [comment]
I can't reproduce this. I took a new copy of Fumbus, and then I added `Efficient Alchemy (Alchemist)`, and it worked. I 0'd and backed the level and that also works.

**Comment by thejoester** [comment]
Okay so what I think happened, is that when I recreated my alchemist's character for him I just dragged the feats from his old character. Just had him remove and manually add the feat and it seems to be working.
