### ISSUE TITLE
Quick Alchemy - Quick Vials

### ISSUE THREAD

**Issue by ottyn** [foundryvtt/pf2e#17780]
Using the new Quick Alchemy action, when creating a Versatile Vial from the formula list to create a Quick Vial, it is only creating a Level 1 vial instead of a vial at level per the rule elements.  The crafting also expends a Versatile Vials Special Resource when it should not.

**Comment by CarlosFdez** [comment]
Quick Vials aren't implemented yet, though we're considering ways it can be done. Versatile Vial shouldn't even be a learnable item though, so I didn't expect people would add it to the formula list and try to use versatile vials to craft versatile vials 🙃

**Comment by ottyn** [comment]
I'll go ahead and close this then since it's already planned.  Thank you to all the devs for the hard work you put in!
