### ISSUE TITLE
Feature request: update character sheets

### ISSUE THREAD

**Issue by arbatter** [foundryvtt/pf2e#17791]
I like foundry and it’s many features but compared to the recent sheet updates by other vtt’s the Pf2e is not going to compete to gain new users, especially people new to pathfinder. Mostly the new ones by competing vtts include easy links to associated feature rules, character builders, written headings in lieu of  symbols, generally more approachable interface. My players prefer not to try foundry sheets for these reasons which makes using the vtt in general not desirable. I’m sure foundry has a dedicated user base and may not be concerned with growth but I see this as big hurdles for appealing to new users. No need to respond. I just needed to put it out there!

**Comment by CarlosFdez** [comment]
There have been slow but iterative UI work on all sheets, including PC sheets. The main tab has been reworked a few months back, and just last patch the inventory tab and crafting had some improvements. Without any designers, and without full-time devs, we cannot work faster than that.

**Comment by TMunsie** [comment]
We are a volunteer development team, so we welcome your contribution to improve the system. If you design it up and create a branch I’m sure the leads will be happy to review it!

Additionally, the development team isn’t commercial or commercially supported, so you are correct that user growth and popularity aren’t our concerns. That being said, players are and our development is in line with that.

**Comment by TikaelSol** [comment]
Closing as not particularly actionable.
