### ISSUE TITLE
Hazard Breath of Despair: Wrong Attack  + Fleeing Condition Number out of Bracket

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#17797]
![grafik](https://github.com/user-attachments/assets/bfbb10c3-3fb2-4dab-b3b2-2025b50364cb)

![grafik](https://github.com/user-attachments/assets/cd25231a-0b0b-420d-b5b6-4f8a174104d4)

The Attack "Despairing Breath" is a meele Attack but should be range. Additionally the Number one of the fleeing condition is out of the Bracket

**Comment by pedrogrullada** [comment]
It looks like both of these are the result of editing errors in Kingmaker itself: Fleeing 1 is not a thing, they might've meant fleeing for 1 round, but who knows; and they didn't provide a range for the attack, and without a range the sheet will default the attack to melee. This isn't very actionable.

**Comment by TikaelSol** [comment]
Closing as a Paizo error

**Comment by Vendergast** [comment]
Ups your are right! Good to know
