### ISSUE TITLE
`Base weapon`(Under details) when creating weapons, inputs the wrong `Base Damage`

### ISSUE THREAD

**Issue by atadtoad** [foundryvtt/pf2e#17801]
Whenever you create any weapon in pf2e, and choose a `base weapon` for example, Maul, Greatsword, etc, it will always default to a 1d6 Slashing damage, regardless of the base weapon. if this wasn't meant to auto-fill I'd imagine it'd leave it empty for manual-filling, however, since it auto-fills it to a 1d6 slashing, I assume it is simply a bug. 🪲

Note: In the books and nethys, their die is a 1d12 bludgeoning or slashing
![image](https://github.com/user-attachments/assets/69fd739a-b078-496a-8f6d-15c193c54138)
![image](https://github.com/user-attachments/assets/018e9e71-6bfa-48d7-8fe0-7af2ceb03928)

**Comment by stwlam** [comment]
1d6 is simply the initial value for that field in weapon data. You can change it to whatever you'd like.

**Comment by atadtoad** [comment]
I have to ask, why have a field for base weapon then? isn't a weapon group sufficient? When putting a base weapon I figured its expected to have it fit those stats? 
Please lmk if i miss understand.

**Comment by TikaelSol** [comment]
Base weapon is there to set the base weapon, which gets used in a lot of automation. We are definitely never going to hard code the damage of a greatsword beyond just having it in the item. That would make the process of making new equipment longer for not much benefit.
