### ISSUE TITLE
Quick Alchemy create items do not stack/remove

### ISSUE THREAD

**Issue by manuel-hegner** [foundryvtt/pf2e#17807]
The following szenario:

1. alchemist with versatile vials
2. Use Quick Alchemy to craft an Alchemist's Fire
3. attack with the Alchemist's Fire
4. the alchemist now has a stack of 0 Alchemist's Fire
5. Use Quick Alchemy to craft an Alchemist's Fire
6. the alchemist now has a stack of 0 and a stack of 1 Alchemist's Fire
7. attack with the Alchemist's Fire
8. the alchemist now has two stacks of 0 Alchemist's Fire

Ideally, the stack would vanish completely after being used. That might be difficult to implement though, as generally stacks of size 0 are quite useful for players. The user friendliness would be improved considerably though, if Quick Alchemy would search for a stack of infused identical items not in a container and add to that before creating a new stack.

**Comment by CarlosFdez** [comment]
Depleting size 0 stuff isn't possible now (rolling damage will stop working and the damage buttons will disappear even if we store it in the damage card), but stacking with a 0 quantity item with the same held state logically makes sense. at least in the short term.

**Comment by manuel-hegner** [comment]
After some investigation there is already a handling for this. It fails right now because of https://github.com/foundryvtt/pf2e/blob/2ad0158cdbc5b564338137e56b99281c6515b681/src/module/item/physical/document.ts#L474

In the case of quick alchemy both items have their `isHeld` property set to `true`, which prevents stacking. I think this should only prevent stacking if both stacks are also non-empty.

**Comment by CarlosFdez** [comment]
Not quite that, we don't want held items stacking with worn items. I saw the stacking before release, but we weren't aware of the exact solution we wanted at the time.
