### ISSUE TITLE
Craft Activity not updated for Remaster

### ISSUE THREAD

**Issue by jsrose09** [foundryvtt/pf2e#17810]
The Craft activity doesn't seem to have been given an update for the Remaster as it still lists the 4 day set up time as seen below.

![image](https://github.com/user-attachments/assets/8b547c69-762f-41cb-a041-be91b16628d2)

Compared to the Remastered version.

![image](https://github.com/user-attachments/assets/f6fa21ec-60ad-47d1-b733-ef0dd92700b6)

**Comment by pedrogrullada** [comment]
Where are you looking at the Craft activity in Foundry? The action item seems to be up to date.
![image](https://github.com/user-attachments/assets/29f779fe-6e10-4fb0-914a-e4a9c31b933f)

**Comment by jsrose09** [comment]
Hm interesting - I'm guessing that the activity I'm looking at now only exists in the Character sheet it was on. That's an unfortunate amount a busy work I or my players have to go do - delete all the actions manually put on the sheets for quick reference and re-add them to be sure they are correct.

**Comment by pedrogrullada** [comment]
Use the refresh button.
![image](https://github.com/user-attachments/assets/015d005d-c634-4578-80c7-6b755b46fd09)

**Comment by jsrose09** [comment]
How have I never known that feature after years of Foundry use....? 

Thank you for enlightenment.
