### ISSUE TITLE
Tempest Touch spell is (still) listed as cursebound

### ISSUE THREAD

**Issue by Weissrolf** [foundryvtt/pf2e#17854]
I think this should not be cursebound (anymore) in Remaster!?

![image](https://github.com/user-attachments/assets/1ec2ae8b-4802-4122-af3f-613e93172d93)

Thanks and have a happy new year.

**Comment by simonward** [comment]
Did you refresh your copy of the spell?

**Comment by Weissrolf** [comment]
I am not sure what "refresh" in this context exactly, but I assume it means to remove the spell from the character sheet and then drag it back on anew?! This worked, so thanks for the hint! :-)

Or is there an automated way to refresh these things to reflect rules/module changes?

**Comment by simonward** [comment]
> I am not sure what "refresh" means in this context exactly, but I assume it means to remove the spell from the character sheet and then drag it back on anew?! This worked, so thanks for the hint! :-)

You can also edit the spell, then click the refresh button in the title bar.

**Comment by Weissrolf** [comment]
> > I am not sure what "refresh" means in this context exactly, but I assume it means to remove the spell from the character sheet and then drag it back on anew?! This worked, so thanks for the hint! :-)
> 
> You can also edit the spell, then click the refresh button in the title bar.

Ah, yes, great. I didn't know about that button. We are mainly playing at the table and I tend to just import my players' Pathbuilder data. So I didn't have to look at/use all intricacies of Foundry/PF2E module too often while using Foundry for my GM duties and presenting maps on mobile monitors (laying flat on the table). Thanks again, well appreciated!
