### ISSUE TITLE
Add Archer Dedication rule element

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1884]
In GitLab by @MrVauxs on Nov 23, 2021, 06:23

The Archer Dedication should have the rule element adding the bow critical specialization if you have an expert bow proficiency.
`{"key":"Note","outcome":["criticalSuccess"],"predicate":{"any":["proficiency:master","proficiency:expert"]},"selector":"bow-weapon-group-damage","text":"<p class='compact-text'><strong>Critical Specialization</strong> If the target of the critical hit is adjacent to a surface, it gets stuck to that surface by the missile. The target is @Compendium[pf2e.conditionitems.eIcWbB5o3pP6OIMe]{Immobilized} and must spend an Interact action to attempt a DC 10 Athletics check to pull the missile free; it can't move from its space until it succeeds. The creature doesn't become stuck if it is incorporeal, is liquid (like a water elemental or some oozes), or could otherwise escape without effort.</p>"}`

**Comment by TikaelSol** [comment]
This has been implemented, closing.
