### ISSUE TITLE
Munitions Crafter, Ammunition Crafting

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1903]
In GitLab by @Velara on Nov 29, 2021, 17:25

At present when a Gunslinger with the munitions crafter feat adds an ammunition formula such as Rounds (Jazail) to their advanced alchemy section. An error message is displayed "Item is not compatible with crafting entry trait requirements, must match one of [["alchemical, bomb"], ["alchemical"]

Moreover, when crafting ammunition or Black Powder doses, they are treated like normal alchemical items and cost 1 reagent per 2, while level 0 ammunition should instead cost 1 reagent per 10 rounds.  Per the Munititions Crafter feat. "If you use a batch of infused reagents to create basic level-0 ammunition such as black powder cartridges or black powder doses, you produce 10 rounds of ammunition."

Awesome job on the crafting window, by the way. Love it.

**Comment by Far2Casual** [comment]
And just for info, there has been a regression of some sort as the warning for incompatible item when adding rounds is back. 
![image](https://user-images.githubusercontent.com/63196064/194763997-77843871-9fe5-4d37-9bd8-5a0f974fde1e.png)

**Comment by shemetz** [comment]
Reproduced again, [link to discussion on Discord](https://discord.com/channels/880968862240239708/880969253765935174/1069627739591688263).


![image](https://user-images.githubusercontent.com/6516621/215522046-293982f8-7a8b-4067-aab9-ce39d893d77f.png)

There's no `item:subtype:ammo`, even though the Consumable Type is "Ammunition".
