### ISSUE TITLE
Allow spells to have multiple save types

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1905]
In GitLab by @fraserstanton on Nov 30, 2021, 11:40

See discord chat below:

Friz — Today at 1:25 AM
Shadow Blast spell:
Saving Throw basic Reflex or Will (target's choice)
You shape the quasi-real substance of the Shadow Plane into a blast. Choose acid, bludgeoning, cold, electricity, fire, force, piercing, slashing, or sonic damage, and choose a 30-foot cone, a 15-foot burst within 120 feet, or a 50-foot line. The blast deals 5d8 damage of the type you chose to each creature in the area.
It doesn't look like we have automated the save to be a choice .. is this a known issue?
Save button doesn't seem to work currently

stwlam — Today at 1:19 AM
We may have different understandings of what an "issue" is, but, no, that's not currently supported 

Friz — Today at 1:25 AM
I am sure there are other spells with choices for saves ... how do we track that a) it doesn't work currently and b) a future fix might fix it?

Supe — Today at 1:29 AM
If I recall, it was blocked previously by a discussion on who chooses. Does the system choose the better one automatically, or does the player/monster choose. If I recall, there was a camp of argument that wanted the player/monster to choose because it'd be meta if they knew their bonuses or something.
I think I was in camp auto-choose-the-better-one but maybe there's some consumable resource that's only for like will saves but not reflex saves or something I'm not aware of
Also like everything else, it needs a way to actually set it in UI that actually makes sense. Save type "will/reflex" as a new choice isn't very sustainable 
Cora (On Strike Since 1997) — Today at 1:30 AM
Also you might have +8 will and +7 reflex, but the Evasion feature, so your reflex ends up better?
Letting the person choose seems RAW. I could also see it being an RP thing, since it basically depends on whether you see through the illusion or not

Ryan (She/Her) — Today at 1:31 AM
or say something like the bulwark armour effect
that's only for certain reflex saves

Supe — Today at 1:32 AM
I think that camp wanted to avoid auto-detection because they wanted to hide those traits fsr 🤷‍♂️
I think raw you take the "better" always if I remember right but that might be hard to determine, especially because of things like evasion.

Raven — Today at 1:38 AM
I mean it literally says "target's choice" in the spell entry so idk where the confusion lies

Supe — Today at 1:39 AM
maybe I was looking at a different instance of the same thing 🤷‍♂️
This was months ago when we were looking at it. But I think currently the only real blocker is how to represent it, and also because there's a mountain of other stuff

Cora (On Strike Since 1997) — Today at 1:41 AM
It probably wouldn't be the worst thing ever if chat cards supported multiple save / template buttons
Then you could just display a reflex and will save button and let people click whichever
There are even spells that have several different potential damage rolls

Supe — Today at 1:43 AM
for several different damage rolls/templates, I was thinking of a variant override system where you select what version of the spell you're casting (waiting on some improvements in parsing and more deliberation before going in on that), and :fryguy: was imagining a nested multiple degrees of success system. 
Some people wanted to do it via inline buttons (the @Template stuff) and remove a bunch of stuff from the details tab as well.
But other than that, having separate template buttons and separate save buttons I think was one way I thought was good. Though saves being a list is odd ui. If anything it'd be "additional saves" or something like that. Not sure yet. 
Though I think there was disagreement on having multiple template buttons. I don't remember.

Cora (On Strike Since 1997) — Today at 1:49 AM
What if the saves were side by side, would that be less objectionable?
So like instead of 

[              Damage              ]

[              Will Save            ]

[             Reflex Save         ]

it could be

[                 Damage                ]

[  Will Save  ] [ Reflex Save ] 

Supe — Today at 1:50 AM
Separate save buttons on the chat card is the easy bit. Its the spell editing form and data storage that I don't know yet. Maybe a + button next to the dropdown to create a second dropdown? An "altType" property? 🤷‍♂️ 
I think the main objectionable-ness wasn't the save buttons, it was the multiple template buttons 

Trist (he/him) — Today at 1:55 AM
mmh but there is spells that offer multiple templates right? like some walls?

**Comment by FolkvangrForgent** [comment]
I was wondering if there was any update on support for multiple save types for a single spell. The issue has come up a few time in play and slows down combat just a bit but enough to make it annoying.
