### ISSUE TITLE
Tracking Issue: Data entry for ChoiceGrant improvements

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#1956]
In GitLab by @TikaelSol on Jan 1, 2022, 22:26

This is a tracking issue for what items have had ChoiceSet/GrantItem added to them

- [x] Classes/Class Features
- - [x] Alchemist
- - [x] Barbarian
- - [x] Bard
- - [x] Champion
- - [x] Cleric
- - [X] Druid
- - [X] Fighter
- - [x] Gunslinger
- - [x] Inventor
- - [x] Investigator
- - [x] Magus
- - [x] Monk
- - [x] Oracle
- - [X] Ranger
- - [X] Rogue
- - [x] Sorcerer
- - [x] Summoner
- - [X] Swashbuckler
- - [X] Witch
- - [X] Wizard

- [x] Class Feats
- - [x] Alchemist
- - [x] Barbarian
- - [x] Bard
- - [x] Champion
- - [x] Cleric
- - [x] Druid
- - [x] Fighter
- - [x] Gunslinger
- - [x] Inventor
- - [x] Investigator
- - [x] Magus
- - [x] Monk
- - [x] Oracle
- - [x] Ranger
- - [x] Rogue
- - [x] Sorcerer
- - [x] Summoner
- - [x] Swashbuckler
- - [x] Witch
- - [x] Wizard

- [ ] Other Feats
- - [x] Skill Feats
- - [x] General Feats
- - [x] Ancestry Feats
- - [x] Heritages
- - [ ] Advanced multiclass feats

- [ ] Spell Effects
- - [x] A - J
- - [ ] K - Z
- [ ] Equipment

**Comment by TikaelSol** [comment]
Not sure why I closed this, it is still open

**Comment by Lioheart** [comment]
I looked for a way to manually create this feat, but it is impossible without the appropriate changes to the system.

You need to create a self:halflevel variable (along the lines of self:level). This will make it possible to use it in the feat.
![obraz](https://github.com/foundryvtt/pf2e/assets/39154364/e7bfe211-367b-45f9-98a7-2c299e87fbf7)

For example, in the Advanced Trickery feat when I inserted the following condition, I could select level feat up to the character's level (example for a 14th level character):
```
"lte": [
                "item:level",
                "self.level"
              ]
```
![obraz](https://github.com/foundryvtt/pf2e/assets/39154364/0b567ce3-7a6f-406b-9f62-f54b59e7d7c8)

I would ask you to consider such a possibility.
