### ISSUE TITLE
Bestiary icons gone after update?

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2004]
In GitLab by @epfaffinger on Jan 17, 2022, 10:25

After upgrading my Pathfinder 2E to v9 in Foundry VTT my Bestiary icons folders have been removed breaking icons in worlds I have?

This folder no longer exists after updating?
systems/pf2e/icons/bestiary-1

**Comment by TheFlyingPig** [comment]
My default loot.svg disappeared.  I'm a new user so it's not much of a hassle, I guess I just need to find a new icon for loot.

**Comment by stwlam** [comment]
> My default loot.svg disappeared. I'm a new user so it's not much of a hassle, I guess I just need to find a new icon for loot.

Nothing has changed with that. It sounds like you may have a bad system install: try getting technical support on the Foundry discord.
