### ISSUE TITLE
Hide feats in compendium popup for which my character does not meet the pre-requisites

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2027]
In GitLab by @Patrick.Son on Jan 22, 2022, 16:21

I like that when opening the compendium from the feats page, the relevant filters are already set (class, level, feat type, etc.). However, it still shows feat choices that I can't actually pick, such as Assurance for a skill I'm not trained in. It would be nice if the list of feats was filtered by such pre-requisites, or at least showing ineligible feats at the bottom, greyed out or something.

**Comment by stwlam** [comment]
We're a very long ways away from prerequisites even being representable in data, so this isn't going to be feasible.
