### ISSUE TITLE
Unhide various bits of text that are hidden for no reason

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2028]
In GitLab by @thenobledrake on Jan 22, 2022, 21:49

All text currently set to gm-only visibility needs to have a way to show the players. Literally everything that doesn't have a secret trait tag should default to visible, not be mega-hidden because someone on the prog squad feels like hiding the game rules from the people playing the game.

Example: poison chat card reads as the name of the poison and a fortitude save button for the player; there's no way to choose to show the text that has been set to GM-only even for us GMs that would rather our players can see the game they are playing.

**Comment by TMunsie** [comment]
Closing as resolved.
