### ISSUE TITLE
Cannot add runes to Eldritch Nails

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2031]
In GitLab by @lptheriault on Jan 23, 2022, 11:20

Cannot add runes to Eldritch Nails. Once the feat is taken, they are listed under strikes but nowhere else. I had to create a custom weapon for that to work.

**Comment by stwlam** [comment]
Closing: a feature allowing unarmed attacks being fully editable as items is not likely to ever happen
