### ISSUE TITLE
Problem with the timing of removing expired effects

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2050]
In GitLab by @j.darien.riffe on Jan 30, 2022, 19:13

This is a replacement for #2048, I misunderstood the behavior I was seeing. The "effects auto-expire" checkbox does not seem to matter for this bug. Instead, when "remove expired effects" is checked, expired effects are sometimes being marked as expired, but "cleaned up" on a later initiative count.

Exactly when is complicated, so I'll run through the cases I'm seeing. To repro, create an encounter with multiple PCs and NPCs, ensure they each have a unique initiative count, grab a 1-round effect expiring at the start of turn. I'm using the following, with Inspire Courage as an example.
![1](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/91888eefa6a3c3573c40db1ba2fb44f9/1.png)

Case 1 - Apply effect to Amiri on her turn, stage through to the next turn. Expires and removes on count 18. As expected, great.

Case 2 - Step through initiative, apply effect to Akata and Bandit each on their own turn. Next round, Akata's drops on 8, Bandit's on 6. As expected, great.

Case 3 - Apply effect to Amiri, Ezren, Akata each on their turn. Next turn, at the start of Amiri's initiative, the effect is marked as Expired, but is not removed. Step forward, both Amiri and Ezren's effects are removed at the start of Ezren's turn. Akata's effect is removed on its turn as expected.

Case 4 - Apply effect to every creature on its turn. Next turn, Amiri, Ezren and Akata all have expired effects not removed. All 4 effects removed at the start of Kyra's turn. Bandit's is removed as normal.

In effect, if any PC has an effect which will expire during a turn, no expired effects will be removed from a token until the lowest initiative PC with an expiring effect is reached. NPCs are not effected unless there is an affected PC. Effects scheduled for end of turn exhibit the same behavior, and including multi-round effects does not trigger the bug, only effects expiring on the current turn.

**Comment by PinkySherman** [comment]
I have a problem with the Shield spell not being removed, ever. It just sits there with the expired tag.
