### ISSUE TITLE
Item cost calculation looks inconsistent in Daily Crafting section

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2070]
In GitLab by @w00tingspree on Feb 6, 2022, 13:00

Hi, my table (esp. me the GM and the alchemist player) really appreciates the work being done on Crafting!

I noticed the infused reagents cost calculation for Daily Crafting is not adding up.

With Advanced Alchemy, if I add 2 different items, it gives me a cost of 1 (maybe it's rounding down?)

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/340deb6721f4b7323da87f5edfd9c692/image.png)

If I add Field Expertise (Bomber) into the mix, the Alchemist should be able to make 3 bombs for 1 reagent, which looks correct. 3 bombs cost 1 reagent, 4 bombs cost 2 reagents as expected:

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/ff07a455ece9a7a47511bf67aae9dbe4/image.png)

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/446607119627b326a3819c445df56567/image.png)

But when I start adding other items, the math starts looking inconsistent again (4 bombs and 1 potion should cost 3 reagents, not 2).

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/2c3a31293885cc728d57f1d72c141fac/image.png)

**Comment by DocSchlock** [comment]
Tested as presented - this was resolved at some point.
