### ISSUE TITLE
Flat-footed inline button from grabbed active effect is not functioning.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2074]
In GitLab by @jpmiers4 on Feb 10, 2022, 21:01

If an actor has the grabbed condition. On the effects tab of that actors sheets. The grabbed condition includes an inline flat check button. This button does not have a dc5 listed and is non-functional when clicked.

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/e42a70615fb608e5879ab537de95bc38/image.png)

**Comment by simonward** [comment]
This appears to work correctly now.
