### ISSUE TITLE
Familiar Sheet : Improvements of localization

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2078]
In GitLab by @rectulo on Feb 13, 2022, 08:26

First of all : The familiar sheet is great

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/6a0782d85bc71150ccc7af98fdf17107/image.png)

I'm asking for help to localize 
1. the saves  
2. sort the localized skills (if it is possible)

**Comment by rectulo** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/98176148/10a978ff-1a74-4068-acf2-639cc1b7731d)
Yes
