### ISSUE TITLE
Feature Request: Add chat log option for new interact options [REPLACEMENT ISSUE]

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2082]
The original issue

	Id: 2082
	Title: Feature Request: Add chat log option for new interact options

could not be created.
This is a dummy issue, replacing the original one.In case the gitlab repository still exists, visit the following link to see the original issue:

https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/issues/2082

**Comment by TikaelSol** [comment]
No idea what this issue is even referring to anymore.
