### ISSUE TITLE
Feature Request: Link Shield Boss/Spikes to shield for dropping / sheathe

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2085]
In GitLab by @Templars_Knight on Feb 14, 2022, 14:30

**Userstory**

The new toggle buttons are awesome. A small addition that would top that off for a shield bearer: create a connection between the offensive element (shield boss or spikes) with the shield. Then I could trigger the drop of the shield weapon from the action area and would correctly lose the shield and the AC bonus. Furthermore, dropping the shields or the shield weapon addition via the equipment page should actually result in the other element having to be dropped as well.

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/593d070caae86f8c9945deb836feb96c/image.png)

Cheers,
TK

**Comment by DocSchlock** [comment]
This was resolved in a recent update - attaching an offensive element to a shield and dropping / stowing the shield will treat the attached offensive element correctly.
