### ISSUE TITLE
@Check inline rolls trait secret not working

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2093]
In GitLab by @jocolamarco on Feb 18, 2022, 05:58

Tested on a clean, new world with no modules.

Entered the following into a journal entry:
`@Check[type:perception|dc:24|traits:secret]`

It runs without changing the context to Blind GM roll as expected:
![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/53dffab5b14f989c3b7c8f84f3237755/image.png)

Versions below:
![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/82fb08c02be97d7523ce76f32d8baf0d/image.png)

**Comment by Braintelligence** [comment]
Is it possible that this still isn't working? I get public roll mode for `@Check[type:stealth|dc:22|traits:secret]` in Foundry v9.
