### ISSUE TITLE
Add heightened spell level to chat-card and attack roll message flags.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2122]
In GitLab by @william.ring.91 on Mar 1, 2022, 10:26

For use in parsing messages for data, the heightened spell level will allow for automation of damage rolls without relying on looking at the flavor text. Use case: in xdy-workbench

**Comment by MrVauxs** [comment]
Would be great if the same happened for what option was selected for 1-2-3 action spells.
