### ISSUE TITLE
Swashbuckler Precise Strike Damage not applied to thrown weapons

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2168]
In GitLab by @drober76 on Mar 23, 2022, 09:27

Precision damage from the Precise Strike feature is not applied when characters have Panache or make a finisher for weapons in the Dart critical specialization effect family. Discovered this with the Tamchal Chakram, a melee weapon with the thrown trait. Fixed it by changing the weapon family to Knife.  Suspect this is because Darts are typically thrown, but now there are two melee weapons (Tamchal Chakram and Stiletto Pen) in this family.  Confirmed this is an issue both with Swashbuckler class and Swashbuckler dedication with Finishing Precision archetype feat.

**Comment by stwlam** [comment]
Closed by #3627
