### ISSUE TITLE
Support weapon and armor automation on NPC sheets.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2188]
In GitLab by @jonbonazza on Apr 1, 2022, 19:32

Unlike with Player Characters, if you create an NPC and give it weapons and armors in their inventory, there's no way to automate them. You always need to create the Strike actions manually and there's no automation around things like ammo consumption #2189.

**Comment by TikaelSol** [comment]
This has been implemented for weapons now, armor isn't really feasible to implement. Closing as completed / won't fix.
