### ISSUE TITLE
Feature Request: option to disable the damage/healing notifications in main chatlog entirely

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2196]
In GitLab by @esheyw on Apr 3, 2022, 14:34

https://i.imgur.com/LEe0Suq.png these guys. I see them as just clutter, especially with the use of a module like [Damage Log](https://github.com/cs96and/FoundryVTT-damage-log) which puts equivalent information on a separate tab.

**Comment by esheyw** [comment]
re: https://github.com/cs96and/FoundryVTT-damage-log/issues/19, if we can't get an option to toggle, could we at least get the messages tagged in such a way that modules could mute them?

**Comment by MorfeuRS** [comment]
I would like to endorse this request.

**Comment by DariusWolfe** [comment]
Count me in for the suppress damage messages support crew.

**Comment by apoapostolov** [comment]
My groups would definitely benefit from less bloat. The only case where the post is useful, however, is when there's a shield applied and the string will properly inform the players that their shield is now broken or destroyed.

**Comment by roguedevjake** [comment]
Putting my vote behind this as well. A pretty big pain and the chat log is cluttered enough as is.

**Comment by roguedevjake** [comment]
For anyone interested, if you do a simple search and replace for the following in **main bundle.js** it will remove the messages

You would need to do it when there are updates... But... it is an option and works for now

`await chat_message_1.ChatMessagePF2e.create({speaker:{alias:token.name,token:null!==(_e=token.id)&&void 0!==_e?_e:null},content:`<p>${statements}</p>`,type:CONST.CHAT_MESSAGE_TYPES.EMOTE,whisper:game.settings.get("pf2e","metagame.secretDamage")&&!(null===(_f=token.actor)||void 0===_f?void 0:_f.hasPlayerOwner)?chat_message_1.ChatMessagePF2e.getWhisperRecipients("GM").map((u=>u.id)):[]}),`

**Comment by esheyw** [comment]
Well, these are useful twice over now (record of IWR, and the undo button) so I'd close this issue if I was still owner of it. Damage log is mostly redudant for me now.
