### ISSUE TITLE
Suggestion: Extend current drag-and-drop wand creation functionality to "metamagic" wands

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2209]
In GitLab by @silvative on Apr 5, 2022, 10:56

There is a common misconception (stemming from loot distributed in early APs) that metamagic wands only contain the metamagic itself, which can then be applied to any spell. This is presumably partly because the fact that metamagic wands hold a spell of their own is not explicitly stated within the item description, only in the surrounding rules text. However, the Wand trait and rules clarify that all wands contain a spell of an appropriate level- the only difference between the basic "Magic Wand" item and the so-called "metamagic wands" is that they also enhance the spell in a specific way. As such, it stands to reason that our current wand creation functionality could benefit from being extended to enable easy creation these other kinds of wand.

Specific wands, of course, should remain discrete items, as they have clear mechanical differences which set them apart.

**Rules reference**:

Wand rules: https://2e.aonprd.com/Rules.aspx?ID=756

Wand trait: https://2e.aonprd.com/Traits.aspx?ID=164

Wand of Widening: https://2e.aonprd.com/Equipment.aspx?ID=373

Wand of Continuation: https://2e.aonprd.com/Equipment.aspx?ID=369

**Comment by Shandyan** [comment]
Related to #2251

**Comment by KSops** [comment]
Just wanted to check that widening and continuation are the only two specialty wands this applies to right?
