### ISSUE TITLE
Disability Options

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2210]
In GitLab by @MrVauxs on Apr 5, 2022, 12:41

The Foundry system currently has no official way to handle the Disability rules from the Core Rulebook, shown [here](https://pf2etools.com/quickreference.html#bookref-quick,0,characters%20with%20disabilities,0).

My current solution is as Bonus Feats, but I get if a more specific solution is preferred. Active Effects are rather prone to deletion though, so I'd advise against that.

Certain items also should alleviate the penalties induced by such disabilities, like [Basic Corrective Lenses](https://pf2etools.com/items.html#basic%20corrective%20lenses_lotgb) should remove penalties from poor eyesight. Attached are examples of rule elements needed to have such effects.

Glasses
`{
    "domain": "all",
    "key": "RollOption",
    "option": "corrective-lens"
}`

"Vision Impairment" bonus feat
`{
    "key": "FlatModifier",
    "selector": "perception",
    "value": -2,
    "predicate": {
        "not": ["corrective-lens"]
    }
}`

The above example has been given by Tikael, in a discussion about this potential feature. You can read the beginning of it [here](https://discord.com/channels/170995199584108546/697845559435853865/960925961992429598) (Discord Link).

**Comment by stwlam** [comment]
There are no concrete rules here to implement.
