### ISSUE TITLE
Integrate the PF2e Ability Score Manager into the system

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2211]
In GitLab by @MrVauxs on Apr 5, 2022, 12:49

It is (most likely, I only have my own experience to support this) widely accepted that the [PF2e Ability Score Manager](https://gitlab.com/pearcebasmanm/pf2e-abs-manager) is, if not a must-have, a heavily wanted module to have in a PF2e game. Including the fact that the module has not been updated for 3 months, I believe it should be added to the main system to maintain compatibility and add features that are otherwise left in the modules Issues page.

Currently, the module has the core basics of being able to correctly apply ability boosts and penalties based on the rules given in the Core Rulebook, with the addition of the optional 2 penalties : 1 boost rule.

This though does not include the ability to use variant rules for statistics, such as [Gradual Ability Boosts](https://gitlab.com/pearcebasmanm/pf2e-abs-manager/-/issues/4). It also does not warn or prevent the user from having [less boosts than they should have](https://gitlab.com/pearcebasmanm/pf2e-abs-manager/-/issues/5).

**Comment by SpartanCPA** [comment]
We have a Ability Score Manager in core now. Closing
