### ISSUE TITLE
[bug] Rich text editor in Journal entries does not span entire window size

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2235]
In GitLab by @Valyar on Apr 19, 2022, 03:34

The rich text editor in Journal entries does not span the whole window, limiting the usage on big screens and requiring a lot of scrolling for text entries. 

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/fc21cc9f9b6ae53bd6764414372c3e33/image.png)

**Comment by TikaelSol** [comment]
Closing as the text editor and journals have been completely redone with v10.
