### ISSUE TITLE
Use localized labels for skill variants in NPC Sheets

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2253]
In GitLab by @dwim on Apr 29, 2022, 07:13

At this point of time, skill variants in NPC sheets are still displayed in English using the skill variant label. If we click on the variant, we can see in the chat that the label is already translated in the base system though.
![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/54d41c9ffbc9e3d1bb770eada0bb3f59/image.png)

If we try to translate the label (using Babele and targeting the Sheet item), the button to roll the skill variant does not work anymore unfortunately.

Suggestion : use the localized label (which already exists) in the NPC Sheet for Skill variants (as it's already done in the chat).

**Comment by Far2Casual** [comment]
This has changed and is now doable, it can be close @cswendrowski
