### ISSUE TITLE
PFS Season 1 Bestiary Inventory Brushup

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2271]
In GitLab by @nullwolf on May 4, 2022, 08:59

The NPCs in the image need to have their Inventory updated to actual equipment. At least 2 of the spellcasters also have some oddities in their Spells. (I will double-check and comment on which ones those are.)
Tagging @TMun 

Link to #1601 

![S1-Inv-Brushup](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/d4478dd4819b8f509dfe9f641de180f6/S1-Inv-Brushup.JPG)

**Comment by TikaelSol** [comment]
PFS brushup has been completed.
