### ISSUE TITLE
Spitting Zombie creature family ability lacking rule elements to grant ranged strike

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2272]
In GitLab by @Syven on May 4, 2022, 14:39

Some of the other abilities in this compendium have rule elements that grant strikes or other action abilities, and the "(Zombie) Spitting Zombie" item is missing rule elements that do the same.

**Comment by TikaelSol** [comment]
I think if there is an ability in the creature family abilities that grants a strike with an RE that is likely something we should move away from. Editing REs to edit the details of a strike is more cumbersome than just creating the strike directly when making a new NPC.
