### ISSUE TITLE
Feature Request: Add Time Elapsed next to Round Counter

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2296]
In GitLab by @bland-html on May 16, 2022, 24:16

Foundry staff suggested this might be better as a system feature.

### Feature Summary

Showcase the time elapsed next to the round counter. This would help improve tracking ability while minimizing module dependency.

### User Experience

Instead of just showing Round 2, it could show Round 2 - 00:06. If needed, users could have a setting to input how much time 1 Round is equal to or just disable it altogether. As rounds move forward, the timer simply elapses however much time the setting is set to.

Ex. Setting - 1 Round = 6 Seconds. Round is currently Round 2. Timer shows 00:06. When Round 3 happens. Timer shows 00:12.

### Priority/Importance

Right now there are a crap ton of things to track. I think adding a simple visual Time Elapsed counter will help many DM's and Players make quicker decisions when considering durations of many different effects. Sometimes messing around with many modules slows down gameplay significantly. Simplistic visual information is always helpful at reducing this.

Since you can have multiple Encounters, this function would also essentially allow an Encounter to act as a makeshift Time Tracker. This would help reduce module dependency as well.

**Comment by DocSchlock** [comment]
Durations are now tracked automatically. Closing.
