### ISSUE TITLE
Add third free ability boost to two backgrounds

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2324]
In GitLab by @MrVauxs on May 30, 2022, 12:28

See the Title, below is the JSON to add to [Discarded Duplicate](https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/blob/master/packs/data/backgrounds.db/discarded-duplicate.json) and [Amnesiac](https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/-/blob/master/packs/data/backgrounds.db/amnesiac.json).
```json
            "2": {
                "value": [
                    "cha",
                    "con",
                    "dex",
                    "int",
                    "str",
                    "wis"
                ]
            }
```

**Comment by TMunsie** [comment]
Resolved by #2731
