### ISSUE TITLE
Voidglutton and Will-o-Wisp tokens are not glowing (missing a Rules Element)

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2329]
In GitLab by @itamarcu on Jun 1, 2022, 06:42

The Flickerwisp tokens are all glowing, but the Voidglutton and two Will-o-Wisp tokens are not.

I suggest adding an additional "Light turned off" effect or toggle to the NPC sheet. For example, these two REs for the Voidglutton:

```json
{"key":"TokenLight","value":{"animation":{"intensity":1,"speed":3,"type":"pulse"},"bright":30,"color":"#fff9a3"},"predicate":{"all":["glowing"]}}
```

and

```json
{"key":"RollOption","label":"Glowing","domain":"all","option":"glowing","toggleable":true,"value":true}
```

(issue [originally posted to the AV module tracker](https://gitlab.com/foundrynet/pf2e-abomination-vaults/-/issues/33), moved to be here instead)

**Comment by TMunsie** [comment]
The dread wisp should also be included

**Comment by avagdumortesin** [comment]
I have updates on the Flickerwisp, Voidglutton, Dread Wisp, and Will-o'-the-Deep; what is the second Will-o-Wisp token mentioned by the OP?

**Comment by leerhund** [comment]
> 

Groetan Candle maybe?
