### ISSUE TITLE
Parry exists as an Equipment Effect, but still needs an Action

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2331]
In GitLab by @sevenveils on Jun 2, 2022, 03:17

Currently there seems to be no consistent way to Parry except to drag the Equipment Effect over each round. The weapon's chat card shows the parry trait but doesn't include an Action, nor does the compendium. An Action that is tied to the effect is needed for the character sheet please. Thanks!

**Comment by TMunsie** [comment]
Parry is an effect in the equipment effect compendium that can be dragged onto the macro bar. Closing as solved.
