### ISSUE TITLE
Double Barrel Trait

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2333]
In GitLab by @AGulyaev12 on Jun 3, 2022, 01:21

Is there any way to automatically increase damage die for guns with double barrel trait ? Usually you need to go to the charsheet and mess with the gun's characteristcs back and forth.

**Comment by JDCalvert** [comment]
The new version of PF2e Ranged Combat has now been released!

**Comment by DocSchlock** [comment]
Double-Barrel implemented in [this commit.](https://github.com/foundryvtt/pf2e/pull/13773)
