### ISSUE TITLE
Mark for death (Assassins Dedication)

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2334]
In GitLab by @AGulyaev12 on Jun 3, 2022, 01:24

The action right now has only the description but neither the GM nor a player can drag'n'drop the effect onto a target. does the effect actauly exists and work ?

**Comment by TMunsie** [comment]
Presently this is the same as hunted shot. We can't use an effect that needs to know who two actors are. We could, similar to hunted shot, create toggles.
