### ISSUE TITLE
Horizontal scroll/pan support on character sheet (for vertical screens)

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2335]
In GitLab by @quirken on Jun 3, 2022, 01:31

This issue is not exclusive to mobile devices - it happens on vertical screens, too. Sure, 620 width windows are not super common, but if you're wanting to *just* see your character sheet, or are using PopOut or similar, it ought to have some sort of fallback, either reflowing, or the ability to scroll/pan horizontally.

I realize mobile support is not officially supported by Foundry VTT to begin with, but modules like [Mobile Improvements](https://gitlab.com/fvtt-modules-lab/mobile-improvements) and [Simple Mobile](https://github.com/Handyfon/simplemobile) go a LONG way to making this a viable option.

However, Pathfinder 2E Character sheets don't work on mobile (or narrow windows), due to being cropped rather than reflowing/resizing, and there being no way to scroll/pan horizontally. Presumably this same issue happens if you try to use foundry on a vertical monitor.

All that really would be needed is for a horizontal scrollbar to be enabled if there wasn't enough room to show everything. Sure, a full reflow/optimized character sheet would be better, but that's a helluva lot more work. Even a scaled-to-fit option that might cause tiny text or buttons would be preferable.

I've attached examples of desktop behavior, desktop with PopOut, and mobile. Curiously, PopOut does enable a few pixels worth of horizontal scroll, but not enough to access more content.

![charsheet_desktop](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/5d5f69fff8812ad19b5a5faf97bc161a/charsheet_desktop.png)

![charsheet_popout](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/477614f51bd20cc9a93346f2848fc854/charsheet_popout.png)

![charsheet_mobile](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/ea6396238e1dbbaef2fe5a01c4abccce/charsheet_mobile.png)

**Comment by stwlam** [comment]
Definitely never happening
