### ISSUE TITLE
Add performance check at Lingering Composition

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#2336]
In GitLab by @sambomb on Jun 3, 2022, 07:40

Just add the Performance check at the cantrip
`@Check[type:performance|dc:@self.level]`

**Comment by DocSchlock** [comment]
This was resolved [in this commit](https://github.com/foundryvtt/pf2e/commit/08db213a55222ba72762d5cb1a3ac681f39d8edc)
