### ISSUE TITLE
Uvuko is not listed in the domains journal entries

### ISSUE THREAD

**Issue by DoctorDankovsky** [foundryvtt/pf2e#2376]
Uvuko (https://2e.aonprd.com/Deities.aspx?ID=228), missing from lists of deities, in domains

**Comment by leerhund** [comment]
Can you explain where Uvuko is missing?

![image](https://user-images.githubusercontent.com/95336883/172403803-742a1e34-8faf-49f1-80dc-1739dbf7e72f.png)

**Comment by leerhund** [comment]
To be honest I didn't even know there was a Domains journal.
It looks like it hasn't been updated in over a year (as far as deities are concerned), probably before The Mwangi Expanse was released.

I'll run through and add those this evening.
