### ISSUE TITLE
Data question: How to implement different ancestry ability boosts/flaws based on heritage?

### ISSUE THREAD

**Issue by roquemore** [foundryvtt/pf2e#2402]
I'm looking at some third-party material where an ancestry has its ability boosts/flaws depend on the heritage that gets picked. What would be the most practical way of implementing this that's still using "real" ability boosts (so as to avoid future issues if/when an ability score manager is included in the system)?

**Comment by leerhund** [comment]
This might better be addressed on the PF2e Foundry Community discord's development-help channel.

https://discord.gg/JYbBUNmj

**Comment by Shandyan** [comment]
Closing, as this isn't an issue with the system.
