### ISSUE TITLE
Errata : Voice Cold as death feat

### ISSUE THREAD

**Issue by rectulo** [foundryvtt/pf2e#2449]
The feat level is 7 instead of 4

The feat is an archetype and a skill feat -> add archetype iin Feattype

**Comment by TMunsie** [comment]
This is a skill feat and already has an archetype tags. Feattype can only be one thing. All other tags are off of skills.

Level 7 is the correct level for this feat:
![image](https://user-images.githubusercontent.com/25963508/173257191-fc7b4cac-06e2-463a-bc72-128bc3d5497e.png)

Closing.
