### ISSUE TITLE
[Bug] Armor runes not working

### ISSUE THREAD

**Issue by MagicSale** [foundryvtt/pf2e#2472]
Hi there!

When building my new character I realized that the armor runes doesn't work anymore. If selecting a potency rune, they still show up the new select field for property rune, but doesn't calculate the new value of the armor nor do they provide the AC or RR bonus to character sheet.

Tried this in several environments and I'm sure that this worked in former versions, so I assume this is a bug.

Foundry v9 (269)
PF2e v3.10.4.11747
(all other modules deactivated)

![image](https://user-images.githubusercontent.com/9884340/173285874-cfb35e1a-1aff-4af6-967e-170237ee7172.png)

![image](https://user-images.githubusercontent.com/9884340/173286070-d21bf913-0083-40e3-b05e-4a8f4d99bb6a.png)

**Comment by leerhund** [comment]
As of current PF2e System version, Armor runes do not alter the price or Item level.

For the AC, make sure that the armor is Invested.

Armor not invested:
![image](https://user-images.githubusercontent.com/95336883/173301373-b67bdec8-e870-4c2d-a7d7-e5a4378b6912.png)

Armor invested:
![image](https://user-images.githubusercontent.com/95336883/173301467-2c6f89d1-d023-49d3-b2ac-e50e40f84a25.png)
