### ISSUE TITLE
Feature: Option to rename item based on fundamental and property runes, materials

### ISSUE THREAD

**Issue by apoapostolov** [foundryvtt/pf2e#2477]
A button in the item card that renames the item from the base name (Shortsword) to a name using all runes and materials (+1 Striking Flaming Cold Iron Shortsword) and vice versa by reverting the item to its base. The expanded name could be dynamic (update when runes and materials change) or be static and need updating via the same button.

**Comment by stwlam** [comment]
I'm not sure what's being requested here. Weapons are renamed automatically.

**Comment by apoapostolov** [comment]
@stwlam I haven't done this in a long time, and yes it does! I apologize for asking for something already developed.
