### ISSUE TITLE
Feature: RuleElement to apply prefix or suffix to its base item or actor

### ISSUE THREAD

**Issue by apoapostolov** [foundryvtt/pf2e#2478]
The RuleElement changes the name of the base item or actor by adding a prefix or suffix, with a priority value for ordering. This would allow for future functionality of items as containers for talismans and fulu, etc. having their names changed by the contained objects (i.e. remind that a talisman is attached to it) and allow for effects modifying the base name of an item (or even an actor).

**Comment by stwlam** [comment]
You can do that with an AE-like

**Comment by apoapostolov** [comment]
Please excuse my ignorance here, but what is AE-like in PF2? Is this a type of RuleElement?

**Comment by TMunsie** [comment]
Active-effect like rule elements. Their use is described in the wiki: https://github.com/foundryvtt/pf2e/wiki/Quickstart-guide-for-rule-elements#activeeffect-like
