### ISSUE TITLE
Barbarian Dragon Instinct does not provide damage bonus.

### ISSUE THREAD

**Issue by NergalV** [foundryvtt/pf2e#2508]
What it says on the tin. Other instincts do, Dragon does not.

**Comment by SpartanCPA** [comment]
Have you picked which color dragon instinct your character has?

**Comment by leerhund** [comment]
> Have you picked which color dragon instinct your character has?

Can confirm this is an issue. If you remove `"any":["battle-form","attack"]` from the Predicates of the Flat Modifier damage REs it works as expected.
