### ISSUE TITLE
Corrosive rune has a reference to a non-existent (regular) success note

### ISSUE THREAD

**Issue by bland-html** [foundryvtt/pf2e#2513]
Aesthetic Bug: Using **Corrosive** produces the following success message. 
![image](https://user-images.githubusercontent.com/90391706/173677339-3fa653fd-1887-4a59-b5c4-6ed25a288610.png)

Automation Bug:
Two-Handed with Property Runes don't increase the damage die on the damaging effects (ex. Holy/Frost/Flaming etc.)

**Comment by stwlam** [comment]
We'll get that note localized, but the two-handed trait doesn't affect property rune damage
