### ISSUE TITLE
Spell traditions aren't localized in chat cards

### ISSUE THREAD

**Issue by Far2Casual** [foundryvtt/pf2e#2522]
It looks like the school tags on spells are not using localized version in the chat. The other tags are translated well.

See here, "Plant" has been localized in french by "Plante", but Primal and Transmutation are not, despite being translated in the system.
This is how it looks in the chat:
![image](https://user-images.githubusercontent.com/63196064/173775448-1a6a24f1-61c1-4815-8190-636754f6ccbe.png)
This is how it looks in the object: 
![image](https://user-images.githubusercontent.com/63196064/173775823-ec75bf17-3805-4c5d-8540-445cd743fd39.png)

**Comment by Far2Casual** [comment]
Babele with the PF2-FR translation module. 
https://gitlab.com/pathfinder-fr/foundryvtt-pathfinder2e-lang-fr.

For example, the module has a translation for the Primal Trait here : https://gitlab.com/pathfinder-fr/foundryvtt-pathfinder2e-lang-fr/-/blob/master/module/lang/fr.json#L3844

**Comment by stwlam** [comment]
Fixed the spell traditions, but Transmutation is in fact being translated as "Transmutation" in that file.

**Comment by Far2Casual** [comment]
Thanks @stwlam !
