### ISSUE TITLE
Can no longer equip items on NPCs

### ISSUE THREAD

**Issue by blacktrench** [foundryvtt/pf2e#2537]
I can no longer equip any item on my npcs, this is as intended or a bug? (checked the changelog.md and did not see anything, sorry if I missed it)

If it is as intended can we re-enable the feature? It was useful for npc lighting using torches and lanterns (token light rules element)

If a bug I have disabled all other modules to confirm it is behaviour from pf2e alone.

thx!

**Comment by leerhund** [comment]
Equipping items on NPC inventories didn't actually change anything on their sheets previously.

**Comment by blacktrench** [comment]
it did for rules elements on the items, now I have to manually enable lighting effects on them instead just equipping a lantern, I could just create them as effects going forward instead but then I have the items for my pcs and effects for my npcs

So not the end of the world if it is not a feature anyone wants just a request to placate my OCD for doubling up my items directory lol

**Comment by leerhund** [comment]
> it did for rules elements on the items, now I have to manually enable lighting effects on them instead just equipping a lantern, I could just create them as effects going forward instead but then I have the items for my pcs and effects for my npcs

I can see that being a valid case for re-enabling the ability to equip items on NPCs. 
Hopefully one of the devs can take a look and make the call.

**Comment by leerhund** [comment]
Fixed by #2635
