### ISSUE TITLE
Spell strike does not work

### ISSUE THREAD

**Issue by belkasro** [foundryvtt/pf2e#2556]
some reason it cant find the code to do spell strike 

Uncaught (in promise) TypeError: strike.attack is not a function
    Spellstrike https://assets.forge-vtt.com/bazaar/modules/advanced-macros/v1.14.2/Macros.js line 172 > Function:250

**Comment by leerhund** [comment]
This isn't really a system issue, so much as a module / macro issue.

I recommend continuing here: https://discord.gg/KNeWc7NQ

**Comment by TMunsie** [comment]
Closing as not a system issue
