### ISSUE TITLE
REs should allow grip to be a predicate

### ISSUE THREAD

**Issue by avagdumortesin** [foundryvtt/pf2e#2582]
When attempting to access the grip of an item, REs will silently fail. I have tried predicating on `weapon:hands:2`, `hands:2`, and `weaponHands:2` without success. There are certain feats that require a one-handed or two-handed weapon; to automate these, we need the ability to predicate on the number of hands being used. This data is already being applied for the Change Grip option on the Actions tab (such as for 2-hand Dx weapons), but should be available in REs as well.

**Comment by stwlam** [comment]
Already present
