### ISSUE TITLE
Rules Engine: Predicates beginning with "target:*" always evaluate false for WeaponPotency key

### ISSUE THREAD

**Issue by joshua-baller** [foundryvtt/pf2e#2588]
After a fair amount of testing I'm pretty sure there is an issue with the WeaponPotency rules in conjunction with the "target:*" predicates. The issue is that these predicates are always false, even when the roll inspector shows them to be true. 

As a test case I placed an undead creature and made is flat-footed. I then applied a series of rules to a sickle and evaluated the results. These should all evaluate true for the test case given, 'true' being that the indicated bonus is applied to the roll. 

`{"key":"WeaponPotency","predicate":{"all":["target:mode:undead"]},"selector":"{item|_id}-attack","value":3,"label":"Potency vs Undead"} #false`
`{"key":"WeaponPotency","predicate":{"all":["target:trait:undead"]},"selector":"{item|_id}-attack","value":3,"label":"Potency vs Undead"} #false`

`{"key":"Striking","predicate":{"all":["target:mode:undead"]},"selector":"{item|_id}-damage","value":2,"label":"Striking vs Undead"} #true`
`{"key":"Striking","predicate":{"all":["target:trait:undead"]},"selector":"{item|_id}-damage","value":2,"label":"Striking vs Undead"} #true`
The same general construct works for 'Striking' and fails for 'WeaponPotency.' Testing of a few other 'target:*' predicates also failed. For example:
`{"key":"WeaponPotency","predicate":{"all":["target:condition:flat-footed"]},"selector":"{item|_id}-attack","value":4,"label":"Potency vs F-F"} #false`

Testing of a variety of other WeaponPotency rules suggests this works for non 'target:*' predicates. See:
`{"key":"WeaponPotency","selector":"{item|_id}-attack","value":3,"label":"Potency (control)"} #true`
`{"key":"WeaponPotency","predicate":{"all":["unarmed"]},"selector":"attack","value":1} #true, tested with fists`
`{"key":"WeaponPotency","predicate":{"all":["weapon:base:sickle"]},"selector":"{item|_id}-attack","value":3,"label":"Potency for this sickle"} #true `

**Comment by DocSchlock** [comment]
This was resolved at some point.

WeaponPotency can now predicate accurately on `target` options.
