### ISSUE TITLE
Blood hag firebolt missing range trait which defaults to 10ft range increment penalty

### ISSUE THREAD

**Issue by fraserstanton** [foundryvtt/pf2e#2637]
Note that AoN also is missing any range details.
The issue is that the PF2E in Foundry auto applies a 10ft range increment if there is no range trait.
![image](https://user-images.githubusercontent.com/85046656/174945146-aa9949bf-cb1d-48ac-a741-1933958f3659.png)

**Comment by TMunsie** [comment]
That we don't have it and that AoN doesn't have it is really because Bestiary 3 doesn't have it, so that's really a red herring. But we should default to infinite range, I suppose. @stwlam this is probably something for the auto-range code?

**Comment by stwlam** [comment]
Give it a biiig range
