### ISSUE TITLE
More "double persistent damage" rolls

### ISSUE THREAD

**Issue by gardeaz2** [foundryvtt/pf2e#2661]
The recent errata's reminder that persistent damage is doubled on a crit gave me this idea.

Critical hit damage rolls from bombs come with a Note that generates an Effect with double the persistent damage instead of the usual damage, which is awesome. I think this kind of feature should be extended to other cases of persistent damage when possible.

For example, Bloody Debilitation adds a Note to damage rolls that just references the Bloody Debilitation feat. From this feat, you can drag the 3d6 Bleed Effect onto a creature's token, which is neat (assuming you have the persistent damage module installed). But it would be cool if the damage roll created a 2*3d6 Bleed Effect on crits, similar to how bombs work. Or at the very least, the Bloody Debilitation feat can always have a 2nd "crit version" effect next to its regular effect, to make it easy to remember to apply double damage.

I assume there are other feats that could similarly be affected by this.

This principle should apply even without the persistent damage module, when the Effects are just Rolls instead.

**Comment by gardeaz2** [comment]
Wait, never mind about the Bloody Debiltation example. Apparently that damage does not get doubled on a crit, because that damage comes from the free action Debilitating Strike, rather than the actual Strike action itself.

**Comment by TikaelSol** [comment]
Closing, we've been using this as the rule for a while now so the system should be good for that errata as is. Let us know if you find specific feats or items that we have mistakes in.
