### ISSUE TITLE
Character sheet gets empty and only shows items

### ISSUE THREAD

**Issue by Luistorch** [foundryvtt/pf2e#2676]
After updating and activating the stamina variant option this happened.
![image](https://user-images.githubusercontent.com/28735690/175520793-869199bf-5de8-4fb4-a042-91be33651304.png)

**Comment by stwlam** [comment]
Would you mind providing your Foundry and system versions, along with any modules you're running?

**Comment by Luistorch** [comment]
![image](https://user-images.githubusercontent.com/28735690/175521761-f366ca54-08a2-40cb-8790-efb049122fbf.png)
Version 9
PF2: 3.11.3.7
![image](https://user-images.githubusercontent.com/28735690/175521895-929e7331-470f-4d70-a18a-970284e5e213.png)

**Comment by stwlam** [comment]
Try disabling the translation modules

**Comment by Luistorch** [comment]
Disabled both. Still happens. All Compendium NPCs are broken too
![image](https://user-images.githubusercontent.com/28735690/175522442-e8e39f7c-c74b-4f9e-afd1-a837bf5086ae.png)
![image](https://user-images.githubusercontent.com/28735690/175522561-3c3a14b0-0744-4f19-9f81-f6d3af26ccf0.png)

**Comment by Luistorch** [comment]
![image](https://user-images.githubusercontent.com/28735690/175523242-119c9549-9b84-4ae0-a706-06864028f100.png)
Seems like there is a problem with the Translations getting stuck

**Comment by Luistorch** [comment]
Solved. Restart the server, set it in english and it works.
