### ISSUE TITLE
Strange key in the re-en.json

### ISSUE THREAD

**Issue by rectulo** [foundryvtt/pf2e#2718]
I found a weird key in the re-en.json.
https://github.com/foundryvtt/pf2e/blob/9ea531b3f5d92f992d7903a4897ea3b986a792e5/static/lang/re-en.json#L703

All the other "poison related keys" are followed by the number of dice and the value 
They have the format *poison1d1.*
The format of this one is *poison**d**1d12*.

I think the **d** must be deleted. I'm afraid (if I do so) to break something elsewhere.

**Comment by stwlam** [comment]
You can kill the extra "d"

**Comment by rectulo** [comment]
I will
