### ISSUE TITLE
Latest changes to double shot and triple shot requires toggling DS before TS can be toggled

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#2747]
![image](https://user-images.githubusercontent.com/81383360/176068978-582b367e-e57e-4b0d-85ad-764cf1a5f229.png)
![image](https://user-images.githubusercontent.com/81383360/176068997-34fe2627-16ad-4c15-a466-53f9ceb506d0.png)

**Comment by stwlam** [comment]
![image](https://user-images.githubusercontent.com/106829671/176069118-6f4bb09e-297e-41bb-abed-1679813d1c5f.png)

**Comment by Symon-S** [comment]
I do know that it requires DS to use it, but seems a bit redundant to require double toggling.
But if this is the intent, then I guess it is what it is.
