### ISSUE TITLE
Voluntary flaw double-boosting dissalowed

### ISSUE THREAD

**Issue by Bolt7** [foundryvtt/pf2e#2763]
Using the voluntary flaws optional rule it's possible to take a stat boosted by the ancestry, add a voluntary flaw, and add the extra boost. This results in an overall +2 to the stat from the ancestry step, so is allowed by the rules. Eg: elf +2 int, vol flaw -2 int, vol flaw +2 int.
However the system prevents you from adding a voluntary flaw boost to a stat the ancestry boosts, or adding an ancestry boost to a stat the voluntary flaw boost applies to.

![image](https://user-images.githubusercontent.com/75871317/176342299-6c806b32-04e5-4cd4-bfee-0fd276bc0f73.png)

![image](https://user-images.githubusercontent.com/75871317/176342264-5b598eb5-cd8f-45c1-ab27-f955ca073f8f.png)

**Comment by TMunsie** [comment]
Per discussion on the discord, this case is nonsensical and a person who really wants to do it can manually do ability scores. Closing as wontfix.

**Comment by stwlam** [comment]
This isn't just a problem with two boosts and two flaws

**Comment by TMunsie** [comment]
Please provide a rational use case
