### ISSUE TITLE
PC size change leads to inconsistent item bulk calculation.

### ISSUE THREAD

**Issue by TehT** [foundryvtt/pf2e#2801]
Permently large PC calculates ALL gear as if they are large versions of the item. When polymorphed to a smaller creature items keep their "large" weight, and are now twice as heavy. 

Size change was applied with Rule Element
`{"key":"CreatureSize","value":"small"}`

Please view images attached. 

![image](https://user-images.githubusercontent.com/7915544/176915333-db1ed7f9-a31e-411c-9b1b-b8abcfca3e67.png)
![image](https://user-images.githubusercontent.com/7915544/176915423-583ece41-bd03-482c-ab84-2121aaef02da.png)

**Comment by TMunsie** [comment]
Is this actually wrong RAW? The polymorph trait says your items are absorbed into you, not that they are resized as well (CRB 635). I’m not saying you’re wrong, I’m just asking for a rules reference saying you’re correct.

**Comment by TehT** [comment]
From Humanoid Form:
"This transformation doesn't change your statistics in any way, and you don't gain any special abilities of the humanoid form you assume. You can still wear and use your gear, which changes size (if necessary) to match your new form. If items leave your person, they return to their usual size."

In this case, the items in question are already medium sized. The characters natural size is large, and he carries equipment in his backpack for other party members, but when he uses Change Shape (equivalent to humanoid form above) all items now weigh twice as much. Upon further examination, items seem to be the correct size category, but the weight increase is still applied. 

![image](https://user-images.githubusercontent.com/7915544/176918867-74ca92e8-b49e-4845-be83-032859f6a067.png)

**Comment by TehT** [comment]
To add to this, it does not appear like the items and size rules are applied correctly for large sized PCs either. 
https://2e.aonprd.com/Rules.aspx?ID=257
The large sized dragon ancestry PC should treat the shortbow as L bulk

**Comment by stwlam** [comment]
If this is from BattleZoo Dragons, you'll need to take it up with them. CreatureSize REs can temporarily resize equipment as well.

**Comment by stwlam** [comment]
Closing due to staleness and active issue at #2840
