### ISSUE TITLE
Magical Trickster doesn't apply sneak attack damage

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#2802]
In fact, the feat does not have any Rule Elements.
Although it's probably more difficult to go by the rule below, perhaps it should have a toggle instead?

> If your single spell leads to multiple separate damage rolls, apply your sneak attack damage only once per target.

**Comment by TikaelSol** [comment]
There is no way to add damage dice to spells currently so it will remain unautomated for now.

**Comment by TikaelSol** [comment]
Grouping all the spell system stuff under a single larger issue
