### ISSUE TITLE
Feat: Scare to Death Errata

### ISSUE THREAD

**Issue by Eregar43** [foundryvtt/pf2e#2823]
The Feat Scare to Death got a change in the last errata (https://paizo.com/pathfinder/faq): Page 266: Scare to Death's kill chances wound up being too high compared to its action cost and other abilities. Change the critical success to say "The target must attempt at a Fortitude save against your Intimidation DC. On a critical failure, it dies. On any other result, it becomes frightened 2 and is fleeing for 1 round. The critical failure effect has the death trait." Then remove the death trait from the feat itself, as creatures immune to death effects can still take the other consequences.

**Comment by leerhund** [comment]
Changes are in PR #2751 
Awaiting merge

**Comment by leerhund** [comment]
Closed by #2751
