### ISSUE TITLE
Items added to a creature while it is temporarily resized are also resized

### ISSUE THREAD

**Issue by OnkOnk** [foundryvtt/pf2e#2840]
I used the Enlarge RE for a medium PC `{"key":"CreatureSize","resizeEquipment":true,"value":"large"}` and it made the PC large and all equipment large. This massively increased the bulk the PC was wearing as it still calculates the bulk of large items as if they were medium size. I attached the actor if that is helpful
[fvtt-Actor-taker-of-life-2.0.txt](https://github.com/foundryvtt/pf2e/files/9037946/fvtt-Actor-taker-of-life-2.0.txt)

**Comment by stwlam** [comment]
The issue I'm seeing with the actor you posted is that some of its equipment is naturally large, which is getting resized to huge. I'm not sure we have a good solution to handle what you're trying to do, but we'll look into it.

**Comment by OnkOnk** [comment]
Intresting, I'm not quite sure what order I applied the equipment in (if I enlarged first, added later or the reverse) but the PC was originally a small sized PC.
