### ISSUE TITLE
Blade Ally is not automatically prompting Critical Specialization text

### ISSUE THREAD

**Issue by Unikatze** [foundryvtt/pf2e#2867]

**Comment by leerhund** [comment]
The following is from a Champ with the Effect: Blade Ally Disrupting Rune attached to his Longbow. They also have the Archer dedication, giving them Critical Specialization with the bow. It appears to be working correctly. What is the exact issue you're experiencing? This may be better troubleshot on the Discord: 

https://discord.gg/m4pSXFw6

![image](https://user-images.githubusercontent.com/95336883/177593931-71211c0b-f800-45bf-9a80-2ff99979ec11.png)

**Comment by leerhund** [comment]
> 

The second image is on a Bastard Sword, which he doesn't have Critical Specialization on. With Blade Ally you don't get the Crit Spec of th weapon, only the Critical effect of the Rune.

**Comment by leerhund** [comment]
Disregard prior comment. I misread something. Looking into this now.
