### ISSUE TITLE
Bug: Inspire Courage is affecting non-damaging spells.

### ISSUE THREAD

**Issue by leerhund** [foundryvtt/pf2e#2914]
![image](https://user-images.githubusercontent.com/95336883/178123599-7a62d211-7139-44ef-888d-ab96ef4fbf6d.png)

**Comment by CarlosFdez** [comment]
While we can do the damaging-effect predication that dangerous sorcery does to inspire courage, I'm wondering if it might not be better to not include status bonuses to damage period if there is no damage formula entries registered in the spell at all. I might just do that.
