### ISSUE TITLE
Feature Request: Lock Button/Toggle for Items/Feats in character sheet

### ISSUE THREAD

**Issue by morganmmerrill** [foundryvtt/pf2e#2918]
Trying to highlight text within feats (specifically) often times leads me to "grabbing" the feat and "throwing" it off of my character sheet. CTRL+Z does not undo this action. The best way that I can find to fix is to reopen the compendium the drag the feat back onto the sheet.
Highlighting text really helps me as I'm reading across all platforms. Having the option to lock "item" boxes that I definitely don't want to remove would be immensely helpful.

**Comment by CarlosFdez** [comment]
It might be nicer to do what we do with spells and restrict the dragzone to only the header, rather than doing a a lock button.
