### ISSUE TITLE
Ancestral Paragon not offering Elf / Orc feats to Half-Elf / Half-Orcs

### ISSUE THREAD

**Issue by leerhund** [foundryvtt/pf2e#2926]
Ancestral Paragon only lists the Half-Orc and Human feats when dropped on a Half-Orc.
Only Half-Elf and Human for Half-Elves.

**Comment by ebuckle** [comment]
I don't think there's a simple fix for this given how the traits for Heritage/Ancestries works.

This would require a difficult work around just for one interaction. Might just be easier to do the additional feat manually for now.

**Comment by leerhund** [comment]
Yeah, a cursory look around told me it wouldn't be a simple fix.
Maybe in a later iteration.

**Comment by MrVauxs** [comment]
The same happens when trying to search for ancestry feats. Only your main ancestry appears, not heritage, even if it's available in the filters.

**Comment by Myriade91** [comment]
Nimble elf is not available in the list. I generally add it as bonus feat and it's taken into account for the speed. Yet it's annoying. Half elves should have access to human, elf and half elf ancestry feats.

**Comment by stwlam** [comment]
Fixed by #8740
