### ISSUE TITLE
Adding the drained condition past drained 1 does not damage a character correctly.

### ISSUE THREAD

**Issue by sandersontavares** [foundryvtt/pf2e#2962]
As per the title. Easy to reproduce. Add drained 1, you take damage and lose max HP. Add more drained after that and you lose the max HP but do not take any damage.

EDIT: To reproduce, first get a character and damage them to a point where the gap between their current hp and their max is higher than twice their level, then apply drained 2.

**Comment by avagdumortesin** [comment]
I cannot reproduce this behavior.

Dev:

https://user-images.githubusercontent.com/55938242/178631777-c0ba2eca-a308-44f0-a384-3791be448805.mov

3.12.2.10:

https://user-images.githubusercontent.com/55938242/178632060-376ffab2-d253-4866-be49-b39a9a03aa2e.mov

**Comment by leerhund** [comment]
> I cannot reproduce this behavior.
> 
> Dev:
> 
>  Screen.Recording.2022-07-12.at.6.41.02.PM.mov 
> 3.12.2.10:
> 
>  Screen.Recording.2022-07-12.at.6.45.03.PM.mov

The problem is that the Lose Hitpoints RE is only triggering on Drained 1. It should trigger all the way down. So in the first example when you lower the Drained, they should remain as 53 Current HP.

**Comment by avagdumortesin** [comment]
Ah, if I mark the HP at below max, I see the behavior.

**Comment by sandersontavares** [comment]
Yes, sorry, I'll edit that to make it easier to reproduce for other people.
