### ISSUE TITLE
Mountain Stance is not capping dexterity bonus to 0

### ISSUE THREAD

**Issue by Ansrala** [foundryvtt/pf2e#2989]
Hello, I just noticed the mountain stance for monks states that "You have a dexterity modifier cap to your AC of +0"  This cap does not seem to be applied while mountain stance is on.

**Comment by SpartanCPA** [comment]
![image](https://user-images.githubusercontent.com/64166996/179361101-83598ffb-e122-4078-aad7-0d65dfd0f712.png)

I just created a test actor and it appears to work properly. Could you give us a screenshot of the issue?

**Comment by Ansrala** [comment]
This is one of my players I am trying to see if he managed to accidentally over ride something but here it is
![tokageyamaMountain](https://user-images.githubusercontent.com/3604111/179361236-2e39689a-da0a-4850-a9b2-abd40c723bd7.png)

**Comment by SpartanCPA** [comment]
Did they happen to erroneously take the `Mountain Quake` feat too early? That feat allows a dex cap of +2, but is a level 14 feat.

**Comment by Ansrala** [comment]
No but call having me check. He has taken Mountain Stronghold which increases his dex cap to  +1.   Looking to see if he has something else that increased it further.

**Comment by Ansrala** [comment]
I removed Mountain Stronghold and re added it to the sheet and now it is properly capped at +1.  Thanks for working through that with me.  sorry to bother you with it.

**Comment by SpartanCPA** [comment]
It's not a bother at all. Please continue to report anything that might be a bug. 

Closing
