### ISSUE TITLE
Feature Request: show the traits used in DC Rollable Buttons in the roll outcome

### ISSUE THREAD

**Issue by GMRobster** [foundryvtt/pf2e#3047]
It would be nice if you could see the traits used in the dc rollable buttons e.g. @Check[type:diplomacy|dc:20|traits:auditory,concentrate,emotion,exploration,linguistic,mental|showDC:gm|name:Coerce] in the outcome of the roll as well (like the skill action macros):
![skillissue](https://user-images.githubusercontent.com/109578550/180048451-3a82e4de-0688-4757-9e96-e58410d5b153.jpg)

**Comment by stwlam** [comment]
You can see them by inspecting the roll, but they aren't traits for the check.
