### ISSUE TITLE
Cannot apply two flaws to the same ability score

### ISSUE THREAD

**Issue by sirrus233** [foundryvtt/pf2e#3059]
There seems to be a bug in the (very shiny!) ability score UI. I think you should be able to take two voluntary flaws on the same ability, as long as that ability also gets an ancestry boost - right?
Example is a Goblin Druid:

From Ancestry: 
 \+ Dex
 \+ Cha
 \- Wis
Chosen boost:
 \+ Wis
Voluntary Flaw:
 \- Cha
 \- Cha
Boost from Voluntary Flaw:
 \+ Wis

System version 3.12.2.10

**Comment by CarlosFdez** [comment]
It seems voluntary boost and voluntary flaw to same ability was handled, but double voluntary flaw was not handled. We'll need to expose an x2 button after a flaw is set to double tap a flaw if valid.

**Comment by Xelalego** [comment]
RAW you can only apply two flaws to the same ability if that ability is boosted by your ancestry.  There are also more extreme edge cases in the paragraph on Voluntary Flaws, it may be beneficial to simply allow for manual numerical bonuses to be available as a step of the Ability Boost UI.

**Comment by TMunsie** [comment]
> RAW you can only apply two flaws to the same ability if that ability is boosted by your ancestry. There are also more extreme edge cases in the paragraph on Voluntary Flaws, it may be beneficial to simply allow for manual numerical bonuses to be available as a step of the Ability Boost UI.

This is why there is a fully manual mode. I don’t think we’re going to go much further on additional features. The voluntary double flaw is legal within the rules so that will be covered. More than that will be a hard no.
