### ISSUE TITLE
Add info about more results in the compendium browser search

### ISSUE THREAD

**Issue by rlach** [foundryvtt/pf2e#3087]
PF2e version: 3.12.2
Foundry: v9 269
Browser: Chrome 103.0.5060.134

When searching for too broad terms the compendium browser just cuts them off at some unspecified number of results.

Here Occult Spells level 1 and 2 ordered by level, we can see that L2 spells end at Remove Fear:

![image](https://user-images.githubusercontent.com/5655000/180605105-36cccc9e-71ed-4044-8d8d-6b72edaf7579.png)

But when you filter by only level 2 spells you can see that there is more:
![image](https://user-images.githubusercontent.com/5655000/180605258-4d2db5b0-b18c-4106-9160-92ac18906be6.png)

The issue with this is there is no way for the user to know this unless they happen to notice. This can be very tricky. For example is Warrior's Regret the last 2nd level Occult spell in existence, or maybe is it not, but something was just cut off from the list, because the user hit the search limit? Well, from those results you can't tell. 

This affects all tabs of the browser, not just the spell list, and sometimes it is very hard to sufficiently limit the results to not cut anything. The second example I gave is already on very reasonable filters - only commons, only one school of magic, only 1 level of spells and the user might already be losing data not even knowing about it. Or an user might be looking for Undead monsters, and not realize with the mixed results, that they are seeing only about 50% of the available monsters.

The compendium browser should show "Showing x out of y results" somewhere if anything was cut off. Pagination would be even better, but I imagine adding a simple text under or above results would be easier to get done. The text could, alternatively be near Clear all Filters button.

**Comment by stwlam** [comment]
Are you still able to reproduce this in V10?

**Comment by rlach** [comment]
I've installed test v10 and made test world. I get infinite scroller now in the results, so that's working great.
