### ISSUE TITLE
Publish PF2E system types as @types npm package

### ISSUE THREAD

**Issue by TheMasterGeese** [foundryvtt/pf2e#3088]
I'm developing a mix of system-agnostic and PF2E-specific modules. In order to access PF2E's typescript types for the latter, I need to check out the repo locally, run tsc, and copy them into my module.

Being able to accomplish this by installing a @types package would be easier to maintain, consistent with other node modules, and would make it easier for new PF2E module developers to get started.

**Comment by stwlam** [comment]
Sorry, but system types are intentionally not public and subject to breaking changes without notice.
