### ISSUE TITLE
Reorganize the Language selection window

### ISSUE THREAD

**Issue by gardeaz2** [foundryvtt/pf2e#3157]
Currently, the language selection window just lists all languages alphabetically, which can be confusing and overwhelming for new players who don't know what most of the languages are. While reorganization isn't a high-priority feature, I think it can be improved if it were formatted according to rarity, as done on [Archives of Nethys](https://2e.aonprd.com/Languages.aspx).

If we wanted to get even fancier, we could add a regional tag to any regional languages and a secret tag to druidic.

This post was inspired by this [document ](https://scribe.pf2.tools/v/YbhrfL2Z-guides-and-tables ) which organizes languages and other parts of the game and lore.

**Comment by TikaelSol** [comment]
I feel this is close enough to what was done with languages recently by tagging with rarity to consider it closed, or as closed as it is likely to get. For data entry purposes I would like to not change from alphabetical lists, as it's generally faster to quickly scroll to the right language and many NPCs know uncommon languages.
