### ISSUE TITLE
Custom Monster Creation Wizard

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#317]
In GitLab by @manituan on May 5, 2020, 13:47

In the NPC sheet have a button to pop up a Wizard that initializes most stats following the rules of the "Gamemastery Guide" book, pages [56, 72]

**Comment by TikaelSol** [comment]
This is handled in the PF2e Workbench module now. Potentially we could add that functionality to the system but we'll close this for now.
