### ISSUE TITLE
Compendium Browser Not Responding

### ISSUE THREAD

**Issue by steev42** [foundryvtt/pf2e#3206]
While working on a bunch of journal entries in which I am drag-and-dropping from the Compendium to the journal, I have twice today come across this issue.

It appears to occur when I minimize Foundry (currently operating in the server instance, not on a webpage).  When restoring, the active Compendium Browser no longer responds to any mouse clicks.  Other windows (journals, spell entries, monster entries) all work as normal.  Compendium Browser does respond to update requests; for instance, attempting to add a spell to a character via the character sheet's search will update the CB.

In order to restore access to the CB, I have to restart the server.

**Comment by dogstarrb** [comment]
When I run in to this issue I am usually able to restore function with an F5 refresh, rather than full server restart. Hopefully that can help until they can bugfix whatever is causing the freezes.

**Comment by stwlam** [comment]
Are you still able to reproduce this in V10?

**Comment by steev42** [comment]
I haven't yet attempted to update to V10, so I cannot say, sorry.
