### ISSUE TITLE
Psychic Focus Points

### ISSUE THREAD

**Issue by dogstarrb** [foundryvtt/pf2e#3216]
So aside from spells not having a way to indicate I've amped them, I have no way to track how many focus points I have unless I actually add a focus spell, which, as a psychic, I don't actually necessarily have. I see that I have a pool of 3, but the dots to track how many I have left don't appear unless I put a placeholder focus spell.

**Comment by TikaelSol** [comment]
This is expected behavior, closing.

**Comment by stwlam** [comment]
Addressed by #3232
