### ISSUE TITLE
Unleash Psyche Effect Coding.

### ISSUE THREAD

**Issue by CriminalMatrix** [foundryvtt/pf2e#3253]
Small issue on the coding for the effect for Unleash Psyche.  The effect restricts the additional damage to leveled spells yet there is no such restriction on the ability.  Cantrips are a subsection under the Psychic Spellcasting entry on page 10 of the Dark Archives and should also be eligible for the additional damage. (as long as they are from the psychic spellcasting feature but understand that is a bigger coding thing)

**Comment by stwlam** [comment]
Fixed in 3.13.4
