### ISSUE TITLE
My spells and spell effects compendiums are completely empty.

### ISSUE THREAD

**Issue by sandersontavares** [foundryvtt/pf2e#3279]
Disabled all modules and relaunched the world, zero console errors, I have no spells in my game.

![image](https://user-images.githubusercontent.com/7301818/182019475-ac01ccc0-9ecb-4901-a44f-db0fde36f80b.png)

**Comment by sandersontavares** [comment]
Reinstalling solved it, so I'm not sure I should close or let you guys investigate causes. Probably a bad update.

**Comment by stwlam** [comment]
Closed as upstream issue
