### ISSUE TITLE
Circle templates under-highlight area when used as emanation and grid size ends in 5

### ISSUE THREAD

**Issue by Geekswordsman** [foundryvtt/pf2e#3281]
**Foundry Version**: 9.269
**PF2E Version**: 3.13.4.15

**Problem**:
When the grid size for a map ends in 5 (75, 95, 125, etc), placing a Circle Template causes the wrong area to show as affected.

**Steps to Reproduce**:
Configure a scene to have a grid size that ends in 0 (for instance, 100).
Change to the template layer, and select circle template.
Place a 5' circle template on the canvas in the middle of a square, note that the affected area is every square around the center (total of 9 squares).
![Expected Result](https://user-images.githubusercontent.com/41522046/182024516-aa604fd1-deee-42b8-8180-c7384af5b1f6.jpg)

Change the scene to have a grid size that ends in 5.
Place another circle template in the middle of a square, note that the affected area is only the square it was placed in plus 3 others to the right and down (total of 4 squares).
![Bugged Result](https://user-images.githubusercontent.com/41522046/182024522-ba9ba950-2c65-4d03-baf7-e7f2a2f463e5.jpg)

**Comment by ebuckle** [comment]
From a first glance, it seems like this is being shaped as a burst instead of an emanation. 

If I had to guess, the system knows to be an emanation if the source of a template is in the center of a grid square. So being a multiple of 5 (or maybe any odd number) prevents this.

**Comment by TikaelSol** [comment]
This is something with all odd pixel grids and is a core Foundry issue I believe.

**Comment by Geekswordsman** [comment]
Not quite; I was not able to replicate this in DnD5e, Call of Cthulhu or PbtA.  Only pf2e treated the affected areas differently between grid sizes.

**Comment by stwlam** [comment]
This is a system bug, but a fix will have to wait for proper emanation support (other than auras). That should happen shortly after V10 is released.

**Comment by stwlam** [comment]
I think this might actually be fixed now? I tested it with 95px grid size, and highlighting had the correct coverage.
