### ISSUE TITLE
Unable to set homebrew Base Weapons as Favored Weapon for deity item

### ISSUE THREAD

**Issue by Hexygon** [foundryvtt/pf2e#3354]
**Foundry Version:** 9.269
**PF2E Version:** 3.13.5.16

**Problem:**
Setting a Base Weapon in the homebrew menu doesn't show it as a valid Favored Weapon within a deity item. Discussed with @CarlosFdez on the PF2e FVTT Discord, and they mentioned how "The property is called baseWeaponTypes internally, but the homebrew menu edits baseWeapons [...] I think it got renamed when the deity sheet was created."

**Steps to Reproduce:**
Go to Game Settings > System Settings > Manage Homebrew Elements
Add a custom Base Weapon (also tried adding it as a Weapon Group, but it should be a Base Weapon)
![image](https://user-images.githubusercontent.com/61675976/182902901-400fbfb2-db7f-4cfa-8e69-15e8f40e2402.png)

Within a deity item, try to set Favored Weapon entry as the new Base Weapon, but it doesn't show as an option
![image](https://user-images.githubusercontent.com/61675976/182903524-85bfe164-91c7-4c3b-9fcd-0539bad39deb.png)

**Comment by stwlam** [comment]
Fixed at some point :shrug:
