### ISSUE TITLE
Chakram seems to be handled as a melee weapon, should only be ranged

### ISSUE THREAD

**Issue by thevortex42** [foundryvtt/pf2e#3369]
Equipping a Chakram to a character gives them a melee and ranged strike with it. The Chakram is a purely ranged weapon, though, and should only have a ranged attack. It is for some reason in the knife group instead of the dart group, which might be part of what causes the error. All other weapons in the knife group are melee, some of them with the "thrown X" trait (X usually being 20 ft.). The Chakram on the other hand is just a ranged weapon with range 20 and the thrown trait. Just like things like the Javelin or Dart.

**Comment by SebastianH17** [comment]
After digging some more into this, it seems like the Chakram from The Grand Bazaar and the Tamchal Chakram from AV are mixed up, the former shows a melee attack where none should be, and the second one only lists a ranged attack despite being a melee weapon.

**Comment by Eregar43** [comment]
It looks like it is based on the Weapons Group. Darts never get a melee entry, but knifes do. And the Chakram is classified as a Knife, the Tamchal Chakram as a Dart. A workaround would be to change that for now - the crit effects are the same for those two weapon groups.
