### ISSUE TITLE
Importing magus by drag'n'drop from the compendium browser end in "Inexorable Iron" imported even if other Hybrid Study was selected

### ISSUE THREAD

**Issue by DawidIzydor** [foundryvtt/pf2e#3397]
Steps to reproduce
1. Create a new Player Character actor
2. Search for magus on Compendium Pakcs tab
3. Drag'n'drop magus from the filtered list to the Player Character actor sheet
4. Select any Hybrid Study instead of Inexorable Iron
5. Go to Feat tab on the Player Character actor sheet, under Class Features the "Hybrid Study->Inexorable Iron" is listed instead of the selected Hybrid Study [bug]

**Comment by TikaelSol** [comment]
Unable to reproduce. There is a bug where if a selection is made quickly it will default to the first in the list, but it's been intermittent. Like this is related to that.
