### ISSUE TITLE
NPC attacks with variable damage types or effects

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#350]
In GitLab by @Shandyan on May 12, 2020, 05:23

Some high level monsters have variable damage types or effects, which needs to be considered if more automation is applied for damage types for resistances etc. 

For example, the pleroma does positive or negative damage with its standard attack; the warsworn can deal P, S or B damage depending on the weapon it uses; the guthallath can do improved grab or push with its fist; the terotricus can do improved grab or push with tentacles.

One possible solution is to make multiple versions of the relevant abilities (e.g. the pleroma would have 'Energy Touch (positive)' and 'Energy Touch (negative)).

This also relates to issue #318 (which describes damage that only affects specific targets).

**Comment by Shandyan** [comment]
Resolved by data entry practices
