### ISSUE TITLE
Switching "Ability Score Method" away from 'Custom' can accidentally lose data

### ISSUE THREAD

**Issue by mullr** [foundryvtt/pf2e#3515]
I was migrating forward a world that started before the fancy new ability score UI. I opened a character sheet and hit 'edit' on ability scores, and saw that "Use Custom" was checked, as I expected. I unchecked "use custom", then rechecked it, and the ability scores were all set to 10! This is an easy way to accidentally lose some pretty important data. It would be nice if the old values were remembered, even just transiently.

**Comment by stwlam** [comment]
You clicked this checkbox here?

![image](https://user-images.githubusercontent.com/106829671/184552070-88c8ec9a-2ecd-40ba-a73f-963a1ff0b98b.png)

**Comment by mullr** [comment]
That's the one. It was checked when I came in. I unchecked it, then re-checked it. That reset all the scores.

**Comment by stwlam** [comment]
Since it did exactly what it said it'd do, I don't think there's an issue here we can address.

**Comment by mullr** [comment]
My expectation was that it would put the ability scores back to the way they were initially, not erase them. I found the current behavior surprising; I had to go back to my notes and reconstruct one of my player's ability scores because of it.

**Comment by stwlam** [comment]
The "resets" bit turns out to be crucial. We can look at temporarily persisting the data, but the warning is pretty clear.

**Comment by mullr** [comment]
And no, I did not read the text under it. I did the first time I saw the UI, but evidently not the subsequent times. Despite the warning, it remains a sharp corner where I found it easy to cut myself.

**Comment by mullr** [comment]
Honestly, I would even be happy if it logged the old scores to the console or something. Just some way to back out after doing the wrong thing.
