### ISSUE TITLE
Specific familiar abilities

### ISSUE THREAD

**Issue by theJLUnit** [foundryvtt/pf2e#3551]
Just a way to input specific familiar abilities, maybe with a denotation that they don't count towards max abilities with a different icon. Right now a lot of those abilities are missing, for example the Aeon Wyrd has 0/4 of its abilities in there.

**Comment by leerhund** [comment]
I'm curious where it states that specific familiar abilities don't count towards their max?

**Comment by theJLUnit** [comment]
The Granted Abilities entry lists normal familiar and master abilities that familiar has. The familiar also gains unique abilities listed below the Granted Abilities entry. - APG page 148.

In the example of an Aeon Wyrd:
**Granted abilities:** aeon stone reservoir, can’t walk, constructed, crystalline, flier. Only Flier is an actual familiar ability therefore only this one is "locked" and counts towards maximum. Otherwise this familiar that would require 3 abilities would grant 5 abilities. 
**Unique Abilities:** aeon stone reservoir, can’t walk, constructed, crystalline are listed after Granted Abilities.

**Comment by leerhund** [comment]
Granted abilities: flier

Unique Abilities: all the others.

The Unique abilities don't count against the max. The Granted abilities do.

At the moment, the system doesn't care how many abilities you place on a familiar sheet. It will only show the mac based on your feats etc.

All you need is the ability to create the items to add to the familiar sheet. (I made these a while back, but talk was bandied around about changing how familiars worked so I never added them or did the others.)
![image](https://user-images.githubusercontent.com/95336883/185008804-f7d04421-3b09-4b19-8107-29d1a402634f.png)

**Comment by theJLUnit** [comment]
My verbiage was maybe a bit off, but I did say "a way to input specific familiar abilities" seeing as how Flier is not a specific one, it would of course count. We're on the same page here ;)

**Comment by TikaelSol** [comment]
Consolidating into #15858
