### ISSUE TITLE
@Check for a lore skill not rolling

### ISSUE THREAD

**Issue by theJLUnit** [foundryvtt/pf2e#3557]
If I set a check inside an action message to:
@Check[type:esoteric-lore|dc:@self.level|adjustment:2|traits:concentrate]
It doesn't roll. Nothing on a click.

If I change it to diplomacy as such:
@Check[type:diplomacy|dc:@self.level|adjustment:2|traits:concentrate]
It does roll.

**Comment by leerhund** [comment]
As long as the actor has the skill, it should roll. If they don't have the skill being checked, it won't roll anything.

![image](https://user-images.githubusercontent.com/95336883/185142512-d7f06e2f-982b-4dd3-b8f9-15b562a41765.png)

**Comment by TikaelSol** [comment]
The most likely culprit is TinyMCE injecting formatting text from copy/pasting. Check the HTML `<>` of the inline and remove any errant span tags.

Closing as non-repro
