### ISSUE TITLE
NPC Ability checks mislabel fortune rolls as misfortune

### ISSUE THREAD

**Issue by ChiefMilesEdgeworth** [foundryvtt/pf2e#3558]
Version: 3.13.5.16
No modules loaded. 

When rolling a basic ability check from an NPC sheet (Strength, Dex, etc.) and clicking "Fortune", the chat card with the roll instead says "Misfortune". The roll is treated as a fortune effect though, still keeping the higher roll. 

![2022-08-17-084115_294x175_scrot](https://user-images.githubusercontent.com/11009874/185129001-0745e6dd-1688-46be-9278-425f28bb5c12.png)

**Comment by TMunsie** [comment]
This is legacy, unmaintained code. Rolling skills is not a thing in the PF2e ruleset; I'm surprised this even survived. Skills used per PFS rules (say, acrobatics) use the new mode, which works correctly. This is either going to be a won't fix or deprecated entirely.

**Comment by ChiefMilesEdgeworth** [comment]
Ok. I'm new to Pathfinder, so I'm adjusting still. Where would you roll a skill that an NPC doesn't have (like say Athletics)?

**Comment by ChiefMilesEdgeworth** [comment]
I'm thinking about actions like Trip/Grab. As long as the base stats are there it's probably not a big deal, since I could just roll a d20 if the situation calls for it like you said.

**Comment by TMunsie** [comment]
You might want to read a bit about NPCs in the GMG. Unless you're playing an NPC as an idiot, if they aren't trained they're asking for trouble if they try to do combat manoeuvres against a party. You can follow untrained rules if you like for PCs, but it is still going to be a GM adjudication.

**Comment by ChiefMilesEdgeworth** [comment]
Ok, thanks so much! It probably would be good to deprecate rolling raw stats on NPC sheets then. I could make a PR if need be.

**Comment by stwlam** [comment]
Ability checks exist on NPCs because they use their ability modifier for any untrained skill check. It's a longstanding piece of technical debt that we're hoping to clean up soonish.

**Comment by asuffield** [comment]
Turns out to be an easy fix to the bug itself, even though this code looks like it should all just die
