### ISSUE TITLE
 Virtuosic Performer feat's rule element only applies the bonus to the Perform action

### ISSUE THREAD

**Issue by silvative** [foundryvtt/pf2e#3563]
### Issue

The rule element for the Virtuosic Performer feat currently only applies the bonus to Perform actions. I disagree with this interpretation of the rule, though it's not hard for me to see why it was read that way. I suspect this is based on the first highlighted sentence- "when making a certain type of performance"- being intepreted as "when you take the Perform action". However, I would argue this is incorrect based on the second highlighted sentence, which clarifies that the bonus should apply to all Performance checks.

![image](https://user-images.githubusercontent.com/66365038/185482645-bc2b69b9-1175-4bc3-9499-077767df8b65.png)

In my opinion, this is a simple misunderstanding caused by an action and a skill sharing almost exactly the same name. 

### Resolution

The recommended resolution would be to change the rule element on the feat to apply to all Performance skill checks.

**Comment by avagdumortesin** [comment]
> You have exceptional talent with *one type* of performance.

Emphasis added.

You gain a bonus for Performance checks with a single type of performance, which is why there is a Virtuosic Performance feat for each specialty. This is correctly implemented.

**Comment by silvative** [comment]
> You gain a bonus for Performance checks with a single type of performance, which is why there is a Virtuosic Performance feat for each specialty. This is correctly implemented.

None of this is relevant to the issue, which is that any performance check that uses that type of performance gains the bonus, not only performance checks that are made as part of the Perform action. 

The fact that the feat only grants you one specialty was never up for debate and is completely irrelevant.

> Nothing in the feat gives any indication that this applies to all Performance checks.

"Apply the bonus to Performance checks of that type" is the exact phrasing of the feat. You would be correct if it was phrased as "Apply the bonus to checks to Perform".
