### ISSUE TITLE
Error clicking on weapon attacks on iOS

### ISSUE THREAD

**Issue by Danmor425** [foundryvtt/pf2e#3570]
After the last JS modification the system works great even on iOS, the only problem I found is when clicking on a weapon attack as shown in the screen shoot.

![IMG_0299](https://user-images.githubusercontent.com/36131365/185649341-e1098e71-4354-4139-a151-ebed41c9d8c7.jpg)
!

This is the error in the console
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'canvas.tokens.controlled')
[Detected 1 package: system:pf2e]

I tried a little debug and found that tokens is not present inside canvas on iOS; on all the desktop browsers (including safari) is present.

I know iOS is not officially supported but it would be fantastic to have this little issue fixed.
Please let me know if I can help.

Thanks for the great work on the PF2e system

**Comment by stwlam** [comment]
A module is necessary for the canvas to function in Foundry. This isn't something the system can address.
