### ISSUE TITLE
When moving a spell from the Spell Prep sheet the sheet itself re-renders and posts Rendering SpellPreparationSheet in the console 

### ISSUE THREAD

**Issue by Varathiel1** [foundryvtt/pf2e#3586]
[FoundryAnimation.zip](https://github.com/foundryvtt/pf2e/files/9388126/FoundryAnimation.zip)

When dragging a spell from the Spell Preparation Sheet onto the Character Sheet's Prepared Caster Spellcasting Entry, the Spell Preparation sheet re-renders on top of the character sheet and the spell does not get added to the list.  Uploaded a zip of a GIF of the interaction above.

Console after 3 attempts, closing and reopening the Preparation list, then 4 more attempts:
<img width="392" alt="Rendering" src="https://user-images.githubusercontent.com/111665801/185769244-8bf6f686-5a5e-46d3-a627-676ab77235f6.PNG">

PF2e version:
<img width="734" alt="PF2eVersion" src="https://user-images.githubusercontent.com/111665801/185769232-16b7d047-5630-48a5-8701-e66071d5e926.PNG">

No active modules:
<img width="92" alt="ActiveModules" src="https://user-images.githubusercontent.com/111665801/185769239-e6941ad1-e03f-4e79-aa78-085664d6cbee.PNG">

**Comment by CarlosFdez** [comment]
You should be able to paste a gif directly and it'll play inline

**Comment by Varathiel1** [comment]
The gif was above 10 MB, so it wouldn't let me.

**Comment by ebuckle** [comment]
I'm not sure what the issue here is, there are no available slots to drag the spell onto so nothing happens
