### ISSUE TITLE
Devise a Stratagem not applying to Javelins

### ISSUE THREAD

**Issue by hitokiri1337** [foundryvtt/pf2e#3605]
Devise a Stratagem doesn't appear to be applying for Javelins, even though they're ranged weapons. Although they lack the agile or finesse traits, they are not considered melee weapons, so they should still apply.

![image](https://user-images.githubusercontent.com/38703108/186145306-0ddff883-f050-43a5-b558-38e476fb77bd.png)

**Comment by Symon-S** [comment]
As per [Devise a Strategem](https://2e.aonprd.com/Actions.aspx?ID=546) the thrown weapon still needs to have the agile or finesse traits.  `A ranged weapon (which must be agile or finesse if it's a melee weapon with the thrown trait)**`
So it seems to be working correctly.

**Comment by Symon-S** [comment]
Yep, you are correct, since it isn't a melee weapon with the thrown trait, it should work :thinking:
