### ISSUE TITLE
finesse melee weapons get dex as damage bonus with thief racket even when thrown

### ISSUE THREAD

**Issue by SarakinGH** [foundryvtt/pf2e#3623]
With Thief Racket finesse melee weapons get Dex as damage bonus even when thrown, when they should get Str in that case.

Quote from [Thief Racket](https://2e.aonprd.com/Rackets.aspx?ID=3):

> When you attack with a finesse melee weapon, you can add your Dexterity modifier

I modified the first rule element in the Thief Racket feat and it seems to work:
`{"ability":"dex","key":"FlatModifier","predicate":{"all":["weapon:melee","weapon:trait:finesse"],"not":["weapon:category:unarmed","thrown"]},"selector":"strike-damage","type":"ability"}`

![image](https://user-images.githubusercontent.com/51151248/186344992-34b8d8ff-dfdc-4fe0-8ac0-8b2c3d2b8a4e.png)

**Comment by stwlam** [comment]
Your screenshot shows it working as expected. I'm also not able to reproduce with Merisiel.

**Comment by SarakinGH** [comment]
Actually, you're right... Issue was based on a mention by another user on the discord...
