### ISSUE TITLE
Chakram has a variant strike, and Stiletto Pen and Tamchal Chakram are missing a variant strike

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#3626]
Chakram is a ranged weapon, but has both a melee and thrown variant.
Stiletto Pen and Tamchal Chakram are melee weapons with the thrown trait, but are missing the thrown variant.
There may be more, but these are the ones I noticed.
![image](https://user-images.githubusercontent.com/81383360/186353541-00cb16e5-e4c4-466b-bc8e-29de2b03cfbf.png)

**Comment by stwlam** [comment]
Your chakram is out of date. It looks like the tamchal chakram is getting coerced into a pure ranged weapon because it's a nonsense AP weapon (melee dart). We'll see about accommodating it.
