### ISSUE TITLE
HTML of resistances and immunities uses "data-weakness"

### ISSUE THREAD

**Issue by itamarcu** [foundryvtt/pf2e#3657]
I found this in the debugger of HTML elements when opening an NPC actor sheet:

![image](https://user-images.githubusercontent.com/6516621/186880561-36f40bb3-ed28-49fe-9aa9-85a503a6c6cf.png)

Apparently, all three of IWR use "data-weakness" - a misleading name, when only one is about weakness while the other two are about the opposites.

This bug doesn't affect users, but it confused me as a modder.

**Comment by stwlam** [comment]
Nothing is depending on it. If and when it's addressed, the entire section will be refactored.

**Comment by itamarcu** [comment]
Sure thing, when this refactor happens I'll just need to remember to patch https://github.com/itamarcu/pf2e-see-simple-scale-statistics

**Comment by stwlam** [comment]
Feel free to make a PR if you need it fixed for your module.

**Comment by shemetz** [comment]
Seems like this was fixed anyway! :]
