### ISSUE TITLE
Sniping Duo effect does not work with striking rule element

### ISSUE THREAD

**Issue by Drental** [foundryvtt/pf2e#3682]
(Sniping Duo Effect)
> {"key":"FlatModifier","predicate":{"all":["sniping-duo"]},"selector":"strike-damage","type":"circumstance","value":"1 + @weapon.data.data.runes.striking"}
Striking rule element is from the other weapon (dual wielding pistols with a blazons of shared power)

**Comment by KSops** [comment]
Can you elaborate on what's not working? Seems to work fine.

**Comment by Drental** [comment]
oh, I did not have time to elaborate here.

the issue is that the striking rune modifier that is applied by another rule element is not properly applied.

**Comment by TikaelSol** [comment]
Duplicate issue to #4148 

I'll close this one as that one is more descriptive of the issue.
