### ISSUE TITLE
Feature Req: Show N/PC Level in Actors list

### ISSUE THREAD

**Issue by jmoskie** [foundryvtt/pf2e#3688]
It would be useful if an Actor's Level was displayed in the list of Actors. 

Specifically, I'd love to have it when I'm designing an encounter with a set of known NPCs/monsters, and adding extra lackeys to help fill it out.

Something like this mockup, maybe?

![image](https://user-images.githubusercontent.com/3129389/187517058-ad40af32-18c3-4bb2-92a0-f58f581c036e.png)

**Comment by CarlosFdez** [comment]
I kinda like the idea but we'd have to look at popular modules. That location is where certain permission visibility modules put extra data for example.

Below the name is a better place if we were adding such data, probably instead showing `Level 7`

**Comment by sandersontavares** [comment]
Just wanna say, I love this idea and I support it becoming a core part of the system.
