### ISSUE TITLE
Character sheets broken (Foundry version 10 support)

### ISSUE THREAD

**Issue by jjsimpson** [foundryvtt/pf2e#3765]
I recently updated my Foundry to Version 10 (Build 284) and so far have noticed at least one major bug with pf2e (v. 3.13.6). None of the character sheets load properly (PC or NPC sheets, see attached screenshot). I had found a reddit post about this exact same issue from a year ago and it seems the solution at the time was they had updated Foundry but were not on a pf2e version that supported that Foundry version. Considering Foundry Version 10 is new and I'm on the latest version of pf2e I wanted to make sure you are aware of this issue. I see no errors in my logs when opening the character sheets and I can tell all of the information is there, they just don't render properly.
![P2_System_Character_Sheet](https://user-images.githubusercontent.com/13365910/188323217-68cd13c2-8f55-424a-94f5-a4747d767fb1.PNG)

**Comment by stwlam** [comment]
There's not a system version compatible with Foundry V10 yet. The warning you clicked through would have made that clear.
