### ISSUE TITLE
Request: Make DC module available to macros

### ISSUE THREAD

**Issue by tyrielv** [foundryvtt/pf2e#3771]
I have some custom macros that I want to make checks with level-based DC. It would be nice to have the DC module available at runtime to custom macros.

**Comment by tyrielv** [comment]
It looks like I may be able to meet my scenario for skill checks using the inline chat option "dc:@self.level" - but that doesn't work for saving throws, which is what I'm actually aiming for.

**Comment by stwlam** [comment]
Copy the code if you'd like, but this isn't public API.
