### ISSUE TITLE
Add sight-sharing mechanics to familiars 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#3797]
currently the issue is that the only way to know where your token is for familiars is to be near it. but when you want to use sense through your familiar you cant see unless you share party vision which isnt ideal and if your familiar has dark vision it gives you their dark vision in this mode. 

as it stands there isnt a seperate indicator for familiar vision.  as standard its either you see what your main token sees or the familiar. and if you loose sight of your familiar due to exploring. you cant click or find your familiar its just gone due to lack of sight on the token. which forces the gm to use shared vision. 

the ideal thing id like to see is you know where your familiar is at all times but you only see through their vision when you select the token

**Comment by TikaelSol** [comment]
Consolidating into #15858
