### ISSUE TITLE
Blinded automation to work with light sources.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#3798]
if you are in an area thats completley dark and the gm gives a player blinded so they cant see the player gets the expected restricted vision which is great but if you activate a light source say from a latern or something similar it doesnt auto cancel which leads the gm to think something is wrong from not cancelling the blinded condition. 

if we could have something that tells the blinded condition that it is being cancelled because it wasnt a spell condition and that it was deactivated by a light source that would automate that game process.

**Comment by stwlam** [comment]
It is intended that manually adding the blinded condition means it won't go away merely because there's a light source.
