### ISSUE TITLE
mark as defeated not removed when healed

### ISSUE THREAD

**Issue by Drental** [foundryvtt/pf2e#3806]
to reproduce: 
1. put an NPC in combat
2. roll a damage roll
3. apply damage until marked as defeated
4. use the heal button on the damage roll

the Defeated marker does not Disappear
Removing defeated on the combat tracker does not remove the skull overlay
removing the skull overlay removes the defeated state from the combat tracker

**Comment by stwlam** [comment]
It's dead, jim.
