### ISSUE TITLE
The PF2e's canvas layer subclasses do not call the correct `draw` and `tearDown` hooks

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/pf2e#3810]
For example, the lighting layer calls the `drawLightingLayerPF2e` and `tearDownLightingLayerPF2e` hooks instead of `drawLightingLayer` and `tearDownLightingLayer`.

The subclasses need to override either the `name` property or the `draw` and `tearDown` methods:
```js
// CanvasLayer#draw
async draw(options={}) {
    console.log(`${vtt} | Drawing the ${this.constructor.name} canvas layer`);
    await this.tearDown();
    await this._draw(options);
    Hooks.callAll(`draw${this.constructor.name}`, this);
    return this;
  }
```

**Comment by stwlam** [comment]
Bit of a core issue, isn't it?

**Comment by stwlam** [comment]
Closing as upstream issue
