### ISSUE TITLE
Alchemist Alchemy Crafting UI does not update selected formulas pane

### ISSUE THREAD

**Issue by Kuenaimaku** [foundryvtt/pf2e#3822]
When attempting to complete daily crafting as an alchemist, the panel containing currently selected formulas does not update until a new value is input for infused reagents, or if the checkboxes for "Toggle Free Crafting" or "Quick Alchemy" are toggled. 

The actions effected are drag-and-dropping known formulas to the crafting pane, adding or subtracting to the quantity to craft, toggling the signature formula state, and removing the formula from the crafting pane via the delete icon.

This was tested in pf2e 4.0.0-beta2 with 0 active modules installed. Below is a recording of the actor's crafting page with the console open to show any potential errors.

https://streamable.com/tg70ju

**Comment by ebuckle** [comment]
Thanks for the report, I'll take a look at this when I get a moment
