### ISSUE TITLE
Compendium Browser filters for empty feat slots

### ISSUE THREAD

**Issue by Sparkasaurusmex** [foundryvtt/pf2e#3835]
The Traits field is not auto populated when browsing the compendium via the search function from a blank feat slot.

**Comment by Sparkasaurusmex** [comment]
This does work from the Class Feats section, just not others.

**Comment by stwlam** [comment]
Closed by #3838

**Comment by Sparkasaurusmex** [comment]
This also affected skill traits in addition to ancestry traits.  Possibly general traits and archetype as well.

**Comment by Sparkasaurusmex** [comment]
Issue is not fixed, only for Ancestry feats.  Problem persists with other feat types.

**Comment by stwlam** [comment]
> Issue is not fixed, only for Ancestry feats. Problem persists with other feat types.

Can you specify the ones you tried and didn't work?

**Comment by Sparkasaurusmex** [comment]
Leveled up Ezran from the Beginner Box.  Ancestry and Class feats have a filter when trying to add from the search in the blank feat area (Ezran begins with an empty Ancestry Feat).  Achetype Feats, Skill Feats, and General Feats do not fill out the "Traits" field when searching from an empty feat slot in their respective categories.
