### ISSUE TITLE
Select NPCs Won't Open

### ISSUE THREAD

**Issue by dogstarrb** [foundryvtt/pf2e#3873]
![image](https://user-images.githubusercontent.com/7331744/189460648-754901e0-1103-4670-a383-80a77d542848.png)

Any way to recover these or am I going to have to rebuild affected NPCs from scratch? Most NPCs are not affected, but I cannot find what might have been in common between characters that are having this issue.

**Comment by CarlosFdez** [comment]
When a get a chance, please export the afflicted NPC JSON and we can start taking a look at it.

**Comment by dogstarrb** [comment]
How can I get it to you? github is telling me I'm not allowed to attach that file type and I don't have a way to zip, only rar

**Comment by dogstarrb** [comment]
Nevermind, I'm a fool. Attached.
[fvtt-Actor-alak-stagram.zip](https://github.com/foundryvtt/pf2e/files/9539367/fvtt-Actor-alak-stagram.zip)

**Comment by TikaelSol** [comment]
Alak and Calmont from the Age of Ashes compendium are broken on the system side it appears. Probably more.
