### ISSUE TITLE
Export to chat log does not include check type any more

### ISSUE THREAD

**Issue by JensChup** [foundryvtt/pf2e#3906]
When exporting the chat log (via the core foundry feature), the resulting log does not contain the type of check any more (which is in the message header)

Example:
![image](https://user-images.githubusercontent.com/85436512/189520281-fc146919-4680-4a55-bb16-536e8e415ac4.png)
will result in
```
[9/11/2022, 11:10:41 AM] Chomp
17
1d20 + 6 = 11 + 6 = 17
```

Previously, a perception check looked like this:
```
[3/13/2022, 5:27:42 PM] Bölefeld Blaumann
15
<h4 class="action">Perception Check</h4><div class="tags"><span class="tag tag_alt">Wisdom +1</span><span class="tag tag_alt">Expert +4</span></div>
1d20 + 5 = 10 + 5 = 15
```

It would be nice if this could be included again in some way.

_FVTT v10 Build 285
System v4.0.1_

**Comment by stwlam** [comment]
This is a change to Foundry itself, sorry.
