### ISSUE TITLE
Metagame Information Setting "Show results on attacks and saves" does not properly work

### ISSUE THREAD

**Issue by Exodil** [foundryvtt/pf2e#3931]
As title says, if the Limit Metagame Information setting 'Show results on attacks and saves' is set to GM the chat card does not display the result if the roll is made by a player (works fine if the GM rolls themselves)
However is the option 'All' is chosen, it works as intended.

No errors or warnings given in the console. 
Foundry Version 10
Build 285
Pf2e system version 4.0.3

Attached Image to demonstrate this.
Screenshot taken from GM client, both rolls made by player. Top roll with 'Show results on attacks and saves' set to 'GM', bottom roll set to 'All'. Made sure that the enemy was targeted on both rolls.

![image](https://user-images.githubusercontent.com/6171247/189672316-ba0847b9-58fe-4cbf-8928-79e3f0ef2345.png)

**Comment by CarlosFdez** [comment]
Just to be certain, can you try without modules? That thumbs up/thumbs down icon makes me uncertain. If you can reproduce it without any modules we can investigate.

**Comment by Exodil** [comment]
Thanks for the answer, the thumbs up/ down icon is actually from the system itself ('Critical Hit and Fumble Card Buttons')
But i deactivated the option for the sake of trying again. I also updated to the newest system version 4.0.4. The bug still persists

![image](https://user-images.githubusercontent.com/6171247/189859650-0d69c2bc-9ef3-41a1-872d-b2573927410a.png)
As you can see, same results. I included my module selection showing I have 0 active modules.
The screenshot was taken on 
Foundry V10 
Build 285
Pf2 version 4.0.4

The screenshot was taken on the GM client.
With the top roll made by the player with the option 'Show results on attacks and saves' set to 'GM', and the bottom one with set to 'All'
Hope this helps

**Comment by stwlam** [comment]
What are your for metagame info settings?

**Comment by mistamichal** [comment]
The same thing is happening for me, too.

**Comment by Exodil** [comment]
Metagame Information Settings as follows:
![image](https://user-images.githubusercontent.com/6171247/189865729-fe0e0956-3612-4e86-b26e-219f92b3af15.png)

I have also tried a completly new world with just a new PC character with minimal setup.
Same results
