### ISSUE TITLE
Persistent damage token icon uses wrong image path

### ISSUE THREAD

**Issue by Arnatious** [foundryvtt/pf2e#3939]
When adding persistent damage to a token, the icon attempts to pull `pf2e/icons/conditions/persistentDamage.webp`, which does not exist (instead named `persistent-damage.webp`.

It seems the condition itself points to the correct icon in it's object, the issue is during the `drawEffects` step, when calling `get temporaryEffects()`. The `ConditionTokenIcons` variable is populated with the wrong path.

**Comment by CarlosFdez** [comment]
Is this only with the persistent damage module, and with an updated version? What happens without the module?

**Comment by Arnatious** [comment]
This is without any modules, just the standard popout condition

Looking closer, it builds the icon path from `${condition.system.hud.statusName}.webp`, when the condition already has an img attribute pointing to the full, correct path.

https://github.com/foundryvtt/pf2e/blob/6655a0f2c2ed34d1e739aefe4168c20653f940bc/src/module/actor/base.ts#L217

Sample condition object
```js
Object { rules: [], name: "Persistent Damage", type: "condition", img: "systems/pf2e/icons/conditions/persistent-damage.webp", system: {…}, sort: 0, ownership: {…}, flags: {…}, _stats: {…}, rollOptionSlug: "persistent-damage", ...}
```
