### ISSUE TITLE
Soulsight (Sorcerer) produces validation warning

### ISSUE THREAD

**Issue by BernhardPosselt** [foundryvtt/pf2e#3942]
Steps to reproduce:
* Create an 8th level Sorcerer
* Pull in Soulsight (Sorcerer) feat into the lv 8 class feat slot
* Check warning output in dev tools

![Screenshot from 2022-09-13 00-30-24](https://user-images.githubusercontent.com/195053/189769886-b207a351-b180-45eb-a3a2-002657e3378b.png)

**Comment by redeux1** [comment]
Bard variant as well
![image](https://user-images.githubusercontent.com/22131782/189988496-bbc02f06-69b1-45fc-8d97-3f91786b7527.png)
