### ISSUE TITLE
Poppet Ancestry Immunities 

### ISSUE THREAD

**Issue by Affirmatron** [foundryvtt/pf2e#3983]
When selecting the Poppet Ancestry, it automatically sets the Construct type Immunities despite the Ancestry's mechanical information indicating simple +1 bonuses to several of the granted Immunities.

**Comment by stwlam** [comment]
![image](https://user-images.githubusercontent.com/106829671/190502119-fda3eef0-f3ba-4b67-97e9-46ec03d713a0.png)
