### ISSUE TITLE
Changing ITEM.TypeFeat to "Feat/Feature" in en.json creates incorrect naming on feat sheets

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt/pf2e#3984]
![image](https://user-images.githubusercontent.com/77904738/190290456-43012f40-91d2-4302-bac7-23d9bc8e8f43.png)

Ideally this should just say "Feat". Features still correctly display "Level". A separate localisation key for just "Feat" could easily be created, but I'm not sure where it'd go in `en.json`

**Comment by stwlam** [comment]
lmao how embarassing
