### ISSUE TITLE
Fatal Aim Wrong Description 

### ISSUE THREAD

**Issue by garzafd** [foundryvtt/pf2e#3994]
Fatal aim has a different description than that on the book, or [Archives of Nethys](https://2e.aonprd.com/Traits.aspx?ID=404)

**Comment by stwlam** [comment]
What's wrong about it?

![image](https://user-images.githubusercontent.com/106829671/190517486-f88249de-c47d-458a-97da-7186b0c8f85e.png)

**Comment by garzafd** [comment]
I have highlighted the sections that differ: 

It’s possible to hold the stock of this weapon under one arm so you can fire it with a single hand **as long as the other hand isn’t holding a weapon, shield, or anything else you would need to move and position, to ensure the weapon doesn’t slip out from under your arm. However**, if you use both hands, the weapon can make fatal attacks. When you wield the weapon in two hands, it gains the fatal trait with the listed damage die. Holding the weapon underarm stably enough to fire is significantly more complicated than just releasing one hand from the weapon, **so to switch** between the two grips, **you must do so with an** Interact action rather than Releasing or as part of reloading.

**Comment by stwlam** [comment]
It turns out to have two different descriptions in the same book:

![image](https://user-images.githubusercontent.com/106829671/190834436-73b738fb-be99-47bc-9089-365eb28ea105.png)

![image](https://user-images.githubusercontent.com/106829671/190834401-e2120e63-0fb4-4fdc-90d8-d220e61ec94d.png)
