### ISSUE TITLE
Invisible NPCs still completely visible to players

### ISSUE THREAD

**Issue by squirrelkiller** [foundryvtt/pf2e#4029]
Due to the basic hearing detection mode added in 4.0.1 invisible NPCs are always detected, as are NPCs in the dark. While this makes sense for some circumstances, it makes NPCs trying to hide completely unable to do so, such as those simply standing still. This ends up completely negating the effects of the new vision modes system.

**Comment by avagdumortesin** [comment]
With the hidden condition applied, others still know what space you're in, which is what the hearing detection shows. 

> While you're hidden from a creature, that creature knows the space you're in but can't tell precisely where you are. You typically become hidden by using [Stealth](https://2e.aonprd.com/Skills.aspx?ID=15) to [Hide](https://2e.aonprd.com/Actions.aspx?ID=62). When [Seeking](https://2e.aonprd.com/Actions.aspx?ID=84) a creature using only [imprecise senses](https://2e.aonprd.com/Rules.aspx?ID=412), it remains hidden, rather than [observed](https://2e.aonprd.com/Conditions.aspx?ID=27). A creature you're hidden from is [flat-footed](https://2e.aonprd.com/Conditions.aspx?ID=16) to you, and it must succeed at a DC 11 flat check when targeting you with an attack, spell, or other effect or it fails to affect you. Area effects aren't subject to this flat check.
> 
> A creature might be able to use the Seek action to try to observe you.

Now, if a creature is undetected, and has that condition applied to the token, the hearing detection does not show that the creature is in the square.

> When you are undetected by a creature, that creature cannot see you at all, has no idea what space you occupy, and can't target you, though you still can be affected by abilities that target an area. When you're undetected by a creature, that creature is [flat-footed](https://2e.aonprd.com/Conditions.aspx?ID=16) to you.
> 
> A creature you're undetected by can guess which square you're in to try targeting you. It must pick a square and attempt an attack. This works like targeting a [hidden](https://2e.aonprd.com/Conditions.aspx?ID=22) creature (requiring a DC 11 [flat check](https://2e.aonprd.com/Rules.aspx?ID=333)), but the flat check and attack roll are rolled in secret by the GM, who doesn't reveal whether the attack missed due to failing the flat check, failing the attack roll, or choosing the wrong square.
> 
> A creature can use the [Seek](https://2e.aonprd.com/Actions.aspx?ID=84) action to try to find you.
