### ISSUE TITLE
Feature Request: Stamina Resource Bar On Tokens

### ISSUE THREAD

**Issue by FolkvangrForgent** [foundryvtt/pf2e#4033]
With the addition of temporary hit-point resource bar adding support for the stamina rule by adding a resource bar to the tokens would be nice. I have been using Bar Brawl to accomplish this at the moment but internal support would be nice.

**Comment by stwlam** [comment]
Why not use the second bar for it?

**Comment by CarlosFdez** [comment]
Even built in, you could do this: 
![image](https://user-images.githubusercontent.com/1286721/190955656-50c9dbcc-e392-4afc-9bf8-b06deb19dfa1.png)

I'm a bit concerned about how the bar is going to look like if it splits 3 ways. Are you sure that's what you want?
