### ISSUE TITLE
Rules elements on read-only items don't allow close

### ISSUE THREAD

**Issue by steev42** [foundryvtt/pf2e#4065]
![image](https://user-images.githubusercontent.com/6807026/191117977-70cb16e7-933e-4823-97dc-4e0bb4fbbce8.png)

After expanding a rules element for an item from a compendium that isn't opening for editing, both the Close and Apply buttons are deactivated.  Close (without save) should be allowed to return to full Rules Element list.

**Comment by stwlam** [comment]
Need to make it not openable in the first place

**Comment by steev42** [comment]
@stwlam If you've selected the option to view them, I think it's fine to open them.  It can help to learn how they work (which is what I was doing with this one).

**Comment by CarlosFdez** [comment]
I can see an argument for it being in a read only mode. If its trivial to make that change I'll try it, but if its tricky I'll make it not openable in the first place.

**Comment by KSops** [comment]
https://github.com/foundryvtt/pf2e/pull/4519 I believe this fixes it?

**Comment by steev42** [comment]
Looks like you are correct @KSops.  I'll allow someone else to close, but I'm satisfied that it works properly now.
