### ISSUE TITLE
Multiple Attack Penalty

### ISSUE THREAD

**Issue by haste91** [foundryvtt/pf2e#4078]
Non-Player Character Actors multiple attack penalties only have 2 options recognized: Normal (-5/-10) and Agile (-4/-8). The weapon Traits determine this; if the attack has Agile, the MAP is changed to -4/-8. No other options are possible.

If you change the weapon MAP drop down in the Item details, this does nothing for an NPC Actor.

Can we get drop down options or blank fields to alter the Multiple Attack Penalties on second and third attacks when adding a new melee or ranged attack?

Thank you

**Comment by SpartanCPA** [comment]
The Agile trait is the only way to lower MAP natively for NPCs in the system (barring the Ranger's Flurry Edge). I don't believe we will be adding a dropdown to break RAW in the attack details.

For Homebrew monsters with lower MAP (such as homebrew Flurry Ranger NPCs), the [Multiple Attack Penalty](https://github.com/foundryvtt/pf2e/wiki/Quickstart-guide-for-rule-elements#multiple-attack-penalty) rule element works to reduce it correctly.

Not Hunted Prey
![image](https://user-images.githubusercontent.com/64166996/191399670-ceb40aad-b41c-48fd-add8-0c53bd9ae021.png)

Hunted Prey (Lower MAP)
![image](https://user-images.githubusercontent.com/64166996/191399735-46f99a78-506e-47c0-bcc1-0276b4496b89.png)
