### ISSUE TITLE
Unable to change showEffectPanel

### ISSUE THREAD

**Issue by Deviantyte** [foundryvtt/pf2e#4098]
Foundry v10 build 286
PF2 4.1.0
Active Modules: 0

- noticed in a new world that the condition panels in the top right weren't appearing when a token was selected
- verified that my settings and versions between the two worlds matched
- disabled modules in the old world to verify that the function wasn't being provided by one, panels still present
- inputting `game.user.settings` indicates `showEffectPanel` is set to false
- setting to true did not change the condition panel behavior

**Comment by stwlam** [comment]
Currently it takes a reload when you change the user setting. We can change it so the update takes immediate effect.
