### ISSUE TITLE
Feature Request: Chronoskimmer Dedication initiative-handling.

### ISSUE THREAD

**Issue by SunsetteSkye** [foundryvtt/pf2e#4107]
Chronoskimmer Dedication has a feature that lets you roll initiative in one of two special ways. Automating this process would significantly ease implementation in a game. Thank you.

**Comment by Drental** [comment]
You became partially unstuck from time and have learned how to manipulate your place in flow of time. When you roll initiative, you can choose one of three options: either do nothing and roll initiative normally, stabilize your timestream, or destabilize your timestream and send it into intense fluctuations. If you choose to stabilize your timestream, you don't roll initiative, and instead your initiative is equal to 10 + your initiative modifier. If you choose to destabilize your timestream, attempt a DC 11 flat check. On a success, your initiative is equal to 19 + your initiative modifier, and on a failure, your initiative is equal to 1 + your initiative modifier. Both stabilizing and destabilizing your timestream are [fortune](https://2e.aonprd.com/Traits.aspx?ID=76) effects.

Additionally, if your initiative roll result is tied with an opponent's initiative roll, you go first. Your manipulation of time grants you access to a number of abilities, some of which require a saving throw. The DC for these abilities is either your class DC or spell DC, whichever is higher, and is called your chronoskimmer DC.

just to have the text of it in the issue for reference.

**Comment by KSops** [comment]
Would it be sufficient to add roll option toggles for `[stable, unstable-success, unstable-fail]`?

**Comment by SunsetteSkye** [comment]
> Would it be sufficient to add roll option toggles for `[stable, unstable-success, unstable-fail]`?

Sure!
