### ISSUE TITLE
Better Hexagon Map Measument Templates

### ISSUE THREAD

**Issue by FolkvangrForgent** [foundryvtt/pf2e#4126]
The hex grid measurement templates are lagging quite behind when compared to the current square grid measurements. I would love to see improvement to the current hex grid measurements to better facilitate play on hex grids (hex grids being a variant rule briefly presented on page 14 of the GMG). The particularly problematic templates that I often run into are the cone and the circle which do not properly highlight what would be considered within a hex template. I have also found that the cone snaps to every 45° even on hex grid where it should snap every 30° and the internal angle should also be 60° instead of 90°. I would also love to see the wall collision feature brought to the hex measurement templates. I have attached a picture that I often reference for hex measurement templates and believe exhibits the de-facto measurement rules for hex grids.
![image](https://user-images.githubusercontent.com/25625121/191661388-7230672c-1100-4c2c-ba42-f0de1745cd8a.png)

**Comment by stwlam** [comment]
Unfortunately, there aren't fully defined hex-play rules, and the amount of unanswered questions left by the GMG are such that it isn't something we're able to build and maintain in the system implementation.

**Comment by CarlosFdez** [comment]
That said if someone wants to make a module for it and certain changes can be done to core to better facilitate it somehow (maybe exposing certain methods or restructuring code or something) feel free to hit us up.

**Comment by FolkvangrForgent** [comment]
Just want to note that I opened a commission for a module (in the league of foundry developers) as I currently am too busy and don't like js/ts so hopefully someone will take that up. If I or someone else was to have related core questions would the discord be the best place to reach?

**Comment by stwlam** [comment]
Making some small accommodations as specified here.
