### ISSUE TITLE
Token reveal Macros not working from AV module

### ISSUE THREAD

**Issue by MrChessur** [foundryvtt/pf2e#4129]
Foundry v10 Build 286
Pf2e 4.1.2
Abomination Vaults 1.2.0

Macros like Flickerwisp Reveal and Skeletal Giant do not execute properly because of a change in Pf2e data. Ones with tiles have a deprecation warning. These are with no other modules activated, just pf2e Abomination Vaults.

![image](https://user-images.githubusercontent.com/28309284/191753843-42a739f0-58b6-487e-bd9c-94885cdc2eae.png)
![image](https://user-images.githubusercontent.com/28309284/191754208-9f3f13c6-bef6-46c3-bc06-11b0a81f0217.png)

Changing the declared const also causes an error mentioning token.update is no longer supported. The weirdest part is the fact that you can get the macros to work if you install Advanced Macros and have it activated when executing the macro.

**Comment by stwlam** [comment]
Tracked at https://github.com/foundryvtt/foundryvtt-premium-content/issues/120

**Comment by Drental** [comment]
should have added "this worked in 4.1.0"
