### ISSUE TITLE
No way to disable hearing sense while using rules based vision

### ISSUE THREAD

**Issue by Lemming3842** [foundryvtt/pf2e#4172]
I'm not sure if this would be a good idea but here it goes. Currently it seems that hearing sense is enabled all the time for characters (or the border around tokens looks like hearing sense and deafened status removes these borders). This makes darkness immersion deteriorates since they will always "hear" tokens outside of vision range. I know per the rules token should be heard but maybe could be the last place where they heard it, or an area where sound were listened (but no specific position since it is an imprecise sense) or any kind of overruling this like for example, if a token is stealthing, it should make at least less or no sound.

The only way around I came up is setting the token deafened but this implies other rules and problems for other actions. Maybe make it enable/disable so when the players actively use hearing it can be toggled and disabled when needed, adding it as a section in the senses for the character sheet maybe?

**Comment by stwlam** [comment]
There will likely be additional solutions in the future, but you can give the undetected condition to anything you want to not be heard. There's also Foundry's GM-hiding tool in the token HUD.

**Comment by Lemming3842** [comment]
Oh ok! thanks for the input :) i'll try those options.
