### ISSUE TITLE
Cannot add weaknesses or resistances on a PC sheet

### ISSUE THREAD

**Issue by mullr** [foundryvtt/pf2e#4186]
1) Make a new PC actor
2) Click the '+' next to "Weaknesses" or "Resistances"
3) Chose some, and press the save button
4) The sheet should reflect the choices, but it does not. 

Immunities works as expected. 

Foundry: v10, build 286
PF2E: 4.1.3
Modules: None (all disabled)

**Comment by TMunsie** [comment]
Cannot replicate. Try on a new world. It may already be fixed in the development branch.

Closing.

![image](https://user-images.githubusercontent.com/25963508/192166132-0b627ee6-aa3d-4e61-9689-4c3ff5e3ea43.png)
