### ISSUE TITLE
Advanced Alchemy not upgrading for dedications

### ISSUE THREAD

**Issue by lyrrados** [foundryvtt/pf2e#4189]
![image](https://user-images.githubusercontent.com/46534231/192181185-de7df3d3-70fa-4bcd-91ce-3039a5cb66ef.png)
![image](https://user-images.githubusercontent.com/46534231/192181225-a7a8b2c6-dee5-4fdb-a826-c8666eae3f41.png)

Advanced Alchemy is not upgrading with the proper feats and levels, stuck at 1.  Verified that both Alchemist and Herbalist Dedications are affected, do not know if others that grant Advanced Alchemy are.

**Comment by KSops** [comment]
I think there's a I think there's a regression for this issue; I'm experiencing this in 4.7.2
Reverting the phase in related REs to "afterDerived" acts as a workaround.
