### ISSUE TITLE
Hazard Sheet Suggestions

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#421]
In GitLab by @JerkyGunner on May 24, 2020, 09:30

Thrilled to have hazards finally in the system!

That said it's time to make them perfect :)

- First suggestion would be to allow basic saves to be tacked onto their strikes when possible.
- Ability to put actions/reactions/attacks into whichever section of the Hazard sheet we like.
- Default icon that's more appropriate than the mystery man.
- Option to add rarity to hazards too (Uncommon/Rare/Unique)
- Space to add Perception and senses to hazards

**Comment by TMunsie** [comment]
Since #585 is open and a duplicate of what is missing, closing this one as remainder complete
