### ISSUE TITLE
Feature Request: Ability to change default compendiums that sheets pull from

### ISSUE THREAD

**Issue by zacdemon** [foundryvtt/pf2e#4221]
For those of us who use homebrew feats/deities/ancestries/backgrounds/classes it would be helpful to be able to change the default compendiums that the character sheets open when a player searches for one of the above options.

**Comment by CarlosFdez** [comment]
I can see potentially introducing flags for third party content to add additional ABCD compendiums to pull choices from.

**Comment by stwlam** [comment]
I think a simpler solution would be to have show a menu containing all options from all compendiums, which can be quickly narrowed from indexes

**Comment by CarlosFdez** [comment]
I forget that searching across all compendiums is fast enough nowadays.

**Comment by surged20** [comment]
Also interested in this. Could the compendium browser be reused here (with those new categories added)?

**Comment by MrZeyami** [comment]
Seconding this request.

**Comment by stwlam** [comment]
Specific compendiums are generally no longer targeted since since version 5.
