### ISSUE TITLE
Barbarian Animal Instincts do not apply Bestial Rage Traits, Specialization Ability, or Raging Resistance based on Animal Chosen

### ISSUE THREAD

**Issue by Kuenaimaku** [foundryvtt/pf2e#4226]
Foundry Version: 10.286
PF2E Version: 4.1.3
Active Modules: 0

While theorycrafting within Foundry with a Barbarian, I noticed that some of the sections of Animal Instincts do not update the actor depending on their level. 

- At level 1, Bestial Rage does not add the morph, primal, and transmutation traits.
- At Level 7, Specialization Ability is not applied. For Deer specifically, Antlers do not gain the Reach trait.
- At Level 9, Raging Resistance does not apply piercing and slashing damage.

![FoundryVTT Image of Deer Animal Instinct](https://user-images.githubusercontent.com/4933855/192693002-43c5bfd2-b639-47ae-94d6-c6dabdbd5faf.png)

**Comment by stwlam** [comment]
Are you still able to reproduce this?
