### ISSUE TITLE
Steel Skin archetype feat

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#4229]
Cannot add Sentinel Archetype Feat "Steel Skin" when using free archetype.

Warning emitted: 'Cannot add feat "Steel Skin" to Archetype Feats: feat type is invalid.'

Perhaps it should be:
"featType": {
	"value": "archetype"
}
rather than:
"featType": {
	"value": "skill"
}

https://2e.aonprd.com/Feats.aspx?ID=2063

<img width="497" alt="Screen Shot 2022-09-27 at 11 03 35 PM" src="https://user-images.githubusercontent.com/1904698/192700358-f771519b-7583-447a-a998-f3d695049f87.png">

**Comment by stwlam** [comment]
See https://github.com/foundryvtt/pf2e/wiki/The-CounterFAQ#free-archetype-and-archetype-skill-feats

**Comment by simonward** [comment]
Good catch. Thanks!
