### ISSUE TITLE
Greater thunder rune has wrong deafened duration

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#4247]
Up to now, I have only noticed Thundering (Greater), but I gave it a blanket label, just in case there were more. [Thundering Runes](https://2e.aonprd.com/Equipment.aspx?ID=306)
![image](https://user-images.githubusercontent.com/81383360/192956892-e5d005ed-51ba-4e64-8f3a-25163c1a9721.png)
![image](https://user-images.githubusercontent.com/81383360/192956463-71502a31-549e-4b87-8d6f-3639fdbb7e85.png)

**Comment by LebombJames** [comment]
What should it be?

**Comment by LebombJames** [comment]
Oh yeah, the DC, I see

**Comment by stwlam** [comment]
There is no mention of the thundering rune in any errata

**Comment by Symon-S** [comment]
It should be permanent for the Greater Thundering Rune on a fail

**Comment by LebombJames** [comment]
Yeah, this has nothing to do with errata, but still needs fixed
