### ISSUE TITLE
Beginner Box Skeleton Guards scimitars have bow descriptions.

### ISSUE THREAD

**Issue by Geekswordsman** [foundryvtt/pf2e#4253]
See attached image - incorrect description, and showing the scimitars having a range increment of 60ft.
![image](https://user-images.githubusercontent.com/41522046/193141837-83c1dcfa-9e1e-4582-ae4d-a2e17fcd42c0.png)

**Comment by stwlam** [comment]
How does it look when you import it?

**Comment by Geekswordsman** [comment]
The same - for instance, if you import the Beginner Box module it has the exact same description.
