### ISSUE TITLE
Unsupported Core Version 10.286

### ISSUE THREAD

**Issue by cmbernard333** [foundryvtt/pf2e#4288]
Recently I saw my Pathfinder 2e system version 4.1.3 was warning me about being on the wrong core version of FoundryVTT. I was on 10.285, so I updated to 10.286 and now it says it is an unsupported core version.

<img width="999" alt="image" src="https://user-images.githubusercontent.com/4392507/193377979-1f46d9d0-336b-4c6d-b8ba-a9ea692f57f7.png">

Here is a screenshot showing a game using Pathfinder 2e in FoundryVTT

<img width="999" alt="image" src="https://user-images.githubusercontent.com/4392507/193378028-ebec5766-0aab-4b31-b081-d4b3c7ad5500.png">

I checked `system.json` for the Pathfinder 2e system and it says verified 10.286. Is this an issue with PF2e or with FoundryVTT itself?

**Comment by stwlam** [comment]
It's a core Foundry bug. Restarting the server clears it.
