### ISSUE TITLE
Feature request: Esoteric Lore CHA

### ISSUE THREAD

**Issue by coboye** [foundryvtt/pf2e#4300]
Thaumaturges need a lore mod config for Esoteric Lore.
Unlike a normal Lore skill, Thaumaturge use Charisma as modifier on Esoteric Lore checks

**Comment by avagdumortesin** [comment]
The Esoteric Lore class feature already has this.

**Comment by stwlam** [comment]
Already done: you may need to get a new copy of the class feature (set PC level to 0 and back again)

**Comment by coboye** [comment]
Oh nice, the problem was the italian i18n "Esoteric**a**" wich suppress the condition i suppose:
![image](https://user-images.githubusercontent.com/3914689/193448675-c587e532-d57e-4faf-b5a4-2b4aa63897c1.png)

Thanks!
