### ISSUE TITLE
Bug: CheckPF2e.roll() no longer supports raw notes data

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#4305]
With the change to rolls being statistics for skills, certain macros have had to find creative ways to overcome the removal of the notes parameter. Which include injecting REs into feats, effects, etc. I am hoping that a notes/RE parameter can make a return, this will allow for temporary REs pertaining to certain types of rolls, which would be less intrusive.

**Comment by CarlosFdez** [comment]
Its not so much removal as it wasn't re-implemented.

**Comment by CarlosFdez** [comment]
I double checked, existing roll functions don't have a roll parameter. Strike doesn't have one, skill statistic modifiers don't have one, and RollParameters for old style rolls don't have a notes. What were you all doing then?

**Comment by Symon-S** [comment]
This is an example that is broken that Tik just posted
```js
const targets = game.user.targets;

if (!actor || targets.size != 1) {
  ui.notifications.warn("You must have an actor selected, and one actor targeted");
} else {
  const skillName = "Esoteric Lore";
  const skillKey = "esoteric-lore";
  const actionSlug = "action:recall-knowledge"
  const actionName = "Recall Knowledge"

  const modifiers = []
  let DCbyLevel = [14, 15, 16, 18, 19, 20, 22, 23, 24, 26, 27, 28, 30, 31, 32, 34, 35, 36, 38, 39, 40, 42, 44, 46, 48, 50]

  const [target] = targets

  let DC = DCbyLevel[target.actor.system.details.level.value]

  const notes = [...token.actor.system.skills[skillKey].notes];

  let options = token.actor.getRollOptions(['all', 'skill-check', skillName.toLowerCase()]);
  options.push(`action:${actionSlug}`);
  options.push(`secret`);

  game.pf2e.Check.roll(
    new game.pf2e.CheckModifier(
      `<span class="pf2-icon">A</span> <b>${actionName}</b> - <p class="compact-text">${skillName } Skill Check</p>`,
      token.actor.system.skills[skillKey], modifiers), {
      actor: token.actor,
      type: 'skill-check',
      options,
      notes,
      dc: {
        value: DC
      }
    },
    event
  );
}```

**Comment by CarlosFdez** [comment]
That has nothing to do with statistic nor skill rolls, that's a direct use of CheckPF2e.roll() which is what they use internally. On top of that, the example code you put seems to be trying to extract it from already registered notes on the skill itself rather than trying to add new ones to the roll. For notes already in the synthetics, actor.skills[skillKey].roll() should work just fine.

Also I tested and it seems to work fine.

**Comment by Symon-S** [comment]
Try this, which is what we used to be able to push into notes.
```js
const = notes = [{
  "selector": "performance",
  "text": "blah blah blah",
  "title": "Blah",
  "outcome": [
    "success"
  ]
}];
const options =[];
const modifiers = [];
 game.pf2e.Check.roll(
    new game.pf2e.CheckModifier(
      `<span class="pf2-icon">A</span> <b>test</b> - <p class="compact-text">test Skill Check</p>`,
      _token.actor.system.skills.prf, modifiers), {
      actor: _token.actor,
      type: 'skill-check',
      options,
      notes,
      dc: {
        value: 20
      }
    },
    event
  );```

**Comment by Symon-S** [comment]
Example from V9 can be found here [Marshal Stances](https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/V9/Marshal%20Stances.js)

**Comment by CarlosFdez** [comment]
Can you give some examples of what you need to convert? The actual culprit is that RollNotePF2e now needs to be a class. I think we both forgot CheckPF2e.roll() was public api.
