### ISSUE TITLE
Feature request: prioritise ownership within a square.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4314]
When you have more than one character in a square as a player you cant select your token when theres more than one character within the same square. this also goes for any other tokens that maybe owned such as familiars. 

solution:

if there is a square with more than one token make it easier to select your own tokens that belong under the ownership you have. 

for example.

two tokens on one square and one is your own, if you select that square it defaults to your token that you own upon selection. as there is no need to select a token other than your own if you are in the same square together. 

ive had many instances of being unable to select tokens when they go through each other or are cramped into a small space.

**Comment by stwlam** [comment]
There is an upstream bug preventing anything like this. Once it's fixed, you can hover a token stack and press Z to cycle to the desired token.

**Comment by ThingsCouldGetDicey** [comment]
ahh so it is fixable? i just had this issue during play.

**Comment by stwlam** [comment]
You can keep an eye on the upstream issue here: https://github.com/foundryvtt/foundryvtt/issues/8042
