### ISSUE TITLE
Feature request: Navigation buttons in journals

### ISSUE THREAD

**Issue by hmarthinsen** [foundryvtt/pf2e#4367]
It would be really useful to have back/forward navigation buttons in the journal UI, especially for journals with many pages and hyperlinks between them. As it is now, I have to remember where I came from when I click a link, and then manually navigate back. One example where this is cumbersome is the "GM Screen" journal entry.

**Comment by stwlam** [comment]
A feature request like that can be made here: https://github.com/foundryvtt/foundryvtt/issues

**Comment by hmarthinsen** [comment]
OK, added an issue here: https://github.com/foundryvtt/foundryvtt/issues/8323
