### ISSUE TITLE
dx assume/default to 1dx dmg, not 0dx

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#4388]
if you accidentally (or not knowing what'll happen) put dx(+y) for dmg, instead of 1dx+y [such as d4+2 instead of 1d4+2], current behaviour seems to treat this as 0dx, and just adds the +y when dmg is clicked - this should treat it is as 1dx+y

**Comment by stwlam** [comment]
Damage for what in particular?

**Comment by dharkus5000** [comment]
i found the problem in attacks on NPCs, but dmg elsewhere seems likely to also have the same issue?

**Comment by TikaelSol** [comment]
I think we can safely leave this, behavior, if data is entered wrong it makes sense that it doesn't work.
