### ISSUE TITLE
Poltergeist is missing traits

### ISSUE THREAD

**Issue by lslavkov** [foundryvtt/pf2e#4411]
After comparing poltergeist with Archive of Nethys it is missing a creature traits.

**Comment by stwlam** [comment]
What was the result of your comparison?

**Comment by TikaelSol** [comment]
Foundry

![image](https://user-images.githubusercontent.com/80183198/194916547-7250a2af-d83d-42b2-a65e-c84b97bbd62d.png)

PDF

![image](https://user-images.githubusercontent.com/80183198/194916610-8dcd7686-85a1-4d1c-ac1c-4d9d47b330df.png)
