### ISSUE TITLE
Herbal Items unaccounted for for Herbalist Archetype

### ISSUE THREAD

**Issue by Cerapter** [foundryvtt/pf2e#4412]
Travel Guide introduced a new trait-that-isn't-a-trait called "herbal items". These interact in a new way with Herbalist Archetype:

> Each of the plant items listed below has specific benefits, some of which apply when you use a specific action or activity.  Alchemical plant items are “herbal items,” meaning characters with the herbalist archetype (Advanced Player’s Guide) can use their archetype abilities with them.

These are Artevil Suspension, Curled Cure Gel, Drowsy Sun Eye Drops, Lady's Blessing Oil, Toothworth Extract and Yarrow-Root Bandage.

Currently, a Herbalist trying to put these in their crafting entry will get an alert that it does not match the `["alchemical", "healing"]` crafting item requirements.

**Comment by TikaelSol** [comment]
Guess we need a new tag.
