### ISSUE TITLE
Cha-, int- and wis-based FlatModifiers don't apply to spell attack rolls and spell DCs

### ISSUE THREAD

**Issue by Cerapter** [foundryvtt/pf2e#4413]
Easiest way to see this is applying Stupefied to a spellcaster. Saves go down, spell attack rolls and spell DCs stay the same.

Seems to be caused by the matching selector altogether missing from the DC / rolls. Inspecting a spell attack roll shows its lack amidst the selectors, so I presume the same is true for spell DCs.

**Comment by CarlosFdez** [comment]
Thanks for catching. Yeah, another thing that slipped through the cracks when I allowed spells to expand off class dc.
