### ISSUE TITLE
Power Attack does not work when used on Wild Shape attacks

### ISSUE THREAD

**Issue by Far2Casual** [foundryvtt/pf2e#4425]
Pretty much explanatory. If the Druid attacks normally:
![image](https://user-images.githubusercontent.com/63196064/194923419-9ae97128-e73d-4f5b-84ba-52e5a4ec5f1d.png)

If the Druid transforms using Wild Shape and uses one of the attacks gained from the transformation:
![image](https://user-images.githubusercontent.com/63196064/194923618-b16beaff-c40e-41ab-9bf2-39573a471b02.png)

In both cases, the toggle is selected of course.

**Comment by stwlam** [comment]
Working as intended: see polymorph rules

**Comment by Far2Casual** [comment]
My bad, thank you for the pointer.
