### ISSUE TITLE
Sneak attack precision damage is not added when target has the Flat-footed condition

### ISSUE THREAD

**Issue by Far2Casual** [foundryvtt/pf2e#4427]
Not working: the damage is not added when the target has the Flat Footed condition:
![image](https://user-images.githubusercontent.com/63196064/194932309-f7942201-dfe3-4126-8346-bc5d6feda9fd.png)

Working : the damage is added if either:
- the attacker activates the "Enable abilities that requires a flat-footed target"
- the system detects that a creature is Flat-footed due to flanking
![image](https://user-images.githubusercontent.com/63196064/194932548-7d401dbb-e846-41fd-9f31-9b54aa79d485.png)

**Comment by TikaelSol** [comment]
The issue is that the target's conditions are not being picked up as roll options.
