### ISSUE TITLE
ABP devastating strikes aren't counted as damage dice 

### ISSUE THREAD

**Issue by EthanNeuralImage** [foundryvtt/pf2e#4460]
The way that Implement's Empowerment's rule element is worded, it doesn't work with Automatic Bonus Progression. Is there a way to add in the damage dice gained from ABS to (1 + @weapon.system.runes.striking) * 2 so that it becomes (1 + @weapon.system.runes.striking *(0 if ABS_VAR > 0 else 1) + ABS_VAR) * 2 where ABS_VAR is the number of dice gained from Automatic Bonus Progression?

**Comment by NikolasTzimoulis** [comment]
Same problem with gravity weapon, it calculates the extra damage like so:  `(1 + @weapon.system.runes.striking) * 2` and thus only adds 2 damage with ABP no matter your level. I think the solution is simply to have `@weapon.system.runes.striking` change automatically to follow what ABP says regardless of the runes on the weapon.

**Comment by krbrousseau** [comment]
Adding on that this bug affects every effect that calculates damage based on striking runes. I've tested this with feats like Fighter's Two-Handed Assault and effects like the Boost Eidolon cantrip. Enabling ABP disables the ability to adjust a weapon's striking runes, so you cannot get around this. If the devastating strikes dice count was used in place of the striking rune level under ABP, these effects would all function correctly.
