### ISSUE TITLE
Claw isn't taken in account as favored weapon by deities.

### ISSUE THREAD

**Issue by DrakEmono** [foundryvtt/pf2e#4472]
Greetings! Some deities (Bastet, Sekhmet and Adanye exactly) have claws as a possible favored weapon. However, when I have a cleric with a claw attack given by an ancestry, the attack die size isn't increased (even with the Deadly Simplicity feat manually added).

Also, talking about clerics and the Deadly Simplicity feat, I think it would be great to add it automatically as a bonus feat if the cleric selects a diety with a simple or unarmed favored weapon and the warpriest doctrine.

Thanks!

**Comment by stwlam** [comment]
Where is the claw coming from?
