### ISSUE TITLE
Possible Lighting Bug When Selecting PC's

### ISSUE THREAD

**Issue by Cosmic-Lattee** [foundryvtt/pf2e#4480]
This might very well be intended and if so I apologize for the wasted time. This was tested with Foundry 10 (288) with Pathfinder 2nd edition 4.2.6.

![Example2](https://user-images.githubusercontent.com/24766235/195966384-5a543f41-477f-4696-957f-db38adeafd53.gif)

So the scenario above is two PC's assigned as party members. One has a light spell on the other has darkvision. Individually it seems to work as expected with the dwarf seeing in color until the edge of the light with the human only seeing to the edge of the light. 

When I select them they both see the light when I select both I see the world through darkvision as if I didn't have a light spell on. My players who all have ownership of each others sheets see this behavior as well

**Comment by stwlam** [comment]
Core issue, unfortunately
