### ISSUE TITLE
Feature request: Add text search feature to inspect roll window

### ISSUE THREAD

**Issue by fraserstanton** [foundryvtt/pf2e#4502]
scrolling through the whole list can be a pain, some kind of text search would be nice?

**Comment by CarlosFdez** [comment]
I'm not certain about a text sort, but I was consider sorting everything without : at the top.

**Comment by stwlam** [comment]
Isn't it already sorted?

**Comment by CarlosFdez** [comment]
Sorry. I'm not certain about a text search. I want to change the sorting to make certain types of roll options easier to find.
