### ISSUE TITLE
`_executeScript` patch breaks Advanced Macros and with it, PF2e Animation Macros

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#4503]
https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/issues/41#issuecomment-1282585951

I do not foresee supporting both PF2e's Macros and Advanced Macros, let alone changing to _only_ PF2e's Macro variables (?)

**Comment by stwlam** [comment]
Advanced Macros is destructive enough on its own that I do not foresee the system going out of its way to accommodate it.
