### ISSUE TITLE
Double Effect Icon on Enemy Tokens

### ISSUE THREAD

**Issue by Cosmic-Lattee** [foundryvtt/pf2e#4509]
So this is tested with a fresh game running 4.2.6 on Version 10 (288).

![Effects](https://user-images.githubusercontent.com/24766235/196585014-11b7cdbc-e5ae-4b60-ab70-2f33c8c93660.gif)

When I drag effects or use a macro to put a effect on npcs it seems to create a phantom double on the token. It doesn't show up on the effect hud on the right of the screen.

It doesn't seem to affect PC tokens. Though interestingly when I placed a effect on a PC token and then placed a different effect on a npc it worked normally, then broke again.

Not shown on the video but if you go to the effect on the token and disable and re-enable the "Show Token Icon?" checkbox it will make the shadow token go away.

**Comment by TikaelSol** [comment]
I have seen this before, shortly after v10 came out but I can't reproduce it now. I've tried several different things. Does this still happen on 4.3?

**Comment by Cosmic-Lattee** [comment]
So when I updated it today to 4.3.1 it fixed it. /shrug
Not sure why since it was seemingly something only affecting me. XD Anyways I will close this for now.
