### ISSUE TITLE
[Request] Add option to look for Hero Point usage in Rule Elements

### ISSUE THREAD

**Issue by LonePaladin** [foundryvtt/pf2e#4516]
I have a house-rule I use, where if someone uses a Hero Point to reroll a check, and the flat d20 roll is 10 or less, they add +10 to the result. I'm looking at automating this, and a chat with Tikael suggested the best way is to have a callout in the code so that Rule Elements can look for it.

He said that this would require someone to dig in `rolls.ts` to figure out where best to put an `options.push("hero-point")`, this would add "hero-point" to the list of options for Rule Elements.

**Comment by stwlam** [comment]
This isn't currently feasible, but maybe some day.

**Comment by Honclbrif** [comment]
Our group is also looking for this exact same thing.
