### ISSUE TITLE
Request for action macros compendium to have respective icons.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4520]
Id like to suggest and even help formalising the respective icons for the pf2 macro compendium having to do them over and over on each player is tediuos and it would be nice to be formalised for everyone using them.

**Comment by stwlam** [comment]
This one here?

![image](https://user-images.githubusercontent.com/106829671/197387457-ed0bd6bb-bdf2-4272-9fb0-8204c92bee16.png)

**Comment by ThingsCouldGetDicey** [comment]
> This one here?
> 
> ![image](https://user-images.githubusercontent.com/106829671/197387457-ed0bd6bb-bdf2-4272-9fb0-8204c92bee16.png)

no this one
![image](https://user-images.githubusercontent.com/62528192/197387927-a54f5b51-5754-48fe-be8e-6f3dad3f79f7.png)

**Comment by stwlam** [comment]
These will sooner be retired than receiving additional attention. Note that if you are changing the icons of imported macros and intend them to be used by players, you can import a single set and give your players limited or higher permission on them.
