### ISSUE TITLE
Effect of unchecked checkboxes are applied

### ISSUE THREAD

**Issue by Nordiii** [foundryvtt/pf2e#4523]
Hello, 

it seems that somehow Actors can get broken which always applies certain effects to them even if the checkbox is unchecked.

I noticed that with the Beginners Box preplaced Kobolds always had Hurried Retreat activated:
https://github.com/foundryvtt/foundryvtt-premium-content/issues/127

The same now happened with multiple Actors in the Abomination Vaults (just installed it and took a quick glance at the first level)

But it seems that this does not only affect NPCs as some Reddit post suggests:
https://www.reddit.com/r/FoundryVTT/comments/y8hdpw/swashbuckler_bugs_pf2e/

**EDIT:**
Foundry: 10.288
PF2E: 4.2.6
Beginner Box: 2.0.1
Abomination Vaults: 1.2.0

**Comment by Drental** [comment]
can you check that the same thing happens when you drag the actor directly from the compendium?

**Comment by Nordiii** [comment]
Dragging the Actor directly from the compendium does not cause this issue. 

Removing the preplaced Actors and replacing them from the Actors menu does not produce the issue either, like mentioned in https://github.com/foundryvtt/foundryvtt-premium-content/issues/127 .

Just the preplaced NPCs have issues. For the PC i can not speak.

**Comment by Drental** [comment]
then it seems like this is only an issue with the premium module, not the system itself.

I do have very specific guesses what might be happening here, and that can not be fixed by the system.

**Comment by Nordiii** [comment]
Thanks for the quick reply!
Wasn't sure because of the bad PC Actor in the Reddit post. I thought maybe it was a migration issue or something a like that!

Have a great day.
