### ISSUE TITLE
Large creatures provide flanking as if they have reach

### ISSUE THREAD

**Issue by Lemantia** [foundryvtt/pf2e#4537]
Large (or more) creatures that don't have reach (like a Tiger) still provide flanking to their allies as though they did.

To reproduce:
Put a player token between 2 large creatures, even if neither of those are adjacent to the token. The player will be flanked, and their AC reduced.

The issue also seem to happen with Huge creatures that don't have reach, like the Hive Mother.

**Comment by stwlam** [comment]
What is the reach of a quasit's claw attack?

**Comment by Lemantia** [comment]
According to the rules, the Quasit's Claw attack should have a reach of 5ft, since its statblock doesn't say otherwise.

In Foundry, the Quasit seem to be assumed to not have any reach, and seem unable to flank, or provide help with flanking.

**Comment by stwlam** [comment]
I'm not sure what rules those are.

**Comment by Lemantia** [comment]
The alternative would be assuming that Reach work as indicated by the table from the CRB p473 https://2e.aonprd.com/Rules.aspx?ID=445 (which is mentioned again in the bestiary, p345), which are supposed to be guidelines.

We can look at a creature like Arboreal  Warden, who has its reach of 10ft specified on one attack, and nothing on the other, which seems to indicate a reach of 5ft (but is also inconsistent with the Gorilla, which has reach 10ft on its fists, and reach 5ft on its jaw).

Looking a bit further, a Shield Archon, Lillend, Cyclops, Ceustodaemon are large and tall creatures but their only attack still specify their reach of 10ft. 

The Demilich is the only creature i've been able to find who has an attack with a specified reach of 0 ft.
