### ISSUE TITLE
Adjustable font size for new character sheet sidebar

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#454]
In GitLab by @Shandyan on May 26, 2020, 06:42

The font size for the headers* in the new sidebar is very small at higher resolutions when compared to the old character sheet. There should be a way to increase the font size - as is, I'm not sure I can use the new sheets on my monitor, as I have to squint to read the heading text.

* i.e. the text used for Fortitude, Reflex, Will

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/3405ff4ac18a0ccc887e80498912c8d4/image.png)

**Comment by stwlam** [comment]
Addressed by core font-size setting
