### ISSUE TITLE
NPC feature frequency is missing "per round" and "per turn"

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#4542]
I was building an NPC and I expected to have "round" (and "turn") in the dropdown here:

![image](https://user-images.githubusercontent.com/6516621/197542620-3e4ef4aa-bd8d-4188-848f-1c1885511351.png)

**Comment by LebombJames** [comment]
That field is meant for tracking the action over time (when on a PC, you'll see it creates a "Uses 1/1"). Tracking as minutely as rounds/turns is therefore unnecessary, impractical

~~Just put 10 per minute~~

**Comment by CarlosFdez** [comment]
I think including "round" is fine.
