### ISSUE TITLE
Line Templates from spells are too thin

### ISSUE THREAD

**Issue by Angry-Snail** [foundryvtt/pf2e#4554]
When casting spells with an area of Line (such as Grim Tendrils and Lightning Bolt), the template placed from the chat card is only 1ft wide instead of 5ft wide. This means that when placing the template on non-45 degree increments, it doesn't highlight the squares properly.

Tested on both an active world with mods and a completely fresh world.

**Comment by Ironxxx** [comment]
I also get this and there's no way to increase the width of the line in Details
