### ISSUE TITLE
Spiked Pit hazard incorrect damage roll.

### ISSUE THREAD

**Issue by steev42** [foundryvtt/pf2e#4623]
![image](https://user-images.githubusercontent.com/6807026/198846418-c9d5370a-ae4a-447a-ba4f-50a8d116040c.png)
Spiked Pit hazard reaction says 1d4 piercing damage, but rolls 2d6.

**Comment by TMunsie** [comment]
Where is this from. It looks like someone copied a different hazard and didn't change the Source.

**Comment by steev42** [comment]
It's listed under "PFS Introductions" in the Compendiums.  And I did just check on another world with no modules that it exists there, so it's probably default data.
