### ISSUE TITLE
Tokens can hear through walls that block sound but not sight

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/pf2e#4628]
The hearing mode must not use `test.los` (`test.los` contains results of sight-based tests). https://github.com/foundryvtt/pf2e/blob/e3f7c35ae6f4ff63c7cc5d97d29b76175cb11e41/src/module/canvas/perception/modes.ts#L108

### Reproduction Steps

Place two tokens with a wall between the two. Make sure one of the tokens has vision enabled, vision range 0, hearing set to a large enough range. Configure the wall:
- Sight Restriction: None
- Sound Restriction: Normal

The token is able to hear the other token even though the wall blocks sound.

**Comment by stwlam** [comment]
Those is intentional for now: there is not yet any mechanical or visual consequence to it, and it serves as a CPU-usage optimization.

**Comment by dev7355608** [comment]
It doesn't affect tokens with darkvision mechanically or visually, because they would see the other token anyway through this wall (soundproof glass) with their infinite darkvision range, but tokens without darkvision can't see the token (assuming it isn't illuminated) but are able to hear it even though the wall should block sound. So it makes a difference for nondarkvision tokens. That's intended (or acceptable because of performance)?
