### ISSUE TITLE
RE validation warnings when fetching documents from Compendia

### ISSUE THREAD

**Issue by Drental** [foundryvtt/pf2e#4637]
I used getDocuments() on all packs for something else and my console gave me *warnings*.

So I thought I'd make an issue that helps finding all the warnings so they can get fixed.

the copy paste of the console is not very readable. Use the macro to get the list after about half a minute.
```
for (const pack of game.packs) {
  console.log(pack.collection)
  await pack.getDocuments();
}
```

```
PF2e System | Base Speed rules element on item Frost Susceptibility (Compendium.pf2e.extinction-curse-bestiary.29NHB8DNNAbEk5Va.Item.gHi2vKCOAok2Xdj9) failed to validate: Unrecognized or missing selector
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | Aura rules element on item Time Siphon (Compendium.pf2e.kingmaker-bestiary.2mkfF43tP8IGVfBz.Item.aHuQg1Wi1gb8KAbH) failed to validate: "effects" property is invalid.
PF2e System | Note rules element on item Staff (Compendium.pf2e.kingmaker-bestiary.sMCEMlNngFINMX8y.Item.6k6LtJmrZAfTImSh) failed to validate: "text" property is missing or invalid
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | Damage Dice rules element on item Bespell Primal Weapon (Compendium.pf2e.pfs-season-1-bestiary.3MSKMI7ehLTC1bqw.Item.MDYvDrMtPOuocfAw) failed to validate: category must be "precision" or omitted
PF2e System | Damage Dice rules element on item Bespell Primal Weapon (Compendium.pf2e.pfs-season-1-bestiary.f9NDRa2grZrqnTIs.Item.MDYvDrMtPOuocfAw) failed to validate: category must be "precision" or omitted
PF2e System | Flat Modifier rules element on item Effect: Prepare Fangs (Compendium.pf2e.pfs-season-3-bestiary.GKF2zLJ0VLy1IBML.Item.sEHp9sZNMb0Ixl7j) failed to validate: A flat modifier must have one of the following types: ability, circumstance, item, potency, proficiency, status, untyped
PF2e System | Flat Modifier rules element on item Effect: Prepare Fangs (Compendium.pf2e.pfs-season-3-bestiary.Gt2NqeZldkUf4vHI.Item.sEHp9sZNMb0Ixl7j) failed to validate: A flat modifier must have one of the following types: ability, circumstance, item, potency, proficiency, status, untyped
PF2e System | Flat Modifier rules element on item Effect: Prepare Fangs (Compendium.pf2e.pfs-season-3-bestiary.XxbdbTlnY0P3RU3h.Item.sEHp9sZNMb0Ixl7j) failed to validate: A flat modifier must have one of the following types: ability, circumstance, item, potency, proficiency, status, untyped
```

**Comment by shemetz** [comment]
Here's a more readable edit, which only has the initial console error line of each:

> PF2e System | Base Speed rules element on item Frost Susceptibility (Compendium.pf2e.extinction-curse-bestiary.29NHB8DNNAbEk5Va.Item.gHi2vKCOAok2Xdj9) failed to validate: Unrecognized or missing selector
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | Aura rules element on item Time Siphon (Compendium.pf2e.kingmaker-bestiary.2mkfF43tP8IGVfBz.Item.aHuQg1Wi1gb8KAbH) failed to validate: "effects" property is invalid.
PF2e System | Note rules element on item Staff (Compendium.pf2e.kingmaker-bestiary.sMCEMlNngFINMX8y.Item.6k6LtJmrZAfTImSh) failed to validate: "text" property is missing or invalid
PF2e System | A Sense rules element may not be applied to a NPC
PF2e System | Damage Dice rules element on item Bespell Primal Weapon (Compendium.pf2e.pfs-season-1-bestiary.3MSKMI7ehLTC1bqw.Item.MDYvDrMtPOuocfAw) failed to validate: category must be "precision" or omitted
PF2e System | Damage Dice rules element on item Bespell Primal Weapon (Compendium.pf2e.pfs-season-1-bestiary.f9NDRa2grZrqnTIs.Item.MDYvDrMtPOuocfAw) failed to validate: category must be "precision" or omitted
PF2e System | Flat Modifier rules element on item Effect: Prepare Fangs (Compendium.pf2e.pfs-season-3-bestiary.GKF2zLJ0VLy1IBML.Item.sEHp9sZNMb0Ixl7j) failed to validate: A flat modifier must have one of the following types: ability, circumstance, item, potency, proficiency, status, untyped
PF2e System | Flat Modifier rules element on item Effect: Prepare Fangs (Compendium.pf2e.pfs-season-3-bestiary.Gt2NqeZldkUf4vHI.Item.sEHp9sZNMb0Ixl7j) failed to validate: A flat modifier must have one of the following types: ability, circumstance, item, potency, proficiency, status, untyped
PF2e System | Flat Modifier rules element on item Effect: Prepare Fangs (Compendium.pf2e.pfs-season-3-bestiary.XxbdbTlnY0P3RU3h.Item.sEHp9sZNMb0Ixl7j) failed to validate: A flat modifier must have one of the following types: ability, circumstance, item, potency, proficiency, status, untyped
