### ISSUE TITLE
Feature Request: Add a variant of Items Only spellcasting type that allows tracking staff charges.

### ISSUE THREAD

**Issue by Minalien** [foundryvtt/pf2e#4640]
Currently playing around with building a Staff Nexus wizard, and I'm realizing that it would be very helpful to have an Items Only spellcasting type for Staves that tracks staff charges.

From a mechanical automation standpoint, casting a spell from a staff consumes charges equal to the spell's level (so a level 5 spell costs 5 charges). There shouldn't be a "Max Charges"-type field, as charges expire after 24h and the number of charges in the staff isn't necessarily consistent from day to day. (Staves get free charges = highest level of spell the character preparing it can cast, and then they can expend spell slots to add additional charges for that day - and Staff Nexus Wizards can eventually expand this count even further).

Rules References:
* [Staves (Core Rulebook 592)](https://2e.aonprd.com/Rules.aspx?ID=748)
* [Staff Nexus (Advanced Player's Guide 142)](https://2e.aonprd.com/ArcaneThesis.aspx?ID=5)

**Comment by CarlosFdez** [comment]
This is likely going to be handled automatically via having a stave rather than a new casting entry., but we're going to need the ability to cast spells that don't exist in the actor. We're pretty close to that point though.

**Comment by CarlosFdez** [comment]
This was more or less also brought up by the much more outdated #413

**Comment by TikaelSol** [comment]
Closing as a duplicate issue.
