### ISSUE TITLE
A big list of (potential) data entry errors

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#4641]
These are the likely errors I found based on extreme statistics - see https://docs.google.com/spreadsheets/d/1soiYf7ia-nru37t9kWrDqDgBcdME_cH4PmyfVowIUzg/edit#gid=565840756 for the data and info.

- Vitalia, a bunch of saves and AC are all at 0.
- Air Mephit, reflex save is +19 (too high). **This is correct per B1**
- Urdefhan Death Scout, spell DC is 31 (too high).  should be 21.
- Herecite of Zevgavizeb, 3rd spell attack bonus is +0.
- Tino (Oni Form), 1st attack bonus is +350 (too high).
- Yabin (White Serpent Form), 2nd attack bonus is +0.
- Spinel Leviathan Syndara, all skills are +0.
- Sié Goluo, spell attack and DC are 0.
- Tehialai-Thief-of-Ships, 7th attack bonus is +36 (too high) **This is correct per LO:MoM**
- Ixirizmid, spell attack and DC are 0. **There is no DC for this ritual in Malevolence**
- Esobok Ghoul, spell attack bonus is +20 (too high)
- Antipaladin, spell attack and DC are 0.
- Advisor, 1st spellcasting DC is 0.
- Clockwork Sphinx, will save is +3 (too low).  should be +13
- Sister of the Bloodshot Eye, many stats are at the default of 10 or 0
- Pavetta Stroon-Drelev, all abilities are at 0
- Nugrah, spell attack is +21 (too high) **This is correct per Kingmaker PDF**
- Nugrah, reflex save is +6 (too low?) **This is correct per Kingmaker PDF**
- Vilderavn Herald, attacks are 0.
- Svetlana, saves are at 0.
- False Priestess, spell attack and DC are 0.
- Leng Envoy, spell attack and DC seem too low.
- Barbtongued Wyvern, 2nd attack bonus is +17 (too low)
- Niodrhast, 2nd attack bonus is +2 (too low)
- Sepoko, spell attack and DC are 0.
- Cephal Lorentus, spell attack and DC are 0.
- Storm Giant, 3rd attack bonus is +37 (too high). **This is correct per Bestiary 1**
- Efreeti, spell attack and DC are 0.
- Elemental Tsunami, strike damage is a bit broken **This is correct per Bestiary 1**
- Calikang, spell attack is 30 (too high)
- Angheuvore Flesh-Gnawer, hp is 0 (too low)
- Harmona, spell attack and DC are 0
- Pakalchi, hp is 0
- Reflection, a bunch of stats are 0 but maybe it's not a mistake **This is correct per Dark Archive**
- Goblin Skeleton, hp 20 (too high, especially for a skeleton)  **This is correct per PFS 1-14**
- Skeleton Soldier, ac 1 (too low).  should be 17 **This is correct per PFS 1-18**
- Manifestation of Qxal (5-6), first attack bonus is +30 (too high)
- Marcon Tinol (3-4), ac is 35 (too high) **This is correct per PFS 1-07**
- Scorched Cavern Troll, 2nd attack bonus is +3 (too low)
- Young Ahuizotl, perception is 0 (too low)
- The Saboteur (5-6), almost all of its stats are beyond extreme for level 2.  maybe its level is meant to be higher?
- Arabuk Yearling, 2nd attack is +2 (too low)
- Glurorchaes (7-8), constitution is +22 (too high)
- Contemplative Mentor, first spell DC is 0
- Boggard Hunter, athletics skill is 0, should be 16

**Comment by TMunsie** [comment]
Corrected most of these in #4643. Annotated remainder. Will let @TikaelSol or @SpartanCPA close if they're happy
