### ISSUE TITLE
Missing RE for Unleash Psyche 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4644]
![image](https://user-images.githubusercontent.com/62528192/198903289-13249a97-ccc6-4634-853b-8ffcba32e4a9.png)
if this could do a status icon that lasts for two rounds and apply the spell effects aswell as the negative effects after its finished it would be useful.
the action reads as follows:
You call on the depths of your mind and let psychic power flood through. Your Psyche remains Unleashed for 2 rounds or until your fall, whichever comes first. You can't voluntarily quell your unleashed psyche. While your Psyche is Unleashed, the following effects occur.

    You're constantly surrounded by the visual manifestation of your psychic magic.
    When you cast a damaging spell, you gain a status bonus to its damage equal to double the spell's level. This applies only to spells that don't have a duration and that you cast using psychic spellcasting.
    You can use actions that have the [psyche] trait

After your unleashed psyche subsides, your mind must recover from the strain of channeling its full power. You can't use Unleash Psyche again for 2 rounds, and you're [stupefied 1] for 2 rounds.

https://2e.aonprd.com/Actions.aspx?ID=1222

**Comment by TikaelSol** [comment]
There is an effect for Unleash Psyche already in the system, if you don't see if linked in your actor's Unleash Psyche action make sure you are up to date then change to level 0 then back up to refresh the class features. There's nothing for the effects after it's removed however, as the system does not support setting durations on conditions and that would be part of a much larger fix.

**Comment by ThingsCouldGetDicey** [comment]
> There is an effect for Unleash Psyche already in the system, if you don't see if linked in your actor's Unleash Psyche action make sure you are up to date then change to level 0 then back up to refresh the class features. There's nothing for the effects after it's removed however, as the system does not support setting durations on conditions and that would be part of a much larger fix.

i tried that and no change.

**Comment by ThingsCouldGetDicey** [comment]
nvm i found the issue, the feat itself on the feat page was being used instead of the action part of it which is different. is that correct?
