### ISSUE TITLE
Quick Alchemy Dedication Feat 

### ISSUE THREAD

**Issue by DimlyCandescent** [foundryvtt/pf2e#4654]
Expected Behaviour: The Quick Alchemy feat obtained through the Alchemist Dedication should provide the Quick Alchemy toggle on the Crafting page. 

Current Behaviour: Said feat does not provide the Quick Alchemy toggle

Workaround: Adding the Quick Alchemy Feature adds the toggle correctly

**Comment by KSops** [comment]
Alchemist Dedication is not supposed to grant Quick Alchemy
https://2e.aonprd.com/Feats.aspx?ID=665
If you mean the base class, it seems to work for a new character

Is Alchemist Dedication feat somehow granting you Quick Alchemy?

**Comment by DimlyCandescent** [comment]
Nope, mean the Quick Alchemy level 4 feat within the Alchemist Dedication.
https://2e.aonprd.com/Feats.aspx?ID=667

**Comment by KSops** [comment]
Ah I think I understand now. The feat doesn't grant but the class feature does.
Root cause is that the check on the crafting tab only checks for the class feature roll option and not for the feat.
