### ISSUE TITLE
Sight range of tokens without darkvision is NaN if the scene is globally illuminated

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/pf2e#4656]
I suspect `?? null` is missing here; `CONFIG.Canvas.visionModes.basic.vision.range` is `undefined`. https://github.com/foundryvtt/pf2e/blob/a1971344f8f0d26091487a29be3a3950f7fed981/src/module/scene/token-document/document.ts#L248

### Reproduction Steps

Place a token of an actor without darkvision in a scene with Darkness Level 0 (RBV enabled).
```js
_token.document.sight.range // undefined
_token.sightRange // NaN
_token.vision.radius // NaN
```

**Comment by stwlam** [comment]
It comes up undefined for me in all three cases. How are you getting `NaN`?

**Comment by dev7355608** [comment]
I can't explain the `undefined` case 2 and 3; this should be impossible, because `Token#getLightRadius` can't possibly return `undefined`. `_token.getLightRadius(undefined)` should be NaN.

I reproduced it in a new world, new default scene, new default actor and token, default settings.
