### ISSUE TITLE
Weapon Property Runes Implementation

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#467]
In GitLab by @putt1 on May 27, 2020, 15:28

Weapon Property runes are extremely hard to automate. Therefore I think we can divide them into 3 categories: ones we can automate fully, ones that we can automate partial and ones we can't.

Runes that can be automated will be rolled together with normal damage. 

Runes that we can partially automate will roll their dice with the damage and display an inline text for the remaining effect.

Runes that we can't automate will display the description text inline and will let you roll dice and damage from the description (if applicable). 

Each roll for a rune that we can't automate should have a way to roll normal and critical damage. If the damage isn't a roll, we should provide a way to apply the damage (and critical damage).

# Runes that can be fully automated

* [x] Ghost Touch: adds the ghost touch trait to the damage
* [x] Wounding: adds 1d6 (1d12 on crit) persistent bleed damage 
* [x] Flaming: 1d6 fire damage and adds 1d10 persistent fire damage on a crit
* [x] Keen: crits on a 19
* [x] Serrating: adds 1d4 slashing damage + adds an activate action
* [x] Holy: adds 1d6 good damage + adds an activate action
* [x] adds 1d6 evil damage + adds an activate action

# Runes that we can sorta automate

* [ ] Disrupting: 
  * adds 1d6 positive damage
  * when rolled critically roll damage normally and display: 
  > The undead is also enfeebled 1 until the end of your next turn."
* [ ] Disrupting (Greater):
  * adds 2d6 positive damage
  * when rolled critically roll damage normally and display: 
  > The undead creature must attempt a DC 34 Fortitude save with the following effects. This is an incapacitation effect.
  > * **Critical Success** It’s enfeebled 1 until the end of your next turn.
  > * **Success** It’s enfeebled 2 until the end of your next turn.
  > * **Failure** It’s enfeebled 3 until the end of your next turn.
  > * **Critical** Failure It’s destroyed.
* [ ] Bloodbane:
  * adds 1 persistent bleed damage to clan enemy
  * displays:
  > Whenever you inflict persistent bleed damage with a bloodbane weapon (whether from its innate ability or in some other way), the weapon leaves ragged wounds. The bleeding creature must succeed at a DC 25 Fortitude save or become sickened 1. The creature is then temporarily immune for 1 hour.
* [ ] Bloodbane (Greater): 
  * adds 1d4 peristent bleed damage to clan enemy
  * displays:
  > Whenever you inflict persistent bleed damage with a bloodbane weapon (whether from its innate ability or in some other way), the weapon leaves ragged wounds. The bleeding creature must succeed at a DC 30 Fortitude save or become sickened 1. The creature is then temporarily immune for 1 hour.
* [ ] Corrosive: 
  * adds 1d6 acid damage
  * when rolled critically roll damage normally and display:
  > The target’s armor (if any) takes 3d6 acid damage (before applying Hardness); if the target has a shield raised, the shield takes this damage instead.
* [ ] Corrosive (Greater):
  * adds 1d6 acid damage
  * when rolled critically roll damage normally and display:
  > The target’s armor (if any) takes 6d6 acid damage (before applying Hardness); if the target has a shield raised, the shield takes this damage instead.
  * displays:
  > The acid damage dealt by this weapon ignores the target’s acid resistance
* [x] Flaming (Greater):
  * adds 1d6 acid damage
  * when rolled critically roll damage normally and display:
  > The weapon deals an additional 2d10 persistent fire damage on a critical hit.
  * displays:
  > The fire damage dealt by this weapon ignores the target’s fire resistance
* [x] Frost: 
  * adds 1d6 cold damage
  * when rolled critically roll damage normally and display:
  > The target is also slowed 1 until the end of your next turn unless it succeeds at a DC 24 Fortitude save.
* [x] Frost (Greater): 
  * adds 1d6 cold damage
  * when rolled critically roll damage normally and display:
  > The target is also slowed 1 until the end of your next turn unless it succeeds at a DC 34 Fortitude save.
  * displays:
  > The cold damage dealt by this weapon ignores the target’s cold resistance
* [x] Shock: 
  * adds 1d6 electricity damage
  * when rolled critically roll damage normally and display:
  > Electricity arcs out to deal an equal amount of electricity damage to up to two other creatures of your choice within 10 feet of the target.
* [x] Shock (Greater): 
  * adds 1d6 cold damage
  * when rolled critically roll damage normally and display:
  > The electricity damage dealt by this weapon ignores the target’s and the other creatures’ electricity resistance
  * displays:
  > The electricity damage dealt by this weapon ignores the target’s electricity resistance
* [ ] Thundering: 
  * adds 1d6 sonic damage
  * when rolled critically roll damage normally and display:
  > The target has to succeed at a DC 24 Fortitude save or be deafened for 1 minute (or 1 hour on a critical failure).
* [ ] Thundering (Greater): 
  * adds 1d6 cold damage
  * when rolled critically roll damage normally and display:
  > The target has to succeed at a DC 34 Fortitude save or be deafened for 1 minute (or 1 hour on a critical failure).
  * displays:
  > The sonic damage dealt by this weapon ignores the target’s sonic resistance
* [ ] Anarchic: 
  * adds 1d6 chaotic damage
  * when rolled critically displays:
  > When you make an attack roll with this weapon against a lawful creature, roll 1d6. On a 1 or 2, you deal double minimum damage; on a 3 or 4, double your damage normally; on a 5 or 6, you deal double maximum damage.
* [ ] Axiomatic: 
  * adds 1d6 lawful damage
  * when rolled critically displays:
  > When you make an attack roll with this weapon against a chaotic creature, instead of rolling, count each weapon damage die as average damage rounded up (3 for d4, 4 for d6, 5 for d8, 6 for d10, 7 for d12).
* [x] Grievous:
  * When having a critical specialization for the weapon type, displays the [additionals crit specialization effects](https://2e.aonprd.com/Equipment.aspx?ID=298) unless it's a dart, then the persistent bleed damage is 2d6

# Runes that can't be automated

* [ ] Kinwarding rune
* [ ] Returning rune
* [ ] Shifting
* [ ] Dancing
* [ ] Spell Storing
* [ ] Speed
* [ ] Vorpal
* [ ] Ancestral Echoing

**Comment by Crineryr** [comment]
I know I am necroing this subject, but I was wondering if it is possible to sorta automate shifting rune similarly to druid's "Spell Effect: Animal Form"? I would see it as a draggable effect that would override/add additional attack based on user's selection. I am not familiar with the code and if this is possible to include other present runes and other modifiers, but just a thought.

**Comment by Symon-S** [comment]
@Crineryr There is a shifting weapon macro in the Workbench module in the interim called "weaponshifting".

**Comment by Crineryr** [comment]
@Symon-S Thanks for a tip, just checked the macro and it works very well!

**Comment by stwlam** [comment]
Closing: this has reached a point where the basics are done. There are gaps, of course, but those are subsumable by larger issues (e.g., item activations).
