### ISSUE TITLE
[alchemist] calculated splash

### ISSUE THREAD

**Issue by milkyw4i** [foundryvtt/pf2e#4676]
Alchemist's Class Feat "Calculated Splash" is not incorporated into damage calculations.
Class feat reads:
You have calculated all the angles to maximize a bomb’s splash. When you throw an alchemical bomb with the [splash](https://2e.aonprd.com/Traits.aspx?ID=150) trait, you can cause the bomb to deal splash damage equal to your Intelligence modifier (minimum 0) instead of the normal amount.

Likely, this also affects the Class Feat "Expanded Splash":
The particularly volatile compounds that you brew into your bombs result in them creating especially large and powerful explosions. When you throw an alchemical bomb that has the [splash](https://2e.aonprd.com/Traits.aspx?ID=150) trait, you can add your Intelligence modifier to the bomb’s usual splash damage, and it deals splash damage to every creature within 10 feet of the target.

Please fix :-)

**Comment by kyles-ep** [comment]
Related/duplicate: https://github.com/foundryvtt/pf2e/issues/1875

**Comment by kyles-ep** [comment]
Expanded splash currently applies extra dmg, but it is part of crit. You can modify the FlatModifier rule to set it to be 1x dmg on crit.

**Comment by sorrythatuserbla** [comment]
Expanded splash is trivial to fix by changing 
![image](https://user-images.githubusercontent.com/78597675/200776193-370d13d9-4f83-4e7d-9c6c-b9ad95e74a1c.png)
to 
![image](https://user-images.githubusercontent.com/78597675/200776259-e3fe4820-35aa-4305-ab8e-a1b075a42b5d.png)

But what about calculated splash?

Is it possible to overwrite the splash part with something like `kh(@actor.abilities.int.mod, current_splash)` ?

**Comment by milkyw4i** [comment]
yeah, it would appear that expanded splash applies to damage, not to splash damage, fixing this, would allow fixing calculated splash as well.
In Pseudocode:

splash_damage = item.splash_damage
if actor has calculated splash feat
  splash_damage = actor.intelligence_modifier
if actor has expanded splash feat
  splash_damage = item.splash_damage + actor.intelligence_modifier

**Comment by KSops** [comment]
Splash seems to be in a pseudo-existent state in the codebase. There's an explicit splash damage portion in the data entries and it gets converted into a modifier with damageCategory `splash` but the enumerated types in `damageCategory` doesnt include splash. Furthermore, a few months ago the ability to set damage category was removed from the flat modifier rules element so it's difficult to express now. It was removed in favor of a `precision` checkbox.

I can only assume the main devs have a plan for addressing it later so I'm leaving this issue alone for now.

**Comment by KSops** [comment]
Related/duplicate: https://github.com/foundryvtt/pf2e/issues/1875
