### ISSUE TITLE
Weak/Elite Templates don't update the DCs of monster abilities

### ISSUE THREAD

**Issue by FrancescoDeS** [foundryvtt/pf2e#4692]
**Expected behavior**: when applying a weak/elite template to a creature sheet, the DCs of the abilities should decrease or increase by 2.
**Observerd behavior**: the DC stays the same after applying a weak/elite template
**Version**: 4.3.3

While the weak/elite templates correctly apply other stat changes (HP, AC, saving throws, skills, Strike attack bonus and damage), they don't seem to update the DC of abilities. For example, if there is an ability with the following element in the description, `@Check[type:will|dc:24]`, the DC will always be 24, even after applying a template.

**Comment by TikaelSol** [comment]
Tested and confirmed this is happening. It's an issue with elite/weak specifically. Other modifiers like frightened do work to reduce the DC of inline checks.
