### ISSUE TITLE
Weird interaction with the levels module

### ISSUE THREAD

**Issue by xavien12** [foundryvtt/pf2e#4724]
Context:
I already brought this bug up with the author of the levels module theripper93 and they said this seems to be a problem with the pf2e module so I brought this up here instead.

Version: 4.3.4

Describe the bug
As a DM when you select a NPC Token (with the vision enabled not checked under the tokens vision options) on a lower elevation, all tokens on higher levels of elevation can be seen. By going to the tokens on the higher elevation and disable and re-enable link to actor size under appearance the tokens from the higher levels disappear again from the lower levels, but can still be selected and glitch in and out when you select a token from a lower elevation but disappear when hovered over again.

To Reproduce
1. Have the actual version of the levels module installed.
2. Create a scene with different elevations. 
3. Put a tile as floor for the higher elevation.
4. Put a token on that floor.
5. Go to a lower elevation.
6. Put a token on that elevation.
8. Go back to the higher elevation floor and select the NPC see that the token on the lower elevation is not shown.
9. Go to a lower elevation and see that that the token in the higher elevation is shown.
10. Go to appearance on the higher elevation token and disable and re-enable link to actor size. 
11. Token on the higher elevation is no longer shown on the lower elevation. 
12. In addition when clicking on a tokens on the lower elevation, the tokens on the higher elevation will appear again on the lower level but disappear when hovered over.

Expected behavior
When you go to a level you should only see the token on that level and also not should only be able select the tokens on that level

Screenshots

high elevation
![strange tokens](https://user-images.githubusercontent.com/58941502/200163473-0c051ff7-e390-4709-ad5c-66eeece56603.png)

lower elevation
![strange tokens 2](https://user-images.githubusercontent.com/58941502/200163470-0024b34d-607d-46be-ad52-f2347aec0324.png)
token on the lower right had been changed by going to appearance and disable and re-enable link to actor size.

Browser:
Firefox

Foundry Version:
v10.288

**Comment by stwlam** [comment]
Weird interactions with modules are module issues, sorry.
