### ISSUE TITLE
Automate deities granting domains in each domain .json

### ISSUE THREAD

**Issue by rectulo** [foundryvtt/pf2e#4725]
In the domains json, there is a list of deities granting this domain with links. They are sorted alphabetically in english. 
This list of deities is giving me headaches.

Each time a lore/campaign book provides new deities or new pantheons, their names must be manually added in the domains.

Is there a way to avoid manual filling of the deities that grants each domain in the domain pages, by using the values of primary and alternate fields domains of each deity in the deity .json ?

I think this could alleviate the job of the Data entry team and translators. If it is possible filling deities json could automate this task.
And if it is possible to localize and sort them, it will automate the translator job too. 

Example with the Abadar.json
`       "domains": {
            "alternate": [
                "duty"
            ],
            "primary": [
                "cities",
                "earth",
                "travel",
                "wealth"
            ]
        },`

**Comment by stwlam** [comment]
These are text journal entries; there is no automation to be had.
