### ISSUE TITLE
Intermittent Inability to Access Right-Click menu in chat

### ISSUE THREAD

**Issue by steev42** [foundryvtt/pf2e#4752]
Some of my players, some of the time, are unable to right click on a chat message (usually to try to use a hero point) and have a menu show up.  

This is very vague, and for that I apologize.  It's been happening since our first session months ago, and I've been trying to narrow it down, but there doesn't seem to be rhyme or reason as to why it's happening.  3 of the 6 players have this issue from time to time.  It doesn't seem to be session related -- they can have the menu appear once, not appear two minutes later, and appear again 5 minutes after that.  I believe everyone having issues is using Chrome, but at least one of us that isn't having issues is also using Chrome (one of the non-issue is using Edge).  It's not tied to the message itself, as I have always been able to spawn the menu myself when they are having troubles.  

If anyone has any further troubleshooting that could help narrow down, I can try them in our next session.

**Comment by TikaelSol** [comment]
Unable to reproduce the issue. Will need more info or reliable steps to reproduce it.
