### ISSUE TITLE
Timestamps incorrect in chat on reload

### ISSUE THREAD

**Issue by steev42** [foundryvtt/pf2e#4753]
Quirky bug.  When loading up the server, the timestamps associated with chat messages for one player (and one player only) seem to be about 2 hours off.  We're all in the same timezone, so that shouldn't make a difference.  But it certainly makes for scrolling back through the chat log to find something a little odd, as I have to scroll through 2 hours of that players messages/die rolls before I get to anyone else's.

As I look at it right now, we finished playing around midnight Eastern last night (9:30 ago).  The most recent messages from him show 7h ago; the most recent message for any other player is 10h ago.  The messages also fall out of the combat round order, as the "Round End" for the end of combat that ended our session show up just before the first of his myriad of messages.

**Comment by stwlam** [comment]
This would be an upstream (Foundry) issue if anything.
