### ISSUE TITLE
Usability issue when equipping stacks of items.

### ISSUE THREAD

**Issue by TehT** [foundryvtt/pf2e#4778]
If you Draw a stackable item, like a bomb, one item is moved out of the stack and equipped.
If you then attack with this weapon, the item is spent, and attack is greyed out, despite the fact that you have more bombs, and you can't draw another one from the stack, since a new stack was created.

As the class most likely to have several stacks of bombs available (alchemist) also has quick bomb available, this seems convoluted, and quite annoying in actual play.

It is currently possible to work around this, by manually equipping all bombs in the inventory, or changing the stack of the drawn bomb to your carried total, at which point it works as expected, but this extra step should not be neccessary.

**Comment by stwlam** [comment]
The system doesn't split off bombs from stacks when you draw them.

**Comment by TehT** [comment]
![image](https://user-images.githubusercontent.com/7915544/201431077-e98a5327-0bff-405e-8aba-eb3d0287a6d5.png)
![image](https://user-images.githubusercontent.com/7915544/201431167-a1768486-3e72-43c4-9d8b-d749188fdf77.png)
![image](https://user-images.githubusercontent.com/7915544/201431252-a98b4bce-2764-4097-a11e-f657d9a47e86.png)

**Comment by stwlam** [comment]
Does the same happen when you draw from the actions tab?

**Comment by TehT** [comment]
same issue occurs when using the draw button
![image](https://user-images.githubusercontent.com/7915544/201432176-35ae9fb0-716c-4e47-9897-0195ea302be8.png)

![image](https://user-images.githubusercontent.com/7915544/201432093-8255a2d3-d83e-4d7e-b7f6-de9ec781f14f.png)

**Comment by stwlam** [comment]
Modules?

**Comment by TehT** [comment]
I did a FTC and it seems the issue can be traced to Ranged Combat, will report issue to them instead, sorry for the trouble!
