### ISSUE TITLE
Critical effect for Sword weapons shows wrong condition

### ISSUE THREAD

**Issue by LonePaladin** [foundryvtt/pf2e#4798]
The critical effect for Sword-type weapons says

> The target is made off-balance by your attack, becoming flat-footed until the start of your next turn.

https://2e.aonprd.com/WeaponGroups.aspx?ID=15

In Foundry, however, the critical effect shows the Hidden condition instead:

![image](https://user-images.githubusercontent.com/37523352/201501547-24269278-7205-4073-83e6-8d972d404a6a.png)

**Comment by stwlam** [comment]
This is due to Monk's Enhanced Journals.
