### ISSUE TITLE
Bug - NPC sneak attack auto applying in damage.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4809]
i was finding with the kobolds that i was using in the beginners box were auto applying sneak attack damage in the roll card. with or without flat footed condition on a pc it was attacking. it was always passive. there wasnt a seperate roll to apply the damage seperatley or a way to turn off the sneak attack damage.

**Comment by TikaelSol** [comment]
This is not a bug in the system, it's from the Beginner Box module importing unmigrated actors. If you grab new versions of the kobold warriors from compendium they will work.

**Comment by TikaelSol** [comment]
Foundry is aware of the issue https://github.com/foundryvtt/foundryvtt-premium-content/issues/170
