### ISSUE TITLE
token.distanceTo returning inaccurate measurements for elevated tokens. 

### ISSUE THREAD

**Issue by velara** [foundryvtt/pf2e#4824]
I've been testing token.distanceTo (I've implemented it here in TTA for ease of viewing, but I get the same results in the console with all modules disabled). 

Things mostly seem to work as you'd expect when everyone is at the same elevation, but if tokens are at different elevations the distance seems to increase a lot faster than one would expect. I've tested with ranged attacks and confirmed that those are using these same measurements for range penalties.

![image](https://user-images.githubusercontent.com/74130268/201760433-b8cdecf1-957f-40b3-aaa9-4da3014952f9.png)

In the above example the one token is only 5ft up, but the distance between it and the token on the ground increases by 40 feet. While there should only be a single diagonal required in this measurement. 

Replication: measure distanceTo between two tokens at different elevations.

**Comment by Drental** [comment]
I'll claim this bug and try to fix it over this weekend. Should be more in line with my skills :)
