### ISSUE TITLE
Alignment formating not working on character sheet

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4874]
![image](https://user-images.githubusercontent.com/62528192/202855763-463171b8-d243-4353-8e44-372688912523.png)

anything in the alignment box that is longer than the box just looks strange it would be cool if the box expanded when it was required to expand on that section of the character sheet.

**Comment by stwlam** [comment]
OS/browser?

**Comment by ThingsCouldGetDicey** [comment]
> OS/browser?

windows 11/ firefox

**Comment by ThingsCouldGetDicey** [comment]
the same thing is happening with the shield hp 
![image](https://user-images.githubusercontent.com/62528192/203166143-87b4ed17-d21a-4d4f-a5aa-c6ea59c7859e.png)
