### ISSUE TITLE
"Remove expired effects" non-functioning

### ISSUE THREAD

**Issue by roguedevjake** [foundryvtt/pf2e#4878]
**Browser:** Electron (foundry)
**Foundry:** 10.290
**PF2e:** 4.4.0
**Conditions:** Fresh campaign, no modules enabled 

The automation settings "Effects auto-expire" & "Remove expired effects" don't seem to be working at the moment. 

Effects say they have expired but keep their rule elements active, and expired effects are not removed automatically. I have tested this with existing effects/actors and newly made effects/actors.

**Comment by TikaelSol** [comment]
I can confirm this issue exists.

**Comment by ThingsCouldGetDicey** [comment]
i am experiencing the same issue with things that should expire for time and round effects.
