### ISSUE TITLE
Student of Perfection/Jalmeri Heavenseeker not found 

### ISSUE THREAD

**Issue by Rastamufasa** [foundryvtt/pf2e#4887]
Good morning, good evening or goodnight whenever you read this. With the new addition to Lost Omens: Impossible Lands it appears that the two archetypes and all that come with them are not found whatsoever in the newest update to the FoundryVTT. The rest of the book appears to be there and present, but none of the focus spells, reworks, or additions these two archetypes offer can not be found anywhere.

**Comment by TikaelSol** [comment]
![image](https://user-images.githubusercontent.com/80183198/202912788-866077ae-5bdf-436c-9940-515faf3990ce.png)

![image](https://user-images.githubusercontent.com/80183198/202912927-ee3de023-5d93-4508-b65d-f7492713f5eb.png)

Both of these have been in the system for a while, the archetypes are older and were reprinted in Impossible Lands. We have not checked them for errata yet, though we know that Heaven's Thunder got updated it just hasn't been updated in the system yet.

**Comment by Rastamufasa** [comment]
I'm 100% certain they've been erratad since they were not only reprinted but aspects to both have been either edited (for Jalmeri) and had focus spells added to them or edited (in regards to Student of Perfection). Student of Perfection has been heavily changed, while I believe the only change to Jalmeri was in fact Heaven's Thunder. I am fully aware they're both archetypes that have existed for a while, but if it was not only reprinted but altered heavily in the new book it should be added with the rest of the content, or at least an explanation as to why, photos of old archetypes that have been edited do nothing for me.
