### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by gideonpepys** [foundryvtt/pf2e#4889]
Just updated to Foundry v10.  I have disabled all modules.

Character sheets have no strike actions.  
AC has not been calculated for any PC actor with armor.
Initiative listed as NaN for all PCs and won't roll in Encounter tab.
XP tracker/counter in the top right corner scrolls over the end of the line so it reads, for example:
10/
1000
instead of 10/1000

**Comment by stwlam** [comment]
You have to update the system as well.

**Comment by gideonpepys** [comment]
Sorry, is probably a stupid question, but what do you mean by update the system?  Which system, where and through what?!?

**Comment by TikaelSol** [comment]
You need to update pf2e as well as foundry itself. If you're self hosting when you launch foundry you can update from the system tab when you first launch foundry. If you are using forge go to the bazaar and update the system. Visit the forge's discord if you need help with that.

**Comment by gideonpepys** [comment]
I'm on Forge.  The system is listed as updated, but the latest version is not the one running in my world.

**Comment by TikaelSol** [comment]
I suggest contact Forge support https://forge-vtt.com/contact since they are the ones who can help you with that, you may just need to stop the server and restart it but they can help much better than we can.
