### ISSUE TITLE
Lost Omens: Impossible Lands Student of Perfection/Jalmeri Heavenseeker not found in newest update 

### ISSUE THREAD

**Issue by Rastamufasa** [foundryvtt/pf2e#4891]
Good morning, good evening or goodnight whenever you read this. With the new addition to Lost Omens: Impossible Lands it appears that the two archetypes and all that come with them are not found whatsoever in the newest update to the FoundryVTT. The rest of the book appears to be there and present, but none of the focus spells, reworks, or additions these two archetypes offer can not be found anywhere.

I'm 100% certain they've been erratad since they were not only reprinted but aspects to both have been either edited (for Jalmeri) and had focus spells added to them or edited (in regards to Student of Perfection). Student of Perfection has been heavily changed, while I believe the only change to Jalmeri was in fact Heaven's Thunder however that is a needed quality of life change to the feat that makes it playable and viable for DMs to use. I am fully aware they're both archetypes that have existed for a while, but if it was not only reprinted but altered heavily in the new book it should be added with the rest of the content, or at least an explanation as to why.

**Comment by TikaelSol** [comment]
Posting the same issue a second time is not going to make me do it faster.

**Comment by Rastamufasa** [comment]
Not trying to make it be done faster, just saw the first post was closed before I could properly respond and elaborate.

**Comment by Rastamufasa** [comment]
If that causes frustration than I apologize, new to Github and just trying to resolve the issue after already jumping through multiple hurdles and loops to be able just to inform someone.

**Comment by Rastamufasa** [comment]
> Posting the same issue a second time is not going to make me do it faster.

Not trying to make it be done faster, just saw the first post was closed before I could properly respond and elaborate.
If that causes frustration than I apologize, new to Github and just trying to resolve the issue after already jumping through multiple hurdles and loops to be able just to inform someone.
