### ISSUE TITLE
Reroll with Hero Point covers damage buttons

### ISSUE THREAD

**Issue by RichardRobertson** [foundryvtt/pf2e#4894]
When rerolling an attack roll by right clicking the chat entry, the reroll covers up the damage and critical buttons. This makes it inconvenient to make those related rolls.

![image](https://user-images.githubusercontent.com/660510/202937597-def21508-2153-4908-9db9-3e40c93ce4e8.png)

**Comment by stwlam** [comment]
This is fixed in 4.4.0.

**Comment by RichardRobertson** [comment]
I wonder if the guy hosting just didn't update. Sorry for the unnecessary report. Couldn't find it when I searched the issues.
