### ISSUE TITLE
Feature Request: revamp the spell tab

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#4907]
![image](https://user-images.githubusercontent.com/62528192/203182181-35c6f9ec-3111-4620-a4d6-95e66019a868.png)

what i suggest is make it so that the sources are tabbed and linked to spell level with a tab beneath the sources. if you are multicassed in different spell sources and have multiple focus spells using the sheet you have to keep scrolling down and down to use it. 

what i propes is to have a tab full of sources. when you click on the source you get the spell level availble in seperate tabs. 

example:

Divine:                Occult:         focus spells: 
lvl1 lvl 2 etc.       Lvl 1 etc        

with them as tabs you can manage the spells alot easier. i dont know how feasible this is due to code but it would look neater and help with organisation of spells.

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated spell tracking issue, #4882
