### ISSUE TITLE
Spells with heightening type "fixed" don't display tradition or school when their level passes heightening threshold

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#5060]
1. Create new NPC actor
2. Change the actor's level to 5
3. Add Spellcasting entry
4. Add spell "Jump" in level 1 slot
        Note that it has the traits [tradition], Move, Transmutation
6. Drag the spell to level 2 slot
        Note that it has the traits [tradition], Move, Transmutation
8. Drag the spell to level 3 slot
        Note that it has the traits Move

Expected: it should have the traits [tradition], Move, Transmutation

Another example would be "Dimension Door" heightened from 4 to 5.

<img width="830" alt="Screen Shot 2022-12-05 at 10 55 08 AM" src="https://user-images.githubusercontent.com/1904698/205720351-66cf5cfc-f893-49be-931a-91c89ae1a13b.png">

**Comment by stwlam** [comment]
Followed reproduction steps, couldn't reproduce. Is this still an issue? Were some steps omitted?
