### ISSUE TITLE
Dragging an effect from sheet to macro toolbar returns wrong macro

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#5067]
When you have an effect on a character and drag it to your macro bar, it instead takes what seems to be the first ever item added to inventory, and creates a macro for that.

https://user-images.githubusercontent.com/32039708/205762433-b38f7c3b-b1d5-4534-8f63-e34cece445ab.mp4

**Comment by KSops** [comment]
Looks like the root cause is in `src/module/actor/sheet/base.ts#_onDragStart` when calculating `supplementalData`.

**Comment by MrVauxs** [comment]
https://github.com/foundryvtt/pf2e/blob/8b332690ba693fe7f44749f1be5b862a72ebf409/src/module/actor/sheet/base.ts#L611-L653

**Comment by TikaelSol** [comment]
Appears to have been fixed at some point.
