### ISSUE TITLE
Missing RE's and issues

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#5142]
- [ ] Shield cantrip Missing Immunity cooldown after it breaks.
- [ ] Shield cantrip failing to interact with damage cards block button
- [ ] oil of unlife not rolling dice upon consumption, missing dice input.
- [ ] less antiplague not having RE upon consumption no message to apply re.

**Comment by stwlam** [comment]
Please make separate issues for these, excluding the shield cantrip since that turned out to be a user error.

**Comment by ThingsCouldGetDicey** [comment]
> 

will do. the shield cantrip doesnt have an immunty re.  

and clicking the block button doesnt auto calculate the hardness and reduce the damage like a shield should.
