### ISSUE TITLE
Shield Cantrip missing Re for immunty to casting it again for 10 minutes.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#5145]
![image](https://user-images.githubusercontent.com/62528192/206932272-c7765b69-e224-4e8a-b293-1fbbd44722b7.png)
if it could work similar to how guidance works as in it auto applies immunity if broken.  and states the immunty re in the description for drag and drop that would be useful too!

**Comment by simonward** [comment]
Shield immunity and link was added:
https://github.com/foundryvtt/pf2e/pull/5010
