### ISSUE TITLE
Rogue No Longer Has Sneak Attack Encounter Check Box

### ISSUE THREAD

**Issue by nathankurt** [foundryvtt/pf2e#5146]
Hi, I've tried this on two servers, one completely clean and one with other add-ons that was running from somebody else's computers.  and it seems like the Rogue no longer has the option for a sneak attack in the encounter actions tab. 

Not sure if this is intentional or not but I never saw anything in the change log about it.

**Comment by stwlam** [comment]
You can restore them by enabling the "Theater of the Mind Toggles" system setting.
