### ISSUE TITLE
Add Flat-footed target toggle if a strike has the backstabber trait

### ISSUE THREAD

**Issue by thes33** [foundryvtt/pf2e#5169]
The theatre of the mind option doesn't seem to create the flat-footed target checkbox anymore.

**Comment by thes33** [comment]
How about a Monk with the Stumbling Stance which has the Backstabber trait?

**Comment by CarlosFdez** [comment]
That is a missing case. Thanks for bringing it up, re-opening it and edited the title.

**Comment by thes33** [comment]
Thanks!  Such as a specific edge case 😛

**Comment by daishimatt** [comment]
Additionally I've noticed this doesn't work if the character has the Rogue Archetype Sneak Attacker archetype feat

**Comment by TikaelSol** [comment]
The damage dialog removes a lot of the impetus for the TotM toggles
