### ISSUE TITLE
Feature Suggestion : Have an option to change "Common" to "Taldane"/"Mwangi"/... game-wide

### ISSUE THREAD

**Issue by Ddinistrioll** [foundryvtt/pf2e#5197]
Inspired by a recent reddit post, I decided to replace all mentions of Common by "Taldane" in my game (Age of Ashes, so Common is Taldane here), it's fluff but flavourful.

Of course, I was able to change all my players classes to include Taldane in place of Common, and with the use of the polyglot module, I was able to set the default spoken language to Taldane.

But Common still exists in my game, and unless I want to do my own version of the PF2e system (which seems a bit excessive imo), I can't remove it.
I would like to be able to set "Common" to another language from the settings, or even just change its name if it's simpler (I don't mind having Taldane appears twice in the language list)

I'm aware that it's a very niche feature, and to be honest I don't know if it's really worth it, but it doesn't cost much for me to suggest it. Worst case scenario you just close the issue. Best case scenario someone thinks of a easy way to implement it, and we have another small but cool flavourful feature :)

**Comment by stwlam** [comment]
"Common" isn't a language per se but a contextual shorthand for the trade language of a given region. You can see this usage in APs: Common is Mwangi in Strength of Thousands and Osiriani in Blood Lords. In each of those, NPC stat blocks in those books list the characters as know "Common," and Taldane will get separate mention if they also speak that. The system will follow suit, though it's possible that someone in the development community would be willing to write a macro or module.

**Comment by CarlosFdez** [comment]
For any module interested in doing such a thing, CONFIG.PF2E.languages.common being changed will change the display value for the common language system-wide.
