### ISSUE TITLE
feature request: custom calendars

### ISSUE THREAD

**Issue by jonbonazza** [foundryvtt/pf2e#5202]
I'm sure I'm not alone in that my world uses a different calendar than Golarion. For instance, in my world, there are 6 days a week rather than 7 etc... and of course the days of the week are differently named than those of Golarion as well. It would be nice if the module had support for custom calendars for better immersion in homebrew worlds.

**Comment by Drental** [comment]
the system implements the rules and setting of Pathfinder 2e and Golarion. If you want to use another setting for your calendar I suggest using a module to display the time.

Making this fully configurable is just out of scope.
