### ISSUE TITLE
New check styles are not working

### ISSUE THREAD

**Issue by Far2Casual** [foundryvtt/pf2e#5203]
![image](https://user-images.githubusercontent.com/63196064/207967319-2852e0ef-95da-44dd-9923-c1f10061b77d.png)

https://github.com/foundryvtt/pf2e/blob/fb3ad0c2817354149721f3e7d9c5a55cd527a250/src/styles/ui/sidebar/chat/_check.scss#L19

**Comment by stwlam** [comment]
Try disabling Dorako UI.
