### ISSUE TITLE
Domain Initiate only specifies Domain in name when added as a feat

### ISSUE THREAD

**Issue by AndroidSalmon** [foundryvtt/pf2e#5211]
When the Cleric class is added to a sheet, popups walk the player through to select their deity, doctrine, and domain. Deity and First Doctrine get the choices appended like so: First Doctrine (Cloistered Cleric), but this doesn't happen for Domain Initiate.

Curiously, this does happen when you manually add Domain Initiate as a Class Feat:
![image](https://user-images.githubusercontent.com/25198736/208152594-8b96f8c8-c5ed-4226-87be-a638e7c466af.png)

**Comment by stwlam** [comment]
Fixed by #5289
