### ISSUE TITLE
Official Abomination vaults - Missing things

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/pf2e#5216]
I only looked at this within the Forgotten Adventures map, can't speak for the other.

Doors that should be locked as per there description:

- E18
- Two Doors South of F7
- F25
- H46
- I05 (To the west)
- I14
- I19
- I54 and I55
- I60 (To the north)
- J5 

H41 is missing 4 Drow Hunters

H26, the Secret Treasury should have Greater Braces of Missile Deflection, not Standard

In H06, for the item Key to Area A7, should be : Key to Area H7

In H4, you are missing 3 x beautiful amethysts worth 20 gp

**Comment by TMunsie** [comment]
Closing as not having to do with the system

**Comment by WaterpoloBlock** [comment]
Thank you, my mistake.

**Comment by TMunsie** [comment]
> Thank you, my mistake.

This is the right place to report it :)

https://github.com/foundryvtt/foundryvtt-premium-content/issues/new?assignees=&labels=bug&template=bug-report.yml
