### ISSUE TITLE
Support module art for items

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#5230]
Expand the Compendium Actor Image mapper to also apply to non-Actor entities, and more specifically, all Item entities, such as equipment, spells, feats, class features, etc.

https://github.com/foundryvtt/pf2e/blob/3da4d309a35253f75a89c79436150238a12d7a07/src/scripts/register-module-art.ts#L3-L88

**Comment by stwlam** [comment]
Not likely to ever happen
