### ISSUE TITLE
Hazard: Perilous Flash Flood

### ISSUE THREAD

**Issue by manfred7168** [foundryvtt/pf2e#5326]
This hazard has a item "Filth Fever": I'm wondering if this item is wrong (maybe from an other hazard ?).
The hazard is from the gamemastery guide, but I did not find any filth fever in this hazard (page 80 f.).

**Comment by TMunsie** [comment]
Repulsive refuse, the third bullet point.
"Additionally, creatures who come into contact with the flood waters are exposed to filth fever (DC 20 Fortitude, Bestiary 258)"
