### ISSUE TITLE
Feature Request: Alternate Ability Scores from GMG

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#535]
In GitLab by @giganogravidon on Jun 11, 2020, 19:12

Hello, I would like to request incorporation for the Alternate Ability Scores system added in the GMG if possible. It combines strength and constitution, splits dexterity into dexterity and agility and moves will saves to use charisma. 

I have dug around in the files for the git, hoping to find out where hp values are called from so that I could follow those callouts through the rest of the documents, but I simply can't find anywhere that would say "HP is calculated using class hp * level + ancestry hp + Con Mod + Bonus + Bonus/level" I know it wouldn't actually look like that, but I am not even finding anything that would let me get a grip on this git. 

It's very complex and I applaud you on how thoroughly built it is, but I am just trying to convert a game from roll20 to foundry that is currently already using the alternate ability scores rule with a modified character sheet I made and I can't find any way to do it. Any advice would be great!

**Comment by stwlam** [comment]
This variant is dropped in GM Core, so we won't be implementing it.
