### ISSUE TITLE
IWR should apply after manual multipliers and adjustments

### ISSUE THREAD

**Issue by tuhs1985** [foundryvtt/pf2e#5401]
IWR applies weakness damage for spells prior to doubling damage, which leads to weakness damage being doubled as well.   Per damage rules (copied below) damage is calculated and doubled in step 1. In step 3 immunities, weakness,and resistance is applied. 

1. Roll the dice indicated by the weapon, unarmed attack, or spell, and apply the modifiers, bonuses, and penalties that apply to the result of the roll. https://2e.aonprd.com/Rules.aspx?ID=336
2. Determine the damage type.
3. Apply the target’s immunities, weaknesses, and resistances to the damage.
4. If any damage remains, reduce the target’s Hit Points by that amount.

**Comment by tuhs1985** [comment]
Most likely a result of the way spell damage is doubled, via the chat button after the roll.

**Comment by stwlam** [comment]
Critical damage rolls aren't supported for spells.

**Comment by CarlosFdez** [comment]
I don't think this is so much a support critical damage issue as it is an order of operations thing and a request for the "double", "half", and "triple" buttons to apply their doubling/halving/triple before IWR.

**Comment by stwlam** [comment]
It's an issue that only affects spells for lack of critical damage support. The OP is under the mistaken impression that doubling damage values is functionally that.

**Comment by CarlosFdez** [comment]
Are there situations in which doubling/halving/tripling damage would double apply IWR? I'm not aware of any.

Those buttons only exist because of criticals and basic saves. I'm not aware of any other purpose.

We do need critical damage spell support, but this is unrelated.
