### ISSUE TITLE
Variant Request: Gouging Claw

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#5404]
Doubt it was overlooked, most probably already in the pipe somewhere.

**Comment by TikaelSol** [comment]
What about it needs a variant?

**Comment by Symon-S** [comment]
@TikaelSol

It's like telekinetic projectile.
It's a choice between two damage types.
[Gouging Claw](https://2e.aonprd.com/Spells.aspx?ID=920)
