### ISSUE TITLE
Blood Vendetta has invalid formula data

### ISSUE THREAD

**Issue by plaidScience** [foundryvtt/pf2e#5405]
I had a migration issue with Blood Vendetta, where after migrating the spell's damage was incorrectly set in a character sheet as:
```json
"damage": {
          "value": {
            "0": {
              "applyMod": false,
              "type": {
                "categories": [],
                "subtype": "",
                "value": "bleed"
              },
              "value": "2d6 persistent"
            }
          }
        },
```
Instead of migrating to the newer version in the compendium

Foundry Version 10
Build 286
PF2E Version 4.6.0

**Comment by TMunsie** [comment]
Data in the compendium seems correct.

![image](https://user-images.githubusercontent.com/25963508/211053833-c21c74f8-859c-47f2-b4ff-0934f5853331.png)

**Comment by stwlam** [comment]
Fixed some time ago, it appears
