### ISSUE TITLE
Alignment Ampoules Add Strength to Damage 

### ISSUE THREAD

**Issue by velara** [foundryvtt/pf2e#5432]
![image](https://user-images.githubusercontent.com/74130268/210254005-21022c79-c00d-4cc4-a486-9e9badeb29d3.png)

All of the Alignment Ampoules, Lesser, Moderate, Greater and Major add strength to their damage rolls, while other bombs correctly do not.

**Comment by simonward** [comment]
It's specifically the splash trait that calls for withholding a character's strength ability modifier. CRB p. 544
This is probably an oversight, but according to RAW it would include strength.

**Comment by velara** [comment]
Wild, I stand corrected then.

**Comment by stwlam** [comment]
@velara We're going to go ahead and add the splash trait to those.
