### ISSUE TITLE
Double Number of Dice on Critical Hit Rule Doesn't Function 

### ISSUE THREAD

**Issue by HarryCuddletrousers** [foundryvtt/pf2e#5439]
![Screenshot 2023-01-02 154144](https://user-images.githubusercontent.com/40306844/210279987-1be2b621-9757-48a9-8d6d-c770fb330ddb.png)
![Screenshot 2023-01-02 154255](https://user-images.githubusercontent.com/40306844/210279992-abbf29d4-ebcb-46c1-bedc-3559eb1601be.png)

**Comment by jdwpom** [comment]
It probably doesn't need to be said, but for the sake of completeness, this issue arose with v4.6.0. "Double the Dice" works fine on all versions of 4.5.
