### ISSUE TITLE
Add predicate to determine whether a spell being cast is a cantrip

### ISSUE THREAD

**Issue by AFigureOfBlue** [foundryvtt/pf2e#5457]
For the Ancestors oracle mystery, the bonuses from the Spellcasting ancestor currently only apply to spells cast from spell slots; they should instead apply to all non-cantrip spells. Currently, things like focus spells, innate spells, and spells cast from items are not including the bonus (and for an oracle, focus spells are pretty essential). There doesn't seem to be a predicate (at least, not one that I've found) that would allow the curse's rule element to apply to all non-cantrips. An appropriate predicate will need to be made available, most likely in `SpellPF2e::getRoleOptions`, before the curse's rule elements can be adjusted.

**Comment by TMunsie** [comment]
Does {spell-cast||spell-attack}" && ¬"cantrip" not work as a predicate? There are probably some weird things like ancestral memory that just won't work because they don't do anything with respect to card generation (You're proficient in a lore for 10 minutes) since they're a utility spell without anything else. Not super familiar with ancestor oracles. But the roll inspector is really helpful in figuring stuff like this out :)

**Comment by AFigureOfBlue** [comment]
The roll inspector is awesome, but unless I'm missing something, it doesn't seem to be available for the damage or healing roll of a spell, which is what this would need to apply to in order to adjust the damage for the relevant spells which aren't currently being affected (such as focus spells). Is there some way to enable the roll inspector for spell damage rolls?

**Comment by TMunsie** [comment]
![image](https://user-images.githubusercontent.com/25963508/210408237-05d99be0-99a3-4a88-9f06-944f056c7b80.png)

This focus spell is inspectable? I know Supe was changing something and this is on master so it might be unreleased, but that seemed to work fine.

![image](https://user-images.githubusercontent.com/25963508/210408622-33eefa2d-cb61-496c-95fa-cd336f5f9ee7.png)

No problem inspecting focus cantrips either

![image](https://user-images.githubusercontent.com/25963508/210408744-402fb4c9-a0cf-4c76-970b-b27b4966f2b1.png)

Or for healing spells

**Comment by AFigureOfBlue** [comment]
Ah! Got it... I was trying to look at the damage roll itself rather than the spell's card, and there is indeed a way to target cantrips with a predicate. I'll close this and create a pull request to fix the curse. Thanks for your help; knowing about the roll inspector is going to be really helpful going forward.

**Comment by TMunsie** [comment]
> Ah! Got it... I was trying to look at the damage roll itself rather than the spell's card, and there is indeed a way to target cantrips with a predicate. I'll close this and create a pull request to fix the curse. Thanks for your help; knowing about the roll inspector is going to be really helpful going forward.

Yeah, it is a ridiculously awesome tool for making stuff "just work" :)
