### ISSUE TITLE
Homebrew damage types are invalid for Flat Modifier Rule Elements

### ISSUE THREAD

**Issue by ByronThompson** [foundryvtt/pf2e#5475]
Attempting to add a homebrew damage type via a Flat Modifier rule element results in the warning 
`PF2e System | Flat Modifier rules element on item ItemName(ActorID) failed to validate: Unrecognized damage type: DamageTypeName`
Even if the homebrew damage type is registered in the settings beforehand

PF2E Version: 4.6.2

**Comment by stwlam** [comment]
You'll want to use the slug generated for the damage type you added:
![image](https://user-images.githubusercontent.com/106829671/210475625-09b0dda1-de37-482b-a4ab-241e3c20c1b5.png)
