### ISSUE TITLE
Add new rules for 2 free ancestry boosts to any ancestry as announced by Paizo

### ISSUE THREAD

**Issue by DawidIzydor** [foundryvtt/pf2e#5484]
In the last community blog post Paizo announced that every ancestry will get option to get 2 ancestry boosts (eg. a dwarf will have a choice of either getting 3 boosts + penalty or 2 boosts no penalty). Add this option to Foundry 

https://paizo.com/community/blog/v5748dyo6si7o

**Comment by TMunsie** [comment]
1) Coming onto the github repository and saying "Add this" without offering to do it yourself is, at best, impolite. Please phrase this as a feature request in the future
2) We had no forewarning and still released all the other errata changes within three hours of finding out they existed
3) This has already been discussed on the discord; code changes take time but we think we'll have it in by the weekend
4) You already have a workaround in that you can edit an ancestry on the character sheet to just have free boosts, or you can turn on manual mode for ability scores and accomplish this, so this already exists as an option in Foundry

Please don't come and phrase requests as demands or instructions. Everyone working on this does so for free as volunteers.

**Comment by TMunsie** [comment]
Closed by #5507
