### ISSUE TITLE
Custom Languages stopped being shown on statblocks

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#5511]
See any Leshy statblock to notice that "Speak With Plants (Some Plant)" has disappeared.
It is still inside the data, it's just not rendered.

**Comment by MrVauxs** [comment]
![image](https://user-images.githubusercontent.com/32039708/211100465-f62176f3-f073-46c5-9575-d0a169e587e2.png)

**Comment by simonward** [comment]
Some overlap with https://github.com/foundryvtt/pf2e/issues/5139

**Comment by MrVauxs** [comment]
This has been fixed.
