### ISSUE TITLE
Missing flags.core.sourceId for some creatures spells

### ISSUE THREAD

**Issue by chepseskhaf** [foundryvtt/pf2e#5552]
The spell item entries of some creatures are missing a flags.core.sourceId property. I am willing to add them with a PR but I am wondering if there is some kind of automated procedure I should be aware of before doing that.

Here is the list:

> Creature: zgvD5MpjPBJXIian (Elite Duergar Taskmaster), Spell: WoACkCLAuT1uY3dK (Detect Magic)
> Creature: zgvD5MpjPBJXIian (Elite Duergar Taskmaster), Spell: Ob9lTYH0z6rkHmab (Shield)
> Creature: zgvD5MpjPBJXIian (Elite Duergar Taskmaster), Spell: IpXRefjnVznYbwGq (Fear)
> Creature: zgvD5MpjPBJXIian (Elite Duergar Taskmaster), Spell: E6OwEipVXIOV6Q6D (Harm)
> Creature: zgvD5MpjPBJXIian (Elite Duergar Taskmaster), Spell: 0V3XCIr5wtgNSFIb (Magic Weapon)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: mobb4GMsJroiE7xE (Daze)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: FoIqFtxgCDHgat9H (Detect Magic)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: WiDrFJEwfiaj8akl (Guidance)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: LaOs3udAveP0bFKf (Message)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: dDqKeIY02hOi9n0h (Shield)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: D0rr4Bdn5tiMhoP9 (Command)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: nmV0GZiUjwYo1hC6 (Purify Food and Drink)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: QFHzSVUXVe6rLw21 (Sanctuary)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: hLF8EZcDa1WVJGw3 (Darkness)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 04ZpQV0ZccJk1gbf (Silence)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 9pwzHDuplGLkryLK (Spiritual Weapon)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: MS8jaE6kgDAZsh8a (Crisis of Faith)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: VtL81QoSuUQ8oWv9 (Locate)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: zU3peH3ieSmobc9f (Neutralize Poison)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: aFjnNL2HQKdIIvue (Air Walk)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: dJG397B9pyKkszm9 (Discern Lies)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 44pCO8XDmv81KlVO (Divine Wrath)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: nAkd1LGXAv5IABHU (Abyssal Plague)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: qUroqhViyScUmYZC (Heal)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: tWhnvZ6cwojkmMyM (Sending)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: gpFvmxU8eWEvAYHU (Blade Barrier)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 4ze69EbDd5LZUFPp (True Seeing)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: fgWf0rfolGTPWeOL (Heroism)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: qTgUyoO78c3KLZWj (Divine Decree)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: Jt8IUfmUA2q67bI7 (Energy Aegis)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: igVfSPNKL3hkWWMK (Regenerate)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 76ufX5SvCYZi4uHm (Harm)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 76ufX5SvCYZi4uHm (Harm)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 76ufX5SvCYZi4uHm (Harm)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 76ufX5SvCYZi4uHm (Harm)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 76ufX5SvCYZi4uHm (Harm)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 76ufX5SvCYZi4uHm (Harm)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: 7ZkTtGhzW9vl5m7F (Spirit Blast)
> Creature: gIcReNQOZceZBBlw (Jonis Flakfatter), Spell: JIukVFodGJ3G8fxH (Spiritual Epidemic)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: dJaxJkNHo3BQJy27 (Detect Magic)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: OcI6SrhOrjTM6joe (Ghost Sound)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: xAfhGIMGCj7NPK77 (Message)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: gqoxRUq74GYLkPPz (Shield)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: 5W8jGY13y07XUbFH (Telekinetic Projectile)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: NPyxoVX5xBt06l1D (Alarm)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: l19HYxWfqe5tThta (Color Spray)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: mn80YDbRe0CR2jK5 (Mage Armor)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: kE16hHjXiE3GjFqD (Acid Arrow)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: BbLUZEJ8LgUkfDwG (Illusory Creature)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: 19pPrnbEoRumwPfP (Knock)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: F6Gh5Mx7nKHmFzeI (Invisibility Sphere)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: HA533P8kpEcItk8S (Lightning Bolt)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: CHXAYqBhknsvGNPr (Nondetection)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: PX3dDORh5j4SWAYX (Confusion)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: 4tt6ZjdR5AJPuI45 (Dimension Door)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: CVQP4H4oCMMxPma2 (Fly)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: GshKiFiTw3EMBRPS (Black Tentacles)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: z6DANJPlG3nUSWMY (Cone of Cold)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: nysa73evCu3cVthj (Mind Probe)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: yiu28YWKf5a9dOhD (Feeblemind)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: JK3UzmKMWgBkwhqU (Teleport)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: FQBTisR9Aly8BG9W (True Seeing)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: bHTnUEgmHf8mTmyp (Prismatic Spray)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: bHTnUEgmHf8mTmyp (Prismatic Spray)
> Creature: E7NEf3kmsY3YjRrz (Kapral), Spell: bc9CZ1CgVPE4CZuF (Project Image)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: ruFTy9QBfVOSgfrQ (Daze)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: 5ao9e21GLNolUu3d (Detect Magic)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: bBP5paBs5zv52eEK (Light)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: uUd8CA9kphY5EMGn (Guidance)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: mmTns1JwirRAD6nL (Message)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: KUIOOFW03yBmRna4 (Command)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: DPi2HANSFfPvyRUJ (Fear)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: Khlm4Iwf1x3BS2st (Sanctuary)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: BEAGkjpg5yhEXzej (Illusory Disguise)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: 2BYv7z4AlfSVjKp3 (Invisibility)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: bS8S7XTluSjedTSK (Silence)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: yDV7MJ90evr3fw1y (Blindness)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: MvLDQhfOMGUHTa0R (Chilling Darkness)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: F11KFxQ50r7xgYdz (Heal)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: zhMfQkFZ0hhJdLWx (Air Walk)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: WedwiYgwc772vAzT (Freedom of Movement)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: 2BYv7z4AlfSVjKp3 (Invisibility)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: PPHtO7ucN8XPtMpm (Death Ward)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: rvjaOuDjs6Lx1VBW (Flame Strike)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: IFm22AWWvNGTwrjw (Shadow Blast)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: CiEkk3kCZJeaOIAU (Phantasmal Killer)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: 0OslKTT14j6ykRGI (Vampiric Exsanguination)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: F11KFxQ50r7xgYdz (Heal)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: yoPJQCGIJ17BGhyB (Harm)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: yoPJQCGIJ17BGhyB (Harm)
> Creature: LkaB8RH73DY4TO9V (Priest of Blackfingers), Spell: yoPJQCGIJ17BGhyB (Harm)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: pWK06Kgl5iyfU6aw (Chill Touch)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: nRzgYZoyIrAtOzOr (Daze)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: kRfg0D4W3F4lPM7U (Detect Magic)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: Aoc8l4MrB0LvtWbp (Guidance)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: DIVRJuQRoG3tKOZX (Message)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: xLWlxZtrGyFgwOoI (Command)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: c7WkNfRwCUpyMatM (Detect Poison)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: qEAlnIRkW8Qpao3n (Illusory Disguise)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: 3ihpX9W8DKeOjv6y (See Invisibility)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: bby5t2H9ih7GSUss (Silence)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: U8tEh3mwcTd0dR2H (Undetectable Alignment)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: 7CJkSVILe6tpyBpc (Crisis of Faith)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: Aa9Ra6VSUBOx4NHV (Locate)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: 7pjSG9jjciwc6dLt (Zone of Truth)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: XRMpVQRUoTSPVJ0X (Discern Lies)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: WvNNCJWxolYCVYdw (Invisibility)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: ftKSUEEhKEWFMHfd (Outcast's Curse)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: kEDYNjP5aBoo6XlE (Flame Strike)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: EQvGP4B1k4AL724e (Phantasmal Killer)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: zky5awLV2KcSRgKf (Prying Eye)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: MM8wXmIOTPwvy3O3 (Blade Barrier)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: z1Tf1xdViuWNLH1C (Heal)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: jhp9r5dEwYeBXEHw (True Seeing)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: ODiIxUqf1OTFYvob (Divine Decree)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: 7QIoSVh7zTgR64x2 (Finger of Death)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: 5HnfbOGWfzz1BGeU (Harm)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: IAvNqKuqzpSHUsw1 (Harm)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: 6eiEyE1s8fUhFfp0 (Harm)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: ogacgYPyipwYeeFG (Harm)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: USsNx8le6w23Cuit (Eradicate Undeath)
> Creature: BCMkxoQB4xK4BniG (Secret-Keeper), Spell: 3B8YuNJMUtM4Y54i (Death's Call)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: C0dAbBjbX3zfRYHu (Acid Splash)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: uDcrqvy7nT8wRuya (Detect Magic)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: uLXB4azkilViHlVe (Light)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: Oj1MnlRwsWtsAP5P (Ray of Frost)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: 9RN6TnYwuZ7OhKPp (Shield)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: mruWNaaGy8lyRoDS (Grease)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: FqD7QFN6kMNOijcZ (Hydraulic Push)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: Wc17cLt13V8IV76B (Mage Armor)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: cEN9uItOTHC8a2B4 (Acid Arrow)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: cEN9uItOTHC8a2B4 (Acid Arrow)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: jlNY26G4LGeXhQHW (Water Walk)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: e4u5w7Xd9FtKGLC4 (Haste)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: fyDaF0edDs6h4goa (Slow)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: L27fI7jDagUtgUk1 (Stinking Cloud)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: DPsxWu6UJ6fCkhYV (Fly)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: qCPrbscSWVdcRzrb (Hydraulic Torrent)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: WRbjZ7jYClC80VoB (Solid Fog)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: NCRXrahZPGoum9pB (Cone of Cold)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: dqdb87Tat2B4NGXw (Wall of Ice)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: FqD7QFN6kMNOijcZ (Hydraulic Push)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: FqD7QFN6kMNOijcZ (Hydraulic Push)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: qCPrbscSWVdcRzrb (Hydraulic Torrent)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: 7eJx42PPG8nPZ6Gu (Disintegrate)
> Creature: N1IpUIW2Ry7uBN3G (Tiderunner Aquamancer), Spell: OUpeiV93KlaVlpUz (Spell Turning)

**Comment by stwlam** [comment]
Fixed by #7035
