### ISSUE TITLE
Request: Enable a second class attribute when dual class is enabled

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#5612]
Since each class gives you one different attribute, for example Barbarian gives Str and Inventor gives Int, it should be allowed to take 2 attributes on the class during character creation, make the second attribute optional is the best option since it gives the user the option of how to handle overlaping attributes from both classes

**Comment by LogosWorks** [comment]
Of Possible note. https://www.reddit.com/r/Pathfinder2e/comments/fkl10a/would_dualclasses_characters_gain_the_key_ability/
I have yet to hear any official rule on this and it would be nice to see the ability to allow each.

**Comment by sambomb** [comment]
It’s a optional rule, I don’t think we will get any official rule on that

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Thomas ***@***.***>
Enviado:sexta-feira, 31 de março de 2023 01:44
Para: ***@***.***>
Cc:Samir ***@***.***>; ***@***.***>
Assunto: Re: [foundryvtt/pf2e] Request: Enable a second class attribute when dual class is enabled (Issue #5612)


Of Possible note. https://www.reddit.com/r/Pathfinder2e/comments/fkl10a/would_dualclasses_characters_gain_the_key_ability/<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.reddit.com%2Fr%2FPathfinder2e%2Fcomments%2Ffkl10a%2Fwould_dualclasses_characters_gain_the_key_ability%2F&data=05%7C01%7C%7Ce04ab6e8a4b4446fb84b08db31a2a4d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638158346855941344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XoUbotiRnrbOSk2lgp1pk7pz96IBVYQ5H1U6VkuHXFw%3D&reserved=0>
I have yet to hear any official rule on this and it would be nice to see the ability to allow each.

**Comment by stwlam** [comment]
Closing as stale and soon to be irrelevant.
