### ISSUE TITLE
Applicable divine intercessions should have IWR automation 

### ISSUE THREAD

**Issue by DoctorDankovsky** [foundryvtt/pf2e#5666]
Hello. I ask you to update the effects that give additional damage, impose weaknesses, impose resistance **pf2e.bones-and-curses** to IWR.

**Comment by stwlam** [comment]
Are you talking about the effects in Deity Boons & Curses? Did you have one or more among those in mind?

**Comment by DoctorDankovsky** [comment]
There is. Asmodeus - Minor Curse and Moderate Boon - Weakness/Resistance fire 5. Gozreh - Minor Curse - Weakness electricity 5. Sarenrae - Moderate Boon - 1d6 damage fire (ignores resistance), Pharasma - Moderate Boon - 1 positive damage to Strikes, a status bonus of +1 to positive damage per spell level, a status bonus of +1 to recoverable HP per spell level. Shizuru - Moderate Boon - You can choose from additional 1d6 fire damage or 1d6 good damage with each attack. Arazni also has Moderate Curse - persistent damage equal to twice the difference between the level of the cursed and his enemy (if the enemy's level is lower).

**Comment by DoctorDankovsky** [comment]
There are also such options (but this does not really apply to IWR anymore) as Iomedae - A Minor Curse - 50% HP and BT for weapons, armor and shields. Major Boon - Axiomatic rune effects, Holy and Striking (Greater) to weapons in your hands (but no more than the allowed number of rune effects), Moderate Curse - the cursed ignores all circumstance bonuses to his attack rolls, and his enemies ignore all circumstance penalties to attack rolls on him. Gorum also Minor Curse that reduces the HP and BT of armor and shields by half, but also reduces the item's bonus to KB by 2 (minimum 0).
