### ISSUE TITLE
Background Ability Boost Not Giving Free Option

### ISSUE THREAD

**Issue by john-gelinas** [foundryvtt/pf2e#5701]
Trying to choose the background ability boost during character creation and while the SRD says "One must be to Constitution or Wisdom, and one is a free ability boost." for the Wandering preacher, foundry is forcing me to pick both Con AND Wis.

**Comment by simonward** [comment]
Unable to reproduce.

<img width="755" alt="Screen Shot 2023-01-14 at 12 10 43 PM" src="https://user-images.githubusercontent.com/1904698/212494454-2f5c7720-80b9-4e8d-aa6f-0c75639060a3.png">

**Comment by john-gelinas** [comment]
Now I am also unable to reproduce as well. My apologies.

**Comment by simonward** [comment]
It's possible there's an issue here, if you can find reproducible steps.

This was reported a month ago:
https://github.com/foundryvtt/pf2e/issues/5168

**Comment by john-gelinas** [comment]
Will watch as I create new characters to see if it reoccurs. Thanks!
