### ISSUE TITLE
Request: Character sheet for companions 

### ISSUE THREAD

**Issue by Brandoff1392** [foundryvtt/pf2e#5746]
Maybe a new sheet similar to the familiar sheet, but for companions.

**Comment by simonward** [comment]
In the meantime, try out PF2e Companion Compendia:
https://foundryvtt.com/packages/pf2e-animal-companions

**Comment by Brandoff1392** [comment]
Ok i will definitely check this out. Thank you

**Comment by TMunsie** [comment]
Closing as Duplicate of #802
