### ISSUE TITLE
Concussive trait not used in IWR logic

### ISSUE THREAD

**Issue by codeadsa** [foundryvtt/pf2e#5756]
Issue: Using a Dueling pistol (shows concussive trait), but the damage roll shows 1d6 Piercing target is a Skeleton Guard with resistance 5 piercing.

Result: The Skeleton guard pierce resistance 5 takes place, ignoring concussive trait of gun.

I'd like the concussive trait to apply the bludgeon damage to the skeleton.

**Comment by iBoMbY** [comment]
If someone is at it, the same would probably make sense for "versatile" weapons.

**Comment by TMunsie** [comment]
> If someone is at it, the same would probably make sense for "versatile" weapons.

Concussive should autoapply because the trait says you get the better of the two. Versatile weapons should be a player selection, not an automatic "choose the best" because there is no such clause. Same with modular.
