### ISSUE TITLE
Bug: Applying roll result to token causes "chat-message is not a valid selector"

### ISSUE THREAD

**Issue by robinsving** [foundryvtt/pf2e#5764]
Sometimes when trying to apply damage to a selected token the nothing happens. 

In console the following message is shown:
`Uncaught (in promise) DOMException: Element.querySelector: 'li.chat-message[data-message-id=1LcVbW7x8W2m63h1]' is not a valid selector`

The chat and Inspect looks as follows. Not sure why the selector is invalid. 
![image](https://user-images.githubusercontent.com/3072502/212772743-965eae06-90f8-4c0d-b935-0ab1e996cb80.png)

Removing all add-ons changed nothing.
Restarting does nothing.
Applying damage on another token, of course does nothing.

**Comment by TMunsie** [comment]
Can you confirm your Foundry and PF2e versions are 10.291 and 4.6.7?

**Comment by robinsving** [comment]
Confirmed

**Comment by TMunsie** [comment]
Can you replicate this with all modules disabled and clearing cache (ctrl+f5) after all modules are disabled please :). (I can tell some are on in that screenshot and it'll reduce possible causes.)

**Comment by TMunsie** [comment]
And because I forgot, do this from a new strike and damage card. If a module modified a card then it'll still have whatever code the module injected is.

**Comment by robinsving** [comment]
I have managed to recreate it from a new strike + damage after clearing cache

**Comment by TMunsie** [comment]
OK. I logged onto the world and after attempting 15 times it did create a chat message card that could do this. For reference this did have the card option off as triple damage it present.

**Comment by TMunsie** [comment]
![image](https://user-images.githubusercontent.com/25963508/212775034-41fc8994-aef0-469f-9e02-36f9126469ee.png)
