### ISSUE TITLE
Incorrect Rule Element Example on the quickstart guide wiki page

### ISSUE THREAD

**Issue by MindlessReader** [foundryvtt/pf2e#5774]
I found an error on the [Quickstart guide for rule elements](https://github.com/foundryvtt/pf2e/wiki/Quickstart-guide-for-rule-elements#immunity-weakness-resistance). The example that shows how to make a rule element that grants resistance to all damage except force doesn't work. I was able to get it working by using "all-damage" instead of "all" as the example did, so that might be the fix, but I'm no expert.

**Comment by TikaelSol** [comment]
Thanks for the catch. Fixed it.
