### ISSUE TITLE
"Raised by Belief" background provides only 1 Ability boost instead of 2

### ISSUE THREAD

**Issue by lafflam** [foundryvtt/pf2e#5790]
The Raised by Belief background is supposed to provide a total of two Ability boosts. One boost must be to an ability specified in the Divine Ability entry for your deity, and one is a free ability boost. However, after creating a new character, selecting my deity and selecting the "Raised by Belief" background, I am only provided with a total of 1 (free) Ability boost for my background choice. I do not have any way to select my second boost according to my deity's Divine Ability.

Expected behavior: At the very least I would expect to be provided two free boosts, one to assign manually in accordance with the Divine Ability entry for my deity, and one for a free ability boost. Ideally of course, the Divine Ability boost would be assigned and locked like other keyed boosts, and the remaining Ability boost would be left for free assignment.

**Comment by simonward** [comment]
"Harrow-Led" is also missing a boost.
