### ISSUE TITLE
Have "Torch is Lit" for Everburning Torch

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/pf2e#5791]
It is implied an Everburning Torch provides the same light as a normal torch. 

I know in the system, when a torch is equipped, the toggle for "Torch is Lit" shows up under the Actions tab. It would be nice if the Everburning Torch could have the same functionality.

**Comment by stwlam** [comment]
The everburning torches, as its name suggests and description explicitly states, is always lit.
