### ISSUE TITLE
Changing Damage types for Versatile weapons

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/pf2e#5793]
Pretty sure this is easier said then done.

It is rather clunky to change the damage types for Versatile weapons. It would be great if when rolling damage, for versatile weapons, it prompts you for what damage type it should be then does the roll.

**Comment by xyzzy42** [comment]
Now that IWR is in, tons of people are asking for this.  I think something well designed is planned for the future.

But in the meantime, you can add REs that make toggles, which you can set _before_ rolling damage.  Any toggle can be dragged from the character sheet actions tab to the macro bar to make a toggle macro.  So this is reasonable convenient to use.  Just have to remember that you wanted to change before you roll.

Add to a weapon, or a deity boon or feat.  The toggles will affect all your appropriately versatile weapons.

```
{"key":"DamageDice","selector":"damage","override":{"damageType":"piercing"},"predicate":["item:trait:versatile-p","use-versatile-p"]}
{"key":"DamageDice","selector":"damage","override":{"damageType":"slashing"},"predicate":["item:trait:versatile-s","use-versatile-s"]}
{"key":"DamageDice","selector":"damage","override":{"damageType":"bludgeoning"},"predicate":["item:trait:versatile-b","use-versatile-b"]}
{"key":"RollOption","option":"use-versatile-p","label":"Use versatile Piercing damage","domain":"damage-roll","toggleable":true}
{"key":"RollOption","option":"use-versatile-s","label":"Use versatile Slashing damage","domain":"damage-roll","toggleable":true}
{"key":"RollOption","option":"use-versatile-b","label":"Use versatile Bludgeoning damage","domain":"damage-roll","toggleable":true}
```

**Comment by WaterpoloBlock** [comment]
Thank you very much, I'll play around with it. And have my fingers crossed for this feature to be added sometime.

**Comment by esheyw** [comment]
[here's](https://drive.google.com/file/d/1B2W-WyMIDOLpISIgZG3rknun85T67zd4/view?usp=share_link) a premade feat to import with just those 6 REs on it.

**Comment by WaterpoloBlock** [comment]
> [here's](https://drive.google.com/file/d/1B2W-WyMIDOLpISIgZG3rknun85T67zd4/view?usp=share_link) a premade feat to import with just those 6 REs on it.

Thank you

**Comment by Ghostdesu** [comment]
Here's the same thing from above adapted for the Modular B, P, or S trait 
```json
{"key":"DamageDice","selector":"damage","override":{"damageType":"piercing"},"predicate":["item:trait:modular","use-modular-p"]}
{"key":"DamageDice","selector":"damage","override":{"damageType":"slashing"},"predicate":["item:trait:modular","use-modular-s"]}
{"key":"DamageDice","selector":"damage","override":{"damageType":"bludgeoning"},"predicate":["item:trait:modular","use-modular-b"]}
{"key":"RollOption","option":"use-modular-p","label":"Use modular Piercing damage","domain":"damage-roll","toggleable":true}
{"key":"RollOption","option":"use-modular-s","label":"Use modular Slashing damage","domain":"damage-roll","toggleable":true}
{"key":"RollOption","option":"use-modular-b","label":"Use modular Bludgeoning damage","domain":"damage-roll","toggleable":true}
```
