### ISSUE TITLE
Side-by-Side is applying to any Animal Companion

### ISSUE THREAD

**Issue by xyzzy42** [foundryvtt/pf2e#5806]
Side by side seems clearly written to only allow flanking "Whenever you and **your** animal companion," are adjacent.  Not another character's animal companion.

~~I also noticed it only works if `game.modules.get("pf2e-animal-companions")?.active`.  Does that need to be a requirement?  Like if you have an AC in the game but don't have the module on, then the AC is still there, but some but not all of their abilities will turn off?  Doesn't make sense to me why someone would want that.~~

**Comment by stwlam** [comment]
This appears to be 2-3 complaints liberally interspliced. Would you mind breaking it out into discrete issues?

**Comment by xyzzy42** [comment]
It's one bug.  And something unimportant and it don't know if it's a bug or not.

Complaint makes me sound like an ass.

**Comment by avagdumortesin** [comment]
There is currently no way to associate a specific AC with a specific PC as the "master". We might be able to change the flanking detection to require both the PC and AC to have the feat or an effect for it, but if there are two PCs with an AC and the feat, we would still encounter this behavior. The only way to fully fix it would be to have ownership of the AC.

**Comment by xyzzy42** [comment]
One could compare the set of players with ownership of the tokens.  Which is of course not always correct.  False positives when multiple players can control the tokens or when a single player has multiple PCs.

The MarkToken RE could be used.  But you'd need to apply an effect "Have Animal Companion" to get the mark and keep that effect on.  Kind of annoying.

A way to allow ownership is better I think.  Also Eidolon could use it too.  There's probably similar issues with that.

**Comment by stwlam** [comment]
This isn't going to be addressable by the system.

**Comment by xyzzy42** [comment]
Create a roll option, `companion-of:uuid` and then it'll be there to check.  A ChoiceSet doesn't (currently) allow drop in of actors, just items.  But a "choose your master" macro that adds the RE to a companion would be trivial.  The roll option also detect companions, instead of the origin uuid, which prevents someone making their own companion from scratch.

And that could go the companion module.  But the flanking check needs to be here.
