### ISSUE TITLE
Feature Request: Add option to apply good/evil damage regardless of alignment

### ISSUE THREAD

**Issue by Maelorn09** [foundryvtt/pf2e#5813]
Please implement the option to deal evil/good and other alignment damages regardless of alignment so that we can support variant rules with ideals/non-alignment from GMG:

**Aligned Damage**
If you’re using the no alignment variant, remove or replace aligned damage (chaotic, evil, good, and lawful damage), which requires significant adjustments for creatures like angels and devils that were built with a weakness to aligned damage. One option is to replace them one-for-one with new damage types like “radiant” and “shadow” that don’t have any moral assumptions. Another option is to simply change the damage type needed for creature weaknesses to some other damage type on a case-by-case basis. A third option is to remove the weaknesses, reduce the monsters’ maximum Hit Points, and call it good. No matter what you do with creatures, you’ll also have to replace abilities like the champion’s that deal aligned damage in a similar way, or remove those abilities.
**If you’re using the moral intentions variant, you can replace chaotic, evil, good, and lawful damage with a single type of damage called aligned damage, which harms those with intentions directly opposed to those held by the character, as determined by you
as GM.**

**Comment by Zullock** [comment]
There is a module that does this: https://foundryvtt.com/packages/pf2e-alignment-damage
