### ISSUE TITLE
Thaumaturge's Esoteric Lore should be related to Charisma

### ISSUE THREAD

**Issue by LiyuNodream** [foundryvtt/pf2e#5815]
Thaumaturge's Esoteric Lore should be related to Charisma instead of Intelligence. Yes, I can add a Ability Modifier each time, but it's too tired! 
We need a way to relate the lore check's default modifier to Charisma.

**Comment by TMunsie** [comment]
This is already automated in the system. Ensure you have the system updated and use "Esoteric Lore" or "Esoteric" or "Lore Esoteric"

![image](https://user-images.githubusercontent.com/25963508/213518172-e3aebdbb-0d18-4b1d-ba75-fce9f0ae4134.png)

![image](https://user-images.githubusercontent.com/25963508/213518269-0ce931b3-fe3c-4d5d-a265-9e2e95fe43a7.png)
