### ISSUE TITLE
Data entry RE improvement: Haughty Obstinacy

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#5823]
Haughty Obstinacy should get a Rule Element added to it, to convert failures to crit fails on Coerce actions.
Use the Self-Loathing feature of the Mitflit as inspiration.

It would also be nice to come up with some predicate for "If you roll a success on a saving throw against a mental effect that attempts to directly control your actions, you critically succeed instead."... but that's not really a specific trait.

**Comment by stwlam** [comment]
This is not currently possible with the RE framework.
