### ISSUE TITLE
Explode action inline formulas lack "area-damage" option 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#5844]
Some Skills like explode in the inventors class do area damage. if that could be labelled and work the same as the splash damage that would be great because then it could interact with the IWR mechanics. 

https://2e.aonprd.com/Actions.aspx?ID=902  

in the system its written as flat damage with nothing for the system to know its splash or area damage. 

![image](https://user-images.githubusercontent.com/62528192/213887899-699fe0cc-f030-487e-92e5-d76dcde819b6.png)

**Comment by pedrogrullada** [comment]
I believe #12751 resolves this.
