### ISSUE TITLE
QOL UX feature: right-click to 'unset' actor sheet fields

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/pf2e#5850]
reporting on a UX painpoint for my players fresh to the system

it would be convenient if a contextMenu() click on an actor sheet's fields that are set by drag-and-drop prompted to remove that field.

Drag and drop setting of class, for example, applies that class but removes the compendium browser button for applying another, so if you accidentally grab the wrong class you cannot remove it, having to open the compendium from another sheet or the compendium menu to resolve this isn't an easy UX to intuit.

An alternative would be to make right-clicks open the compendium for the appropriate section, as an alternative.

**Comment by CarlosFdez** [comment]
At the very least, dragging a new class does remove the previously added class and all class features added by the previous one, so until this exists, people can fix any such errors by dragging the class they actually want onto their sheet.
