### ISSUE TITLE
Gunslinger pistolleros challenge missing res

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#5877]
![image](https://user-images.githubusercontent.com/62528192/214214674-e6246c16-c32e-4910-9e6f-29747f999423.png)

https://2e.aonprd.com/Feats.aspx?ID=3174

the missing res are for the Success 

"Both you and the opponent gain a +2 status bonus to damage rolls with Strikes made against each other. If you're a master in the skill you used for the check, the status bonus to damage rolls increases to +3, and if you're legendary, it increases to +4.
You can have only one challenge in effect at a time; challenging a new opponent ends this effect on any current target. Otherwise, the effect lasts until one of you is defeated, flees, or the encounter ends". 

this effect lasts until someone dies. or goes down for both the pc and the creature affected with this.

**Comment by KSops** [comment]
What REs are you proposing to add? Currently, at best it would be an effect that adds a roll option to toggle this status bonus. I don't think selectively applying it can be automated. Would that be enough to address the issue?

**Comment by ThingsCouldGetDicey** [comment]
> What REs are you proposing to add? Currently, at best it would be an effect that adds a roll option to toggle this status bonus. I don't think selectively applying it can be automated. Would that be enough to address the issue?

if it could be solved where by the toggle the player also takes extra damage then yes thats fine.  but to the amount of their proficiency rank

**Comment by TikaelSol** [comment]
This should be done using a token mark RE.

**Comment by DocSchlock** [comment]
This was resolved in [this commit.](https://github.com/foundryvtt/pf2e/commit/82fcacdc58c840518e3a7d02a2897e011753c6f2)
