### ISSUE TITLE
Feature request: when searching consumables with firearms bring up ammunition.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#5879]
i would like to see it that when you search for consumables and you select the firearm search terms for the ammunition to be easy to find. as this is what happens when you do so.

![image](https://user-images.githubusercontent.com/62528192/214220849-6a753198-bb19-48d3-ab1a-55faaa40d1c5.png)

**Comment by stwlam** [comment]
Those do exactly what they say they do: filter for weapons
