### ISSUE TITLE
Add origin roll options during damage application

### ISSUE THREAD

**Issue by ShadowsGamer** [foundryvtt/pf2e#5895]
This would be usefull for automating conditional resistance bonuses. Example:
<details>
  <summary>Archtype Feat from Abomination Vaults</summary>
 Scholarly Defense 

Your knowledge of strange creatures and their bizarre anatomy allows you to anticipate their physical attacks and reduce the damage you take from them. You gain resistance to physical damage from melee attacks made by aberrations and oozes. This resistance is equal to one-third your level.
</details>

<details>
<summary>Example rule for that feat</summary>
{
  "key": "Resistance",
  "type": "physical",
  "value": "floor(@actor.level/3)",
  "predicate": [
    {
      "or": [
        "origin:trait:ooze",
        "origin:trait:abberation"
      ]
    }
  ]
}
</details>

**Comment by stwlam** [comment]
This works, but the example rule element wouldn't validate and needs to be fixed if not done already.
