### ISSUE TITLE
Class item sheet labels have insufficient room for more-verbose languages

### ISSUE THREAD

**Issue by rectulo** [foundryvtt/pf2e#5896]
Is it possible to improve the left menu to be more easily readable ?

In french
![image](https://user-images.githubusercontent.com/98176148/214567649-64c8e009-5641-4b13-94c3-712dca55a12e.png)

vs. in english
![image](https://user-images.githubusercontent.com/98176148/214568231-464c34a3-b71e-47f4-8196-91b18480c016.png)

**Comment by asuffield** [comment]
Huh, these are all using a fixed width: https://github.com/foundryvtt/pf2e/blob/091141aeb4a297322b14c6977259db143b3b0270/src/styles/item/_index.scss#L396

Well that's not going to work. Currently scratching my head over how to do this without fixed widths.

**Comment by asuffield** [comment]
Okay, the answer is to use css grid for all of these things. I'm going to have to do some css surgery to pull this off, but it looks doable.
