### ISSUE TITLE
Cant edit spell variants text box

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#5901]
when adding spell variants into a spell you can click the edit button here:

![image](https://user-images.githubusercontent.com/62528192/214643925-321931ee-6afb-4755-aee1-451776320432.png)

but when it is open i cannot edit the text inside the spell variant. which is important for editing stuff like different effects and damage types on persistant damage. 

![image](https://user-images.githubusercontent.com/62528192/214644313-95dc97be-1ce5-4aa3-9014-48b3f4d2adf3.png)
 theres no edit button available on spell variants text box.

**Comment by stwlam** [comment]
This is done intentionally
