### ISSUE TITLE
Variant spells are rolled with their parent version's roll options

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/pf2e#5942]
u fix

**Comment by CarlosFdez** [comment]
for the attack roll, the saving throw, or the damage?

**Comment by stwlam** [comment]
ummm, I think it was damage!

**Comment by CarlosFdez** [comment]
Damage seems to be fine. The modifiers are kinda screwing for the dice increasing ones, but the first one is heal vs undead and the second is heal vs living.

![image](https://user-images.githubusercontent.com/1286721/215079804-fa4e14e4-c918-4ca0-9577-2d855c1809a1.png)

I also just tested a spell attack with tkprojectile, set it to slashing, and the damage type says slashing:
![image](https://user-images.githubusercontent.com/1286721/215080106-1ff66f6c-13c9-49e3-bde7-f1c2cb40ac15.png)

**Comment by CarlosFdez** [comment]
Even saving throw is including damaging-effect. I think I might have ended up fixing this one when I fixed ChatMessagePF2e#item not heightening. Let me know if you get to repro it again, and how.
