### ISSUE TITLE
Torch light should be more animated

### ISSUE THREAD

**Issue by LonePaladin** [foundryvtt/pf2e#5945]
I recently discovered the new feature, where if you equip a torch it creates a check-box on the Actions tab titled "Torch is lit". Checking this causes the character's token to emit light -- but despite the rule element having the animation flagged for it, the light coming out doesn't have any animation. And since it's not changing the token settings, I can't override it in the token's normal light settings.

The torch has the following "Token Light" rule element:
```json
{
  "key": "TokenLight",
  "predicate": [
    "lit-torch"
  ],
  "value": {
    "animation": {
      "intensity": 4,
      "speed": 1,
      "type": "torch"
    },
    "bright": 20,
    "color": "#9b7337",
    "dim": 40,
    "shadows": 0.2
  }
}
```
which just eyeballing it *looks* right, but clearly something isn't.

**Comment by stwlam** [comment]
It's animated but a bit too subtle. V10 changed a lot of the visuals of lights and made all our token light REs ugly :\

**Comment by LonePaladin** [comment]
Okay, I did a side-by-side with a torch-produced light and just a default light with the same animation. And, yeah, the new one is ugly -- I preferred the one that... I dunno, wiggled? Heck, most of the light effects are just gone now.

**Comment by LonePaladin** [comment]
Found out part of the problem: my test light didn't have a *color*. That made the animation show up.

But the one attached to the torch doesn't have the central glow.
