### ISSUE TITLE
The disable ABP flag doesn't work on the extra damage dice

### ISSUE THREAD

**Issue by BigHatLogan01** [foundryvtt/pf2e#5968]
It looks like my animal companions are getting the extra weapon dice again but not any other bonus from Automatic Bonus Progression.
I checked and this flag is set but it is ignored for the damage dice it seems.

```
          {
            "key": "ActiveEffectLike",
            "mode": "override",
            "path": "flags.pf2e.disableABP",
            "value": true,
            "priority": 10
          },
```

![image](https://user-images.githubusercontent.com/123773460/215189783-2790f5bf-cf3b-47b0-8148-6882c4eb6df0.png)

![image](https://user-images.githubusercontent.com/123773460/215190407-3ef947e9-7cf1-4e4a-bb0d-46ccb3a8db28.png)

**Comment by stwlam** [comment]
Fixed by #5845
