### ISSUE TITLE
Extra damage from "forceful" is not being applied.  Bug? Feature Request?

### ISSUE THREAD

**Issue by Wizard-Level-1** [foundryvtt/pf2e#5974]
I don't know if this is a bug or a feature that needs to be implemented, but weapons that are forceful do not apply their extra damage on subsequent hits. I imagine it's not as easy to implement as it sounds.  Maybe just having a 2 more damage buttons on the weapon {Damage (2nd attack)] and [Damage (3rd+ attack)] each button being keyed to add the appropriate extra damage as per the number of weapon damage dice.

**Comment by xyzzy42** [comment]
The system doesn't track actions, at all, so there's no way to automate this without action tracking.  You can add some rules to the weapon that give toggles for the extra damage:

```json
{"key":"RollOption","domain":"damage-roll","option":"attack-two","toggleable":true,"label":"2nd Attack with {item|name}"}
{"key":"RollOption","domain":"damage-roll","option":"attack-three","toggleable":true,"label":"3rd+ Attack with {item|name}"}
{"key": "FlatModifier","selector":"damage","value":"@item.system.damage.dice","type":"circumstance","predicate": ["item:trait:forceful","attack-two",{"not":"attack-three"}],"label": "Forceful 2nd"}
{"key": "FlatModifier","selector":"damage","value":"2*@item.system.damage.dice","type":"circumstance","predicate": ["item:trait:forceful","attack-three"],"label":"Forceful 3rd"}
```

**Comment by Wizard-Level-1** [comment]
> The system doesn't track actions, at all, so there's no way to automate this without action tracking. You can add some rules to the weapon that give toggles for the extra damage:
> 
> ```json
> {"key":"RollOption","domain":"damage-roll","option":"attack-two","toggleable":true,"label":"2nd Attack with {item|name}"}
> {"key":"RollOption","domain":"damage-roll","option":"attack-three","toggleable":true,"label":"3rd+ Attack with {item|name}"}
> {"key": "FlatModifier","selector":"damage","value":"@item.system.damage.dice","type":"circumstance","predicate": ["item:trait:forceful","attack-two",{"not":"attack-three"}],"label": "Forceful 2nd"}
> {"key": "FlatModifier","selector":"damage","value":"2*@item.system.damage.dice","type":"circumstance","predicate": ["item:trait:forceful","attack-three"],"label":"Forceful 3rd"}
> ```

Thank you, this is extremely helpful.

**Comment by xdy** [comment]
Note that it should be @weapon.system.damage.dice not @item.system.damage.dice in the above REs.

**Comment by Wizard-Level-1** [comment]
Hm, this script actually doesn't seem to work.   "Syntax error in rule element definition: unexpected non-whitespace character after JSON at position 122"

**Comment by xyzzy42** [comment]
Don't they both work?  I'm sure I tested. Did I forget to check it worked with a Striking rune? My highly subjective opinion is that `item` is better REs still make sense when they can be copied to non-weapon items.

**Comment by xdy** [comment]
Maybe? All I know is that @item didn't work for me, but @weapon did.

**Comment by xdy** [comment]
Weird, didn't work for me until I switched. Some module interaction on my side perhaps? I just retested on my regular game world(latest pf2e, way too many modules) and it still doesn't work for me with @item. Ah well.

**Comment by xdy** [comment]
You're right. I put my REs on a feat rather than the item itself (as the character in question has shifting weapons), which is why @weapon was needed for me rather than @item.
(Posting here in addition to the discord just in case anyone else has done the same.)

**Comment by stwlam** [comment]
Just reminding everyone that this is a venue for system development rather than one for advice and assistance with using rule elements.

**Comment by sambomb** [comment]
@stwlam with the new Damage roll windows Forceful damage can be listed as an option? 
Disabled by default, and with the right option whenever it's possible.
