### ISSUE TITLE
Evocation missing from custom spell traits

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#5994]
![Peek 2023-01-28 14-35](https://user-images.githubusercontent.com/81383360/215292237-67cd2313-c3d8-4046-b682-2b4a5a3978cf.gif)

**Comment by TMunsie** [comment]
Evocation is a school, not a trait.

![image](https://user-images.githubusercontent.com/25963508/215292366-7d96326f-077e-4fa2-94e5-ffcec69a1831.png)

Closing
