### ISSUE TITLE
Issue: Players are able to see Blind Rolls using the "Use as Initiative" button.

### ISSUE THREAD

**Issue by joshua-igor** [foundryvtt/pf2e#6030]
My players are able to see the results of blind rolls by clicking on the "Set as initiative" button. An example is on the screenshot attached; The player rolled a blind check, but by clicking on the button, it set their initiative as that value, making the blind roll useless.
Is there a way to not show this button when a roll is blind? Or maybe show "???" as the initiative value?

Player's view:
![image](https://user-images.githubusercontent.com/19159042/215417717-9c92ec2a-54bb-4f70-a4cb-7757af78e218.png)

GM's view:
![image](https://user-images.githubusercontent.com/19159042/215418158-266c48f4-964f-4848-8b7d-9dcac70eae5f.png)

FoundryVTT v10.291
PF2 v4.6.8

**Comment by KSops** [comment]
I first thought to disable message sending but there's no feedback on whether you hit the button or not.
I tried adding a localization string `"{name}'s Initiative has been set."`
Does this seem reasonable? First message is a normal message and the second is a blind roll.
![Screenshot (375)](https://user-images.githubusercontent.com/13683351/216925042-6c690511-3af3-4237-b449-6295e1ecdc1a.png)

**Comment by KSops** [comment]
One thing I'm not sure about though is that the combat tracker will still show the initiative, even if it's not in chat. Is this change really worth it? Unless you're asking to also hide the initiative value in the combat tracker.

**Comment by joshua-igor** [comment]
I believe the easiest and most effective approach is, when a player rolls a Blind Roll, only show the "Set as Initiative" button to GMs. Since the player is not supposed to know the result, it does not seem reasonable for them to be able to set this unknown number as their initiative.
In a real-life scenario, the GM would roll behind the GM Shield, so the player would never be able to know which number they rolled, making it impossible to write their initiative by themselves.
I believe that Blind Rolls are normally not used as initiative, so revoking the player's ability to set it as their initiative will not affect any games. And for the unusual scenario that a blind roll needs to be set as an initiative, the GM would still be able to do it by clicking on the button.
Hope I was clear for the explanation. Thanks for the fast reply and for giving it a try, Kyle.

**Comment by KSops** [comment]
Not that I GM, but it seems like a convenient time-saver to let the players click the "setInitiative" button while GM is setting up the encounter. But your approach is certainly less involved. Raised PR for the second approach of hiding button from players when blind roll.

**Comment by joshua-igor** [comment]
Thanks for this, Kyle.
I agree that it is really time-saving making the players set their own
initiative. But, for blind rolls, 99% of the time, it will not be for
initiative, so we are risking a player having a misclick, revealing the
blind roll result to them, just to have a time-saver on a very unusual
scenario.
I hope you have a wonderful Monday, Kyle.

**Comment by cepvep** [comment]
Rolling Stealth for initiative is fairly common, so I don't know if I'd call it an "unusual scenario", but I agree the number should be obfuscated in some way.

**Comment by joshua-igor** [comment]
I agree, rolling Stealth for initiative is common, but when rolling it as
an initiative, by default, the player rolls it publicly. So, the cases
where a Blind Roll needs to be set as initiative are rare.
