### ISSUE TITLE
Feature Request: make the default macro created with a toggle drag to include text stating their on off states.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#6059]
this feature request is for when you drag a toggle and it goes onto the macro bar. for it to be standarderised so that when you use the macro the macro is already pre built with the references to the toggle ability and to then spit that into the chat as to the state of it being on or off. so that when a player or gm drags a toggleable ability into a macro the on off state message is built into the macro as standard.

this would be super useful for gms and players and it would indicate to gms when things are active without having to open players character sheets.

it would also need to be able to send this message from the effect tracker on the top right hand corner and have to implement well with metagaming knowledge. i.e if its an npc ability not to reveal when these are happening. this would be for pcs only.

another solution would be to add floating text as to when its activated and used via macro toggle.

many thanks in advance for all the fantastic work you do.

**Comment by stwlam** [comment]
I don't think we're going to start spamming chat with toggle states, but a notification might be possible.

**Comment by ThingsCouldGetDicey** [comment]
yup as i discovered this as a function but for the player there is no way to tell if its on or off maybe if it isnt chat a floating text notification would suffice. and have that as part of the macro generation code.

**Comment by ThingsCouldGetDicey** [comment]
To add to this a notification to gm and player who uses the toggle via a blue ui notification would be the best choice imho.
