### ISSUE TITLE
Party actor/sheet

### ISSUE THREAD

**Issue by apoapostolov** [foundryvtt/pf2e#6124]
Purpose: define a party as a set of player characters and apply effects or manage their inventory and currency in a unified way from a new character sheet. Similar to the implementation of Groups in DND5E 2.1.x.

Functionality
- [ ] Drag and Drop Player Characters to a Party sheet to manage what characters are part of the Party. 
- [ ] Party Token that can be put on wilderness or city maps to move all players together. Shared vision among all included characters in the Party when put on such maps, instead multiple individual character tokens.
- [ ] Shared Effects that apply RE to all members of the party. Like Scout Exploration that gives each member of the party +1 to initiative.
- [ ] Shared Currency that is sum of all the money the party has. Allows the DM to group-give and group-take money, distributed equally between all members (or other methods, if this is further advanced) to no longer struggle with asking players to add money, or to spread expenses for one purchase between multiple players adding overhead discussions to the game.
- [ ] Shared Inventory for quest items, etc. Shared Inventory is in the Party sheet, but also inside every player's sheet as a special container that doesn't count against bulk. This can represent "rule of cool" simplified quest item storage, or party's horse cart they travel with, etc.

**Comment by CarlosFdez** [comment]
This has been a thing we've been talking about internally for a long time (in fact, even before DND5e got it, I can almost assume atro heard us talking about it and liked the idea) but we haven't been able to jump to it because of a myriad of other projects.

**Comment by apoapostolov** [comment]
I am very happy to hear that it is considered. I am definitely aware this is an epic and shouldn't expect it anytime soon. I wanted to just compile all potential uses that are usable for my games.

**Comment by stwlam** [comment]
From #6611:
> If possible, it would be nice to have an option to toggle on for the crafting section of the player sheet for characters using infused reagents where they can dictate temporary items such as alchemical items that are to be sent to either the party sheet or if they have the correct permissions, directly to player sheets. This would make the life of alchemists out there infinitely easier. Just a thought!
