### ISSUE TITLE
Spells that cause multiple types of damage in an AoE are triggering Area Weakness twice.

### ISSUE THREAD

**Issue by sandersontavares** [foundryvtt/pf2e#6177]
As per the title. Tested with Eclipse Burst and Frigid Flurry against a troop that had area weakness. I believe the intended behavior is for area damage to trigger only once.

**Comment by stwlam** [comment]
Working as intended: weaknesses are assessed against each damage instance, and in this case each damage instance is area damage.

**Comment by sandersontavares** [comment]
Sorry for taking long to reply. I see your interpretation as reasonable. I would argue that by the rules on page 453 of the core rulebook, emphasis mine:

> **If you have a weakness to something that doesn't normally deal damage, such as water, you take damage equal to the weakness value when touched or affected by it.** If more than one weakness would apply to the same instance of damage, use only the highest applicable weakness value.

Since area damage is not a *type* of damage, I'd argue the above rules apply and it should trigger the weakness only once per spell in this case. But if you and the other devs disagree, it's completely fine, it's very rare that it comes up and when it does I will just house rule. Great job on implementing IWR!

**Comment by stwlam** [comment]
It doesn't refer to damage types. As in your quote: 

> If you have a weakness to something that doesn't normally deal damage, such as water, you take damage equal to the weakness value when touched or affected by it.

Area damage is certainly something that normally deals damage despite not being a damage type, much like physical, splash, etc. Absent any clarification from Paizo or some previously unconsidered rule buried somewhere, I expect the system will stick to the current implementation.
