### ISSUE TITLE
Massive damage rolls messages no longer wrapping correctly

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#6182]
PF2e v4.7.1
I know this will pretty much have none or barely any priority.
But when I roll a massive critical damage roll I get this:
![image](https://user-images.githubusercontent.com/81383360/216887992-c584ff70-3051-4793-89db-d76f485a3be8.png)

This didn't happen in 4.6.8
This is obviously from a macro... FoB and Double Slice to be precise

**Comment by stwlam** [comment]
The styling for that was last changed on Jan 10. :\

**Comment by Symon-S** [comment]
Might need some Dorako loving?

**Comment by Symon-S** [comment]
Thanks @stwlam
