### ISSUE TITLE
some Feat entries of impossible land

### ISSUE THREAD

**Issue by sakusenerio** [foundryvtt/pf2e#6197]
REVEAL HIDDEN SELF：lack of frequency
TOWERING PRESENCE：lack of frequency
DOMINION AURA；ASURA MAGIC；JALMERI RAKSHASA MAGIC；IDOL THREAT ：not even in the system

**Comment by simonward** [comment]
It looks like Reveal Hidden Self and Towering Presence are correctly set at once per day and once per hour respectively.
