### ISSUE TITLE
Same ID used twice

### ISSUE THREAD

**Issue by rectulo** [foundryvtt/pf2e#6203]
An ID ("_id": "5Rd1LNWiczurzj0C") is used twice for two different abilities :
- the breath weapon for the [air mephit](https://github.com/foundryvtt/pf2e/blob/master/packs/data/pathfinder-bestiary.db/air-mephit.json), ligne 460
- the breath weapon for the [fire mephit](https://github.com/foundryvtt/pf2e/blob/master/packs/data/pathfinder-bestiary.db/fire-mephit.json) ligne 522

We can not translate it... and I don't know to fix this

**Comment by stwlam** [comment]
The same item ID can be used twice on two different actors. Are you not able to target owned items for translation according to UUID?

**Comment by simonward** [comment]
If you need to generate a new id, you can use:
`console.log(`randomID: ${randomID()}`)`

**Comment by rectulo** [comment]
> Are you not able to target owned items for translation according to UUID?

I asked Dwim to explain the whole process better than I am able to do. I'm just a "field coder".
What I understand: the script skips the translation for the same ID when extracting the files to avoid us translating twice that ID used by many monsters. 
Then the script reinjects the ID translated when it is needed for the monsters.
In the example above, the air mephit is having the description field of the fire mephit inside. 
I think it should be easier for us to have each time a new ID.

I will try to replace ID by a new one. I will wait for Dwim's advices to do so and trying to catch other instances if they exist.

If I replace IDs, is there any risk to break something inside your code if something use this ID for a predicate ? Is there a way to avoid it ?

**Comment by Far2Casual** [comment]
> The same item ID can be reused on two different actors. Are you not able to target owned items for translation according to UUID?

Sure, we handle that. But if we use the same ID on two different actors, shouldn't it be for the exact same item ? Here, the Breath Weapon on the Fire and Air mephits have the same ID (5Rd1LNWiczurzj0C), but different descriptions. I believe that is wrong, right ?

**Comment by stwlam** [comment]
It isn't, no. IDs must be 16 alphanumeric characters and unique for each collection. That is the full set of requirements.

**Comment by Far2Casual** [comment]
At this point, Babele only allows us to target either item names or item IDs.

**Comment by rectulo** [comment]
Many Thanks !
