### ISSUE TITLE
[Feature] Allow players to apply spell effects

### ISSUE THREAD

**Issue by manuel-hegner** [foundryvtt/pf2e#6223]
There should be an option to allow players to apply spell effects (via drag and drop) to tokens, even if they are lacking ownership of the characters.

**Comment by TMunsie** [comment]
The option **is** ownership. As a stated system goal, we don't want to be breaking the Foundry permission model. Auras work by using the GM permissions as opposed to the player permissions in a passive sense. What you are asking for is actively to break the permission model, and that is presently outside of the scope of the project design goals.

They question is why should the system implement this, as opposed to a module. And from the system design view this is very much module-space.
