### ISSUE TITLE
Wrap really, really long damage instance formulas 

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#6283]
Way to duplicate by rolling the following:
`/r {((2 * (1d6 + 6 + 3d6[precision]) + 1d10)[piercing] + (2 * (1d6 + 6 + 3d6[precision]) + 1d10)[piercing])[piercing]}`
or
`/r {(((2d6[doubled]) + 2 * 6 + (6d6[doubled])[precision] + 1d10)[piercing] + ((2d6[doubled]) + 2 * 6 + (6d6[doubled])[precision] + 1d10)[piercing])[piercing]}`

This is attempting to duplicate a double critical hit damage roll for a Flurry of Blows while in monastic archer stance.

![image](https://user-images.githubusercontent.com/81383360/218016699-a4d74998-9806-4939-82b2-89faa3e28e55.png)
![image](https://user-images.githubusercontent.com/81383360/218016876-8176d2a4-dbb5-4bb6-ac84-203160247912.png)

**Comment by stwlam** [comment]
Well that's just nutty.

**Comment by Symon-S** [comment]
All these roll 2 damages and add them together are nutty

**Comment by stwlam** [comment]
If you add them that way they are!

**Comment by KSops** [comment]
Looks like a change to `normal` at https://github.com/foundryvtt/pf2e/blob/4.7.4/src/styles/ui/sidebar/chat/_damage.scss#L87 fixes this? but not sure about regression.
