### ISSUE TITLE
"Ongoing Strategy" adds flat weapon damage instead of precision damage

### ISSUE THREAD

**Issue by Crineryr** [foundryvtt/pf2e#6289]
Hi,

As noted in subject, damage is not properly converted to precision damage. I'm adding a list of chat rolls, first 2 are with "Ongoing Strategy +3", last one is with "Devise a Stratagem". 

![image](https://user-images.githubusercontent.com/123328116/218114759-b9ce3902-599c-47b4-927e-4448abdf10cc.png)

Below direct extract from AoN, precision damage should be dealt instead:
![image](https://user-images.githubusercontent.com/123328116/218115117-52fb9521-d5cf-48a1-88eb-9460fd59bd7a.png)

Is it possible to add a fix for it?

Thanks!

**Comment by simonward** [comment]
It works for me. Have you tried replacing the feat with a fresh copy from the compendium?

**Comment by Crineryr** [comment]
Thanks for info, I've done what you suggested and now it works fine. Thanks a lot, I am closing this issue :)
