### ISSUE TITLE
Treat Wounds (PF2e Macros) - expanding the macro

### ISSUE THREAD

**Issue by Crineryr** [foundryvtt/pf2e#6290]
Hey,

There is a very useful macro for Treat Wounds, but I would love to see some features added. Here's a list of what I think would be neat to have on hand:

- Option to select if you are using "Treat Wounds" or "Battle Medicine"
- Adding to the chat draggable effect depending of type of action was selected - either "Effect: Treat Wounds Immunity" or "Effect: Battle Medicine Immunity"
- Battle Medicine action states that target is immune to **your** Battle Medicine, so ideally if an effect's name could be a variable depending on what actor used it. Something like "Effect: Battle Medicine Immunity (_Actor_)"
- Both effects share the same icon, making it hard to distinguish on the get go what effect is on each token. Could one icon be changed?
- Feat-related changes - additional toggles to activate (or auto detect) feats such as "Forensic Medicine Methodology" and "Medic Dedication" would be great

I know it's a lot, but would greatly improve usability of this macro :)

Cheers

**Comment by Symon-S** [comment]
There is a macro in workbench that does most, if not all of these already, although having it done by natively would be nice.

**Comment by sorrythatuserbla** [comment]
@Crineryr 
Yes, can confirm, that all these features are included in the treat wounds-Battle Medicine macro from pf2e workbench. Hopefully it can be at one day reimplemented in core. But for now it is complete afaik.

**Comment by Crineryr** [comment]
Thanks for info, I was not aware that this mod exist. Will definitely give it a go!

After taking a look I can see that it properly calculates Medic Dedication, but not Forensic Medicine. Oh well, still an improvement :)

I will leave this request hanging, maybe one day it will be added to the core. Otherwise, feel free to close it.

**Comment by sorrythatuserbla** [comment]
It has forensic medicine included. 
Please ping @darkim on the discord to share what is it what you are missing.

**Comment by Crineryr** [comment]
You are right, probably I have missed something the first time I checked.

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated issue #15855
