### ISSUE TITLE
Settlement Scholastic Feat

### ISSUE THREAD

**Issue by ESMDEVTS** [foundryvtt/pf2e#6332]
The Settlement Scholastic feat should be an archetype feat but is listed as a skill feat and thus cannot be correctly used.

**Comment by stwlam** [comment]
It is an archetype skill feat.

See https://2e.aonprd.com/Feats.aspx?ID=1881 and https://github.com/foundryvtt/pf2e/wiki/The-CounterFAQ#i-am-using-the-free-archetype-variant-rule-and-am-trying-to-add-the-medic-archetypes-treat-condition-feat-to-an-archetype-feat-slot-why-cant-i-do-this-in-foundry

**Comment by ESMDEVTS** [comment]
Correct, the pulldown in the compendium has it set as a skill feat which is an error.
