### ISSUE TITLE
Fey Influence classified as General Feat

### ISSUE THREAD

**Issue by pinkflumph** [foundryvtt/pf2e#6333]
Fey Influence should be an Ancestry Feat, instead it is classified as General

**Comment by simonward** [comment]
Cannot reproduce.

<img width="238" alt="Screen Shot 2023-02-12 at 10 17 23 PM" src="https://user-images.githubusercontent.com/1904698/218384843-675ee00c-00ee-427e-a758-36b79e06dc55.png">

**Comment by pinkflumph** [comment]
I now see it was fixed in an update, closing the issue
