### ISSUE TITLE
Demoralize: Intimidation Macro could provide a link to an effect: Immunity to Demoralize (similar to Battle medicine immunity)

### ISSUE THREAD

**Issue by sorrythatuserbla** [foundryvtt/pf2e#6383]
Demoralize says: _Regardless of your result, the target is temporarily immune to your attempts to Demoralize it for 10 minutes._
It would be nice to have an effect in the system and a link to that effect in the result of the demoralize roll.

**Comment by DawidIzydor** [comment]
There's a macro doing excactly this in Pf2e Workbench, so maybe import it from there to system?

**Comment by TikaelSol** [comment]
I'm against having blank tracking effects stored in the system, and not a fan of the few that we have for things like immunity. These are the sorts of things that the Extempore Effects module works better for, as storing them in compendiums bloats the system size. I would much prefer a system implementation allowing these kinds of tracking effects with no other automation to be generated similarly to how the module functions.
