### ISSUE TITLE
Magic Fang description missing link to effect

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#6422]
![image](https://user-images.githubusercontent.com/62528192/219676677-e2e26ddb-9c68-459a-aed5-d31039a85719.png)

https://2e.aonprd.com/Spells.aspx?ID=179 

currently theres no effect with duration to drag once this spell has been cast.

**Comment by TMunsie** [comment]
The spell effect is linked to the spell. The user needs to update to the latest version or replace the version of the spell.

On release (4.7.4):
![image](https://user-images.githubusercontent.com/25963508/219708575-98824ca3-94ed-4ed8-adb0-dccd6051d2f2.png)

Closing as erroneous report

**Comment by ThingsCouldGetDicey** [comment]
hi sorry about this report theres an actor in outlaws of alkenstar that has the older version of the spell without the effect.

**Comment by TMunsie** [comment]
> hi sorry about this report theres an actor in outlaws of alkenstar that has the older version of the spell without the effect.

Ok... Care to say which one? Otherwise this is like reporting "Something is broken! You should find it!"

**Comment by ThingsCouldGetDicey** [comment]
> > hi sorry about this report theres an actor in outlaws of alkenstar that has the older version of the spell without the effect.
> 
> Ok... Care to say which one? Otherwise this is like reporting "Something is broken! You should find it!"

dewey darstar book 1 chapter 2 part 3
