### ISSUE TITLE
Avoid Notice system macro is set to Public by default, should be blind GM roll

### ISSUE THREAD

**Issue by weepingminotaur** [foundryvtt/pf2e#6434]
Pretty much what the title says. Stealth rolls should be blind GM rolls, not public rolls.

**Comment by InfamousSky** [comment]
avoid notice does not have the secret trait, that is something for whyzo to fix not the system

**Comment by weepingminotaur** [comment]
OK, but the associated Stealth check would have the Secret trait, right? Anyway, I understand. It's weird that AN doesn't have the secret trait.

**Comment by InfamousSky** [comment]
why would it? Skills do not have any traits by default

**Comment by weepingminotaur** [comment]
Yep. But the very nature of this particular skill (Stealth) would seem to make it secret by default. Really, the AN check should be a specific Stealth skill action, but that's beyond the purview of the Foundry system.
