### ISSUE TITLE
Spell and Ability durations to replace prior applied effects with new duration

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#6498]
So i was having this discussion about rules and wondered how the system handles this rule

Duplicate Effects
When you’re affected by the same thing multiple times, only one instance applies, using the higher level of the effects, or the newer effect if the two are the same level. For example, if you were using mage armor and then cast it again, you’d still benefit from only one casting of that spell. Casting a spell again on the same target might get you a better duration or effect if it were cast at a higher level the second time, but otherwise doing so gives you no advantage.

https://2e.aonprd.com/Rules.aspx?ID=312

Currently when an effect is dragged onto a token more than once it applies the effect twice rather than replacing the cooldown. 

what would be nice is future applications of the effect when dragged on after the first instance just resets the cooldown rather than adds additional effects.

**Comment by stwlam** [comment]
This already effectively happens

**Comment by ThingsCouldGetDicey** [comment]
it doesnt tho.

it just keeps stacking.
![effects3](https://user-images.githubusercontent.com/62528192/220240878-80b1825b-f135-4c90-bf96-b3643ea0c72b.gif)
