### ISSUE TITLE
Allow Abjuration Trait to be Removed from Magic Armor

### ISSUE THREAD

**Issue by avagdumortesin** [foundryvtt/pf2e#6501]
Since the CRB shows Magic Armor as having the Abjuration trait, it is applied whenever a +1 potency rune is added to armor. 

Specific Magic Armors may not have the Abjuration trait, and may have a different school trait added. When creating a Magic Armor item, there should be an option to say this is a Specific Magic Armor, which removes the Abjuration trait.

Alternatively, remove the school trait from the list of traits automatically added to Magic Armor items.

**Comment by TikaelSol** [comment]
Paizo only lists the traits that are specific to that armor, not the ones that come from the runes. If armor runes pass their traits onto the armor itself then the current behavior is correct for the same reason that Paizo doesn't include traits from sub-ordinate actions.

**Comment by stwlam** [comment]
Closing due to staleness and ensuing removal of trait
