### ISSUE TITLE
Opening a token sheet produces a warning if they have an attack without damage

### ISSUE THREAD

**Issue by sorrythatuserbla** [foundryvtt/pf2e#6576]
Double clicking on a token to open it's sheet will produce the below warning
![grafik](https://user-images.githubusercontent.com/78597675/221121256-e4c8f724-4656-45c8-bfcc-8403e05f5d82.png)
This seems to happen for all creatures which have attacks that don't deal damage (like Web attacks)

![grafik](https://user-images.githubusercontent.com/78597675/221121498-f4860acd-04bb-404c-8d41-471e1712842a.png)

**Comment by avagdumortesin** [comment]
Fixed with https://github.com/foundryvtt/pf2e/pull/6557
