### ISSUE TITLE
Auras will affect other tokens even when the creature providing the aura has a toggled visibility state

### ISSUE THREAD

**Issue by sorrythatuserbla** [foundryvtt/pf2e#6577]
![grafik](https://user-images.githubusercontent.com/78597675/221122035-ac08a261-0c34-4de1-a6f9-c43064d17c01.png)

Not sure if this is working as intendet since this behaviour differs strongly from the usall design of these tokens not interacting with the game in any way. Refering lightsources on the token for example.

**Comment by stwlam** [comment]
This is a little tricky since people are currently also using the hidden toggle in lieu of sneaking mechanics.

**Comment by sorrythatuserbla** [comment]
Oh ok, was not aware. I.thought everyone was just using the hidden/unnoticed/etc. conditions.
