### ISSUE TITLE
Homebrew damage in Inline rolls and Rule Elements

### ISSUE THREAD

**Issue by Darkluc9850** [foundryvtt/pf2e#6594]
Being able to apply the homebrew types of damage to Inline rolls and rule elements such as Flat Modifier would be very good, specially with the No Alignment Variant Rule, where if we create a necrotic type of damage, we can do [[/r 1d6[necrotic]]] to auto calculate RWI.

**Comment by stwlam** [comment]
This is already possible. If you're experiencing difficulties with it, feel free to hop on discord and ask questions.

**Comment by Darkluc9850** [comment]
My bad, didn't notice that I needed to put the "hb_" before the damage type.
