### ISSUE TITLE
Auras for Inspire Courage and other Aura effects

### ISSUE THREAD

**Issue by AtelierSnek** [foundryvtt/pf2e#6601]
Currently some Auras have configured Aura Rules, but said Auras do not automatically affect targets, even if there is no save/it only affects allies or willing targets.

Classically, this applies to Inspire Courage (but others too!), which *could* have the following aura rule:
```json
{
  "effects": [
    {
      "affects": "allies",
      "events": [
        "enter"
      ],
      "uuid": "Compendium.pf2e.spell-effects.beReeFroAx24hj83"
    }
  ],
  "key": "Aura",
  "radius": 60,
  "slug": "inspire-courage-aura",
  "traits": [
    "emotion",
    "mental",
    "visual"
  ]
}
```

Is this just not-yet-implemented? If that's the case, we're happy to sit down and power through any friendly/non-save auras that need specifying.

**Comment by simonward** [comment]
It appears this is similar to Bless, where RAW it's not an aura but rather an emanation. That means it doesn't move after it's been cast.

**Comment by AtelierSnek** [comment]
Oh! I've been completing misreading it then. My bad.
