### ISSUE TITLE
Darkvision should be limited to 60 feet

### ISSUE THREAD

**Issue by icopp** [foundryvtt/pf2e#6604]
This a rules gotcha hidden in the [Vision and Light](https://www.aonprd.com/Rules.aspx?Name=Vision%20and%20Light&Category=Exploration) section (rather than the darkvision rules):

> Characters with darkvision (dwarves and half-orcs) can see lit areas normally as well as dark areas within 60 feet. A creature can’t hide within 60 feet of a character with darkvision unless it is invisible or has cover.

To match this, characters would have to be able to see in the current darkvision mode but only to a 60 foot radius, and then normal (darker) vision after that.

**Comment by nikolaj-a** [comment]
That looks like a Pathfinder 1st Edition thing. No such range limitation is present in Pathfinder 2nd Edition.

**Comment by icopp** [comment]
Oh, geez. You're right, sorry, somehow I was on the wrong AoN site.
