### ISSUE TITLE
Party Sheet Suggestion

### ISSUE THREAD

**Issue by disShades** [foundryvtt/pf2e#6611]
If possible, it would be nice to have an option to toggle on for the crafting section of the player sheet for characters using infused reagents where they can dictate temporary items such as alchemical items that are to be sent to either the party sheet or if they have the correct permissions, directly to player sheets. This would make the life of alchemists out there infinitely easier. Just a thought!

**Comment by stwlam** [comment]
Duplicate of #6124, but moved comment over there
