### ISSUE TITLE
Devoted Guardian Feat has the Passive trait despite requiring an action

### ISSUE THREAD

**Issue by MindWeb125** [foundryvtt/pf2e#6618]
AoN lists Devoted Guardian as an action you can take so long as your last action was to raise a shield: https://2e.aonprd.com/Feats.aspx?ID=3623

In the feats list in Foundry it is given the Passive trait and there's no mention of it requiring an action.

![image](https://user-images.githubusercontent.com/105242276/221386843-4fb7b7e3-6fae-4fca-a30b-cc7706d69b56.png)

**Comment by simonward** [comment]
Fixed by https://github.com/foundryvtt/pf2e/pull/6610
