### ISSUE TITLE
Search support for other languages[feature request I think]

### ISSUE THREAD

**Issue by sakusenerio** [foundryvtt/pf2e#6626]
If you search in Compendium browser for something, partial match is usable only if you are using English.
While many languages' compendium localization work active and completed, it will be nice if users can search freely with other languages in compendium browser instead of having to use a search MOD.

**Comment by stwlam** [comment]
Would you mind providing an example language and search terms? The search engine _should_ be language-agnostic.

**Comment by sakusenerio** [comment]
https://github.com/foundryvtt/pf2e/assets/96058441/b55653ce-89da-4dca-a571-2b5af6f59081

I made a video to show it better.
When I search for 'potion' in compendium browser, all items with 'potion' in its name will pop up;
However when I search for '药水' - which is the translation of 'potion' - nothing shows up. 
But, if I search for '壁虎药水' (the complete translation of 'Gecko potion'), browser can get me gecko potion as normal.

Complete match is supported for all localization, while partial match is not. Not sure if it have anything to do with Babele.
I use only localization mod and Babele in this video.

**Comment by stwlam** [comment]
Thanks. There may be an issue with the search engine knowing how to split those. I'll do some research and see if we can find a solution.

**Comment by stwlam** [comment]
Which translation module(s) are you using? I see there are multiple for Simple Chinese.
