### ISSUE TITLE
Resistance to all damage dice in single attack not being applied properly, results in too much damage

### ISSUE THREAD

**Issue by sesopenko** [foundryvtt/pf2e#6629]
When attacking with two damage types, ie: 1d6 pierce + 1d4 fire, if one damage die bypasses damage resistance the other damage die from the same attack will incorrectly bypass damage resistance too, causing too much damage on the target.

See rules explanation [here, under Resistance](https://2e.aonprd.com/Rules.aspx?ID=342)

The text below is in the link above and also Core Rulebook 4th Printing page 453 (lower left corner of page)

> It’s possible to have resistance to all damage. When an
effect deals damage of multiple types and you have resistance
to all damage, apply the resistance to each type of damage
separately. If an attack would deal 7 slashing damage and
4 fire damage, resistance 5 to all damage would reduce the
slashing damage to 2 and negate the fire damage entirely.

**Steps to reproduce with an example combat scenario:**

1. Add a Fire Mephit to the play area
2. Add a Vampiric Mist to the play area
3. Start combat and roll initiative
4. roll an attack for the Fire Mephit until it strikes
5. Target the Vampiric Mist and click the Damage button for the attack in the Chat log

**Expected Result:**

The 1d6 pierce should have the physical 5 damage resistance applied to it and the 1d4 fire should bypass the physical 5 damage resistance.

**Actual result:**

Both the piercing and fire damage bypass the physical 5 damage resistance, resulting in damage rolls up to 10 damage being fully applied to the target.  Too much damage occurs for the target.

You can see the log in the screenshot attached here, where too much damage was applied because the pierce damage bypassed the physical damage.  It should have only received 3 damage, because the 5 pierce wasn't enough to bypass the DR 5 physical.

![damage resistance bug](https://user-images.githubusercontent.com/673974/221432170-0592951d-165e-4e1c-b8ed-a7d37dc25907.png)

**Comment by simonward** [comment]
If you hover over the (i) symbol, what do you see?
My expectation is that it took -5 physical, +5 fire.
(5-5 piercing)+(3+5 fire) = 8

**Comment by sesopenko** [comment]
Oh my, I just realized that the vampiric mist has 5 fire weakness, which means it takes 5 bonus points of fire damage whenever it takes fire.  Things are working as expected, sorry for the trouble!
