### ISSUE TITLE
Rime Crystal Spellheart missing effect

### ISSUE THREAD

**Issue by Kyajin0** [foundryvtt/pf2e#6637]
The Rime Crystal Spellheart item from Treasure vault is missing the Armor and Weapon Spell Effects to drag/drop onto characters. From Treasure vault, Jolt Coil works similarly and has the spell effects, so seems like it is missing by error from rime crystal. Thank you!

**Comment by simonward** [comment]
Will be fixed by https://github.com/foundryvtt/pf2e/pull/6635
