### ISSUE TITLE
Imprecise scent - should it be an option somewhere?

### ISSUE THREAD

**Issue by kcits** [foundryvtt/pf2e#6646]
Rule book doesn't have it as a listed "feat" pre se, but it is has it in several descriptions.  Example: 
Hunting Catfolk
You come from a long line of skilled hunters and trackers and have a particularly keen sense of smell. You gain imprecise scent with a range of 30 feet.

Pathbuilder puts it under Special Feature Level, and when doing an import from Pathbuilder to Foundry there is not an Imprecise scent option.

Should there be one?

**Comment by avagdumortesin** [comment]
When you select the Hunting Catfolk heritage, the Scent ability is added. If it's not being added to the import from Pathbuilder, reach out to the dev of the importer for assistance. Beyond that, adding the Heritage from the compendium should add it to the senses.
<img width="751" alt="Screenshot 2023-02-26 at 11 46 00 PM" src="https://user-images.githubusercontent.com/55938242/221504364-833e5f06-59f2-4464-ad79-e2ffd59f7fe0.png">
