### ISSUE TITLE
Resonating Fork (Major)

### ISSUE THREAD

**Issue by sakusenerio** [foundryvtt/pf2e#6654]
This one is a little tricky,

In FVTT data description it says:
> The spell attack roll of any spell cast by activating this item is +13, and the spell DC is 29.

……well, TV didn't specify what shoud spell attack roll of major version be, while considering spell attack roll equals spell DC-10, it's only fair major version having an attack roll of +19 intead of a +13 which is the exact AB from greater version.

**Comment by TikaelSol** [comment]
Ultimately this is a Paizo error, and best reported on their forums.  We'll fix it in the system but PFS players wouldn't be able to use it (not that PFS players would likely have a major version anyways)
