### ISSUE TITLE
Bug: Aura fill color property doesn't work at all

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#6655]
Root cause is this line of code:

https://github.com/foundryvtt/pf2e/blob/033a769e725679926d2667adf98cc333cbd96d28/src/module/canvas/token/aura/renderer.ts#L84

the second parameter passed to `beginFill` is the [alpha override](https://pixijs.download/dev/docs/PIXI.Graphics.html#beginFill);  if it is 0, the fill will never be shown (because it will be fully transparent).

I tested locally, and removing that `, 0` solved the bug.

**Comment by shemetz** [comment]
If you fix this bug, you may also need to fix some people's Aura REs which include a fill property which was doing nothing until now.

**Comment by stwlam** [comment]
It is intended for the fill color to be a highlight fill color.
