### ISSUE TITLE
Vivacious Conduit not applying the heal when using the Take a Breather macro

### ISSUE THREAD

**Issue by RonJomero** [foundryvtt/pf2e#6665]
I have a party that uses the Stamina variant rule.  And one member has the Vivacious Conduit feat, but when using the Take a Breather macro it isn't applying the healing (to hit points, wouldn't expect it to apply to stamina).

**Comment by TikaelSol** [comment]
We don't handle any of these 10 minute rest activities in the system, similarly we don't advance the clock by 10 minutes when using treat wounds or the like.
