### ISSUE TITLE
Changing a token's represented synthetic actor freezes Foundry

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/pf2e#6679]
- Import 2 actors, i belive they can be any but let's use the imported Adept and Animated Broom for this
- Place Adept in new scene
- Open token config
- Change "Assigned Actor" to Animated Broom
- Click Update Token
- Foundry will freeze for multiple minutes (the freeze will vary from seconds to minutes)

Call stack exceded error 
![image](https://user-images.githubusercontent.com/1346839/221881318-28baad94-33a7-4e68-8023-147a7d42ad48.png)

**Comment by stwlam** [comment]
Nothing. Any omitted steps? Modules in play?

**Comment by theripper93** [comment]
odd, no modules, steps are quite straightforward - and i'm pretty sure all my pf2 settings are at default

**Comment by stwlam** [comment]
OK, I'll ask around to see if anyone else can reproduce.

**Comment by esheyw** [comment]
I just tried this on a completely fresh world, world hung for only ~3s, got two errors: ![](https://i.imgur.com/2USZlW0.png)
