### ISSUE TITLE
Barricade Buster has a wrong Volley trait value

### ISSUE THREAD

**Issue by 4lias-PF2** [foundryvtt/pf2e#6702]
Volley should be 30 ft. not 20 ft. for the new Barricade Buster of Treasure Vault

**Comment by simonward** [comment]
My PDF shows volley 20 ft. as correct.
<img width="177" alt="Screen Shot 2023-03-01 at 11 02 13 AM" src="https://user-images.githubusercontent.com/1904698/222238999-69cb00e1-642b-4995-b877-564badbc9fe5.png">
