### ISSUE TITLE
Unlocalized skill checks

### ISSUE THREAD

**Issue by MSAbaddon** [foundryvtt/pf2e#6718]
Looks like there are still a few skill checks that don't get localized properly:

![image](https://user-images.githubusercontent.com/66370966/222532226-1642a03e-ef03-4b46-8472-ce36e958f420.png)
First one is a skill check rolled directly from an NPC sheet, the second one is rolled from a PC sheet.

Also, for @Check rolls with a set DC, the skill name in the DC line is not localized:
![image](https://user-images.githubusercontent.com/66370966/222532504-a7732881-fe9a-4e83-b8cc-47eb70333f71.png)

**Comment by simonward** [comment]
Same issue as [2253](https://github.com/foundryvtt/pf2e/issues/2253)?

**Comment by MSAbaddon** [comment]
The other issue is related to skill variants. This issue is about actual skills

**Comment by simonward** [comment]
Inline skill checks should be fixed by: https://github.com/foundryvtt/pf2e/pull/6727

**Comment by dellatorreadrian** [comment]
Should this be closed?

**Comment by MSAbaddon** [comment]
Not quite. While the first issue is solved an @Check command e.g. added to the chat still has the label unlocalized
![image](https://github.com/foundryvtt/pf2e/assets/66370966/c991a93d-fa24-4ce2-9223-96a594199a75)
![image](https://github.com/foundryvtt/pf2e/assets/66370966/03b09fdb-4d4e-458e-ba0e-e23c1d7a60f2)

I think this isn't actually a localization issue though - as far as I understand it the plain check type is used for the label instead of using the skill name - otherwise it would be Thievery in English I guess?
