### ISSUE TITLE
Update machine broke

### ISSUE THREAD

**Issue by AbnormalFricker** [foundryvtt/pf2e#6752]
I was updating from version 4.6.8 to 4.7.2, but in accident turned off my laptop while it was trying to updage character sheets, and now, all of sheets will look broken, unusable, and I can't play with my friend anymore on anything later than 4.6.8. Every new update will just try to "fix" broken sheets for infinite amount of time, and do absolutely nothing. And another problem is that after you update to something later, it will try to "update" everything only once, even if you update your game again from 4.6.8, so nothing will ever gonna get fixed. I cannot update pathfinder 2e anymore, and thats breaks some of my modules even. Please, help me.

**Comment by TikaelSol** [comment]
Come by our discord (https://discord.gg/pf2e) and we can try to help you get your world sorted, it's likely an actor was damage by the migration being stopped part way through.
