### ISSUE TITLE
PF2 Range Hunters Edge: Precision not being applied

### ISSUE THREAD

**Issue by Nyarlathotep3001** [foundryvtt/pf2e#6754]
Ranged attack does not apply  additional 1d8 precision damage for L4 ranger with "Precision" Hunter's Edge.

Character shhet has the check boxes for "Target is your hunted prey" and  "First attack on hunted prey this round".

Tested 
- selecting target before checking both boxes
- selecting taget after checking both boxes
- selecting target before checking "First attack on hunted prey this round" only
- only checking "First attack on hunted prey this round" selecting target after.
- selecting target without checking either button

FOUNDRY VTT Version    10 - Build 291
PF2 System                       4.8.3

**Comment by TikaelSol** [comment]
![image](https://user-images.githubusercontent.com/80183198/222968744-253f9b7f-0652-4160-9e3c-ddf647953d50.png)

Works for me, you may want to set the PC to level 0 then back up to reset their class features.

**Comment by Nyarlathotep3001** [comment]
Resetting the level to zero and back does fix this issue.  

Is there way to tell that this action is required after a new version is relaeased?

**Comment by TikaelSol** [comment]
It shouldn't be required normally. If the actor was imported from somewhere like Pathmuncher it's possible it didn't import properly.
