### ISSUE TITLE
Params injection into statistics broken

### ISSUE THREAD

**Issue by Symon-S** [foundryvtt/pf2e#6783]
This can easily be replicated by trying to inject params into a brand new actor.
Say for a fighter with double slice and trying to inject on the first "weapon" action non-agile weapon.
`await token.actor.system.actions[0].attack({options: ["double-slice-second"]});`

See https://discord.com/channels/880968862240239708/880969304365994034/1082500271793508373

Also `skipDialog: true` doesn't work either.

**Comment by xyzzy42** [comment]
The root case is that roll options injected in the `attack()` or `roll()` call will get deleted if a RollOption RE exists for the same option and its value is false.

RollOption REs have a `beforeRoll` method, which adds the option to the set if the RE is true and *deletes it if it's false.*

Maybe this should be changed to just add the option on true and do nothing on false?  I.e., let injected options override the toggles.

**Comment by stwlam** [comment]
This isn't a `Statistic`, and the method you're using doesn't accept that parameter. Feel free to make separate feature requests for each item mentioned.
