### ISSUE TITLE
Mystify Not Hiding Item Value and Traits

### ISSUE THREAD

**Issue by AquaDraco** [foundryvtt/pf2e#6785]
For players, mystified items show the gold value and traits (and columns become misaligned):
![image](https://user-images.githubusercontent.com/5697845/223325280-001e8c41-cc07-4e15-858a-ec85961abe73.png)

Going off of resolved bug #1836, this appears to be a bug.

After investigating the code file [item-summary.hbs](https://github.com/foundryvtt/pf2e/blob/master/static/templates/actors/partials/item-summary.hbs) associated with the bug, the traits seem to be appearing incorrectly due to "or" being used instead of an "and" in line 1.
![image](https://user-images.githubusercontent.com/5697845/223327934-c70db27a-c52b-4221-9c22-07365a2343d4.png)

In addition, the "item.isIdentified" should be replaced with "identified" (also in line 1), so that the summary is only hidden for the player and not the GM (as defined in [item-summary-renderer.ts](https://github.com/foundryvtt/pf2e/blob/89a2f431655f44a8592afbaa49f7f32acd4fbfae/src/module/actor/sheet/item-summary-renderer.ts)).

On line 15, there seems to need an "identified" check so that the player doesn't see the gold value.
![image](https://user-images.githubusercontent.com/5697845/223325858-52d54249-c663-406a-8fc0-2148de7a414e.png)

I made my changes in my local system just to test it out:
```
{{#if (and item.system.traits identified)}}
    <div class="tags item-properties">
        {{#if rarityLabel}}
            <span class="tag {{item.system.traits.rarity}}">{{localize rarityLabel}}</span>
        {{/if}}
        {{#each chatData.traits as |trait|}}
            <span class="tag" data-tooltip="{{trait.description}}">{{localize trait.label}}</span>
        {{/each}}
        {{#each chatData.properties as |property|}}
            <span class="tag tag_secondary">{{localize property}}</span>
        {{/each}}
    </div>
{{/if}}

{{#if (and item.price identified)}}
<section>
    <div>{{localize "PF2E.LevelN" level=item.level}}</div>
    <div>{{localize "PF2E.Item.Physical.PriceLabel" price=item.price.value}}</div>
</section>
{{/if}}
```

Issue appears to be resolved (GM view on left, player view on right):
![image](https://user-images.githubusercontent.com/5697845/223327522-5909d46e-3f2c-4b25-9795-602199770cd4.png)

I've only played one session of Pathfinder and I've never seen this language or file extension in my life, so I might not know what I'm talking about.

**Comment by CarlosFdez** [comment]
You're correct, that's my bad. More specifically, it needs to use @root.identified instead of item.isIdentified in order to handle cases where its not a physical item.
