### ISSUE TITLE
Item Mystification revealing item traits, item level, and price

### ISSUE THREAD

**Issue by Pyroman2xxx** [foundryvtt/pf2e#6790]
Version: Pathfinder version 4.8.3
Recreate: Create new world, add PC actor, give a magic item, mystify it, view it in a logged-in PC inventory tab.

There are traits that, when moused-over in GM's view, state that they are hidden from players but are clearly visible in the players inventory. I believe that Item level and price should also be hidden since they reveal quite a bit of information but I am not sure if that was intended.

**Comment by AquaDraco** [comment]
This should be fixed in #6787

**Comment by stwlam** [comment]
Duplicate of #6785
