### ISSUE TITLE
Feature Request: Add a RollOption toggle for Inventor's Unstable Actions

### ISSUE THREAD

**Issue by blackquaza** [foundryvtt/pf2e#6808]
Inventors get a variety of Unstable actions, which require a flat check to use them again (or a 10-minute break to reset). We should add a toggleable RollOption to the Inventor class (and dedication) tracking whether the unstable action has been used. Bonus points if Unstable actions check this value and change it when rolling the flat check.

**Comment by TikaelSol** [comment]
Closing as a duplicate of #9637
