### ISSUE TITLE
Feature Request: Add to npc actor sheet Attitude tracking

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#6809]
i think it would be really nice if there was a section somewhere in the notes on npc sheets that there was the attitude gradient from hostile to friendly that the gm could click to track at bare minimum but later have make an impression actually track with it as an automation if possible.  i.e rolling a make an impression check improves the state that the gm set it to prior to them rolling. 

it would be nice if it was in the private notes area with boxes indicating colour of their friendly state from red (hostile) to green (friendly)

**Comment by stwlam** [comment]
No plans for this, sorry
