### ISSUE TITLE
Applying rune to a weapon while dual wielding causes incorrect damage rolls

### ISSUE THREAD

**Issue by Time-Vault** [foundryvtt/pf2e#6846]
Specifically, I applied the shocking rune to a dueling pistol while also wielding the erraticannon. Now when rolling damage for one of the weapons when clicking the button in the chat it rolls the damage for the other weapon.

- This also occurs when testing with a second dueling pistol.
- Damage is rolled correctly when not dual wielding.
- Damage is also rolled correctly when duel wielding two guns that are not the weapon with the rune.

**Comment by Time-Vault** [comment]
A bit more testing: damage is rolled correctly when done through the character sheet

**Comment by TikaelSol** [comment]
Unable to reproduce this issue. Try with no modules enabled.
