### ISSUE TITLE
Overriding a Deadly weapon's damage type does not update the additional critical damage

### ISSUE THREAD

**Issue by cuyima** [foundryvtt/pf2e#6858]
Foundry Version: 10.291
PF2E Version: 4.8.3

When creating a rule to override a weapon's damage type, the additional critical damage by the Deadly trait is not updated to match the  base damage.
![image](https://user-images.githubusercontent.com/52758909/224427022-b69e64ae-2015-4e2e-b57f-2a50cab457d4.png)

I tried the following rules and neither affected the Deadly damage:
```json
{
  "definition": [
    "item:slug:soulforged-partizan"
  ],
  "key": "DamageDice",
  "selector": "strike-damage",
  "override": {
    "damageType": "{item|flags.pf2e.rulesSelections.planarPainDamage}"
  }
}
{
  "definition": [
    "item:slug:soulforged-partizan"
  ],
  "key": "DamageDice",
  "selector": "damage",
  "override": {
    "damageType": "{item|flags.pf2e.rulesSelections.planarPainDamage}"
  }
}
```

**Comment by stwlam** [comment]
Deadly dice don't necessarily increase with increasing weapon die size: that must be done separately

**Comment by cuyima** [comment]
I am not trying to increase the damage dice i am trying to make them match the overridden damage type of the weapon.

**Comment by stwlam** [comment]
Sorry, I completely misread this!
