### ISSUE TITLE
Unable to drag & drop toggle-options on character sheets into the hotbar

### ISSUE THREAD

**Issue by liquidsonic** [foundryvtt/pf2e#6922]
Not sure whats changed, when I attempted to drag the toggable options on a character sheet to the hotbar, nothing happened and there was no options to do it. Tried a few, not just confident finisher and it still didn't work :(

https://user-images.githubusercontent.com/18706361/224803317-24c2cd95-13f5-49a0-971a-c077dca44ed9.mp4

**Comment by stwlam** [comment]
Fixed by #6928
