### ISSUE TITLE
Crafting Basic Ammunition does not Create Stacks of 10 with Munitions Crafter

### ISSUE THREAD

**Issue by avagdumortesin** [foundryvtt/pf2e#6945]
The Munitions Crafter feat reads:
> If you use a batch of infused reagents to create basic level-0 ammunition such as black powder cartridges or black powder doses, you produce 10 rounds of ammunition.

When adding Black Powder (Dose or Round) or Rounds (Arquebus) (both of these I added for testing) to the Munitions Crafter section of the Crafting tab, changing the quantity to 10 requires 5 reagents. The system seems to be following the standard 1 reagent/2 items from Alchemical Crafting/Infused Reagents limits for these.

**Comment by stwlam** [comment]
Duplicate of #1903
