### ISSUE TITLE
Treasure Vault runes not listed in weapon and armor rune selection dropdowns

### ISSUE THREAD

**Issue by AFigureOfBlue** [foundryvtt/pf2e#6962]
When applying runes to a weapon or armor, at least some (possibly all?) of the new runes from _Treasure Vault_ seem to be missing. The "merciful" and "authorized" weapon runes and the "portable" armor rune are ones that my players have encountered this with so far, and all the other ones I've spot-checked have been similarly missing from the dropdowns.

**Comment by stwlam** [comment]
The entire runes framework is undergoing a refactor, but newer ones will make it in soon.

**Comment by gourinator** [comment]
Can we get an ETA for the undergoing? And a workaround?

**Comment by TMunsie** [comment]
ETA: when someone volunteers to do the work. The system is updated and improved by volunteer contribution.

Workaround: Since most runes are labels just change the label. If it does something specific add an item-specific rule element that does that thing or posts a note about it.
