### ISSUE TITLE
Container Content Limit

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#698]
In GitLab by @TMun on Aug 14, 2020, 13:44

Some containers (Bandoliers, gloves of storing) have restrictions on the number of storable items as well as bulk. There is presently no way to enforce this.

**Comment by TikaelSol** [comment]
Close as won't fix? Not sure we want to chase down implementations for one off items.

**Comment by TikaelSol** [comment]
We'll reevaluate if more items of that sort get added.
