### ISSUE TITLE
Bug: Effects are missing a flag and can't be removed from actors

### ISSUE THREAD

**Issue by sorrythatuserbla** [foundryvtt/pf2e#6990]
No modules - empty world 
Foundry Version 10 Build 291
Pf2e 4.9.2

How to reproduce:

1. Give an actor a random effect which has a duration. (I tested with shield spell, and raise shield and some others.)
2. Advance game time until effect would be expired. (2 rounds eg.)
3. Try to remove the effect -> Impossible until you reload the application (Edit: Or reapply the same effect again and remove both)

![image](https://user-images.githubusercontent.com/78597675/225460468-e79acd4c-136d-4941-bee5-3a36b7f38438.png)

https://user-images.githubusercontent.com/78597675/225460488-dfa5e3f2-c93b-4074-91e6-c5fb81b6c56b.mp4

**Comment by stwlam** [comment]
What are the effect expiration settings in this world?
