### ISSUE TITLE
Risky Surgery RE needs to account for crafting for chirrurgeon alchemist

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#7029]
![image](https://user-images.githubusercontent.com/62528192/226121763-aaf52e32-f328-48a3-b295-89251a0c0579.png)

needs to add selector crafting. or nature for natural medicine.

**Comment by stwlam** [comment]
This is too mired in unclear writing to address.

**Comment by ThingsCouldGetDicey** [comment]
how could i be more specific?
