### ISSUE TITLE
Feature Request: Ability to mark treasure that shouldn't be auto-sold

### ISSUE THREAD

**Issue by GeneralDisorder** [foundryvtt/pf2e#7054]
Hi,

I recently started running the Abomination Vaults module for my party, and in the official foundry modules all the keys are handed out as Treasure-type objects.
This is reasonable in some cases, since some of the keys are actually worth money if sold, but in most cases you might want to hang onto keys or similar objects because they can be useful.
However, there is that nice button for automatically converting all treasure to coin. If one of my players converts their treasure to coin by mistake, they might sell both 0gp and 10gp keys by accident before they've had a chance to use them.

Of course there is one solution that is creating the key as "Equipment" or so to avoid this issue, but in some cases it would be useful if you could tag certain pieces of treasure as "Important", or "Quest Item", or "Not for Sale", and that these items would not automatically be sold by the Sell all treasure button. I think it might also be reasonable that this tag is enabled by default for Treasure items that have 0 value.

**Comment by stwlam** [comment]
Those keys should be equipment items if they're not intended to be treasure
