### ISSUE TITLE
Missing file for sending deity items to chat

### ISSUE THREAD

**Issue by ethasis** [foundryvtt/pf2e#7056]
![image](https://user-images.githubusercontent.com/96197228/226437342-1a54063c-a296-42da-aa44-038a9fa697b9.png)

This message appears in the console when attempting to 'send' a deity entry into chat. The noted file seems to be missing from the pf2e repository, not to mention my installation.

**Comment by stwlam** [comment]
I don't believe there's a way to send it to chat.

**Comment by ethasis** [comment]
Ah, you're correct! It's not a pf2e system feature. Apologies.
