### ISSUE TITLE
The minimum of 1 damage loses its type

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#7087]
<img width="293" alt="Screen Shot 2023-03-22 at 10 17 11 PM" src="https://user-images.githubusercontent.com/1904698/227122149-564221ef-ea5b-43c2-bb10-fb17c35d280f.png">

I used: `[[/r 0[fire]]]`

**Comment by Rapida11428** [comment]
I wrote up: https://github.com/foundryvtt/pf2e/pull/7091 - it handles this case, but I noticed a command of [[/r 0[fire]+0[cold]]] loses its typing for the roll, so still applies 1 damage despite immunity/resist.
