### ISSUE TITLE
Barbarian Animal Instinct attacks mislabeled

### ISSUE THREAD

**Issue by circaskater411vm** [foundryvtt/pf2e#7148]
The Animal Instinct Wolf and Frog are mislabeled. When you pick Wolf it shows the tongue action and the frog only has Jaws.

Edit: The damage types are mislabeled as well. It shows piercing instead of bludgeoning for the jaws.

**Comment by avagdumortesin** [comment]
Duplicate https://github.com/foundryvtt/pf2e/issues/7100

**Comment by circaskater411vm** [comment]
That's weird. I searched but didn't find this. Thank you for responding.
