### ISSUE TITLE
Respect phtosensitivity mode for RBV effects

### ISSUE THREAD

**Issue by Drental** [foundryvtt/pf2e#7152]
The Photosensitivity Mode is a foundryvtt core feature
![image](https://user-images.githubusercontent.com/74384067/227805889-eb0b4bcc-8b66-4ca3-b544-b24249763ca9.png)

> Anyone know a way I can remove this effect without applying deafened? One of my players has a photosensitivity disability and this effect can trigger actual blindness for them. The deafness condition gets rid of it but also has other negative effects for that player character so we dont want to do that in game. If there's a way I can swap this effect out or create a custom condition it would be amazing 

![image](https://user-images.githubusercontent.com/74384067/227805832-8e60b0e0-14dc-4bb9-babd-d919f115cfca.png)
There is currently no good workaround for this when unconscious

**Comment by stwlam** [comment]
The Photosensitivity Mode is a foundryvtt core feature
