### ISSUE TITLE
Missing Domain: Introspection

### ISSUE THREAD

**Issue by keyneston** [foundryvtt/pf2e#7188]
The domain `Introspection` does not appear when adding domains to a deity. The spells for it such as `guided introspection` do appear to exist.

<img width="510" alt="CleanShot 2023-03-29 at 12 19 35@2x" src="https://user-images.githubusercontent.com/39023/228504154-ba693d31-09af-4e2d-bf94-3bf90aefb460.png">

[AoN Link](https://2e.aonprd.com/Domains.aspx?ID=60)

**Comment by simonward** [comment]
Consider adding this to Narakaas as an alternate.
