### ISSUE TITLE
Mauler does not increase two-handed weapon proficiency

### ISSUE THREAD

**Issue by MarkPearce** [foundryvtt/pf2e#7195]
The mauler dedication does not scale proficiency with simple and martial two-handed weapons, or weapons with the two handed trait to match the characters highest weapon proficiency.

for example a 7th level fighter:
![image](https://user-images.githubusercontent.com/6976378/228692355-66b4020d-5d6a-44b7-b0d5-3920336ac330.png)

![image](https://user-images.githubusercontent.com/6976378/228692406-373f044c-63c9-468b-99b9-d35168181620.png)
(character in this example has Dwarven Weapon familiarity, so the advanced weapons should be treated as martial)

**Comment by stwlam** [comment]
Remaster fixed this.
