### ISSUE TITLE
Feats not populating in compendium browser

### ISSUE THREAD

**Issue by jrellistone** [foundryvtt/pf2e#7205]
Just updated to 4.10.0 and noticed that nothing is populating in the feats/feature section of the compendium browser and it doesn't seem to populate any sources in the dropdown. 
![image](https://user-images.githubusercontent.com/129385821/228810383-faa22bce-18d6-4d49-ae8e-1d035f80f892.png)

**Comment by stwlam** [comment]
Check the compendiums themselves: this is almost always a sign of a failed system install (particular on Windows if the system was initially installed with administrator privileges and then updated without). Uninstall the system, make sure Data/systems/pf2e is really gone, and then reinstall.
