### ISSUE TITLE
Broken pj sheet

### ISSUE THREAD

**Issue by allnnde** [foundryvtt/pf2e#7206]
with version 4.10 we noticed that the character sheet is not working, also there are many errors in the console.

![image](https://user-images.githubusercontent.com/8978118/228837062-cafcbc49-5171-4ae7-b803-43ff81f99dc6.png)

**Comment by TMunsie** [comment]
Cannot replicate on core system. Can you confirm this is a problem with zero modules active.

**Comment by TikaelSol** [comment]
Try with no modules, also try uninstalling and reinstalling the PF2e system, making sure that the `data/systems/pf2e` folder is gone after the uninstall.

Closing as this is not a system issue, it's something local to your machine.
