### ISSUE TITLE
FR: Automate Psychics Core Ability : Unleash Psyche stupify application

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#7208]
https://2e.aonprd.com/Actions.aspx?ID=1222

raw if someone unleashes unleash psyche it automatically adds stupified 1 for two rounds after the two rounds of being used. 

what i would like to see is the automation of the stupify effect with the correct expiration after its applied.

**Comment by TikaelSol** [comment]
Closing in favor of #15864
