### ISSUE TITLE
Automaton feat "Reinforced Chassis" creates item with wrong armor type

### ISSUE THREAD

**Issue by farabor** [foundryvtt/pf2e#7216]
The armor from the feat is supposed to be medium armor,  but the armor created is tagged as light.  Minor issue that doesn't impact me, but would be nice for a future update to fix.
![image](https://user-images.githubusercontent.com/129508855/229102843-ae0dd6a8-5190-4777-a6b4-f705553d2e1b.png)

**Comment by simonward** [comment]
This should already be fixed in latest release.
Commit 58afd88add5
