### ISSUE TITLE
Feature Request: When a creature has an innate status effect hide from pcs but show gm.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#7228]
A common issue is that when gms have a creature that has slowed 1 because of undead or some innate status effect the pcs see the status effect before they have even interacted with it which breaks the game immersion for finding out if a creature has slowed or has other things going on. what i would like to see as a fix to this is to have any creature that has an innate conditional status trait to be hidden from pcs but still show for gms. that way pcs can still see when they effect a creature with other debuffs but cant see the innate debuff or buff.

**Comment by stwlam** [comment]
It is immediately obvious when creatures are visibly slow.
