### ISSUE TITLE
Dread Marshal Stance damage bonus should apply to all damage

### ISSUE THREAD

**Issue by websterguy** [foundryvtt/pf2e#7246]
Currently the flat modifier on Effect: Dread Maarshal Stance has the selector `strike-damage`, but it should be `damage`.

The text reads "[...] it grants you and allies a status bonus to damage rolls equal to the number of weapon damage dice of the unarmed attack or weapon you are wielding [...]". It later has a clause about applying frightened only to strikes, but the damage bonus does not specify strikes only.

**Comment by ZephyrS8** [comment]
I am interested in what sort of processes are followed that let this change go into a public release.

**Comment by TMunsie** [comment]
> I am interested in what sort of processes are followed that let this change go into a public release.

The same sort of process that allows people to put offensive, inappropriate, and inane comments into the gitlab: We're a community project of volunteers that does the best we can. Anyone can create an account and anyone can contribute and although all commits are reviewed by at least one other person who has merge rights and all rules are discussed, sometimes single line changes aren't paid attention to as closely as they could be. Feel free to fork the system and build your own version, if you prefer. For the speed of evolution and the size and complexity of the system, especially given that this is done freely by volunteers on their spare time, I think that we do a pretty amazing job.

**Comment by simonward** [comment]
The initial issue report was https://github.com/foundryvtt/pf2e/issues/7196
When I reviewed the report, I mistakenly believed it to be accurate.

**Comment by ZephyrS8** [comment]
Thanks Simon, that's what I was after. Just a little bit of insight into how these things run. I re-read my question a few times to make sure it was precise and not offensive, that was not my intention. I think you do an amazing job too. I also, however, think that sometimes you make decisions that seem wrong, or incorrect and I was wondering as to the process. As you now have the term 'official' in your name, and there are paid for Paizo products that require this to run, I am not sure that telling users to fork their own version is a great solution.

**Comment by TMunsie** [comment]
> Thanks Simon, that's what I was after. Just a little bit of insight into how these things run. I re-read my question a few times to make sure it was precise and not offensive, that was not my intention. I think you do an amazing job too. I also, however, think that sometimes you make decisions that seem wrong, or incorrect and I was wondering as to the process. As you now have the term 'official' in your name, and there are paid for Paizo products that require this to run, I am not sure that telling users to fork their own version is a great solution.

If someone is competent enough to find this ticket to be able to comment on it, then the assumption is that they can also click the links to see the decision and approval chains from the initial report with the rule statement, to the fix, to the report on the error with the initial bug, to the reversion. 

If you were truly interested in understanding you would have done this first instead of coming and writing your question. You would have read the project documentation as well.  Your question made it clear that neither of those things were done. And it is a question that would be better asked somewhere on discord and not on the git repository.
