### ISSUE TITLE
Traits not autofilled when browsing archetype feats from character sheet

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#7250]
1) Enable free archetype
2) Click Browse or the magnifying glass next to an empty slot

<img width="499" alt="Screen Shot 2023-04-01 at 8 42 59 PM" src="https://user-images.githubusercontent.com/1904698/229330121-90fd9cf4-fc37-458a-8cf2-251ab156fd2c.png">

Note how the resulting list isn't pre-filtered.

**Comment by stwlam** [comment]
Fixed at some point

**Comment by simonward** [comment]
I just tested this, and it does not appear to be fixed.

**Comment by stwlam** [comment]
Class feats are prefiltered.
