### ISSUE TITLE
Fury Barbarian extra damage feature is not working correctly

### ISSUE THREAD

**Issue by Takaskii** [foundryvtt/pf2e#7258]
The feature that provides the fury barbarian with extra damage at certain levels does not add any bonus damage before or after calculation.

**Comment by stwlam** [comment]
Can you say what you're seeing, and how it's different than what you're expecting to see?

**Comment by TikaelSol** [comment]
Unable to reproduce the issue. Fury barbarians don't get a damage increase until level 7. If you are above level 7 then try setting your level to 0 then back, this may be due to an imported character.
