### ISSUE TITLE
Unable to set price for 'Treasure' Items

### ISSUE THREAD

**Issue by BaklavaBear** [foundryvtt/pf2e#7262]
Since updating to 4.10.0, all 'Treasure' type Items cannot hold a price value. All other Item types are able to be given a price. Whenever I give a 'Treasure' Item a price, the box goes blank. This applies to new Items and old ones from before the update. I have tried diasbling all mods and the issue persists.

**Comment by EtienneLamoureux** [comment]
I can reproduce. Additionally, editing an existing treasure item with a value resets it to 0.

**Comment by nikolaj-a** [comment]
Try updating a bit more 🙂 It was fixed in an follow-up release.
