### ISSUE TITLE
Creature attacks requiring multiple actions

### ISSUE THREAD

**Issue by Jnosh** [foundryvtt/pf2e#7279]
Creature attacks requiring multiple actions don't currently seem to be supported.

Seems to be very rare, the only two instances I am aware of are:
* Xulgath Gutrager (EC4)
* Barnacle Ghoul (AoE3)

Both have a ranged attack using two actions in the PDF but are listed as using one action in the compendium. For Barnacle Ghoul, '[Two Actions]' is even accidentally in the attack name.

**Comment by stwlam** [comment]
This is something we've decided not to support, as it's isolated to two APs that were underway before the initial line of rulebooks were finalized. NPC attacks are Strike actions, and Strike is a single action. The annotation in that attack name isn't an accident but a clarification for the (likely never to be corrected) stat block in the AP.

**Comment by Jnosh** [comment]
Thank you for the clarification!
