### ISSUE TITLE
`resizeEquipment` option of CreatureSize rule element doesn't treat small creatures as medium

### ISSUE THREAD

**Issue by natis1** [foundryvtt/pf2e#7296]
When you are resized by the creature size rule element, resize equipment should preserve bulk values. It should do this by treating size medium and small as a single size category for equipment. And when creatures are grown from small to medium or shrunk from medium to small, it should not do any equipment resizing.

Here are three case studies where the current behavior causes problems:
- If you are size small and grow to size large, and your equipment is anything other than size small, (all equipment being size medium by default when dragged onto your inventory, even as a size small creature), you will instantly find yourself massively encumbered. This means you need to manually edit every single item to make it size small.

- The above situation causes problems with giant barbarians as taking a size large weapon of bulk 2 on a small creature will lead the item going from 4 bulk to 8 bulk when you use Giant's Stature (as it grows two equipment size categories from large to gargantuan while the PC only grows one equipment size category from small/medium to large). Taking a medium sized weapon causes you to lose a massive rage damage bonus when not using Giant's Stature though.

- You can cheese the fact the game treats medium and small equipment identically by choosing to take small equipment on a medium sized character. Then if by some magic you shrink from size medium to size small, now all your equipment is size tiny and extremely easy to carry around. Also, any large equipment you have now becomes medium and much easier to carry. The spell Humanoid Form, as an example, can produce this behavior.

If this behavior is fully intended by the game designers then I believe we should at least get a option added to resize-equipment for preserving bulk values. However, it's my interpretation of the rules that there should only be one size category for equipment that is suitable for medium or small creatures and going from small to large should only increase equipment size by one category so bulk is preserved.

Images show the inventory before and after applying Giant's Stature on a size small creature
![image](https://user-images.githubusercontent.com/2016651/230273210-02093fba-9a61-4809-9eb5-f9f72233d852.png)
![image](https://user-images.githubusercontent.com/2016651/230273114-3446f5c4-02f9-40dd-af77-8930d131cde3.png)

**Comment by stwlam** [comment]
The Creature Size rule element includes a `resizeEquipment` option to do precisely what you describe.
