### ISSUE TITLE
FR: Have the system track item activation on sheet.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#7306]
if you are using an item that has a once per day activation or more there is nothing on the system that tracks that activation.

i came across this issue with orc ferocity where mechanically it would activate but it wouldnt tick down. from 1 of 1 to 0. 

other instances where items have a once per day but no way to track them currently.

**Comment by stwlam** [comment]
Reactions aren't implemented, so what you're describing if from a module

**Comment by ThingsCouldGetDicey** [comment]
this isnt just about orc ferocity its for anything that has a once per day use.
