### ISSUE TITLE
[Bug] Flanking is applying flatfooted to strikes made with ranged weapons within melee range

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#7318]
Actors in this configuration:
![](https://i.imgur.com/4Um4aXf.png)
produce this result:
![](https://i.imgur.com/Ez5KRp0.png)

screenshots were taken in a high-module world, but I tested with no modules active, just dropped valeros and ezren on opposite sides of a goblin warrior, same outcome.

**Comment by asuffield** [comment]
Here's the culprit: https://github.com/foundryvtt/pf2e/commit/5079c878fb891429c7c3e5d81fcdb3d22a5ffe5b

This implementation of getReach invalidated the expression used in ActorPF2e.getRollContext, which depends on this not working. Fix incoming.
