### ISSUE TITLE
Feature Request: RollOption differentiating critical damage rolls from regular damage rolls

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#7325]
IE, if, on a strike card, I hit the 'critical' button instead of the 'damage' button, inject a RollOption marking it as such. This would be to facilitate automation like increasing dying by an extra point on critical damage, and probably other things I'm not thinking of.

**Comment by asuffield** [comment]
It's sort of in there already, it's in DamageRollContext.outcome. There's an interesting question about whether we want everything in the context objects to be replicated into roll options, but automation should be able to get hold of it easily enough.

**Comment by DocSchlock** [comment]
A `check:outcome` RollOption was added to damage rolls at some point that should satisfy this request.
