### ISSUE TITLE
Disambiguate the battle medicine immunity and treat wounds immunity effect icons

### ISSUE THREAD

**Issue by bogga** [foundryvtt/pf2e#7346]
Currently, the icons for Effect: Battle Medicine Immunity and Effect: Treat Wounds Immunity are the same, making it harder for party members, specifically the healers, to see at a glance what is available. For my group, it requires us to stop game flow and have each player read out the current immunities, which is a little frustrating

Could we change the icons for either treat wounds and its immunity or battle medicine and its immunity?

**Comment by sandersontavares** [comment]
To add to that, I think it would be more interesting to propose that Battle Medicine Immunity be generated by actors, and have the symbol use the picture of the character, so as to discern from which friend's battle medicine you're immune.

**Comment by bogga** [comment]
that would be cute! I think it's definitely scope creep for this issue but we could split this into two separate things. I believe the Treat Wounds & Battle Medicine macro from pf2e workbench handle this in the meantime :)
