### ISSUE TITLE
Item bulk amounts are adjusted according to vehicle size as though vehicles were creatures

### ISSUE THREAD

**Issue by tpegasus79** [foundryvtt/pf2e#7357]
When you import a vehicle from the compendium, like a wagon and add equipment to the vehicle for storage, the bulk of the items stored are reduced by 1.  A screenshot shows half-plate (normally 3 bulk) as 2 bulk and shields are showing as L instead of 1 Bulk. I do not see anywhere under vehicle rules where you count stored equipment as 1 less on bulk when on a vehicle.  If there is a place to show this could you point me in the right direction.  Other than that, this looks like a bug.
![Vehicle Bulk](https://user-images.githubusercontent.com/37181891/231023088-e6207527-3b3b-4287-9b57-b18dc3a93c7a.jpg)

**Comment by nuclearGoblin** [comment]
If you add a larger item, it looks like it is taking half and rounding up; an alchemist's lab has bulk 3 inside a wagon instead of bulk 6: 

![image](https://user-images.githubusercontent.com/45541156/231038082-93a17bee-426a-43b2-abf1-45a34c04533b.png)

I wonder if this is intentional, as a horse (or other creature) would be dragging a wagon, so the bulk is treated as half according to the [dragging rules](https://2e.aonprd.com/Rules.aspx?ID=193).

**Comment by tpegasus79** [comment]
That make sense with the dragging rule.  Did not think of that combined with a vehicle.  One of the many things I love about PF2e is the complexity that can be done with it. 
Since you spoke of the dragging rules, it looks like size of the vehicle plays a part in the bulk amount.  I imported a sailing ship and half plate became L bulk.

The question though since its just cargo it's about weight and each large creature pulling a wagon can typically pull 100 bulk the wagon can hold 200 bulk total.  So, 100 suits of half plate for a 10 x 10 wagon?  Seems a bit excessive.

If this is correct where even as a cargo holding, and it should be reduced by the size of the vehicle please let me know if it is calculating correctly.

**Comment by nuclearGoblin** [comment]
Interesting. This leads me to believe the dragging rules are unrelated. Maybe it is related to the [bulk conversion rules](https://2e.aonprd.com/Rules.aspx?ID=257) instead, then. For a gargantuan **creature**\*, an object of 3-4 bulk is treated as light. This behavior also occurs for a gargantuan player character (though you have to specify the size of items such as armor): 

![image](https://user-images.githubusercontent.com/45541156/231607906-713ebc60-a9c7-4bdc-befa-b09f6845974c.png)
![image](https://user-images.githubusercontent.com/45541156/231607949-a8f9795e-39ac-49ed-8db6-67d38a8f409f.png)
![image](https://user-images.githubusercontent.com/45541156/231608054-82d55d28-df17-4268-816c-65644fc317e8.png)

\*However, those rules seem to be explicitly for creatures, and rereading the [vehicle rules](https://2e.aonprd.com/Rules.aspx?ID=1279), they seem to imply that the bulk adjustment rules aren't meant to apply. I am still learning my way around PF2 (coming from PF1), so someone correct me if I'm misinterpreting this.
