### ISSUE TITLE
Inventor's Overdrive feature

### ISSUE THREAD

**Issue by tpegasus79** [foundryvtt/pf2e#7358]
The overdrive feature from the Inventor is normally only for the inventor, but if you take the prototype companion innovation you can apply your overdrive to the companion. The effect: overdrive that you can apply to tokens uses the effected tokens intelligence modifier for the adjustment instead of the inventor's intelligence modifier. Is there a way to update this to where it uses the inventor's ability modifier so the adjustment on the damage for the companion displays and calculates correctly?  same goes for effect: critical success overdrive and each level above (expert overdrive, etc etc.)

**Comment by stwlam** [comment]
Duplicate of #7237
