### ISSUE TITLE
Sundry item-data errors

### ISSUE THREAD

**Issue by Malkyn99** [foundryvtt/pf2e#7365]
Went through to update my loot rolltables and found a few things worth reporting.
Vigilant Eye (Major) is the wrong level.
Wand of Pernicious Poison (Purple Worm Sting) has copy in the name, but is otherwise the right level.
Blessed Reformer is not capitalized right.
Energy Mutagen and Stone Body Mutagen are not associated with Treasure Vault as a source despite getting a reprint.

**Comment by simonward** [comment]
For Energy Mutagen and Stone Body Mutagen, if there are no updates then the earlier source is preferred. If there are any updates needed to these items, please file a separate ticket.

**Comment by simonward** [comment]
Actually, I see the rarity has changes. I will update.

**Comment by simonward** [comment]
Mutagen sources changed updated via https://github.com/foundryvtt/pf2e/pull/7379
