### ISSUE TITLE
V11 feature request:  pre-package the compendium packs in folders

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#7408]
Foundry V11 will add compendium folders and therefore allow the module to organize the compendium packs better.

Currently, there are 73 packs, which is **a lot** of packs.  They take up so much space that scrolling down the list is time-consuming, even though it's necessary sometimes - particularly for non-pf2e compendiums (as the pf2e content is more easily accessed through the compendium browser).  It would be great to collect many of them together, grouped up and divided among folders.

Note that, based on recent V11 development commentary, systems and modules will not be able to include such folders as part of the manifest;  instead, they'll have to add it to some initialization/migration script for now.

The actual division of folders is something that should be given more consideration, but my initial suggestion is to simply divide them by type and subtype.  This means one folder for all Actors, one for all Items, one for all Journal entries, etc.  This can also be a bit less simple, with subtypes - for example, one folder for all Player Characters, one for all NPCs, one for Feats, one for Actions, etc.

An alternative division to suggest would be by source category:  one folder for all "core series" rulebooks, one oflder for all adventure path content, etc.  However, that division may require splitting up some of the packs - e.g. "Feats" which currently has all feats from all sources.

**Comment by TMunsie** [comment]
We'll likely just go back to the same organizational scheme we have in Foundry 0.7

**Comment by stwlam** [comment]
Currently not possible in V11

**Comment by LebombJames** [comment]
Atro mentioned a one-time script the first time a world is loaded to create and assign compendia to folders. A potential solution
