### ISSUE TITLE
Damage Type is not recognized in Roll Tags with math in them

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#7416]
Damage Type in `[[/r ]]` tags is not recognized when you add, subtract, or do any kind of calculations inside the tag.
Example:
```
[[/r 2d10[bludgeoning]]]
[[/r 2d10+5[bludgeoning]]]
```
The latter example will not output bludgeoning damage.

This can be fixed by adding parenthesis to the whole equation, `[[/r (2d10+5)[bludgeoning]]]`, but that's unnecessary overhead as well as it requiring the writer to add curled brackets to have appropriate, parenthesis-less text `{2d10 + 5 bludgeoning}`.

**Comment by stwlam** [comment]
This is core operator precedence, so we're not going to change it unless upstream does.
