### ISSUE TITLE
Feature Request: A method to have an applied effect's initial badge value be conditional on an actor property

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#7423]
eg to allow a counter with value `@actor.abilities.con.mod + 5` for a 'Holding Breath' Effect, etc

**Comment by Strangley-Browne** [comment]
I reckon, Getting Swallowed, Drowning, Buried Alive, Getting caught in a vacuum and general GM bastardy. ![image](https://user-images.githubusercontent.com/87890230/232272515-72d72644-9715-4056-976d-a82eb5f46d21.png)

**Comment by DocSchlock** [comment]
Support for this was added at some point. I tested the example request using the Formula counter value type and it worked with actor properties.

Closing as completed.

**Comment by esheyw** [comment]
So, I guess I never tested with formula instead of straight counter? Or it slipped in while I wasn't looking. However, this is still not actually super useful, as setting the badge this way does not allow changing it, rending it pointless for any use case, like held breath, where it starts at a value and should tick down from there. I'll open a separate feature request.
