### ISSUE TITLE
Feature Request: Some method of dragging an item link from its own sheet

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#7424]
I often will open up quick insert, type some stuff in, click an entry that looks promising, read through it's description, decide yes, that's what I want, and then... I need to open quick insert again and retype to actually drop the item somewhere. There's no way from just that sheet to drag a copy of that item to a token or character sheet or whatever. I think having this option would be a very nice QoL improvement. 

The drag handle could either be the item's icon, or maybe if its possible to add drag handling to the 'get id' button? or, worst case, add a specific new thing to grab, somewhere on the sheet.

**Comment by stwlam** [comment]
This is more a limitation of the Quick Insert module: all core and system workflows leave a draggable link in place after clicking it to open an item sheet.
