### ISSUE TITLE
Misspelling in Description of Feat "Eerie Flicker"

### ISSUE THREAD

**Issue by DregoryTerm** [foundryvtt/pf2e#7440]
The **Trigger** for the Reaction of the _Eerie Flicker_ feat begins with "A enemy's Strike ..." when it should be "An enemy's Strike ...".
![image](https://user-images.githubusercontent.com/50883644/232558446-63db31f6-9b5d-447d-8087-4e30e17e54f8.png)

**Comment by simonward** [comment]
This misspelling exists in the source document.

<img width="331" alt="Screen Shot 2023-04-17 at 10 10 03 AM" src="https://user-images.githubusercontent.com/1904698/232559509-8a550eb6-d0fb-4ed0-8dca-e0a24a060bcb.png">
