### ISSUE TITLE
Feature Request: Add homebrew trait support to hazards

### ISSUE THREAD

**Issue by CrimsonPolar** [foundryvtt/pf2e#7465]
In the Manage Homebrew Elements, it is currently not possible to add traits for hazards. This would be useful as hazards are currently missing some traits that would be helpful to have such as Animal and Disease.

**Comment by stwlam** [comment]
"Animal" is part of hazard traits now. "Disease" may be added as a trait of a hazard's abilities, but even disease-centric hazards don't have the trait themselves. At this point I can't see there being sufficient grounds for adding hazard traits to homebrew options.
