### ISSUE TITLE
Feature Request: Hide the traits of a mystified item to the players

### ISSUE THREAD

**Issue by preslavnpetrov** [foundryvtt/pf2e#7505]
When players see the traits of a mystified item, it gives them an idea of what the item is without making the necessary rolls to identify magic and so forth.

It would be best to have the traits of mystified items hidden to players, but still visible to the GM.

**Comment by stwlam** [comment]
Where are they appearing?

**Comment by preslavnpetrov** [comment]
My bad, this is a duplicate of #6785, we were just running an old version.
