### ISSUE TITLE
Bug: Cannot craft Aether Marble (Lesser) with Advanced Alchemy

### ISSUE THREAD

**Issue by enumag** [foundryvtt/pf2e#7519]
I'm playing a Bomber Alchemist so I'm collecting all the bomb recipes I can. So I also added "Aether Marble (Lesser)" into my crafting list. Normal crafting works however when I try to add this bomb into the list I want to have crafted during daily preparation with Advanced Alchemy it fails with this error:

```
No eligible crafting entry was found.
```

Didn't encounter this issue with any other bomb or elixir so far, only this one.

**Comment by enumag** [comment]
I think it might be due to a typo. On the PF2E website the bomb is called [Aether Marble](https://2e.aonprd.com/Equipment.aspx?ID=2416) while in this plugin it's called "Aether Marble*s*". Other versions of this bomb likely have the same issue.

**Comment by Cerapter** [comment]
It's not an alchemical bomb, it's just a bomb, therefore it's not valid for your alchemical crafting entry.

Now, literally every other bomb in existence also has the alchemical trait, so you can just chalk it up to "standard AP quality writing".

**Comment by enumag** [comment]
Whoa I completely missed it's missing the alchemical tag. Do you think it's intentional or that it's simply an error on PF2E website?

**Comment by stwlam** [comment]
Reading the description, it seems plausible that it's truly intended to be a non-alchemical bomb. We're going to have to keep it as written unless/until there's errata for it.
