### ISSUE TITLE
Stealth bonus from Pest Form not applying in roll calculation

### ISSUE THREAD

**Issue by ahoward-cf** [foundryvtt/pf2e#7533]
Pest Form spell effect should apply a +10 bonus to Stealth. It does appear to on both character sheets and NPC sheets (the modifier becomes +10, and on NPC sheets, becomes blue) when the Pest Form effect is active, but this bonus is not actually applied to the roll in any way. It does not appear when fast rolling, nor is there a toggle option in the roll dialog. This is true for v4.10.4, and has been the case for several weeks. No errors are created in the console when Stealth is rolled while Pest Form is active.

**Comment by stwlam** [comment]
Fixed by #7392
