### ISSUE TITLE
Feature Request: a property on Aura REs to allow them to ignore walls entirely.

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#7548]
This would allow for 'everyone in your party...' effects, such as Scouting.

**Comment by CarlosFdez** [comment]
That sounds more like "if the range is unlimited, remove wall testing" type of deal, in my biased opinion.

**Comment by esheyw** [comment]
That would certainly work for Scouting, but maybe someone wants to homebrew some BBEG aura of 'you feel bad within 60ft' that ignores physical obstacles? I'll leave implementation choices to you folks, but I think there's value in allowing for such things. Maybe ignore walls if it has the `mental` trait?

**Comment by LebombJames** [comment]
Mental effects would still require line of effect so wouldn't pass through walls. But I do agree that "you feel bad within 60ft" is a valid use case

**Comment by esheyw** [comment]
Adding 'effects that should be applied to everyone on a Plane' to this list of things this would help with: https://discord.com/channels/170995199584108546/697845559435853865/1127767415791566970

**Comment by stwlam** [comment]
Not aura-related
