### ISSUE TITLE
'Crit Effects' text missing from the Critical Hit Deck effects entries

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#757]
In GitLab by @Darkling0057 on Sep 4, 2020, 23:37

92 / 216 of the effects of the cards are missing the 'Crit Effects' text

I think the table column being labeled 'Crit Effects' was an attempt to do this and save space, but not all of the effects on the cards are Crit effects.

e.g: Critical Hit Deck # 2: 'Where Am I?' and 'Surprise Opening' are Crit Effects, 'Missing Ear' and 'Mind Cloud' are not.
![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/ef5e99ee5ef8fde0a87010a4af86ed2d/image.png)

This mechanically effects some applications.  
As per the rules 'Crit Effects' replace a weapons 'Critical Specialization Effect' but the other effects, like Missing Ear, will happen in addition to a weapons critical specialization effect.

**The specific entries which should include "Crit Effect" text:**

[card number. Name of each entry which should have a crit effect]  

I've included the ones with no entries needing changes, just so it's clear they weren't skipped

(I also noticed a few other minor errors while going through them so I've noted those as well)

- 1: Crunch, Forearm Piercing, Surprise Opening
- 2: Where Am I?, Surprise Opening
- 3: Surprise Opening, Brow to Chin
- 4:
- 5: Feeble Parry, Shoulder Wound, Hamstring
- 6: Cracked Knee, Calf Jab
- 7: Bell Ringer, Skewered
- 8: Split Open, Send 'Em Reeling, Shattered Jaw
- 9: Tangled
- 10: I see Stars, Pinhole
- 11: Two in a Row, Weapon Strike
- 12: Missing Digits
- 13: Throat Slash *[this is card 14 in the pdf]*
- 14: *[this is card 15 in the pdf]*
- 15: Numbing Blow, Overhand Chop *[this is card 13 in the pdf]*
- 16: Two for One, Cut Straps
- 17: And Stay Down!
- 18: Rattled, Guarded Strike, Severed Tendon
- 19: Nighty Night, That'll Leave a Mark!
- 20: 
- 21: Collapsed Lung, Nerve Cluster
- 22: Bony Masher, Punctured Lung
- 23: Nicked an Artery
- 24: Ruptured Spleen, Muscle Severed
- 25: 
- 26: Crushed Intestines, Lodged in the Bone, Severed Spine
- 27: Crushed Trachea, Long Gash
- 28: Skull Crush, Hand Wound
- 29: Caved Skill
- 30: To Your Thinky Bits
- 31: Across the Eyes
- 32: Head Shot, From Chops to Groin
- 33: Broken Rids, Spinal Tap, Nerve Slice
- 34: Staggering Blow, Heart Shot
- 35: Thunder Strike, Decapitation
- 36: 
- 37: 
- 38: Armor Dent, Eye Patch for You
- 39: Soul-Crushing Blow
- 40:  
- 41: Broken Leg, Grazing Hit, Swing Through
- 42: Shield Smack, Muscle Wound
- 43: 
- 44: Knockback, Deep Hurting
- 45: Low Blow, Hobbled, Bad Parry
- 46: Busted Shin, Sapping Slash
- 47: Back Breaker, Deep Wound, Brow Cut
- 48: Busted Shin, Sapping Slash
- 49: Tenacious Wound, Parrying Strike
- 50: Leg Wound
- 51: Organ Scramble
- 52: Light's Out, Bewildering Display
- 53: Roundhouse, Delayed Wound
- 54: *[This entry is a duplicate of 45]*

**Comment by TikaelSol** [comment]
This was solved with the rework of the journal entries.
