### ISSUE TITLE
Bug: Invalid reference to main.css when editing an items description. 

### ISSUE THREAD

**Issue by Oshcakes** [foundryvtt/pf2e#7580]
![image](https://user-images.githubusercontent.com/61471647/235138145-fcb9607f-d1df-4ba8-945d-c4212c8a836f.png)

**Comment by reonZ** [comment]
https://github.com/foundryvtt/pf2e/blob/5f6fd0209d680f7e9e492e80e3df64f3f19a1bf3/src/scripts/hooks/init.ts#L83
