### ISSUE TITLE
Night Hag's Nightmare Rider incorrect reference

### ISSUE THREAD

**Issue by FrostLock63** [foundryvtt/pf2e#7587]
Nightmare Rider refers to the creature Nightmare, but is instead linked to the spell Nightmare.

**Comment by FrostLock63** [comment]
Actually the passive section for Night Hag is just a mess, with a lot of unnecessary entries.

**Comment by simonward** [comment]
Many of the passive entries contain rule elements to implement those abilities, so they're not entirely unnecessary.
