### ISSUE TITLE
New Automation: Could you guys make possible to add a Condition to a Strike so if the target takes the damage it becomes Flat-Footed (for instance) without the need of dragging the effect to the token?

### ISSUE THREAD

**Issue by Bomberman1988** [foundryvtt/pf2e#7633]
It's gonna make so much easier to apply the effect of bombs, Debilitations (from Rogues), etc. I know it's possible to do it with Persistent Damage, but not with Conditions (hopefully yet).

**Comment by stwlam** [comment]
Applying non-damaging effects isn't going to happen without user intervention.
