### ISSUE TITLE
Acid Splash description cleanup request

### ISSUE THREAD

**Issue by Demorome** [foundryvtt/pf2e#7639]
![image](https://user-images.githubusercontent.com/69116996/235550147-74fbe7ab-83a8-4035-8759-b8b086a7e762.png)
The circled red part should say "1 acid splash damage", since currently it isn't immediately obvious when reading that this "1 acid" is splash damage.

Could either use this: `[[/r (1[splash])[acid]]]{1 acid splash damage}`
Or just remove the inline roll entirely and replace it with the text, since the damage is automated when casting the spell anyways.

**Comment by ThingsCouldGetDicey** [comment]
i think that anything that has the automation for splash damage should just revert to text to make it cleaner.
