### ISSUE TITLE
Predicates that are not arrays behave identically to predicates with a single RollOption

### ISSUE THREAD

**Issue by cjneidhart** [foundryvtt/pf2e#7664]
According to the documentation in the wiki, predicates must be arrays. However, predicates that are just a string behave identically to an array containing that string. No warning or other feedback is given to the user that this is considered incorrect.

Here's a trivial example of a RulesElement that works. This rule will only be applied when the actor is Level 2, just like if the predicate were `["self:level:2"]`.
![image](https://user-images.githubusercontent.com/22824545/235956117-79bfedbc-de11-4600-a7cd-7e2533491c8d.png)

Potential Solutions:
- When a non-array predicate is entered, display an error and disable the rule. This behavior matches what happens when a user enters a predicate that is invalid JSON.
- Change the wiki's documentation (and the types in the source code, if necessary) to officially support non-array predicates.
- Silently correct non-array predicates. Once the text box is unselected, brackets will be added to the predicate if it's not already an array.

**Comment by stwlam** [comment]
This is due to Foundry's `DataModel` API being extremely lax. I don't know that we need an immediate fix here: an array structure is documented as being required, even if a non-array is silently wrapped in one.
