### ISSUE TITLE
Insight Coffee needs Rule Elements

### ISSUE THREAD

**Issue by DirtyLaundry6** [foundryvtt/pf2e#7697]
While the bonus depending on the type of coffee created can easily be added as a modifier by the player, there needs to be a way to change their Strategic Strike dice from D6 to D8 while under the effect of the coffee.

**Comment by TikaelSol** [comment]
We currently lack the ability to upgrade the damage dice of a class feature in a clean way. We could alter the feature to have it be d8 when the effect is present but then people would need to either replace the class feature on their sheets or we migrate it.

**Comment by Tridus** [comment]
You can do this in your own game by modifying Strategic Strike to do d8s when something it recognizes as Insight Coffee is up. I did that like this:
1. Create a custom effect for Insight Coffee with a different slug (I used "insight-coffee-chris"). It's pretty easy to add the bonus to the skill check from here.
2. Change the existing rule on strategic strike to add a nand to not apply it when insight coffee is up:
 `{"category":"precision","dieSize":"d6","key":"DamageDice","predicate":["devise-a-stratagem",{"nand":["self:effect:insight-coffee-chris"]}],"selector":"strike-damage","value":{"brackets":[{"end":4,"value":{"diceNumber":1}},{"end":8,"start":5,"value":{"diceNumber":2}},{"end":12,"start":9,"value":{"diceNumber":3}},{"end":16,"start":13,"value":{"diceNumber":4}},{"start":17,"value":{"diceNumber":5}}]}}`

3. Add a second rule elemnt to strategic strike for d8s when the buff is found:
`{"category":"precision","dieSize":"d8","key":"DamageDice","predicate":["devise-a-stratagem","self:effect:insight-coffee-chris"],"selector":"strike-damage","value":{"brackets":[{"end":4,"value":{"diceNumber":1}},{"end":8,"start":5,"value":{"diceNumber":2}},{"end":12,"start":9,"value":{"diceNumber":3}},{"end":16,"start":13,"value":{"diceNumber":4}},{"start":17,"value":{"diceNumber":5}}]}}`

This isn't a very clean way to do it, but all the player has to do is apply the custom effect to themselves and the dice change, so it does work. Might be a viable solution for you while the system doesn't handle it.

**Comment by pedrogrullada** [comment]
Closed by #15645
