### ISSUE TITLE
EphemeralEffect: NPCs with initiative:rank predicates don't apply Flat-Footed when dealing Strike damage from the character sheet

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#7707]
Steps:

1) Add the EphemeralEffect RE to an NPC with Sneak Attack and Surprise Attack. I used Assassin, and added it to the Surprise Attack passive.
```
{
	"key": "EphemeralEffect",
	"predicate": [
		"encounter:round:1",
		{
			"lt": [
				"self:participant:initiative:rank",
				"target:participant:initiative:rank"
			]
		}
	],
	"selectors": [
		"strike-attack-roll",
		"spell-attack-roll",
		"strike-damage",
		"attack-spell-damage"
	],
	"uuid": "Compendium.pf2e.conditionitems.AJh5ex99aV6VTggg"
}
```
2) Add the NPC plus a target to the combat tracker, round 1, and begin the encounter.
3) Target a creature with worse initiative.
4) Roll a Strike from the NPC sheet. Note how Flat-Footed is applied.
5) Roll damage from the NPC sheet.
	Note how Flat-Footed is NOT applied, as there is no Sneak Attack damage.
6) Roll damage from the Strike card in the chat.
	Note how Flat-Footed is applied, as there is Sneak Attack damage.

Note that it does work for EphemeralEffects that aren't initiative based.

**Comment by CarlosFdez** [comment]
Might I have fixed this just recently without realizing what I fixed was the root cause of this? Does this issue still persist?

**Comment by simonward** [comment]
> Might I have fixed this just recently without realizing what I fixed was the root cause of this? Does this issue still persist?

Retested, and the issue still occurs.

**Comment by CarlosFdez** [comment]
Wait, before I dig in, that RE uses the participant's proficiency rank. NPCs don't have ranks at all. Why is it predicating rank?

**Comment by simonward** [comment]
> Wait, before I dig in, that RE uses the participant's proficiency rank. NPCs don't have ranks at all. Why is it predicating rank?

initiative:rank, which is not a proficiency.

**Comment by CarlosFdez** [comment]
I see, that property name is incredibly misleading. 

I tested on latest master, are you sure you have everything right? Is the combat not started?
![image](https://user-images.githubusercontent.com/1286721/236887417-6c195c01-c440-44a4-8c4e-c4116f5276e3.png)

**Comment by simonward** [comment]
The strike works, but not the damage.

**Comment by CarlosFdez** [comment]
That'll learn me to read an issue after only sleeping 4 hours. That said at the very least its definitely an ephemeral effect issue, and doesn't *seem* to be something stemming from either the damage or perception refactor.

**Comment by stwlam** [comment]
Does this work with attack or damage rolls using PCs?

**Comment by simonward** [comment]
> Does this work with attack or damage rolls using PCs?

Verified that it works correctly for PCs.

**Comment by stwlam** [comment]
No examples in compendiums

**Comment by simonward** [comment]
<img width="301" alt="Screen Shot 2023-05-09 at 2 12 32 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/5aeae813-f2ed-4d7b-8eb0-99181712d5aa">
