### ISSUE TITLE
Seugathi Magic Item Mastery Feature - Scrolls and Wands

### ISSUE THREAD

**Issue by ChaseDonnally** [foundryvtt/pf2e#7734]
Creatures with the "Magic Item Mastery" feature should be able to use spells and wands. (I believe this is mostly Seugathi but it's possible other NPC creatures have this Passive Ability). Currently the system will not allow these creatures to use spells or wands since it thinks they don't qualify.

**Comment by stwlam** [comment]
I think this will be the first NPC that can leverage items-only spellcasting

**Comment by TikaelSol** [comment]
The DC on items only always resets to 0 on NPCs on any actor update, so we can't implement this one just yet.

**Comment by CarlosFdez** [comment]
Seems like a bug that needs fixing
