### ISSUE TITLE
Feature Request - Actor permission to view player sheet but not token vision.

### ISSUE THREAD

**Issue by natis1** [foundryvtt/pf2e#7745]
Currently the limited permission lets you see a small aspect of a player sheet, but not the token vision.
The observer permission lets you see the whole sheet and token vision.

I want a way for my players to be able to view the entire character sheets but not the associated visions of the tokens. My players wanted it to better coordinate builds and resources without having to send screenshots back and forth. But I want to maintain separate vision because some of my players have darkvision and others do not.

**Comment by natis1** [comment]
From what it seems like. Only five levels of sheet visibility are intended by the foundry vtt devs. I suggested changing this and got completely shut down by them. So I instead hacked together a module that will make it so the limited visibility sheet shows the entire sheet.

It's literally one line of code. It solves the problem for me anyway so long as you don't also want "limited" sheets to exist.

https://github.com/natis1/pf2e-limited-sheetview

**Comment by GorgoPrimus** [comment]
This is a thing I’ve asked for before and would love to see as well for the same reasons.

**Comment by stwlam** [comment]
This is an upstream limitation, and they've declined to split the two permissions.
