### ISSUE TITLE
[Question] PopOut! Module - JQuery Events

### ISSUE THREAD

**Issue by TheRealValiantic** [foundryvtt/pf2e#7790]
Hi! So let me start this thread off with the message that I do not know anything about coding, at all. It's magic to me.

But we've been using the PopOut! Module ( https://foundryvtt.com/packages/popout )  for a while, which is intended to only be used with 5e in fairness, but has worked wonderfully with the Pathfinder 2e module as well. Upon running into a bug last night, where characters were unable to swap equipment due to having the sheet 'Popped out', I've done some digging.

I ran into: https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues/95

And so basically, this 'Issue' is more of an attempt to gather information from my end. Apologies if that's not it's intended use. I'm willing to believe the Dev from PopOut! that'd it'd be a lot, if perhaps too much work, but I was wondering if another solution could perhaps be found to solve it. A work around on 2e's module, or perhaps someone with a better head for coding here could make a PopOut! Pf2e module/branch/similar module for the functionality. Or perhaps it's a thing that could be build into the sheets eventually and to not require a module at all.

For those of us with several monitors, being able to put pages/sheets/maps sheets over to the other one and reduce overlap is a really welcomed functionality. It's luckily a bug that can be worked around but figured I'd ask around nonetheless and this seemed like the best place to do it!

Thank you for reading, any bits of information is welcome about the issue. (I have no clue what a Jquery Event Listener even is)

Love all the work you all put into the module!

**Comment by TMunsie** [comment]
This is an issue that doesn’t really have anything to do with the PF2e system. It is just how core Foundry and the Pop Out module function. Your best bet is to find the ticket requesting that Foundry enable this functionality natively within the core software and support it.

We actively try not code the system for support for any specific module, no matter how good it is.

Closing as not within the scope of the system.

**Comment by stwlam** [comment]
In case it is helpful, the issue you link is flat wrong: the pf2e system utilizes jquery _less_ extensively than core Foundry or the dnd5e system (both of which are jquery-driven for virtually all interactivity within every application window).
