### ISSUE TITLE
Icon file picker no longer shows current icon path

### ISSUE THREAD

**Issue by simonward** [foundryvtt/pf2e#7794]
<img width="516" alt="Screen Shot 2023-05-08 at 1 02 45 PM" src="https://github.com/foundryvtt/pf2e/assets/1904698/8defeea9-3e9d-4eab-9e4e-86ca07896294">

**Comment by stwlam** [comment]
This is the pathfinder system repository. You'll want to post an issue like this here: https://github.com/foundryvtt/foundryvtt

**Comment by simonward** [comment]
Broken by:
```
commit cd52dbd8f42211b845858bbefa768f9ddb40eff8
Author: Shark that walks like a man <106829671+stwlam@users.noreply.github.com>
Date:   Thu May 4 04:57:09 2023 -0500

    Add interact (modular) weapon-auxiliary action (#7645)
```

**Comment by CarlosFdez** [comment]
My suspicion from digging in there is that there's a conflict due to the new selected handlebars helper.
