### ISSUE TITLE
Non-draconic sorcerers unable to use Dragon Disciple Dedication

### ISSUE THREAD

**Issue by sammichweasel** [foundryvtt/pf2e#7854]
Hi! the Dragon Disciple Dedication states "Access - You are a kobold with the dragonscaled or spellscaled heritage, a dragon instinct barbarian, or a draconic bloodline sorcerer." I haven't checked the barbarian or sorcerer options, but one of my players was trying to use a dragonscaled kobold to access the Archetype, and it keeps returning the error "[character] has no valid options for Dragon Disciple Dedication."

**Comment by stwlam** [comment]
Access isn't enforced by the system.

**Comment by sammichweasel** [comment]
Okay, so is there something else that it could be looking for? That's the exact text of the error, so it sounds like it's trying to find something specific

**Comment by sammichweasel** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/133836839/c0398384-4e83-4fde-9ce2-829a198723a4)

**Comment by stwlam** [comment]
Are you able to export the character and post a link here?

**Comment by sammichweasel** [comment]
I just swapped the character to a Draconic Bloodline Sorcerer, and was able to add the Dragon Disciple Dedication without any trouble. It appears that the feat is looking for these

**Comment by sammichweasel** [comment]
I can export it to a json, but I'm unfamiliar with how to get that to you.
