### ISSUE TITLE
Aerial Piledriver feat description is slightly wrong

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#7860]
![image](https://github.com/foundryvtt/pf2e/assets/6516621/b67a0676-2edf-4557-b64c-7762431a1098)

https://2e.aonprd.com/Feats.aspx?ID=3402

It should say "deals 1d6 **additional** damage".  The word "additional" is missing.

**Comment by simonward** [comment]
Could also use an automation pass.
