### ISSUE TITLE
Incorrect display of attributes

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#7873]
![image](https://github.com/foundryvtt/pf2e/assets/244795/f4e9d9c2-3771-432b-b95b-495980cf7f0f)

<img width="626" alt="image" src="https://github.com/foundryvtt/pf2e/assets/244795/78f30a11-539d-4ca8-b94b-28d7cbf72b80">

Using animal companion module, it's showing incorrect values to Dex and Int, it should be +9 dex and -2 int, it's probably related to the fact that players usually can't get this numbers, but as showed at the print, it's applying the +9 dex bonus correctly at reflex for example and the -2 to int on skills.

**Comment by stwlam** [comment]
Module data error
