### ISSUE TITLE
Animal Instinct added strike rage scaling is incorrect

### ISSUE THREAD

**Issue by Maelorn09** [foundryvtt/pf2e#7889]
Hi, I just noticed that for the animal instinct = cat the rage specialization ability at lvl 15 (scaling rage damage from 5 to 12) is only applied to one of the unarmed attacks (at least for cat animal type). 
The +12 bonus should be applied to both.

![image](https://github.com/foundryvtt/pf2e/assets/114569560/0e8eb75a-b080-4ef7-9c42-8ddc14710645)

![image](https://github.com/foundryvtt/pf2e/assets/114569560/23c154e0-f122-437e-b4d5-cbc165d06193)

**Comment by stwlam** [comment]
Module data error

**Comment by Maelorn09** [comment]
@stwlam the agile attacks don't stop the rage from adding additional damage. Why was this closed as not planned? The damage is added to cat's jaws but not cat's claws - this is the issue here.
![image](https://github.com/foundryvtt/pf2e/assets/114569560/09c68d4f-f7bd-4e08-9719-54f77c17ab12)
![image](https://github.com/foundryvtt/pf2e/assets/114569560/64910ef3-96c6-4318-9dcd-b96261238035)

![image](https://github.com/foundryvtt/pf2e/assets/114569560/e33ea4d2-9a42-464c-8c81-c55a59e19481)
