### ISSUE TITLE
Changing damage type with the modular trait's dropdown menu on the Strikes page picks up the Strike (in Firefox)

### ISSUE THREAD

**Issue by Cerapter** [foundryvtt/pf2e#7932]
In Firefox (113.0.1) on Arch Linux, when you change the damage type using the new dropdown menu on the PC's Strikes page, you pick up the HTML element for the strike as well. This doesn't do anything or cause any bugs as far as I could see, it just looks weird.

The same issue does not exist on Chromium 113.0.5672.92.

https://github.com/foundryvtt/pf2e/assets/43446478/fe3bd2e9-7e58-4d64-8bea-a7482d009dff

**Comment by stwlam** [comment]
Does "pick up" mean it triggers the dragstart listener?

**Comment by Cerapter** [comment]
Unsure, I could only really test after work.
But I can say it does call the `dropActorSheetData` hook when you click away afterwards, so it's not just something graphical.

**Comment by CarlosFdez** [comment]
Cannot repro on firefox on windows, but this is amazing.

**Comment by CarlosFdez** [comment]
Fixed by #7936
