### ISSUE TITLE
Adding/Subtracting HP

### ISSUE THREAD

**Issue by Cosmic-Lattee** [foundryvtt/pf2e#7939]
Tested using 4.12.0 without modules.

![HP Issue](https://github.com/foundryvtt/pf2e/assets/24766235/012a37ee-3053-4ef3-aa2c-0a316b015f2f)

So with the newest release it seems that directly adding or subtracting HP onto characters and monsters has been reversed. Damage done through buttons works normally.

**Comment by In3luki** [comment]
Thank you for the report. It looks like this was already fixed by #7926 so it should work as expected in the next release.
