### ISSUE TITLE
Create Spell Effect: Sanctuary

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#7946]
At the moment the Spell Sanctuary has no Spell Effect. Would it possible to create one? (Mostly for Reminder reasons, but my Group could use it for Animations aswell :) )

Sanctuary Reads (Copied from AoN):
You ward a creature with protective energy that deters enemy attacks. Creatures attempting to attack the target must attempt a Will save each time. If the target uses a hostile action, the spell ends.

Critical Success Sanctuary ends.
Success The creature can attempt its attack and any other attacks against the target this turn.
Failure The creature can't attack the target and wastes the action. It can't attempt further attacks against the target this turn.
Critical Failure The creature wastes the action and can't attempt to attack the target for the rest of sanctuary's duration.

**Comment by TikaelSol** [comment]
We don't add reminder effects to the system currently.  I think this is a good use case for eating some of the functionality of the PF2e Extempore Effects module to generate blank effects programatically as needed rather than storing something on disk that does nothing but start a timer.
