### ISSUE TITLE
Problems trying to updating PF2E

### ISSUE THREAD

**Issue by GanpaPape** [foundryvtt/pf2e#7960]
Try to update my game PF2E it usually takes about 5 minutes maybe 10 now it's taking forever and nothing's happening I get this error.
![image](https://github.com/foundryvtt/pf2e/assets/134349329/9c6d75fe-01ac-46fc-8e28-13f734735f1f)
I've talked to everyone on discord they all sent me here can you please help me out I have a game in two weeks.?
I also turned off all the modules.

**Comment by stwlam** [comment]
While this isn't a support venue, we do have a dedicated discord server for the pf2e system on foundry: https://discord.gg/pf2e
