### ISSUE TITLE
Change "malformed predicate" error message to be more helpful

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#7967]
Currently, there's an error that happens a few dozen times for me each time I open my world, which prints to the console:

> PF2e System | The provided predicate set is malformed.

I traced the code to the line `            return console.error("PF2e System | The provided predicate set is malformed."),` and only by adding a break point and manually debugging I managed to figure out which actual predicate set is malformed (in this case it seems to be something in the ability scores of a specific player character).

My request is that you change this console error message to be more helpful and descriptive, with one or more of the following pieces of info:
- name of actor
- name of item/field with the predicate
- literal predicate string

**Comment by stwlam** [comment]
We're working toward stringing together the item to each rule element so that it shows up in the stack trace
