### ISSUE TITLE
Issue with feat Nimble Dodge

### ISSUE THREAD

**Issue by reyzor1991** [foundryvtt/pf2e#7970]
When I toggle feat, AC not changed
but if I change domain from ac -> all then AC changed

<img width="849" alt="Screenshot 2023-05-23 at 12 48 45" src="https://github.com/foundryvtt/pf2e/assets/6688366/62dd96af-3c6b-4a4d-91c6-ef592c2d9bbf">

<img width="739" alt="Screenshot 2023-05-23 at 12 52 11" src="https://github.com/foundryvtt/pf2e/assets/6688366/949dbdb6-f7dd-4e2b-a206-6a857f0c3776">

**Comment by stwlam** [comment]
Duplicate of #7959
