### ISSUE TITLE
0-round effects don't work out of combat.

### ISSUE THREAD

**Issue by TomChristoffer** [foundryvtt/pf2e#7983]
0-round effects (such as true strike) are made to expire at the end of the current turn with a 0 round duration, but they only work inside combat encounters during your turn, if you apply the effect out of an encounter it just immediately expires and is unable to be used, so you have to manually edit the duration of the effect each time you want to use it. Especially egregious on things like Saoc Astroloy which is more or less meant to be used out of combat.

**Comment by stwlam** [comment]
This is intentional in the case of True Strike, but Soac Astrology should definitely work out of encounter mode. We'll look into it.
