### ISSUE TITLE
Dragon's Crest has bad data

### ISSUE THREAD

**Issue by robinsving** [foundryvtt/pf2e#7984]
After upgrading to 4.12.1 I am getting a number of errors in the logs. Most of them are currently useless ("The provided predicate set is malformed") but some look like real errors.
The character sheet is also looking a bit tattered, see below.

`ERROR: TypeError: Failed data preparation for Actor.JZjiFVkBj4hWDO1u. actor.abilities[ability] is undefined`

`WARNING: PF2e System | ActiveEffect-Like rules element on item Expert Sorcerer Spellcasting (Actor.JZjiFVkBj4hWDO1u.Item.66L4PYXZDufyjdUV) failed to validate: Failed to resolve injected property "system.proficiencies.traditions.{actor|system.proficiencies.aliases.sorcerer}.rank"`

N.b. reloading without mods yielded the same results.

Is it just for me to recreate the character, or is there some actual bug here to fix?

This is my character sheet after the upgrade. Confirmed on two different instances
![image](https://github.com/foundryvtt/pf2e/assets/3072502/bc918081-77b9-4f5e-a695-4a5b3ae20964)

Here is an export of the character, in case you want to test locally
[fvtt-Actor-grimm-wontan.json.log](https://github.com/foundryvtt/pf2e/files/11548616/fvtt-Actor-grimm-wontan.json.log)

**Comment by stwlam** [comment]
Sorry, but we're not able to handle support requests when an importer is in use.

**Comment by robinsving** [comment]
@stwlam This is unrelated to import/mod. It is the **Dragon's Crest** item that, when added to a character sheet, screws up things.

Please reopen.
