### ISSUE TITLE
Support for Foundry 11

### ISSUE THREAD

**Issue by choque88** [foundryvtt/pf2e#8021]
Please excuse me asking, but I wasn't able to find anything about it in the readme or in the issue tracker. Is there a roadmap for adding support for Foundry 11? I'd love to update my server to 11 Build 299 but the pf2e game system doesn't support the core version 11 (yet). I'll happily stay at 10 for now, but it would be nice to know when the support for core version 11 is planned to be added.

Thanks!

**Comment by TMunsie** [comment]
As we have stated on the livestream, in the patch notes, on discord, on the pathfinder 2e subreddit, and elsewhere, we are not upgrading the system until we’ll after PaizoCon. Likely the first or second week of June we will release a beta. 

We are all volunteers. Please give it time. This may seem terse but having to answer this question in every possible place dozens of times in 24 hours is getting more than frustrating.

**Comment by imgurbot12** [comment]
Had the same question. Would be nice if the information could be included in the README or maybe on the foundry website page. Good to know thanks.
