### ISSUE TITLE
Feature Request: add a actor Hardness selector for RE

### ISSUE THREAD

**Issue by Gieff** [foundryvtt/pf2e#8025]
Issue: Creatures with construct armor like, animated armor, animated statue, etc.when critted or at half hp have a reduced ac and hardness is removed. The ac is already automated and hardness was a non issue till the last update.

With the implementation of hardness in the IWR in v4.12, I think is needed a way to automate the removal of the hardness value witihn the RE adding a selector for the actor's hardness.

**Comment by Gieff** [comment]
Sorry to bother, I did a little more research trying to make it work and found an old issue https://github.com/foundryvtt/pf2e/issues/5964 that is the same, and using AE-like is not working (or at least, I can't make it work).

That time you closed and then reopened the issue because while discussing on discord said *"We can do some deferred processing of ae-likes in the beforeDerived phase"* (I have no idea what is the meaning, maybe it can help)

**Comment by stwlam** [comment]
For the purpose of hardness, you can send the ae-like all the way to the `afterDerived` phase.
