### ISSUE TITLE
Flat footed from flanking and prone being stacked

### ISSUE THREAD

**Issue by erikbuhler** [foundryvtt/pf2e#8038]
An enemy who is both prone and flanked has flat-footed counted twice for a total of -4AC.

[Image from chat card](https://cdn.discordapp.com/attachments/880969253765935174/1112055874098302996/double_flat_footed.png)

**Comment by In3luki** [comment]
I can't reproduce this with two players flanking a prone Morlock Engineer.

**Comment by stwlam** [comment]
Fixed in 4.12.3
