### ISSUE TITLE
Tallow Bomb doesn't display damage button.

### ISSUE THREAD

**Issue by MarsMage** [foundryvtt/pf2e#8054]
An attack with a [Tallow Bomb](https://2e.aonprd.com/Equipment.aspx?ID=1501) just results in a hit/miss post, with no way to display the persistent damage or splash.
![image](https://github.com/foundryvtt/pf2e/assets/42742105/8d5a4429-c594-45ab-bf08-59dac93c2478)

Based on a discord conversation, it sounds like the issue is the bomb having zero base damage.
![image](https://github.com/foundryvtt/pf2e/assets/42742105/8c84c99c-ebf1-43f7-8d8a-3c0ec1485aff)

I'm able to replicate the behavior on other bombs by setting the base damage to zero
![image](https://github.com/foundryvtt/pf2e/assets/42742105/a63a2b3c-5024-48bb-a808-50d02c57dd5a)

Testing Environment:
![image](https://github.com/foundryvtt/pf2e/assets/42742105/a86f9225-679c-499e-8458-136dc247b124)

**Comment by simonward** [comment]
I believe this is fixed by recent changes.
