### ISSUE TITLE
Satchel, Sheath and Belt Pouch

### ISSUE THREAD

**Issue by moonlitfields** [foundryvtt/pf2e#8074]
Cant tell if they were removed in the latest version- but now the compendium no longer contains these items and most likely more that I am unaware of. Was this all  errata'd out? And would there be a way to add it back in?
![Missing](https://github.com/foundryvtt/pf2e/assets/135179026/00bdec98-1137-44c2-8857-fe8876599fd2)

**Comment by TMunsie** [comment]
It was removed in the very first errata of the CRB. We left it in for legacy reasons but finally made the decision to remove them as they no longer serve any function. You can manually recreate them if you like as custom items.

**Comment by moonlitfields** [comment]
Okay! Completely fine! Im just happy to know it wasnt me breaking everything I touch lmao

**Comment by moonlitfields** [comment]
Oh question - did you remove the picture emblems for them- or are they still in the files somewhere. So i can reuse them if they are there. New to messing with foundry sorry
