### ISSUE TITLE
agorron guard and tenebric giant errors

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#8103]
the agorron guards have in their claw dmg "3d+18", should be "3d**6**+18"
tenebric giants should have no cloying shadows on their rock strike as that's for melee only; they should also have +2 greater striking scythes, and perhaps (though this isn't stated in the statblock) some rocks, so they can use their rock strike?
both of these creatures are from blood lords 5 btw, for reference

**Comment by simonward** [comment]
The Cloying Shadows ability is specifically called out for the rock attack.
