### ISSUE TITLE
Feature Request: Choice Set for dragon barbarians Dragon Breath

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#8107]
Currently if a dragon bar chooses a dragon breathe their damage is untyped even tho the damage is supposed to be of the type they choose, because of the iwr system it fails to interact with damage reduction or increases.

**Comment by stwlam** [comment]
It's an inline link, so a choice set won't do anything. You can always edit the description to set the damage type.
