### ISSUE TITLE
Token Prototype Shenanigans

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#8145]
No clue how to name this issue.
---

When you make a new actor and give it a new portrait image, but no token image, when placed on the scene it uses the portrait image instead of the default hooded SVG. **However**, that portrait image path is not reflected in the prototype token data, causing inconsistencies when looking at the token data.

This was replicated without modules, on latest version at the time (PF2e 4.12.9).

https://github.com/foundryvtt/pf2e/assets/32039708/b8f1005a-6577-4781-9db9-d2288127c0b9

In comparison, when doing the exact same set of changes in 5e, the prototype token image is changed.

**Comment by stwlam** [comment]
This is so that the token image changes along with the actor image until explicitly set.

**Comment by MrVauxs** [comment]
> This is so that the token image changes along with the actor image until explicitly set.

I get that, 5e does the same, but it's not changed in the data, causing errors in modules!
