### ISSUE TITLE
Show Non-Weapon Items with Strike Rules in Strike Actions

### ISSUE THREAD

**Issue by Larkinabout** [foundryvtt/pf2e#8147]
When non-weapon items with a Strike rule element are equipped, the strike shows up on the Actions tab of the character sheet. Unequipping the item, either by clicking 'Sheathe' or 'Drop' on the strike or via the Inventory tab, causes the strike to disappear from the Actions tab.

It would be useful to allow non-weapon items with a Strike rule element to work like weapon items where clicking 'Sheathe' or 'Drop' does not remove the strike from the list and allows for the item to be drawn or picked up from the Actions tab.

**Comment by stwlam** [comment]
You can give any rule element on a physical item a property of `"requiresEquipped": false` (and, if necessary, `"requiresInvestment": false`) to have them always available.
