### ISSUE TITLE
Add Items, Background and Spell from the Comic: Wake the Dead 

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#8197]
Maybe this is already planned for after V5 comes along, but nevertheless it might be easily overlooked.

Background: Awful Scab
Spell: Cyclone Rondo

Items:
Nexian Sealing Blade
Nexian Sealing Blade (Greater)
Rattling Bolt
Rattling Bolt (Greater)
Silver Orb
Silver Orb (Greater)
Silver Orb (Lesser)

Link to Archives of Nethys:
https://2e.aonprd.com/Sources.aspx?ID=201

**Comment by TMunsie** [comment]
We’ll have to see if a member of the development team has a copy of it.
