### ISSUE TITLE
Feature Request: Setting to make token image remain visible at any elevation

### ISSUE THREAD

**Issue by GorgoPrimus** [foundryvtt/pf2e#8256]
Right now if you have a scene partially under water and put a fish at -10 to show how deep it is the fish’s token will disappear and ‘go under the floor’, looking bad (no image) and making it harder for players to target it. Could there be an option to make it act like tokens do at positive elevations, ie. always remain visible?

**Comment by TMunsie** [comment]
This is a core foundry behaviour. The system doesn’t do anything here.

you’ll want to request this on the foundry repository or commission a module.
