### ISSUE TITLE
Error on attempting to open loot actors from certain module compendia

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#8281]
see: https://github.com/Drental/shopping-experience/issues/4
![](https://i.imgur.com/xQ9FPNw.png)
This, I think, counts as a system bug? It's not *all* loot actors, all from this module (and copies made from those base actors in other compendia) that generate this error.

**Comment by stwlam** [comment]
The module isn't listed anymore, so it isn't feasible to troubleshoot until the author updates it.
