### ISSUE TITLE
Macro XP does not work well with bigger groups and Extreme Encounters

### ISSUE THREAD

**Issue by AndeHofer** [foundryvtt/pf2e#8285]
Foundry V10 B291, PF2E 4.12.9

Used macro:
![image](https://github.com/foundryvtt/pf2e/assets/1547309/4890bd3f-854e-4358-8b95-5e34f43b7a5b)

For groups with 4 it works like expected, the max XP for an encounter is 160. But if the group is more then 4 and you want to adjust the encounter to give the same XP the max. XP is 128.

Example 1: group of 5 with level 5 VS lvl 8 (correct)
![image](https://github.com/foundryvtt/pf2e/assets/1547309/9a37f7e1-1045-4e79-b919-9e6f4804975d)

Example 2: VS lvl 9 (correct)
![image](https://github.com/foundryvtt/pf2e/assets/1547309/31407d55-83a5-4719-941b-22641eadf748)

Example 3: VS lvl 10 (wrong, XP should be 160)
![image](https://github.com/foundryvtt/pf2e/assets/1547309/5bc2e9fa-4db0-4543-bdf7-f91211fb94f2)

**Comment by stwlam** [comment]
There is no threat level for party level + 5, so it is bounded down to party level + 4. That is why you are seeing the same XP for both encounters.
