### ISSUE TITLE
Version 11.302 already released

### ISSUE THREAD

**Issue by Q-efx** [foundryvtt/pf2e#8302]
We just got an update to 11.302, modules set it already as required (very annoying)

Please check release version notes, if there is something useful. I don't think 302 is a hard requirement... Not everyone is able to update that fast..

**Comment by stwlam** [comment]
You are free to not update the system until you are ready.

**Comment by CarlosFdez** [comment]
It also is actually a hard requirement for the system, 302 fixed the compendium folders that prevented us foldering them up.
