### ISSUE TITLE
Undefined item.system.description.gm on migrated items causes errors in item sheet

### ISSUE THREAD

**Issue by Nightara** [foundryvtt/pf2e#8326]
item/sheet/base.ts:getData() doesn't check item.system.description.gm for existence, causing an undefined error on item.system.description.gm.trim() in line 95 when used with items imported from a previous version (4.X).

**Comment by stwlam** [comment]
It's in the template.json file. Do you have a reproduction example?

**Comment by Nightara** [comment]
I only saw the issue on data imported from 4.6.X (And potentially other versions, too), items created in 5.0.1 don't have the issue, so it will probably be hard to reproduce.

I tried to reproduce the error (After running Foundry with the workaround I suggested in #8327, then reverting to the unmodified pf2e module), but it doesn't seem to occur anymore.
I'm not very familiar with the code of this module, maybe running it on the modified version once (Which allowed everything to run without crashes) caused the system to rewrite the items?
