### ISSUE TITLE
Treat Wounds action has broken macro link in 5.0.1

### ISSUE THREAD

**Issue by Silvertower** [foundryvtt/pf2e#8373]
@UUID[Compendium.pf2e.pf2e-macros.Macro.Treat Wounds] is no longer valid and results in "undefined" broken macro link.

**Comment by stwlam** [comment]
Where is the malformed link, exactly? https://github.com/foundryvtt/pf2e/blob/master/packs/actions/treat-wounds.json

**Comment by Silvertower** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/8496016/18d78422-dae9-4cfa-ab53-1d3bcc49a229)

This happens on 3 different Foundry v11.302 instances.

**Comment by Silvertower** [comment]
Indeed, pasting in @UUID[Compendium.pf2e.pf2e-macros.Macro.Treat Wounds] to chat also shows a broken/undefined macro link.

**Comment by stwlam** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/106829671/4a6d81f7-fc0c-4c9d-8ae3-e5da8d4d00cf)

**Comment by Silvertower** [comment]
I can reproduce at will in a VM by fresh installing Foundry VTT 11.302 and then PF2E 5.0.1. I am uncertain how else to contribute with this issue.

**Comment by Silvertower** [comment]
Steps to reproduce:

1. Install Foundry VTT 11.302 on Windows or Linux, as normal.
2. Install PF2E 5.0.1 game system.
3. Create a new world using the PF2E game system.
4. Log in to the new world as Gamemaster.
5. Create a new Actor -> Player Character.
6. Open the new PC's character sheet, go to the Actions tab, go to the Exploration sub-tab.
7. Click Browse next to Actions and find the Treat Wounds activity, then drag it onto the PC's character sheet.
8. Click on the diamond to the left of Treat Wounds to link the ability to the chat window, or click on Edit for the action.
9. Note that the Treat Wounds macro link shows as "undefined" with a broken link symbol to the left.

**Comment by stwlam** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/106829671/dde1348e-57ee-4cd7-ae0e-a475cab41882)

My best guess is you have a world copy or one from another compendium.

**Comment by Silvertower** [comment]
I literally told you how to reproduce the issue with a fresh install in a VM.

**Comment by Silvertower** [comment]
In case anyone else finds this issue, the problem is with the compendium links. Linking by name no longer works.

For example, if you paste the following into the chat pane:

@UUID[Compendium.pf2e.pf2e-macros.Macro.Treat Wounds]
and
@UUID[Compendium.pf2e.actionspf2e.Item.Treat Wounds]

The macro links will be broken.

But pasting the raw macro with unique ID works:

@UUID[Compendium.pf2e.pf2e-macros.Macro.6duZj0Ygiqv712rq]
and
@UUID[Compendium.pf2e.action-macros.Macro.R03LRl2RBbsm6EcF]

The issue can be reproduced 100% of the time using the steps provided above.
