### ISSUE TITLE
Celestial Rage effect missing

### ISSUE THREAD

**Issue by AFigureOfBlue** [foundryvtt/pf2e#8378]
In the stat block of NPC Grace "The Rhino" Owano, the Celestial Rage ability is linked to the standard Rage effect. However, Grace's Celestial Rage grants rather different effects from a traditional rage, including weakness 10 to evil, +10 foot status bonus to speed. Either a separate effect should be created for this; or, since it's just for the NPC stat block as far as I'm aware, it could be turned into a checkbox on her stat block.

EDIT: Correction, right now it does seem that despite just being the usual "Effect: Rage", it is not adding the damage bonus which that effect normally does, which is good. It also is adding in the weakness to evil. Looks like the speed bonus is the only thing missing at the moment.

**Comment by stwlam** [comment]
It looks like the ability is just missing the speed bonus.
