### ISSUE TITLE
As in Life, So in Death - No Selections

### ISSUE THREAD

**Issue by EMPFingers** [foundryvtt/pf2e#8391]
Foundry V11 302
PF2E V5.0.1
All modules disabled.

When adding the As in Life, So in Death ancestry feat to a skeleton the box to select a common ancestry will be empty, closing it will result in an error and place the appropriate feats in their place.

![image](https://github.com/foundryvtt/pf2e/assets/70672700/4a792cd4-ce0a-4677-a32c-d0a34cf1436b)
![image](https://github.com/foundryvtt/pf2e/assets/70672700/210a2be1-831b-4f32-9665-add80f6e250e)
![image](https://github.com/foundryvtt/pf2e/assets/70672700/2afaca94-27d1-4e1e-9f4d-436e9e33d57c)

**Comment by stwlam** [comment]
Closed by https://github.com/foundryvtt/pf2e/pull/8325
