### ISSUE TITLE
Scenes do not load with invalid Token Paths

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#8397]
**ALL MODULES DISABLED?** `true`
**OS, Hosting, Browser (if applicable)**: Hosted on Ubuntu Linux, opened in Chrome 114.0.5735.134 
**Short Description of bug**: Attempting to Load a Scene with a broken token image results in the scene no longer loading.
**Simple steps to reproduce the bug**: Put a token with an invalid image path on any scene and refresh.
**Screenshots and/or console errors**:
![image](https://github.com/foundryvtt/pf2e/assets/32039708/7fe09c62-0140-4b19-b508-bf30e382f83f)

This only happens in V11 PF2e 5.0.2. Testing a D&D5e world, it works as usual.

**Comment by stwlam** [comment]
Please update this issue if you can narrow reproduction steps.
