### ISSUE TITLE
The Magic trait in attacks by Monsters or NPCs is not considered

### ISSUE THREAD

**Issue by Grampasso96** [foundryvtt/pf2e#8407]
When an NPC or Monster attacks with weapons or abilities that have the "Magic" trait on top and inflict physical damage, such as 2d8 Piercing damage, the damage that is applied via the program's automatic calculation is incorrect. In fact, if a player or other enemy that takes that damage has resistance to physical damage of 5 and which is double if they are from a non-magical source, the reduction applied is always 10; instead since the attack has the magic trait it should only be reduced by 5. This generates big problems in the calculation especially when PCs or other NPCs have these resistances and force you to manually calculate the damage each time as the program is not reliable.

**Comment by arthurtrumpet** [comment]
What version is this on?
Testing with 5.01 and 5.02 it works fine.
Versus a ghost commoner with resistance 5 physical (double vs non magical) it calculates correctly. First strike does -5 from a magical guisarme. Second does -10 from non-magical unarmed strike.
![image](https://github.com/foundryvtt/pf2e/assets/84977997/df2275e6-c8df-47dc-95db-4410d7a57feb)

**Comment by Grampasso96** [comment]
I'm in version 5.02, and if the damage comes from a player there's no problem, but the calculation error comes from the damage between Monster (or NPC) and monster. For example, if a bone devil attacks a Ghost Commoner with its bone shard, which deals only 2d8 piercing damage and has the magic trait, the Ghost Commoner reduces the damage by 10 instead of just 5.
![test](https://github.com/foundryvtt/pf2e/assets/136462967/16f885ac-95df-4cb0-8d83-effd452e940a)
