### ISSUE TITLE
NPC counteract from spells error

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#8422]
NPC counteracts currently use a roll as if they're PCs with trained prof in their spells, for example the vanyver uses cha of 5 + trained prof of 15 (they're lvl 13), and therefore rolls +20 with their dispel magic, but this is not at all their spell attack mod, which is +26 - every NPC with counteract spells, like dispel magic, or true seeing, does this same thing.

**Comment by JamzTheMan** [comment]
Running a Shadow Leydroth last night and it's Counteract check from it's innate Dispel Magic & Disjunction spells only roll the d20, adding no bonus (should be +28?)

Tested on PF2e 5.6.2 & 5.7.2 with no mods.

**Comment by DocSchlock** [comment]
This was resolved recently.

Counteracts for NPCs now use the correct values.
