### ISSUE TITLE
Colour Blindness accessibility

### ISSUE THREAD

**Issue by TVandevenne** [foundryvtt/pf2e#8432]
Is your feature request related to a problem? Please describe.

One of my players is colourblind and he can't see 75% of the character sheet.

Describe the solution you'd like

There are international standards for colours so user accessibility is high for them as well.
What the person told me is that it is mostly due to not having enough contrast between background and text.

I hope you can make an easy fix soon by fixing the colour palette or a "for now" fix by not having dark grey text on light grey backgrounds etc.

Many Thanks
Great tool otherwise
<img width="930" alt="Screenshot 2023-06-25 214426" src="https://github.com/foundryvtt/pf2e/assets/111162355/ba884e3a-00c1-42a3-8191-429456905dcb">

**Comment by stwlam** [comment]
We would need more information to help your player. Where is the contrast issue?

**Comment by TVandevenne** [comment]
Hi, the player has exchanged the Browser Edge for Chrome and apparently Chrome has a different way to show colour intensity and it is now useable for him.  No need to do extra work but perhaps make a note for colour blind users to favour Chrome over say edge.
