### ISSUE TITLE
Blood Vendetta rolls the wrong damage.

### ISSUE THREAD

**Issue by WaterpoloBlock** [foundryvtt/pf2e#8441]
Foundry VTT: 10
Build: 291
PF2e : 4.12.9

When rolling damage for Blood Vendetta, instead of rolling 2d6. It makes the output 2d6.

![Blood_Vendetta](https://github.com/foundryvtt/pf2e/assets/73310678/65276d49-8a9e-4a9f-9245-4727672e01fc)

**Comment by simonward** [comment]
That's because it inflicts 2d6 persistent bleed damage. The damage is rolled and applied at the end of each of the target's turns.

https://2e.aonprd.com/Spells.aspx?ID=675
