### ISSUE TITLE
Feature Request: "Make/Add-to Merchant" buttons to complement the "Make/Add-to Rolltable" buttons on the compendium browser

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#8447]
This seems like the kind of thing that would be handy - filter down to a list of 'all consumables between level 1 and 5 with the healing trait' and add it to an Apothecary merchant loot actor, for example. Not sure if you'd want to require an existing loot actor, which means you could go with a single button, or allow creation of a new one.

**Comment by TikaelSol** [comment]
Closing in favor of the consolidated issue #6588
