### ISSUE TITLE
bug: level calculation on armor is incorrect

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#8455]
![image](https://github.com/foundryvtt/pf2e/assets/62528192/d97595d0-1c9a-40b5-8a27-d04055210349)
if you see that this plate armor should be level 5 with the potency rune but it says level 2. ive had similar issues with other armors with potency runes.

**Comment by stwlam** [comment]
not a bug

**Comment by CarlosFdez** [comment]
Duplicate of #1845 and this is a feature request
