### ISSUE TITLE
Player client getting an error if any token is moved before game is unpaused

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#8457]
I have my PCs all on a scene, and one player client logged in with an owned character on the field. If I move any token (including theirs) as the GM while the game is still paused, the player client gets an error: 
![](https://i.imgur.com/dsIJ272.png) this goes away after I unpause for the first time and doesn't come back if I repause. Happens on both gridless and 5ft grid scenes. No (relevant) modules (libwrapper, socketlib, modulemanagement+, find the culprit, silence compatibility warnings).

**Comment by stwlam** [comment]
Unable to reproduce: check modules

**Comment by esheyw** [comment]
I can't make it happen reliably, going to close, I'll post if I get something solid.
