### ISSUE TITLE
(Bug/Request) Deity Creation lacks full implementation

### ISSUE THREAD

**Issue by MrZeyami** [foundryvtt/pf2e#8463]
While the Deity item conforms to the gods listed in the core rulebook, the gamemastery guide explicitly states that deities may have more than 4 domains, yet the form restricts choices to 4. Additionally, there is now published Paizo content which allows the Cleric player to choose a Lore skill, so the item should also support this functionality.

I'm further requesting that a homebrew variant I've seen floated around be added to pf2e for deities, namely replacing favored weapons with favored weapon groups.

**Comment by stwlam** [comment]
We can bump the number of domains one can set, but lore skills aren't yet in a state where including them is technically feasible.
