### ISSUE TITLE
Labels for Effects always split at : and using remaining half as label

### ISSUE THREAD

**Issue by BernhardPosselt** [foundryvtt/pf2e#8476]
I've got an effect named **Campfire Story: Critical Failure**. When applying it to an actor the effect shows up as **Critical Failure** only, making it hard to understand where it came from:
![Screenshot from 2023-06-28 16-54-34](https://github.com/foundryvtt/pf2e/assets/195053/f2e5ec5c-7777-43f7-a1ce-57488a3c4eae)

Prepending **Effect:** to turn it into **Effect: Campfire Story: Critical Failure** makes it render as expected.

Looks like this was done to remove a leading **Effect:** or **Spell Effect**: but it applies to everything containing a colon now. Maybe we could whitelist those 2 specific strings instead?

**Comment by stwlam** [comment]
Use parentheses!
