### ISSUE TITLE
[Question] Origin of Icons to keep style consistent

### ISSUE THREAD

**Issue by Leolele99** [foundryvtt/pf2e#8477]
This is less of a request or bug, but I noticed there is no clear documentation for the artstyle of the icons used, and also no source on the assets that might have been used during their creation. 

This makes it a lot harder to stay consistent within the style and add new icons for new content down the line.

I know the base foundry icons are mainly from an artist called REXARD, but some in this system seem to be unique while still fitting this style, or edits of the original icons used.

I'd like to propose either collection some used item sources here or creating a seperate section for it in the wiki.

**Comment by Leolele99** [comment]
I hope its okay to ping you @InfamousSky , I noticed a lot of the great Guns & Gears icons are by you. 
Do you remember where they are from?

**Comment by stwlam** [comment]
Guns & Gears icons are also by Rexard with the exception of combination weapon icons, which were commissioned.
