### ISSUE TITLE
Darkvision by rules not working.

### ISSUE THREAD

**Issue by drew585** [foundryvtt/pf2e#8483]
Greater darkvision and darkvision should have same visual effects on token.

![image](https://github.com/foundryvtt/pf2e/assets/138072408/89eaebcb-c3d9-4dac-9fd8-ba86dc3a8f2d)

Greater darkvision works properly, with grey vision beyond light source.
![image](https://github.com/foundryvtt/pf2e/assets/138072408/99aacd4d-6ab3-4eb1-af13-e6e519b5b3ba)

Darkvision does not change vision at all. No vision beyond light source.
![image](https://github.com/foundryvtt/pf2e/assets/138072408/a945605d-b317-4d06-ad03-21ac4723f1f8)

**Comment by stwlam** [comment]
Check the PC's senses

**Comment by drew585** [comment]
The two images are same PC with either darkvision or greater darkvision applied.
Below image is directly from the compendium. You can see that darkvision feat does not carry any sense rules.
![image](https://github.com/foundryvtt/pf2e/assets/138072408/338c18d1-b274-4129-bb03-3354027f060d)

**Comment by stwlam** [comment]
Thanks, we'll remove the rule element.

**Comment by drew585** [comment]
Maybe I did not communicate well. I believe that the darkvision feat needs the rule element added. Not that the greater darkvision needs it removed. Both should provide black and white vision in total darkness.
The only difference between the two in the PF2E rules is that greater darkvision is immune to magical darkness.

**Comment by stwlam** [comment]
It is intentional that the darkvision ancestry feature lacks a rule element.

**Comment by drew585** [comment]
Why would that be? The pathfinder game rules have that rules element. The intent of the compendium items is not to automate the PF2E rules?

**Comment by stwlam** [comment]
These particular items are no longer used for system automation. Ancestries, heritages, and feats all cover this without bringing in that pair.

**Comment by drew585** [comment]
You mention feats as the alternative but the two items I've shown are already feats.

Without this pair I see two options for myself to add darkvision to a player character that does not have it already.
1: disable vision by rule automation for the whole game just so I can set it manually in the token.
2: copy the darkvision feat from compendium to items list, then add the sense myself. Workable for me, but why should a user have to learn how to code a custom feat to add an ability from the core rulebook to a character?
Urg...... I've said my piece.


![image](https://github.com/foundryvtt/pf2e/assets/138072408/37d4c8d4-b112-4a0b-828e-bf9709694ad4)

**Comment by TMunsie** [comment]
> You mention feats as the alternative but the two items I've shown are already feats.
> 
> Without this pair I see two options for myself to add darkvision to a player character that does not have it already. 1: disable vision by rule automation for the whole game just so I can set it manually in the token. 2: copy the darkvision feat from compendium to items list, then add the sense myself. Workable for me, but why should a user have to learn how to code a custom feat to add an ability from the core rulebook to a character? Urg...... I've said my piece.
> 

If you want to do this manually just toggle the sense on in the characters senses on the front page of the character sheet. That is the present, expected workflow. You're welcome to do it differently if you want, but that's on you.

![image](https://github.com/foundryvtt/pf2e/assets/25963508/a696365e-b585-4916-9ce8-fd8c4a5d267f)

**Comment by drew585** [comment]
Well it seems that I goofed. I thought those were disabled when using vision by rule.
Sorry for wasting your time.
Thank you for helping me.
