### ISSUE TITLE
Dragged-template grid highlighting is unrepresentative of highlight when dropped

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#8499]
I'm not sure if this is feasible, given how circle templates are overloaded for bursts/emanations, but if there's some way to update the on-drag template preview to represent emanations when you're closer to the centre of a grid square than a vertex, that'd be a nice improvement over current: 
![](https://i.imgur.com/7YDOCh5.gif)

There's also some mild weirdness with cones:
![](https://i.imgur.com/LrSoGy5.gif)

**Comment by stwlam** [comment]
Emanations aren't implemented with the exception of auras (which don't use measured templates). I suggest voting for the V12 feature.
