### ISSUE TITLE
Psychopomp spirit touch should apply appropriate damage dice

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#8512]
not sure it's only PCs, but when rolling dmg with psychopomps vs undead PCs, it rolls negative dmg instead of positive; their spirit touch should do pos vs undead, neg vs living 
note: still on the latest V10 version atm

**Comment by stwlam** [comment]
There are quite a few psychopomp creatures. Are you referring to one in particular?

**Comment by dharkus5000** [comment]
no, it's the common feature called spirit touch that's i think shared by all of them?

**Comment by stwlam** [comment]
I checked the Catrina, and it's a roll note delivered via attack effect. So no problems there except there being better toys available now.

**Comment by stwlam** [comment]
Reframing this as a feature request to deal damage according to target

**Comment by dharkus5000** [comment]
just spotted that the shabti slayers have exactly the same problem as the same rule element, that doesn't work, is used - except theirs is only 1/2 of the rule elements - they do extra dmg to only undead

**Comment by simonward** [comment]
I tested Shabti Slayer against a Skeleton PC, and it behaves correctly. What sort of undead PC are you testing against? Can you reproduce with a fresh PC? Have you tried replacing the feature that's granting undead?

**Comment by dharkus5000** [comment]
just tried against the 4 PCs in my game from last night, lich, mummy, zombie & skeleton - skeleton was the only one it worked on and did positive dmg - might be due to all those having humanoid and undead traits?
just deleted the lich's dedication feat and then gave it back, nothing changed

**Comment by dharkus5000** [comment]
just tried the vanth warrior i orginally found the problem with, on the skeleton PC, it did positive dmg too

**Comment by simonward** [comment]
A mummy PC has "self:mode:living", which is incorrect. It's possible that modeOfBeing() is called too early, as traits appear to be empty.
@stwlam?

**Comment by DocSchlock** [comment]
I tested the mentioned creatures & PC types and this appears to have been resolved at some point. Undead PCs have the correct self:mode now and Spirit Touch is applying the correct damage types.
