### ISSUE TITLE
[Feature Request] Prevent removal of feats granted by other items

### ISSUE THREAD

**Issue by this-gavagai** [foundryvtt/pf2e#8535]
Many items (especially classes, heritages, etc.) grant feats defined internally by Rule Elements. At present, it is possible to delete these feats, which leaves a discrepancy in the character sheet.

For example, create a new actor with Human ancestry and Versatile Heritage. A Choice Set will offer a choice among 1st level general feats, which is then written to the rule element and granted. That feat will be automatically added, but it is then possible to delete it manually. At this point, the Heritage will say it is providing a General Feat, but no General Feat is provided and no indication that it is missing will be visible.

This is different from how skills granted by feats/features are handled. If a skill is marked trained by a class, trying to set it as untrained will fail with the warning "The selected proficiency is below proficiency set by features". This ensures more coherence in the character sheet, and it would be a nice feature to provide the same checks against feat deletion as well.

**Comment by TikaelSol** [comment]
This could be accomplished already by adding
```json
"onDeleteActions": {
    "grantee": "restrict"
  }
  ```
to the grants, however I am not in favor of doing this by default on existing grants. I think If you delete stuff from your sheet that is kind of on you. There are some times when people would want to delete the granted item for some homebrew purpose or just to have more control over the sheet.

**Comment by this-gavagai** [comment]
Good to know that there's already a rule element that can prevent this.

My argument for enforcing this by default is just that it's more consistent with a declarative programming paradigm. If Versatile Heritage grants the feat called Fleet, the data should expect Fleet to be there unless there's another declaration somewhere saying that it has been removed. 

For homebrew, a more consistent solution would be to edit the granting object, not to just delete the grant arbitrarily.
