### ISSUE TITLE
AdjustStrike -> Versatile traits do not work on Strikes added from REs

### ISSUE THREAD

**Issue by yoshisman8** [foundryvtt/pf2e#8539]
When you use the AdjustStrike RE to add the Versatile P/B/S/Fire/Etc trait to a strike that was added by a Strike Rule Element, you cannot actually change the damage type on said strike. The buttons to change damage types will be visible but wont activate. 

Video with issue attached:

https://github.com/foundryvtt/pf2e/assets/4214215/60a6684d-fe73-4350-bbd3-abad1f807370

**Comment by dellatorreadrian** [comment]
Hi!
  Could you comment here text you filled your RE with?
  I don't know if it was something already fixed between the creation of this issue and today, but I couldn't replicate your error right now.
