### ISSUE TITLE
Configure CONST.DEFAULT_TOKEN to no longer have the file dialog default to the wrong directory

### ISSUE THREAD

**Issue by Geekswordsman** [foundryvtt/pf2e#8541]
Foundry VTT v11.304
PF2E v5.1.0

When changing the image for an actor or item, the pf2e system will default Foundry's FileDialog to the systems/pf2e directory.  This unexpected behavior can cause users to upload to the system directory or require extra steps in order to properly assign an asset to the document.

The expected behavior is Foundry's default: when changing a default image, the default directory should be the last browsed directory (see foundry.js line 66348).

As Foundry only supports one default image (defined via CONST.DEFAULT_TOKEN), this is more complicated - please refer to open feature request on FoundryVTT at https://github.com/foundryvtt/foundryvtt/issues/9720

**Comment by stwlam** [comment]
`Actor.DEFAULT_ICON` and `Item.DEFAULT_ICON` are still in place from what I can tell. I believe `CONST.DEFAULT_TOKEN` is used only for tokens, and it isn't configurable (being in `CONST`).

**Comment by stwlam** [comment]
This issue is also present in dnd5e: reproduce by creating a new item and changing its icon.
