### ISSUE TITLE
Unable to add Archetype skill feat for Free Archetype Progression

### ISSUE THREAD

**Issue by ThunderousLeft** [foundryvtt/pf2e#8549]
Foundry v11 gives warning that feat type is invalid, even though feat is part of Dandy archetype progression

Archetype Feats in character sheet accepting class feats, but not archetype feats.

Dedication in question:
https://2e.aonprd.com/Feats.aspx?ID=1935

https://github.com/foundryvtt/pf2e/assets/16866924/68a75641-ae46-486b-ab91-cb8b84a6e0a4

**Comment by stwlam** [comment]
See https://github.com/foundryvtt/pf2e/wiki/The-CounterFAQ#i-am-using-the-free-archetype-variant-rule-and-am-trying-to-add-the-medic-archetypes-treat-condition-feat-to-an-archetype-feat-slot-why-cant-i-do-this-in-foundry
