### ISSUE TITLE
Feature request: Add the effect of the Gymnast (Swashbuckler)'s Exemplary Finisher please

### ISSUE THREAD

**Issue by Bomberman1988** [foundryvtt/pf2e#8577]
**[Exemplary Finisher (Gymnast)](https://2e.aonprd.com/Styles.aspx?ID=4):** If the foe is grabbed, restrained or prone, you gain a circumstance bonus to the damage roll equal to twice the number of weapon damage dice.

**Comment by simonward** [comment]
Fixed by https://github.com/foundryvtt/pf2e/pull/8211
