### ISSUE TITLE
Feature request: Add the effect of the feat Deadly Grace (Swashbuckler lv16) please

### ISSUE THREAD

**Issue by Bomberman1988** [foundryvtt/pf2e#8578]
[Deadly Grace:](https://2e.aonprd.com/Equipment.aspx?ID=1961) Your graceful attacks are especially powerful. When you score a critical hit with an [agile](https://2e.aonprd.com/Traits.aspx?ID=170) or [finesse](https://2e.aonprd.com/Traits.aspx?ID=179) melee weapon that has the [deadly](https://2e.aonprd.com/Traits.aspx?ID=174) trait, you double the number of dice from that trait. When you wield an agile or finesse melee weapon that doesn't have the deadly trait, it gains the deadly d8 trait instead.

**Comment by pedrogrullada** [comment]
Closed by #16552
