### ISSUE TITLE
Feature Request: an angle property on auras

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#8579]
It would limit the aura's application to an arc 'in front' of the token, like with token lights. 

I don't have any specific examples requiring it, this is just in the vein of 'it'd be neat if we could...'. I imagine it's notably more complicated than the current tests, but line of effect is already there, so maybe not?

**Comment by stwlam** [comment]
but that ain't no aura

**Comment by esheyw** [comment]
I can't think of a better way to conceive of 'apply effect in a cone' which is a not-unheard-of feature of monster design generally, in homebrew if not official paizo work. 'everyone lit by this holy bullseye lantern I'm carrying gets a bonus' sort of thing, or the core feature of certain non-ORCish creatures that get converted often.

**Comment by stwlam** [comment]
"apply effects from cones" seems a better way to express applying effects from cones than "allow auras to be shaped like pie slices"
