### ISSUE TITLE
Bracketed "diceNumber" resolving problem.

### ISSUE THREAD

**Issue by HibaniPaws** [foundryvtt/pf2e#8597]
Last update it was working just fine but a rule element like this no longer works on the current update (5.1.1)

"brackets": [
      {
        "start": 11,
        "value": {
          "diceNumber": "@item.badge.value * 2"
          "dieSize": "d8"
        },
        "end": 16
      }

**Comment by stwlam** [comment]
Is this found on a compendium item?
