### ISSUE TITLE
Broken Link/Missing Spell Effect: Nudge Fate

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#8628]
![Nudge Fate](https://github.com/foundryvtt/pf2e/assets/134313750/24cc335f-88d5-4230-a8a4-c7501d12af88)

One of my Players created a Witch and noticed that the Spell Nudge Fate has a Broken or Missing Link for the Spell Effect. I testet it in my local foundry without any modules and there was no Spell Effect either. Its nowhere in any Compedium Folder, so i guess it got lost or was never created?

**Comment by stwlam** [comment]
Closing as module issue

**Comment by Vendergast** [comment]
Ok, didnt connect it to a modul. Thanks anyway :)

**Comment by stwlam** [comment]
@Vendergast This will specifically be a localization module with an out-of-date spell description.
