### ISSUE TITLE
bug: arcane cascade isnt adding damage values or showing in chat card for starlit span magus.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/pf2e#8629]
arcane cascade isnt showing damage in the rolls with the effect on. 

![image](https://github.com/foundryvtt/pf2e/assets/62528192/823f1d79-015b-4308-b631-4224705c4d3d)

**Comment by ThingsCouldGetDicey** [comment]
this was tested with no modules.

**Comment by In3luki** [comment]
The desciption of Arcane Cascade states that it only applies to melee strikes.

**Comment by ThingsCouldGetDicey** [comment]
> The desciption of Arcane Cascade states that it only applies to melee strikes.

if thats the case then it should be modified for starlit span magus

**Comment by LebombJames** [comment]
Modified to do what? This appears to work as intended

**Comment by ThingsCouldGetDicey** [comment]
> Modified to do what? This appears to work as intended

realised that this wasnt a bug by as intended its just so odd that you gain a class feature that you cant use on something you picked. will close.
