### ISSUE TITLE
Brightshade does not have a use button

### ISSUE THREAD

**Issue by UristMcClaws** [foundryvtt/pf2e#8632]
When sending the item to chat, there is no use button unlike the rest of the poisons. It appears it's because it is set to have 0 charges.
<img width="218" alt="image" src="https://github.com/foundryvtt/pf2e/assets/19419208/aa2a3a54-4873-4317-bf44-16a96eb9a52c">

**Comment by simonward** [comment]
Fixed by https://github.com/foundryvtt/pf2e/pull/8634
