### ISSUE TITLE
PF2e doesnt account for proficiency in advanced weapons when treated as martial weapons via Dwarven Weapon Familiarity

### ISSUE THREAD

**Issue by ThunderousLeft** [foundryvtt/pf2e#8656]
Dwarven Weapon Familiarity should allow my dwarf to treat Advanced Dwarven Weapons as Martial Dwarven Weapons. I have proficiency in Martial Dwarven Weapons. Yet, when using a Dwarven War Axe, a normally Advanced Dwarven Weapon, PF2e does not treat my character as proficient. This has just begun happening after porting from v10 to v11, and I have replicated it on a fresh character sheet as seen here:

https://github.com/foundryvtt/pf2e/assets/16866924/74ec441f-92f2-4ac3-95ba-8ad1b80e5632

Foundry: v11.305
PF2e: v5.1.2

Modules enabled:
Pathfinder Token Pack: Bestiaries
Module Management+

**Comment by ThunderousLeft** [comment]
Relevant REs seem to be all intact 
![image](https://github.com/foundryvtt/pf2e/assets/16866924/da097318-c580-45e3-af68-312b2be7b5b4)

**Comment by stwlam** [comment]
How did you gain proficiency in martial weapons?

**Comment by stwlam** [comment]
Everything looks in order here: your character is trained in martial dwarven weapons because they're treated as simple weapons. But an advanced dwarven weapon is treated as a martial weapon, with which the character is untrained.
