### ISSUE TITLE
Fix Request: Battle Oracle's Fast Healing isn't working

### ISSUE THREAD

**Issue by Bomberman1988** [foundryvtt/pf2e#8671]

**Comment by Bomberman1988** [comment]
![1](https://github.com/foundryvtt/pf2e/assets/103781301/9499e32a-5bbb-4dca-98e5-ae94b7580764)
![2](https://github.com/foundryvtt/pf2e/assets/103781301/dde2c588-a624-4d14-9301-7a1a4505c5db)
![3](https://github.com/foundryvtt/pf2e/assets/103781301/b9f9e7cb-7412-42a3-83cc-e180d9030d22)

Showing pictures from rounds 1 to 3

**Comment by stwlam** [comment]
Does the effect have any fast healing on it?
