### ISSUE TITLE
Spell Effect: Light doesn't work correctly for tokens of different sizes

### ISSUE THREAD

**Issue by Omoz** [foundryvtt/pf2e#8735]
Ran into an issue with `Spell Effect: Light` when playing a session yesterday. We worked around it for the session, but I think I found what's causing it. Tokens seem to only be able to see light effects from tokens the same size scale or larger than itself. I was able to test this after the session with this example.

The token on the left is medium sized creature with a scale of 1. The token on the right is a small creature with a scale of 0.8 with `Spell Effect: Light` applied.
![image](https://github.com/foundryvtt/pf2e/assets/44378972/5d8a84c2-b43c-4230-967d-70243eed7efb)

From the small token's perspective, it sees the light as expected.
![image](https://github.com/foundryvtt/pf2e/assets/44378972/30ca6b3f-7d3f-426c-a488-74a07ee64350)

From the medium token's perspective, it doesn't.
![image](https://github.com/foundryvtt/pf2e/assets/44378972/9ad0066c-f170-49ca-b451-65aa5f8d9bfc)

If `Spell Effect: Light` is applied to the medium token, it works as expected for the small token with the default scale.
![image](https://github.com/foundryvtt/pf2e/assets/44378972/cd7150a0-2d9f-4337-a4c8-901fdfacf7c8)

And if I manually override the scale of the small token to be 1 with `Spell Effect: Light` applied, the medium token can see the light.
![image](https://github.com/foundryvtt/pf2e/assets/44378972/c2a45006-0075-4ab5-a3d8-e9bffec09b6e)

I've also tried this with `Torch is lit` and the same issue applies.

**Comment by stwlam** [comment]
Like so?
![image](https://github.com/foundryvtt/pf2e/assets/106829671/3188d88f-a9b8-4f91-a92c-c32661c42cd1)

**Comment by Omoz** [comment]
I don't seem to get that.
![image](https://github.com/foundryvtt/pf2e/assets/44378972/52df9785-70d4-4735-b54e-8c190c7b8804)

Is it possible this could be affected by other modules? I'm going to try toggling off some modules to see if that affects things as I have modules like Levels installed that could affect lighting.

**Comment by Omoz** [comment]
Nevermind. It's Levels not playing nice. I toggled it off and that works now.
![image](https://github.com/foundryvtt/pf2e/assets/44378972/46962ea2-6773-4dfe-9106-ee6cf4c32211)
