### ISSUE TITLE
Feature Request: Add hotkey for World Clock

### ISSUE THREAD

**Issue by 117Dios** [foundryvtt/pf2e#8746]
Just a small QoL change in order to make it easier to edit in-game time and remove some "dependency" from modules. Maybe something like:

- Hotkey to toggle World Clock
- Hotkey to just open it
- Hotkey to just close it
- Maybe make it resizable, with a smaller default size

**Comment by TMunsie** [comment]
Request this of the PF2e keybind module. Essentially all the optional keybinds live there.
