### ISSUE TITLE
Cosmic Form - automation is not working

### ISSUE THREAD

**Issue by Crineryr** [foundryvtt/pf2e#8751]
Hey!

My player used Cosmic Form (Moon) for the first time and we've noticed that automation is not working properly. When tested on Sun it appears that something is wrong as well. Could you please check it?

**Comment by simonward** [comment]
Can you be more specific about what issues you’re seeing?

**Comment by Crineryr** [comment]
Sorry, could have been more precise. Most of the functions of the Effect is not working, but to describe them by the spell description:

- AC is not being adjusted
- Attacks are not auto granted
- Athletics is not adjusted to mod +25
- Speed types are not granted

From what I can see, this stuff works:
- Temp HP
- Darkvision

Interestingly enough, a lot of text is already written in, but for some reason it doesn't work. Here's Moon form example (see screen)
![image](https://github.com/foundryvtt/pf2e/assets/123328116/d6201a60-eff9-4a39-9ef5-511e56793d38)
