### ISSUE TITLE
Darkvision makes lights with "Adaptive Luminance" monochrome (sometimes).

### ISSUE THREAD

**Issue by eivindhusby** [foundryvtt/pf2e#8770]
https://github.com/foundryvtt/pf2e/assets/85963179/4cab2027-9283-4542-9ffb-fdcacbaec00b
Noticed this a few weeks back. Might have been right after I updated to Foundry v11, but I can remember for certain.
All the verification testing was done in a clean test-world with no modules enabled, and Foundry and Pf2e up to date as of today.
All the issues are on the player side and not on the GM side.
Foundry 305v11
Pf2e 5.1.2
I use Foundry for IRL play, so all tokens are owned by the same user.
For the test, I have 4 tokens. 2 with darkvision and two without.
At first, everything looks right. I select a darkvision token, and everything but the areas with light goes monocrhome.
I select another darkvision token and nothing changes. But if I then follow up with either selecting the first darkvision token, or move the second one, the areas with light also goes monochrome.
And it stays that way until I repeat the exact same procedure with two of the non-darkvision tokens.
If I turn off vision sharing, it doesn't stay locked in monochrome if any token is selected (even a darkvision one), but instead the same vision bug happens if no tokens are selected.
It does not seem to apply if the lights are set to anything other than "Adaptive Luminance", but most lights I have on most maps are already set to that, as it's the default.
While the circumstances sounds very specific, it triggers multiple times per session for me, and I've seen two or three others noticing it on the Pf2e discord just today.

**Comment by stwlam** [comment]
Upstream issue, sorry.
