### ISSUE TITLE
Feature Request: search filters within the prepared spellbook

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#8823]
For higher level casting it would be nice if we had a filter by level and a search at the top as the list gets longer and longer.

i know the browser compendium exists but as you get more lvels and the spell list increases this can help to shorten prep.

**Comment by LewisIsWorking** [comment]
Can I up vote this besides just heart reacting it?

Great idea!

**Comment by LewisIsWorking** [comment]
Can I up vote this besides just heart reacting it?

Great idea!

**Comment by simonward** [comment]
Search was added by https://github.com/foundryvtt/pf2e/pull/10729

**Comment by stwlam** [comment]
That's just to the preparation dialog

**Comment by CarlosFdez** [comment]
Given the title mentions the prepared spellbook, I think this was asking about the prepared dialog!

**Comment by stwlam** [comment]
But that's not prepared :\
