### ISSUE TITLE
Rage effect only adding temp HP

### ISSUE THREAD

**Issue by ltsjoe** [foundryvtt/pf2e#8870]
So I'm finding an interesting issue with the Rage: Effect.
While it does give the Barbarian the 5 temp HP, it does not seem to decrease his AC by 1, nor add the additional damage.
On top of that, he took the Dragon Instinct (Green Dragon) class feat and it is not altering rage to cause acid damage either.
Thoughts?

Foundry VTT v11 build 306
Pathfinder 2e Module 5.2.1

![image](https://github.com/foundryvtt/pf2e/assets/18501940/f454db7b-a41c-409b-8803-e85a10ab8cd2)

Attack Rolls while Rage is enabled
![image](https://github.com/foundryvtt/pf2e/assets/18501940/5cf307f8-0657-4e07-9277-6d90cccf60ab)
![image](https://github.com/foundryvtt/pf2e/assets/18501940/5702afa7-0034-49df-bbcb-a7786b386a05)

Sheet without Rage enabled
![image](https://github.com/foundryvtt/pf2e/assets/18501940/65d6bac0-fe16-4b57-9c13-44c38251b5dc)

Sheet while Rage is enabled
![image](https://github.com/foundryvtt/pf2e/assets/18501940/cd3ae401-eea2-4345-9bb3-d420009ad11d)

**Comment by TikaelSol** [comment]
Was this character imported from Pathbuilder by chance? Try setting them to level 0 then back up.

**Comment by ltsjoe** [comment]
> Was this character imported from Pathbuilder by chance? Try setting them to level 0 then back up.

It was not, but I'll give that a shot.
