### ISSUE TITLE
Blood Pear Tree from SF AP incorrect

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#8880]
the Blood-Pear Tree is a variant of the original from BotD, that's in the stolen fate AP bk 2, in BotD the rotten fruit attack does poison splash, but in SF, it's changed to a bloody pear that does bleed splash, but this change isn't evident in the version in foundry - not sure if persistent as splash is even possible? but that's what it says! tried changing the dmg type to bleed and it forces the category of dmg to persistent, so seems it's not currently possible to have it be both?

**Comment by dharkus5000** [comment]
also the SF version doesn't have the blight ability, so that shouldn't be there either

**Comment by TikaelSol** [comment]
When I entered it we asked Paizo for clarification. The system can't do bleed splash damage and it makes no sense for the creature, so I assumed it was a typo and corrected it. Since the system can't handle the other way around we'll keep assuming that.
