### ISSUE TITLE
[Bug] - Advanced Dogma

### ISSUE THREAD

**Issue by Crineryr** [foundryvtt/pf2e#8898]
Hey,
Advanced Dogma (Archetype Feat) does not have a choice set akin to basic dogma. It would be helpful to have a choices available :)

Thanks!

**Comment by JDCalvert** [comment]
#4477 would fix this, but it's very out of date. I'll look at updating it with the latest changes and we'll see if it can get merged.

**Comment by TikaelSol** [comment]
The new filter format required for v11 may end up more flexible, but it's still going to be a difficult problem.

As for this issue, it's a duplicate of #1956 so I'll close it.
