### ISSUE TITLE
Feature Request: a way to predicate on 'actor is holding any item with given trait'

### ISSUE THREAD

**Issue by esheyw** [foundryvtt/pf2e#8900]
This idea comes after a discord conversation where there was homebrew forceful automation using toggles, and we were trying to see if there was a way to only show the toggle if they were carrying a weapon with forceful, without just copying the rule to every new weapon. The title would be a solution, and it would also provide new options for organizing automation (I'm mostly thinking homebrew trait stuff, but maybe paizo stuff as well).

**Comment by stwlam** [comment]
The explosion of roll options would make this untenable, sorry.
