### ISSUE TITLE
Demolishing Rune needs special handling for its damage

### ISSUE THREAD

**Issue by Deathsworn** [foundryvtt/pf2e#8942]
The persistent damage on the Demolishing Rune is dealing 1d6 * 2 persistent Force instead of 1d12. 

V5.2.1

**Comment by stwlam** [comment]
This is a system limitation. Currently the only deviation of this kind from normal critical damage rules is from this comic, so there's not much compelling accommodation of it.

**Comment by TikaelSol** [comment]
This appears to be covered by CRB printing 3 errata. Doubling the dice is correct, and the item should change to reflect the proper way of handling critical persistent damage. I'd wager Paizo is not exactly chomping at the bit to errata a comic book, so we're unlikely to ever see an official word on it, but the same logic that went into fixing this issue on the wounding rune should apply here as well.

```Page 585: In the wounding rune, given that persistent damage doubles on a critical hit, changing the 1d6 to 1d12 instead of doubling would actually make it deal less damage on average. Thus, remove the part about changing to 1d12 damage on a critical hit. Instead, the wounding rune's bleed damage doubles as normal for persistent damage.```

https://paizo.com/pathfinder/faq
