### ISSUE TITLE
Bug: New auras trigger only after next canvas event

### ISSUE THREAD

**Issue by this-gavagai** [foundryvtt/pf2e#8948]
Under some circumstances, new auras added to actors will not trigger (apply effects to other nearby tokens) immediately upon arrival. Instead, they will trigger only after the next canvas "event", such as movement, reloading, etc. 

This bug has been tricky to isolate because it doesn't always appear for me on newly created scenes, but after the scene has been used for a while it has consistently begun to manifest this behavior. That suggests to me that the issue has something to do with how the auras are interacting with scene data, but I am not able to be more specific than that at this time.

A reddit thread has been created about the same issue: 
https://www.reddit.com/r/FoundryVTT/comments/1596cdo/pf2e_anyone_else_having_trouble_with_pf2e/

See video below for demonstration.
Circumstances: all modules except "Find the Culprit" off, scene is active, combat is active, map has square grid, no walls or other obstacles, alliances set correctly.

https://github.com/foundryvtt/pf2e/assets/9303694/dbd20509-f940-49ff-91ec-581e64b85b8e

**Comment by stwlam** [comment]
Keeping this open, but I'm not yet able to reproduce it

**Comment by this-gavagai** [comment]
Yeah, it's really bugging me that I can't pinpoint the issue. 

I have been able to reproduce it consistently on a new world that imports the Abomination Vaults maps now (Chrome on MacOS using localhost connection):

1) Create a new world and login as gamemaster
2) Activate Abomination Vaults module and activate scene "E - Arena" (some but not all of the other scenes manifest the same problem too)
3) Create two new characters, and under configuration set them to party.
4) Create a combat with the two new characters and a few enemy creatures.
5) Start combat. 
6) While in range and sight line of the other, add Aura: Protective Ward to one of the characters.

https://github.com/foundryvtt/pf2e/assets/9303694/a8793b2f-de85-40da-b7cb-0ab78db551fe

This may be an issue with these abomination vault scenes specifically, or it may be just a matter of scene size/complexity/features. My next step is to try testing on other similarly complex scenes.

**Comment by stwlam** [comment]
Nothing, sorry.
[Screencast from 07-27-2023 09:35:54 PM.webm](https://github.com/foundryvtt/pf2e/assets/106829671/4c9afb0c-46e2-49fb-86a7-6442c76371ca)

**Comment by beefor** [comment]
Have you tried applying the aura to a PC who already existed on the scene when the scene was loaded? I've been able to consistently reproduce this with PCs who start on the scene, but it doesn't seem to happen for actors who didn't start in the scene on load.

**Comment by this-gavagai** [comment]
> Have you tried applying the aura to a PC who already existed on the scene when the scene was loaded? I've been able to consistently reproduce this with PCs who start on the scene, but it doesn't seem to happen for actors who didn't start in the scene on load.

Hmm…interesting. I’m not able to reproduce that exactly, but load/reload dynamics are definitely part of the picture. Duplicating a scene then activating the duplicate seems to eliminate the problem for me, for example, but only until the scene is reloaded.

**Comment by orangepeelbeef** [comment]
I also ran into this bug with inspire courage. The bard casts it, nothing happens until someone moves in the scene and then the inspire courage gets applied to everyone. 

However i believe this functionality comes from PF2e workbench, so it is possible workbench is messing something up.  It is the same behavior as described in this ticket though.

**Comment by orangepeelbeef** [comment]
I was able to diff a broken scene with a duplicated working scene.  The only thing different is the broken scene has this in the templates section of the data, while the working scene has nothing in the templates section.

`  "templates": [
        {
            "_id": "jvZFCgEvE4i87O0o",
            "angle": 0,
            "borderColor": "#000000",
            "direction": 0,
            "distance": 60,
            "fillColor": "#050505",
            "flags": {
                "pf2e": {
                    "origin": {
                        "castLevel": 2,
                        "name": "Inspire Courage",
                        "slug": "inspire-courage",
                        "traits": [
                            "bard",
                            "cantrip",
                            "composition",
                            "emotion",
                            "mental",
                            "enchantment",
                            "occult"
                        ],
                        "type": "spell",
                        "uuid": "Actor.EVzGXyIRvjpEWya8.Item.KnRkpn0pceXFAzbl"
                    }
                }
            },
            "hidden": false,
            "t": "circle",
            "user": "FseH38o4k9ZD75gn",
            "width": null,
            "x": 3550,
            "y": 2250
        }
    ],`

**Comment by stevem-hd** [comment]
I am also having issues with inspire courage not applying.

Aura: Protective Ward works fine however

**Comment by this-gavagai** [comment]
Thanks for your efforts, @orangepeelbeef. It sounds like the issue isn't about serialized data structures but rather something that happens in memory. That makes sense, given how the issue is interacting with duplicating and reloading scenes, that makes sense.

**Comment by orangepeelbeef** [comment]
I have kept several scenes around that have the issue, i'm happy to test anything if there is something to test.

**Comment by this-gavagai** [comment]
I believe I've got a bit more information: the problem seems to occur when the token producing the aura represents an actor with *another* token existing in another scene. Consistently, it seems I'm able to fix the problem shown in the video above by deleting other tokens representing the actor located in other scenes.

**Comment by stwlam** [comment]
Closing as module issue; will reopen if reproduction steps are provided

**Comment by xdy** [comment]
I can reproduce the auras not propagating using only the system like this:

Setup:
Make a new world with one scene, one player user, two actors (one of which is owned by the player). Give the non-player actor 'Aura: Protective Ward'. Place both next to each other on the scene. The player actor is now affected. Unpause the game. Log in as the player user, move the token out of the area. The player is now unaffected. So far so good.

Reproduction:
As the player, move the player token back and forth so the player token is alternatingly in and out of the aura. Nothing happens.
As the GM, move the player token back and forth so the player token is alternatingly in and out of the aura. Nothing happens.
As the GM, move the nonplayer token back and forth so the player token is alternatingly in and out of the aura. Nothing happens.
Copy the actors into a new scene and perform the above reproduction actions. Nothing happens.

**Comment by this-gavagai** [comment]
It's definitely not a module issue, as I can reproduce it consistently in a brand-new world with no modules active.

I believe the core of the issue is what I posted in my last comment: having the same actor represented by a token in two different scenes.

Here is a video that starts from absolute scratch creating a new world, without modules, showing the bug. I have been able to reproduce this on all three computers I tested.

https://github.com/foundryvtt/pf2e/assets/9303694/4650dd4b-1ae6-4bc0-844b-4139cadc4410

Steps:
1) Create a new world using pf2e system
2) Enter world as Gamemaster
3) Create two actors
4) In configuration settings for each actor, set Alliance to "Party"
5) Create two new scenes
6) Place both actors as tokens in adjacent squares in Scene 1
7) Place both actors as tokens in adjacent squares in Scene 2
8) Activate Scene 2
9) Apply "Aura: Protective Ward" item to one token. See if the effect propagates to other token.
10) Activate Scene 1 and repeat applying "Aura: Protective Ward". See if effect propagates here too.

On all three systems I tested, the aura propagated correctly on one scene but only after a token movement on the other.

**Comment by TMunsie** [comment]
I had this a few times at GenCon using the workbench module. It also made me lose sync and I’d end up with multiple copies of the effect attached by the aura and over time I would get the no embeddedObject error and have to refresh to clear. Admittedly “modules” but decent to try and diagnose

**Comment by this-gavagai** [comment]
Thanks @TMunsie! I've been seeing similar embeddedObject errors but haven't been sure if they're related to the aura propagation issue or not.

**Comment by this-gavagai** [comment]
I believe I've identified the code relevant to this issue.

When an aura-bearing effect is added to a token, the `_onRelatedUpdate` method is called not just on the token in the active scene but also on all other tokens representing the same actor in other scenes:

**Comment by this-gavagai** [comment]
I believe I've identified the code relevant to this issue.

When an aura-bearing effect is added to a token, the _onRelatedUpdate method is called not just on the token in the active scene but also on all other tokens representing the same actor in other scenes:

https://github.com/foundryvtt/pf2e/blob/b2ddb137059a1d57307e04f59e12eb809ef07823/src/module/scene/token-document/document.ts#L419-L450

This creates a race condition in the denounced checkAuras method here:

https://github.com/foundryvtt/pf2e/blob/b2ddb137059a1d57307e04f59e12eb809ef07823/src/module/scene/helpers.ts#L8

The debounce method means that checkAuras will be called only once within the 100ms window. When an actors token is present in only one scene, this isn't a problem. But, when the actors token is present in multiple scenes, the checkAuras method will sometimes call only for a scene other than the active one. As a result, the auras don't propagate until the next action is taken on the scene.

**Comment by this-gavagai** [comment]
An effective fix here seems to be shifting the scene's focus check outside of the debounce wrapper.

In concrete terms, the token-document definition's `_onRelatedUpdate` method could be changed such that this bit:

https://github.com/foundryvtt/pf2e/blob/f6f301d0b3ffaef58bb2fde530a0ea93b91db924/src/module/scene/token-document/document.ts#L447-L449

Is changed to filter out scenes when not `isInFocus`.
```javascript
        if ((aurasChanged && this.scene?.isInFocus) || "width" in changes || "height" in changes) {
            this.scene?.checkAuras?.();
        }

```
This should fix the problem described here, but I don't understand enough about update lifecycles to know if there are any unintended consequences to this. Happy to make a pull request if this approach makes sense, though.

**Comment by this-gavagai** [comment]
Thanks so much @stwlam! I've tested the code you've written and it does the trick. Putting the isInFocus check where you did makes more semantic sense too.

Digging in here made me appreciate how vast this code base is. We all greatly appreciate what you and the other maintainers do.
