### ISSUE TITLE
Bug: Advancing time with an effect with duration on a token causes all items in the sidebar to flash

### ISSUE THREAD

**Issue by maplealmond** [foundryvtt/pf2e#8950]
How to reproduce

* Using PF2e v5.2.3 and FVTT V11 build 306
* Using module Beginner Box (Not required, but convenient to reproduce)
* Have one PC token on the field (one of the example PCs will work)
* Apply an effect from the items tab with a duration (Elemental Aid will work)
* With the Effects folder open, advance system time by any amount (1 round should be fine)

Observed:  All the items in the items folder sidebar will briefly flicker, appearing to not render for a frame or two and then render again.

Expected:  The items should not visibly change.

Impact:  Minor, but annoying if using something like Simple Calendar and real time progress which is updating the PF2e system clock in 1 second increments.

**Comment by stwlam** [comment]
Limitation of upstream rendering workflows
