### ISSUE TITLE
Feature Request: add a way for MeasuredTemplatePF2e to use different collision types

### ISSUE THREAD

**Issue by reonZ** [foundryvtt/pf2e#8969]
Everything is there in the code, it would just require an extra property to specify which collision type to use and pass it to the `highlightGrid` helper in `MeasuredTemplatePF2e#highlightGrid`.

While this is not directly used in the system, it could allow third parties to use it.

**Comment by stwlam** [comment]
This is more appropriate as an upstream feature request.
