### ISSUE TITLE
Bug: pressing enter on HP value on pc sheet triggers damage value on last open card.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#8971]
could it be possible to prevent a link between the chat card upon pressing enter in the hp field.

**Comment by stwlam** [comment]
Is this on a particular sheet?

**Comment by GuitarGuyNick** [comment]
> Is this on a particular sheet?

pc actor sheet havnt tested with creatures.

**Comment by stwlam** [comment]
Check modules

**Comment by GuitarGuyNick** [comment]
if you have a spell open it will roll the last spell
