### ISSUE TITLE
Champion's Resistance doesn't apply during damage application

### ISSUE THREAD

**Issue by TheGnome1** [foundryvtt/pf2e#9015]
IWR automation for a resistance rule element value with 
@item.origin.level 
is not processed correctly.
The value is represented on the actor sheet but IWR automation does not reduce by any amount. 
(specific instance is Champion's Resistance) RE {"key":"Resistance","type":"all-damage","value":"@item.origin.level+2"}

**Comment by stwlam** [comment]
appears to work (from a level-5 champion):
![image](https://github.com/foundryvtt/pf2e/assets/106829671/60d57f5e-c4ab-47fe-9e5f-320779767788)

**Comment by TheGnome1** [comment]
It puts the effect on the character sheet yes... but the resistance does
not work when you actually try to apply damage to the actor
