### ISSUE TITLE
KM - NPC speartooth separate entry?

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#9023]
there's a creature called "Speartooth" in KM pg 104 - in foundry i found the same creature (mis?)named "Black Smilodon", no creature by speartooth and it appears to be the same creature, not sure what happened here, but it just appears to have the wrong name? searched the PDF and now found that paizo has done the weird thing they do where they reuse the statblock of a unique creature and have lots of em at once later on - maybe the creature should be duplicated in foundry, with both names existing? otherwise unless someone thinks to check if it's used later (not happened upto this point (lvl 11) before that), they're gonna not find speartooth?

**Comment by dharkus5000** [comment]
also Black Smilodon statblock should def not have unique, cause you see 4 or 8 together later on, not sure what you wanna do with that!

**Comment by TikaelSol** [comment]
If the stats are not different we don't duplicate them, but we should fix the rarity for that one.
