### ISSUE TITLE
Tremorsense can perceive Npcs with toggled off visibility state

### ISSUE THREAD

**Issue by Thomas-Zan** [foundryvtt/pf2e#9032]
Hello, I have found something that I believe to be a bug. 
Having a pc with a tremorsense (either precise of imprecise) makes npcs visible that should not be perceivable by the party.

I do assume that toggling an NPCs visibility state feature is to make them not exist in the world for session prep.

Foundry Version: V11 Stable
Build 306
Pf2 system version 5.2.3
Active modules 0

Steps to reproduce:
- Create any PC with a tremorsense (In my example I use a Android Mage Automaton Magus with the Magical Experiment Background which gives him an imprecise sense Tremorsense 30ft)
- Use any NPC
- Drag both on Scene
- Toggle off NPC visibility (Toggle visibility state on right-click menu)
- PC can still see NPC

![tremor-sense1](https://github.com/foundryvtt/pf2e/assets/6171247/6edb873c-cb29-4c13-a86f-0ec4cc46a8a7)
![tremor-sense2](https://github.com/foundryvtt/pf2e/assets/6171247/fceb5a61-b4f7-41fe-b4df-4ed8cc525adf)

**Comment by stwlam** [comment]
This would be a core Foundry bug if anything. We use the stock tremorsense detection mode.

**Comment by stwlam** [comment]
Try testing from a player's user. We make GM-hidden tokens hidden even to GMs with basic vision, but by Foundry's reckoning a GM should be able to see GM-hidden tokens so long as the token itself is configured to see anything at all.
