### ISSUE TITLE
Feature Suggestion: Relic Gifts Compendium

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#9064]
I know Relics arent something on the radar at the moment, but some Relic Gifts Powers (like Deadly Spark) are already in the System.
At the moment they are located in the Adventure Specific Actions with no relation to any Adventure at all. 
For better understanding my Suggestion would be to Create an Extra Compendium for the RelicGifts to group them.

Maybe there is a good reason for not doing that. This is just a suggestion and can easily be overthrown or ignored :D

**Comment by TikaelSol** [comment]
These are in the adventure specific actions for a reason, namely that they are in fact used by an adventure. When we handle relics properly we will migrate links to where they can all live. Until then that adventure, being something with premium content available for it, needed some level of system supported automation.

**Comment by Vendergast** [comment]
Alright thanks for the Info :)
