### ISSUE TITLE
Feature Request: add a way for minions summoned creatures to be traceable to the source 

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#9088]
What id like to see if any creature is summoned from a spell and becomes a minion. a way of tracing that back to the person who casted the spell. so that if there is alot of creatures doing the same thing you can link back to each caster. and have an indication of when these summoned creatures/minions are supposed to go on the combat tracker.

**Comment by stwlam** [comment]
Traceable implies there being something to trace
