### ISSUE TITLE
[bug] Gate's threshold isn't working

### ISSUE THREAD

**Issue by Maelorn09** [foundryvtt/pf2e#9101]
Hi, when leveling up a kineticist I can't drop any feats into the Gate Threshold "Expand Portal" option.
![image](https://github.com/foundryvtt/pf2e/assets/114569560/9e600fa3-7e14-4e34-b300-f7b57e6bf22b)

**Comment by shemetz** [comment]
Also true for the initial two impulse feats granted by the Kinetic Gate class feature at first level (none are granted, but no popup appears either).

**Comment by nsurette** [comment]
If you click close on that window it does open a window where you can pick which junction you use but yeah. It still needs work.
