### ISSUE TITLE
Data entry errors from Rage of elements (several)

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#9103]
**Solar Detonation** - missing the word "Vitality" from the 2nd damage embedded in the description.

![image](https://github.com/foundryvtt/pf2e/assets/6516621/9afe800c-e0c7-4e9e-b23a-6773b3595621)

**Channel Elements** - typo in description, "fl w".  Also, "10-foot emanation" should not be an embedded template;  it's an aura that emanates from your token and moves with it.

![image](https://github.com/foundryvtt/pf2e/assets/6516621/ffc5b9fe-671a-4189-a7d3-3e92269b94d6)

**Aerial boomerang** - not exactly an error, but I think it would be nice to include a `@Template[type:line|distance:5]` (single square template) in the description, to let users keep track of the boomerang's square during the round after the ability is used.

**Eternal Torch** - in the sentence "All your torches-even ones you already created-shed bright light...", the dashes should be spaced out.  (I think this is a common issue with text that was copied from the pdf, e.g. in Four Winds)

**Flying Flame** - the button in the description doesn't work.  It's: `[[/r (floor(@actor.level/2)+1)d6)[fire]]]{leveled fire damage}`

**Comment by dmarcuse** [comment]
Solar detonation is actually entered correctly as vitality damage, but vitality isn't recognized by the system as a damage type yet - so it's handled as untyped damage, with no descriptive text after the dice.

**Comment by TikaelSol** [comment]
For the eternal torch those should be emdash. If you find more please note them. Miscommunication on my part for not updating all the data entry team people that we weren't removing those.

**Comment by TikaelSol** [comment]
Fixed solar detonation (and a couple other vitality/void inlines). The `fl w` thing is a fun side effect of early access PDFs with bad character encoding. I'd wager that Kineticist and its feats will have a few of these sorts of missing character typos. We'll have to go over all that stuff with a closer eye.
