### ISSUE TITLE
Inspire Courage aura broken?

### ISSUE THREAD

**Issue by fbeuttler** [foundryvtt/pf2e#9111]
I just upgraded to v11 and the new pf2e module version (5.3), and I'm figuring out which mods and settings I had, because some of it got blanked out.
The question I have is about the Inspire Courage aura macro: when I use it on my bard, it seems like it's activating the aura, but not applying the buff to anyone (including the bard herself). the Aura is visible when I mouse-over, but it doesn't actually buff anyone

![image](https://github.com/foundryvtt/pf2e/assets/134541955/f0b6ddba-79c4-4be2-aee8-6d3d8334f0d5)

**Comment by stwlam** [comment]
This would be a module issue
