### ISSUE TITLE
Request - Stunned for x rnds implementation

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#9130]
when an effect gives you stunned for a duration rather than a number of actions, currently the system has no way to do this via conditions
for example if you get stunned for 1 minute
it'd be great if a way was created to signify this on a token

**Comment by TikaelSol** [comment]
This can be done by having an effect that grants the condition, with the duration on the effect itself. However the system should do something more elegant than clutter the compendiums with a ton of effects that only grant conditions.

**Comment by TikaelSol** [comment]
Closing in favor of more specific effect improvement issues.
