### ISSUE TITLE
Familiar sheet support for actions, traits, equipment etc

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#915]
In GitLab by @ricothebold on Dec 5, 2020, 12:59

I may not be using the correct term if it means something specific, but currently you can't add a bunch of "rules elements" to familiar sheets.  Actions (e.g. familiar focus), traits (e.g. plant, for leshy familiars), equipment, etc.

**Comment by TikaelSol** [comment]
Traits and actions are supported now. Equipment for familiars still isn't a thing and we can cross that bridge if it happens
