### ISSUE TITLE
Wild Shape Effect

### ISSUE THREAD

**Issue by Slaycker** [foundryvtt/pf2e#9150]
The animal shape effect, which makes it possible to select the animal/shape you want and that you have is in error, it erases the character's defense, does not put its temporary hp and does not change the character's size. On the other hand, the effects of animals separately work well and normally.

Wild Shape Effect
![image](https://github.com/foundryvtt/pf2e/assets/106133347/64774506-f66a-4a6e-92c8-45c83126f2c2)

Separate Effect
![image](https://github.com/foundryvtt/pf2e/assets/106133347/08cb6811-eb8b-4d87-b4d8-b36218f556ea)

**Comment by stwlam** [comment]
Closing as nonrepro, but please visit us on discord for assistance: https://discord.gg/pf2e
