### ISSUE TITLE
NPC vivielle Ramsley (outlaws of alkenstar) is missing a spell

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#9156]
![image](https://github.com/foundryvtt/pf2e/assets/139762764/a3c39c49-ae07-4674-82cb-12155b373f7b)
![image](https://github.com/foundryvtt/pf2e/assets/139762764/62113586-64f5-4b53-8559-a12f4fa72c95)

this is in book two chapter 4 of outlaws of alkenstar

which also means she should be level 5 because of the spell rank.

**Comment by InfamousSky** [comment]
she does not have a unique statblock.
![image](https://github.com/foundryvtt/pf2e/assets/88115652/fb5c683c-5e4d-4ade-8953-48f25036d4ed)

**Comment by GuitarGuyNick** [comment]
but it does state in the adventure path that she needs to cast that spell. so it should be in her stat block

**Comment by TMunsie** [comment]
Please ask Paizo to errata.

**Comment by GuitarGuyNick** [comment]
how do i do that?

**Comment by TMunsie** [comment]
> how do i do that?

E-mail. Use their Forum. Contact them on discord. However you like? We input the stat blocks that Paizo authors, and we can't say whether they're supposed to know the spell or have a scroll of it or have a wand of it. Only Paizo can do that.

**Comment by TikaelSol** [comment]
We can fix this one just fine, just assume she has that spell on top of the other things since she is supposed to cast it in the adventure.
