### ISSUE TITLE
Feature Request: Ability to define precious material damage for spells

### ISSUE THREAD

**Issue by maplealmond** [foundryvtt/pf2e#9159]
The new Rage of Elements spell Needle Darts allows for a spell attack to deal cold iron or slivered damage.  There is no way to model this in the system currently.  Needle Darts as entered only does piercing damage, and a variant spell cannot be set to be silvered.

For purposes of IWR interaction it would be nice if we could allow a spell to have a precious metal effect.

**Comment by stwlam** [comment]
This is already possible from spell sheets.
![image](https://github.com/foundryvtt/pf2e/assets/106829671/8d578576-e622-43a1-bd5e-44329e53f8f6)

**Comment by maplealmond** [comment]
Totally missed that option.  Thank you!
