### ISSUE TITLE
Wrong Damage: Eldritch Flare

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#9175]
![grafik](https://github.com/foundryvtt/pf2e/assets/134313750/0528cb19-08c0-4e36-9aa4-c010d6cd5ccd)

As shown this posoin deals fire damge, but in the original:
![grafik](https://github.com/foundryvtt/pf2e/assets/134313750/c88648a5-7861-4a69-8c61-c98ceabc9a2a)

there is no fire damage at all.

**Comment by TikaelSol** [comment]
"The spell deals half its damage as one of the types the spell deals" So it could be fire damage, but since most damage from it should be poison the inline buttons should be set entirely to poison damage.
