### ISSUE TITLE
Wrong Damage: Scarlet Mist

### ISSUE THREAD

**Issue by Vendergast** [foundryvtt/pf2e#9181]
![Screenshot 2023-08-06 220132](https://github.com/foundryvtt/pf2e/assets/134313750/4c25304c-97d4-4b4a-877a-d3d0f17365d8)

As seen above Scarlet Mist deals bleed damage (Blutung = Bleed) but should deal:

![Screenshot 2023-08-06 220147](https://github.com/foundryvtt/pf2e/assets/134313750/ca773123-23bb-4a00-ad35-af4e1a952d01)

Persistent Bleed damage.

**Comment by stwlam** [comment]
Bleed damage is persistent by definition
