### ISSUE TITLE
unshaken in iron feat isnt automating armor specialisation

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#9183]
https://2e.aonprd.com/Feats.aspx?ID=4179

this feat isnt showing as automated for a player i have.as it is not automating the armor specialisation effect. 

this is from the new stalwart defender archetype.

**Comment by TikaelSol** [comment]
Armor specialization in general is not yet automated.

**Comment by GuitarGuyNick** [comment]
> Armor specialization in general is not yet automated.

thank you for letting me know. maybe i should change the fr to add armor spec?

**Comment by stwlam** [comment]
> You gain the armor specialization effect of light armor.

ಠ_ಠ

**Comment by GuitarGuyNick** [comment]
in there case they are heavy

**Comment by pedrogrullada** [comment]
Closed by #10093
