### ISSUE TITLE
Cannot equip armor with more than 1 property rune while Automatic Bonus Progression is toggled.

### ISSUE THREAD

**Issue by Baddiemcnoskill** [foundryvtt/pf2e#9201]
If ABP: Allow Property Runes is selected, you can put up to 3 property runes on an Armor item if it is in the items tab.

But if you place it onto a character sheet or try to edit it within a character sheet to begin with, you cannot select more than one Property rune.

**Image showing the variant rule is toggled:**
![image](https://github.com/foundryvtt/pf2e/assets/107281965/d6862106-8dbd-4689-aacd-d1cc1aabeb55)

**Image showing a magical plate armor on a character sheet:**
![image](https://github.com/foundryvtt/pf2e/assets/107281965/f72643c3-b753-4843-85b2-fe17cae0919a)

**Image of the same item when it is generic and not on a character sheet yet:**
![image](https://github.com/foundryvtt/pf2e/assets/107281965/ecadc6c7-bf00-44ae-bb9c-083bbae679bd)

**Comment by stwlam** [comment]
The level of the character determines the equivalent potency rune level and therefore also the maximum number of property runes.

**Comment by Baddiemcnoskill** [comment]
Doing it this way makes it much harder to create magic items while retaining good automation within Foundry.
