### ISSUE TITLE
Add Multiple Selectors support for DamageDice rule element.

### ISSUE THREAD

**Issue by 13ulbasaur** [foundryvtt/pf2e#9224]
I'd like to request that the DamageDice rule element have support added for multiple selectors, the same way FlatModifiers does, so that I could do something like:

`{
  "key": "DamageDice",
  "override": {
    "damageType": "force",
    "dieSize": "d10"
  },
  "selector": [
    "slug1-damage",
    "slug2-damage",
    "slug3-damage",
    "slug4-damage"
  ]
}`

I was stuck for a while trying to figure out why this wasn't working until it was suggested I have only one selector. Being able to condense this into one rules element would make it much tidier than having to make four separate ones.

**Comment by stwlam** [comment]
As an alternative, you can use a selector of "damage" and further filter via predication
