### ISSUE TITLE
Potency Bonus is inconsistently applied to polymorphed unarmed attacks

### ISSUE THREAD

**Issue by chrpow** [foundryvtt/pf2e#9227]
**Is:**
Currently, when automatic bonus progression is used, a potency bonus is automatically added to regular unarmed attacks and NOT to polymorphed unarmed attacks. RAW, this is CORRECT:

> If you take on a battle form with a polymorph spell, the special statistics can be adjusted only by circumstance bonuses, status bonuses, and penalties.

However, in Foundry, if a character wears handwraps of mighty blows, they WILL receive a potency bonus when they make unarmed attacks while polymorphed. RAW this is INCORRECT.

One could interpret the way polymorph rules interact with ABP in one of two ways, but Foundry is inconsistent about which ruling is correct:

Interpretation 1: The allowed list of bonuses while polymorphed doesn't explicitly include potency bonuses. One might argue that this is because ABP is a variant rule that was introduced after the core rules were written, and ABP has a history of being incompletely adjudicated in the core rules. Under this interpretation, potency bonuses should be added to the list of allowable bonuses. In other words, polymorph attacks should be treated like unarmed attacks, which automatically get potency bonuses even without items.

Interpretation 2: The RAW are correct and complete, even when ABP is used. Because potency bonuses are not called out in the rules for polymorph, they should be ignored 100% of the time when polymorphed. In other words, polymorph attacks should be treated like spell attacks, which don't get potency bonuses as characters level up.

**SB:**
If ruling 1 is used, then potency bonuses should be applied to polymorphed attacks regardless of whether or not handwraps of mighty blows are equipped, as they should be treated like ordinary unarmed attacks (which don't require handwraps in ABP). _This ruling is less supported by the core rules and relies on conjecture about how the game _should_ be balanced under ABP._

If ruling 2 is used, then all unarmed attacks while polymorphed should explicitly remove any potency bonuses from their modifiers, even if they come from items like handwraps. _This is the RAW interpretation and probably should be used, but Foundry currently doesn't explicitly remove potency bonuses from polymorphed attacks._

**Comment by stwlam** [comment]
Not able to reproduce. Are you sure the PC's unarmed attack modifier just isn't higher?
