### ISSUE TITLE
Reagent Cost is not incremented by plus buttons

### ISSUE THREAD

**Issue by ThomasGCarpenter** [foundryvtt/pf2e#9234]
<img width="384" alt="Screenshot 2023-08-09 153431" src="https://github.com/foundryvtt/pf2e/assets/29062625/2a3c9c0f-0cb5-4dff-834b-3b12d4fe9b85">

Reagent cost should be 4. Reagent cost does increment when items are dragged in but not when plus button is clicked.

**Comment by Fabrice-Schoeneberger** [comment]
The cost is (kind of) correct. The rules are for Advanced Alchemy: "For each batch of infused reagents you spend, choose an alchemical item of your advanced alchemy level or lower that's in your formula book, and make a batch of **two of that item**".
The cost should increment whenever the total number on potions change up from even to uneven (so like of you have 4 and add a 5th one).
But the cost is also (kind of) false. It should be 3. 1 For 1 for the first 2 Cognitive Mutagen, 1 for the 3rd one and one for the Cheetah's Elixir as far as I understand the rules.
