### ISSUE TITLE
Increase Max Resolve Points

### ISSUE THREAD

**Issue by Peach774** [foundryvtt/pf2e#9240]
I'm trying to increase max resolve using a custom feat and I can't get it to work for the life of me.
I've tried several varieties of code:
{"key":"ActiveEffectLike","mode":"upgrade","path":"{{data.attributes.resolve.max}}","value":2} (also tried with add instead for all of these)
{"key":"ActiveEffectLike","mode":"upgrade","path":"data.attributes.resolve.max","value":2}
{"key":"ActiveEffectLike","mode":"upgrade","path":"systemData.attributes.resolve.max","value":2}
{"key":"ActiveEffectLike","mode":"upgrade","path":"resolve.max","value":2}

Please help me - I am going insane trying to get this to work

**Comment by stwlam** [comment]
While this is not a support venue, please feel free to seek assistance on discord: http://discord.gg/pf2e
