### ISSUE TITLE
Remember my sources (feature request)

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [foundryvtt/pf2e#9260]
Most of the time I want to search for something in the compendium, I want to search only through the things I own. Sometimes I just found something in one section and want to search with the same sources in another.
Here my ideas:
1. Everytime a user searches something, you could save either all parameters or just the sources in a file or something to that user. And whenever they do another search apply those saved parameters. You could make this optional in the menu under a point "Remember my sources/search options" for those that like it the way it currently is

OR

2. In the options menu, give every user the option to define "default search options". Either for just sources or all options. Optional with those presaved sources you could also make a button at the top of the sources list like "use default/predefined" that applies the in the options defined selection

I prefere the first option but both are fine.

The reason to why the focus on the sources is simply, because there are so many. The list of sources gets greater all the time and filtering throught the ones you own takes ages, and I don't see it becoming better without an upgrade like this. All other search options are very short in size and very quick.

**Comment by stwlam** [comment]
Does removing sources in the browser config not satisfy your requirements?

**Comment by Fabrice-Schoeneberger** [comment]
I don't see options to remove sources anywhere in the options. 🤔

**Comment by stwlam** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/106829671/7926325b-1cd2-4118-be3a-5aeda8495822)

**Comment by Fabrice-Schoeneberger** [comment]
That is 95% of what I want ... how did I miss that😅
I think it still would be nice if it remembered the sources selected when you go from for example equipment to feats, but thats not that important. Thank you for helping
