### ISSUE TITLE
Ogre Hook incorrect weapon category

### ISSUE THREAD

**Issue by LTErnis** [foundryvtt/pf2e#9317]
Ogre Hook is set up as an advanced weapon instead of martial:

https://2e.aonprd.com/Weapons.aspx?ID=86

![image](https://github.com/foundryvtt/pf2e/assets/142252680/32f4962c-c32c-4143-a1fe-2b78bd2a77bb)

**Comment by stwlam** [comment]
The book doesn't list a category. AoN and we just assigned it something different.

**Comment by LTErnis** [comment]
> The book doesn't list a category. AoN and we just assigned it something different.

Thanks, I've checked in the bestiary and noticed that too. Any reason for specifically picking advanced category? If you don't mind me asking :)

**Comment by TMunsie** [comment]
Fatal plus trip plus it is sort of an ancestry weapon. Great pick is fatal and a martial weapon. So ogre hook seems more in line with advanced weaponry.

**Comment by LTErnis** [comment]
> Fatal plus trip plus it is sort of an ancestry weapon. Great pick is fatal and a martial weapon. So ogre hook seems more in line with advanced weaponry.

Thanks for the explanation! I saw it being compared to a scythe (martial) which is also trip+fatal+same dmg, so I guess the limiting factor would be that it's ancestral?
