### ISSUE TITLE
Manual Modifer Bug on Newest versions of Firefox.

### ISSUE THREAD

**Issue by Genny-Gen** [foundryvtt/pf2e#9338]
In the newest versions of Firefox, when on the roll modifier screen, manually inputting a modifier and putting a + before the number modifier instantly sets it to a +1 no matter the number put in after. Weirdly this does not occur when a - is put in first. Works perfectly fine just putting the number in without a + though.
The strange part is, this doesn't occur in other browsers, or older versions of Firefox.  In testing I used Brave, Microsoft edge, and an older version of Firefox, 102 ESR. They do not suffer the + issue.

**Comment by stwlam** [comment]
What's the version?

**Comment by stwlam** [comment]
This appears to be a six-year-old bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1392068
