### ISSUE TITLE
Request/Discussion: Refactor physical item types

### ISSUE THREAD

**Issue by shemetz** [foundryvtt/pf2e#9351]
Currently, the inventory item types available in the system do not adequately cover all use cases, and I believe many people are in favor of expanding the list of options, particularly those tied to automation in various ways.

Here's a list of the existing Physical Item types, what they currently include, and what I think they are intended to represent:

| Item type  | My description/association | Examples **(bolded if controversial)** |  Examples of items *not* included |
| ------------- | ------------- | ------------- | ------------- |
| Armor  | Armor, the specific item you wear in your Armor slot and uses some armor proficiency | Armor, Barding, **Shields** | Clothing (Equipment)  |
| Consumable  | Items that can only be used once, or a small number of times.  Everything under "Momentary Magic" in the core books.  | Ammunition, Oils, Potions, Talismans, "Wondrous Consumables", Poisons, Scrolls, **Wands**, **Blindpepper Bomb** | Magical Staves (Weapon), Tactician's Helmet (Equipment) |
| Container | Items that physically contain other items | Backpack, Chest, Portable Hole | Gloves of Storing (Equipment), Class kits |
| Equipment | Worn or carried items that don't fit other categories (this is the "misc" category) | Armor, Gloves/Boots/Cloaks/etc, Instruments, Tools, most adventuring gear (e.g. Bedroll, Hourglass), most specific magic items (e.g. Flying Broomstick), **Runes (when not directly inside weapon/armor details tab)**, **Keys (e.g. Caliddo's Keys)**, **Precious Materials (e.g. Silver Ingot)** | Weapons, Ammunition, Armor, Containers that are worn |
| Kit | Class kits (probably removed in Remaster?) | Class kits | |
| Treasure | Items purely used as currency or intended to be easily exchanged for currency | Coins, gems, art objects, raw crafting materials, **occasionally Keys and other important "story" items** | Precious Materials |
| Weapon | Items used in combat to harm others physically, including expendable weapons but not weapon components | Melee/thrown/ranged weapons, Bombs (mostly), Staves, Shield Boss | Shields (Armor) |

Here are some problems that I see with the existing types:
- "Equipment" is a catch-all category for all the miscellaneous items;  I think this is not ideal, and it should be split up further.  When somebody is e.g. creating a new custom Precious Material, or a plot item with a description that the players are expected to read, "Equipment" is not the word that comes to mind;  the word implies that the item can be equipped, i.e. held or carried.
  - I suggest making "Equipment" only refer to items that have a Usage field in the rulebooks;  in other words, items that are either "worn", or "worn (some body part)", or "held in X hand(s)" (or e.g. "Hands: X").  All other items should be put under a different category, and new categories should be made for them (see my points below).  The remaining items (Bedroll, Gauntlight, Endless Grimoire, Practice Targets...) should be put under a new "Misc"/"Other" category.
- Keys (found by characters and used to open specific doors) are marked as either Equipment (a recent change from last week) or Treasure, leading to bug reports like: https://github.com/foundryvtt/foundryvtt-premium-content/issues/325, #7054.  Other important items may also be marked as Treasure by accident;  for example, a piece of paper with important writing, or a book, or 
  - I think keys should belong to a new item type such as "Quest Items" or "Key Items" - Adventure-specific items that should never be accidentally sold (though they still can have a gold value).  Keys are not really "equipment", because they aren't usually worn/held in any meaningful way, and they are important for players to see separately in their sheet because they serve a story purpose.
- Bombs should all be weapons.  Currently, a player that crafts a [Blindpepper Bomb](https://2e.aonprd.com/Equipment.aspx?ID=799) will not find it under Weapons, but rather under Consumables, even though it still functions as most other bombs - just without an attack roll (only a saving throw).  I've had a player complain about this, unable to find the item where she expected in the Actions tab, because only weapons appear there.  Note that [Bioluminescence Bomb](https://2e.aonprd.com/Equipment.aspx?ID=1819) *is* considered a weapon, so I don't see the reason why Blindpepper Bomb isn't.
- Runes, Talismans, and Spellhearts are usually attached to items.
- Wands are considered "consumable" even though they refresh every day.
  - Wands should possibly have their own item types, as they work with very specific rules, though there isn't full automation yet.  I imagine the item type would include a field for one spell stored.  Scrolls could also use a similar item type, though it isn't needed as much, as Consumable fits them pretty well.
- Equipment that has charges, such as the [Tactician's Helm](https://2e.aonprd.com/Equipment.aspx?ID=2339), doesn't let players keep track of those charges because those items are "not Consumables".
  - Staves and other items with charges should just probably have a "charges" field added to them.  I don't think adding a new item type is needed, because they're still all weapons or equipment.
- Runes can currently be in one of two places:  either as free-floating Equipment or as a selected option inside Weapon/Armor items.  Having them as built-in options is alright, but there is currently no way to mark the connection between a rune and an item if it an [Accessory Rune](https://2e.aonprd.com/Equipment.aspx?Category=23&Subcategory=78) or just a homebrew rune.  Spellhearts are in a similar place (plus the issue of needing to track spell usage like Wands).  Talismans too.  Weapon attachments too (scope, stabilizer).
   - We should add a new "Attachment" item type.
   - In the future, we would probably like to have them "contained" by other items, but that's a separate feature request.
- Precious Materials seem to me like they should just be Treasure, as they are near equivalent to currency.  If not, they should be their own item type, and not Equipment, because they aren't worn or carried.
- Shields should be their own category;  there isn't a reason to lump them in with Armor. other than a few similarities with their statistics.  They function quite differently, requiring special automation.

Overall, I think a lot of item type categories should be added!

The biggest reason *not* to add these categories - other than the required effort of recategorizing thousands of items - is that if we have more categories we have more headers in the character sheet, leading to a cumbersome sheet.  However, I think this can be solved by just combining certain headers after this refactor happens.

For example:  Attachments that aren't currently attached, Precious materials, Treasure, and Key Items are all generally similar (irrelevant during most scenes) so they could be bundled up together under "Carried Treasure".  Weapons and Shields could be group up as "Weapons".  Armor and other worn Equipment could be grouped up as "Worn Equipment", and maybe moved down below Consumables because many of them are rarely clicked (unless they have a special action that isn't automated).  Equipment that is held in a hand, rather than worn, could actually be put into a "Held Equipment" category, and placed near the top after "Weapons" - because it's more likely to be drawn/stowed frequently.

I know that this issue has been brought up before (about wands being consumable, keys being treasure, shields being armor), but I couldn't find another discussion of it in GitHub.  Feel free to move this discussion to Discord, and/or split into multiple github issues if you have specific action items.

**Comment by shemetz** [comment]
@rectulo Just like Gloves of Storing and similar items, this is currently an Equipment.  I think it should either become a Container, or stay an Equipment and wait for a future "any item can contain other items" feature. It seems to fit both the ideal Container definition and the ideal Equipment definition, so either option seems good to me.

**Comment by stwlam** [comment]
Closing as stale/not in tune with development plans
