### ISSUE TITLE
Add option for Weapon Innovation inventor's overdrive to deal fire damage

### ISSUE THREAD

**Issue by pedrogrullada** [foundryvtt/pf2e#9364]
Building an inventor for an upcoming campaign and I just learned they can make their additional overdrive damage be fire damage. This is not implemented in the system yet. Perhaps adding a toggle if you have the weapon innovation, or making a separate effect?
![image](https://github.com/foundryvtt/pf2e/assets/103401186/ece79b98-ef57-4d96-8dd0-952fcb213464)

**Comment by tdhsmith** [comment]
Looks to be closed by #10036?
