### ISSUE TITLE
Add a button to ChoiceSet windows to quickly open a compendium item being referenced

### ISSUE THREAD

**Issue by pedrogrullada** [foundryvtt/pf2e#9404]
While I'm aware Foundry is not meant to be one's primary source when planning a character, I do think it'd be a nice improvement to building characters within Foundry to be able to quickly look up what an option entails.

Here is a quick and dirty mock up, just recycling the "i" button down there, but it'd probably be better if it were a different one.

![image](https://github.com/foundryvtt/pf2e/assets/103401186/daca1e95-e28f-479f-af92-a24847931e77)

**Comment by stwlam** [comment]
From #9786:
> It would be really cool if we were able to read the choices before clicking on it. Like barbarian instincts, a window pops up and ask which one you want, it would be nice if you right click or hover the name and it opens the journal with what the instinct does before deciding. Same for the feat that gives you a general feat choice, would be nice to know what the feat does easier
