### ISSUE TITLE
Tag knowledge skill rolls with dubious knowledge

### ISSUE THREAD

**Issue by bogga** [foundryvtt/pf2e#9409]
QOL request: if a character rolls a knowledge skill and has the dubious knowledge feat, tag the roll message with "Dubious Knowledge" just to give the GMs a passive reminder
Maybe also worth making it conditional on the roll being a (non-crit) failure?

**Comment by stwlam** [comment]
This wouldn't be correct, sorry.

**Comment by CarlosFdez** [comment]
More accurately, this is already done, but it must specifically be a roll for recall knowledge. Some modules expose such a roll (workbench has a basic actions macro that does such a thing), but also so do the roll links of some adventures.

What we're actually missing is a way for NPCs to dump RK in the chat.
