### ISSUE TITLE
Mister Beak & Other NPCs have an incorrect Phantom Pain

### ISSUE THREAD

**Issue by crowlute** [foundryvtt/pf2e#9424]
As noted in the title, mister Beak and a few other NPCs have an incorrect Phantom Pain spell in Abomination Vaults.

The Phantom Pain on Mister Beak, Graulgust, and other NPCs with said spell have, under Edit -> Details -> Damage: 1d4 Persistent Mental damage. This is causing persistent mental damage to be applied to a target, even if they Succeed their save. 

Deleting and importing the version from the Compendium fixes this, but it would be nice if the NPCs had the correct handling of the spell on their sheets already :)
(I got help from the "Pathfinder on Foundry VTT Community and Volunteer Development Server" and am including a few attachments that may be relevant: 
The code (as shown by @websterguy https://media.discordapp.net/attachments/880969241552113695/1142611819731632158/image.png), 
A successful save receiving 1/2 persistent damage instead of none: https://media.discordapp.net/attachments/880969241552113695/1142610024984739971/image.png
Wrong Phantom Pain: https://media.discordapp.net/attachments/880969241552113695/1142610401679384667/image.png
Right Phantom Pain:  https://media.discordapp.net/attachments/880969241552113695/1142608782279581766/image.png)

I'm not very knowledgeable about github so I hope this passes muster for an issue report.

**Comment by TMunsie** [comment]
If it is correct in the system compendium I’m not sure what you want us to do?

Is this an old install, with old actors in it? If you reinstall AV does it have the issue still?

If it doesn’t, then the solution is to replace the actors in old installs or use a new install. If it does still have the issue then you need to report it to the premium content module. At least if you’re telling me that the actors in the system compendium are correct?

**Comment by websterguy** [comment]
The issue is actually many actors in the compendiums have old versions of the spells with the persistent damage included as part of the normal damage roll, which is different than the way the spell itself is in the compendium right now (as it should be). For instance, Mister Beak currently in the compendium on 5.3.2:

![image](https://github.com/foundryvtt/pf2e/assets/54455090/98fb120c-592e-4885-adb9-d1bd2c78ab5c)
