### ISSUE TITLE
feature request: a way to collect results from a send to chat dc.

### ISSUE THREAD

**Issue by GuitarGuyNick** [foundryvtt/pf2e#9442]
i dont know if this is possible but i propose something that could collect results in a chat card rather than having multiple chat cards for results.

so for example:

someone posts to chat a skill check dc or save dc through the send to chat feature. 

in alot of cases the whole party may have to do this

if there are multiple results coming from these saves and checks.

id like to have a chat card that collects these saves into one chat card so its easier to digest for the gm. 

so a chat card that recieves data from the pc and is expecting the end result after a save or a skill check. 

and shows the level of success for each of the pcs. and on each of the pcs results you have a drop down menu to change them if needed. 

i fully understand if this isnt possible but its something i thought about today in respect to how many saves my players are doing collectively and it becoming messy in the chat to decipher which belongs to which save/skill check.

**Comment by stwlam** [comment]
Not going this way, sorry

**Comment by GuitarGuyNick** [comment]
will there be something that will cater towards that idea? or make it easier to recieve mass saves?

**Comment by stwlam** [comment]
Maybe a module will provide it: inquire with the author of Target Damage

**Comment by GuitarGuyNick** [comment]
what about at the very least having the full description of what they are saving from? or have the send to chat saves contain where they came from in the chat description?
