### ISSUE TITLE
wrong tag linking from character sheet to feat browser

### ISSUE THREAD

**Issue by mishakuma** [foundryvtt/pf2e#9463]
![image](https://github.com/foundryvtt/pf2e/assets/142813471/16b1a805-9ebc-4722-a6c4-50975946f175)

Hey i was reacreating my PCs because we are switching from german to english.... 

so i recognised if i klick on the search icon in PC Sheet Feats section under Skill and General Feat, the compendium browser opens up with the "Monk" Tag in the Filter. Its just a Small issue but i thought i let you know.

I didn't test it on other classes yet but i will post later if the same happens to different classes

![image](https://github.com/foundryvtt/pf2e/assets/142813471/90887a65-8981-40ce-bafb-9f92f53c662d)

![image](https://github.com/foundryvtt/pf2e/assets/142813471/4a52b893-8e97-4aac-98af-75236c4b17e4)

**Comment by stwlam** [comment]
Not able to reproduce this. If you can provide reproduction steps, we'll gladly reopen it.
