### ISSUE TITLE
Gaseous Form spell effect listed as "Gaseous Form" but adds "Vapor Form"

### ISSUE THREAD

**Issue by digitalpacman** [foundryvtt/pf2e#9476]
This is very simple, and annoying, but doesn't stop anything really. The text of the draggable spell effect says "Gaseous Form" but when applied, it actually adds a "Vapor Form". This changed at some point. I had animations that worked with gaseous form but it's changed to vapor form now.

**Comment by rectulo** [comment]
That is a remaster change and we are in a transition phase. 
Choice has been made to keep the old name in items (ie NPCs of previous AP) but to give it in the system the remastered name. The label stays unchanged in the description of the item but the link leads to the new name. 
The effect will be the same in both cases. 
For animations, I guess it's better to apply the remaster changes you will find in the Journals during the transition.

**Comment by digitalpacman** [comment]
Oh okay that makes sense
