### ISSUE TITLE
Angelic Halo Rule Element Support

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/pf2e#9502]
> Allies in your halo's emanation who are healed by a heal spell gain a status bonus to Hit Points regained equal to double the heal spell's level.

This will require implementing `spell.rank` into `healing-received` workflow.

The Rule Element for good measure.
```json
{
  "key": "FlatModifier",
  "predicate": [
    "item:slug:heal"
  ],
  "selector": "healing-received",
  "value": "2 * @spell.rank",
  "type": "status"
}
```

**Comment by stwlam** [comment]
MAKE A PR< MR VAUX
