### ISSUE TITLE
Damage type roll option not changing when using versatile weapons

### ISSUE THREAD

**Issue by zrampage96** [foundryvtt/pf2e#9594]
hi im working on a new effect for my game and i have found a bug where the damage types are swapping for the predicate but it is swapping and rolling the correct damage for the dice when swapping with versatile damages

![image](https://github.com/foundryvtt/pf2e/assets/58835626/d109aaaa-f193-4cb1-954a-69c6a34d43e8)

**Comment by stwlam** [comment]
These rule elements wouldn't do what you're describing

**Comment by zrampage96** [comment]
i been getting help from the pathfinder in foundry discord by tikael

**Comment by zrampage96** [comment]
it should be adding fire damage by on the level on the effect but only on percing damage and on weaons with a homebrewed weapon triat

**Comment by TikaelSol** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/80183198/96362987-d9f3-4bcc-bba5-616005128255)

The `item:damage:type` roll option is not changing when you change a weapon from slashing / piercing using the versatile toggles.
