### ISSUE TITLE
[Feature Request] Option to allow access to stash without allowing viewing of other PCs' statistics

### ISSUE THREAD

**Issue by AFigureOfBlue** [foundryvtt/pf2e#9658]
I love what I'm seeing of the new party sheet!

In the style of campaign I run, I prefer that the players not be able to readily view the statistics (skills, languages, senses, saves, etc.) of other PCs), since such things often can reveal secrets pertaining to a character's backstory. By setting ownership of the Party to "None", I as a GM can view the party sheet without the various players also being able to access it to see their fellow PCs' statistics. However, I would love to still be able to make use of the stash as a shared party treasure chest. Would it be possible to add a setting or permission level where players could open the party sheet to see its name, image, and stash, but not access all the details about the party members' statistics?

**Comment by TMunsie** [comment]
Why would you not just use a loot actor?

**Comment by CarlosFdez** [comment]
This setting already exists. Go to Limit Metagame Information in settings and tick off `Show Party Member Stats`. This hides the overview tab, as well as numerical values for characters the user lacks observer permission for. HP is still visible as a bar in the exploration mode tab.

**Comment by AFigureOfBlue** [comment]
Oh, that's perfect! Exactly what I was looking for. I had even looked in Limit Metagame Information but I must have missed it - thank you.
