### ISSUE TITLE
Kineticist Archetype not adding Elemental Blast to Attacks

### ISSUE THREAD

**Issue by dogstarrb** [foundryvtt/pf2e#9659]
The Elemental Blast drop down for 1 or 2 actions appears, but the blast attack itself does not, nor does the Elemental Blast Action appear among Actions. 
![Kineticist Dedication](https://github.com/foundryvtt/pf2e/assets/7331744/81a7fe32-ced2-49d2-aa63-8907a718ca9b)
![attacks and actions](https://github.com/foundryvtt/pf2e/assets/7331744/25ddb5ec-cf85-4786-b542-4a6489034a24)

**Comment by wouldntsavezion** [comment]
You need to have the proper Kinetic Aura enabled, try clicking on the "use" button on Channel Elements to setup everything.
