### ISSUE TITLE
Scorching Column Leveled Hazardous Terrain Damage is wrong

### ISSUE THREAD

**Issue by EmurlahnRPG** [foundryvtt/pf2e#9668]
The level scalling damage on the hazardous terrain on Scorching Column (Kineticist Fire Feat) does not scale correctly. 
As far as I can see, there is no equation that will return the correct scalling. 
I don't know if you can put in an if/else, that just checks player level for the correct threshold, or if there is a more elegant way to do it.

**Comment by tdhsmith** [comment]
Is this definitely still a problem? It looks correct to me as of v5.4.4, upping to 3 hazardous damage at level 4, 5 damage at level 7, etc...

**Comment by EmurlahnRPG** [comment]
I cannot see the formula in 5.4.4, but in 5.4.2 it increases to 3 damage at level 3,  5 damage at level 6, and 7 at level 9 and so forth. So it is basically a level ahead.
