### ISSUE TITLE
Items cannot be removed from containers in party and loot sheets

### ISSUE THREAD

**Issue by datorangebottle** [foundryvtt/pf2e#9681]
It seems like you can't actually remove items from containers in the party sheet.
Steps to reproduce:
1) Add a Backpack to your party sheet.
2) Add an item to the sheet (In this case, Blunderbuss Rounds)
3) Open the backpack.
4) Add the item to the backpack.
5) Try to remove the item from the backpack. [Note: the weight in the backpack does not change even if it successfully moves out of the container]
6) Close the backpack. 
7) Notice the item warping back into the backpack.

**Comment by CarlosFdez** [comment]
This seems to also be a bug with loot actors. Seems to be a failing of whatever the socket communication does.
