### ISSUE TITLE
Can't open character sheets

### ISSUE THREAD

**Issue by harpzone** [foundryvtt/pf2e#9698]
So, after updating to 5.4.0, I can no longer open my character sheets. I can still open my NPC sheets but not the player character sheets. I wonder if I missed something in the patch notes or if it's a bigger issue. I can add characters to the party sheet, and the party sheets open, but I can't open the characters from there either. When I use my macros to roll for the characters, they still roll, so the information for everything is there. If I make a new character sheet, it won't let me open it.

**Comment by stwlam** [comment]
While this isn't a support venue, you are welcomed to seek assistance on discord: http://discord.gg/pf2e
