### ISSUE TITLE
Critical Success Overdrive no longer applies bonus damage after upgrading to v11

### ISSUE THREAD

**Issue by LazyDope** [foundryvtt/pf2e#9714]
After upgrading to v11 from v10, the effect from the Overdrive feature shows a prompt when applied and does not add the additional damage regardless of whether critical success or success is selected. If you manually apply the old effect for regular success it still works, however an effect for critical success does not exist.

**Comment by TikaelSol** [comment]
![image](https://github.com/foundryvtt/pf2e/assets/80183198/acb006f5-1c33-44c8-a8f8-0cccf8ebaf39)

I don't see this issue. Are you applying it to the inventor or their companion?

**Comment by LazyDope** [comment]
I was applying it to myself, the inventor, however I was able to fix it by removing the entire class and adding it back. Something must've been not initialized properly through the upgrade from v10 to v11.
