### ISSUE TITLE
prone immunity aquatic combat

### ISSUE THREAD

**Issue by dharkus5000** [foundryvtt/pf2e#9733]
as per the prone condition, you can't be prone while swimming, which you've pretty much gotta be doing if the aqautic combat effect is in place, so it'd make sense to add prone immunity to the effect?

**Comment by stwlam** [comment]
Walking the sea floor happens even in APs.

**Comment by dharkus5000** [comment]
walking the sea floor is a homebrew thing, not supported by the rules, and you still can't be prone in that case i'd think, RAW you have to swim to move underwater

**Comment by stwlam** [comment]
Do you have a citation any of that?

**Comment by stwlam** [comment]
CRB pg. 512:
> PCs in an aquatic environment need a way to breathe (typically a water breathing spell) and must usually Swim to move, though a PC who sinks to the bottom can walk awkwardly, using the rules for greater difficult terrain.
