### ISSUE TITLE
Request: Dragging Elemental Blast to macro / hotbar

### ISSUE THREAD

**Issue by Gurrgel** [foundryvtt/pf2e#9739]
Currently, it's not possible to drag the Kineticist's Elemental Blast Attack Action (from the Actino page of the character sheet) down to the Macro bar, something which you can do with other attacks found in the same list, if it would be possible to add support for adding it to the macro bar that would be great!

**Comment by nsurette** [comment]
This might be because Elemental Blast doesn't seem to have any sort of automation for the attack portion of the skill therefore there's nothing for the hotbar to have. 
I'm not sure if this would be a seperate issue or just part of the one above but Elemental Blast could use some automation or at least links to where it is automated.

**Comment by TikaelSol** [comment]
@nsurette Elemental blast is fully automated, channel your element and if that does not work make sure you are on an up to date system build and rebuild the actor (do not use importers).

**Comment by Gurrgel** [comment]
To clarify, the Channel Elements feature works just as I'd expect it to, and if I drag that to the macro bar I can click it just fine (the Use button listed under the action name in the character sheet is unavailable, but that seems harder to solve). 

However, what I'm talking about is the Elemental Blast attack that pops up in your character sheet once you have activated Channel Elements. That ability is impossible to drag down to the action/macro bar, and even if I manually set up a macro and refer to the ItemID of the Elemental Blast Ability, it doesn't offer the usual attack (with different MAPs) and damage rolls I'd get if I drag a weapon attack down. I was hoping it would be possible to drag the attack down so that whenever the macro button was clicked, it would either use Elemental Blast as an attack with the currently selected modifiers (Action usage, options from Weapon Infusion), or the ones that were selected at the time the ability was dragged to the action bar.
