### ISSUE TITLE
Send to chat condition and tooltip aren't working anymore on v11

### ISSUE THREAD

**Issue by ariakas2008** [foundryvtt/pf2e#9765]
Hello, 
seems in v11 Send to chat condition and tooltips aren't working anymore.
I am on fvtt11.308, pf2 5.4.2, no modules enabled.
Step to reproduce:
-add a condition from token hud to a token or drag a condition from compendium condition on token
-clic on "send to chat" button on condition icon on top right of canvas
or
-activate a combat
-hover mouse on chat message conditions of current combatant

![image](https://github.com/foundryvtt/pf2e/assets/49585869/666a92cf-1538-4ef4-8d49-b31d77ab188e)

**Comment by ariakas2008** [comment]
I can replicate it also on a fresh new world.

**Comment by simonward** [comment]
This is probably a bad system install. Try deleting the PF2e system entirely, then reinstalling. If you're on Forge, restart your server.

**Comment by ariakas2008** [comment]
> This is probably a bad system install. Try deleting the PF2e system entirely, then reinstalling. If you're on Forge, restart your server.

already done them all, to no avail. I am on Oracle.

**Comment by ariakas2008** [comment]
> This would be a caching or core installer issue. In case of it having to do with caching, go to http(s)://hostname-of-server/systems/pf2e/lang/en.json and reload it once it comes up. Then go back to your game and hard refresh there.

I can't reach that link (with the ip address of my Oracle instance). I have deleted my cache, to no avail.
