### ISSUE TITLE
Magus Inexorable Iron - Temp HP on Use not applied

### ISSUE THREAD

**Issue by dbfimau83** [foundryvtt/pf2e#9766]
The Magus' Arcane Stance for the Inexorable Iron Hybrid Studies ability presently only adds temp HP at the start of the turn and not also on use like it should. The ability in the rules reads:

"WHEN YOU ENTER ARCANE CASCADE STANCE AND at the start of each of your turns while you're in that stance, if you're wielding a melee weapon in two hands, you gain temporary Hit Points equal to half your level (minimum 1 temporary HP)." Secrets of Magic, pg.39 (emphasis added.).

The "Stance: Arcane Cascade" effect (item ID: fsjO5oTKttsbpaKl) has a Temporary HP rule that reads:

{"events":{"onTurnStart":true},"key":"TempHP","predicate":["feature:inexorable-iron","self:weapon:melee","self:weapon:hands-held:2"],"value":"max(floor(@actor.level / 2), 1)"}

I've verified that it correctly applies the temp HP at the beginning of each subsequent turn after use, but not also immediately upon using it. I have inelegantly corrected this by modifying the rule element with another Temporary HP entry, but it gets rolled back with each system update.

**Comment by TMunsie** [comment]
Feel free to commit the updated effect to the repository for review :)
