### ISSUE TITLE
Specific metal trait not applied for Needle Darts spell damage

### ISSUE THREAD

**Issue by johncarney** [foundryvtt/pf2e#9808]
When casting _Needle Darts_, we are given the option of the specific type of metal to be used. However, the damage does not have the chosen trait.

In the screenshot below I chose _Needle Darts (Silver)_ in the chat card and attacked a creature that is "resistant to physical (except silver)." The resistance was incorrectly applied, presumably because the damage did not have the _Silver_ trait.

<img width="298" alt="image" src="https://github.com/foundryvtt/pf2e/assets/322950/e39acc53-e961-4311-bbda-fc66f37730b6">

In the following screenshot I attacked the same creature with a silvered weapon. Interestingly there is no _Silver_ trait shown in the damage card, nevertheless the damage bypassed the physical damage resistance as expected.

<img width="298" alt="image" src="https://github.com/foundryvtt/pf2e/assets/322950/0b96c7bf-f124-47b5-a13f-66da00c254d6">

**Comment by simonward** [comment]
Unable to reproduce. Please retest without modules.

**Comment by johncarney** [comment]
Done. You're quite right. I will try to isolate the problematic module and take it up with them. Thanks for taking the time to look into it.

<img width="287" alt="Screenshot 2023-09-02 at 10 49 40 PM" src="https://github.com/foundryvtt/pf2e/assets/322950/c339cf99-8421-480f-a1c3-be3053935f8c">

**Comment by johncarney** [comment]
FWIW, the problem appears to be in the [PF2e Workbench](https://github.com/xdy/xdy-pf2e-workbench/issues/974) module's "autoroll damage for spell attacks" option.
