### ISSUE TITLE
Druid Order Explorer not giving the Level 1 feat of the order

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#9825]
https://2e.aonprd.com/Feats.aspx?ID=319
You have learned the secrets of another druidic order, passing whatever rites of initiation that order requires and gaining access to its secrets. Choose an order other than your own. **You gain a 1st-level feat that lists that order as a prerequisite**, and you are now a member of that order for the purpose of meeting feat prerequisites. If you commit acts anathema to your new order, you lose all feats and abilities requiring that order but retain your other druid feats and abilities. You don’t gain any of the other benefits of the order you chose.

Bard Basic Muse Whisper's already do something similar, without checking for the selected muse you take with the feat, if possible this could be automated too.

**Comment by stwlam** [comment]
With the character in question, do they have the druid class or archetype?

**Comment by sambomb** [comment]
Archetype
