### ISSUE TITLE
Attempting to change the Party Sheet's name as a player breaks UI scaling

### ISSUE THREAD

**Issue by MoritzGr** [foundryvtt/pf2e#9849]
When I, as a player, try to change my Party sheet's name and confirm with enter, the games page reloads and adds a "?name=..." query to the url. I noticed this on a Forge hosted game going from "https://_GMNAME_.eu.forge-vtt.com/game" to "https://_GMNAME_.eu.forge-vtt.com/game?name=TestPartyName".

The name change does not go through (This might be because my account does not have the rights to the actor, though) and this newly loaded page behaves the same as the regular game, with the exception that the sidebar now scales to its content, and with it the action bar at the bottom resulting in both not always being displayed at their intended positions at the bottom of the screen:

Example on Items tab:
![image](https://github.com/foundryvtt/pf2e/assets/22797767/4426b29f-0f03-46bc-ae5e-8f916cec1bc5)

Example on Settings tab:
![image](https://github.com/foundryvtt/pf2e/assets/22797767/18fe4150-5d7c-4c62-83d8-4e8f2bae7fa9)

Example on chat tab, causing the sidebar and action bar to be off the screen:
![image](https://github.com/foundryvtt/pf2e/assets/22797767/51e7f5cd-8720-43d3-94d4-7dad22bef317)

I know this isn't exactly a showstopper and a very obscure problem, but I thought I would still document it and write an issue to let you know. Also I'm not sure if this is one or multiple bugs, and if it is exclusive to the PF2e module, but this is the way I know how to trigger it.

**Comment by TMunsie** [comment]
Verified on non-forge install on master:

![image](https://github.com/foundryvtt/pf2e/assets/25963508/31e8503d-c889-497d-99fa-797d60518bdb)
