### ISSUE TITLE
Feature Request: Disable Golarion Specific Languages as Homebrew option

### ISSUE THREAD

**Issue by dogstarrb** [foundryvtt/pf2e#9867]
When playing in homebrew settings, the Golarion specific languages can create a lot of clutter when considering one might have each of them replaced with a homebrew setting specific language, and can create confusion for players not familiar enough with the settings in question to know which languages are available here, and creates more questions for the GM. It would be significant QoL to filter out these setting specific languages as a Homebrew Settings option.

**Comment by stwlam** [comment]
A module could do it, but this won't be something the system implements.
