### ISSUE TITLE
[Feature Request] Create NPC abilities by dragging feat/feature items onto the NPC

### ISSUE THREAD

**Issue by AFigureOfBlue** [foundryvtt/pf2e#9900]
I frequently have a use case where I'm designing NPCs which have abilities which replicate feats or features which are available to PCs. 

Currently, that involves importing the feat/feature from the compendium, adding a blank action to the NPC, copying and pasting the text of the feat/feature, adjusting the number of actions it takes to use (if any) and (most significantly) adding rule elements and pasting in their JSON data.

This would all be much simpler if it were possible to simply drag a feat/feature onto an NPC stat block and have it get added to the NPC as either an action or passive (depending on the feat/feature in question).

Obviously not every PC feat or feature would instantly work perfectly on an NPC; some have predicates that end up requiring other PC-specific features and such. But this would work out of the box for many abilities as-is (e.g., the many feats that grant new actions or reactions, which are precisely the ones most likely to be useful to an NPC), and would be a huge time savings for others (which might just need some DCs manually set or a couple predicates adjusted in their rule elements - still far simpler than recreating the whole ability from scratch).

**Comment by stwlam** [comment]
We recommend making NPCs using PC rules (see [here](https://2e.aonprd.com/Rules.aspx?ID=1042) for guidance). It's already a shaky proposition to copy the contents--including rule elements--of a feat to an NPC, and it will only get worse as system automation improves.
