### ISSUE TITLE
Option to turn off unmaintained module warnings

### ISSUE THREAD

**Issue by apoapostolov** [foundryvtt/pf2e#9918]
Currently I am still using the mod Hidden Soundtracks that - while it is unmaintained - works perfectly with PF2E. I have a mild OCD and manually removing the slow yellow notifications every time is really causing me annoyance. I want to remove these warnings through an option ideally. 

I asked Dorako of Dorako UI if there was a way to turn these off via CSS and he told me he doesn't know of a way to do it perhaps because these is no special class added to them, so even a partial resolution via a CSS class that allows them to be turned off via Custom CSS mod or other approach will be good enough.

Thanks in advance!

**Comment by stwlam** [comment]
Sorry: if it could be turned off, it wouldn't be in place at all.
