### ISSUE TITLE
Flavor Text parsing should be complete internationalized

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#993]
In GitLab by @mirkoRainer on Jan 13, 2021, 04:32

In pf2e.ts around line 283, there is a reference to the flavor of a message which evaluates a boolean based on English. This would not work if the flavor has been translated. From a cursory glance, this is the only reference in the code that is not internationalized.

```
Hooks.on('getChatLogEntryContext', (html, options) => {
    const canApplyDamage = (li) => {
        const { messageId } = li.data();
        const message = game.messages.get(messageId);

        return (
            canvas.tokens.controlled.length &&
            message.isRoll &&
            message.data &&
            message.data.flavor &&
            message.data.flavor.includes('Damage')
        );
    };
```

**Comment by TikaelSol** [comment]
These lines are no longer present in the system
