### ISSUE TITLE
"value":"-@item.badge.value" not working for "system.attributes.dying.max"

### ISSUE THREAD

**Issue by blacktrench** [foundryvtt/pf2e#9937]
I use {"key":"ActiveEffectLike","mode":"override","path":"system.attributes.dying.max","value":"-@item.badge.value"} for a custom effect that works similar to Doomed, instead of subtracting from max dying I can no longer add any stacks of dying as it is stuck at dying 1, won't increase.

-@item.badge.value still works for conditions like frightened

Tested with no modules

![image](https://github.com/foundryvtt/pf2e/assets/24504912/8852774a-ca44-4e0c-b489-23da7491e179)

**Comment by stwlam** [comment]
Why this isn't a support venue, you are invited to seek assistance on our discord server: https://discord.gg/pf2e
