### ISSUE TITLE
The fire kineticist does not take into account the damage dice

### ISSUE THREAD

**Issue by Pashapkin** [foundryvtt/pf2e#9972]
The fire kineticist does not increase the damage bone of abilities and "Elemental Strike" when choosing single gates.
Does this need to be fixed in formulas or can a separate module be installed for this?

**Comment by stwlam** [comment]
Can you point to the ability you're referring to?

**Comment by Pashapkin** [comment]
Yes, This SCORCHING COLUMN. Initially, she deals d6 damage, but when choosing a single fire gate, she must deal d8, but the damage bone does not change

**Comment by stwlam** [comment]
Not able to reproduce. Was this kineticist from the initial content release? Does it have the kineticist class or archetype?

![image](https://github.com/foundryvtt/pf2e/assets/106829671/b537e74e-543a-444f-8100-95be410cf1d4)

**Comment by Pashapkin** [comment]
Yes, this class-kineticist. Apparently I made a mistake when creating the kinetic. 
But at the same time, the kinetics of fire does not increase the damage bone in the "element strike" when choosing one gate/
<img width="347" alt="fire " src="https://github.com/foundryvtt/pf2e/assets/144554330/e0415a3b-e267-447b-b8af-e4c0579929db">

**Comment by MrVauxs** [comment]
> Yes, this class-kineticist. Apparently I made a mistake when creating the kinetic. But at the same time, the kinetics of fire does not increase the damage bone in the "element strike" when choosing one gate/ <img alt="fire " width="347" src="https://user-images.githubusercontent.com/144554330/266798736-e0415a3b-e267-447b-b8af-e4c0579929db.png">

Did you put Elemental Blast into two actions mode? The damage increase does not affect 1 action impulses.
Also if you want to be sure you got the newest version of everything, replace existing feats and level down your Kineticist to 0 and then back to original level.
