### ISSUE TITLE
Bombs and Thrown trait

### ISSUE THREAD

**Issue by sambomb** [foundryvtt/pf2e#9990]
https://2e.aonprd.com/Rules.aspx?ID=703

An alchemical bomb combines volatile alchemical components that explode when the bomb hits a creature or object. Most alchemical bombs deal damage, though some produce other effects. Bombs have the [bomb](https://2e.aonprd.com/Traits.aspx?ID=21) trait.

Bombs are **martial thrown weapons** with a range increment of 20 feet. When you throw a bomb, you make a weapon attack roll against the target’s AC, as you would for any other weapon. It takes one hand to draw, prepare, and throw a bomb. Due to the complexity involved in preparing bombs, Strikes to throw alchemical bombs gain the [manipulate](https://2e.aonprd.com/Traits.aspx?ID=104) trait. The bomb is activated when thrown as a Strike—you don’t have to activate it separately.

Since the trait's from the bomb at the weapon list say's it Varies 
https://2e.aonprd.com/Weapons.aspx?ID=73 every bomb should inherit the Thrown trait from the Alchemical Bombs description.
That way every bomb could receive the Thrown trait to enable the correct interactions.

This is similar to the Concentrate trait been suppressed when the Verbal trait is present at spells

**Comment by stwlam** [comment]
Can you say succinctly what the concrete system issue is?

**Comment by sambomb** [comment]
> Can you say succinctly what the concrete system issue is?

All Bomb's should have the Thrown trait.

**Comment by stwlam** [comment]
If you can find a rule that states as much, we'll gladly add it. Bomb traits may vary, but that alone doesn't entail they get any particular trait other than what they say they have.

**Comment by sambomb** [comment]
https://2e.aonprd.com/Weapons.aspx?ID=73 alchemical bomb description says it's a thrown weapon, the same format of language ( use traits as adjectives ) occur at Sneak Attack 
<img width="179" alt="image" src="https://github.com/foundryvtt/pf2e/assets/244795/360de85d-5729-4f49-abfc-7037451addfb">

The splash trait https://2e.aonprd.com/Traits.aspx?ID=150  consider the alchemical bombs as thrown weapons

The use of a trait as an adjective occur in many places, just to keep the focus on the bombs, they are listed here the same way https://2e.aonprd.com/Feats.aspx?ID=95
<img width="175" alt="image" src="https://github.com/foundryvtt/pf2e/assets/244795/708afec2-fc7a-4e8c-9aae-c95dfe7e2998">

**Comment by stwlam** [comment]
Agreed: alchemical bombs are thrown martial weapons. Attack rolls with them are ranged attack rolls. But the trait?

**Comment by CarlosFdez** [comment]
More specifically, look at the actual bombs in the book. They don't have the trait.
